### ISSUE TITLE
[2.1.5+] Having WALinuxAgent installed causes Python to FTBFS due to tests failure

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#1004]
Bug in bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1534509
(Details plz see this bug)

Summary: Cannot build python package if WALA installed in the VM.

Steps:
1. Install WALA package in RHEL
2. Download python source code, run Python-2.7.5/Lib/test/test_runpy.py

Actual result:
```
test_directory_error (__main__.RunPathTest) ... 
usage: /tmp/tmpV8u4tQ [-verbose] [-force] [-help] -configuration-path:<path to configuration file>-deprovision[+user]|-register-service|-version|-daemon|-start|-run-exthandlers]

FAIL
......
FAIL: test_directory_error (__main__.RunPathTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Python-2.7.5/Lib/test/test_runpy.py", line 364, in test_directory_error
    self._check_import_error(script_dir, msg)
  File "Python-2.7.5/Lib/test/test_runpy.py", line 325, in _check_import_error
    self.assertRaisesRegexp(ImportError, msg, run_path, script_name)
AssertionError: ImportError not raised
```

Root cause:
When install WALA, it sets /usr/lib/python2.7/site-packages/__main__.py, which has global impact of python. 

Does this __main__.py necessary for WALA running? We suggest not to include __main__.py while building WALA package to avoid global impact.
And if tests/ folder is useless for WALA running, I also suggest not to put in into WALA package.

Thanks!

**Comment by boumenot** [comment]
We will investigate.

**Comment by hglkrijger** [comment]
@yuxisun1217 could you give me access to the listed bug?

**Comment by vrdmr** [comment]
@hglkrijger Did you get access to the bugzilla bug?
