### ISSUE TITLE
Azure Linux VM is having "GoalState.*.xml is missing" error

### ISSUE THREAD

**Issue by azurejon** [Azure/WALinuxAgent#1007]
My cx encounters an issue that VM’s WALinuxAgent would have the following error,

41456 ERROR Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/GoalState.11.xml is missing., duration=0
2018/01/12 18:02:23.157512 WARNING Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/GoalState.11.xml is missing.

I have tried the 2 methods as below,
(1)	Update WALinuxAgent to the latest version  Stop and Start agent service
(2)	Backup all GoalState.*.xml to another directory  Remove all GoalState.*.xml files under /var/lib/waagent/

However, the issue remains… please advise if there is anything we could do! Thanks!!

**Comment by boumenot** [comment]
This is a known issue.  Please see the [wiki for a mitigation](https://github.com/Azure/WALinuxAgent/wiki/Known-Issues#2219---protocolerror-varlibwaagentgoalstate1xml-is-missing).
