### ISSUE TITLE
distro detection

### ISSUE THREAD

**Issue by rjschwei** [Azure/WALinuxAgent#1015]
Upstream Python is deprecating platform.linux_distribution() which is used during install of the agent, and the code will disappear in Python 3.7 [1].  There is a new external module [2]. Should the agent depend on the external module? 

[1] https://docs.python.org/3.6/library/platform.html#platform.linux_distribution
[2] https://github.com/nir0s/distro#distro---a-linux-os-platform-information-api

**Comment by hglkrijger** [comment]
@rjschwei, apologies for the delay. Yes, it should - are you planning to switch the agent over to Python 3?

**Comment by rjschwei** [comment]
@hglkrijger Yes, we are switching to Python 3. For openSUSE Leap 15 and SLE 15 the default Python interpreter will be Python 3. In SLE 15 Python 2 will only be available in the "Legacy Module" which means support end two years after initial release.

**Comment by hglkrijger** [comment]
Good to know, thanks @rjschwei.

**Comment by boumenot** [comment]
Sorry for the delay on this.  We have raised this issue with the other distros to ensure there are no surprises at packaging time, and to ensure it's suitable for them too.

**Comment by boumenot** [comment]
The fix was merged.
