### ISSUE TITLE
walinuxagent 2.2.20 handler is keeping download the omsagent 1.4.58.7 but failed to disable older omsagent extension 1.4.56.5

### ISSUE THREAD

**Issue by sundaxi** [Azure/WALinuxAgent#1019]
Error message logs repeat in waagent.log looks like below. 

From guest os perspective, I could see lots of traffic was generated by waagent handler and from the waagent logs, I could see the handler is trying download/install the omsagentforlinux 1.4.58.7 but failed to disable omsagentforlinux 1.4.58.5. The operation kept failed repeatly and the omsagentfor linux extension states as "Transitioning"
```
2018/01/06 23:07:46.731983 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Target handler state: enabled
2018/01/06 23:07:46.743489 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] [Enable] current handler state is: notinstalled
2018/01/06 23:07:51.094812 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=Download succeeded, duration=0
2018/01/06 23:07:51.107818 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/06 23:07:51.121596 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Initialize extension directory
2018/01/06 23:07:51.142064 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update settings file: 0.settings
2018/01/06 23:07:51.159026 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable extension [omsagent.py -disable]
2018/01/06 23:07:51 OmsAgentForLinux started to handle.
2018/01/06 23:07:51 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] cwd is /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5
2018/01/06 23:07:51 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Change log file to /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/1.4.56.5/extension.log
2018/01/06 23:07:52.174867 ERROR Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=[ExtensionError] Non-zero exit code: 1, omsagent.py -disable, duration=0
2018/01/06 23:07:52.191380 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/06 23:07:52.291125 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Remove extension handler directory: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7
2018/01/06 23:07:55.373756 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Target handler state: enabled
2018/01/06 23:07:55.384748 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] [Enable] current handler state is: notinstalled
2018/01/06 23:08:00.278801 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=Download succeeded, duration=0
2018/01/06 23:08:00.291616 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/06 23:08:00.299439 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Initialize extension directory
2018/01/06 23:08:00.313816 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update settings file: 0.settings
2018/01/06 23:08:00.328295 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable extension [omsagent.py -disable]
```

**Comment by hglkrijger** [comment]
Please provide the contents of `/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/1.4.56.5/extension.log`

**Comment by sundaxi** [comment]
@hglkrijger Thanks for your reply.
The extension.log is huge but repeat the same errror below 
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] sequence number is 0
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5/config/0.settings
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettingsCertThumbprint": "8CB4E2939C96FC93D39D0D5439FFC60D1B9E9C95", "protectedSettings": "MIICtAYJKoZIhvcNAQcDoIICpTCCAqECAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEGTUuftXZt6mShaVoEYrS28wDQYJKoZIhvcNAQEBBQAEggEAjv9AZBZCVoSkpt4ahZzd4nfdcqGV15zB7AtTLF1e2uOFo2ImHxn7fCZJkPSBYI4Ye7pOUqQ2XFo6JhsJ2I6xrft/Vyh1uVWWSGWipXobtSUyn+CXT9Rkc3QGgOqVjFZ5t8KtPqBlinP2CxhxvIlRaCGS0zfKwOkW+OKsufvWJBQAqrBN9vsbqt4MuxDXS+jqdCXBOs6GltF+gEaRfExS9eEJok0rM0O+4ooaXNvODMWDvsMKaTDv1JSjcSW1Tjf4op+ceMa7lf7bDsHHxLr6MlAdrrr1GvJ9V4ORmlcRYl+w4woEBpMbK/+YZ7z32YfivBanvEfzImmjLoEh5xPlajCCAS0GCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIdNZV89ZkqYGAggEIoRFh2xIP48ZJKRVCWx729ODi7+t4YdGgS+YvsJP5sESrYY0FO6mP44oIoqCHdy07+LTmU8Lj5reVvF/C5peTJt2cU9mk0L7kIhVOJQFv//eNa58bCcMFGicStS+uJsnVyCNrxeBLWe2R3VDFfVGKGTXIW53zAPto5h0ufBnU34yYw7amWHjiMLVbrbbVK3palUaV4uGtdnRir+PxatCX5w0jZuXu7gMrq84sqCK33KmLIUyFi6cO/HJyMFw6AOUjer4YN/7QiumO7KK9MnUVGwDCh/vWik+eCq2A5w2gAlpnQdOJx39Fqp9idWNDSK/FG38gdZWCL2afO4vNIYhVRmFQP1CzesLY", "publicSettings": {"workspaceId": "ad9244f1-e9c7-431f-813d-5ba9e98d81fe", "azureResourceId": "/subscriptions/fe4c153a-e4be-4922-b139-a3edd6062474/resourcegroups/prestashop/providers/microsoft.compute/virtualmachines/nineeleven", "stopOnMultipleConnections": true}}}]}
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Config decoded correctly.
2018/01/25 14:19:33 ERROR:CalledProcessError.  Error Code is 1
2018/01/25 14:19:33 ERROR:CalledProcessError.  Command string was /opt/microsoft/omsagent/bin/service_control disable
2018/01/25 14:19:33 ERROR:CalledProcessError.  Command result was invoke-rc.d: unknown initscript, /etc/init.d/omsagent- not found.
2018/01/25 14:19:33 ERROR:ERROR:  disable_omsagent_service failed with result '100' on workspace ad9244f1-e9c7-431f-813d-5ba9e98d81fe.
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Output of command "/opt/microsoft/omsagent/bin/service_control disable":
2018/01/25 14:19:33 invoke-rc.d: unknown initscript, /etc/init.d/omsagent- not found.
2018/01/25 14:19:33 ERROR:  disable_omsagent_service failed with result '100' on workspace ad9244f1-e9c7-431f-813d-5ba9e98d81fe.
2018/01/25 14:19:33 ERROR:Disable failed with exit code 1
2018/01/25 14:19:33 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable failed with exit code 1
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable,failed,1,Disable failed with exit code 1
2018/01/25 14:19:43 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] sequence number is 0
2018/01/25 14:19:43 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5/config/0.settings

**Comment by hglkrijger** [comment]
It looks like the issue is with omsagent 1.4.56.5 not being installed correctly:
```
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Output of command "/opt/microsoft/omsagent/bin/service_control disable":
2018/01/25 14:19:33 invoke-rc.d: unknown initscript, /etc/init.d/omsagent- not found.
```
 You could try remove the extension directly, depending on how it is built, that may work, but for a deeper investigation you will need to follow up with the OMS team. Please file this issue at https://github.com/Microsoft/OMS-Agent-for-Linux/issues

**Comment by GarethRUK** [comment]
Just found this issue in our environment. So that's 127MB download x 10 (machines) every 10 seconds. which works out as 32TB for a month. The traffic is going across VNET peering in North Europe so has cost us around £500 a month. Ouch.

**Comment by flyinprogrammer** [comment]
Here to report this is still a bug, with no exponential backoff/retry - or obvious signals to an administrator until you implement your own out-of-band monitoring. l.o.l.

**Comment by vrdmr** [comment]
@flyinprogrammer - We are working on the fix for the extension issues. And the re-download issue has already been fixed.

ref. @larohra

**Comment by flyinprogrammer** [comment]
ok i was running v2.2.40 on bionic today, from the proposed repo, and it wouldn't stop flapping until i cleared out all the old downloads of OmsAgent. https://github.com/Azure/WALinuxAgent/issues/1393 was also an issue until i used your advice.
