### ISSUE TITLE
/var/lib/waagent directory keep growing indefinitely

### ISSUE THREAD

**Issue by gpenin** [Azure/WALinuxAgent#1020]
The /var/lib/waagent directory keep growing indefinitely with archive (zip) files and their uncompressed folders.

Is it possible to clean the /var/lib/waagent directory after OMS Agent, Extensions, etc... are installed/updated ?

**Comment by hglkrijger** [comment]
We do have logic to clean up cached files on disk, as well as telemetry events and extensions which are deleted. If an extension is in use, we leave it alone.

**Comment by enihcam** [comment]
There are many copies of previous waagent versions in /var/lib/waagent. Everytime I removed them, they came back after restart the service. Any ideas? @hglkrijger

**Comment by seeafish** [comment]
@hglkrijger would you mind elaborating on this? At present I have quite a few `run-command` directories that over the last 4-5 weeks haven't been cleaned up. At which point does it clean up after itself?
