### ISSUE TITLE
Re-implement the test case test_purge_agents

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1025]
The test case test_purge_agents is sensitive to the current version of the agent.  If the agent version is *even* the order is kept_agents/purged_agents. If the agent version is *odd* it is the opposite.

The unit tests need to be handle any version. The unit test copies data from a locally commited agent .zip, which means we have to maintain binary bits, which is also a bad practice.  It would be better if the unit tests built the version on the fly, and had a consisten way to handle guest agent versions.

**Comment by hglkrijger** [comment]
The test `test_upgrade_available_purges_old_agents` also need to be fixed. It breaks if we set a patch version, e.g. `2.2.30.1`

**Comment by vrdmr** [comment]
> The test test_upgrade_available_purges_old_agents also need to be fixed. It breaks if we set a patch version, e.g. 2.2.30.1

This is working now.

**Comment by vrdmr** [comment]
The fix is working and closing the issue.
