### ISSUE TITLE
Server Load Average 

### ISSUE THREAD

**Issue by moijafcor** [Azure/WALinuxAgent#1028]
After resizing a two core Azure's Ubuntu 16.04.03 VM, its Load average went from a 1.5% (1/5/15) to above 6% (1/5/15) and sustained `iowait `above 80%.

Tried a couple of more VM sizes, up or down, same issue. 

Everything went down to normal after` sudo service walinuxagent stop`.

![image](https://user-images.githubusercontent.com/767600/35733338-009570cc-07eb-11e8-8cb4-bcf18f9f2e9e.png)

**Comment by hglkrijger** [comment]
Which version of the agent was involved? Do you have extensions installed, and if so which ones?

**Comment by boumenot** [comment]
I am timing this issue out.  Please re-open if can supply the requested data.

**Comment by moijafcor** [comment]
No extensions AFAIK, just vanilla copy provided by Azure. OmsAgentForLinux-1.4.59.1.

Issue persists if I let the agent run (i.e. after reboots).
