### ISSUE TITLE
Deprovision user fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by mbekkelund** [Azure/WALinuxAgent#1033]
Hi. 

I have been troubleshooting this for a while now and I have found out that the newer versions of waagent/walinuxagent is failing to do "deprovision user" on Ubuntu 14.04.

I have tried several times with the old agent (2.0.5) and it works perfectly, but as soon as I run an upgrade on walinuxagent (2.2.10 and above) I end up with the following error: 

    azure-arm: 2018/02/06 13:45:16.259766 ERROR Command: 'userdel -f -r packer'
    azure-arm: 2018/02/06 13:45:16.261144 ERROR Return code: 16
    azure-arm: 2018/02/06 13:45:16.263976 ERROR Result: userdel: user packer is currently used by process 1941

This seems to be a result of the new waagent running into some problems when we do "waagent -force -deprovision+user". 

I am using packer to build images, and the only change we have done is upgrading walinuxagent.
I can get around this by skipping the "+user" part and removing the user, but I thought it would be OK to file an issue about it here aswell. This might just be an issue with userdel on Ubuntu 14.04, but nevertheless, waagent shouldn't fail like this.

**Comment by boumenot** [comment]
We test with Packer extensively, and use the deprovision+user process across all of our endorsed distros.  We do not hit this issue, so I think we are doing something differently from you.  We follow the examples templates that are in the Packer repository.

We do not consider anything prior to 2.2.10 to have good behavior.  2.0.5 is an **extremely** old version of the agent, and not considerable quality by any means.  It's so old that I think it's a typo - please confirm.  Are you sure that version isn't for CustomScript?  I checked out telemetry, and I see no agent reporting in with that version.

**Comment by mbekkelund** [comment]
With the latest available Ubuntu image I do not see this problem anymore. I suspect it to be related to userdel itself, but not going to spend more time looking into it as it works well now. Thanks for the response.
