### ISSUE TITLE
waagent fails to deploy SSH key on CentOS 7

### ISSUE THREAD

**Issue by cottsay** [Azure/WALinuxAgent#104]
Relevant excerpt from `waagent.log` after provisioning is attempted:
```
2015/08/19 12:35:10 Created user account: azureuser
2015/08/19 12:35:10 Deploy public key:28EC0E2C8F27A2A0D081742A97D517CBD1FFFFFF
2015/08/19 12:35:10 ERROR:Failed: 28EC0E2C8F27A2A0D081742A97D517CBD1FFFFFF.pub.crt -> /home/azureuser/.ssh/authorized_keys
2015/08/19 12:35:10 ERROR:CalledProcessError.  Error Code is 1
2015/08/19 12:35:10 ERROR:CalledProcessError.  Command string was chcon unconfined_u:object_r:ssh_home_t:s0 /home/azureuser/.ssh/authorized_keys
2015/08/19 12:35:10 ERROR:CalledProcessError.  Command result was chcon: cannot access /home/azureuser/.ssh/authorized_keys: No such file or directory
2015/08/19 12:35:10 ERROR:Traceback (most recent call last):
2015/08/19 12:35:10 ERROR:  File "/usr/sbin/waagent", line 6048, in main
2015/08/19 12:35:10 ERROR:    WaAgent.Run()
2015/08/19 12:35:10 ERROR:  File "/usr/sbin/waagent", line 5571, in Run
2015/08/19 12:35:10 ERROR:    provisionError = self.Provision()
2015/08/19 12:35:10 ERROR:  File "/usr/sbin/waagent", line 5457, in Provision
2015/08/19 12:35:10 ERROR:    error = ovfobj.Process()
2015/08/19 12:35:10 ERROR:  File "/usr/sbin/waagent", line 4566, in Process
2015/08/19 12:35:10 ERROR:    ChangeOwner(path, self.UserName)
2015/08/19 12:35:10 ERROR:  File "/usr/sbin/waagent", line 2242, in ChangeOwner
2015/08/19 12:35:10 ERROR:    os.chown(filepath, p[2], p[3])
2015/08/19 12:35:10 ERROR:OSError: [Errno 2] No such file or directory: '/home/azureuser/.ssh/authorized_keys'
2015/08/19 12:35:10 ERROR:
2015/08/19 12:35:10 ERROR:Exception: [Errno 2] No such file or directory: '/home/azureuser/.ssh/authorized_keys'
```

At the very least, this should not cause a crash (which prevents provisioning from completing). We shouldn't try to chcon/chown/chmod the file if we failed to create it, and even if we did, the error should be graceful.

Machine configuration: http://rpm.cottsay.net/el7.1-azure-ks.cfg

Thanks,

--scott

**EDIT**: This is using WALinuxAgent-2.0.14-1.el7 from EPEL: https://apps.fedoraproject.org/packages/WALinuxAgent

**Comment by cottsay** [comment]
Upon further investigation, I've found that this error seems to be related to the use of DSA keys (or maybe more specifically, non-RSA keys).

RSA keys seem to function as intended, and have not caused this crash in any of my tests.

This issue also seems to affect the official OpenLogic 7.1 image.

Thanks,

--scott

**Comment by hglkrijger** [comment]
@cottsay, sorry for the delay in this issue. I agree the current behavior is not graceful, and the linked commit should address that. We are replacing the 2.0.x agent in the near term with 2.1.3, which does support DSA keys. You can find it here: https://github.com/Azure/WALinuxAgent/releases/tag/v2.1.3 and information on how to upgrade here: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-update-agent/
