### ISSUE TITLE
unit test failure

### ISSUE THREAD

**Issue by rjschwei** [Azure/WALinuxAgent#1046]
The unit test "test_get_first_if()" in test_default makes an assumption about the network configuration of the system on which the unit test is being run:

self.assertTrue(ifname.startswith('eth'))

Thus this unit test necessarily fails on systems that use a bridge or systems that use predictable network interface names.

**Comment by boumenot** [comment]
Agreed.  What's the best way to fix it?  I am open to suggestions.

**Comment by rjschwei** [comment]
I would say that socket.socket() in azurelinuxagent/common/osutil/default.py shoulde be mocked to retun an expected value that delivers eth as a return value.

**Comment by boumenot** [comment]
Thank you, I will make that change for the next release.
