### ISSUE TITLE
Can't update waagent by script on Ubuntu

### ISSUE THREAD

**Issue by FabienLavocat** [Azure/WALinuxAgent#1051]
I am using an ARM Template to deploy a new Ubuntu machine. This template will run a bash script that starts by updating the machine packages system.
```
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update > /var/log/init_update.stdout 2> /var/log/init_update.stderr 
sudo apt-get -y install htop unzip default-jre vnstat
sudo apt-get -y upgrade > /var/log/init_upgrade.stdout 2> /var/log/init_upgrade.stderr 
sudo apt-get -y dist-upgrade > /var/log/init_dist_upgrade.stdout 2> /var/log/init_dist_upgrade.stderr 
sudo apt-get -y autoremove > /var/log/init_autoremove.stdout 2> /var/log/init_autoremove.stderr
```

The latest Ubuntu machine image on Azure doesn't have (yet) the latest version of the waagent package so my script will try to update it but it fails and returns the following error:

```
Preparing to unpack .../walinuxagent_2.2.21+really2.2.20-0ubuntu1~16.04.1_amd64.deb ...

debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```

My workaround is to list all the packages of the machine and update everything but waagent.

**Comment by szarkos** [comment]
Another option may be to hold the 'walinuxagent' package, upgrade and then unhold:

    apt-mark hold walinuxagent
    ... update ...
    apt-mark unhold walinuxagent

Is there a reason you are not using cloud-init to do this work vs. a script?  You can send a cloud config like the following via customdata:

    #cloud-config
    apt_upgrade: true

This would need to be base64 encoded and sent via the customData parameter as part of the osProfile.  See also this doc for more info: https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-using-cloud-init

**Comment by FabienLavocat** [comment]
Thanks @szarkos I didn't know about the `apt-mark hold` & `apt-mark unhold`, I'll try to use it from now on.

Regarding cloud-init, well, I haven't looked at it yet, I do not know anything about it, but I will check if it is something I can leverage in my deployments.

**Comment by szarkos** [comment]
Here is a sample ARM template that uses customdata for reference: https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-customdata

In this example the raw text customdata is added as a variable to the parameters.json and encoded using the base64() function in azuredeploy.json.  However, if the customdata is not changing then it may be easier to base64-encode the customdata and add it to the parameters.json directly as a string.  Just be sure to remove the base64() function in azuredeploy (don't want to base64 twice :) )

**Comment by FabienLavocat** [comment]
Thanks, that's very useful!

**Comment by hglkrijger** [comment]
Assuming this is complete
