### ISSUE TITLE
WARNING Too many files under: /var/lib/waagent/events, removing oldest

### ISSUE THREAD

**Issue by bebarb** [Azure/WALinuxAgent#1055]
Hello, 

I have an issue with the version 2.2.21 installed in FreeBSD, We have tried to reinstall the agent, however after the re-installation: 
$ waagent --version
WALinuxAgent-2.2.21 running on freebsd 11.0
Python: 2.7.12
Goal state agent: 2.2.21
$ service waagent status
waagent is not running.
$ sudo service waagent start

It seems that the process just ran for a minute and then it stopped. After try to restart the service it appears as ¨not running¨. 

Below is the error: 

2018/01/29 21:05:13 MyBackupTestLinuxInt started to handle.
2018/01/29 21:45:58.716270 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=[ExtensionError] Non-zero exit code: 127, main/handle.sh install, duration=0
2018/01/29 21:45:58.745519 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/29 21:45:58.828979 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Remove extension handler directory: /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0
2018/01/29 21:45:58.879411 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 31, duration=2002
2018/01/29 21:45:58.895692 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/29 22:44:15.359364 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing.
2018/01/29 22:44:15.378795 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing., duration=0
2018/01/29 22:44:15.401421 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/29 23:44:16.692932 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing.
2018/01/29 23:44:16.712959 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing., duration=0
2018/01/29 23:44:16.736757 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 00:44:19.597006 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing.
2018/01/30 00:44:19.616994 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing., duration=0
2018/01/30 00:44:19.639114 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 01:44:21.433760 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing.
2018/01/30 01:44:21.456474 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.31.xml is missing., duration=0
2018/01/30 01:44:21.499712 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 02:13:54.471520 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Target handler state: enabled
2018/01/30 02:13:54.494488 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] [Enable] current handler state is: notinstalled
2018/01/30 02:13:54.725307 INFO Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Download, message=Download succeeded, duration=0
2018/01/30 02:13:54.747444 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 02:13:54.762305 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Initialize extension directory
2018/01/30 02:13:54.781620 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Update settings file: 2.settings
2018/01/30 02:13:54.795929 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Install extension [main/handle.sh install]
2018/01/30 02:13:55.852354 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=[ExtensionError] Non-zero exit code: 127, main/handle.sh install, duration=0
2018/01/30 02:13:55.879901 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 02:13:55.938167 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Remove extension handler directory: /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0
2018/01/30 02:13:55.977118 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 32, duration=1928
2018/01/30 02:13:55.996566 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 02:44:23.069714 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 02:44:23.087069 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 02:44:23.112564 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 03:44:26.116336 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 03:44:26.137341 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 03:44:26.160890 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 04:44:26.146641 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 04:44:26.166791 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 04:44:26.190472 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 05:44:27.457209 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 05:44:27.474247 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 05:44:27.496987 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 06:44:29.035627 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 06:44:29.056788 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 06:44:29.079502 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 07:44:31.798761 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 07:44:31.816991 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 07:44:31.839932 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 08:44:31.937519 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 08:44:31.958319 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 08:44:31.980404 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 09:44:34.869921 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 09:44:34.888153 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 09:44:34.912329 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 10:44:35.767472 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 10:44:35.784472 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 10:44:35.807198 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 11:44:35.781761 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 11:44:35.804984 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 11:44:35.829462 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 12:44:38.375767 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 12:44:38.394628 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 12:44:38.417373 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 13:44:39.271184 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 13:44:39.288504 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 13:44:39.312624 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 14:19:15.404555 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Target handler state: enabled
2018/01/30 14:19:15.423609 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] [Enable] current handler state is: notinstalled
2018/01/30 14:19:15.690293 INFO Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Download, message=Download succeeded, duration=0
2018/01/30 14:19:15.711251 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 14:19:15.725382 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Initialize extension directory
2018/01/30 14:19:15.750222 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Update settings file: 2.settings
2018/01/30 14:19:15.768083 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Install extension [main/handle.sh install]
2018/01/30 14:19:16.826612 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=[ExtensionError] Non-zero exit code: 127, main/handle.sh install, duration=0
2018/01/30 14:19:16.851693 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 14:19:16.913762 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0] Remove extension handler directory: /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0
2018/01/30 14:44:40.766463 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing.
2018/01/30 14:44:40.786170 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.32.xml is missing., duration=0
2018/01/30 14:44:40.807728 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 15:07:31.331687 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0] Target handler state: enabled
2018/01/30 15:07:31.351556 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0] [Enable] current handler state is: notinstalled
2018/01/30 15:07:31.596477 INFO Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Download, message=Download succeeded, duration=0
2018/01/30 15:07:31.619866 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 15:07:31.634504 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0] Initialize extension directory
2018/01/30 15:07:31.653962 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0] Update settings file: 3.settings
2018/01/30 15:07:31.669718 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0] Install extension [main/handle.sh install]
2018/01/30 15:07:32.716273 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=[ExtensionError] Non-zero exit code: 127, main/handle.sh install, duration=0
2018/01/30 15:07:32.740932 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 15:07:32.805968 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0] Remove extension handler directory: /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9126.0
2018/01/30 15:07:32.853011 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 33, duration=2042
2018/01/30 15:07:32.872260 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 15:44:41.052188 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.33.xml is missing.
2018/01/30 15:44:41.072846 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.33.xml is missing., duration=0
2018/01/30 15:44:41.096637 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 16:44:43.807145 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.33.xml is missing.
2018/01/30 16:44:43.827065 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.33.xml is missing., duration=0
2018/01/30 16:44:43.848306 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 17:09:55.620068 INFO Agent WALinuxAgent-2.2.0 forwarding signal 15 to WALinuxAgent-2.2.19
2018/01/30 17:09:56.993676 INFO Azure Linux Agent Version:2.2.21
2018/01/30 17:09:57.003543 INFO OS: freebsd 11.0
2018/01/30 17:09:57.009490 INFO Python: 2.7.12
2018/01/30 17:09:57.033557 INFO Run daemon
2018/01/30 17:09:57.043439 INFO No RDMA handler exists for distro='freebsd' version='11.0'
2018/01/30 17:09:57.054641 INFO Activate resource disk
2018/01/30 17:09:57.229701 INFO Resource disk device da1 found.
2018/01/30 17:09:57.267457 INFO Resource disk partition /dev/da1s1 found.
2018/01/30 17:09:57.287733 INFO Resource disk /dev/da1s1 is already mounted
2018/01/30 17:09:57.315291 INFO Clean protocol
2018/01/30 17:09:57.327638 ERROR Command: 'dmidecode --string system-uuid'
2018/01/30 17:09:57.344871 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 17:09:57.360201 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 17:09:57.374016 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 17:09:57.386527 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 17:09:57.400278 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/30 17:09:58.946870 ERROR Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 77, in run
    self.daemon(child_args)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 123, in daemon
    self.provision_handler.run()
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 68, in run
    if self.is_provisioned():
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 178, in is_provisioned
    if not self.osutil.is_current_instance_id(s):
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py", line 270, in is_current_instance_id
    id_this = self.get_instance_id()
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py", line 289, in get_instance_id
    rc, s = shellutil.run_get_output(DMIDECODE_CMD)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/utils/shellutil.py", line 94, in run_get_output
    logger.error(u"Command: '{0}'", e.cmd)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 199, in error
    DEFAULT_LOGGER.error(msg_format, *args)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 65, in error
    self.log(LogLevel.ERROR, msg_format, *args)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 87, in log
    appender.write(level, log_item)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 145, in write
    self.event_func(level, msg)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/event.py", line 301, in add_log_event
    reporter.add_log_event(level, message)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/event.py", line 248, in add_log_event
    self.save_event(json.dumps(data))
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/event.py", line 158, in save_event
    logger.warn("Too many files under: {0}, removing oldest".format(self.event_dir))
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 195, in warn
    DEFAULT_LOGGER.warn(msg_format, *args)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 62, in warn
    self.log(LogLevel.WARNING, msg_format, *args)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 87, in log
    appender.write(level, log_item)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/logger.py", line 145, in write
    self.event_func(level, msg)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/event.py", line 301, in add_log_event
    reporter.add_log_event(level, message)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/event.py", line 248, in add_log_event
    self.save_event(json.dumps(data))
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/event.py", line 158, in save_event

Attached is an extract of the complete log, since the file is too large and the error is recurrent. 

[Last three days.txt](https://github.com/Azure/WALinuxAgent/files/1776028/Last.three.days.txt)

Thanks, 

Bernal.

**Comment by boumenot** [comment]
Sorry, we do not officially support FreeBSD.  The official list is in the README of the repo.

The errors in your log are indicative of a [Known Issue that was posted on the wiki](https://github.com/Azure/WALinuxAgent/wiki/Known-Issues) for 2.2.19, but the errors that I see in your log don't really match the title.

The error in your title indicates that there are too many files, and the agent has given up.  There was an issue in 2.2.21 that was hot fixed to address this.  I recommend you either upgrade to 2.2.22 (if possible), or delete all of the files under /var/lib/waagent/events/*.tld.  (I assume the path is the same on FreeBSD, but I do not know.)
