### ISSUE TITLE
Issues with Linux Azure Backup

### ISSUE THREAD

**Issue by quicktechvan** [Azure/WALinuxAgent#1059]
I have been running successful Linux backups for the better part of a month, when on the 20th of February they have started failing
I am receiving an error in the portal for the pre-check
Could not communicate with the VM agent for snapshot status - Snapshot VM sub task timed out
I am receiving an error after 1 hours and 35 minute backup in progress
Could not communicate with the VM agent for snapshot status.

Here is a tail of the wagent.log file
2018/03/05 14:31:57.742721 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9120.0] Target handler state: enabled
2018/03/05 14:31:57.745038 ERROR [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9120.0] Failed to save handler status: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9120.0/config/HandlerStatus'
2018/03/05 14:31:57.747218 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=None, message=[ExtensionError] Downgrade not allowed, duration=0

I am unaware of how to reinstall the extension as the KB article states, there is no extension installed to uninstall nor is there one available to install

here is the waagent version

WALinuxAgent-2.2.22 running on ubuntu 14.04
Python: 2.7.6
Goal state agent: 2.2.22

Hopefully someone can help.

**Comment by boumenot** [comment]
/cc: @soumyapattnaik - are there any instructions you can provide above and beyond the KB?

**Comment by Mangaleshwar** [comment]
@quicktechvan 

Please provide the output of below command.

# ls -l /var/log/azure/Microsoft.Azure.RecoveryServices.VMSnapshotLinux

Please try below steps, where we are removing the extension from the VM manually. 

	o # sudo rm -f /var/lib/waagent/*.[0-9]*.xml 
	o # systemctl stop waagent 
	o # mkdir /tmp/SnapshotExt_backup 
	o # cd /var/lib/waagent 
	o # mv Microsoft.Azure.RecoveryServices* /tmp/SnapshotExt_backup/ 
	o # mv  Microsoft.Azure.RecoveryServices__VMSnapshotLinux* /tmp/SnapshotExt_backup/ 
	o # mv Microsoft.Azure.RecoveryServices.VMSnapshotLinux-* /tmp/SnapshotExt_backup/ 
	o # cd /var/lib/waagent --> make sure there are no files/directories related to Snapshot extension 
	o # cd /var/log/azure/ 
	o # rm -rf Microsoft.Azure.RecoveryServices.VMSnapshotLinux --> be extra cautious while executing rm -rf commands 
	o # systemctl start waagent 
	o # systemctl status waagent --> confirm if waagent is running 

Once waagent is running, go ahead and start backup now. This will now install the latest version of snapshot extension and since the XML files of the older snapshot versions are removed, there will not be any version mismatch errors.

Let us know if you face the backup issue even after performing above steps.

**Comment by quicktechvan** [comment]
ls -l /var/log/azure/Microsoft.Azure.RecoveryServices.VMSnapshotLinux
total 28
drwxr-xr-x 2 root root 4096 Sep 21 10:13 1.0.9120.0
drwxr-xr-x 2 root root 4096 Nov  7 00:26 1.0.9121.0
drwxr-xr-x 2 root root 4096 Nov 13 03:28 1.0.9123.0
drwxr-xr-x 2 root root 4096 Nov 24 09:29 1.0.9124.0
drwxr-xr-x 2 root root 4096 Feb  5 13:38 1.0.9126.0
drwxr-xr-x 2 root root 4096 Feb 16 20:44 1.0.9127.0
drwxr-xr-x 2 root root 4096 Mar  5 11:33 1.0.9128.0

With Ubuntu 14.04 I needed to start and stop the service with initctl stop walinuxagent and start with initctl start walinuxagent

I have started my first backup since following your steps, I will update you if it is successful.

**Comment by Mangaleshwar** [comment]
Thanks for the update @quicktechvan 

@boumenot, Requesting your assistance to understand why the waagent picks up the older version even when the VM has the latest version of snapshot extension.

**Comment by boumenot** [comment]
This issue was kept open for @soumyapattnaik to provide support on a KB article.  The issue has now pivoted to the downgrade issue, which is being tracked separately, so I see no need to keep this issue open.

**Comment by jeromeza** [comment]
I've had the same issue with RHEL6 + Ubuntu 14.04 machines. I can confirm that the fix suggest by @Mangaleshwar worked for me too. Thanks.

**Comment by alexandreweiss** [comment]
Hi guys,
Could you please share the location of the downgrade issue bug tracking
I created (perhaps duplicate) issue here : https://github.com/Azure/azure-linux-extensions/issues/552

**Comment by BigDaddyTurbo** [comment]
Hi,

I'm having a similar problem with one of my Linux VMs.  Have tried the solution above but it seems to have a problem installing the correct agents.  This is from the /var/log/waagent.log

2018/04/27 13:02:32.029794 INFO Azure Linux Agent Version:2.2.20
2018/04/27 13:02:32.031674 INFO OS: ubuntu 14.04
2018/04/27 13:02:32.038098 INFO Python: 3.4.3
2018/04/27 13:02:32.039667 INFO Run daemon
2018/04/27 13:02:32.047234 INFO Clean protocol
2018/04/27 13:02:32.049287 INFO Provisioning already completed, skipping.
2018/04/27 13:02:32.056585 INFO RDMA capabilities are not enabled, skipping
2018/04/27 13:02:32.058266 INFO Installed Agent WALinuxAgent-2.2.20 is the most current agent
2018/04/27 13:02:32.351816 INFO Agent WALinuxAgent-2.2.20 is running as the goal state agent
2018/04/27 13:02:32.374606 INFO Detect protocol endpoints
2018/04/27 13:02:32.379772 INFO Clean protocol
2018/04/27 13:02:32.381287 INFO WireServer endpoint is not found. Rerun dhcp handler
2018/04/27 13:02:32.382803 INFO Test for route to X.X.X.X
2018/04/27 13:02:32.390017 INFO Route to X.X.X.X exists
2018/04/27 13:02:32.391401 INFO Wire server endpoint:X.X.X.X
2018/04/27 13:02:32.410697 INFO Fabric preferred wire protocol version:2015-04-05
2018/04/27 13:02:32.412436 INFO Wire protocol version:2012-11-30
2018/04/27 13:02:32.419208 WARNING Server preferred version:2015-04-05
2018/04/27 13:02:32.788637 INFO Start env monitor service.
2018/04/27 13:02:32.790765 INFO Configure routes
2018/04/27 13:02:32.799196 INFO Gateway:None
2018/04/27 13:02:32.800499 INFO Routes:None
2018/04/27 13:02:32.808618 INFO Event: name=WALinuxAgent, op=HeartBeat, message=94;0;BFC75363-B4CE-43F8-A85E-53981F9B25E0;0, duration=0
2018/04/27 13:02:32.847095 INFO WALinuxAgent-2.2.20 running as process 10939
2018/04/27 13:02:32.847312 INFO Wire server endpoint:X.X.X.X
2018/04/27 13:02:32.859079 INFO Wire server endpoint:X.X.X.X
2018/04/27 13:02:32.869137 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2018/04/27 13:02:32.879016 INFO Wire server endpoint:X.X.X.X
2018/04/27 13:02:32.886121 INFO Purging disk cache, current incarnation is 94
2018/04/27 13:02:32.918658 INFO [Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4] Target handler state: enabled
2018/04/27 13:02:32.919879 INFO [Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4] [Enable] current handler state is: notinstalled
2018/04/27 13:02:35.004903 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent, op=Download, message=Download succeeded, duration=0
2018/04/27 13:02:35.008437 INFO [Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4] Initialize extension directory
2018/04/27 13:02:35.015676 INFO [Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4] Update settings file: 0.settings
2018/04/27 13:02:35.016855 INFO [Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4] Install extension [MMAExtensionInstall.exe]
**2018/04/27 13:02:36.027573 ERROR Event: name=Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent, op=Install, message=[ExtensionError] Non-zero exit code: 2, MMAExtensionInstall.exe, duration=0
2018/04/27 13:02:36.063064 INFO [Microsoft.Azure.RecoveryServices.VMSnapshot-1.0.42.0] Target handler state: enabled
2018/04/27 13:02:36.064740 INFO [Microsoft.Azure.RecoveryServices.VMSnapshot-1.0.42.0] [Enable] current handler state is: notinstalled
2018/04/27 13:02:36.607803 INFO Event: name=Microsoft.Azure.RecoveryServices.VMSnapshot, op=Download, message=Download succeeded, duration=0
2018/04/27 13:02:36.609517 INFO [Microsoft.Azure.RecoveryServices.VMSnapshot-1.0.42.0] Initialize extension directory
2018/04/27 13:02:36.627230 INFO [Microsoft.Azure.RecoveryServices.VMSnapshot-1.0.42.0] Update settings file: 0.settings
2018/04/27 13:02:36.646135 INFO [Microsoft.Azure.RecoveryServices.VMSnapshot-1.0.42.0] Install extension [Scripts\install.cmd]
2018/04/27 13:02:37.651517 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshot, op=Install, message=[ExtensionError] Non-zero exit code: 127, Scripts\install.cmd, duration=0**
2018/04/27 13:02:37.760032 INFO [Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4] Remove extension handler directory: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4
2018/04/27 13:02:37.796682 INFO [Microsoft.Azure.RecoveryServices.VMSnapshot-1.0.42.0] Remove extension handler directory: /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshot-1.0.42.0
2018/04/27 13:02:37.807558 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 94, duration=4928

When I look at the extensions associated with this Linux VM there are only two listed; MicrosoftMonitoringAgent and VMSnapshot.  Both of which have a status of 'Unavailable'.  I've uninstalled the VMsnapshot from the Extensions screen but to no avail.

I can see this thread is referring to the Microsoft.Azure.RecoveryServices.VMSnapshot**Linux** extension.  The extension on my VM doesn't have this Linux suffix.

Can anyone help?

**Comment by boumenot** [comment]
Do you realize you are running a Windows extension on a Linux VM?

```text
[Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent-1.0.11081.4] Install extension [MMAExtensionInstall.exe]
```

I am hella confused too because if this is a Linux VM you should be running VMSnapshotLinux not VMSnapshot.

Unfortunately, the platform does not protect you from installing a Windows extension on a Linux VM even though it is doomed to fail. ☹️ We are trying to correct that **glaring** mistake.

**Comment by BigDaddyTurbo** [comment]
I do. But this is what the VM is pulling down, no?

The question is...why is the waagent trying to pull the MS executable?

**Comment by BigDaddyTurbo** [comment]
So how do you tell the agent to install the Linux agent and not the Windows one?

Currently the extensions against this VM show:

![image](https://user-images.githubusercontent.com/38787486/39378883-8a3158f2-4a51-11e8-96e5-0cdffc351307.png)

I followed these instructions:

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/update-agent

That seemed to update the agent.  I would have thought when I updated the agent and started a backup it would install the snapshotlinux extension, no?

I'm verse with Linux but new to Azure.  A friend of mine has this problem (he's a Windows guy) and has asked me to help.

**Comment by boumenot** [comment]
The referenced document is about updating the agent not these extensions.  I do not see the relevance between the two issues.

Someone (or thing) installed Windows extensions on a Linux VM.  This will need to be undone, and if you want the functionality of these extensions you will need to install the Linux flavors of them (if they exist).  Sorry, I do not have any knowledge of where to get these or how to install them.  This repository is for the Linux agent only.  I recommend you reach out to Azure support for assistance.

**Comment by BigDaddyTurbo** [comment]
No worries.  I'll keep digging.  Thanks for the assistance.

**Comment by atul-ram** [comment]
The above said exit code:126 could happen while the “/var” filesystem is mounted with “noexec” property where extension installation could not execute.

Action plan:
To mount the “/var” filesystem with execute permissions
1. edit /etc/fstab and set exec instead of noexec for “/var”
2. remount /var using 'mount -o remount /var' and now I can see it is mounted without noexec in mount and /etc/mtab

After following the above steps, we could initiate the backup which installed the extension successfully and the snapshot step succeeded
