### ISSUE TITLE
OMI Restarted But Not Staying Up. Will Be Restarted In The Next Iteration.

### ISSUE THREAD

**Issue by sweigand** [Azure/WALinuxAgent#1060]
Had a weird issue start yesterday (March 8, 2018) on my CentOS7-based VM: WAAgent started spitting out "diagnostic.py[21347]: OMI restarted but not staying up. Will be restarted in the next iteration."

 OMI looks fine and is started and running.

**Comment by boumenot** [comment]
This repository is for the Linux guest agent, and does not cover OMS agent.  Please contact Azure support or open an issue against the OMS [repository](https://github.com/Azure/azure-linux-extensions/tree/master/OmsAgent).
