### ISSUE TITLE
walinuxagent issues for credativ:Debian:9:9.0.201803020 image

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/WALinuxAgent#1064]
hello, all!

I have two issues with walinuxagent for credativ:Debian:9:9.0.201803020 image:

1)
when I run 'sudo waagent -deprovision+user -force' I got the following messages:
userdel: user azureuser is currently used by process 635
userdel: azureuser mail spool (/var/mail/azureuser) not found

azureuser@debian-std-prepare:~$ ps -ef | grep 635
1000        635      1  0 13:42 ?        00:00:00 /lib/systemd/systemd --user
1000        636    635  0 13:42 ?        00:00:00 (sd-pam)
1000        741    641  0 13:45 pts/0    00:00:00 grep 635

2)
if I have default Provisioning.RegenerateSshHostKeyPair=y in /etc/waagent.conf
I cannot create VM from VHD
if I change it to Provisioning.RegenerateSshHostKeyPair=n
VM is successfully created from VHD

**Comment by boumenot** [comment]
1. What is the process associated with 635?  I would expect the user to not be running anything other than the shell.
 1. I would expect this value to have any effect on image generation.  Please provide logs for the provisioning process.  This may give insight into why it is not working.

**Comment by alexeyshishkin01** [comment]
1. What is the process associated with 635? I would expect the user to not be running anything other than the shell.
- pls. see my message above

2. I would expect this value to have any effect on image generation. Please provide logs for the provisioning process. This may give insight into why it is not working.
- unfortunately I don't have logs anymore since the issue was open almost a month ago
- but you see the process to reproduce the issue is easy and straightforward

**Comment by boumenot** [comment]
I saw the message above, and it did not answer my question, which is why I asked it.

We deploy Debian 9 images many times per day to validate the Linux guest agent.  The process is

 1. Deploy the VM.
 1. Install the latest build of the agent
 1. Deprovision the image
 1. Capture the image
 1. Deploy the captured image

We do not see this issue.  I am not sure what we are doing differently.  If you have logs, please re-open and attach the logs.

**Comment by alexeyshishkin01** [comment]
here's a console screen which shows an issue:

root@Alexey-HP:~#
root@Alexey-HP:~# az group create \
> --name debianresourcegroup \
> --location northeurope
Location     Name
-----------  -------------------
northeurope  debianresourcegroup
root@Alexey-HP:~#
root@Alexey-HP:~#
root@Alexey-HP:~# az vm create \
> --name debian-std-prepare \
> --resource-group debianresourcegroup \
> --image credativ:Debian:9:9.0.201803020 \
> --location northeurope \
> --size Standard_DS1 \
> --ssh-key-value ~/.ssh/id_rsa.pub \
> --admin-username azureuser \
> --authentication-type ssh \
> --public-ip-address-dns-name debian-std-prepare-dnsname \
> --os-disk-name debian-std-prepare-osdisk \
> --storage-sku Standard_LRS
ResourceGroup        PowerState    PublicIpAddress    Fqdns                                                      PrivateIpAddress    MacAddress         Location
-------------------  ------------  -----------------  ---------------------------------------------------------  ------------------  -----------------  -----------
debianresourcegroup  VM running    13.79.185.231      debian-std-prepare-dnsname.northeurope.cloudapp.azure.com  10.0.0.4            00-0D-3A-B3-A7-86  northeurope
root@Alexey-HP:~# rm -rf ~/.ssh/known_hosts
root@Alexey-HP:~# ssh azureuser@debian-std-prepare-dnsname.northeurope.cloudapp.azure.com
The authenticity of host 'debian-std-prepare-dnsname.northeurope.cloudapp.azure.com (13.79.185.231)' can't be established.
RSA key fingerprint is c5:48:25:f0:1c:46:a0:32:41:eb:f3:9a:fd:dc:9e:7b.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'debian-std-prepare-dnsname.northeurope.cloudapp.azure.com,13.79.185.231' (RSA) to the list of known hosts.
Linux debian-std-prepare 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
azureuser@debian-std-prepare:~$ wa
wait        wall        watch       watchgnupg
azureuser@debian-std-prepare:~$ vi /lib/systemd/system/walinuxagent.service
azureuser@debian-std-prepare:~$ /usr/sbin/waagent --version
WALinuxAgent-2.2.14 running on debian 9.3
Python: 3.5.3
Goal state agent: b'2.2.25'
azureuser@debian-std-prepare:~$ sudo apt-get update && sudo apt-get -y upgrade
Ign:1 http://debian-archive.trafficmanager.net/debian stretch InRelease
Hit:2 http://debian-archive.trafficmanager.net/debian-security stretch/updates InRelease
Hit:3 http://debian-archive.trafficmanager.net/debian stretch-updates InRelease
Hit:4 http://debian-archive.trafficmanager.net/debian stretch-backports InRelease
Hit:5 http://debian-archive.trafficmanager.net/debian stretch Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  base-files bsdutils cron dbus isc-dhcp-client isc-dhcp-common libapparmor1 libblkid1 libc-bin libc-l10n libc6 libdbus-1-3 libfdisk1 libicu57
  libmount1 libncurses5 libncursesw5 libpam-systemd libsmartcols1 libssl1.0.2 libssl1.1 libsystemd0 libtinfo5 libudev1 libuuid1
  linux-image-4.9.0-6-amd64 locales-all mount multiarch-support ncurses-base ncurses-bin openssh-client openssh-server openssh-sftp-server openssl
  systemd systemd-sysv tzdata udev util-linux waagent
41 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 68.2 MB of archives.
After this operation, 56.3 kB of additional disk space will be used.
Get:1 http://debian-archive.trafficmanager.net/debian stretch/main amd64 base-files amd64 9.9+deb9u4 [67.3 kB]
Get:2 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 bsdutils amd64 1:2.29.2-1+deb9u1 [112 kB]
Get:3 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 util-linux amd64 2.29.2-1+deb9u1 [981 kB]
Get:4 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 mount amd64 2.29.2-1+deb9u1 [189 kB]
Get:5 http://debian-archive.trafficmanager.net/debian stretch/main amd64 ncurses-bin amd64 6.0+20161126-1+deb9u2 [366 kB]
Get:6 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libc6 amd64 2.24-11+deb9u3 [2,693 kB]
Get:7 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libc-bin amd64 2.24-11+deb9u3 [779 kB]
Get:8 http://debian-archive.trafficmanager.net/debian stretch/main amd64 ncurses-base all 6.0+20161126-1+deb9u2 [238 kB]
Get:9 http://debian-archive.trafficmanager.net/debian stretch/main amd64 dbus amd64 1.10.26-0+deb9u1 [210 kB]
Get:10 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libdbus-1-3 amd64 1.10.26-0+deb9u1 [194 kB]
Get:11 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libapparmor1 amd64 2.11.0-3+deb9u2 [78.9 kB]
Get:12 http://debian-archive.trafficmanager.net/debian stretch-updates/main amd64 systemd-sysv amd64 232-25+deb9u3 [81.1 kB]
Get:13 http://debian-archive.trafficmanager.net/debian stretch-updates/main amd64 libpam-systemd amd64 232-25+deb9u3 [188 kB]
Get:14 http://debian-archive.trafficmanager.net/debian stretch-updates/main amd64 libsystemd0 amd64 232-25+deb9u3 [280 kB]
Get:15 http://debian-archive.trafficmanager.net/debian stretch-updates/main amd64 systemd amd64 232-25+deb9u3 [2,468 kB]
Get:16 http://debian-archive.trafficmanager.net/debian stretch-updates/main amd64 udev amd64 232-25+deb9u3 [1,114 kB]
Get:17 http://debian-archive.trafficmanager.net/debian stretch-updates/main amd64 libudev1 amd64 232-25+deb9u3 [125 kB]
Get:18 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libuuid1 amd64 2.29.2-1+deb9u1 [70.1 kB]
Get:19 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libblkid1 amd64 2.29.2-1+deb9u1 [168 kB]
Get:20 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libmount1 amd64 2.29.2-1+deb9u1 [178 kB]
Get:21 http://debian-archive.trafficmanager.net/debian stretch/main amd64 cron amd64 3.0pl1-128+deb9u1 [95.4 kB]
Get:22 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libfdisk1 amd64 2.29.2-1+deb9u1 [203 kB]
Get:23 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libsmartcols1 amd64 2.29.2-1+deb9u1 [126 kB]
Get:24 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libncurses5 amd64 6.0+20161126-1+deb9u2 [93.4 kB]
Get:25 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libtinfo5 amd64 6.0+20161126-1+deb9u2 [300 kB]
Get:26 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libncursesw5 amd64 6.0+20161126-1+deb9u2 [115 kB]
Get:27 http://debian-archive.trafficmanager.net/debian stretch/main amd64 multiarch-support amd64 2.24-11+deb9u3 [200 kB]
Get:28 http://debian-archive.trafficmanager.net/debian stretch-updates/main amd64 tzdata all 2018d-0+deb9u1 [266 kB]
Get:29 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 isc-dhcp-client amd64 4.3.5-3+deb9u1 [325 kB]
Get:30 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 isc-dhcp-common amd64 4.3.5-3+deb9u1 [136 kB]
Get:31 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libssl1.0.2 amd64 1.0.2l-2+deb9u3 [1,294 kB]
Get:32 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libssl1.1 amd64 1.1.0f-3+deb9u2 [1,344 kB]
Get:33 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libc-l10n all 2.24-11+deb9u3 [820 kB]
Get:34 http://debian-archive.trafficmanager.net/debian stretch/main amd64 openssh-sftp-server amd64 1:7.4p1-10+deb9u3 [39.5 kB]
Get:35 http://debian-archive.trafficmanager.net/debian stretch/main amd64 openssh-server amd64 1:7.4p1-10+deb9u3 [332 kB]
Get:36 http://debian-archive.trafficmanager.net/debian stretch/main amd64 openssh-client amd64 1:7.4p1-10+deb9u3 [779 kB]
Get:37 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 libicu57 amd64 57.1-6+deb9u2 [7,700 kB]
Get:38 http://debian-archive.trafficmanager.net/debian stretch/main amd64 linux-image-4.9.0-6-amd64 amd64 4.9.82-1+deb9u3 [39.0 MB]
Get:39 http://debian-archive.trafficmanager.net/debian-security stretch/updates/main amd64 openssl amd64 1.1.0f-3+deb9u2 [725 kB]
Get:40 http://debian-archive.trafficmanager.net/debian stretch/main amd64 locales-all amd64 2.24-11+deb9u3 [3,624 kB]
Get:41 http://debian-archive.trafficmanager.net/debian stretch/main amd64 waagent all 2.2.18-3~deb9u1 [103 kB]
Fetched 68.2 MB in 7s (8,567 kB/s)
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../base-files_9.9+deb9u4_amd64.deb ...
Unpacking base-files (9.9+deb9u4) over (9.9+deb9u3) ...
Setting up base-files (9.9+deb9u4) ...
Installing new version of config file /etc/debian_version ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../bsdutils_1%3a2.29.2-1+deb9u1_amd64.deb ...
Unpacking bsdutils (1:2.29.2-1+deb9u1) over (1:2.29.2-1) ...
Setting up bsdutils (1:2.29.2-1+deb9u1) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../util-linux_2.29.2-1+deb9u1_amd64.deb ...
Unpacking util-linux (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up util-linux (2.29.2-1+deb9u1) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../mount_2.29.2-1+deb9u1_amd64.deb ...
Unpacking mount (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up mount (2.29.2-1+deb9u1) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../ncurses-bin_6.0+20161126-1+deb9u2_amd64.deb ...
Unpacking ncurses-bin (6.0+20161126-1+deb9u2) over (6.0+20161126-1+deb9u1) ...
Setting up ncurses-bin (6.0+20161126-1+deb9u2) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../libc6_2.24-11+deb9u3_amd64.deb ...
Unpacking libc6:amd64 (2.24-11+deb9u3) over (2.24-11+deb9u1) ...
Setting up libc6:amd64 (2.24-11+deb9u3) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../libc-bin_2.24-11+deb9u3_amd64.deb ...
Unpacking libc-bin (2.24-11+deb9u3) over (2.24-11+deb9u1) ...
Setting up libc-bin (2.24-11+deb9u3) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../ncurses-base_6.0+20161126-1+deb9u2_all.deb ...
Unpacking ncurses-base (6.0+20161126-1+deb9u2) over (6.0+20161126-1+deb9u1) ...
Setting up ncurses-base (6.0+20161126-1+deb9u2) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../0-dbus_1.10.26-0+deb9u1_amd64.deb ...
Unpacking dbus (1.10.26-0+deb9u1) over (1.10.24-0+deb9u1) ...
Preparing to unpack .../1-libdbus-1-3_1.10.26-0+deb9u1_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.10.26-0+deb9u1) over (1.10.24-0+deb9u1) ...
Preparing to unpack .../2-libapparmor1_2.11.0-3+deb9u2_amd64.deb ...
Unpacking libapparmor1:amd64 (2.11.0-3+deb9u2) over (2.11.0-3) ...
Preparing to unpack .../3-systemd-sysv_232-25+deb9u3_amd64.deb ...
Unpacking systemd-sysv (232-25+deb9u3) over (232-25+deb9u1) ...
Preparing to unpack .../4-libpam-systemd_232-25+deb9u3_amd64.deb ...
Unpacking libpam-systemd:amd64 (232-25+deb9u3) over (232-25+deb9u1) ...
Preparing to unpack .../5-libsystemd0_232-25+deb9u3_amd64.deb ...
Unpacking libsystemd0:amd64 (232-25+deb9u3) over (232-25+deb9u1) ...
Setting up libsystemd0:amd64 (232-25+deb9u3) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../systemd_232-25+deb9u3_amd64.deb ...
Unpacking systemd (232-25+deb9u3) over (232-25+deb9u1) ...
Preparing to unpack .../udev_232-25+deb9u3_amd64.deb ...
Unpacking udev (232-25+deb9u3) over (232-25+deb9u1) ...
Preparing to unpack .../libudev1_232-25+deb9u3_amd64.deb ...
Unpacking libudev1:amd64 (232-25+deb9u3) over (232-25+deb9u1) ...
Setting up libudev1:amd64 (232-25+deb9u3) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../libuuid1_2.29.2-1+deb9u1_amd64.deb ...
Unpacking libuuid1:amd64 (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up libuuid1:amd64 (2.29.2-1+deb9u1) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../libblkid1_2.29.2-1+deb9u1_amd64.deb ...
Unpacking libblkid1:amd64 (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up libblkid1:amd64 (2.29.2-1+deb9u1) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../libmount1_2.29.2-1+deb9u1_amd64.deb ...
Unpacking libmount1:amd64 (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up libmount1:amd64 (2.29.2-1+deb9u1) ...
(Reading database ... 25496 files and directories currently installed.)
Preparing to unpack .../cron_3.0pl1-128+deb9u1_amd64.deb ...
Unpacking cron (3.0pl1-128+deb9u1) over (3.0pl1-128+b1) ...
Preparing to unpack .../libfdisk1_2.29.2-1+deb9u1_amd64.deb ...
Unpacking libfdisk1:amd64 (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up libfdisk1:amd64 (2.29.2-1+deb9u1) ...
(Reading database ... 25495 files and directories currently installed.)
Preparing to unpack .../libsmartcols1_2.29.2-1+deb9u1_amd64.deb ...
Unpacking libsmartcols1:amd64 (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up libsmartcols1:amd64 (2.29.2-1+deb9u1) ...
(Reading database ... 25495 files and directories currently installed.)
Preparing to unpack .../libncurses5_6.0+20161126-1+deb9u2_amd64.deb ...
Unpacking libncurses5:amd64 (6.0+20161126-1+deb9u2) over (6.0+20161126-1+deb9u1) ...
Preparing to unpack .../libtinfo5_6.0+20161126-1+deb9u2_amd64.deb ...
Unpacking libtinfo5:amd64 (6.0+20161126-1+deb9u2) over (6.0+20161126-1+deb9u1) ...
Setting up libtinfo5:amd64 (6.0+20161126-1+deb9u2) ...
(Reading database ... 25495 files and directories currently installed.)
Preparing to unpack .../libncursesw5_6.0+20161126-1+deb9u2_amd64.deb ...
Unpacking libncursesw5:amd64 (6.0+20161126-1+deb9u2) over (6.0+20161126-1+deb9u1) ...
Setting up libncursesw5:amd64 (6.0+20161126-1+deb9u2) ...
(Reading database ... 25495 files and directories currently installed.)
Preparing to unpack .../multiarch-support_2.24-11+deb9u3_amd64.deb ...
Unpacking multiarch-support (2.24-11+deb9u3) over (2.24-11+deb9u1) ...
Setting up multiarch-support (2.24-11+deb9u3) ...
(Reading database ... 25495 files and directories currently installed.)
Preparing to unpack .../00-tzdata_2018d-0+deb9u1_all.deb ...
Unpacking tzdata (2018d-0+deb9u1) over (2018c-0+deb9u1) ...
Preparing to unpack .../01-isc-dhcp-client_4.3.5-3+deb9u1_amd64.deb ...
Unpacking isc-dhcp-client (4.3.5-3+deb9u1) over (4.3.5-3) ...
Preparing to unpack .../02-isc-dhcp-common_4.3.5-3+deb9u1_amd64.deb ...
Unpacking isc-dhcp-common (4.3.5-3+deb9u1) over (4.3.5-3) ...
Preparing to unpack .../03-libssl1.0.2_1.0.2l-2+deb9u3_amd64.deb ...
Unpacking libssl1.0.2:amd64 (1.0.2l-2+deb9u3) over (1.0.2l-2+deb9u2) ...
Preparing to unpack .../04-libssl1.1_1.1.0f-3+deb9u2_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.0f-3+deb9u2) over (1.1.0f-3+deb9u1) ...
Preparing to unpack .../05-libc-l10n_2.24-11+deb9u3_all.deb ...
Unpacking libc-l10n (2.24-11+deb9u3) over (2.24-11+deb9u1) ...
Preparing to unpack .../06-openssh-sftp-server_1%3a7.4p1-10+deb9u3_amd64.deb ...
Unpacking openssh-sftp-server (1:7.4p1-10+deb9u3) over (1:7.4p1-10+deb9u2) ...
Preparing to unpack .../07-openssh-server_1%3a7.4p1-10+deb9u3_amd64.deb ...
Unpacking openssh-server (1:7.4p1-10+deb9u3) over (1:7.4p1-10+deb9u2) ...
Preparing to unpack .../08-openssh-client_1%3a7.4p1-10+deb9u3_amd64.deb ...
Unpacking openssh-client (1:7.4p1-10+deb9u3) over (1:7.4p1-10+deb9u2) ...
Preparing to unpack .../09-libicu57_57.1-6+deb9u2_amd64.deb ...
Unpacking libicu57:amd64 (57.1-6+deb9u2) over (57.1-6+deb9u1) ...
Preparing to unpack .../10-linux-image-4.9.0-6-amd64_4.9.82-1+deb9u3_amd64.deb ...
Unpacking linux-image-4.9.0-6-amd64 (4.9.82-1+deb9u3) over (4.9.82-1+deb9u2) ...
Preparing to unpack .../11-openssl_1.1.0f-3+deb9u2_amd64.deb ...
Unpacking openssl (1.1.0f-3+deb9u2) over (1.1.0f-3+deb9u1) ...
Preparing to unpack .../12-locales-all_2.24-11+deb9u3_amd64.deb ...
Unpacking locales-all (2.24-11+deb9u3) over (2.24-11+deb9u1) ...
Preparing to unpack .../13-waagent_2.2.18-3~deb9u1_all.deb ...
Unpacking waagent (2.2.18-3~deb9u1) over (2.2.14-1~deb9u1) ...
Setting up libncurses5:amd64 (6.0+20161126-1+deb9u2) ...
Processing triggers for mime-support (3.60) ...
Setting up isc-dhcp-common (4.3.5-3+deb9u1) ...
Setting up tzdata (2018d-0+deb9u1) ...

Current default time zone: 'Etc/UTC'
Local time is now:      Thu Apr  5 12:21:54 UTC 2018.
Universal Time is now:  Thu Apr  5 12:21:54 UTC 2018.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up libicu57:amd64 (57.1-6+deb9u2) ...
Setting up isc-dhcp-client (4.3.5-3+deb9u1) ...
Setting up libssl1.0.2:amd64 (1.0.2l-2+deb9u3) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Setting up udev (232-25+deb9u3) ...
addgroup: The group `input' already exists as a system group. Exiting.
update-initramfs: deferring update (trigger activated)
Setting up libapparmor1:amd64 (2.11.0-3+deb9u2) ...
Setting up libssl1.1:amd64 (1.1.0f-3+deb9u2) ...
Setting up libc-l10n (2.24-11+deb9u3) ...
Setting up systemd (232-25+deb9u3) ...
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
Setting up openssl (1.1.0f-3+deb9u2) ...
Setting up openssh-client (1:7.4p1-10+deb9u3) ...
Setting up cron (3.0pl1-128+deb9u1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Setting up libdbus-1-3:amd64 (1.10.26-0+deb9u1) ...
Setting up linux-image-4.9.0-6-amd64 (4.9.82-1+deb9u3) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-4.9.0-6-amd64
/etc/kernel/postinst.d/zz-update-grub:
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.9.0-6-amd64
Found initrd image: /boot/initrd.img-4.9.0-6-amd64
done
Setting up systemd-sysv (232-25+deb9u3) ...
Setting up locales-all (2.24-11+deb9u3) ...
Setting up openssh-sftp-server (1:7.4p1-10+deb9u3) ...
Setting up dbus (1.10.26-0+deb9u1) ...
A reboot is required to replace the running dbus-daemon.
Please reboot the system when convenient.
Setting up libpam-systemd:amd64 (232-25+deb9u3) ...
Setting up openssh-server (1:7.4p1-10+deb9u3) ...
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:pP5f2LZAnkWhDhWeIJkUpjHZ4eI6OunXKngMv9sPuBw root@debian-std-prepare (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:YPiyBIT4+TdXK9Aet1iqCitEYuGL15cGdkTW9it9muc root@debian-std-prepare (ED25519)
Setting up waagent (2.2.18-3~deb9u1) ...
Installing new version of config file /etc/waagent.conf ...
waagent-provision.service is a disabled or a static unit, not starting it.
waagent-resourcedisk.service is a disabled or a static unit, not starting it.
waagent-provision.service is a disabled or a static unit, not starting it.
waagent-resourcedisk.service is a disabled or a static unit, not starting it.
waagent-provision.service is a disabled or a static unit, not starting it.
waagent-resourcedisk.service is a disabled or a static unit, not starting it.
waagent-provision.service is a disabled or a static unit, not starting it.
waagent-resourcedisk.service is a disabled or a static unit, not starting it.
Processing triggers for initramfs-tools (0.130) ...
update-initramfs: Generating /boot/initrd.img-4.9.0-6-amd64
Processing triggers for libc-bin (2.24-11+deb9u3) ...
azureuser@debian-std-prepare:~$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
azureuser@debian-std-prepare:~$ /usr/sbin/waagent --version
WALinuxAgent-2.2.18 running on debian 9.4
Python: 3.5.3
Goal state agent: 2.2.25
azureuser@debian-std-prepare:~$ history -c
azureuser@debian-std-prepare:~$ HISTSIZE=0
azureuser@debian-std-prepare:~$ sudo waagent -deprovision+user -force
WARNING! The waagent service will be stopped.
WARNING! All SSH host key pairs will be deleted.
WARNING! Cached DHCP leases will be deleted.
WARNING! root password will be disabled. You will not be able to login as root.
WARNING! /etc/resolv.conf will be deleted.
WARNING! azureuser account and entire home directory will be deleted.
userdel: user azureuser is currently used by process 1053
userdel: azureuser mail spool (/var/mail/azureuser) not found
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
azureuser@debian-std-prepare:~$ exit
logout
Connection to debian-std-prepare-dnsname.northeurope.cloudapp.azure.com closed.
root@Alexey-HP:~#
