### ISSUE TITLE
deprovision step should cleanup HWADDRR if present

### ISSUE THREAD

**Issue by moreandres** [Azure/WALinuxAgent#1065]
After running the deprovisioning step, my VHD import still failed to complete because I forgot to cleanup a harcoded MAC. I would say is useful to add such a cleanup into the step itself.

```
Bringing up interface eth0:  Device eth0 has different MAC address than expected, ignoring.
[FAILED]
```

`cat /etc/sysconfig/network-scripts/ifcfg-eth0`

```
DEVICE=eth0
HWADDR=00:57:57:a5:76:78
ONBOOT=yes
BOOTPROTO=dhcp
DHCPCLASS=
```

**Comment by boumenot** [comment]
I don't believe this file is created by the agent, so I am hesitant to touch it.  

/cc @szarkos - do you have an opinion on this issue?

**Comment by szarkos** [comment]
In the past this is also why the agent removed /etc/udev/rules.d/70-persistent-net.rules on older CentOS releases, but I think we stopped short of trying to edit ifcfg files. Yet it's true that there's little chance for this sort of configuration to work properly on Azure.

Maybe at least a big warning if HWADDR is detected during deprovision would be the safer approach.

**Comment by hglkrijger** [comment]
We have decided not to make any changes here.
