### ISSUE TITLE
'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1066]
We have noticed failures with CustomScriptForLinux with the following error message.

```text
'NoneType' object has no attribute 'encode'
```

This may affect other extensions in this repo, but the only report we have is for CustomScript.

**Comment by jasonzio** [comment]
For the repro we have, the faulting code path goes through set_handler_status(), which extracts the properties from handler_status and writes them to the status blob. In particular, that method calls get_properties(handler_status). If that returns None, json.dumps() will also return None, and that's what gets handed to fileutil.write_file().

Take a look at [fileutil.write_file()](https://github.com/Azure/WALinuxAgent/blob/70cc1d2bd743ff8ab73a7c2f2cd5c60113b3b85b/azurelinuxagent/common/utils/fileutil.py#L82). That method doesn't guard against the `content` parameter being None. If you pass a variable set to None to this method, you'll get exactly the error we're seeing here.

Most obvious fix: if content is None, do nothing, successfully.
Possibly wiser fix: if content is not a String or Unicode, complain and do nothing.
Possibly required: if content is Unicode, don't bother encoding it before writing it.
