### ISSUE TITLE
CentOS,  Backup Pre-Check status is "Warning"

### ISSUE THREAD

**Issue by IanLin419** [Azure/WALinuxAgent#1082]
I'm for sure my waagent is the latest one and the backup procedure is successful. But the status of Backup Pre-Check is "Warning".

WALinuxAgent >>> 2.2.18-1.el6
Microsoft.Azure.RecoveryServices.VMSnapshotLinux >>>> 1.0.9128.0

Does anyone have somehow to fix it?
If you need more information, please feel free to let me know.

**Comment by boumenot** [comment]
The latest version of the agent is 2.2.25.  It depends on your Distro and your configuration if you automatically get this version or not.

This is not the correct repository for extension related issues.  I **think** a better repository is https://github.com/Azure/azure-linux-extensions.
