### ISSUE TITLE
ERROR in Microsoft.OSTCExtensions.LinuxDiagnostic - Download, code 231

### ISSUE THREAD

**Issue by hougaard** [Azure/WALinuxAgent#1087]
I keep getting this error on a Debian 9.4 VM. Resulting in excessive IO.

`2018/03/31 00:37:12.770069 ERROR Event: name=Microsoft.OSTCExtensions.LinuxDiagnostic, op=Download, message=[ExtensionError] Non-zero exit code: 231, diagnostic.py -disable, duration=0
2018/03/31 00:37:12.968241 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Remove extension handler directory: /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029
2018/03/31 00:37:15.500186 INFO WALinuxAgent-2.2.25 waiting for orphan process 4539 to terminate
2018/03/31 00:37:16.122902 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Target handler state: enabled
2018/03/31 00:37:16.124011 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] [Enable] current handler state is: notinstalled
2018/03/31 00:37:17.763611 INFO Event: name=Microsoft.OSTCExtensions.LinuxDiagnostic, op=Download, message=Download succeeded, duration=1630
2018/03/31 00:37:17.764151 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Initialize extension directory
2018/03/31 00:37:17.782949 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Update settings file: 0.settings
2018/03/31 00:37:17.783702 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9025] Disable extension [diagnostic.py -disable]
2018/03/31 00:37:18.504717 INFO WALinuxAgent-2.2.25 waiting for orphan process 4539 to terminate
2018/03/31 00:37:18.793751 ERROR Event: name=Microsoft.OSTCExtensions.LinuxDiagnostic, op=Download, message=[ExtensionError] Non-zero exit code: 231, diagnostic.py -disable, duration=0
2018/03/31 00:37:18.821374 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Remove extension handler directory: /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029`

Any suggestions?

**Comment by boumenot** [comment]
Please open an issue against the [Azure/azure-linux-extensions](https://github.com/Azure/azure-linux-extensions/) repository.  This repository is only for Azure Linux guest agent.
