### ISSUE TITLE
SLES 11 SP4 - mkfs.ext3: No such file or directory while trying to determine filesystem size

### ISSUE THREAD

**Issue by NitroAMD** [Azure/WALinuxAgent#1093]
On SLES 11 SP4 VMs, the resource disk mostly don't mount at boot despite the resource disk is attached:

lsblk
NAME   MAJ:MIN RM SIZE RO MOUNTPOINT
sdb      8:16   0   8G  0
└─sdb1   8:17   0   8G  0
sda      8:0    0  30G  0
└─sda1   8:1    0  30G  0 /
fd0      2:0    1   4K  0

/var/log/waagent.log
...
2018/04/03 10:58:41.270489 INFO Azure Linux Agent Version:2.2.18
2018/04/03 10:58:41.286368 INFO OS: suse 11
2018/04/03 10:58:41.286874 INFO Python: 2.6.9
2018/04/03 10:58:41.290127 INFO Run daemon
2018/04/03 10:58:41.291329 INFO No RDMA handler exists for distro='SUSE Linux Enterprise Server' version='11'
2018/04/03 10:58:41.293024 INFO Activate resource disk
2018/04/03 10:58:41.344743 INFO Examining partition table
2018/04/03 10:58:41.502909 INFO GPT not detected, determining filesystem
2018/04/03 10:58:41.548668 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/03 10:58:41.559924 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/04/03 10:58:41.566065 INFO The partition is formatted with ntfs, updating partition type to 83
2018/04/03 10:58:41.605021 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/03 10:58:41.621604 INFO sfdisk -c  /dev/sdb 1 83 succeeded
2018/04/03 10:58:41.640987 INFO Format partition [mkfs.ext3 -F /dev/sdb1]
2018/04/03 10:58:41.734628 ERROR Command: 'mkfs.ext3 -F /dev/sdb1'
2018/04/03 10:58:41.734869 ERROR Return code: 1
2018/04/03 10:58:41.734985 ERROR Result: mke2fs 1.41.9 (22-Aug-2009)
mkfs.ext3: No such file or directory while trying to determine filesystem size^M

2018/04/03 10:58:41.735381 INFO Waiting for partition [/dev/sdb1], 5 attempts remaining
2018/04/03 10:58:46.740741 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2018/04/03 10:58:46.800684 WARNING Failed to mount resource disk. Retry mounting after re-reading partition info.
2018/04/03 10:58:46.871212 ERROR Command: 'mount /dev/sdb1 /mnt/resource'
2018/04/03 10:58:46.888164 ERROR Return code: 32
2018/04/03 10:58:46.898597 ERROR Result: mount: special device /dev/sdb1 does not exist

2018/04/03 10:58:46.915778 WARNING Failed to mount resource disk. Attempting to format and retry mount. [mount: special device /dev/sdb1 does not exist
]
2018/04/03 10:58:46.944627 ERROR Command: 'mkfs.ext3 -F /dev/sdb1'
2018/04/03 10:58:46.964763 ERROR Return code: 1
2018/04/03 10:58:46.979086 ERROR Result: mke2fs 1.41.9 (22-Aug-2009)
mkfs.ext3: No such file or directory while trying to determine filesystem size^M

2018/04/03 10:58:47.013659 ERROR Command: 'mount /dev/sdb1 /mnt/resource'
2018/04/03 10:58:47.026169 ERROR Return code: 32
2018/04/03 10:58:47.036872 ERROR Result: mount: special device /dev/sdb1 does not exist

2018/04/03 10:58:47.049367 ERROR Failed to mount resource disk [000005] Could not mount /dev/sdb1 after syncing partition table: [32] mount: special device /dev/sdb1 does not exist

2018/04/03 10:58:47.071300 ERROR Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[000005] Could not mount /dev/sdb1 after syncing partition table: [32] mount: special device /dev/sdb1 does not exist
, duration=0
...

##############################################################################

Formatting /dev/sdb1 manually (mkfs.ext3 /dev/sdb1) and then restart waagent helps out (disk get mounted), but at VM restart (more at deallocate/start), the mount errors happen again (sometimes it works fine, but mostly not).

You can easily reproduce the error when you delete "/dev/sdb1" via "fdisk /dev/sdb" and deallocate/start the VM.

##############################################################################

rpm -qa | grep azure
python-azure-agent-2.2.18-28.5.1

zypper info util-linux
Repository: SLES11-SP4-Pool
Name: util-linux
Version: 2.19.1-6.72.1
Arch: x86_64
Vendor: SUSE LINUX Products GmbH, Nuernberg, Germany
Support Level: Level 3
Installed: Yes
Status: up-to-date
Installed Size: 2.2 MiB
Summary: A collection of basic system utilities
Description:
This package contains a large variety of low-level system utilities
that are necessary for a Linux system to function. It contains the
mount program, the fdisk configuration tool, and more.
https://github.com/karelzak/util-linux/releases

##############################################################################

Tried the following, found within https://github.com/Azure/WALinuxAgent/issues/600, but it didn't helped out so far:
/usr/lib64/python2.6/site-packages/azurelinuxagent/daemon/resourcedisk/default.py
174          logger.info("Mount resource disk [{0}]", mount_string)
•	175   ret, output = shellutil.run_get_output("sync")
176          ret, output = shellutil.run_get_output(mount_string, chk_err=False)

From my point of view there is a missing "partprobe" at some stage or the "util-linux" tools are too old and harbor some bugs here in combination with the WALinuxAgent.

Any suggestions to look after or some mitigation starting points?

Thanks

**Comment by rjschwei** [comment]
According to the code after:

2018/04/03 10:58:41.566065 INFO The partition is formatted with ntfs, updating partition type to 83
2018/04/03 10:58:41.605021 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/03 10:58:41.621604 INFO sfdisk -c /dev/sdb 1 83 succeeded

there is a reread_partition_table() which is designed to trigger an update of the partition table. However the could still be a timing issue.

The only thing I could think of to show that this is a timing issue would be to hack 

azurelinuxagent/daemon/resourcedisk/default.py

and add a sleep before

shellutil.run(mkfs_string)

**Comment by NitroAMD** [comment]
*Thank you for your prompt help here. Much appreciated*

I added "sleep (10)" and tried "sleep (20)" too here:
146             logger.info("GPT not detected, determining filesystem")
147             ret = self.change_partition_type(suppress_message=True, option_str="{0} 1 -n".format(device))
148             ptype = ret[1].strip()
149             if ptype == "7" and self.fs != "ntfs":
150                 logger.info("The partition is formatted with ntfs, updating "
151                             "partition type to 83")
152                 self.change_partition_type(suppress_message=False, option_str="{0} 1 83".format(device))
153                 self.reread_partition_table(device)
154                 logger.info("Format partition [{0}]", mkfs_string)
*155               sleep(20)
156                 shellutil.run(mkfs_string)
157             else:
158                 logger.info("The partition type is {0}", ptype)


192             if ret:
193                 logger.warn("Failed to mount resource disk. "
194                             "Attempting to format and retry mount. [{0}]",
195                             output)
196
*197               sleep(20)
198                 shellutil.run(mkfs_string)
199                 ret, output = shellutil.run_get_output(mount_string)
200                 if ret:
201                     raise ResourceDiskError("Could not mount {0} "
202                                             "after syncing partition table: "
203                                             "[{1}] {2}".format(partition,
204                                                                ret,
205                                                                output))

but now I get the following errors

/var/log/waagent.log
2018/04/04 08:19:03.839188 INFO Agent WALinuxAgent-2.2.18 forwarding signal 15 to WALinuxAgent-2.2.18
2018/04/04 08:19:56.263317 INFO Azure Linux Agent Version:2.2.18
2018/04/04 08:19:56.263870 INFO OS: suse 11
2018/04/04 08:19:56.264396 INFO Python: 2.6.9
2018/04/04 08:19:56.265856 INFO Run daemon
2018/04/04 08:19:56.266937 INFO No RDMA handler exists for distro='SUSE Linux Enterprise Server' version='11'
2018/04/04 08:19:56.268692 INFO Activate resource disk
2018/04/04 08:19:56.284203 INFO Examining partition table
2018/04/04 08:19:56.408871 INFO GPT not detected, determining filesystem
2018/04/04 08:19:56.435331 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/04 08:19:56.448650 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/04/04 08:19:56.453888 INFO The partition type is 0
2018/04/04 08:19:56.454069 INFO Waiting for partition [/dev/sdb1], 5 attempts remaining
2018/04/04 08:20:01.459306 INFO Waiting for partition [/dev/sdb1], 4 attempts remaining
2018/04/04 08:20:06.478874 INFO Waiting for partition [/dev/sdb1], 3 attempts remaining
2018/04/04 08:20:11.500038 INFO Waiting for partition [/dev/sdb1], 2 attempts remaining
2018/04/04 08:20:16.521474 INFO Waiting for partition [/dev/sdb1], 1 attempts remaining
2018/04/04 08:20:21.542425 ERROR Failed to mount resource disk [000005] Partition was not created [/dev/sdb1]
2018/04/04 08:20:21.558111 ERROR Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[000005] Partition was not created [/dev/sdb1], duration=0

##############################################################################

Maybe there is an issue with sfdisk here or how it is used out of python?

##############################################################################

If I use sfdisk manually, all works fine too:
# sfdisk /dev/sdb <<EOM
> 0,
> ;
> ;
> EOM
Checking that no-one is using this disk right now ...
OK

Disk /dev/sdb: 1044 cylinders, 255 heads, 63 sectors/track
Old situation:
Units = cylinders of 8225280 bytes, blocks of 1024 bytes, counting from 0

   Device Boot Start     End   #cyls    #blocks   Id  System
/dev/sdb1          0       -       0          0    0  Empty
/dev/sdb2          0       -       0          0    0  Empty
/dev/sdb3          0       -       0          0    0  Empty
/dev/sdb4          0       -       0          0    0  Empty
New situation:
Units = cylinders of 8225280 bytes, blocks of 1024 bytes, counting from 0

   Device Boot Start     End   #cyls    #blocks   Id  System
/dev/sdb1          0+   1043    1044-   8385929+  83  Linux
/dev/sdb2          0       -       0          0    0  Empty
/dev/sdb3          0       -       0          0    0  Empty
/dev/sdb4          0       -       0          0    0  Empty
Warning: no primary partition is marked bootable (active)
This does not matter for LILO, but the DOS MBR will not boot this disk.
Successfully wrote the new partition table

Re-reading the partition table ...

If you created or changed a DOS partition, /dev/foo7, say, then use dd(1)
to zero the first 512 bytes:  dd if=/dev/zero of=/dev/foo7 bs=512 count=1
(See fdisk(8).)
# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           30G  1.3G   27G   5% /
udev            2.0G  104K  2.0G   1% /dev
tmpfs           2.0G  652K  2.0G   1% /dev/shm
/dev/sda1        30G  1.3G   27G   5% /
# lsblk
NAME   MAJ:MIN RM SIZE RO MOUNTPOINT
sda      8:0    0  30G  0
└─sda1   8:1    0  30G  0 /
sdb      8:16   0   8G  0
└─sdb1   8:17   0   8G  0
fd0      2:0    1   4K  0
# service waagent restart
Shutting down MicrosoftAzureLinuxAgent                                                                                                                        done
Starting MicrosoftAzureLinuxAgent                                                                                                                             done
# lsblk
NAME   MAJ:MIN RM SIZE RO MOUNTPOINT
sda      8:0    0  30G  0
└─sda1   8:1    0  30G  0 /
sdb      8:16   0   8G  0
└─sdb1   8:17   0   8G  0 /mnt/resource
fd0      2:0    1   4K  0
# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           30G  1.3G   27G   5% /
udev            2.0G  104K  2.0G   1% /dev
tmpfs           2.0G  652K  2.0G   1% /dev/shm
/dev/sda1        30G  1.3G   27G   5% /
/dev/sdb1       7.9G  810M  6.7G  11% /mnt/resource

/var/log/waagent.log
2018/04/04 08:26:58.621162 INFO Agent WALinuxAgent-2.2.18 forwarding signal 15 to WALinuxAgent-2.2.18
2018/04/04 08:26:59.817227 INFO Azure Linux Agent Version:2.2.18
2018/04/04 08:26:59.829724 INFO OS: suse 11
2018/04/04 08:26:59.841969 INFO Python: 2.6.9
2018/04/04 08:26:59.854820 INFO Run daemon
2018/04/04 08:26:59.868006 INFO No RDMA handler exists for distro='SUSE Linux Enterprise Server' version='11'
2018/04/04 08:26:59.884986 INFO Activate resource disk
2018/04/04 08:26:59.905366 INFO Examining partition table
2018/04/04 08:26:59.926650 INFO GPT not detected, determining filesystem
2018/04/04 08:26:59.945645 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/04 08:26:59.966228 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/04/04 08:26:59.979944 INFO The partition type is 83
2018/04/04 08:26:59.993068 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2018/04/04 08:27:00.362885 WARNING Failed to mount resource disk. Retry mounting after re-reading partition info.
2018/04/04 08:27:00.424736 ERROR Command: 'mount /dev/sdb1 /mnt/resource'
2018/04/04 08:27:00.440333 ERROR Return code: 32
2018/04/04 08:27:00.453017 ERROR Result: mount: special device /dev/sdb1 does not exist

2018/04/04 08:27:00.469493 WARNING Failed to mount resource disk. Attempting to format and retry mount. [mount: special device /dev/sdb1 does not exist
]
2018/04/04 08:27:28.887640 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext3
2018/04/04 08:27:28.906084 INFO Enable swap
2018/04/04 08:27:28.922041 INFO Create swap file
2018/04/04 08:27:28.947281 ERROR Command: 'umask 0077 && fallocate -l 1073741824 '/mnt/resource/swapfile''
2018/04/04 08:27:28.964976 ERROR Return code: 1
2018/04/04 08:27:28.977656 ERROR Result: fallocate: /mnt/resource/swapfile: fallocate failed: Operation not supported

2018/04/04 08:27:28.997456 INFO fallocate unsuccessful, falling back to dd
2018/04/04 08:27:50.345387 INFO dd successful
2018/04/04 08:28:41.247264 INFO Enabled 1048576KB of swap at /mnt/resource/swapfile
2018/04/04 08:28:41.262576 INFO Clean protocol
2018/04/04 08:28:41.276600 INFO Provisioning already completed, skipping.

##############################################################################

Here the /etc/waagent.conf to complete the content
#
# Microsoft Azure Linux Agent Configuration
#

# Enable instance creation
Provisioning.Enabled=y

# Rely on cloud-init to provision
Provisioning.UseCloudInit=n

# Password authentication for root account will be unavailable.
Provisioning.DeleteRootPassword=y

# Generate fresh host key pair.
Provisioning.RegenerateSshHostKeyPair=y

# Supported values are "rsa", "dsa" and "ecdsa".
Provisioning.SshHostKeyPairType=rsa

# Monitor host name changes and publish changes via DHCP requests.
Provisioning.MonitorHostName=y

# Decode CustomData from Base64.
Provisioning.DecodeCustomData=n

# Execute CustomData after provisioning.
Provisioning.ExecuteCustomData=n

# Algorithm used by crypt when generating password hash.
#Provisioning.PasswordCryptId=6

# Length of random salt used when generating password hash.
#Provisioning.PasswordCryptSaltLength=10

# Allow reset password of sys user
Provisioning.AllowResetSysUser=n

# Format if unformatted. If 'n', resource disk will not be mounted.
ResourceDisk.Format=y

# File system on the resource disk
# Typically ext3 or ext3. FreeBSD images should use 'ufs2' here.
ResourceDisk.Filesystem=ext3

# Mount point for the resource disk
ResourceDisk.MountPoint=/mnt/resource

# Create and use swapfile on resource disk.
ResourceDisk.EnableSwap=y

# Size of the swapfile.
ResourceDisk.SwapSizeMB=1024

# Comma-seperated list of mount options. See man(8) for valid options.
ResourceDisk.MountOptions=None

# Respond to load balancer probes if requested by Microsoft Azure.
LBProbeResponder=y

# Enable verbose logging (y|n)
Logs.Verbose=n

# Is FIPS enabled
OS.EnableFIPS=n

# Root device timeout in seconds.
OS.RootDeviceScsiTimeout=300

# If "None", the system default version is used.
OS.OpensslPath=None

# Set the path to SSH keys and configuration files
OS.SshDir=/etc/ssh

# If set, agent will use proxy server to access internet
#HttpProxy.Host=None
#HttpProxy.Port=None

# Detect Scvmm environment, default is n
# DetectScvmmEnv=n

#
# Lib.Dir=/var/lib/waagent

#
# DVD.MountPoint=/mnt/cdrom/secure

#
# Pid.File=/var/run/waagent.pid

#
# Extension.LogDir=/var/log/azure

#
# Home.Dir=/home

# Enable RDMA management and set up, should only be used in HPC images
# OS.EnableRDMA=y

# Enable or disable goal state processing auto-update, default is enabled
AutoUpdate.Enabled=n

# Determine the update family, this should not be changed
# AutoUpdate.GAFamily=Prod

# Determine if the overprovisioning feature is enabled. If yes, hold extension
# handling until inVMArtifactsProfile.OnHold is false.
# Default is disabled
# EnableOverProvisioning=n

# Allow fallback to HTTP if HTTPS is unavailable
# Note: Allowing HTTP (vs. HTTPS) may cause security risks
# OS.AllowHTTP=n

# Add firewall rules to protect access to Azure host node services
# Note:
# - The default is false to protect the state of exising VMs
OS.EnableFirewall=y

**Comment by NitroAMD** [comment]
Thank you for your prompt help here. Much appreciated

I added "sleep (10)" and tried "sleep (20)" too here:
146             logger.info("GPT not detected, determining filesystem")
147             ret = self.change_partition_type(suppress_message=True, option_str="{0} 1 -n".format(device))
148             ptype = ret[1].strip()
149             if ptype == "7" and self.fs != "ntfs":
150                 logger.info("The partition is formatted with ntfs, updating "
151                             "partition type to 83")
152                 self.change_partition_type(suppress_message=False, option_str="{0} 1 83".format(device))
153                 self.reread_partition_table(device)
154                 logger.info("Format partition [{0}]", mkfs_string)
***155              sleep(20)
156                 shellutil.run(mkfs_string)
157             else:
158                 logger.info("The partition type is {0}", ptype)


192             if ret:
193                 logger.warn("Failed to mount resource disk. "
194                             "Attempting to format and retry mount. [{0}]",
195                             output)
196
***197              sleep(20)
198                 shellutil.run(mkfs_string)
199                 ret, output = shellutil.run_get_output(mount_string)
200                 if ret:
201                     raise ResourceDiskError("Could not mount {0} "
202                                             "after syncing partition table: "
203                                             "[{1}] {2}".format(partition,
204                                                                ret,
205                                                                output))

but now I get the following errors

/var/log/waagent.log
2018/04/04 08:19:03.839188 INFO Agent WALinuxAgent-2.2.18 forwarding signal 15 to WALinuxAgent-2.2.18
2018/04/04 08:19:56.263317 INFO Azure Linux Agent Version:2.2.18
2018/04/04 08:19:56.263870 INFO OS: suse 11
2018/04/04 08:19:56.264396 INFO Python: 2.6.9
2018/04/04 08:19:56.265856 INFO Run daemon
2018/04/04 08:19:56.266937 INFO No RDMA handler exists for distro='SUSE Linux Enterprise Server' version='11'
2018/04/04 08:19:56.268692 INFO Activate resource disk
2018/04/04 08:19:56.284203 INFO Examining partition table
2018/04/04 08:19:56.408871 INFO GPT not detected, determining filesystem
2018/04/04 08:19:56.435331 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/04 08:19:56.448650 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/04/04 08:19:56.453888 INFO The partition type is 0
2018/04/04 08:19:56.454069 INFO Waiting for partition [/dev/sdb1], 5 attempts remaining
2018/04/04 08:20:01.459306 INFO Waiting for partition [/dev/sdb1], 4 attempts remaining
2018/04/04 08:20:06.478874 INFO Waiting for partition [/dev/sdb1], 3 attempts remaining
2018/04/04 08:20:11.500038 INFO Waiting for partition [/dev/sdb1], 2 attempts remaining
2018/04/04 08:20:16.521474 INFO Waiting for partition [/dev/sdb1], 1 attempts remaining
2018/04/04 08:20:21.542425 ERROR Failed to mount resource disk [000005] Partition was not created [/dev/sdb1]
2018/04/04 08:20:21.558111 ERROR Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[000005] Partition was not created [/dev/sdb1], duration=0


Maybe there is an issue with sfdisk here or how it is used out of python?


If I use sfdisk manually, all works fine too:
* sfdisk /dev/sdb <<EOM
> 0,
> ;
> ;
> EOM
Checking that no-one is using this disk right now ...
OK

Disk /dev/sdb: 1044 cylinders, 255 heads, 63 sectors/track
Old situation:
Units = cylinders of 8225280 bytes, blocks of 1024 bytes, counting from 0

   Device Boot Start     End   #cyls    #blocks   Id  System
/dev/sdb1          0       -       0          0    0  Empty
/dev/sdb2          0       -       0          0    0  Empty
/dev/sdb3          0       -       0          0    0  Empty
/dev/sdb4          0       -       0          0    0  Empty
New situation:
Units = cylinders of 8225280 bytes, blocks of 1024 bytes, counting from 0

   Device Boot Start     End   #cyls    #blocks   Id  System
/dev/sdb1          0+   1043    1044-   8385929+  83  Linux
/dev/sdb2          0       -       0          0    0  Empty
/dev/sdb3          0       -       0          0    0  Empty
/dev/sdb4          0       -       0          0    0  Empty
Warning: no primary partition is marked bootable (active)
This does not matter for LILO, but the DOS MBR will not boot this disk.
Successfully wrote the new partition table

Re-reading the partition table ...

If you created or changed a DOS partition, /dev/foo7, say, then use dd(1)
to zero the first 512 bytes:  dd if=/dev/zero of=/dev/foo7 bs=512 count=1
(See fdisk(8).)
* df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           30G  1.3G   27G   5% /
udev            2.0G  104K  2.0G   1% /dev
tmpfs           2.0G  652K  2.0G   1% /dev/shm
/dev/sda1        30G  1.3G   27G   5% /
* lsblk
NAME   MAJ:MIN RM SIZE RO MOUNTPOINT
sda      8:0    0  30G  0
└─sda1   8:1    0  30G  0 /
sdb      8:16   0   8G  0
└─sdb1   8:17   0   8G  0
fd0      2:0    1   4K  0
* service waagent restart
Shutting down MicrosoftAzureLinuxAgent                                                                                                                        done
Starting MicrosoftAzureLinuxAgent                                                                                                                             done
* lsblk
NAME   MAJ:MIN RM SIZE RO MOUNTPOINT
sda      8:0    0  30G  0
└─sda1   8:1    0  30G  0 /
sdb      8:16   0   8G  0
└─sdb1   8:17   0   8G  0 /mnt/resource
fd0      2:0    1   4K  0
* df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           30G  1.3G   27G   5% /
udev            2.0G  104K  2.0G   1% /dev
tmpfs           2.0G  652K  2.0G   1% /dev/shm
/dev/sda1        30G  1.3G   27G   5% /
/dev/sdb1       7.9G  810M  6.7G  11% /mnt/resource

/var/log/waagent.log
2018/04/04 08:26:58.621162 INFO Agent WALinuxAgent-2.2.18 forwarding signal 15 to WALinuxAgent-2.2.18
2018/04/04 08:26:59.817227 INFO Azure Linux Agent Version:2.2.18
2018/04/04 08:26:59.829724 INFO OS: suse 11
2018/04/04 08:26:59.841969 INFO Python: 2.6.9
2018/04/04 08:26:59.854820 INFO Run daemon
2018/04/04 08:26:59.868006 INFO No RDMA handler exists for distro='SUSE Linux Enterprise Server' version='11'
2018/04/04 08:26:59.884986 INFO Activate resource disk
2018/04/04 08:26:59.905366 INFO Examining partition table
2018/04/04 08:26:59.926650 INFO GPT not detected, determining filesystem
2018/04/04 08:26:59.945645 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/04 08:26:59.966228 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/04/04 08:26:59.979944 INFO The partition type is 83
2018/04/04 08:26:59.993068 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2018/04/04 08:27:00.362885 WARNING Failed to mount resource disk. Retry mounting after re-reading partition info.
2018/04/04 08:27:00.424736 ERROR Command: 'mount /dev/sdb1 /mnt/resource'
2018/04/04 08:27:00.440333 ERROR Return code: 32
2018/04/04 08:27:00.453017 ERROR Result: mount: special device /dev/sdb1 does not exist

2018/04/04 08:27:00.469493 WARNING Failed to mount resource disk. Attempting to format and retry mount. [mount: special device /dev/sdb1 does not exist
]
2018/04/04 08:27:28.887640 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext3
2018/04/04 08:27:28.906084 INFO Enable swap
2018/04/04 08:27:28.922041 INFO Create swap file
2018/04/04 08:27:28.947281 ERROR Command: 'umask 0077 && fallocate -l 1073741824 '/mnt/resource/swapfile''
2018/04/04 08:27:28.964976 ERROR Return code: 1
2018/04/04 08:27:28.977656 ERROR Result: fallocate: /mnt/resource/swapfile: fallocate failed: Operation not supported

2018/04/04 08:27:28.997456 INFO fallocate unsuccessful, falling back to dd
2018/04/04 08:27:50.345387 INFO dd successful
2018/04/04 08:28:41.247264 INFO Enabled 1048576KB of swap at /mnt/resource/swapfile
2018/04/04 08:28:41.262576 INFO Clean protocol
2018/04/04 08:28:41.276600 INFO Provisioning already completed, skipping.


Here the /etc/waagent.conf to complete the content
*
* Microsoft Azure Linux Agent Configuration
*

* Enable instance creation
Provisioning.Enabled=y

* Rely on cloud-init to provision
Provisioning.UseCloudInit=n

* Password authentication for root account will be unavailable.
Provisioning.DeleteRootPassword=y

* Generate fresh host key pair.
Provisioning.RegenerateSshHostKeyPair=y

* Supported values are "rsa", "dsa" and "ecdsa".
Provisioning.SshHostKeyPairType=rsa

* Monitor host name changes and publish changes via DHCP requests.
Provisioning.MonitorHostName=y

* Decode CustomData from Base64.
Provisioning.DecodeCustomData=n

* Execute CustomData after provisioning.
Provisioning.ExecuteCustomData=n

* Algorithm used by crypt when generating password *.
*Provisioning.PasswordCryptId=6

* Length of random salt used when generating password *.
*Provisioning.PasswordCryptSaltLength=10

* Allow reset password of sys user
Provisioning.AllowResetSysUser=n

* Format if unformatted. If 'n', resource disk will not be mounted.
ResourceDisk.Format=y

* File system on the resource disk
* Typically ext3 or ext3. FreeBSD images should use 'ufs2' here.
ResourceDisk.Filesystem=ext3

* Mount point for the resource disk
ResourceDisk.MountPoint=/mnt/resource

* Create and use swapfile on resource disk.
ResourceDisk.EnableSwap=y

* Size of the swapfile.
ResourceDisk.SwapSizeMB=1024

* Comma-seperated list of mount options. See man(8) for valid options.
ResourceDisk.MountOptions=None

* Respond to load balancer probes if requested by Microsoft Azure.
LBProbeResponder=y

* Enable verbose logging (y|n)
Logs.Verbose=n

* Is FIPS enabled
OS.EnableFIPS=n

* Root device timeout in seconds.
OS.RootDeviceScsiTimeout=300

* If "None", the system default version is used.
OS.OpensslPath=None

* Set the path to SSH keys and configuration files
OS.SshDir=/etc/ssh

* If set, agent will use proxy server to access internet
*HttpProxy.Host=None
*HttpProxy.Port=None

* Detect Scvmm environment, default is n
* DetectScvmmEnv=n

*
* Lib.Dir=/var/lib/waagent

*
* DVD.MountPoint=/mnt/cdrom/secure

*
* Pid.File=/var/run/waagent.pid

*
* Extension.LogDir=/var/log/azure

*
* Home.Dir=/home

* Enable RDMA management and set up, should only be used in HPC images
* OS.EnableRDMA=y

* Enable or disable goal state processing auto-update, default is enabled
AutoUpdate.Enabled=n

* Determine the update family, this should not be changed
* AutoUpdate.GAFamily=Prod

* Determine if the overprovisioning feature is enabled. If yes, hold extension
* handling until inVMArtifactsProfile.OnHold is false.
* Default is disabled
* EnableOverProvisioning=n

* Allow fallback to HTTP if HTTPS is unavailable
* Note: Allowing HTTP (vs. HTTPS) may cause security risks
* OS.AllowHTTP=n

* Add firewall rules to protect access to Azure host node services
* Note:
* - The default is false to protect the state of exising VMs
OS.EnableFirewall=y

**Comment by boumenot** [comment]
It is odd that it works manually, but not via the agent.  Would you please increase the verbosity of the agent, and attach those logs.  

/etc/waagent.conf
```text
# Enable verbose logging (y|n)
Logs.Verbose=y
```

**Comment by rjschwei** [comment]
Well the agent runs much earlier in the process, thus that it works manually is not necessarily a surprise. It could also be related to jitter in the framework and how fast/slow the ephemeral storage device is really available.

**Comment by NitroAMD** [comment]
This is the output with increased verbosity:

2018/04/06 22:16:25.669404 INFO Agent WALinuxAgent-2.2.18 forwarding signal 15 to WALinuxAgent-2.2.18
2018/04/06 22:17:19.511095 INFO Azure Linux Agent Version:2.2.18
2018/04/06 22:17:19.512154 INFO OS: suse 11
2018/04/06 22:17:19.512262 INFO Python: 2.6.9
2018/04/06 22:17:19.512660 INFO Run daemon
2018/04/06 22:17:19.512912 INFO No RDMA handler exists for distro='SUSE Linux Enterprise Server' version='11'
2018/04/06 22:17:19.513261 INFO Activate resource disk
2018/04/06 22:17:19.516237 VERBOSE Run 'mount'
2018/04/06 22:17:19.548014 INFO Examining partition table
2018/04/06 22:17:19.548462 VERBOSE Run 'parted /dev/sdb print'
2018/04/06 22:17:19.592024 INFO GPT not detected, determining filesystem
2018/04/06 22:17:19.592292 VERBOSE Run 'sfdisk --part-type -f /dev/sdb 1 -n'
2018/04/06 22:17:19.617986 INFO sfdisk with --part-type failed [1], retrying with -c
2018/04/06 22:17:19.618197 VERBOSE Run 'sfdisk -c -f /dev/sdb 1 -n'
2018/04/06 22:17:19.643226 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/04/06 22:17:19.643510 INFO The partition type is 0
2018/04/06 22:17:19.643697 INFO Waiting for partition [/dev/sdb1], 5 attempts remaining
2018/04/06 22:17:24.648936 INFO Waiting for partition [/dev/sdb1], 4 attempts remaining
2018/04/06 22:17:29.669407 INFO Waiting for partition [/dev/sdb1], 3 attempts remaining
2018/04/06 22:17:34.692981 INFO Waiting for partition [/dev/sdb1], 2 attempts remaining
2018/04/06 22:17:39.792288 INFO Waiting for partition [/dev/sdb1], 1 attempts remaining
2018/04/06 22:17:44.813765 ERROR Failed to mount resource disk [000005] Partition was not created [/dev/sdb1]
2018/04/06 22:17:44.830151 ERROR Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[000005] Partition was not created [/dev/sdb1], duration=0

**Comment by NitroAMD** [comment]
@ rjschwei mentioned, that "agent runs much earlier in the process", so do you have some suggestions to delay the agent service startup ?

**Comment by NitroAMD** [comment]
We needed a workaround so we implemented the following:

**vim /etc/init.d/after.local**
`#!/bin/sh
service waagent stop
sfdisk /dev/sdb <<EOM
0,
;
;
;
EOM
partprobe
mkfs.ext3 /dev/sdb1 -q
service waagent start`

The only question is: Is /dev/sdb "always" the temporary drive if no one modifies things?
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/about-disks-and-vhds?toc=%2Fazure%2Fvirtual-machines%2Flinux%2Ftoc.json
https://blogs.msdn.microsoft.com/mast/2013/12/06/understanding-the-temporary-drive-on-windows-azure-virtual-machines/

I didn't reviewed the Python code in detail, but how you determine that the Temporary Drive is the "Temporary Drive"?

Additonally, can partprobe be the "solution" for the waagent issues here?

**Comment by hglkrijger** [comment]
The ephemeral disk is found with [this code](https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/osutil/default.py#L1125). It is not guaranteed to be `/dev/sdb`. 

I am glad you found a workaround, but it seems as though something outside of the agent is the source of the issue or we would see this issue much more frequently and in our nightly tests. I am not sure there is any further action we can take. 

If you can provide a repro or want to submit a PR we would be happy to take another look.
