### ISSUE TITLE
Waagent stop responding to Azure - CentOS 7.1

### ISSUE THREAD

**Issue by KPCSInfra** [Azure/WALinuxAgent#110]
Via PowerShell command: 
$vm = get-azurevm -ServiceName xxxx -Name xxxx
$vm.GuestAgentStatus | Format-List GuestAgentVersion,Status

VM Guest Agent Status: NotReady

Therefore, it does not function a backup of Azure VM to Azure Backup Vault. Snapshot has not been created. Only restart waagent daemon will solve the issue..

-------------------------------------------------------------------
2015/09/13 14:44:03 Windows Azure Linux Agent Version: WALinuxAgent-2.0.13
2015/09/13 14:44:03 Linux Distribution Detected      : centos
2015/09/13 14:44:03 Module /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2015/09/13 14:44:03 VMM Init script not found.  Provisioning for Azure
2015/09/13 14:44:03 IPv4 address: 172.16.xxx.xxx
2015/09/13 14:44:03 MAC  address: 00:0D:3A:22:03:D0
2015/09/13 14:44:03 Probing for Windows Azure environment.
2015/09/13 14:44:03 DoDhcpWork: Setting socket.timeout=10, entering recv
2015/09/13 14:44:03 Discovered Windows Azure endpoint: 168.63.129.16
2015/09/13 14:44:03 Fabric preferred wire protocol version: 2015-04-05
2015/09/13 14:44:03 Negotiated wire protocol version: 2012-11-30
2015/09/13 14:44:03 Retrieved GoalState from Windows Azure Fabric.
2015/09/13 14:44:03 ExpectedState: Started
2015/09/13 14:44:03 ContainerId: 736fca64-c729-4a8a-8c8b-2552a9ed696f
2015/09/13 14:44:03 RoleInstanceId: 65606d3c51184cb19a45257c07d3ddad.xxx-xxxx
2015/09/13 14:44:03 ActivateResourceDisk: /dev/sdb1 is already mounted.
2015/09/13 14:44:03 Posted Role Properties. CertificateThumbprint=601402884eb2ec8337c1f4b4f1f3402d
2015/09/13 14:44:06 Finished processing ExtensionsConfig.xml
2015/09/15 06:07:38 ERROR:Retry=0
2015/09/15 06:07:38 ERROR:HTTP Req: POST /machine?comp=health
2015/09/15 06:07:38 ERROR:HTTP Req: Data=<?xml version="1.0" encoding="utf-8"?><Health xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GoalStateIncarnation>1</GoalStateIncarnation><Container><ContainerId>736fca64-c729-4a8a-8c8b-2552a9ed696f</ContainerId><RoleInstanceList><Role><InstanceId>65606d3c51184cb19a45257c07d3ddad.pczdds-portaldb2</InstanceId><Health><State>Ready</State></Health></Role></RoleInstanceList></Container></Health>
2015/09/15 06:07:38 ERROR:HTTP Req: Header={'Content-Type': 'text/xml; charset=utf-8', 'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent'}
2015/09/15 06:07:38 ERROR:HTTP Err: Status=503
2015/09/15 06:07:38 ERROR:HTTP Err: Reason=Service Unavailable
2015/09/15 06:07:38 ERROR:HTTP Err: Header=[('date', 'Tue, 15 Sep 2015 06:07:37 GMT'), ('connection', 'close'), ('content-type', 'text/html; charset=us-ascii'), ('content-length', '326'), ('server', 'Microsoft-HTTPAPI/2.0')]
2015/09/15 06:07:38 ERROR:HTTP Err: Body=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
2015/09/15 06:07:38 ERROR:<HTML><HEAD><TITLE>Service Unavailable</TITLE>
2015/09/15 06:07:38 ERROR:<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
2015/09/15 06:07:38 ERROR:<BODY><h2>Service Unavailable</h2>
2015/09/15 06:07:38 ERROR:<hr><p>HTTP Error 503. The service is unavailable.</p>
2015/09/15 06:07:38 ERROR:</BODY></HTML>
2015/09/15 06:07:38 ERROR:
2015/09/15 06:07:48 ERROR:Socket IOError getaddrinfo() argument 2 must be integer or string, args:('getaddrinfo() argument 2 must be integer or string',)
2015/09/15 06:07:48 ERROR:Retry=1
2015/09/15 06:07:48 ERROR:HTTP Req: POST /machine?comp=health
2015/09/15 06:07:48 ERROR:HTTP Req: Data=<?xml version="1.0" encoding="utf-8"?><Health xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GoalStateIncarnation>1</GoalStateIncarnation><Container><ContainerId>736fca64-c729-4a8a-8c8b-2552a9ed696f</ContainerId><RoleInstanceList><Role><InstanceId>65606d3c51184cb19a45257c07d3ddad.pczdds-portaldb2</InstanceId><Health><State>Ready</State></Health></Role></RoleInstanceList></Container></Health>
2015/09/15 06:07:48 ERROR:HTTP Req: Header={'Content-Type': 'text/xml; charset=utf-8', 'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent'}
2015/09/15 06:07:48 ERROR:HTTP Err: response is empty.
2015/09/15 06:07:58 ERROR:Socket IOError getaddrinfo() argument 2 must be integer or string, args:('getaddrinfo() argument 2 must be integer or string',)
2015/09/15 06:07:58 ERROR:Retry=2
2015/09/15 06:07:58 ERROR:HTTP Req: POST /machine?comp=health
2015/09/15 06:07:58 ERROR:HTTP Req: Data=<?xml version="1.0" encoding="utf-8"?><Health xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GoalStateIncarnation>1</GoalStateIncarnation><Container><ContainerId>736fca64-c729-4a8a-8c8b-2552a9ed696f</ContainerId><RoleInstanceList><Role><InstanceId>65606d3c51184cb19a45257c07d3ddad.pczdds-portaldb2</InstanceId><Health><State>Ready</State></Health></Role></RoleInstanceList></Container></Health>
2015/09/15 06:07:58 ERROR:HTTP Req: Header={'Content-Type': 'text/xml; charset=utf-8', 'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent'}
2015/09/15 06:07:58 ERROR:HTTP Err: response is empty.
2015/09/15 06:08:08 ERROR:Socket IOError getaddrinfo() argument 2 must be integer or string, args:('getaddrinfo() argument 2 must be integer or string',)
2015/09/15 06:08:31 Retrieved GoalState from Windows Azure Fabric.
2015/09/15 06:08:31 ExpectedState: Started
2015/09/15 06:08:31 ContainerId: 736fca64-c729-4a8a-8c8b-2552a9ed696f
2015/09/15 06:08:31 RoleInstanceId: 65606d3c51184cb19a45257c07d3ddad.pczdds-portaldb2
2015/09/15 06:08:31 Posted Role Properties. CertificateThumbprint=601402884eb2ec8337c1f4b4f1f3402d
2015/09/15 06:08:34 Finished processing ExtensionsConfig.xml
2015/09/20 14:00:52 ERROR:Socket IOError [Errno 111] Connection refused, args:(111, 'Connection refused')
2015/09/20 14:00:52 ERROR:Retry=0
2015/09/20 14:00:52 ERROR:HTTP Req: PUT https://xxxxx.blob.core.windows.net/$system/xxxx-xx.xxxxxxb.xxx-xxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/20 14:00:52 ERROR:HTTP Req: Data=
2015/09/20 14:00:52 ERROR:HTTP Req: Header={'Content-Length': '0', 'x-ms-blob-content-length': '512', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'PageBlob', 'x-ms-date': '2015-09-20T14:00:52Z'}
2015/09/20 14:00:52 ERROR:HTTP Err: response is empty.
2015/09/20 14:03:09 ERROR:Socket IOError [Errno 110] Connection timed out, args:(110, 'Connection timed out')
2015/09/20 14:03:09 ERROR:Retry=1
2015/09/20 14:03:09 ERROR:HTTP Req: PUT https://xxxxx.blob.core.windows.net/$system/xxxx-xxxx.xxx-xxxx.pxxx-xxxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/20 14:03:09 ERROR:HTTP Req: Data=
2015/09/20 14:03:09 ERROR:HTTP Req: Header={'Content-Length': '0', 'x-ms-blob-content-length': '512', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'PageBlob', 'x-ms-date': '2015-09-20T14:00:52Z'}
2015/09/20 14:03:09 ERROR:HTTP Err: response is empty.
2015/09/20 14:05:27 ERROR:Socket IOError [Errno 110] Connection timed out, args:(110, 'Connection timed out')
2015/09/20 14:05:27 ERROR:Retry=2
2015/09/20 14:05:27 ERROR:HTTP Req: PUT https://xxxxx.blob.core.windows.net/$system/xxxxx-xxxx.xxxx-xxxxxx-xxxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/20 14:05:27 ERROR:HTTP Req: Data=
2015/09/20 14:05:27 ERROR:HTTP Req: Header={'Content-Length': '0', 'x-ms-blob-content-length': '512', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'PageBlob', 'x-ms-date': '2015-09-20T14:00:52Z'}
2015/09/20 14:05:27 ERROR:HTTP Err: response is empty.
2015/09/20 14:07:44 ERROR:Socket IOError [Errno 110] Connection timed out, args:(110, 'Connection timed out')
2015/09/20 14:07:44 ERROR:Failed to clean up page blob for status
2015/09/21 16:07:19 ERROR:Socket IOError [Errno 111] Connection refused, args:(111, 'Connection refused')
2015/09/21 16:07:19 ERROR:Retry=0
2015/09/21 16:07:19 ERROR:HTTP Req: HEAD https://xxxx.blob.core.windows.net/$system/xxx-xxx.xxx-xxxxxx-xxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/21 16:07:19 ERROR:HTTP Req: Data=None
2015/09/21 16:07:19 ERROR:HTTP Req: Header={'x-ms-version': '2014-02-14', 'x-ms-date': '2015-09-21T16:07:19Z'}
2015/09/21 16:07:19 ERROR:HTTP Err: response is empty.
2015/09/21 16:07:29 ERROR:Traceback (most recent call last):
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 5939, in main
2015/09/21 16:07:29 ERROR:    WaAgent.Run()
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 5541, in Run
2015/09/21 16:07:29 ERROR:    goalState.ExtensionsConfig.ReportHandlerStatus()
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 3832, in ReportHandlerStatus
2015/09/21 16:07:29 ERROR:    UploadStatusBlob(uri, status.encode("utf-8"))
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 2891, in UploadStatusBlob
2015/09/21 16:07:29 ERROR:    blobType = GetBlobType(url)
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 2820, in GetBlobType
2015/09/21 16:07:29 ERROR:    }, chkProxy=True);
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 2759, in HttpHead
2015/09/21 16:07:29 ERROR:    return self.HttpRequest("HEAD", url, None, headers, maxRetry, chkProxy)
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 2751, in HttpRequest
2015/09/21 16:07:29 ERROR:    headers, proxyHost, proxyPort)
2015/09/21 16:07:29 ERROR:  File "/usr/sbin/waagent", line 2679, in _HttpRequest
2015/09/21 16:07:29 ERROR:    conn.request(method, path, data)
2015/09/21 16:07:29 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 973, in request
2015/09/21 16:07:29 ERROR:    self._send_request(method, url, body, headers)
2015/09/21 16:07:29 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
2015/09/21 16:07:29 ERROR:    self.endheaders(body)
2015/09/21 16:07:29 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
2015/09/21 16:07:29 ERROR:    self._send_output(message_body)
2015/09/21 16:07:29 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
2015/09/21 16:07:29 ERROR:    self.send(message_body)
2015/09/21 16:07:29 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 805, in send
2015/09/21 16:07:29 ERROR:    self.sock.sendall(data)
2015/09/21 16:07:29 ERROR:  File "/usr/lib64/python2.7/ssl.py", line 226, in sendall
2015/09/21 16:07:29 ERROR:    amount = len(data)
2015/09/21 16:07:29 ERROR:TypeError: object of type 'bool' has no len()
2015/09/21 16:07:29 ERROR:
2015/09/21 16:07:29 ERROR:Exception: object of type 'bool' has no len()
2015/09/27 14:11:12 Windows Azure Linux Agent Version: WALinuxAgent-2.0.13
2015/09/27 14:11:12 Linux Distribution Detected      : centos
2015/09/27 14:11:12 Module /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2015/09/27 14:11:12 VMM Init script not found.  Provisioning for Azure
2015/09/27 14:11:12 IPv4 address: 172.16.xxx.xxx
2015/09/27 14:11:12 MAC  address: 00:0D:3A:22:03:D0
2015/09/27 14:11:12 Probing for Windows Azure environment.
2015/09/27 14:11:12 DoDhcpWork: Setting socket.timeout=10, entering recv
2015/09/27 14:11:12 Discovered Windows Azure endpoint: 168.63.129.16
2015/09/27 14:11:12 Fabric preferred wire protocol version: 2015-04-05
2015/09/27 14:11:12 Negotiated wire protocol version: 2012-11-30
2015/09/27 14:11:12 Retrieved GoalState from Windows Azure Fabric.
2015/09/27 14:11:12 ExpectedState: Started
2015/09/27 14:11:12 ContainerId: 736fca64-c729-4a8a-8c8b-2552a9ed696f
2015/09/27 14:11:12 RoleInstanceId: 65606d3c51184cb19a45257c07d3ddad.pczdds-portaldb2
2015/09/27 14:11:12 ActivateResourceDisk: /dev/sdb1 is already mounted.
2015/09/27 14:11:12 Posted Role Properties. CertificateThumbprint=601402884eb2ec8337c1f4b4f1f3402d
2015/09/27 14:11:15 Finished processing ExtensionsConfig.xml
2015/09/28 02:17:19 Windows Azure Linux Agent Version: WALinuxAgent-2.0.13
2015/09/28 02:17:19 Linux Distribution Detected      : centos
2015/09/28 02:17:19 Module /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2015/09/28 02:17:19 VMM Init script not found.  Provisioning for Azure
2015/09/28 02:17:19 IPv4 address: 172.16.248.11
2015/09/28 02:17:19 MAC  address: 00:0D:3A:22:03:D0
2015/09/28 02:17:19 Probing for Windows Azure environment.
2015/09/28 02:17:19 DoDhcpWork: Setting socket.timeout=10, entering recv
2015/09/28 02:17:19 Discovered Windows Azure endpoint: 168.63.129.16
2015/09/28 02:17:19 Fabric preferred wire protocol version: 2015-04-05
2015/09/28 02:17:19 Negotiated wire protocol version: 2012-11-30
2015/09/28 02:17:19 Retrieved GoalState from Windows Azure Fabric.
2015/09/28 02:17:19 ExpectedState: Started
2015/09/28 02:17:19 ContainerId: 736fca64-c729-4a8a-8c8b-2552a9ed696f
2015/09/28 02:17:19 RoleInstanceId: 65606d3c51184cb19a45257c07d3ddad.xxx-xxx
2015/09/28 02:17:19 ActivateResourceDisk: /dev/sdb1 is already mounted.
2015/09/28 02:17:19 Posted Role Properties. CertificateThumbprint=601402884eb2ec8337c1f4b4f1f3402d
2015/09/28 02:17:23 Finished processing ExtensionsConfig.xml
2015/09/29 18:40:59 ERROR:Socket IOError [Errno 104] Connection reset by peer, args:(104, 'Connection reset by peer')
2015/09/29 18:40:59 ERROR:Retry=0
2015/09/29 18:41:00 ERROR:HTTP Req: HEAD https://xxx.blob.core.windows.net/$system/xxx-xxxx.xxx-xxx.xxx-xxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/29 18:41:00 ERROR:HTTP Req: Data=None
2015/09/29 18:41:00 ERROR:HTTP Req: Header={'x-ms-version': '2014-02-14', 'x-ms-date': '2015-09-29T18:40:29Z'}
2015/09/29 18:41:00 ERROR:HTTP Err: response is empty.
2015/09/29 18:41:10 ERROR:Traceback (most recent call last):
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 5939, in main
2015/09/29 18:41:10 ERROR:    WaAgent.Run()
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 5541, in Run
2015/09/29 18:41:10 ERROR:    goalState.ExtensionsConfig.ReportHandlerStatus()
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 3832, in ReportHandlerStatus
2015/09/29 18:41:10 ERROR:    UploadStatusBlob(uri, status.encode("utf-8"))
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 2891, in UploadStatusBlob
2015/09/29 18:41:10 ERROR:    blobType = GetBlobType(url)
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 2820, in GetBlobType
2015/09/29 18:41:10 ERROR:    }, chkProxy=True);
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 2759, in HttpHead
2015/09/29 18:41:10 ERROR:    return self.HttpRequest("HEAD", url, None, headers, maxRetry, chkProxy)
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 2751, in HttpRequest
2015/09/29 18:41:10 ERROR:    headers, proxyHost, proxyPort)
2015/09/29 18:41:10 ERROR:  File "/usr/sbin/waagent", line 2679, in _HttpRequest
2015/09/29 18:41:10 ERROR:    conn.request(method, path, data)
2015/09/29 18:41:10 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 973, in request
2015/09/29 18:41:10 ERROR:    self._send_request(method, url, body, headers)
2015/09/29 18:41:10 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
2015/09/29 18:41:10 ERROR:    self.endheaders(body)
2015/09/29 18:41:10 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
2015/09/29 18:41:10 ERROR:    self._send_output(message_body)
2015/09/29 18:41:10 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
2015/09/29 18:41:10 ERROR:    self.send(message_body)
2015/09/29 18:41:10 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 805, in send
2015/09/29 18:41:10 ERROR:    self.sock.sendall(data)
2015/09/29 18:41:10 ERROR:  File "/usr/lib64/python2.7/ssl.py", line 226, in sendall
2015/09/29 18:41:10 ERROR:    amount = len(data)
2015/09/29 18:41:10 ERROR:TypeError: object of type 'bool' has no len()
2015/09/29 18:41:10 ERROR:
2015/09/29 18:41:10 ERROR:Exception: object of type 'bool' has no len()
2015/09/29 19:17:30 Windows Azure Linux Agent Version: WALinuxAgent-2.0.13
2015/09/29 19:17:30 Linux Distribution Detected      : centos
2015/09/29 19:17:30 Module /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2015/09/29 19:17:30 VMM Init script not found.  Provisioning for Azure
2015/09/29 19:17:30 IPv4 address: 172.16.xxx.xxx
2015/09/29 19:17:30 MAC  address: 00:0D:3A:22:03:D0
2015/09/29 19:17:30 Probing for Windows Azure environment.
2015/09/29 19:17:30 DoDhcpWork: Setting socket.timeout=10, entering recv
2015/09/29 19:17:30 Discovered Windows Azure endpoint: 168.63.129.16
2015/09/29 19:17:30 Fabric preferred wire protocol version: 2015-04-05
2015/09/29 19:17:30 Negotiated wire protocol version: 2012-11-30
2015/09/29 19:17:30 Retrieved GoalState from Windows Azure Fabric.
2015/09/29 19:17:30 ExpectedState: Started
2015/09/29 19:17:30 ContainerId: 736fca64-c729-4a8a-8c8b-2552a9ed696f
2015/09/29 19:17:30 RoleInstanceId: 65606d3c51184cb19a45257c07d3ddad.pczdds-portaldb2
2015/09/29 19:17:30 ActivateResourceDisk: /dev/sdb1 is already mounted.
2015/09/29 19:17:30 Posted Role Properties. CertificateThumbprint=601402884eb2ec8337c1f4b4f1f3402d
2015/09/29 19:17:33 Finished processing ExtensionsConfig.xml
2015/09/29 20:31:31 ERROR:Socket IOError [Errno 111] Connection refused, args:(111, 'Connection refused')
2015/09/29 20:31:31 ERROR:Retry=0
2015/09/29 20:31:31 ERROR:HTTP Req: PUT https://xxx.blob.core.windows.net/$system/xxx-xxx.xxx-xxx.xxxx-xxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/29 20:31:31 ERROR:HTTP Req: Data=
2015/09/29 20:31:31 ERROR:HTTP Req: Header={'Content-Length': '0', 'x-ms-blob-content-length': '512', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'PageBlob', 'x-ms-date': '2015-09-29T20:31:31Z'}
2015/09/29 20:31:31 ERROR:HTTP Err: response is empty.
2015/09/29 20:33:48 ERROR:Socket IOError [Errno 110] Connection timed out, args:(110, 'Connection timed out')
2015/09/29 20:33:48 ERROR:Retry=1
2015/09/29 20:33:48 ERROR:HTTP Req: PUT https://xxx.blob.core.windows.net/$system/xxx-xxx.xxxx-xxxx.xxxx-xxxxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/29 20:33:48 ERROR:HTTP Req: Data=
2015/09/29 20:33:48 ERROR:HTTP Req: Header={'Content-Length': '0', 'x-ms-blob-content-length': '512', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'PageBlob', 'x-ms-date': '2015-09-29T20:31:31Z'}
2015/09/29 20:33:48 ERROR:HTTP Err: response is empty.
2015/09/29 20:36:05 ERROR:Socket IOError [Errno 110] Connection timed out, args:(110, 'Connection timed out')
2015/09/29 20:36:05 ERROR:Retry=2
2015/09/29 20:36:05 ERROR:HTTP Req: PUT https://xxxx.blob.core.windows.net/$system/xxx-xxxx.xxx-portaldb.xxx-xxxxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/29 20:36:05 ERROR:HTTP Req: Data=
2015/09/29 20:36:05 ERROR:HTTP Req: Header={'Content-Length': '0', 'x-ms-blob-content-length': '512', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'PageBlob', 'x-ms-date': '2015-09-29T20:31:31Z'}
2015/09/29 20:36:05 ERROR:HTTP Err: response is empty.
2015/09/29 20:38:23 ERROR:Socket IOError [Errno 110] Connection timed out, args:(110, 'Connection timed out')
2015/09/29 20:38:23 ERROR:Failed to clean up page blob for status
2015/09/30 17:02:47 ERROR:Socket IOError [Errno 111] Connection refused, args:(111, 'Connection refused')
2015/09/30 17:02:47 ERROR:Retry=0
2015/09/30 17:02:47 ERROR:HTTP Req: HEAD https://xxx.blob.core.windows.net/$system/xxx-xxx.xxxx-xxxpczdds-xxxxx.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=YI5qUkXtCxy4OLu4B1pEhpf3%2Fy0Uteo143aqrg3SCns%3D
2015/09/30 17:02:47 ERROR:HTTP Req: Data=None
2015/09/30 17:02:47 ERROR:HTTP Req: Header={'x-ms-version': '2014-02-14', 'x-ms-date': '2015-09-30T17:02:47Z'}
2015/09/30 17:02:47 ERROR:HTTP Err: response is empty.
2015/09/30 17:02:57 ERROR:Traceback (most recent call last):
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 5939, in main
2015/09/30 17:02:57 ERROR:    WaAgent.Run()
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 5541, in Run
2015/09/30 17:02:57 ERROR:    goalState.ExtensionsConfig.ReportHandlerStatus()
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 3832, in ReportHandlerStatus
2015/09/30 17:02:57 ERROR:    UploadStatusBlob(uri, status.encode("utf-8"))
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 2891, in UploadStatusBlob
2015/09/30 17:02:57 ERROR:    blobType = GetBlobType(url)
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 2820, in GetBlobType
2015/09/30 17:02:57 ERROR:    }, chkProxy=True);
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 2759, in HttpHead
2015/09/30 17:02:57 ERROR:    return self.HttpRequest("HEAD", url, None, headers, maxRetry, chkProxy)
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 2751, in HttpRequest
2015/09/30 17:02:57 ERROR:    headers, proxyHost, proxyPort)
2015/09/30 17:02:57 ERROR:  File "/usr/sbin/waagent", line 2679, in _HttpRequest
2015/09/30 17:02:57 ERROR:    conn.request(method, path, data)
2015/09/30 17:02:57 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 973, in request
2015/09/30 17:02:57 ERROR:    self._send_request(method, url, body, headers)
2015/09/30 17:02:57 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
2015/09/30 17:02:57 ERROR:    self.endheaders(body)
2015/09/30 17:02:57 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
2015/09/30 17:02:57 ERROR:    self._send_output(message_body)
2015/09/30 17:02:57 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
2015/09/30 17:02:57 ERROR:    self.send(message_body)
2015/09/30 17:02:57 ERROR:  File "/usr/lib64/python2.7/httplib.py", line 805, in send
2015/09/30 17:02:57 ERROR:    self.sock.sendall(data)
2015/09/30 17:02:57 ERROR:  File "/usr/lib64/python2.7/ssl.py", line 226, in sendall
2015/09/30 17:02:57 ERROR:    amount = len(data)
2015/09/30 17:02:57 ERROR:TypeError: object of type 'bool' has no len()
2015/09/30 17:02:57 ERROR:
2015/09/30 17:02:57 ERROR:Exception: object of type 'bool' has no len()

**Comment by tmaierACN** [comment]
Can you please check which version of waagent you are running there?

**Comment by yuezh** [comment]
@KPCSInfra This is a bug for waagent-2.0.13. The fix is included in the latest waagent package. You could use yum upgrade WALinuxAgent to get the fix.

**Comment by KPCSInfra** [comment]
Thank you all. Actually it looks good. It looks like, that the problem was solved by upgrading WAAGENT.
I will continue to watch the situation.
