### ISSUE TITLE
Kernel version to be available made available by Linux VM agent

### ISSUE THREAD

**Issue by sujayt** [Azure/WALinuxAgent#1101]
This information helps to know which kernel version is running inside the VM without actually logging into the VM.

**Comment by boumenot** [comment]
Would you please explain this request better?  What do you mean exactly?

**Comment by hglkrijger** [comment]
Timing out due to lack of activity.

**Comment by boumenot** [comment]
The request is to make the kernel version available in the VM status blob.

```json
 "guestOSInfo": {
    "osName": "debian",
    "version": "2.2.26",
    "computerName": "supervm",
    "osVersion": "9.4"
  },
```

The status blob does not contain the kernel information, which is useful in some cases.  CRP is unwilling to allocate a new field, so if we made this change we would have to overload an existing one.  This is a breaking change.

**Comment by jasonzio** [comment]
I'm not sure why this is considered a breaking change. Does CRP suddenly fail if the status blob contains within it a new field it knows nothing about? If it's simply a matter of CRP not surfacing that value elsewhere, that's not critical; as long as the information is actually available in the status blob, tools can be built that allow the owner of a VM to retrieve the blob as-is, no?

**Comment by boumenot** [comment]
CRP does not want to allocate a new field for the kernel version (per our last conversation with them - it has been a while).  It would be a breaking change if we modify an existing field to include the kernel version.

The other alternative that we discussed in person is to modify the JSON document to include the kernel version.  CRP should safely ignore that change.  This means the kernel version would not be exposed through any API that fronts the JSON blob.  The kernel version could still be accessed by fetching the blob directly.  (Off the top of my head I don't know if that's possible or not, but I strongly suspect that it is.)

**Comment by danielsollondon** [comment]
@sujayt - @boumenot has provide an option, if that is suitable for you please raise a PR.
