### ISSUE TITLE
want to add Wiki

### ISSUE THREAD

**Issue by nmikuni** [Azure/WALinuxAgent#1111]
Hi, this is not the Issue but as I don't know how to pull request the Wiki, I am posting here.
I want to add Wiki about Goal-State-Agent. Could you please review the .md file and merge to Wiki if it seems good? I attach the file as txt, but I wrote it as Markdown.
[Goal-Agent.txt](https://github.com/Azure/WALinuxAgent/files/1915346/Goal-Agent.txt)

**Comment by boumenot** [comment]
Thank you for contributing.  I think the documentation is mostly correct, but I would want to clarify a few statements before publishing it.

I will do that, but it most likely will not be until next or the week after.

**Comment by nmikuni** [comment]
Hi, thank you for taking this. I'd like to know about the status :)

**Comment by boumenot** [comment]
Thanks for you patience on this, and I am sorry it took so long.  2.2.30 is near enough completion that I wrapped this up.

https://github.com/Azure/WALinuxAgent/wiki/What-does-%22Goal-state-agent%22-mean-in-waagent--version-Output%3F
