### ISSUE TITLE
Problem with the agent having access to dvd device

### ISSUE THREAD

**Issue by marlonrc** [Azure/WALinuxAgent#1117]
Customer is trying to provision his custom OS based on Linux From Scratch in the Azure marketplace, but at the time the agent (Azure Linux Agent Version:2.2.18.7) needs to access the DVD drive, the agent can't find it. Find below the error:
azurelinuxagent.common.exception.OSUtilError: [OSUtilError] Failed to get dvd device from /dev
Inner error: The following devices were found, but none matched the pattern [(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])]: ['log', 'vcsa12', 'vcs12', 'vcsa11', 'vcs11', 'vcsa10', 'vcs10', 'vcsa9', 'vcs9', 'vcsa8', 'vcs8', 'vcsa7', 'vcs7', 'vcsa6', 'vcs6', 'vcsa5', 'vcs5', 'vcsa4', 'vcs4', 'vcsa3', 'vcs3', 'vcsa2', 'vcs2', 'disk', 'block', 'rtc', 'char', 'stderr', 'stdout', 'stdin', 'fd', 'core', 'shm', 'pts', 'initctl', 'memory_bandwidth', 'network_throughput', 'network_latency', 'cpu_dma_latency', 'sdc', 'vmbus', 'rtc0', 'sg2', 'sdb1', 'sda7', 'sda6', 'sda5', 'sda4', 'sda3', 'sda2', 'sda1', 'sda', 'sdb', 'sg1', 'sg0', 'bsg', 'loop7', 'loop6', 'loop5', 'loop4', 'loop3', 'loop2', 'loop1', 'loop0', 'loop-control', 'ram15', 'ram14', 'ram13', 'ram12', 'ram11', 'ram10', 'ram9', 'ram8', 'ram7', 'ram6', 'ram5', 'ram4', 'ram3', 'ram2', 'ram1', 'ram0', 'hwrng', 'ttyS3', 'ttyS2', 'ttyS1', 'ttyS0', 'ptmx', 'ttyef', 'ttyee', 'ttyed', 'ttyec', 'ttyeb', 'ttyea', 'ttye9', 'ttye8', 'ttye7', 'ttye6', 'ttye5', 'ttye4', 'ttye3', 'ttye2', 'ttye1', 'ttye0', 'ttydf', 'ttyde', 'ttydd', 'ttydc', 'ttydb', 'ttyda', 'ttyd9', 'ttyd8', 'ttyd7', 'ttyd6', 'ttyd5', 'ttyd4', 'ttyd3', 'ttyd2', 'ttyd1', 'ttyd0', 'ttycf', 'ttyce', 'ttycd', 'ttycc', 'ttycb', 'ttyca', 'ttyc9', 'ttyc8', 'ttyc7', 'ttyc6', 'ttyc5', 'ttyc4', 'ttyc3', 'ttyc2', 'ttyc1', 'ttyc0', 'ttybf', 'ttybe', 'ttybd', 'ttybc', 'ttybb', 'ttyba', 'ttyb9', 'ttyb8', 'ttyb7', 'ttyb6', 'ttyb5', 'ttyb4', 'ttyb3', 'ttyb2', 'ttyb1', 'ttyb0', 'ttyaf', 'ttyae', 'ttyad', 'ttyac', 'ttyab', 'ttyaa', 'ttya9', 'ttya8', 'ttya7', 'ttya6', 'ttya5', 'ttya4', 'ttya3', 'ttya2', 'ttya1', 'ttya0', 'ttyzf', 'ttyze', 'ttyzd', 'ttyzc', 'ttyzb', 'ttyza', 'ttyz9', 'ttyz8', 'ttyz7', 'ttyz6', 'ttyz5', 'ttyz4', 'ttyz3', 'ttyz2', 'ttyz1', 'ttyz0', 'ttyyf', 'ttyye', 'ttyyd', 'ttyyc', 'ttyyb', 'ttyya', 'ttyy9', 'ttyy8', 'ttyy7', 'ttyy6', 'ttyy5', 'ttyy4', 'ttyy3', 'ttyy2', 'ttyy1', 'ttyy0', 'ttyxf', 'ttyxe', 'ttyxd', 'ttyxc', 'ttyxb', 'ttyxa', 'ttyx9', 'ttyx8', 'ttyx7', 'ttyx6', 'ttyx5', 'ttyx4', 'ttyx3', 'ttyx2', 'ttyx1', 'ttyx0', 'ttywf', 'ttywe', 'ttywd', 'ttywc', 'ttywb', 'ttywa', 'ttyw9', 'ttyw8', 'ttyw7', 'ttyw6', 'ttyw5', 'ttyw4', 'ttyw3', 'ttyw2', 'ttyw1', 'ttyw0', 'ttyvf', 'ttyve', 'ttyvd', 'ttyvc', 'ttyvb', 'ttyva', 'ttyv9', 'ttyv8', 'ttyv7', 'ttyv6', 'ttyv5', 'ttyv4', 'ttyv3', 'ttyv2', 'ttyv1', 'ttyv0', 'ttyuf', 'ttyue', 'ttyud', 'ttyuc', 'ttyub', 'ttyua', 'ttyu9', 'ttyu8', 'ttyu7', 'ttyu6', 'ttyu5', 'ttyu4', 'ttyu3', 'ttyu2', 'ttyu1', 'ttyu0', 'ttytf', 'ttyte', 'ttytd', 'ttytc', 'ttytb', 'ttyta', 'ttyt9', 'ttyt8', 'ttyt7', 'ttyt6', 'ttyt5', 'ttyt4', 'ttyt3', 'ttyt2', 'ttyt1', 'ttyt0', 'ttysf', 'ttyse', 'ttysd', 'ttysc', 'ttysb', 'ttysa', 'ttys9', 'ttys8', 'ttys7', 'ttys6', 'ttys5', 'ttys4', 'ttys3', 'ttys2', 'ttys1', 'ttys0', 'ttyrf', 'ttyre', 'ttyrd', 'ttyrc', 'ttyrb', 'ttyra', 'ttyr9', 'ttyr8', 'ttyr7', 'ttyr6', 'ttyr5', 'ttyr4', 'ttyr3', 'ttyr2', 'ttyr1', 'ttyr0', 'ttyqf', 'ttyqe', 'ttyqd', 'ttyqc', 'ttyqb', 'ttyqa', 'ttyq9', 'ttyq8', 'ttyq7', 'ttyq6', 'ttyq5', 'ttyq4', 'ttyq3', 'ttyq2', 'ttyq1', 'ttyq0', 'ttypf', 'ttype', 'ttypd', 'ttypc', 'ttypb', 'ttypa', 'ttyp9', 'ttyp8', 'ttyp7', 'ttyp6', 'ttyp5', 'ttyp4', 'ttyp3', 'ttyp2', 'ttyp1', 'ttyp0', 'ptyef', 'ptyee', 'ptyed', 'ptyec', 'ptyeb', 'ptyea', 'ptye9', 'ptye8', 'ptye7', 'ptye6', 'ptye5', 'ptye4', 'ptye3', 'ptye2', 'ptye1', 'ptye0', 'ptydf', 'ptyde', 'ptydd', 'ptydc', 'ptydb', 'ptyda', 'ptyd9', 'ptyd8', 'ptyd7', 'ptyd6', 'ptyd5', 'ptyd4', 'ptyd3', 'ptyd2', 'ptyd1', 'ptyd0', 'ptycf', 'ptyce', 'ptycd', 'ptycc', 'ptycb', 'ptyca', 'ptyc9', 'ptyc8', 'ptyc7', 'ptyc6', 'ptyc5', 'ptyc4', 'ptyc3', 'ptyc2', 'ptyc1', 'ptyc0', 'ptybf', 'ptybe', 'ptybd', 'ptybc', 'ptybb', 'ptyba', 'ptyb9', 'ptyb8', 'ptyb7', 'ptyb6', 'ptyb5', 'ptyb4', 'ptyb3', 'ptyb2', 'ptyb1', 'ptyb0', 'ptyaf', 'ptyae', 'ptyad', 'ptyac', 'ptyab', 'ptyaa', 'ptya9', 'ptya8', 'ptya7', 'ptya6', 'ptya5', 'ptya4', 'ptya3', 'ptya2', 'ptya1', 'ptya0', 'ptyzf', 'ptyze', 'ptyzd', 'ptyzc', 'ptyzb', 'ptyza', 'ptyz9', 'ptyz8', 'ptyz7', 'ptyz6', 'ptyz5', 'ptyz4', 'ptyz3', 'ptyz2', 'ptyz1', 'ptyz0', 'ptyyf', 'ptyye', 'ptyyd', 'ptyyc', 'ptyyb', 'ptyya', 'ptyy9', 'ptyy8', 'ptyy7', 'ptyy6', 'ptyy5', 'ptyy4', 'ptyy3', 'ptyy2', 'ptyy1', 'ptyy0', 'ptyxf', 'ptyxe', 'ptyxd', 'ptyxc', 'ptyxb', 'ptyxa', 'ptyx9', 'ptyx8', 'ptyx7', 'ptyx6', 'ptyx5', 'ptyx4', 'ptyx3', 'ptyx2', 'ptyx1', 'ptyx0', 'ptywf', 'ptywe', 'ptywd', 'ptywc', 'ptywb', 'ptywa', 'ptyw9', 'ptyw8', 'ptyw7', 'ptyw6', 'ptyw5', 'ptyw4', 'ptyw3', 'ptyw2', 'ptyw1', 'ptyw0', 'ptyvf', 'ptyve', 'ptyvd', 'ptyvc', 'ptyvb', 'ptyva', 'ptyv9', 'ptyv8', 'ptyv7', 'ptyv6', 'ptyv5', 'ptyv4', 'ptyv3', 'ptyv2', 'ptyv1', 'ptyv0', 'ptyuf', 'ptyue', 'ptyud', 'ptyuc', 'ptyub', 'ptyua', 'ptyu9', 'ptyu8', 'ptyu7', 'ptyu6', 'ptyu5', 'ptyu4', 'ptyu3', 'ptyu2', 'ptyu1', 'ptyu0', 'ptytf', 'ptyte', 'ptytd', 'ptytc', 'ptytb', 'ptyta', 'ptyt9', 'ptyt8', 'ptyt7', 'ptyt6', 'ptyt5', 'ptyt4', 'ptyt3', 'ptyt2', 'ptyt1', 'ptyt0', 'ptysf', 'ptyse', 'ptysd', 'ptysc', 'ptysb', 'ptysa', 'ptys9', 'ptys8', 'ptys7', 'ptys6', 'ptys5', 'ptys4', 'ptys3', 'ptys2', 'ptys1', 'ptys0', 'ptyrf', 'ptyre', 'ptyrd', 'ptyrc', 'ptyrb', 'ptyra', 'ptyr9', 'ptyr8', 'ptyr7', 'ptyr6', 'ptyr5', 'ptyr4', 'ptyr3', 'ptyr2', 'ptyr1', 'ptyr0', 'ptyqf', 'ptyqe', 'ptyqd', 'ptyqc', 'ptyqb', 'ptyqa', 'ptyq9', 'ptyq8', 'ptyq7', 'ptyq6', 'ptyq5', 'ptyq4', 'ptyq3', 'ptyq2', 'ptyq1', 'ptyq0', 'ptypf', 'ptype', 'ptypd', 'ptypc', 'ptypb', 'ptypa', 'ptyp9', 'ptyp8', 'ptyp7', 'ptyp6', 'ptyp5', 'ptyp4', 'ptyp3', 'ptyp2', 'ptyp1', 'ptyp0', 'fb0', 'tty63', 'tty62', 'tty61', 'tty60', 'tty59', 'tty58', 'tty57', 'tty56', 'tty55', 'tty54', 'tty53', 'tty52', 'tty51', 'tty50', 'tty49', 'tty48', 'tty47', 'tty46', 'tty45', 'tty44', 'tty43', 'tty42', 'tty41', 'tty40', 'tty39', 'tty38', 'tty37', 'tty36', 'tty35', 'tty34', 'tty33', 'tty32', 'tty31', 'tty30', 'tty29', 'tty28', 'tty27', 'tty26', 'tty25', 'tty24', 'tty23', 'tty22', 'tty21', 'tty20', 'tty19', 'tty18', 'tty17', 'tty16', 'tty15', 'tty14', 'tty13', 'tty12', 'tty11', 'tty10', 'tty9', 'tty8', 'tty7', 'tty6', 'tty5', 'tty4', 'tty3', 'tty2', 'tty1', 'vcsa1', 'vcs1', 'vcsa', 'vcs', 'tty0', 'console', 'tty', 'kmsg', 'urandom', 'random', 'full', 'zero', 'port', 'null', 'kmem', 'mem', 'vga_arbiter']

**Comment by boumenot** [comment]
We do not support custom images.  You will need to debug this on your own.

Azure uses the DVD to get information about the VM being deployed, so it **must** be available at the time of provisioning.  The error message indicates it is not.  My first suggestion is to ensure the latest version of the LIS drivers are installed, and that the kernel supports Hyper-V.

**Comment by sundaxi** [comment]
Hi @boumenot , if I removed /var/lib/waagent/provisioned manually, the agent will try to re-provisioning the VM again during next boot, but at this time, the dvd was not inserted via host level and the provisioning would fail forever. Any idea about this please?
