### ISSUE TITLE
Download telemetry

### ISSUE THREAD

**Issue by hglkrijger** [Azure/WALinuxAgent#1118]
Currently we flag the following as a `Download` failure; this is misleading, and should be changed to something more appropriate, such as `Extension` failure with a specific `publisher.name` message. 

```
[ExtensionError] Non-zero exit code: 1, omsagent.py -disable
```

**Comment by boumenot** [comment]
This issue occurs when the extension is being upgraded. The new install handler sets its state to `Download`.  The old extension handler is then disabled and uninstalled. If the old extension handler causes an exception to be raised the catcher consults the **new** extension handler not the **old** extension handler. As a result, the operation is incorrect.

The caller is ignorant of the old extension handler, so I'll have to figure out an elegant way to plumb this through. Elegant may not be all that elegant.
