### ISSUE TITLE
Consistent Set of Unit Test Helper Methods

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1124]
We support and test on Python 2.6, 2.7, and 3.4.  There were some gotchas in the code base such as our use of assert_called_once() that are not present in Python 3.4.  (This feature was added in Python 3.6, and back ported to 2.7.)  The test cases with this method would pass in TravisCI, but fail on developer's machines.

Please invest in making the unit testing tools more pleasant for the developer.  Identify some of the methods that are missing, and automatically patch the current version of Python to make them available.  

Please update this issue with the missing methods.

 1. Mock's assert_called_once()
 1. Mock's assert_not_called()

**Comment by jasonzio** [comment]
The current compatibility list:

- assertRegex
- assertNotRegex
- assertIn
-assertNotIn
-assertGreater
-assertLess
-assertIsNone
-assertIsNotNone


In addition, two new testcase decorators have been added: `@skip_if_predicate_true(predicate, msg)` and `@skip_if_predicate_false(predicate, msg)`. These decorators will invoke the predicate function and either perform the test or log the message, depending on the bool returned by the (parameter-less) predicate and the particular decorator in use.

**Comment by hglkrijger** [comment]
@boumenot are there more to add or can we close?

**Comment by jasonzio** [comment]
A current CR covers `assertRaiseRegex`. I think Chris intended this to be a constant reminder to use the richest assert methods by building back-rev implementations rather than by writing in-line version detection code, and as a place to record "non-portable assert methods that really need to be made portable".

**Comment by hglkrijger** [comment]
Think we have them covered
