### ISSUE TITLE
Mount a new device 

### ISSUE THREAD

**Issue by kannirockstar** [Azure/WALinuxAgent#1128]
Am using SLES 11 VM and having issues with mounting a device. 

Statement: Every restart of host changes the device names of the volumes attached, so my file systems is all over the place. And the issue is inconsistent with every restart. 

I tried using UUID instead of device names to see if solves the problem. But I get below error when using UUID. 

Here are the steps, 
mkfs.xfs -f /dev/sdf
Then i add the below string to /etc/fstab,
/dev/disk/by-uuid/795de0b7-d6a6-4d21-86d7-c6a3d44f0e66 /oracle/AZ1/origlogA xfs defaults 1 1

When i try to mount the device using "mount -a"
I get below,
mount: special device /dev/disk/by-uuid/795de0b7-d6a6-4d21-86d7-c6a3d44f0e66  does not exist

I can however mount with device name,
mount /dev/sdf/ /oracle/AZ1/origlogA  ........but the problem with this is that the device name is not being persistent. Every reboot changes the device name, so it gets mapped to a wrong mount. 

The UUID works two other mounts, that are in the /etc/fstab. So its not an issue with syntax. 

Here's my /etc/fstab

devpts  /dev/pts          devpts  mode=0620,gid=5 0 0
proc    /proc             proc    defaults        0 0
sysfs   /sys              sysfs   noauto          0 0
debugfs /sys/kernel/debug debugfs noauto          0 0
tmpfs   /run              tmpfs   noauto          0 0
/dev/disk/by-uuid/7ae608d2-a0df-4b94-9cbd-5205bacacb41 / ext3 defaults 1 1
/dev/disk/by-uuid/39d2aeef-8f76-46a7-a91a-94b8acb9f6b5 /oracle xfs defaults 1 1
/dev/disk/by-uuid/795de0b7-d6a6-4d21-86d7-c6a3d44f0e66 /oracle/AZ1/origlogA xfs defaults 1 1

Am really frustrated with this.

**Comment by szarkos** [comment]
Hi,

Very sorry you're running into this issue.  This is common in some older distributions where the device-mapper may not generate those symlinks when a filesystem changes.  This behavior, and the issue with non-persistent device file names unfortunately are not unique to the Azure platform.

My advice would be to run the following command to force udev to re-run the applicable udev rules (such as *-device-mapper.rules):

      udevadm trigger --subsystem-match=block

After this please check 'ls -l /dev/disk/by-uuid' and 'mount -a' to make sure the symlink for the disk shows up.

Thanks,
Steve

**Comment by hglkrijger** [comment]
Timing out, please reopen as needed.
