### ISSUE TITLE
RHEL > 7 versions will switch to python3

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#1129]
Hi there,

As we known that RHEL > 7 versions will switch to python3. Can we consider to make WALA use python3 in RHEL > 7 versions? Thanks!

And it seems that currently most of the extensions are using python2 only. Is there any plan to support python3? Thanks!

**Comment by hglkrijger** [comment]
Is the plan to change the system default to Python3, or to run WALA under Python3? The agent can run fine under Python3, but extensions cannot, unfortunately. As far as I know, most extensions do not have plans to update to Python3 support.

**Comment by yuxisun1217** [comment]
@hglkrijger Currently as I known that RHEL > 7 versions will change the system default to Python3, which means there will be no /usr/bin/python but only /usr/bin/python3. This change needs WALA run under Python3 in RHEL. I think our developer will also submit some patches here about this change.

About the specific version I'm sorry I also have no accurate answer now. The official words are "next major version of Red Hat Enterprise Linux". I'll update here as soon as I get more information.

About the extensions, thank you for your updating. We'll discuss more and see if we can support them.

Thanks!

**Comment by hglkrijger** [comment]
That will not fix the extensions themselves though, which have a Python language version dependency in many cases. Internally we are following up with some of the extension publishers, but it is unlikely we will get all of them updated in the near term.

**Comment by hglkrijger** [comment]
As I recall from discussions with @baude around containerization, there is significant work to do to enable this and that work is per-extension. From my perspective it seems equivalent to adding language support for an extension, if not a larger challenge. Either way, the extensions need to be updated, and while we have influence over those we own, there are many third-party extensions as well as first-party extensions which we do not own, and there is no deterministic way to ensure those run on Python 3.

**Comment by jasonzio** [comment]
Not only that, but there's no requirement that a container infrastructure be installed in any particular VM, and I'm distinctly uncomfortable adding that as a requirement.

**Comment by danielsollondon** [comment]
Currently the agent supports Py3, however, but there is work needed to be done in some extensions, the publishers have been informed.

**Comment by hglkrijger** [comment]
Since there is no work to be done in the agent, closing this out.
