### ISSUE TITLE
Set Permissions of Resource Disk

### ISSUE THREAD

**Issue by kemhof** [Azure/WALinuxAgent#113]
This should probably be tagged as an enhancement request.  

The Resource disk (/dev/sdb1) that the Windows Azure Linux agent mounts.  It would be nice to be able to specify what permissions it has when its mounted.  The nature of this resource disk would be perfect for /tmp.  However, due to its dynamic allocation, permissions on /tmp do not persist across machine power cycles, and scripting an init task to set permissions on the mounted disk is not trivial as its hard to detect when the actual mount operation is completed.

**Comment by ahmetalpbalkan** [comment]
@kemhof is this issue about changing the owner/group of the mount point?

I believe we are consistent with Windows (and other cloud providers') behavior here by letting only `root` write to the resource disk (`/mnt` or `/mnt/resource`).

If you need to customize it for yourself, you can have a startup script (or a cloud-init/cloud-config script through CustomData field on the virtual machine) to `chmod`/`chgrp` these mountpoints.
