### ISSUE TITLE
Agent version is WALinuxAgent-2.0.16 even in the new agents

### ISSUE THREAD

**Issue by chubin** [Azure/WALinuxAgent#1133]
```
$ grep GuestAgentVersion.=.\" bin/waagent2.0
GuestAgentVersion = "WALinuxAgent-2.0.16"
```

I can't believe that it is a bug, I suppose that it is intentionally, but what is the reason for that?

**Comment by hglkrijger** [comment]
`bin/waagent-2.0` is an older version of the agent which is no longer supported or maintained. We are forced to keep it because several extensions have taken a dependency on it which we cannot yet break.
