### ISSUE TITLE
Telemetry Should Include Additional IMDS Metadata

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1137]
The latest version of IMDS includes the following fields that should be considered for inclusion:

 1. zone
 1. vmScaleSetName

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#instance-metadata-data-categories

**Comment by boumenot** [comment]
It isn't clear that vmScaleSetName is actually needed because it is already part of the RoleInstanceName.

**Comment by jasonzio** [comment]
If it has to be parsed out of RoleInstanceName, it can't be indexed (and thus searched-for with efficiency).
