### ISSUE TITLE
very high disk usage

### ISSUE THREAD

**Issue by toutougabi** [Azure/WALinuxAgent#1139]
I started noticing an increase in cost of my Azure virtual machines in the last months, finally tracked the additionnal cost to massives amounts of disk writes and deletes.

Once in the server, about every 2 secondes, i notice upwards of 100mbps per second spike from the agent

This is the result from iotop
103400 be/4 root       10.73 K/s  161.33 M/s  0.00 %  2.78 % python3 -u bin/WALinuxAgent-2.2.25-py2.7.egg -run-exthandlers

i'm running ubuntu 16.04 LTS with Docker version 17.05.0-ce, build 89658be

what could be the cause of this ?

regards,
GG

**Comment by toutougabi** [comment]
After a minute of using iotop to monitor data accumulation, here's the result

103400 be/4 root        180.00 K      2.36 G  0.00 %  1.45 % python3 -u bin/WALinuxAgent-2.2.25-py2.7.egg -run-exthandlers

Over 2GB of data written to disk by the agent in a minute, no wonder our storage IO costs are high...

**Comment by boumenot** [comment]
What is the agent writing?  We do not observe this in our own tests.

**Comment by toutougabi** [comment]
I know to sda but other than that, i have no visibility exactly where it's writing...

**Comment by boumenot** [comment]
I am timing this issue out.  Please re-open if you can provide data.

**Comment by ICTIntergrators** [comment]
I had the same issue. I found the below error in the /var/log/waagent.log. It was repeating every so many seconds.

ERROR Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=[ExtensionError] Non-zero exit code: 1, omsagent.py -disable, duration=0

I removed omsagent which restored the disk usage. My one was writing over a TB per day and causing slow response times. 

I haven't reinstall OMS to see if it resolves.

Hope this helps.

**Comment by irab** [comment]
Same here, raising a ticket next week.

**Comment by flyinprogrammer** [comment]
did anyone ever figure this out - i'm seeing the same exact behavior

**Comment by toutougabi** [comment]
Nope sorry, same as the OMS agent. Both agents for linux caused us tons of issues. We have moved most of our stuff to AKS so we no longer need to manage the issue but it's certainly a bad point for linux workloads in azure.

**Comment by vrdmr** [comment]
This is related to #1342. I have taken up this work item.

**Comment by MaxWinterstein** [comment]
Same here. Installed agent when going through security advisory. Ubuntu 16.04. Lead to extrem slow inserts on a MongoDB instance, sometimes more than 10 seconds.

It produced 8.7TB Traffic within about 2 two weeks. Not cool.

**Comment by vrdmr** [comment]
#1342 is fixed. The fix (#1431) went in to 2.2.35 and is deployed.

Closing this issue.
