### ISSUE TITLE
FreeBSD swap issues

### ISSUE THREAD

**Issue by kormic911** [Azure/WALinuxAgent#1144]
Hey guys,

I get the following errors when enabling swap on a FreeBSD 11.1 vm in Azure

> 2018/05/02 22:59:28.956032 INFO Create swap file
> 2018/05/02 22:59:28.966853 ERROR Command: 'umask 0077 && fallocate -l 1073741824 '/mnt/resource/swapfile''
> 2018/05/02 22:59:28.976805 ERROR Return code: 127
> 2018/05/02 22:59:28.982007 ERROR Result: /bin/sh: fallocate: not found
> 
> 2018/05/02 22:59:28.989423 INFO fallocate unsuccessful, falling back to dd
> 2018/05/02 23:03:06.302613 INFO dd successful
> 2018/05/02 23:03:06.350612 ERROR Command: 'mkswap /mnt/resource/swapfile'
> 2018/05/02 23:03:06.358502 ERROR Return code: 127
> 2018/05/02 23:03:06.364548 ERROR Result: /bin/sh: mkswap: not found
> 2018/05/02 23:03:06.377821 ERROR Command: 'swapon /mnt/resource/swapfile'
> 2018/05/02 23:03:06.447080 ERROR Return code: 1
> 2018/05/02 23:03:06.458015 ERROR Result: swapon: /mnt/resource/swapfile: Block device required
> 2018/05/02 23:03:06.467834 ERROR Failed to enable swap [000005] /mnt/resource/swapfile

Perhaps we can allow the /mnt/resource partition being formatted as swap (currently only ufs is supported on bsd) and just mounting the entire partition, otherwise https://www.freebsd.org/doc/handbook/adding-swap-space.html suggests adding the swapfile as a md99 device to fstab.

> waagent -version
> WALinuxAgent-2.2.14 running on freebsd 11.1
> Python: 2.7.13
> Goal state agent: 2.2.14

Thanks

**Comment by hglkrijger** [comment]
Feel free to submit a PR.
