### ISSUE TITLE
walinuxagent sends fabric traffic to public IPs (creating the possibility of MITM attacks?)

### ISSUE THREAD

**Issue by eruditej** [Azure/WALinuxAgent#1149]
Pre November, the agent mostly used http/168.63.129.16 for communication but in some update started making unlogged calls to https/443 to various public IPs in Azure.

We noticed this when our virtual firewall became saturated with this traffic after the Spectre reboots Jan 4th when all the walinuxagents auto-updated. The fabric traffic was being routed.

We mitigated this by creating static routes for the IP blocks being hit most.

Other users reported this to you in other issues since the traffic isn't charged as egress from the VM itself, but the traffic is no longer 'invisible' if you route it through a virtual firewall.

netstat -a | grep http | sort
tcp        0      0 172.19.21.40:45114      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45122      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45130      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45154      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45162      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45172      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45180      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45188      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45196      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45204      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:45260      blob.sn4prdstr09a:https TIME_WAIT
tcp        0      0 172.19.21.40:49358      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49366      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49432      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49440      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49448      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49456      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49464      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49472      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:49488      blob.sn4prdstr01a:https TIME_WAIT
tcp        0      0 172.19.21.40:53922      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53924      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53930      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53932      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53938      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53940      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53946      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53948      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53954      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53956      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53962      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53964      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53970      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53972      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53980      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53982      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53988      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53990      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53996      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:53998      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54004      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54006      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54012      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54014      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54020      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54022      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54028      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54030      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54036      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54038      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54044      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54046      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54052      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54054      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54060      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54062      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54068      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54070      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54076      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:54078      queue.sn4prdstp02:https TIME_WAIT
tcp        0      0 172.19.21.40:59394      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59402      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59410      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59418      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59426      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59434      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59442      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59450      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59452      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59460      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59468      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59476      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59484      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59492      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59500      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59508      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59516      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59524      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59532      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59540      168.63.129.16:http      TIME_WAIT
tcp        0      0 172.19.21.40:59548      168.63.129.16:http      TIME_WAIT

**Comment by boumenot** [comment]
What do you mean by *fabric* traffic?

The agent has always reached out to the public Internet to post the status of the VM.  Status is posted to an Azure blob storage account.  There has been no change in this regard.  

If a customer disables public Internet access the agent will fallback to a non-public service that will post the status to Azure blob storage on its behalf.

**Comment by eruditej** [comment]
https://github.com/Azure/WALinuxAgent/issues/931

Perhaps it was unnoticed previously because there was less data? On Jan 4th, the agent was updated for a sizable number of machines and due to the already reported and closed as 'enhancement' issue, it flooded our firewall.

You are saying VM status accounts for all this traffic?

**Comment by eruditej** [comment]
walinuxagent is the agent that enables basic operations like shutting the vm on and off via the portal.

i call that 'fabric traffic'

I dont get charged for the packets to on/off a VM, they go through the fabric.

**Comment by boumenot** [comment]
Thank you for clarifying because we call an internal piece of Azure by the name *Fabric*, so I wanted to make sure we were using the same terms.

I don't know what the traffic is that you are seeing.  I can make an educated guess though.  If the traffic is originating from the agent process, and it destined for Azure blob storage it is most likely status blob updates.  These are small JSON documents that are sent every **3** seconds.  These documents contain information about the VM's agent and extensions.  You should be able to review this with a network capture tool if you would like to confirm.

If the agent cannot reach Azure blob storage through its public IP address it will send the data out via the 168.x.x.x address.

The agent is only responsible for extension life-cycle and sending a heartbeat signal upstream.  The heartbeat indicates the VM agent is alive, which can be used when considering if an extension should be installed on a VM or not.  The agent does not help with shutdown or other basic VM operations.  I define basic as start, stop, shutdown, and reboot.

**Comment by eruditej** [comment]
what's the workaround for making it send the data via the internal IP?

iptables drop outbound 443?

We think this data should be handled via the 168 address. We need to make
it take that path in order to untangle the static routes we had to make in
order to let it bypass our vfw.

**Comment by boumenot** [comment]
If you block traffic to Azure blob storage the agent will retry until failure, and then switch to the internal IP.  There is no configuration knob at this time to make it start that way.

I think your iptables rule is sufficient to make it fail.

**Comment by eruditej** [comment]
the downside being, some things actually do outbound 443 intentionally. and
even then we might want to intentionally store something in a blob.

is there a reason tbis doesn't default to the 168 ip?

**Comment by eruditej** [comment]
I can keep all the traffic routed through the hypervisor by using cgroups to force the route for the walinuxagent process to use the wire IP as the default route.

However, this is very hacky.

If someone can intercept my routed status traffic and alter the results, it can trigger automation based on status. I still consider routing walinuxagent traffic over public networks to be a possible security risk and adds complexity since users could unintentionally block status updates via their own network configs.

Status should go through the wire IP by default.

**Comment by boumenot** [comment]
The public traffic is over HTTPS.  The status blob is a statement of the VM's health not a document to take action against.

There is already a conversation about using 168 exclusively, but we have not made a decision yet.

I think your question has been addressed, so I am closing this issue.

**Comment by eruditej** [comment]
People create runbooks that are triggered by VM health. Is it getting VM
heath via a different mechanism or through traffic routed over public IP?

**Comment by jasonzio** [comment]
Whether the agent writes to the status blob directly, or the host writes to the status blob on behalf of the agent (because the agent passed status via the 168.x.x.x connection), the network path from the host to the storage account is identical. I’m pretty sure that path never goes over public networks. In any event, as Chris pointed out, the status blob updates are sent over HTTPS and are thus confidential and tamper-proof.

**Comment by eruditej** [comment]
you do not understand azure networking

traffic to public IPs is routed, place a virtual firewall in front of your
vms as their default route. the status traffic will hit it.

traffic to 168 is visible only to azure and the host making the call

https is not magic either and you have exposed agent traffic to ssl zero
days.

q.e.d.

**Comment by jasonzio** [comment]
Once the host receives the status blob from the guest via net 168, the host then writes the status blob to exactly the same storage blob that the guest tried (and failed) to write to. Since the host doesn’t have the same firewalls your guest VM might have, the host’s access to storage is unimpeded. Net result: whether the guest writes directly to storage or the host writes to storage on the guest’s behalf, the actual IP subnets traversed by that data are identical.

When I said “that path never goes over public networks”, I meant precisely and only what I said. The traffic is routed, yes, but the IP subnets those packets traverse are all part of Microsoft’s internal network.

**Comment by eruditej** [comment]
There is a large difference between front side traffic and backside
traffic. With 168, the traffic is always backside. no other guest can see
it.

With public IPs. the traffic is front side and I can see it with wireshark
on hosts it passes through.

does that taxonomy work for you?

**Comment by GarethRUK** [comment]
I agree. This traffic should be on backside via the 168 address and shouldn't by default go over the front-side.

**Comment by eruditej** [comment]
workaround
HttpProxy.Host=127.0.0.1
HttpProxy.Port=1  
#1 is the tcpmux port and unless you have the initials K.S.B. you probably arent using it

Connect to **public** IP fails and it fast fails back to 168.
