### ISSUE TITLE
Linux Agent should log VM IP address, NIC state and route table

### ISSUE THREAD

**Issue by ritewari** [Azure/WALinuxAgent#1152]
Linux Agent should log VM IP address, NIC state and route table

**Comment by paulmey** [comment]
It might be nice if the agent logged this periodically and perhaps also when routing/network `IOError`s are caught? I'd also like to add iptables to the list, although that gets big really quick. Unless there is an easy way to see if a TCP packet to a specific address was dropped by local iptables config, the agent could log a suggestion to check `iptables -L` to see if traffic to the address is blocked.

**Comment by jasonzio** [comment]
From the [netfilter FAQ](https://netfilter.org/documentation/FAQ/netfilter-faq-3.html#ss3.18):

> 3.18 Why isn't the 'iptables -C' (--check) option implemented? 
> Well, first of all, we're lazy ;). To be honest, implementing a check option is almost impossible as soon as you start to do stateful firewalling. Traditional stateless firewalling bases it's decision just on information present in the packets header. But with connection tracking (and '-m state' based rules), the outcome of the filtering decision depends on header+payload, as well as header+payload of previous packets within this connection.

**Comment by paulmey** [comment]
yeah, the only practical way I have found is to `iptables -I OUTPUT -t raw -p tcp -d $wireserverip -j TRACE` (as well as for the PREROUTING chain) and then grep a packet in dmesg by ID to see what the last rule is that it hits... That's not easy to automate...

**Comment by jasonzio** [comment]
#1222 logs route table at startup and any time it changes.

**Comment by jasonzio** [comment]
#1229 logs NIC state at startup and when it changes.
