### ISSUE TITLE
Is the WALinuxAgent still required when using cloud-init ?

### ISSUE THREAD

**Issue by LW81** [Azure/WALinuxAgent#1153]
Hi,

we are preparing custom RHEL images for Azure and we are planning to use cloud-init as the methodology to configure the VM instances created from the image.

What's not clear to me after reading the docs is whether the WALinuxAgent is still required as well ?!

Ideally we can avoid it, as this would allow us to more or less use the same image for onprem OpenStack deployments as well as Azure usage

Thanks for the help in advance.

**Comment by LW81** [comment]
Hi folks,

do you have an update for me on this ?

**Comment by danielsollondon** [comment]
Apologies for the delay, currently we do not support running Linux VMs without the Linux Agent, but stay tuned.

**Comment by hglkrijger** [comment]
Closing for now.

**Comment by jgallucci32** [comment]
For reference purposes:
https://cloudinit.readthedocs.io/en/latest/topics/datasources/azure.html

> In order to operate correctly, cloud-init needs walinuxagent to provide much of the interaction with azure.
