### ISSUE TITLE
Agent can leak http(lib, .client) connections

### ISSUE THREAD

**Issue by jasonzio** [Azure/WALinuxAgent#1156]
The restlib.http_{request,get,put,head,push}() methods all return a raw HTTPResponse object, and the caller is expected to either completely consume the body (until resp.read() indicates there's no more data in the body, or resp.closed is True), or to explicitly close the connection. Or both, depending on the exact vintage of pythonlib in use.

There are two problems with this approach.

- restlib's methods don't expose the connection to the caller, so there's no safe way for the caller to find the connection to close it.
- many callers have multiple exit points after receiving the HTTPResponse object, making cleanup an ugly thing.

Restlib should be changed to return a context-manager object which captures both the HTTPConnection and HTTPResponse objects. This context manager would return the HTTPResponse object from the `__enter()__` method, and the `__exit()__` method would call close() on the HTTPConnection object.

Python2's httplib HTTPResponse object doesn't support context manager behavior at all, but Python3 claims to do this correctly. A helper should be added to common.future to provide the appropriate context manager (the HTTPResponse for Python3, our own implementation for Python2).

**Comment by boumenot** [comment]
This was fixed in #1194.
