### ISSUE TITLE
Ubuntu 16.04 update from 2.2.20 -> 2.2.25

### ISSUE THREAD

**Issue by zeronines** [Azure/WALinuxAgent#1163]
Trying to update to 2.2.25 on Ubuntu 2.2.25 

keith@v8buildx:~/WALinuxAgent-2.2.25$ sudo python setup.py install --register-service
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from azurelinuxagent.common.version import AGENT_NAME, AGENT_VERSION, \
ImportError: No module named azurelinuxagent.common.version
keith@v8buildx:~/WALinuxAgent-2.2.25$ waagent -version
WALinuxAgent-2.2.20 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.20

It appears I'm missing something, any guidance will help.

**Comment by hglkrijger** [comment]
Ubuntu uses python3.

**Comment by zeronines** [comment]
Is there a way to run the script with Python3 or do I have to try and revert back to Python2?

 

Keith.

**Comment by zeronines** [comment]
Hans,

 

Thanks for your input.  We were able to run the setup.py still found errors.

 

keith@v8buildx:~/WALinuxAgent-2.2.25$ sudo python3 setup.py install --register-service

running install

running build

running build_py

running install_lib

running install_data

copying bin/waagent -> /usr/sbin

copying bin/waagent2.0 -> /usr/sbin

copying init/ubuntu/walinuxagent.service -> /lib/systemd/system

running install_egg_info

running egg_info

writing WALinuxAgent.egg-info/PKG-INFO

writing dependency_links to WALinuxAgent.egg-info/dependency_links.txt

writing top-level names to WALinuxAgent.egg-info/top_level.txt

reading manifest file 'WALinuxAgent.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'WALinuxAgent.egg-info/SOURCES.txt'

removing '/usr/local/lib/python3.5/dist-packages/WALinuxAgent-2.2.20.egg-info' (and everything under it)

Copying WALinuxAgent.egg-info to /usr/local/lib/python3.5/dist-packages/WALinuxAgent-2.2.20.egg-info

running install_scripts

keith@v8buildx:~/WALinuxAgent-2.2.25$ sudo service walinuxagent restart

keith@v8buildx:~/WALinuxAgent-2.2.25$ waagent -version

Traceback (most recent call last):

  File "/usr/sbin/waagent", line 31, in <module>

    import azurelinuxagent.agent as agent

ImportError: No module named azurelinuxagent.agent

 

 

Any guidance?

 

Thanks,

 

Keith.

**Comment by hglkrijger** [comment]
Make sure the agent is running under Python 3:
```
cat bin/waagent | sed 's_#!/usr/bin/env python_#!/usr/bin/env python3_' > /usr/sbin/waagent
```
Alternatively you can skip the `--register-service` on a fresh VM.

We generally recommend folks do not install or upgrade from source to avoid these issues. Is there a specific need to use source?

**Comment by zeronines** [comment]
We used an Ubuntu image from azure with waagent 2.2.20.

 

We are syndicating our software to Azure Stack on our Microsoft contact mentioned that we should use v2.2.25 and sent us to the github link.

 

Are you aware of any salient points to use v2.2.25 in Azure Stack, or shoud we publish with v2.2.20?

 

Thanks for you help on this .

 

Keith.

**Comment by hglkrijger** [comment]
You may want to check with @boumenot on this, as he has managed the last few releases. In general I would recommend you stick to what is in the image and/or the latest available through the package manager. Usually we keep up to date release notes as to what has changed between releases.
