### ISSUE TITLE
Add addition error codes in linux agent for better classification of errors.

### ISSUE THREAD

**Issue by ritewari** [Azure/WALinuxAgent#1173]
1.	Wire Server not reachable – No interface detected on guest or interface disconnected.
2.	Wire Server not reachable – No IPAddress on the NIC or APIPA (Dump DHCP retry on Linux)
3.	Wire Server not reachable – No route found on route table.
4.	Wire Server not reachable – Interface up with a valid IPaddress – This category NIC is actually up and running and has IPaddress but still wire server is not reachable. This could be result of some firewall rule or Iptables block or issue with TCP stack on the VM.

**Comment by jasonzio** [comment]
This is too large a task to bite off, as the number of places where "Not Reachable" might be detected is awfully large. The enhanced logging requested in #1152 would seem to provide all the information required by a human to determine the reason for "Network unreachable".

**Comment by ritewari** [comment]
we need this info so that reporting can be automated, manual parsing will not be scaleable

**Comment by hglkrijger** [comment]
@ritewari I feel like there is not enough information here to proceed with making changes. Are you working with anyone on our team, or can you submit a PR for this?

**Comment by hglkrijger** [comment]
Timing this out
