### ISSUE TITLE
Adviosry about waagent blob status update/download extension packages 

### ISSUE THREAD

**Issue by sundaxi** [Azure/WALinuxAgent#1193]
Hi Team, 

I am reading the source code of waagent, it seems to me that when waagent download extension/agent bits or updated blob status, it used hostplugin protocol <ENDPOINT>:32526. It looks very like the that the download or update blob status traffic goes through hostplugin protocol and Wireserver helped to route the traffic to public network(Microsoft storage account page/block blob). 

So from guest os perspective, it should doesn't have TCP connection between waagent and Microsoft storage account directly, is that correct? 

Can you please help to confirm it? 

Great thanks

**Comment by boumenot** [comment]
Can you please explain the issue you are most concerned with first?  You are asking for implementation details, which I am happy to share, but I would like to know for what.

**Comment by sundaxi** [comment]
Thanks @boumenot 
The issue is some of VMs setup tcp connection with status blob:443 every 3 secs which used the public traffic by default and it will failover to use HostPlugin protocol if the storage account is unreachable. This will cost cx's network traffic consumption by default. 

I am wondering if there is any method to use hostplugin by default instead of connect to public storage account directly?

In my test environment, it seems some VM used hostplugin by default(one of my ubuntu server)

Great thanks in advance.

**Comment by sundaxi** [comment]
Never mind, I went through the waagent code and now I understand the behavior well. Thanks
