### ISSUE TITLE
Add support for RDMA on RHEL 7.5

### ISSUE THREAD

**Issue by iamshital** [Azure/WALinuxAgent#1198]
We're getting following issue on RHEL 7.5 when tried to enable RDMA:

`2018/06/01 06:38:50.399639 INFO Daemon No RDMA handler exists for distro='Red Hat Enterprise Linux Server' version='7.5'`
`2018/06/01 06:38:50.400702 INFO Daemon Activate resource disk`
`2018/06/01 06:38:50.414274 INFO Daemon Examining partition table`
`2018/06/01 06:38:50.508980 INFO Daemon GPT not detected, determining filesystem`
`2018/06/01 06:38:50.538277 INFO Daemon sfdisk with --part-type failed [1], retrying with -c`
`2018/06/01 06:38:50.545569 INFO Daemon sfdisk -c -f /dev/sdb 1 -n succeeded`
`2018/06/01 06:38:50.545898 INFO Daemon The partition type is 83`
`2018/06/01 06:38:50.546868 INFO Daemon Mount resource disk [mount /dev/sdb1 /mnt/resource]`
`2018/06/01 06:38:50.794194 INFO Daemon Resource disk /dev/sdb is mounted at /mnt/resource with ext4`
`2018/06/01 06:38:50.801390 INFO Daemon Clean protocol`
`2018/06/01 06:38:50.804130 INFO Daemon Provisioning already completed, skipping.`
`2018/06/01 06:38:50.804662 ERROR Daemon RDMAHandler.install_driver not implemented
`

We've RDMA driver available for RHEL 7.5 and need to test them asap.
If you need any other information, please contact me at : v-shisav@microsoft.com

**Comment by danielsollondon** [comment]
@iamshital - please can you raise a PR for this?
