### ISSUE TITLE
F5 Image use DNS cache as WireServer Endpoint caused provisioning timeout

### ISSUE THREAD

**Issue by sundaxi** [Azure/WALinuxAgent#1205]
Hi Team, 

I have cx deployed F5 Big IP image from Azure protal with custom DNS. And Waagent determine the endpoint via dhcp leases with option DNS

Agent tested the route table for 168.63.129.16 firstly but failed 
2018/06/11 16:06:43.574368 INFO Test for route to 168.63.129.16
2018/06/11 16:06:43.575654 WARNING No route exists to 168.63.129.16

Then Agent check the endpoint via dhcp_cache_exists method, and codes below to get the Endpoint via DNS IP address
Codes below: 
if not expired and cached_endpoint is not None and has_option_245:
     endpoint = cached_endpoint

Logs below: 
018/06/11 16:06:43.579319 INFO looking for leases in path [/var/lib/dhclient/dhclient*.leases]
2018/06/11 16:06:43.580846 INFO dhcp entry:172.31.9.4,10.224.128.4, 245:True, expired:False
2018/06/11 16:06:43.581515 INFO found endpoint [172.31.9.4,10.224.128.4]
2018/06/11 16:06:43.582177 INFO cached endpoint found [172.31.9.4,10.224.128.4]

As checked the DHCP lease file, the option 245 was set as 168.63.129.16 but it seems in the agent code, if the route table for 168.63.129.16 doesn't not exsit, agent will use DNS server as Wire Endpoint alternatively. 

In this case, agent send Wire restful API to DNS server instead and cannot get any response. Provisioning will be timeout from Azure Platform. Would you please advise if it's by design. 

Would you please help me to understand why or in any scenario, guest os needs to use DNS server as WireServer. As I consulted with Platform Engineer, it seems from Azure HOST, wireserver can only be configured as 168.63.129.16. Please kindly advise!

In addition, for F5 image, it seems raw socket doesn't work to get the mac address via fcntl as well. 

Full waggent logs below 
2018/06/11 16:06:43.570932 INFO WireServer endpoint is not found. Rerun dhcp handler
2018/06/11 16:06:43.574368 INFO Test for route to 168.63.129.16
2018/06/11 16:06:43.575654 WARNING No route exists to 168.63.129.16
2018/06/11 16:06:43.578624 INFO Checking for dhcp lease cache
2018/06/11 16:06:43.579319 INFO looking for leases in path [/var/lib/dhclient/dhclient*.leases]
2018/06/11 16:06:43.580846 INFO dhcp entry:172.31.9.4,10.224.128.4, 245:True, expired:False
2018/06/11 16:06:43.581515 INFO found endpoint [172.31.9.4,10.224.128.4]
2018/06/11 16:06:43.582177 INFO cached endpoint found [172.31.9.4,10.224.128.4]
2018/06/11 16:06:43.582934 INFO Cache exists [True]
2018/06/11 16:06:43.583315 INFO Wire server endpoint:172.31.9.4,10.224.128.4
2018/06/11 16:07:14.808880 INFO WireServer is not responding. Reset endpoint
2018/06/11 16:07:14.810884 INFO Protocol endpoint not found: WireProtocol, [ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] GET http://172.31.9.4,10.224.128.4/?comp=versions -- IOError [Errno -2] Name or service not known -- 6 attempts made
2018/06/11 16:07:14.811394 INFO Retry detect protocols: retry=0
2018/06/11 16:07:19.818527 INFO WireServer endpoint is not found. Rerun dhcp handler
2018/06/11 16:07:19.820883 INFO Test for route to 168.63.129.16
2018/06/11 16:07:19.833267 WARNING No route exists to 168.63.129.16
2018/06/11 16:07:19.837162 INFO Send dhcp request
2018/06/11 16:07:19.891604 ERROR Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/daemon/main.py", line 77, in run
    self.daemon(child_args)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/daemon/main.py", line 123, in daemon
    self.provision_handler.run()
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/pa/provision/default.py", line 81, in run
    self.protocol_util.get_protocol_by_file()
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/util.py", line 305, in get_protocol_by_file
    self.protocol = self._detect_protocol(protocols)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/util.py", line 186, in _detect_protocol
    if protocol_name == "WireProtocol" \
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/util.py", line 153, in _detect_wire_protocol
    self.dhcp_handler.run()
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/dhcp.py", line 63, in run
    self.send_dhcp_req()
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/dhcp.py", line 159, in send_dhcp_req
    mac_addr = self.osutil.get_mac_addr()
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/osutil/f5.py", line 130, in get_mac_addr
    addr = self.get_if_mac(self.mgmt)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/osutil/default.py", line 674, in get_if_mac
    info = fcntl.ioctl(sock.fileno(), 0x8927, param)
IOError: [Errno 19] No such device
, duration=0

**Comment by sundaxi** [comment]
can anyone look into this issue please?

**Comment by boumenot** [comment]
I am not sure we can be of any help. F5 is not on our list of endorsed distros, and the agent is a version that was pulled.  We do not support appliances, but we do incorporate appliance patches to make it easier to ship the agent.

I recommend you follow up with F5.

**Comment by sundaxi** [comment]
@boumenot F5 is BIG IP which should be supported by Waagent.  I do see the bigIP Class in azurelinux.common.osutil.bigip. 
class BigIpOSUtil(DefaultOSUtil)

I need your help to explain why if checking routing table in /proc/net/route failed, agent needs to check DNS cache instead. 

In addition, if multiple DNS configured, for example 8.8.8.8;123.123.123.123, the agent treats the endpoint as [8.8.8.8 123.123.123.123], it's definitely an issue, isn't ?

**Comment by depperson** [comment]
This was fixed in the agent in #1176.  Recent BIG-IP versoions (read: 13+) use a newer waagent with this fix.  Older BIG-IP versions deployed via recent ARM templates also have a workaround for this.  Deploying BIG-IP v12.x via Marketplace while also using custom DNS on your vNet is currently the only way to run into this problem.
