### ISSUE TITLE
Waagent Logs SAS Keys

### ISSUE THREAD

**Issue by wzamlynny** [Azure/WALinuxAgent#1213]
SAS keys can be found in waagent.log, for example when an HTTP error occurs the full request including SAS key is logged. These should be removed and not logged.

**Comment by jasonzio** [comment]
Please provide example log messages (with the SAS redacted, of course).

**Comment by wzamlynny** [comment]
Here are two examples with the SAS being leaked:

> 2016/10/02 15:39:46 ERROR:Socket IOError The read operation timed out, args:('The read operation timed out',)
> 2016/10/02 15:39:46 ERROR:Retry=0
> **2016/10/02 15:39:46 ERROR:HTTP Req: HEAD https://centos74794.blob.core.windows.net/vhds/craigw-centos7.5c01b5aa-89ab-4036-bcf9-195ed3dd4dea.status?<SAS-KEY\>**
> 2016/10/02 15:39:46 ERROR:HTTP Req: Data=None
> 2016/10/02 15:39:46 ERROR:HTTP Req: Header={'x-ms-version': '2014-02-14', 'x-ms-date': '2016-10-02T15:39:36Z'}
> 2016/10/02 15:39:46 ERROR:HTTP Err: response is empty.





> 2016/10/05 04:01:32 ERROR:Socket IOError The read operation timed out, args:('The read operation timed out',)
> 2016/10/05 04:01:32 ERROR:Retry=0
> **2016/10/05 04:01:32 ERROR:HTTP Req: PUT https://centos74794.blob.core.windows.net/vhds/craigw-centos7.5c01b5aa-89ab-4036-bcf9-195ed3dd4dea.status?<SAS-KEY\>**
> 2016/10/05 04:01:32 ERROR:HTTP Req: Data={"version":"1.0","timestampUTC":"2016-10-05T04:01:21Z","aggregateStatus":{"guestAgentStatus":{"version":"WALinuxAgent-2.0.16","status":"Ready","formattedMessage":{"lang":"en-US","message":"GuestAgent is running and accepting new configurations."}},"handlerAggregateStatus":[{"status": "Ready", "runtimeSettingsStatus": {"settingsStatus": {"status": {"status": "success", "formattedMessage": {"lang": "en-US", "message": "Enable succeeded"}, "operation": "Enable", "code": "0", "name": "Microsoft.OSTCExtensions.LinuxDiagnostic"}, "timestampUTC": "2016-09-14T07:18:14Z"}, "sequenceNumber": "0"}, "handlerVersion": "2.3.9007", "handlerName": "Microsoft.OSTCExtensions.LinuxDiagnostic"}]}}
> 2016/10/05 04:01:32 ERROR:HTTP Req: Header={'Content-Length': '686', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'BlockBlob', 'x-ms-date': '2016-10-05T04:01:21Z'}
> 2016/10/05 04:01:32 ERROR:HTTP Err: response i

s empty.

**Comment by vrdmr** [comment]
Picking up this bug.
