### ISSUE TITLE
'waagent -deprovision' on Ubuntu 1804 breaks internet connnectivity

### ISSUE THREAD

**Issue by iamshital** [Azure/WALinuxAgent#1215]
In latest Ubuntu 1804 azure image, when we tried to capture a customized image, and performed `waagent -deprovision`, we couldn't able to connect to internet due to lost `/etc/resolv.conf file.` 

The VMs created by this customized image gets provisioned successfully but they fail to connect to Internet.

**Comment by boumenot** [comment]
This appears to be a dupe of #1151, and is fixed in master.
