### ISSUE TITLE
osutil class hierarchy is half-baked

### ISSUE THREAD

**Issue by jasonzio** [Azure/WALinuxAgent#1216]
In the beginning, osutil was intended to isolate differences between Linux distros. Any operation that had some distro difference got a baseline (common denominator) implementation in default.py, and the distro(s) that differed overrode the method.

Then FreeBSD and OpenBSD were added. Instead of refactoring then (to create linux.py), the BSDs just overrode what they needed to, with many functions in default.py exposed but unused.

Changing the implementation of anything in default.py has a high likelihood of breaking something in BSD support because there's no clear way to know what the osutil exposed surface is supposed to be. There are many functions in osutil that are exposed solely to support tests... BSD tests appear to be a subset of Linux tests.

Osutil should really be refactored to have a clean interface that the rest of the agent and test suite can rely upon, and the Linux and BSD inheritance hierarchies should be separated (meeting only at the interface, contractual, root).

**Comment by hglkrijger** [comment]
@jasonzio we decided to close this in triage, please reopen if and when you choose to work on it.
