### ISSUE TITLE
Issues with waagent.conf and swap

### ISSUE THREAD

**Issue by psinger** [Azure/WALinuxAgent#1220]
I am currently trying to set-up swap on my Ubuntu 16 VM. I am following the standard procedure and have set waagent.conf accordingly:

    ResourceDisk.Format=y
    ResourceDisk.Filesystem=ext4
    ResourceDisk.MountPoint=/mnt/resource
    ResourceDisk.EnableSwap=y
    ResourceDisk.SwapSizeMB=64000

Just restarting the service does nothing. After rebooting, if I instantly type ```free -m``` I can see the swap. But a moment later it is gone. When I re-check waagent.conf also ```ResourceDisk.Format``` is set to no automatically: ```ResourceDisk.Format=n```.

On my other vms it works flawlessly. The only difference is, that on this VM I have an encrypted disk, lsblk output:

    sdb                                        8:16   0   678G  0 disk
    └─sdb1                                     8:17   0   678G  0 part
      └─xxx                                  253:1    0   678G  0 crypt /mnt/resource

Any ideas?

**Comment by hglkrijger** [comment]
Could you take a look at `/var/log/waagent.log` and see if there is anything interesting in there? There is nothing in the agent which ever writes to `/etc/waagent.conf` so I find that suspicious. Perhaps start by trying to determine what is changing that file?

Feel free to reopen if you find anything which might be agent related.

**Comment by psinger** [comment]
@hglkrijger It probably has something to do with disk encryption and order of operations:

    2018/07/18 09:54:19.487394 WARNING Failed to mount resource disk. Retry mounting after re-reading partition info.
    2018/07/18 09:54:19.504318 ERROR Command: 'mount /dev/sdb1 /mnt/resource'
    2018/07/18 09:54:19.505770 ERROR Return code: 32
    2018/07/18 09:54:19.506683 ERROR Result: mount: unknown filesystem type 'crypto_LUKS'

**Comment by hglkrijger** [comment]
@psinger is this Azure Disk Encryption, or something else?

**Comment by psinger** [comment]
@hglkrijger Yes, Azure Disk Encryption.

**Comment by hglkrijger** [comment]
@danielsollondon could you please put us in touch with someone from ADE to take a look at this issue?

**Comment by ejarvi** [comment]
When the EncryptFormatAll operation is specified to enable encryption of all data drives (which includes the ephemeral disk), Azure Disk Encryption modifies the waagent.conf file.  This prevents a conflict that would otherwise occur if WALA were to format the ephemeral drive instead of ADE.   Once ADE has formatted and mounted the drive on the encrypted layer it should be ready for use.   If ephemeral disk encryption is not desired, using the standard enable operation at time of enable (rather than encrypt format all) could also bypass this behavior.

**Comment by hglkrijger** [comment]
@psinger let us know if that does not answer your question.

**Comment by psinger** [comment]
@hglkrijger @ejarvi It partly explains what happens, but I am still not sure how to enable swap then.
