### ISSUE TITLE
Need clear signal that provisioning has completed

### ISSUE THREAD

**Issue by jim-minter** [Azure/WALinuxAgent#1223]
Hit this with 2.2.18 so for all I know it might be solved in a newer release, or it might be a case that I need to read the manual.  Anyway:

We hit an issue on RHEL/CentOS where we set WALinuxAgent to format the ephemeral disk and mount it on /var/lib/docker.  Unfortunately it turns out that WALinuxAgent was racing with docker, sometimes they ran concurrently and docker got very broken.

It would be good to have a clear signal that provisioning has completed (e.g. create a file on the filesystem, or use systemd-notify, or something) to make it easier to hold dependent jobs.  The alternatives are parsing the WAAgent log for "provision completed" text, or spinning checking if /mnt/resource (or whatever) is a mountpoint yet.

**Comment by hglkrijger** [comment]
We write `/var/lib/waagent/provisioned` when provisioning is complete.
