### ISSUE TITLE
osutil default get_primary_interface() should be refactored to use get_list_of_routes()

### ISSUE THREAD

**Issue by jasonzio** [Azure/WALinuxAgent#1226]
When get_list_of_routes() and the RouteEntry class from networkutil were added, the rest of osutil's default implementation was left as-is to minimize risk of breakage. Once 2.2.27 (or later) ships, any other code referencing the route table should be altered to use the newly introduced infrastructure.

**Comment by elfosardo** [comment]
hello @jasonzio I put together PR #1377 for this

**Comment by narrieta** [comment]
Fixed by #1377
