### ISSUE TITLE
Failed to send events: 'ascii' codec can't encode character u'\u25cf' in position 123: ordinal not in range(128)

### ISSUE THREAD

**Issue by TechnologyAnimal** [Azure/WALinuxAgent#1227]
I was trying to execute a shell script on a RHEL 7.3 Azure VM using the linux custom script extension. My script worked when being executed locally, but was failing during the CI/CD process. I was trying to gather more information to debug, and get hung up on this ascii encoding error in the waagent.log.

To solve the problem, I ended up adding a bunch of additional logging to my script, which should have been done anyways.  Of course it was a problem with my script, but I wasted so much time trying to troubleshoot what I thought was an encoding problem.

Should I be looking for clues in /var/log/waagent.log or what are the best logs to look at for troubleshooting a problem like this?  Any help is appreciated.

2018/06/21 23:12:16.178650 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 1, duration=156
2018/06/21 23:13:21.242007 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Target handler state: enabled
2018/06/21 23:13:21.281125 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] [Enable] current handler state is: notinstalled
2018/06/21 23:13:21.419888 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Download, message=Download succeeded, duration=98
2018/06/21 23:13:21.425785 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Initialize extension directory
2018/06/21 23:13:21.430850 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Update settings file: 0.settings
2018/06/21 23:13:21.435414 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Install extension [bin/custom-script-shim install]
2018/06/21 23:13:22.444786 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Install, message=Launch command succeeded: bin/custom-script-shim install, duration=1005
2018/06/21 23:13:22.451136 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Enable extension [bin/custom-script-shim enable]
2018/06/21 23:13:23.460535 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Enable, message=Launch command succeeded: bin/custom-script-shim enable, duration=1004
2018/06/21 23:13:23.604040 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 2, duration=2395
**2018/06/21 23:14:15.963156 WARNING Failed to send events: 'ascii' codec can't encode character u'\u25cf' in position 123: ordinal not in range(128)**
2018/06/21 23:27:16.288509 INFO Agent WALinuxAgent-2.2.26 launched with command 'python -u bin/WALinuxAgent-2.2.26-py2.7.egg -run-exthandlers' is successfully running
2018/06/21 23:27:16.296592 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.26 launched with command 'python -u bin/WALinuxAgent-2.2.26-py2.7.egg -run-exthandlers' is successfully running

**Comment by jasonzio** [comment]
Thanks for the problem report. Just for your information, the "Failed to send events" warning refers to the agent health telemetry stream, so it had no bearing on your CSE problem (as you already figured out). As distros move on to using Python3 as their default, this class of error should become less frequent.

Definitely appreciate the problem report.

**Comment by hglkrijger** [comment]
To answer your other question, the best place to look for clues is in the custom script logs, rather than the agent logs. Better than that is to create your own logs, as you ended up doing. Thanks for the report.
