### ISSUE TITLE
Better Support Multiple Telemetry Writers

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1233]
The agent and extensions write telemetry data to /var/lib/waagent/events. There are occasions where there are collisions between various parties. The agent should better support a process for avoiding collisions. One possibility is to support namespaces, so each party only has to manage itself as opposed to itself and all other parties.

The agent uses the current time as the file name, which is why there is a (small) chance of collision.  Maybe a more formalized system like <name>.<timestamp>.tld would be better?

When I was reading the code it was not clear to me how the agent was using the timestamp value, so this system may already work today. If the file name ends in .tld it is assumed to be telemetry.

**Comment by hglkrijger** [comment]
If I understand the above, we are already doing this today. I am closing this out, feel free to reopen if you feel like I missed something.
