### ISSUE TITLE
How to remove Microsoft.Azure.RecoveryServices.VMSnapshotLinux handler?

### ISSUE THREAD

**Issue by enihcam** [Azure/WALinuxAgent#1239]
I tried to enable the backup feature, but it did not work eventually. Now how to remove Microsoft.Azure.RecoveryServices.VMSnapshotLinux handler? It is not shown in portal. Thanks.

```
Jul 06 13:18:04 localhost python[255]: 2018/07/06 13:18:04.180810 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9133.0] Target handler state: enabled
Jul 06 13:18:04 localhost python[255]: 2018/07/06 13:18:04.182688 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9133.0] [Enable] current handler state is: >
Jul 06 13:18:04 localhost python[255]: 2018/07/06 13:18:04.184024 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9133.0] Update settings file: 0.settings
Jul 06 13:18:04 localhost python[255]: 2018/07/06 13:18:04.185622 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9133.0] Enable extension [main/handle.sh en>

```

I tried to rm the /var/lib/waagent, but they were re-created after reboot.

**Comment by boumenot** [comment]
This repository is for WALinuxAgent, not VMSnapshotLinux.  Sorry, I don't know how to uninstall this extension.  If the extension is not visible in portal you will most likely need to use the CLI or an API to delete the extension.  However you enabled the backup feature is where I would start when trying to determine how to disable it.

A quick search turns up some [documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/vmsnapshot-linux) on installing it via the CLI.  There are commands to disable it too.
