### ISSUE TITLE
Azure vm with Ubuntu 15.10 error No module named azurelinuxagent.agent

### ISSUE THREAD

**Issue by hodzanassredin** [Azure/WALinuxAgent#124]
Created fresh vm from azure gallery on prortal with Ubuntu 15.10. Checked "Install the VM Agent"
Result is:

hodza@cltemplate:~$ waagent -deprovision
Traceback (most recent call last):
  File "/usr/sbin/waagent", line 31, in <module>
    import azurelinuxagent.agent as agent
ImportError: No module named azurelinuxagent.agent

**Comment by yuezh** [comment]
Hi, Hodza

In Ubuntu 15.10 image. Agent is installed in python3. Please use the following command to run deprovision.

python3 /usr/sbin/waagent -deprovision

Thanks
Yue

**Comment by hodzanassredin** [comment]
thx it works
