### ISSUE TITLE
'dvd' containing the ovf-env.xml (day0 config from the template) fails to mount

### ISSUE THREAD

**Issue by jimbeauh** [Azure/WALinuxAgent#1242]
Customers are unable to launch Cisco ASAv - BYOL 4 NIC version 9.9.1-5. This ASAv version uses waagent 2.2.20.

Logs from boot diagnostics:

9.9.1.5:

Waagent - 2018/07/05 20:55:38.587424 INFO Clean protocol
Waagent - 2018/07/05 20:55:38.592003 INFO Running default provisioning handler
Waagent - 2018/07/05 20:55:38.598324 INFO Copying ovf-env.xml
Waagent - 2018/07/05 20:55:38.602260 VERBOSE mount_dvd: Deferring to parent method
Waagent - 2018/07/05 20:55:38.608143 VERBOSE get_dvd_device: Deferring to parent class
Waagent - 2018/07/05 20:55:38.614685 VERBOSE Run 'mount'
Waagent - 2018/07/05 20:55:38.621776 VERBOSE get_mount_point: Deferring to parent class
Waagent - 2018/07/05 20:55:38.627750 VERBOSE mount: Deferring to parent method
Waagent - 2018/07/05 20:55:38.632921 VERBOSE Run 'mount -o ro -t udf,iso9660 /dev/hdc /mnt/cdrom/secure'
Waagent - 2018/07/05 20:55:38.716622 WARNING Mounting dvd failed [retry 1/5, sleeping 5 sec]
Waagent - 2018/07/05 20:55:43.739316 VERBOSE mount: Deferring to parent method
Waagent - 2018/07/05 20:55:43.739916 VERBOSE Run 'mount -o ro -t udf,iso9660 /dev/hdc /mnt/cdrom/secure'
Waagent - 2018/07/05 20:55:43.860991 WARNING Mounting dvd failed [retry 2/5, sleeping 5 sec]
Waagent - 2018/07/05 20:55:48.879236 VERBOSE mount: Deferring to parent method
Waagent - 2018/07/05 20:55:48.879849 VERBOSE Run 'mount -o ro -t udf,iso9660 /dev/hdc /mnt/cdrom/secure'
Waagent - 2018/07/05 20:55:48.936803 WARNING Mounting dvd failed [retry 3/5, sleeping 5 sec]
Waagent - 2018/07/05 20:55:53.959288 VERBOSE mount: Deferring to parent method
Waagent - 2018/07/05 20:55:53.959856 VERBOSE Run 'mount -o ro -t udf,iso9660 /dev/hdc /mnt/cdrom/secure'
Waagent - 2018/07/05 20:55:54.041217 WARNING Mounting dvd failed [retry 4/5, sleeping 5 sec]
Waagent - 2018/07/05 20:55:59.059112 VERBOSE mount: Deferring to parent method
Waagent - 2018/07/05 20:55:59.059685 VERBOSE Run 'mount -o ro -t udf,iso9660 /dev/hdc /mnt/cdrom/secure'
Waagent - 2018/07/05 20:55:59.110303 WARNING Mounting dvd failed [retry 5/5, sleeping 5 sec]
Waagent - 2018/07/05 20:56:04.129316 INFO Detect protocol endpoints
Waagent - 2018/07/05 20:56:04.129884 INFO Clean protocol
Waagent - 2018/07/05 20:56:04.133065 INFO Wire server endpoint:168.63.129.16

lina/dev:

Waagent - 2018/07/05 18:17:43.829481 INFO Clean protocol
Waagent - 2018/07/05 18:17:43.830148 INFO Running default provisioning handler
Waagent - 2018/07/05 18:17:43.833055 INFO Copying ovf-env.xml
Waagent - 2018/07/05 18:17:43.833520 VERBOSE mount_dvd: Deferring to parent method
Waagent - 2018/07/05 18:17:43.833940 VERBOSE get_dvd_device: Deferring to parent class
Waagent - 2018/07/05 18:17:43.835314 VERBOSE Run 'mount'
Waagent - 2018/07/05 18:17:43.839239 VERBOSE get_mount_point: Deferring to parent class
Waagent - 2018/07/05 18:17:43.840291 VERBOSE mount: Deferring to parent method
Waagent - 2018/07/05 18:17:43.841244 VERBOSE Run 'mount -o ro -t udf,iso9660 /dev/hdc /mnt/cdrom/secure'
Waagent - 2018/07/05 18:17:43.888326 INFO Successfully mounted dvd
Waagent - 2018/07/05 18:17:43.893724 VERBOSE Load ovf-env.xml
Waagent - 2018/07/05 18:17:43.906597 VERBOSE umount_dvd: Deferring to parent method
Waagent - 2018/07/05 18:17:43.907023 VERBOSE umount: Deferring to parent method
Waagent - 2018/07/05 18:17:43.908301 VERBOSE Run 'umount /mnt/cdrom/secure'
Waagent - 2018/07/05 18:17:43.978169 VERBOSE eject_dvd: Deferring to parent class
Waagent - 2018/07/05 18:17:43.982133 VERBOSE get_dvd_device: Deferring to parent class
Waagent - 2018/07/05 18:17:43.985811 VERBOSE Run 'eject /dev/hdc'
Waagent - 2018/07/05 18:17:43.996594 INFO Detect protocol by file
Waagent - 2018/07/05 18:17:43.999194 INFO Clean protocol
Waagent - 2018/07/05 18:17:44.001554 INFO Wire server endpoint:168.63.129.16

**Comment by danielsollondon** [comment]
worked by sz
