### ISSUE TITLE
Validate compute fields for IMDS

### ISSUE THREAD

**Issue by hglkrijger** [Azure/WALinuxAgent#1249]
We had to remove Compute field validation (#1250) because we cannot yet filter out RDFE vms, we need to add this back.

**Comment by narrieta** [comment]
@jacwil - Is this an issue we will be working on? Thanks

**Comment by jacwil** [comment]
> @jacwil - Is this an issue we will be working on? Thanks

@narrieta - This is something IMDS team will be doing sometime in the future. It is not scheduled work, just on our Backlog.

We are tracking this outside of GitHub so feel free to close this as something to the effect of "will not fix."

**Comment by narrieta** [comment]
thanks, @jacwil ; closing
