### ISSUE TITLE
Can't login to ubuntu vm created from deprovisioned image.

### ISSUE THREAD

**Issue by hodzanassredin** [Azure/WALinuxAgent#125]
Steps to reproduce:
1. Create ubuntu 15.10 with password ssh auth vm in azure
2. ssh to it and run sudo python3 /usr/sbin/waagent -deprovision
3. delete vm
4. create vm from image with password ssh auth
4. try to login from putty
Result:
putty shows "Access denied" message
and in putty logs last line is: password authentication failed

Workaround: reset password to a new one for user(azure portal or azure cli)

**Comment by yuezh** [comment]
You should use "deprovision+user" to remove user account. Otherwise the previous user account will be reserved and if provisioned with the same account, it will fail.

The command is python3 ```/usr/sbin/waagent -deprovision+user```
