### ISSUE TITLE
Repositories Failed

### ISSUE THREAD

**Issue by mrevros** [Azure/WALinuxAgent#1252]
Hi All,
 I can not update the WALinuxAgent service because of mirrorlist failures.
OS RHEL 7.2

 yum check-update WALinuxAgent
Loaded plugins: langpacks, product-id, rhui-lb, search-disabled-repos
epel/x86_64/metalink                                                                                                                                                                                                  |  30 kB  00:00:00
Could not retrieve mirrorlist https://westeurope-cds2.cloudapp.net/pulp/mirror/PA error was
14: curl#6 - "Could not resolve host: westeurope-cds2.cloudapp.net; Name or service not known"

Any help?

Thanks

**Comment by hglkrijger** [comment]
@mrevros we do not own the mirrorlist servers, sorry.
