### ISSUE TITLE
RDMA error on Linux

### ISSUE THREAD

**Issue by devszr** [Azure/WALinuxAgent#1253]
I've experienced this a few times now. On a Linux H16r machine with a CentOS 7.3.1611 image, RDMA set up fails, although it doesn't happen all the time and on all the machines. The error goes away when the machines are rebooted. The error message in the logs is

2018/07/12 15:44:21.158646 INFO RDMA: driver package present: microsoft-hyper-v-rdma-4.2.3.1.144-20180209.x86_64

2018/07/12 15:44:21.160220 INFO RDMA: driver package is up-to-date
2018/07/12 15:44:21.160914 INFO RDMA capabilities are enabled in configuration
2018/07/12 15:44:21.161355 INFO Wire server endpoint:168.63.129.16
2018/07/12 15:44:24.182869 ERROR Error setting up rdma device: [000008] [Wireserver Exception] [000009] None
2018/07/12 15:44:24.184254 INFO Installed Agent WALinuxAgent-2.2.18 is the most current agent

/Dev

**Comment by hglkrijger** [comment]
@devszr I believe the reboot is expected sometimes. Adding @longlimsft and @shirgall, who own this area.

**Comment by shirgall** [comment]
Are you using an older HPC image? The current ones should be set to default to the current host version (OS144), in an attempt to avoid too many reboots.

**Comment by devszr** [comment]
I'm using the CentOS 7.3.1611 HPC image. Not sure if it is the older image?

**Comment by hglkrijger** [comment]
@shirgall ?

**Comment by hglkrijger** [comment]
Timing this out

**Comment by wfang** [comment]
@hglkrijger is there another issue tracking this? Or should we leave this open?
