### ISSUE TITLE
Was changed default behavior of agent

### ISSUE THREAD

**Issue by Suvitruf** [Azure/WALinuxAgent#1258]
**foreword**
https://serverfault.com/questions/922014/rejected-all-local-requests

And in /etc/waagent.conf I've found `OS.EnableFirewall=y`. On our old VM there is no such rule. 

And all new deployed VM has this rule. So, you have changed default behavior of your agent. Why?

Also, https://github.com/Azure/WALinuxAgent/blob/master/config/ubuntu/waagent.conf#L107

```
# - The default is false to protect the state of existing VMs
OS.EnableFirewall=y
```
But I clearly see `y`.

**Comment by Suvitruf** [comment]
Hello, @hglkrijger. I've disabled it and waiting for the results. 

But I'm not 100% sure that it was the issue. Also, our problem (that I've described on serverfault) happens periodically =/

**Comment by Suvitruf** [comment]
Btw, @hglkrijger is it possible, that agent has added this rules?

```
Chain RESET (0 references)
pkts bytes target prot opt in out source destination 
0 0 REJECT tcp -- * * 0.0.0.0/0 0.0.0.0/0 reject-with tcp-reset

Chain PROHIBIT (0 references)
pkts bytes target prot opt in out source destination 
0 0 REJECT all -- * * 0.0.0.0/0 0.0.0.0/0 reject-with icmp-host-prohibited
```

**Comment by hglkrijger** [comment]
@Suvitruf no, we do not create any REJECT rules at all. We are about to roll out a change with a DROP rule, but that will only be for non-admin traffic and only with destination 168.63.129.16. The rules you have listed above are for 0.0.0.0.
