### ISSUE TITLE
folder pre-created assumption issue.

### ISSUE THREAD

**Issue by andyliuliming** [Azure/WALinuxAgent#1259]
and in bosh stemcell, the /var/lib/waagent is not pre-created.

when CGroups.setup() is called, agent try to write event, but the /var/lib/waagent is created in the later function 
/Users/andy/workspace/WALinuxAgent/azurelinuxagent/daemon/main.py:
L79 self.daemon(child_args)

so the waagent would crash.

**Comment by danielsollondon** [comment]
What image is this?

**Comment by hglkrijger** [comment]
It looks like the agent has been setup in a way which is not supported in that image. If the agent is not running under `/var/lib/waagent` to start with, then that is the issue.

**Comment by hglkrijger** [comment]
Clarified this was setup as expected. Re-opening. Will be addressed by #1261

**Comment by hglkrijger** [comment]
Fix merged
