### ISSUE TITLE
Waagent crash

### ISSUE THREAD

**Issue by vnorbix** [Azure/WALinuxAgent#126]
I've recently updated my Azure Linux VM from Ubuntu 14.04 to Ubuntu 15.10, waagent was also updated with the packages to the latest versions. Now waagent is crashing along the starting process, here's the error log:

2015/11/16 13:48:43.757780 INFO Azure Linux Agent Version:2.1.1
2015/11/16 13:48:43.760802 INFO OS: ubuntu 15.10
2015/11/16 13:48:43.762852 INFO Python: 3.4.3
2015/11/16 13:48:43.771321 INFO Send dhcp request
2015/11/16 13:48:43.902194 INFO Wire server endpoint:100.76.170.110
2015/11/16 13:48:43.904818 INFO Gateway:100.76.170.1
2015/11/16 13:48:43.907044 INFO Routes:None
2015/11/16 13:48:43.928629 INFO Configure routes
2015/11/16 13:48:43.950326 INFO Detect default protocol.
2015/11/16 13:48:44.851669 INFO Fabric preferred wire protocol version:2015-04-05
2015/11/16 13:48:44.861121 INFO Wire protocol version:2012-11-30
2015/11/16 13:48:44.863388 WARNING Server prefered version:2015-04-05
2015/11/16 13:48:44.937908 INFO Protocol V1 found.
2015/11/16 13:48:44.942308 INFO Protocol V2 found.
2015/11/16 13:48:44.946275 INFO run provision handler.
2015/11/16 13:48:44.998557 INFO Copy ovf-env.xml.
2015/11/16 13:48:45.002047 ERROR Provision failed: (000004)Failed to copy ovf-env.xml: Failed to get dvd device
2015/11/16 13:48:45.041766 INFO Activate resource disk
2015/11/16 13:48:45.041959 INFO Start env monitor service.
2015/11/16 13:48:45.113679 INFO Resource disk /dev/sdb1 is already mounted
2015/11/16 13:48:45.128551 INFO Enable swap
2015/11/16 13:48:45.150086 INFO Swap already enabled
2015/11/16 13:48:45.171321 INFO Report vm status
2015/11/16 13:48:45.173837 INFO Upload status blob
2015/11/16 13:48:45.323291 ERROR Traceback (most recent call last):
  File "/usr/sbin/waagent", line 35, in <module>
    agent.main()
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/agent.py", line 141, in main
    run()
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/agent.py", line 46, in run
    HANDLERS.main_handler.run()
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/distro/default/run.py", line 81, in run
    protocol.report_status(vm_status)
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/protocol/v1.py", line 104, in report_status
    self.client.upload_status_blob(vmStatus)
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/protocol/v1.py", line 551, in upload_status_blob
    status_blob.upload(ext_conf.status_upload_blob)
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/protocol/v1.py", line 292, in upload
    blob_type = self.get_blob_type(url)
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/protocol/v1.py", line 308, in get_blob_type
    'x-ms-version' : self.__class__.__storage_version__
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/utils/restutil.py", line 140, in http_head
    max_retry=max_retry, chk_proxy=chk_proxy)
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/utils/restutil.py", line 119, in http_request
    proxy_host=proxy_host, proxy_port=proxy_port)
  File "/usr/lib/python3.4/dist-packages/azurelinuxagent/utils/restutil.py", line 83, in _http_request
    conn.request(method, url, data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1172, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.4/http/client.py", line 1053, in putrequest
    host_enc = host.encode("ascii")
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by yuezh** [comment]
@vnorbix, did you do any proxy config to waagent? Such as:
HttpProxy.Host=None
HttpProxy.Port=None

**Comment by vnorbix** [comment]
@yuezh, thanks for your response. HttpProxy is not present in the config, here's my full config I'm using:
Role.StateConsumer=None
Role.ConfigurationConsumer=None
Role.TopologyConsumer=None
Provisioning.Enabled=y
Provisioning.DeleteRootPassword=y
Provisioning.RegenerateSshHostKeyPair=n
Provisioning.SshHostKeyPairType=rsa
Provisioning.MonitorHostName=n
Provisioning.DecodeCustomData=n
Provisioning.ExecuteCustomData=n
ResourceDisk.Format=y
ResourceDisk.Filesystem=ext4
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.EnableSwap=y
ResourceDisk.SwapSizeMB=2048
LBProbeResponder=y
Logs.Verbose=n
OS.RootDeviceScsiTimeout=300
OS.OpensslPath=None

Do you think a verbose log would help you?

**Comment by lizzha** [comment]
@vnorbix, does cloud-init runs in your VM?

**Comment by vnorbix** [comment]
@lizzha, yes, it seems to be, but I found this in cloud-init.log:

Nov 16 13:45:57 [CLOUDINIT] util.py[DEBUG]: Cloud-init v. 0.7.7 running 'init-local' at Mon, 16 Nov 2015 12:45:57 +0000. Up 35.65 seconds.
...
Nov 16 13:45:58 [CLOUDINIT] util.py[WARNING]: No instance datasource found! Likely bad things to come!
Nov 16 13:45:58 [CLOUDINIT] util.py[DEBUG]: No instance datasource found! Likely bad things to come!#012Traceback (most recent call last):#012  File "/usr/bin/cloud-init", line 253, in main_init#012    init.fetch()#012  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 336, in fetch#012    return self._get_data_source()#012  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 264, in _get_data_source#012    pkg_list, self.reporter)#012  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 274, in find_source#012    raise DataSourceNotFoundException(msg)#012cloudinit.sources.DataSourceNotFoundException: Did not find any data source, searched classes: (DataSourceAzureNet)
Nov 16 13:45:58 [CLOUDINIT] util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Nov 16 13:45:58 [CLOUDINIT] util.py[DEBUG]: Read 11 bytes from /proc/uptime
Nov 16 13:45:58 [CLOUDINIT] util.py[DEBUG]: cloud-init mode 'init' took 0.412 seconds (0.42)
Nov 16 13:45:58 [CLOUDINIT] handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources

**Comment by lizzha** [comment]
@vnorbix Seems there's conflict between cloud-init and waagent in provisioning.

Have you ever tried to set 
 Provisioning.Enabled=n
 ResourceDisk.Format=n
in waagent.conf, and then provision the VM?

**Comment by vnorbix** [comment]
@lizzha, I changed the config file, shut down the VM (deallocated), then started it, no changes, the same error lines are in the logs.

**Comment by lizzha** [comment]
@vnorbix , could you please try following steps:
1. Make sure the config file contains
    Provisioning.Enabled=n
    ResourceDisk.Format=n
2. run command # sudo waagent -deprovision
3. shut down the VM
4. capture the VM image
5. create a new VM from the captured image

If this cannot resolve the issue, could you please provide detailed steps of how you update your VM and update waagent, so that we could try to repro and take a look?

**Comment by vnorbix** [comment]
@lizzha, thanks for the suggestion, this solution worked! Now waagent is running without problems. I can now also register the VM to recovery services, that was my initial issue.

So, next time it would be recommanded to recreate the VM when waagent will be updated (major version changes) with the OS, right?
