### ISSUE TITLE
Creating a swapfile using dd is extremely slow, please use fallocate on Linux

### ISSUE THREAD

**Issue by Arthur2e5** [Azure/WALinuxAgent#127]
@butangmucat told me today that his Azure instance takes 10 mins to generate a swapfile on each boot. Most sane Linux admins, however, people prefer to use [fallocate(1)](http://linux.die.net/man/1/fallocate) to do the work of creating a non-sparse file, especially on IO-speed-challanged conditions like Azure. This also reduces disk wear (trivial to say, isn't it?).

The biggest difference of using `dd` and `fallocate` is that the former creates a file with some given contents, while the latter only allocates some space for a file. Since the space is allocated (therefore the file is not sparse), it's still effective for swaps.

https://github.com/Azure/WALinuxAgent/blob/2.0/waagent#L545 exhibits this behavior:
```Python
swap = Config.get("ResourceDisk.EnableSwap")
if swap == None or swap.lower().startswith("n"):
    return
sizeKB = int(Config.get("ResourceDisk.SwapSizeMB")) * 1024
if os.path.isfile(mountpoint + "/swapfile") and os.path.getsize(mountpoint + "/swapfile") != (sizeKB * 1024):
    os.remove(mountpoint + "/swapfile")
if not os.path.isfile(mountpoint + "/swapfile"):
    Run("dd if=/dev/zero of=" + mountpoint + "/swapfile bs=1024 count=" + str(sizeKB))
    Run("mkswap " + mountpoint + "/swapfile")
if not Run("swapon " + mountpoint + "/swapfile"):
    Log("Enabled " + str(sizeKB) + " KB of swap at " + mountpoint + "/swapfile")
else:
    Error("ActivateResourceDisk: Failed to activate swap at " + mountpoint + "/swapfile")
```

See also https://stackoverflow.com/questions/257844/quickly-create-a-large-file-on-a-linux-system.

Resolves #127.

**Comment by Arthur2e5** [comment]
Oh……and you guys are using a super small block size. Why don't you scale it to units of at least 4M and fill up the nasty remainders using the old size?

**Comment by hglkrijger** [comment]
fix merged, closing
