### ISSUE TITLE
Hostname changed to shortname

### ISSUE THREAD

**Issue by Klaas-** [Azure/WALinuxAgent#1274]
Hi,
in https://github.com/szarkos/AzureBuildCentOS/issues/41#issuecomment-406518060 I noticed that the agent seems to change the hostname to the shortname on purpose which leads to an issue with NetworkManager and the searchdomains. Is there an option to use fqdn hostname or do I have to use the fqdn as my vmname in azure?

Greetings
Klaas

**Comment by hglkrijger** [comment]
No, there is no option to use fqdn as hostname - you need to use the vmname.
