### ISSUE TITLE
WAAGENT changing sshd_config option

### ISSUE THREAD

**Issue by mabicca** [Azure/WALinuxAgent#1284]
Hi there,

I have noticed that waagent is changing /etc/ssh/sshd_config file options.

For instance, I set:
ChallengeResponseAuthentication yes

If I restart the waagent, or wait for a while, it will revert it to:
ChallengeResponseAuthentication no

Is that expected? Why is that being changed?

To reproduce the issue, you just need to:
1) change the option
2) restart the waagent
3) you will notice a new sshd_config file with the timestamp and the original file gets changed

This was tested with:

**cat /etc/*release**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**waagent -version**
WALinuxAgent-2.2.20 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.30

**Comment by boumenot** [comment]
Are you sure it is the agent?  The agent may set a value at provision time, but otherwise leaves it alone.  VMAccessForLinux will reset the value every time it is enabled.

There's an issue about this open against VMAccessForLinux.  See https://github.com/Azure/azure-linux-extensions/issues/623.

**Comment by hglkrijger** [comment]
This looks like a VMA issue, closing.
