### ISSUE TITLE
PIP or Package Management solution for installing/uninstalling instead of compiling from Source

### ISSUE THREAD

**Issue by whytoe** [Azure/WALinuxAgent#1296]
Azure Linux relies on this project to deploy, is it possible to include a PIP package or RPM that would push the WALINUX Agent to a repository to keep it up to date. 

Red Hat has a package in **rhel-7-server-extras-rpms** but it is still the 2.2.18.

This would help with the uninstall of WaLinux Agent as well and to facilitate upgrades to the binary. Since this is a Microsoft requirement it would be nice to see some form of package management because that is a great way to manage packages.

Thanks
Dan

**Comment by hglkrijger** [comment]
RHEL manages the package for RedHat.

**Comment by whytoe** [comment]
I know this 

> Red Hat has a package in rhel-7-server-extras-rpms but it is still the 2.2.18.

Is it possible to include a PIP package?
