### ISSUE TITLE
Including WALinuxAgent into custom kernel

### ISSUE THREAD

**Issue by richawil** [Azure/WALinuxAgent#1297]
I want to include the WALinuxAgent in my custom kernel. I assume I need a package built which will include all the packages upon which the WALinuxAgent depends.  Then I want to explode that package and add it to my kernel source base.
Is this the right procedure?  How does the package including all dependencies get built?  Is it the makepkg.py script?

**Comment by hglkrijger** [comment]
Unfortunately I am not able to tell you the correct procedure since this is not something we have done before or support. We do not build the packages either, the distro vendors own that process. 

The `makepkg.py` script is simply for building the egg which we distribute via our self-update mechanism.

**Comment by richawil** [comment]
Perhaps I can get the information I need by working backwards.

After the LinuxAgent code is successfully integrated into a Linux distro, what are all the files which were added and modified?
If I know what files need to be put where, I can come up with a way to deliver them in a package without using RPM.

**Comment by hglkrijger** [comment]
Python files for the agent are placed in site-packages. Other dependencies such as openssl are managed by the package manager. You can find the dependencies in the package spec as maintained by the vendor, for example: https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/walinuxagent/trusty/view/head:/rpm/walinuxagent.spec

**Comment by hglkrijger** [comment]
As suggested in email, you might also consider looking at recent cloud-init submissions, which allow cloud-init to perform all the necessary steps for provisioning outside of the agent. 

Closing this issue.
