### ISSUE TITLE
VM Extension status files handled differently between VMs and VMSSs

### ISSUE THREAD

**Issue by roiyz** [Azure/WALinuxAgent#1307]
[Opening on behalf of @martingoodwell] 

Hi,
we have a VM extension which is available on Azure Portal.
That extension used to work for both, VMs and VMSSs, exactly the same way.
For some weeks now, Azure Portal presents an error message, when applied to VMSSs:

VM has reported a failure when processing extension 'oneAgentLinux'. Error message: "Failed to get status file [Errno 2] No such file or directory: '/var/lib/waagent/dynatrace.ruxit.oneAgentLinux-2.3.0.1/status/1.status'".
Our extension writes 0.status, which is recognized by Azure when being applied to VMs.
But when applied to VMSSs, Azure seems to look for 1.status instead.
That wasn't the case up to a couple weeks ago.
Do you have any information on why this behavior changed?
Also, if this was a planned change, which source do we need to follow to be informed about changes like these upfront?

Thanks!

**Comment by hglkrijger** [comment]
@MartinGoodwell the status file should be written with the correct sequence number, this is not fixed at 0 and that is long standing behavior. The sequence number increases every time the platform updates the extension model, which can be for various reasons, such as new settings. In the case of VMSS, most likely the overprovision status is being changed.

**Comment by MartinGoodwell** [comment]
@hglkrijger One final question: we're working on the fix and are closely following the documentation "User guide for writing extension handlers", which states:

> VM Agent provides sequence number of the VM Extension configuration as environment variable,
“ConfigSequenceNumber”. This is to help extension handler determine if its enable command is
invoked with updated VM Extension configuration. 

However, according to our tests, that environment variable is not set for code that runs as part of the "enable" stage.
So, we'll just stick to the highest sequence number found for settings files, right?

Thanks!

**Comment by hglkrijger** [comment]
Yes, that is the typical pattern for extensions.
