### ISSUE TITLE
AutoUpdate - Default Enabled

### ISSUE THREAD

**Issue by Jared975** [Azure/WALinuxAgent#1308]
In the waagent.conf file, the option to enable auto update is commented out.  The line above this states that the default behavior is enabled. 

Is there a reason that this is commented out?  I believe it would fix a lot of Azure agent issues that I've run into if this feature was enabled by default.  If this is commented out on purpose, can you please explain what the concerns or problems led to this decision? 
```
# Enable or disable goal state processing auto-update, default is enabled
# AutoUpdate.Enabled=y
```

Thanks so much for your support!

-Jared

**Comment by hglkrijger** [comment]
The comment is merely to demonstrate the value, it is enabled by default.

**Comment by hglkrijger** [comment]
No, it is still enabled.
