### ISSUE TITLE
libglibmm-2.4-1c2a dependency

### ISSUE THREAD

**Issue by darue-keller** [Azure/WALinuxAgent#133]
problems on ubuntu server on azure, 15.04 and 15.10...

It looks to me like this package is not available after 14.04 LTS, not present and not easy to provide in 15.04, 15.10 etc. I'd suspect the dependency should be less specific as to the version.

note: Azure Diags seem to 'just not work' if launching a 15.10 VM, works fine if you launch a 14.04 VM.

upgraded to 15.10 from 14.04 and sure enough complaints about this dependency started, as of 15.10, every ~30 seconds a lot of error messages get written in '/var/log/azure/Microsoft.OSTCExtensions.LinuxDiagnostic/2.0.92/extension.log'

Also, with Diags not working right, the Azure UI (preview portal is all I've tested) hangs and acts all sorts of weird ways.

in /var/log/waagent.log, you also start seeing errors like this:
2015/12/01 21:15:55.570721 INFO Report vm status
2015/12/01 21:15:55.574034 INFO Upload status blob
2015/12/01 21:15:55.635711 ERROR Failed to report vm status: Failed to clean up page blob: 400

and no new diag info shows up in the portal UI.

Seems like a major problem to me.

**Comment by reppolice** [comment]
Sounds like the reason "lubuntu-desktop" removed walinuxagent on my 15.10 . And yes, sounds quite major

**Comment by cyrrill** [comment]
Happening on Ubuntu 14.04 as well:
```
# tail /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```

Relevant log lines:
```
2015/12/30 17:39:58 | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
2015/12/30 17:39:58 |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
2015/12/30 17:39:58 ||/ Name                                 Version                                 Architecture Description
2015/12/30 17:39:58 +++-====================================-=======================================-============-===============================================================================
2015/12/30 17:39:58 ii  libglibmm-2.4-1c2a:amd64             2.39.93-0ubuntu1                        amd64        C++ wrapper for the GLib toolkit (shared libraries)
2015/12/30 17:39:58 
```

**Comment by ahmetalpbalkan** [comment]
@szarkos this looks like #152, any ideas if this is a packaging issue?

**Comment by darue-keller** [comment]
There have been substantial changes since this was opened. Not noticing any issues currently with this... I think things have been fixed.
