### ISSUE TITLE
No name resolution on Ubuntu 17.10 after ```waagent -deprovision+user```

### ISSUE THREAD

**Issue by larohra** [Azure/WALinuxAgent#1332]
```/etc/resolve.conf``` not found after ```waagent -deprovision+user```

Similar issue - https://github.com/Azure/WALinuxAgent/issues/1151

**Comment by larohra** [comment]
Mitigation -

Run ```cd /etc; ln -s ../run/systemd/resolve/stub-resolv.conf resolv.conf``` as **root** after every ```waagent -deprovision+user``` command

**Comment by hglkrijger** [comment]
17.10 is no longer supported
