### ISSUE TITLE
the ssh config 'PasswordAuthentication' would be overwrite to 'yes' wrongly.

### ISSUE THREAD

**Issue by andyliuliming** [Azure/WALinuxAgent#1334]
if in some distro the 'PasswordAuthentication' is set to 'no', and then create one image in azure,
and create the vm using that image without specify the 'disablePasswordAuthentication' (this is optional)
then the 'PasswordAuthentication' would be overwrite to 'yes'.

i thinks wala should only do the sshd config when the disablePasswordAuthentication is set to true,
and leave the sshd_config file be if disablePasswordAuthentication is false?

**Comment by hglkrijger** [comment]
If this value is not specified then CRP will still pass `disablePasswordAuthentication=False` down via the goal state, so we cannot tell if it is specified explicitly or not.

Regardless, this is long-standing behavior (~3 years) and it is too risky to change now.
