### ISSUE TITLE
backup does not work for me on FreeBSD (pfsense)

### ISSUE THREAD

**Issue by harkx** [Azure/WALinuxAgent#1335]
When using a pfsense (based on FreeBSD 11.1) distro, I'm unable to create backups. Agent version is v2.2.26.

The error I receive in the Azure Job list is:

> Error code: GuestAgentSnapshotTaskStatusError
> Error Message: Could not communicate with the VM agent for snapshot status.

During the execution there are some errors in the log. (also about iptables, that does not exist on FreeBSD)

Is there any workaround for this so we can use backups for this VM ?

/var/log/waagent.log:
> 2018/09/06 19:59:23.323809 ERROR Provisioning failed: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to get dvd device from /dev
> Inner error: The following devices were found, but none matched the pattern [(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])]: ['dumpdev', 'reroot', 'geom.ctl', 'sndstat', 'hv_tsc', 'mdctl', 'console', 'devctl', 'devctl2', 'random', 'urandom', 'bpf', 'bpf0', 'consolectl', 'sysmouse', 'fido', 'kbdmux0', 'kbd1', 'mem', 'kmem', 'netmap', 'full', 'null', 'zero', 'pci', 'fd', 'stdin', 'stdout', 'stderr', 'nfslock', 'auditpipe', 'audit', 'midistat', 'io', 'klog', 'speaker', 'ctty', 'acpi', 'apmctl', 'apm', 'atkbd0', 'kbd0', 'psm0', 'bpsm0', 'ttyu0', 'ttyu0.init', 'ttyu0.lock', 'cuau0', 'cuau0.init', 'cuau0.lock', 'ttyu1', 'ttyu1.init', 'ttyu1.lock', 'cuau1', 'cuau1.init', 'cuau1.lock', 'devstat', 'ufssuspend', 'pf', 'usbctl', 'xpt0', 'hv_kvp_dev', 'hv_fsvss_dev', 'hv_appvss_dev', 'fd0', 'pass0', 'pass1', 'ttyv0', 'ttyv1', 'ttyv2', 'ttyv3', 'ttyv4', 'ttyv5', 'ttyv6', 'ttyv7', 'ttyv8', 'ttyv9', 'ttyva', 'ttyvb', 'da0', 'da0p1', 'da0p2', 'da0p3', 'da1', 'gptid', 'da1s1', 'md0', 'cpuctl0', 'cpuctl1', 'tun1', 'tun2', 'tun3', 'tun4', 'tun5', 'tun6', 'tun7', 'tun8', 'tun9', 'tun10', 'tun11', 'pts']
> 2018/09/06 19:59:23.438657 ERROR Command: 'iptables --version'
> 2018/09/06 19:59:23.438816 ERROR Return code: 127
> 2018/09/06 19:59:23.438953 ERROR Result: /bin/sh: iptables: not found
> 2018/09/06 19:59:23.444128 ERROR Event: name=WALinuxAgent, op=Firewall, message=, duration=0
> 2018/09/06 19:59:25.410699 ERROR Event: name=Microsoft.Azure.NetworkWatcher.NetworkWatcherAgentLinux, op=Install, message=[ExtensionError] Non-zero exit code: 51, ./install.sh install, duration=0
> 2018/09/06 19:59:27.703455 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=[ExtensionError] Non-zero exit code: 3, main/handle.sh install, duration=0
> 2018/09/06 20:00:24.510633 ERROR Event: name=Microsoft.Azure.NetworkWatcher.NetworkWatcherAgentLinux, op=Install, message=[ExtensionError] Non-zero exit code: 51, ./install.sh install, duration=0
> 2018/09/06 20:00:26.875935 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=[ExtensionError] Non-zero exit code: 3, main/handle.sh install, duration=0
> 2018/09/06 20:14:57.901269 ERROR Event: name=WALinuxAgent, op=Provision, message=[ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to get dvd device from /dev
> Inner error: The following devices were found, but none matched the pattern [(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])]: ['dumpdev', 'reroot', 'geom.ctl', 'sndstat', 'hv_tsc', 'mdctl', 'console', 'devctl', 'devctl2', 'random', 'urandom', 'bpf', 'bpf0', 'consolectl', 'sysmouse', 'fido', 'kbdmux0', 'kbd1', 'mem', 'kmem', 'netmap', 'full', 'null', 'zero', 'pci', 'fd', 'stdin', 'stdout', 'stderr', 'nfslock', 'auditpipe', 'audit', 'midistat', 'io', 'klog', 'speaker', 'ctty', 'acpi', 'apmctl', 'apm', 'atkbd0', 'kbd0', 'psm0', 'bpsm0', 'ttyu0', 'ttyu0.init', 'ttyu0.lock', 'cuau0', 'cuau0.init', 'cuau0.lock', 'ttyu1', 'ttyu1.init', 'ttyu1.lock', 'cuau1', 'cuau1.init', 'cuau1.lock', 'devstat', 'ufssuspend', 'pf', 'usbctl', 'xpt0', 'hv_kvp_dev', 'hv_fsvss_dev', 'hv_appvss_dev', 'fd0', 'pass0', 'pass1', 'ttyv0', 'ttyv1', 'ttyv2', 'ttyv3', 'ttyv4', 'ttyv5', 'ttyv6', 'ttyv7', 'ttyv8', 'ttyv9', 'ttyva', 'ttyvb', 'da0', 'da0p1', 'da0p2', 'da0p3', 'da1', 'gptid', 'da1s1', 'md0', 'cpuctl0', 'cpuctl1', 'tun1', 'tun2', 'tun3', 'tun4', 'tun5', 'tun6', 'tun7', 'tun8', 'tun9', 'tun10', 'tun11', 'pts']
> 2018/09/06 20:14:57.901856 ERROR Provisioning failed: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to get dvd device from /dev
> Inner error: The following devices were found, but none matched the pattern [(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])]: ['dumpdev', 'reroot', 'geom.ctl', 'sndstat', 'hv_tsc', 'mdctl', 'console', 'devctl', 'devctl2', 'random', 'urandom', 'bpf', 'bpf0', 'consolectl', 'sysmouse', 'fido', 'kbdmux0', 'kbd1', 'mem', 'kmem', 'netmap', 'full', 'null', 'zero', 'pci', 'fd', 'stdin', 'stdout', 'stderr', 'nfslock', 'auditpipe', 'audit', 'midistat', 'io', 'klog', 'speaker', 'ctty', 'acpi', 'apmctl', 'apm', 'atkbd0', 'kbd0', 'psm0', 'bpsm0', 'ttyu0', 'ttyu0.init', 'ttyu0.lock', 'cuau0', 'cuau0.init', 'cuau0.lock', 'ttyu1', 'ttyu1.init', 'ttyu1.lock', 'cuau1', 'cuau1.init', 'cuau1.lock', 'devstat', 'ufssuspend', 'pf', 'usbctl', 'xpt0', 'hv_kvp_dev', 'hv_fsvss_dev', 'hv_appvss_dev', 'fd0', 'pass0', 'pass1', 'ttyv0', 'ttyv1', 'ttyv2', 'ttyv3', 'ttyv4', 'ttyv5', 'ttyv6', 'ttyv7', 'ttyv8', 'ttyv9', 'ttyva', 'ttyvb', 'da0', 'da0p1', 'da0p2', 'da0p3', 'da1', 'gptid', 'da1s1', 'md0', 'cpuctl0', 'cpuctl1', 'tun1', 'tun2', 'tun3', 'tun4', 'tun5', 'tun6', 'tun7', 'tun8', 'tun9', 'tun10', 'tun11', 'pts']
> 2018/09/06 20:14:58.019019 ERROR Event: name=WALinuxAgent, op=Firewall, message=, duration=0
> 2018/09/06 20:14:59.901835 ERROR Event: name=Microsoft.Azure.NetworkWatcher.NetworkWatcherAgentLinux, op=Install, message=[ExtensionError] Non-zero exit code: 51, ./install.sh install, duration=0
> 2018/09/06 20:15:02.160908 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=[ExtensionError] Non-zero exit code: 3, main/handle.sh install, duration=0

**Comment by hglkrijger** [comment]
The iptables logs are not related. The issue here is the backup extension is not functioning. 

I would recommend you reach out to the Backup folks through normal support channels, however the list of OSes which are supported for backup are here: https://docs.microsoft.com/en-us/azure/backup/backup-azure-arm-vms-prepare#supported-operating-systems-for-backup and they do not include any BSD variant, so ymmv.

**Comment by Tulkis** [comment]
Hi @fegu,

Finally I got a success backing a pfsense, freebsd 11.3. I have VMAgent version: 2.2.45 (come with marketplace image).

First I did was install python 3.7 using pkg commands then I created symlink for /usr/bin/python -> /usr/local/bin/python3.7 and testart waagent.
Then I go through the logs catching errors and I could see error messages like this:
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/sbin/waagent': '/usr/sbin/waagent'
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/waagent/main/handle.sh': '/var/lib/waagent/main/handle.sh'
```
Basically I set up a symlink for every "FileNotFoundError" and create a symlink for everyone:
```
sudo ln -s /usr/local/sbin/waagent /usr/sbin/waagent
sudo ln -s /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9170.0/main/handle.sh /var/lib/waagent/main/handle.sh
```
I've could lost some one more, the pfsense command history is tricky.
After a VMAgent restart I could lauch a successful backup.

Hope it helps.
Regards.

**Comment by L0g0ff** [comment]
Tnx for your input @EduardCloud 

> I've could lost some one more, the pfsense command history is tricky.

Here is my full fix for Pfense: 2.4.5_1
```
ln -s /usr/local/bin/python3.7 /usr/bin/python
ln -s /usr/local/bin/python3.7 /usr/bin/python3
ln -s /usr/local/sbin/waagent /usr/sbin/waagent
mkdir /var/lib/waagent/main
ln -s /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9172.0/main/handle.sh /var/lib/waagent/main/handle.sh
```

You can find some helpful information in these log files:
/var/log/waagent.log
 /var/log/azure/Microsoft.Azure.RecoveryServices.VMSnapshotLinux/extension.log

I also enabled the vebose logging and updates in:
/usr/local/etc/waagent.conf

```
# Enable verbose logs
Logs.Verbose=y
# Disable auto update
autoUpdate.Enabled=y
```
restart the waagent (_service waagent restart_)when you make some changes.

the snapshot in Azure take max 15 min. If the snapshot isn't ready there is something wrong.

![afbeelding](https://user-images.githubusercontent.com/26351528/100849864-494bda00-3483-11eb-8b3a-862f7e8bc937.png)

Don't forget to turn the autoupdate & verbose off on a production machine.

I takes me a lot of time to troubleshoot this issue and the information is very bad documented so I hope it helps someone else!

**Comment by mrventerj** [comment]
@L0g0ff 

I am fairly new to this issue, is the solutions above to provide the ability to only take snapshots of disks manually or does this solution provide the ability to run the pfsense VM backups through Azure Recovery services vault?

**Comment by eduardcloud** [comment]
> @L0g0ff
> 
> I am fairly new to this issue, is the solutions above to provide the ability to only take snapshots of disks manually or does this solution provide the ability to run the pfsense VM backups through Azure Recovery services vault?

VM backups works wel too.

Regates.

**Comment by eduardcloud** [comment]
> @eduardcloud Thanks for the response, I followed the steps that L0g0ff posted, but I cannot enable backups on the VM. My FreebSD image already has Python 3.7. -waagent version: 2.2.45 ,FreeBSD 12.3.
> 
> Is the solution posted here still applicable to a possible newer Image or did I do something wrong?

Hi @mrventerj  I have FreeBSD 12.2-STABLE and it works. But when I upgraded it from the previous version I need to repeat the steps again to get backups running again. 
I don't know if there are any issue with 12.3

Regards

**Comment by mrventerj** [comment]
Thanks @eduardcloud , did you repeat the steps you posted or the steps L0g0ff posted?

**Comment by eduardcloud** [comment]
Yes @mrventerj  I did. The symlinks were lost and the python version changed.

**Comment by mrventerj** [comment]
For each of the symlinks I get the following:
ln -s /usr/local/bin/python3.7 /usr/bin/python
ln: /usr/bin/python: File exists

In my bin directory, I have python and python3 folders, should I rather install 3.7 or change the sym link command to:
n -s /usr/local/bin/python3 /usr/bin/python?

**Comment by stephenw10** [comment]
Python 3.8 is installed by default in pfSense 22.01 so your symlinks should look like:
```
ln -s /usr/local/bin/python3.8 /usr/bin/python
```
Remove the links to 3.7 and replace them.

**Comment by stephenw10** [comment]
You should have symlinks in /usr/bin named python and python3. They should both point at the binary /usr/local/bin/python3.8.

I'm not actually sure you need both since the script appears to search for the binary under various names:
```
pythonVersionList="python3.8 python3.7 python3.6 python3.5 python3.4 python3.3 python3 python2.7 python2.6 python2 python"

for pythonVersion in ${pythonVersionList};
do
	cmnd="/usr/bin/${pythonVersion}"
	if [ -f "${cmnd}" ]
    then
		echo "`date -u`- ${pythonVersion} path exists" >> $logfile
		$cmnd main/handle.py -$configSeqNo -$1
		rc=$?
	fi
	if [ $rc -eq 0 ]
	then
		break
	fi
done
```

**Comment by mrventerj** [comment]
@stephenw10 Thanks Stephen, I have fixed the following:
"You should have symlinks in /usr/bin named python and python3. They should both point at the binary /usr/local/bin/python3.8."
Python3 was still pointing 

Alas, I still cant backup xD - error log contains:
`2022/03/19 19:29:44.551184 INFO ExtHandler WireServer endpoint is not found. Rerun dhcp handler
2022/03/19 19:29:44.552620 INFO ExtHandler Test for route to 168.63.129.16
2022/03/19 19:29:44.564199 WARNING ExtHandler No route exists to 168.63.129.16
2022/03/19 19:29:44.568792 INFO ExtHandler Checking for dhcp lease cache
2022/03/19 19:29:44.569769 INFO ExtHandler Cache exists [False]
2022/03/19 19:29:44.570745 INFO ExtHandler Send dhcp request
2022/03/19 19:29:54.661273 WARNING ExtHandler Failed to send DHCP request: [DhcpError] timed out
`

**Comment by stephenw10** [comment]
I also saw warnings but it still completed. That looks like a network issue though. Maybe unrelated to the script?

**Comment by mrventerj** [comment]
@stephenw10  Aye it was unrelated, turns out I had my WAN IP address on static, when I switch it to DHCP it started working, I maybe had an incorrect default gateway, after switching to DCHP it started working, thanks for your and everyone else's help on here. <3
