### ISSUE TITLE
FreeBSD: Protocol endpoint not found: WireProtocol, [ProtocolError] [DhcpError] Failed to receive dhcp response.

### ISSUE THREAD

**Issue by tengtengvn** [Azure/WALinuxAgent#1343]
I've tried multiple versions from this github and FreeBSD repo but they're have the same issue, I've rebuilt the OS with v2.2.31 but it doesn't help. Appreciate your help in advance.

2018/09/21 00:01:14.649882 INFO Daemon Azure Linux Agent Version:2.2.31
2018/09/21 00:01:14.650098 INFO Daemon OS: freebsd 11.1
2018/09/21 00:01:14.650325 INFO Daemon Python: 2.7.14
2018/09/21 00:01:14.650582 VERBOSE Daemon Command: [ps -p 69364]
2018/09/21 00:01:14.654575 INFO Daemon Daemon is already running: 69364
2018/09/21 00:01:20.174724 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:01:20.178460 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:01:20.183371 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:01:20.183555 VERBOSE Daemon Command: [/etc/rc.d/dhclient start hn0]
2018/09/21 00:01:20.193761 VERBOSE Daemon Command: [route delete 255.255.255.255 -iface hn0]
2018/09/21 00:01:20.197909 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] [DhcpError] Failed to receive dhcp response.
2018/09/21 00:01:20.198328 VERBOSE Daemon HTTP connection [GET] [/Microsoft.Compute/identity?api-version=2015-05-01-preview] [None] [{'Connection': 'close', 'User-Agent': 'WALinuxAgent/2.2.31'}]
2018/09/21 00:01:20.201988 VERBOSE Daemon [HTTP Response] Status Code 404
2018/09/21 00:01:20.202112 INFO Daemon Protocol endpoint not found: MetadataProtocol, [ProtocolError] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview
2018/09/21 00:01:20.202236 INFO Daemon Retry detect protocols: retry=12
2018/09/21 00:01:30.296678 INFO Daemon WireServer endpoint is not found. Rerun dhcp handler
2018/09/21 00:01:30.296972 INFO Daemon Test for route to 168.63.129.16
2018/09/21 00:01:30.297093 WARNING Daemon No route exists to 168.63.129.16
2018/09/21 00:01:30.297222 INFO Daemon Checking for dhcp lease cache
2018/09/21 00:01:30.297298 INFO Daemon Cache exists [False]
2018/09/21 00:01:30.297360 INFO Daemon Send dhcp request
2018/09/21 00:01:30.297439 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:01:30.303894 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:01:30.308823 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:01:30.308976 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:01:30.311900 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:01:30.316790 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:01:30.317017 VERBOSE Daemon BuildDhcpRequest: transactionId:CB34F452,CB34F452
2018/09/21 00:01:30.317199 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:01:30.321985 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:01:30.329566 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:01:30.329773 VERBOSE Daemon Command: [route add 255.255.255.255 -iface hn0]
2018/09/21 00:01:30.332951 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:01:40.376706 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:01:40.376978 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:01:50.396709 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:02:00.476677 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:02:10.576639 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:02:40.676723 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:02:50.776732 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:03:50.876689 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:04:00.906666 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:05:00.926592 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:05:00.930147 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:05:00.935116 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:05:00.935292 VERBOSE Daemon Command: [/etc/rc.d/dhclient start hn0]
2018/09/21 00:05:00.944733 VERBOSE Daemon Command: [route delete 255.255.255.255 -iface hn0]
2018/09/21 00:05:00.947996 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] [DhcpError] Failed to receive dhcp response.
2018/09/21 00:05:00.948349 VERBOSE Daemon HTTP connection [GET] [/Microsoft.Compute/identity?api-version=2015-05-01-preview] [None] [{'Connection': 'close', 'User-Agent': 'WALinuxAgent/2.2.31'}]
2018/09/21 00:05:00.952261 VERBOSE Daemon [HTTP Response] Status Code 404
2018/09/21 00:05:00.952393 INFO Daemon Protocol endpoint not found: MetadataProtocol, [ProtocolError] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview
2018/09/21 00:05:00.952632 INFO Daemon Retry detect protocols: retry=13
2018/09/21 00:05:10.976691 INFO Daemon WireServer endpoint is not found. Rerun dhcp handler
2018/09/21 00:05:10.976884 INFO Daemon Test for route to 168.63.129.16
2018/09/21 00:05:10.977017 WARNING Daemon No route exists to 168.63.129.16
2018/09/21 00:05:10.977125 INFO Daemon Checking for dhcp lease cache
2018/09/21 00:05:10.977200 INFO Daemon Cache exists [False]
2018/09/21 00:05:10.977260 INFO Daemon Send dhcp request
2018/09/21 00:05:10.977337 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:05:10.981232 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:05:10.986265 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:05:10.986483 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:05:10.989377 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:05:10.994184 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:05:10.994488 VERBOSE Daemon BuildDhcpRequest: transactionId:A2179EA1,A2179EA1
2018/09/21 00:05:10.994612 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:05:10.997754 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:05:11.002576 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:05:11.002740 VERBOSE Daemon Command: [route add 255.255.255.255 -iface hn0]
2018/09/21 00:05:11.005581 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:05:21.026872 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:05:21.027215 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:05:31.126660 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:05:41.176744 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:05:51.226643 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:06:21.276830 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:06:31.376724 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:07:31.476703 VERBOSE Daemon Send DHCP request: Setting socket.timeout=10, entering recv
2018/09/21 00:07:41.576680 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/21 00:08:41.676627 VERBOSE Daemon Command: [ifconfig -l ether]
2018/09/21 00:08:41.680340 VERBOSE Daemon Command: [ifconfig hn0]
2018/09/21 00:08:41.685072 VERBOSE Daemon Interface info: (hn0,10.57.0.4,00:0d:3a:1e:5e:db)
2018/09/21 00:08:41.685248 VERBOSE Daemon Command: [/etc/rc.d/dhclient start hn0]
2018/09/21 00:08:41.695781 VERBOSE Daemon Command: [route delete 255.255.255.255 -iface hn0]
2018/09/21 00:08:41.702852 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] [DhcpError] Failed to receive dhcp response.

**Comment by roiyz-msft** [comment]
@tengtengvn, at this point, we don't officially support FreeBSD for the linux agent so we can't assist any further on this issue. but looking at your logs, the issue above may be a result of a broader network issue Azure's technical support may help identify what should be fixed.
