### ISSUE TITLE
utf-8 encoding required for Linux Agent

### ISSUE THREAD

**Issue by larohra** [Azure/WALinuxAgent#1344]
Error being thrown:
 ERROR ExtHandler [ProtocolError] [Wireserver Exception] 'latin-1' codec can't encode characters in position 1207-1212: Body ('\u691c') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by narrieta** [comment]
We need to understand impact.

**Comment by rebekahHess** [comment]
When a Linux VM with Japanese characters in the resource group or vm name connects to serial console, the following Error message is printed repeatedly in the terminal:
2018/09/21 18:18:06.310566 ERROR ExtHandler [ProtocolError] [Wireserver Exception] 'latin-1' codec can't encode characters in position 1207-1212: Body ('\u691c\u7d22\u30b7\u30b9\u30c6\u30e0') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
This interferes with serial console usage as the user may be typing commands in the terminal, and these error messages are suddenly injected.

**Comment by larohra** [comment]
+Azure Linux Agent
