### ISSUE TITLE
Ubuntu 18.10-daily: iptables table security Memory allocation problem

### ISSUE THREAD

**Issue by chvalean** [Azure/WALinuxAgent#1346]
Using the daily 18.10 Ubuntu Cosmic Azure images, we see the below errors in WALA agent logs.
VM functionality is not affected as far as we can tell.
The OS starts with WALA 2.2.20, then gets upgraded to 2.2.31, however the error mentioned below remains.

**OS: ubuntu 18.10
Python: 3.6.6
WALA: 2.2.31**

```
Determined Agent WALinuxAgent-2.2.31 to be the latest agent
ExtHandler Configure routes
ERROR ExtHandler Command: [iptables -w -t security -L OUTPUT --zero OUTPUT -nxv], `
return code: [3], result: [iptables v1.6.1: can't initialize iptables table `security': Memory allocation problem
...
ERROR ExtHandler Command: [iptables -w -t security -A OUTPUT -d 168.63.129.16 -p tcp -m `
owner --uid-owner 0 -j ACCEPT], return code: [3], `
result: [iptables v1.6.1: can't initialize iptables table `security': Memory allocation problem
Perhaps iptables or your kernel needs to be upgraded.
...
WARNING ExtHandler Dhcp client is not running. 
```

**Comment by narrieta** [comment]
We do not see this issue in our tests. Please re-open if still an issue.

**Comment by chvalean** [comment]
Right, well it might have just went away in the one year gap since it was set to investigating. :)

**Comment by narrieta** [comment]
@chvalean 

> Right, well it might have just went away in the one year gap since it was set to investigating. :)

and for that, we apologize.

We are in the process of cleaning up/addressing open issues (hence closing this one)
