### ISSUE TITLE
Latest waagent package in Debian source has serious memory leak

### ISSUE THREAD

**Issue by BH4EHN** [Azure/WALinuxAgent#1351]
Hello guys, I'm using Microsoft Azure China by 21vianet.

Same as #1321, The "waagent" package in Debian 9 source is still 2.2.18 (testing and unstable source is 2.2.26) and has serious memory leak problem.
Looks version 2.2.31 and above solves this problem. I manually upgrade all my Debian VM to the latest 2.2.32, but I think this issue may affect others.

**Comment by roiyz-msft** [comment]
@BH4EHN, thanks for letting us know. We are about to release a new agent version, once that's out, we'll work with the different distros to have the new version as default.

**Comment by echarlus** [comment]
Hello,
debian9 still uses version 2.2.18-3 which indeed causes memory issues ... Any hint on when we'll be able to get a new version which fixes the issue ?

**Comment by BH4EHN** [comment]
@echarlus  
As I create a new VM with Debian image a few hours ago, I discover the waagent running in the image is not the version in Debian apt source but the latest version 2.2.35 which is installed standalone.
I guess that Debian or Microsoft (at least one of these two) knows the issues but encountered some problem update the package in Debian apt source.

At this time, I suggest remove the memory leak version using apt and manually installed the latest version (like I do, if you don't have large numbers of Debian VM), or use the deb in Ubuntu apt source (not tested myself, just think it might work), or build yourself a deb package (for large scale deployment or for later use).
