### ISSUE TITLE
WALinuxAgent Fails Network Connection On OpenBSD 6.3

### ISSUE THREAD

**Issue by sirredbeard** [Azure/WALinuxAgent#1360]
[Docs show](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-openbsd#prepare-openbsd-image-for-azure) WALinuxAgent was supported as recently as OpenBSD 6.1.

Installing on OpenBSD 6.3 produces several networking-related errors based on current guidance. Attempts to troubleshoot, detailed below, have been unsuccessful. This may be related to #1243 and/or #735, so it may affect FreeBSD and Microsoft's official FreeBSD image in the Azure Marketplace.

Steps to reproduce: 

1. Download OpenBSD 6.3 [install ISO](https://cdn.openbsd.org/pub/OpenBSD/6.3/amd64/install63.iso). Create new VM in Hyper-V, 1st gen VM, 1GB RAM, 4GB VHD, attach ISO, reboot, select Autoinstall, enter URL http://git.io/fxWxO (a simple autoinstall script), after auto-restart perform a manual shutdown on VM, eject ISO, restart to boot from VHD, login as root with password blowfish1. 
2. Configure dependencies: 
$ echo "https://ftp.openbsd.org/pub/OpenBSD" > /etc/installurl
$ pkg_add py-setuptools openssl git
$ ln -sf /usr/local/bin/python2.7 /usr/local/bin/python
$ ln -sf /usr/local/bin/python2.7-2to3 /usr/local/bin/2to3
$ ln -sf /usr/local/bin/python2.7-config /usr/local/bin/python-config
$ ln -sf /usr/local/bin/pydoc2.7 /usr/local/bin/pydoc
3. Install WALinuxAgent:
$ git clone https://github.com/Azure/WALinuxAgent`
$ cd WALinuxAgent`
$ python setup.py install`
$ waagent -register-service

Expected Results:

WALinuxAgent would be able to resolve DHCP lease.

Actual Results:

DHCP errors:
![image](https://user-images.githubusercontent.com/33820650/46786444-de6b4200-cd02-11e8-9dbd-355f3b224f40.png)

Attempted Troubleshooting:

1. Checking network connection, working.
2. Renewing DHCP lease.
3. Adjusting permissions on /var/db/dhclient.leases.hvn0.

No change.

Additional Details:

[Verbose detailed logs from waagent](https://gist.github.com/sirredbeard/23126b24d00aa274ab1285a6405a70ad).

Here is the ifconfig:
![image](https://user-images.githubusercontent.com/33820650/46786545-3013cc80-cd03-11e8-8907-668bf18c90ff.png)

**Comment by roiyz-msft** [comment]
Hi @sirredbeard, thanks for sending this information. OpenBSD is not an officially supported [distro](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros). But if you'd like to contribute a PR to solve this issue, we are open to review it and add it if it resolves this problem on OpenBSD.

**Comment by athompso** [comment]
> Hi @sirredbeard, thanks for sending this information. OpenBSD is not an officially supported [distro](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros). 

Perhaps not all the Azure team has seen https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-openbsd, or heard the announcement at BSDCan that OpenBSD was now supported?

I just wasted/spent a day trying to use OpenBSD in Azure... so much for that idea :-(
