### ISSUE TITLE
Errors seen on OpenBSD and FreeBSD reproducible on Devuan

### ISSUE THREAD

**Issue by sirredbeard** [Azure/WALinuxAgent#1364]
The error messages reported in detail in #1360 and #1343 are reproducible on Devuan Ascii.

WALinuxAgent should support non-systemd *Nix and distros.

![capture232](https://user-images.githubusercontent.com/33820650/46921352-3be3e500-cfc8-11e8-9261-29c0efe80ce7.PNG)
![capture343](https://user-images.githubusercontent.com/33820650/46921353-3be3e500-cfc8-11e8-8d97-a504cee9220e.PNG)

WALinuxAgent Version: 2.2.18

**Comment by vrdmr** [comment]
@sirredbeard at this point, we don't officially support Devuan for the linux agent so we can't assist any further on this issue. the official list is [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros). 

But looking at your logs, the issue above may be a result of a broader network issue. The wireserver is a well-known endpoint and should be reachable from the VM. If DHCP or direct connection to the endpoint is not working, it is a networking setup issue and Azure's technical support may help identify what should be fixed.
