### ISSUE TITLE
[2.1] wrong config key

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#137]
![image](https://cloud.githubusercontent.com/assets/159209/11852077/e1cadabc-a3ea-11e5-9e67-378ac8b69f86.png)

I believe it should be "Provisioning"; not "Provision". :-)

**Comment by yuezh** [comment]
Good catch. Do you intent to send a PR?

**Comment by ahmetalpbalkan** [comment]
Not really I was just reading the codebase.

**Comment by yuezh** [comment]
If you don't mind, I would do the fix. Thx

**Comment by ahmetalpbalkan** [comment]
Sure :-) that's why I reported.

**Comment by ahmetalpbalkan** [comment]
it looks like it's fixed
