### ISSUE TITLE
On the Azure portal, the Extensions tab of the VM shows an warning: Some details about the installed extensions are unavailable. This can occur when the virtual machine is stopped or the agent is unresponsive.

### ISSUE THREAD

**Issue by shubhamgupta514** [Azure/WALinuxAgent#1371]
Hi Team ,

On the Azure portal, the Extensions tab of the VM shows an warning:
Some details about the installed extensions are unavailable. This can occur when the virtual machine is stopped or the agent is unresponsive.

As I checked the commandexecution.log in the extensions log folder ,I found below errors:
[Extension Error] Failed to get ext handler pkgs
Inner Error: [Protocol Error] Failed fetch manifests from all sources

OS is RHEL 7.5
WALinuxAgent version is 2.2.18

The extensions which we are using on the vm are
DscForLinux
VMDiagnostics
NetworkWatcher

**Comment by narrieta** [comment]
With this information it is hard to tell if this is an issue in one of the extensions or in the Agent. I would suggest opening a support request in the portal. Thanks!
