### ISSUE TITLE
Logging to identify CloudInit version

### ISSUE THREAD

**Issue by RandolphYao** [Azure/WALinuxAgent#1379]
Hi Team, 

I'm writing to post a feature request to log the cloud init version and if the flag indicating if it's enabled or not. 

Logging Cloud init version would be very helpful 
1. for analytic team to perform predictive VM provision based on the capabilities according to the Cloud init version, 
2. tracking and analysis (slice and dice) of potential provision bugs / issues and performance. We could potentially detecting issues early on, rather than ask customer to tell us when issue happened. 

Best, 
- Ranyao

**Comment by jasonzio** [comment]
Sounds like a simple enough change. Feel free to submit a PR if you want it done soon. The internal dev team is pretty good about reviewing and approving PRs from outside the team.

**Comment by trstringer** [comment]
@RandolphYao this is a fairly old request. If you still have a need for this work, please fee free to reopen this issue.
