### ISSUE TITLE
waagnet python exception AttributeError: 'unicode' object has no attribute 'attrib'

### ISSUE THREAD

**Issue by JPvRiel** [Azure/WALinuxAgent#138]
Noticed swap failed to mount and found that waagent aborted and didn't start in the `/var/log/waagent.log`

Related to https://github.com/Azure/WALinuxAgent/issues/76, except it's not ubuntu and does not use cloud_init. It's a custom Linux image:
```
$ /usr/sbin/waagent -version                  
AzureLinuxAgent-2.1.0 running on kali 2.0
$ python --version
Python 2.7.9
```

When the VM was originally provisioned, waagent created the swap file in /mnt/resources and swap was made available.

When rebooting the VM, the swap file was not created or enabled.

```
2015/12/23 12:51:27.108498 INFO Configure routes
2015/12/23 12:51:27.117699 INFO Detect default protocol.
2015/12/23 12:51:27.419800 INFO Fabric preferred wire protocol version:2015-04-05
2015/12/23 12:51:27.424300 INFO Wire protocol version:2012-11-30
2015/12/23 12:51:27.427163 WARNING Server prefered version:2015-04-05
2015/12/23 12:51:27.631573 ERROR Traceback (most recent call last):
  File "/usr/sbin/waagent", line 29, in <module>
    agent.Main()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/agent.py", line 111, in Main
    Run()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/agent.py", line 41, in Run
    Handlers.runHandler.run()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/distro/default/run.py", line 50, in run
    prot.DetectDefaultProtocol()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/protocolFactory.py", line 79, in DetectDefaultProtocol
    availableProtocols = DetectAvailableProtocols()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/protocolFactory.py", line 71, in DetectAvailableProtocols
    protocol = probeFunc()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/protocolFactory.py", line 50, in DetectV1
    protocol.initialize()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/v1.py", line 68, in initialize
    self.client.updateGoalState(forced=True)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/v1.py", line 481, in updateGoalState
    self.updateExtensionsConfig(goalState)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/v1.py", line 446, in updateExtensionsConfig
    self.extensionsConfig = ExtensionsConfig(xmlText)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/v1.py", line 902, in __init__
    self.parse(xmlText)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/v1.py", line 938, in parse
    settings)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/protocol/v1.py", line 936, in <lambda>
    pluginSettings = filter(lambda x: x.attrib["name"] == name
AttributeError: 'unicode' object has no attribute 'attrib'
```

**Comment by yuezh** [comment]
@JPvRiel. As far as I know kali is not a supported distro for 2.1 branch. Would you please switch to version 2.0.15? 
https://github.com/Azure/WALinuxAgent/releases/tag/WALinuxAgent-2.0.15

**Comment by JPvRiel** [comment]
@yuezh thanks, and while noted that kali isn't an officially supported distro, it is based off debian, and *Debian by Credativ* is officially supported? Technically, indirectly I'm following the documentation provided by Microsoft as well (even if it's a derivative distro).
* https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-endorsed-distributions/

Kali is simply using the Debian package. I've installed waagent from the distro's official repo and switching to the old verison is non-trivial. As far as possible, sysadmin best-practise is to use a distro's supported package system and update mechanisms instead of installing from source code, etc. Debian is not packaging older 2.0.x versions.

So perhaps this needs to be pushed downstream to the Debian package maintainer, given bastian.blank@credativ.de maintains the waagent package for Debian and has packed 2.1.x, not 2.0.x?

```
$ apt-cache show waagent
Package: waagent
Version: 2.1.0-3
Installed-Size: 531
Maintainer: Bastian Blank <bastian.blank@credativ.de>
Architecture: all
Depends: init-system-helpers (>= 1.18~), python, python:any (<< 2.8), python:any
 (>= 2.7.5-5~), ca-certificates, iptables, openssh-server, openssl, parted, sudo, net-tools, python-pyasn1
Conflicts: network-manager, walinuxagent
Size: 86812
```

The kali repo doesn't provide `2.0.15` and debain doesn't have any 2.0.x package option:
* http://repo.kali.org/kali/pool/main/w/waagent/ 
* https://packages.debian.org/search?keywords=waagent

**Comment by yuezh** [comment]
@SuperScottz, may be you could answer this question.

**Comment by ahmetalpbalkan** [comment]
@JPvRiel Hello, have you found a solution to this problem? It's not clear at which point and why you are getting this error, if you have a found out why, it would be great to know. Would you like to keep this issue open?

**Comment by JPvRiel** [comment]
@ahmetalpbalkan, I'm unsure if the downstream maintainer appears to have updated the package. See: http://metadata.ftp-master.debian.org/changelogs//main/w/waagent/waagent_2.1.3-3_changelog

Hopefully in the next week or so I can attempt to upgrade and see if the new debian package resolves the problem (it's requires a major version upgrade from Sana to Rolling distro repo's in Kali Linux, so it's not a quick thing to test).

**Comment by hglkrijger** [comment]
@JPvRiel, have you had a chance to verify if this has been fixed?

**Comment by hglkrijger** [comment]
closing, due to lack of activity. @JPvRiel, feel free to reopen if you still see this issue.

**Comment by drivelbyday** [comment]
I am also experiencing this issue with 2016.1.kali-rolling-amd64.  The conflict is networkmanager.  Is there a fix for debian itself?  Removing network manager appears to work, but the walinuxagent "tests" are not documented well.  Is there brief documentation for performing the tests?

**Comment by drivelbyday** [comment]
#394
