### ISSUE TITLE
OpenWRT support required

### ISSUE THREAD

**Issue by plessisa** [Azure/WALinuxAgent#1380]
Hi Teams,

I am new to git hub project but an experienced dev and Linux admin. I need to install the WALinuxAgent on an OpenWRT distro.
I can write the code that is require to support it, may I contribute to the project?

Best,

plessisa

**Comment by vrdmr** [comment]
Hi @plessisa, Thanks for your question. We would be happy to go over any code changes you make. Please send in your PR and me or anyone in my team would take a look. Please let me know if you need more information.

Thanks.

**Comment by plessisa** [comment]
Great, I submitted a PR for Openwrt support
