### ISSUE TITLE
Waagent 2.2.20 and 2.2.32 | OS.EnableFirewall=y breaks load balanced sets probing | |Ubuntu 18.04 

### ISSUE THREAD

**Issue by bebarb** [Azure/WALinuxAgent#1383]
Hello, 

We have found a similar issue to the described in this link https://github.com/Azure/WALinuxAgent/issues/879, with the version 2.2.20 and 2.2.32.2 (after update the agent in Ubuntu 18.04.) 
Until we set OS.EnableFirewall=n, and restart the agent service and the VM, the LB sets probing were successful.  Since the Iptables rules for 168.63.129.16 were removed. 

Is this the expect behavior? If it is know that OS.EnableFirewall=y, breaks load balanced sets probing, why is it not set by default as =n? 

In my customer's environment, the issue happens in several VMs, and it means a hard work to change manually the option in all the VMs.  

Thanks

**Comment by pgombar** [comment]
@bebarb we are not seeing this in our tests. Can you elaborate on how you verify the LB sets probing is failing? Thanks.
