### ISSUE TITLE
Cloud-init disables user password after different kernel install + 2 reboots

### ISSUE THREAD

**Issue by ader1990** [Azure/WALinuxAgent#1386]
Hello,

Environment:

- platform: Azure
- arm image: Canonical UbuntuServer 16.04-DAILY-LTS latest 

Steps:
1. Deploy VM with user/pass authentication
2. Install latest linux-next-upstream kernel (for example 4.19.0-4db9d11bcbef, where 4db9d11bcbef is the git tag from the linux-next latest tree: https://kernel.googlesource.com/pub/scm/linux/kernel/git/next/linux-next/)
3. reboot (all good)
4. reboot again
5. cloud-init disables the username password authentication

I checked the cloud-init logs and found:

> 2018-11-01 16:45:28,566 - __init__.py[INFO]: User <my-username>already exists, skipping.
> 2018-11-01 16:45:28,570 - util.py[DEBUG]: Running command ['passwd', '-l', '<my-username>'] with allowed return codes [0] (shell=False, capture=True)
> 2018-11-01 16:45:28,793 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
> 2018-11-01 16:45:28,795 - util.py[DEBUG]: Read 781 bytes from /etc/sudoers
> 2018-11-01 16:45:28,796 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 51 bytes
> 2018-11-01 16:45:28,797 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully

This issue is very bad one, as it can render your vm inaccessible on Azure.

Thank you,
Adrian Vladu

**Comment by narrieta** [comment]
Adrian, since the issue is in cloud-init, would you open this issue in http://launchpad.net/cloud-init?

Thank you!
