### ISSUE TITLE
problems when var partition is mounted as "noexec"

### ISSUE THREAD

**Issue by donestefan** [Azure/WALinuxAgent#1388]
Hi,
due to security recommendations it is quite common to use the "noexec" flag when mounting /var partition. 
However, waagent uses /var when installing Azure Extensions. This causes an ambiguous [error code 126](https://github.com/Azure/WALinuxAgent/issues/1059#issuecomment-397564240) to be logged and Extension installation to fail.
Some extensions like OMS Agent already [added support](https://github.com/Microsoft/OMS-Agent-for-Linux/issues/476) for installation on machines with noexec partitions.
Can you add a fix (or at least some meaningful logging) to waagent also? 

I'm using WALinuxAgent-2.2.18 on hardened Centos/RedHat.

**Comment by pgombar** [comment]
@donestefan closing since this is the current design. It is costly to change the current design and there are no plans of doing it in the near future.
