### ISSUE TITLE
OSUTIL.decode_customdata: CoreOS vs default

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#139]
Hi folks, 

distro | implementation
------------ | -------------
default | [OSUTIL.decode_customdata](https://github.com/Azure/WALinuxAgent/blob/ea7f7ea806945c97cc6bf546afe378ebb85dc0ca/azurelinuxagent/distro/default/osutil.py#L635-L636)
coreos | [OSUTIL.decode_customdata](https://github.com/Azure/WALinuxAgent/blob/ea7f7ea806945c97cc6bf546afe378ebb85dc0ca/azurelinuxagent/distro/coreos/osutil.py#L88-L89)

why is there a difference? why is coreos decoding base64 and others aren't?

as far as I can tell ovf-env.xml always base64-encodes the custom data field. (so [this test](https://github.com/Azure/WALinuxAgent/blob/ea7f7ea806945c97cc6bf546afe378ebb85dc0ca/tests/test_ovfxml.py#L56) most probably is not accurate).

**Comment by szarkos** [comment]
Alex Crawford added that.  AFAIR the CoreOS guys wanted this decoded so that they didn't have to modify their cloud-init implementation to decode it themselves.

**Comment by ahmetalpbalkan** [comment]
@szarkos is there any point of saving the base64 contents rather than decoding and then saving?
