### ISSUE TITLE
CGroups Azure Backup

### ISSUE THREAD

**Issue by cyber035** [Azure/WALinuxAgent#1390]
Hi I have a problem with Azure Backup, the WALinux Agent is giving this warning every few min:

WARNING ExtHandler Monitor: failed to update cgroups tracked extensions: 'Cgroup hierarchy cpu not found in /proc/cgroups'

Snapshot is never completed and I get failed backup.

I tried to set CGroups.EnforceLimits=y , no effect.

Os is CentOS 7.5 with CloudLinux so:
Linux 3.10.0-714.10.2.lve1.5.19.7.el7.x86_64 #1 SMP Fri Sep 28 08:37:09 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by narrieta** [comment]
@cyber035 Is CloudLinux available in the Azure Marketplace or is this a custom image? In the meanwhile, could you tell us the contents of your /proc/cgroups?

Thanks!

**Comment by cyber035** [comment]
I was recommended by Azure Support to try v2.2.18 and it works, but had to disable update.

**Comment by narrieta** [comment]
In our latest release (2.2.41) errors in cgroups should not be blocking and extensions should execute correctly. Please re-open this issue if the problem is still there.

**Comment by kailashmsft** [comment]
Hi @narrieta 

SUSE.SLES-SAP-BYOS.12-SP3.2019.03.06 vm running with 2.2.36 is also showing the same logs
Is there any bug in this version of waagent as well.
2.2.36 
2020/06/04 07:46:55.907407 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent/Microsoft.Azure.Diagnostics.LinuxDiagnostic
2020/06/04 07:46:55.918008 WARNING ExtHandler Monitor: failed to update cgroups tracked extensions: [Errno 30] Read-only file system: '/sys/fs/cgroup/cpu/WALinuxAgent'
2020/06/04 07:47:56.001845 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent/Microsoft.Azure.Diagnostics.LinuxDiagnostic
2020/06/04 07:47:56.009959 WARNING ExtHandler Monitor: failed to update cgroups tracked extensions: [Errno 30] Read-only file system: '/sys/fs/cgroup/cpu/WALinuxAgent'
2020/06/04 07:48:56.116939 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent/Microsoft.Azure.Diagnostics.LinuxDiagnostic
2020/06/04 07:48:56.126350 WARNING ExtHandler Monitor: failed to update cgroups tracked extensions: [Errno 30] Read-only file system: '/sys/fs/cgroup/cpu/WALinuxAgent'
2020/06/04 07:49:56.201893 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent/Microsoft.Azure.Diagnostics.LinuxDiagnostic
2020/06/04 07:49:56.203008 WARNING ExtHandler Monitor: failed to update cgroups tracked extensions: [Errno 30] Read-only file system: '/sys/fs/cgroup/cpu/WALinuxAgent'
2020/06/04 07:50:56.310282 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent/Microsoft.Azure.Diagnostics.LinuxDiagnostic
20

--

**Comment by narrieta** [comment]
@kailashmsft Is the extension running ok?

**Comment by kailashmsft** [comment]
nope none of the extension are working

**Comment by narrieta** [comment]
ok, then the bug is in that version too

**Comment by kailashmsft** [comment]
@narrieta thanks for the update
