### ISSUE TITLE
waagent and ClamAV cpu usage issue

### ISSUE THREAD

**Issue by OwainWin** [Azure/WALinuxAgent#1403]
I have an issue where some change in the waagent has a conflict with ClamAV on-access scanning and causes the waagent python process - python -u bin/WALinuxAgent-2.2.33-py2.7.egg -run-exthandlers - to gradually consume all the cpu.

This started a some point with 2.2.26 on any new VM's deployed, existing VM's running the same waagent version are fine.
This has persisted through every new agent release up to and including 2.2.33.

I've had this open as a support call and upgrading LAD 2.39 to 3.0 has lessened the impact - it takes longer to consume all the cpu, but is still an issue.  I have been advised by support to create a new issue here.
I have been able to temporarily fix this by excluding the following directories from on-access scanning:
- /opt/microsoft/omsagent
- /opt/microsoft/omsconfig
- /opt/omi/share/omsconfig
- /var/lib/waagent
- /var/opt/microsoft/omsagent
- /var/opt/microsoft/omsconfig

However I haven't ascertained which of these paths is the actual cause of the issue.
To be able to exclude these directories has required a re-configuration ClamAV that isn't ideal.
I would like to know what has caused this change of behaviour as this wasn't previously as issue and is only on newly deployed VM's.

**Comment by OwainWin** [comment]
Hi Norberto

I have deployed a VM with the same excludes apart from the /var/lib/waagent as requested and I can confirm that this does not have the issue – the cpu consumption is fine.

Best Regards

Owain

**Comment by narrieta** [comment]
Thanks for trying that. The rest of the directories belong to the OMS Agent. Could you open an issue on their Github repo? https://github.com/Microsoft/OMS-Agent-for-Linux

**Comment by OwainWin** [comment]
Hi Norberto

I have open a new issue as instructed:

https://github.com/Microsoft/OMS-Agent-for-Linux/issues/856

Best Regards

Owain

**Comment by narrieta** [comment]
Issue was moved to the OMS repo: https://github.com/Microsoft/OMS-Agent-for-Linux/issues/856
