### ISSUE TITLE
ResourceWarning: unclosed file <_io.BufferedReader name=3>

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#1406]
`azurelinuxagent.ga.exthandlers` in e9ab9a6c80d9f4e42829b63864e4aef96d0a8055 raises several `ResourceWarning` type warnings:

```
/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/azurelinuxagent/ga/exthandlers.py:836: ResourceWarning: unclosed file <_io.BufferedReader name=4>
  self.launch_command(enable_cmd, timeout=300, extension_error_code=1009)
/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/azurelinuxagent/ga/exthandlers.py:846: ResourceWarning: unclosed file <_io.BufferedReader name=3>
  extension_error_code=1010)
/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/azurelinuxagent/ga/exthandlers.py:892: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  env={'VERSION': version})
```

**Comment by narrieta** [comment]
@waldiTM - In order to debug this issue we would need a little more information. Where do you see this error? Is it in the extension log? Could you attach the full log if you have it?

Do you think this is relate e9ab9a6c80d9f4e42829b63864e4aef96d0a8055

**Comment by waldiTM** [comment]
They show up in the unit tests while running in Python 3.7.

**Comment by pgombar** [comment]
@waldiTM we couldn't repro this on our side. We use `nosetests` to run our unit tests, FYI.
