### ISSUE TITLE
PID file not updating on service restart (FreeBSD 10.2 - waagent 2.0.15)

### ISSUE THREAD

**Issue by Scotis** [Azure/WALinuxAgent#141]
Note: this VM had 2.0.12 on it by default - just updated it to 2.0.15 by following the directions on this page: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-update-agent/

Restarted the service:

    sudo service waagent restart
    /etc/rc.d/waagent: WARNING: $command_interpreter /usr/local/bin/python != python
    /etc/rc.d/waagent: WARNING: $command_interpreter /usr/local/bin/python != python
    Stopping waagent.
    Waiting for PIDS: 636.
    /etc/rc.d/waagent: WARNING: $command_interpreter /usr/local/bin/python != python
    Starting waagent.

Note: the old PID was 636

Find the new PID:

    ps -waux | grep waa
    root      1937   0.0  0.2   96036  16620  1  I     1:18AM   0:00.15 python /usr/sbin/waagent daemon (python2.7)

Note: new PID is 1937

Check the PID file:

    sudo cat /var/run/waagent.pid
    636

Still using old PID. :frowning:

**Comment by Scotis** [comment]
Here was the last line of the waagent.log before restart:

    2015/12/30 01:11:50 pgrep -n dhclient

Here is the last two lines of waagent.log after restart:

    2015/12/30 01:11:50 pgrep -n dhclient
    2015/12/30 01:18:45 Azure Linux Agent Version: WALinuxAgent-2.0.15

Also python version:

    python-2.7_2,2                 The "meta-port" for the default version of Python interpreter
    python2-2_3                    The "meta-port" for version 2 of the Python interpreter
    python27-2.7.10_1              Interpreted object-oriented programming language

**Comment by Scotis** [comment]
This seems to only happen when the script stalls/freezes as reported in issue #142 - If I restart the service while it is actively reporting health and logging things - this issue does not happen...

**Comment by ahmetalpbalkan** [comment]
@Scotis since this only happens in case of #142 which has a mitigation: https://github.com/Azure/WALinuxAgent/issues/142#issuecomment-189144717 closing this one. Please let us know if the issue persists.
