### ISSUE TITLE
Deprovision fails on FreeBSD 11.1

### ISSUE THREAD

**Issue by cloudguy23** [Azure/WALinuxAgent#1414]
Deprovision fails on FreeBSD 11.1.  WAAGENT v2.2.34 depends on /etc/rc.conf for successful exit.

> waagent -deprovision
> WARNING! The waagent service will be stopped.
> WARNING! All SSH host key pairs will be deleted.
> WARNING! Cached DHCP leases will be deleted.
> WARNING! root password will be disabled. You will not be able to login as root.
> WARNING! /etc/resolv.conf will be deleted.
> Do you want to proceed (y/n)y
> 2018/12/05 01:59:48.822681 ERROR Failed to run 'deprovision': Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/agent.py", line 163, in main
>     agent.deprovision(force, deluser=False)
>   File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/agent.py", line 116, in deprovision
>     deprovision_handler.run(force=force, deluser=deluser)
>   File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/deprovision/default.py", line 211, in run
>     self.do_actions(actions)
>   File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/deprovision/default.py", line 231, in do_actions
>     action.invoke()
>   File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/deprovision/default.py", line 50, in invoke
>     self.func(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/osutil/freebsd.py", line 36, in set_hostname
>     conf_file = fileutil.read_file(rc_file_path).split("\n")
>   File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/utils/fileutil.py", line 53, in read_file
>     with open(filepath, mode) as in_file:
> IOError: [Errno 2] No such file or directory: '/etc/rc.conf'

Workaround:

> touch /etc/rc.conf
> waagent -deprovision
> WARNING! The waagent service will be stopped.
> WARNING! All SSH host key pairs will be deleted.
> WARNING! Cached DHCP leases will be deleted.
> WARNING! root password will be disabled. You will not be able to login as root.
> WARNING! /etc/resolv.conf will be deleted.
> Do you want to proceed (y/n)y

**Comment by narrieta** [comment]
Sorry, we don't officially support FreeBSD for the linux agent so we can't assist any further on this issue. the official list is [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros).

If you can provide a fix we will be happy to look at your PR.
