### ISSUE TITLE
Exception processing extension handlers: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by axelgMS** [Azure/WALinuxAgent#1423]
running latest version of WALinuxAgent: 2.2.34

2018/12/06 13:56:25.607964 INFO Determined Agent WALinuxAgent-2.2.34 to be the latest agent
2018/12/06 13:56:27.115368 INFO ExtHandler Agent WALinuxAgent-2.2.34 is running as the goal state agent

Image =
                "publisher": "OpenLogic",
                "offer": "CentOS",
                "sku": "7.2",
                "version": "latest"

Waagent.log is full of

2018/12/13 18:51:40.004441 WARNING ExtHandler Exception processing extension handlers: 'NoneType' object is not iterable
2018/12/13 18:51:40.038431 ERROR ExtHandler Event: name=WALinuxAgent, **op=ExtensionProcessing, message=Exception processing extension handlers: 'NoneType' object is not iterable**, duration=0

**Comment by narrieta** [comment]
Fixed by #1472
