### ISSUE TITLE
Error while testing SLES 15SP1

### ISSUE THREAD

**Issue by ricardobranco777** [Azure/WALinuxAgent#1426]
![2932](https://user-images.githubusercontent.com/10237751/50007810-66dfba80-ffb2-11e8-8212-1ab96727cd4e.png)

The naive version check in `int(distro_version) > 11` is causing trouble.

**Comment by ricardobranco777** [comment]
Fix:

https://github.com/Azure/WALinuxAgent/pull/1427

**Comment by pgombar** [comment]
Hi Ricardo, I just approved your PR (#1427), thanks for the fix. The fix will be published in the new release in January.
