### ISSUE TITLE
Read VM location from WALinuxAgent

### ISSUE THREAD

**Issue by smereczynski** [Azure/WALinuxAgent#143]
There should be the possibility to read location where VM is running. It can be WALinuxAgent command or node in XML configuration parsed on deployment or incarnation. In many cases the user service's configuration is based on VM location so if VM clould read it's own location it will be very usefull.

**Comment by yuezh** [comment]
That's reasonable requirement. We will work with service team to add that. @andyzhangx may provide you some workaround to get the location info from existing api.

**Comment by andyzhangx** [comment]
the location info in VM is under file /var/lib/waagent/ExtensionsConfig*, e.g.
<Location>eastus2</Location>
You cloud use the following command line to get location info:
grep '<Location>' /var/lib/waagent/ExtensionsConfig* --no-filename | sed 's/<Location>//g' | sed 's/<\/Location>//g' | sed 's/ //g' | tr 'A-Z' 'a-z' | uniq

**Comment by smereczynski** [comment]
Hah, I did not noticed that because of differences between ExtensionsConfig iterations. I have 4 iterations of this file:

ExtensionsConfig.1.xml
ExtensionsConfig.2.xml
ExtensionsConfig.3.xml
ExtensionsConfig.4.xml

and I was looking for something like <Location> in the fourth one. But this is just in the first one. Thank You for hint!

**Comment by ahmetalpbalkan** [comment]
There are plans to launch an Instance Metadata API for Azure. It will give you an HTTP API to gather more information about the VM and the subscription it is running in. Please stay tuned.

Closing as the issue not about to the agent.
