### ISSUE TITLE
[BUG] Can't uninstall VM extension when previously-installed version of the extension is unregistered

### ISSUE THREAD

**Issue by EvanCui** [Azure/WALinuxAgent#1449]
**Describe the bug**
The agent cannot handle the uninstallation when the older version of a VM extension is unregisterd.
The agent will fall into an infinite loop of log messages:
2019/01/30 06:44:26.666774 ERROR ExtHandler Event: name=Microsoft.HpcPack.HpcAcmAgent, op=Download, message=Unable to find version 1.0.33.0 in manifest for extension Microsoft.HpcPack.HpcAcmAgent, duration=0
2019/01/30 06:44:29.909154 WARNING [Microsoft.HpcPack.HpcAcmAgent-1.0.33.0] Failed to find installed version of Microsoft.HpcPack.HpcAcmAgent to uninstall

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs.
2019/01/29 10:10:25.438763 ERROR [Microsoft.HpcPack.HpcAcmAgent-1.0.44.0] Failed to save handler status: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.HpcPack.HpcAcmAgent-1.0.44.0/config/HandlerStatus'
2019/01/29 10:10:25.513608 ERROR Event: name=Microsoft.HpcPack.HpcAcmAgent, op=None, message=[ExtensionError] Failed to find any valid extension package, duration=0

2. Serial console output
Not monitored.

3. Steps to reproduce the behavior.
Publish a VM extension of version 1.0.1.0
Install the extension to a VM.
Unregister the VM extension of version 1.0.1.0
Publish the VM extension of version 1.0.2.0
Use powershell to request the VM to uninstall the VM extension.
Check the WAAgent.log, there will be infinite logs saying failed to find the package to uninstall.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Red Hat Enterprise Linux Server release 7.2
 - WALinuxAgent version 
WALinuxAgent-2.2.14 running on redhat 7.2
Python: 2.7.5
Goal state agent: 2.2.35.1

**Additional context**
I did some investigation. It seems that the agent is pulling the registered packages and save into a list, and when an uninstall is requested, it tries to find the version from the list, however, there is no matching version, so that the agent fails to uninstall.
I thought the agent should only find the version from the installed folder, once found, execute the uninstallCommand specified in the manifest file.

**Comment by jeking3** [comment]
Needs a better title.

**Comment by larohra** [comment]
Fixed in #1970
