### ISSUE TITLE
rpm -ba incorrect syntax for rhel/centos 6.10

### ISSUE THREAD

**Issue by ajaysuryawanshi** [Azure/WALinuxAgent#1455]
Not able buid rpm for rhel/centos6.10 using source. "python setup.py bdist_rpm" failed with below error.

rpm -ba --define _topdir /root/WALinuxAgent-2.2.35/build/bdist.linux-x86_64/rpm --clean build/bdist.linux-x86_64/rpm/SPECS/WALinuxAgent.spe

**Comment by jayninja** [comment]
master branch built just fine for me on CentOS 6.10. Attached buffer. 
[test-6.10.txt](https://github.com/Azure/WALinuxAgent/files/3291662/test-6.10.txt)

**Comment by larohra** [comment]
`python setup.py bdist_rpm` building fine on rhel-6.10 [stdout.log](https://github.com/Azure/WALinuxAgent/files/3672685/stdout.log)

I did notice though that rpm version >4 removed the `-ba` flag which causes the above command to fail. Make sure to install `rpm-build` package before trying to build, after installing `rpm-build` this command should succeed - `python setup.py bdist_rpm`
