### ISSUE TITLE
CustomData not handled correctly when Provisioning.DecodeCustomData=n

### ISSUE THREAD

**Issue by chkp-zegman** [Azure/WALinuxAgent#146]
When you set:
Provisioning.DecodeCustomData=n
The following code raises an exception:
SetFileContents(LibDir + '/CustomData', bytearray(MyDistro.translateCustomData(self.CustomData)))
The reason is that:
self.CustomData is a unicode string.
The value returned from MyDistro.translateCustomData is the same unicode string.
bytearray on a unicode string raises an exception.
As a result, no CustomData is written to the disk.

**Comment by chkp-zegman** [comment]
A suggested change is to call bytearray with a 2nd encoding argument thus:
SetFileContents(LibDir + '/CustomData', bytearray(MyDistro.translateCustomData(self.CustomData), 'utf-8'))

**Comment by hglkrijger** [comment]
fix merged into develop
