### ISSUE TITLE
Downloads and executes unauthenticated binaries

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#147]
waagent can be instructed to download and execute arbitrary executables. It does not enforce any kind of authentication.

Excerpt from log:
```
> Found Plugin: Microsoft.OSTCExtensions.LinuxDiagnostic version: 2.0.92
> Downloading plugin manifest: Microsoft.OSTCExtensions.LinuxDiagnostic from http://rdfepirv2db3prdstr02.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions_LinuxDiagnostic_europenorth_manifest.xml
> Plugin server is: rdfepirv2db3prdstr02.blob.core.windows.net
> Bundle URI = http://rdfepirv2db3prdstr02.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__LinuxDiagnostic__2.0.92
> Plugin bundlehttp://rdfepirv2db3prdstr02.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__LinuxDiagnostic__2.0.92downloaded successfully length = 111831319
> Extracted http://rdfepirv2db3prdstr02.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__LinuxDiagnostic__2.0.92 to /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.0.92

```

**Comment by yuezh** [comment]
Thanks for reporting this. We are working on fixing this.

**Comment by ahmetalpbalkan** [comment]
Hi @waldiTM,

We have  recently deployed secure transport for delivery of Virtual Machine Extensions. The newly deployed versions of Virtual Machine Extensions are delivered to the virtual machines over TLS (https). Over time, we will be fully transitioning to TLS.

From your example above, it appears like your virtual machine is running a 2.0 version of the LinuxDiagnostic extension. The latest version is 2.3.9. If you specify the extension as `2.*` while you are deploying (or `"autoUpgradeMinorVersion":true` in ARM templates), the newer versions of the extension should be delivered via TLS to your VM.

Thanks for reporting the problem and sorry for the inconvenience.

**Comment by waldiTM** [comment]
It must check the signature of the binary after downloading. Just using TLS is not adequate.

**Comment by ahmetalpbalkan** [comment]
@waldiTM Fair point. Currently, the storage medium providing the Virtual Machine Extension packages is the same highly-protected storage bucket providing the Virtual Machine Images as well. They are subject to the same security audits and scans.

The Virtual Machine Extension packages are published not only by Microsoft, but other approved independent software vendors (such as Chef, Puppet Labs, ESET) as well. This makes it somewhat challenging to get the right set of keys to the Virtual Machines.

While these are just technical challenges, Extension Signing is certainly on our list and we are hoping to come back and improve.
