### ISSUE TITLE
WALinuxAgent not being updated on CentOS VMs

### ISSUE THREAD

**Issue by nunoplopes** [Azure/WALinuxAgent#1475]
**Describe the bug**
My CentOS VMs haven't upgraded to the new version (2.2.36).
According to #1342, it was supposed to be deployed already.

**Distro and WALinuxAgent details**
$ waagent --version
WALinuxAgent-2.2.32.2 running on centos 7.6.1810
Python: 2.7.5
Goal state agent: 2.2.36

These are CentOS 7 (OpenLogic) VMs, both in West Europe & West US.

**Comment by narrieta** [comment]
There are 2 versions of the agent ([details here]( https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output)).

The version you see (2.2.32.2) is updated by each distro owner.
