### ISSUE TITLE
FreeBSD 11.2 :  'cannot read route table [[Errno 2] No such file or directory: '/proc/net/route'

### ISSUE THREAD

**Issue by narrieta** [Azure/WALinuxAgent#1479]
The freebsd based on the marketplace image is returning a large amount of errors such as the one below:
$ tail waagent.log
2019/03/04 13:51:35.200690 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
2019/03/04 13:52:35.312408 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
[...]

**Comment by minusbat** [comment]
I looked at this, and started working on a fix for it actually. All it is trying to do is to read the routing table to see if it has changed. As such it should be enough to replace that code with the output of 'netstat -rn' I would thing. Just need to understand how to add a FreeBSd specific bit of code there in the way its done everywhere else. I don't do python really though (more of a C / Obj-C person)

**Comment by mike-pt** [comment]
I looked into the same recently , cause without this working properly backups will never work.

The route table is easy to work around, I do know some python and I thing I've identified the 2 places this needs to change, but there's also the iptables side of it.

The main issue is that this is linux centric... Well its called "WALinuxAgent" not "WAUnix", there might be more places that need workarounds, but honestly other than adding if/else to cover both the linux and bsd cases doesn't seem to make much sense for me, I wish Microsoft could give BSD a bit more attention since they do support it on Azure and at least make sure basic things like backups work!

I would vote on having a WA BSD Agent that simply implement the bsd logic separate of this one.

**Comment by onenachi** [comment]
Well I've tested and submitted a PR. Now its just a waiting game.

**Comment by pgombar** [comment]
Closing as the PR got merged and will be included in the next release.

**Comment by minusbat** [comment]
I just pulled master and installed this on FreeBSD 12.1 and I am still getting the original error:

2019/10/25 19:43:06.776594 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']

Is there anything extra that I need to do to make this work ? I know the original PR was for FreeBSD 11, but presumably this should also work on 12 ?

**Comment by onenachi** [comment]
This should just work on 12. I haven't tested it on 12, only on 11.2 and 11.3. But as long as the osutil used is the FreeBSD one, there should be no issues.

**Comment by minusbat** [comment]
```2019/10/25 19:57:34.854327 INFO Daemon Determined Agent WALinuxAgent-2.2.44 to be the latest agent
2019/10/25 19:57:35.025716 INFO ExtHandler Agent WALinuxAgent-2.2.44 is running as the goal state agent
2019/10/25 19:57:35.027219 INFO ExtHandler Distro info: freebsd 12.1, osutil class being used: FreeBSDOSUtil, agent service name: waagent
```

so it looks like its using the correct osutil, but I still get this:

```
2019/10/25 19:57:37.373371 INFO ExtHandler ProcessGoalState completed [incarnation 27; 2165 ms]
2019/10/25 19:58:35.297555 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
2019/10/25 19:59:35.335631 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
```

and so on....

**Comment by onenachi** [comment]
Well that error was previously caused by wireserver_route_exists. Now that function calls the osutils read_route_table. The FreeBSD osutil has no mention of "/proc/net/route" at all. If it failed there it would complain about a failed `netstat -rn -f inet` which it isnt.

This means that:
- Perhaps the fix was committed to the develop branch and not master
- Either there is another piece of code that manually reads /proc/net/route
- The OSUtil being used is for some reason the default still
- Perhaps the compilation was not done correctly (I have faced this when old .pyc files are used instead of new .py ones)

**Comment by onenachi** [comment]
> ```
> 2019/10/25 19:57:35.025716 INFO ExtHandler Agent WALinuxAgent-2.2.44 is running as the goal state agent
> 2019/10/25 19:57:35.027219 INFO ExtHandler Distro info: freebsd 12.1, osutil class being used: FreeBSDOSUtil, agent service name: waagent
> ```
> 
> so it looks like its using the correct osutil, but I still get this:
> 
> ```
> 2019/10/25 19:57:37.373371 INFO ExtHandler ProcessGoalState completed [incarnation 27; 2165 ms]
> 2019/10/25 19:58:35.297555 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
> 2019/10/25 19:59:35.335631 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
> ```
> 
> and so on....

I just checked, the fix is in the develop branch and not master.

**Comment by narrieta** [comment]
Yes, the fix has not been merged to master. It is in the release-2.2.44 branch (via develop), We currently deploying release-2-2.44; once deployment completes we'll merge it to master.

**Comment by minusbat** [comment]
I am running the develop branch, but just to make sure I wiped it, did a fresh checkout from git and a fresh build (python 3.7) and an install, but its still doing it. Will add a complete transcript of the startup below so you can see what its doing - it identifies freebsd, but it does still seem to do thing like run iptables. Puzzling...

```
2019/10/25 20:29:30.039688 INFO Daemon Agent WALinuxAgent-2.2.42 forwarding signal 15 to WALinuxAgent-2.2.44
2019/10/25 20:29:30.502345 INFO Daemon Azure Linux Agent Version:2.2.42
2019/10/25 20:29:30.503834 INFO Daemon OS: freebsd 12.1
2019/10/25 20:29:30.506558 INFO Daemon Python: 2.7.16
2019/10/25 20:29:30.527759 INFO Daemon CGroups Status: Cgroups are not supported by the platform
2019/10/25 20:29:30.532610 INFO Daemon Run daemon
2019/10/25 20:29:30.534316 INFO Daemon No RDMA handler exists for distro='freebsd' version='12.1'
2019/10/25 20:29:30.535324 INFO Daemon Activate resource disk
2019/10/25 20:29:30.604361 INFO Daemon Resource disk device da1 found.
2019/10/25 20:29:30.615835 INFO Daemon Resource disk partition /dev/da1s1 found.
2019/10/25 20:29:30.628026 INFO Daemon Resource disk /dev/da1s1 is already mounted
2019/10/25 20:29:30.635840 INFO Daemon Clean protocol
2019/10/25 20:29:30.639703 INFO Daemon Running default provisioning handler
2019/10/25 20:29:30.641439 INFO Daemon Copying ovf-env.xml
2019/10/25 20:29:30.644655 ERROR Daemon Provisioning failed: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to get dvd device from /dev
Inner error: The following devices were found, but none matched the pattern [(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])]: ['dumpdev', 'reroot', 'console', 'sndstat', 'random', 'urandom', 'hv_tsc', 'devctl', 'devctl2', 'geom.ctl', 'mdctl', 'input', 'kbdmux0', 'kbd1', 'mem', 'kmem', 'netmap', 'full', 'null', 'zero', 'pci', 'fd', 'stdin', 'stdout', 'stderr', 'nfslock', 'auditpipe', 'audit', 'midistat', 'sequencer0', 'music0', 'tcp_log', 'io', 'klog', 'uinput', 'ctty', 'consolectl', 'sysmouse', 'fido', 'bpf', 'bpf0', 'acpi', 'apmctl', 'apm', 'atkbd0', 'kbd0', 'psm0', 'bpsm0', 'ttyu0', 'ttyu0.init', 'ttyu0.lock', 'cuau0', 'cuau0.init', 'cuau0.lock', 'ttyu1', 'ttyu1.init', 'ttyu1.lock', 'cuau1', 'cuau1.init', 'cuau1.lock', 'devstat', 'ufssuspend', 'zfs', 'netdump', 'crypto', 'usbctl', 'xpt0', 'hv_kvp_dev', 'hv_fsvss_dev', 'hv_appvss_dev', 'pass0', 'pass1', 'pass2', 'pass3', 'pass4', 'pass5', 'fd0', 'da0', 'da1', 'da2', 'da3', 'da4', 'da5', 'da0p1', 'da0p2', 'da0p3', 'da1s1', 'gpt', 'ttyv0', 'ttyv1', 'ttyv2', 'ttyv3', 'ttyv4', 'ttyv5', 'ttyv6', 'ttyv7', 'ttyv8', 'ttyv9', 'ttyva', 'ttyvb', 'pts']
 (0s)
2019/10/25 20:29:30.646269 INFO Daemon Detect protocol endpoints
2019/10/25 20:29:30.646590 INFO Daemon Clean protocol
2019/10/25 20:29:30.647690 INFO Daemon WireServer endpoint is not found. Rerun dhcp handler
2019/10/25 20:29:30.647987 INFO Daemon Test for route to 168.63.129.16
2019/10/25 20:29:30.648172 WARNING Daemon No route exists to 168.63.129.16
2019/10/25 20:29:30.649053 INFO Daemon Checking for dhcp lease cache
2019/10/25 20:29:30.650341 INFO Daemon Cache exists [False]
2019/10/25 20:29:30.652688 INFO Daemon Send dhcp request
2019/10/25 20:29:30.943530 INFO Daemon Configure routes
2019/10/25 20:29:30.944523 INFO Daemon Gateway:10.112.10.1
2019/10/25 20:29:30.946440 INFO Daemon Routes:None
2019/10/25 20:29:30.956557 INFO Daemon Wire server endpoint:168.63.129.16
2019/10/25 20:29:30.966390 INFO Daemon Fabric preferred wire protocol version:2015-04-05
2019/10/25 20:29:30.967932 INFO Daemon Wire protocol version:2012-11-30
2019/10/25 20:29:30.968303 INFO Daemon Server preferred version:2015-04-05
2019/10/25 20:29:31.292412 INFO Daemon Found private key matching thumbprint 67AC2A2A7591B2F756FDF8CE4F01116AA9F7BB2E
2019/10/25 20:29:31.314562 ERROR Daemon Event: name=WALinuxAgent, op=Provision, message=Provisioning failed: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to get dvd device from /dev
Inner error: The following devices were found, but none matched the pattern [(sr[0-9]|hd[c-z]|cdrom[0-9]|cd[0-9])]: ['dumpdev', 'reroot', 'console', 'sndstat', 'random', 'urandom', 'hv_tsc', 'devctl', 'devctl2', 'geom.ctl', 'mdctl', 'input', 'kbdmux0', 'kbd1', 'mem', 'kmem', 'netmap', 'full', 'null', 'zero', 'pci', 'fd', 'stdin', 'stdout', 'stderr', 'nfslock', 'auditpipe', 'audit', 'midistat', 'sequencer0', 'music0', 'tcp_log', 'io', 'klog', 'uinput', 'ctty', 'consolectl', 'sysmouse', 'fido', 'bpf', 'bpf0', 'acpi', 'apmctl', 'apm', 'atkbd0', 'kbd0', 'psm0', 'bpsm0', 'ttyu0', 'ttyu0.init', 'ttyu0.lock', 'cuau0', 'cuau0.init', 'cuau0.lock', 'ttyu1', 'ttyu1.init', 'ttyu1.lock', 'cuau1', 'cuau1.init', 'cuau1.lock', 'devstat', 'ufssuspend', 'zfs', 'netdump', 'crypto', 'usbctl', 'xpt0', 'hv_kvp_dev', 'hv_fsvss_dev', 'hv_appvss_dev', 'pass0', 'pass1', 'pass2', 'pass3', 'pass4', 'pass5', 'fd0', 'da0', 'da1', 'da2', 'da3', 'da4', 'da5', 'da0p1', 'da0p2', 'da0p3', 'da1s1', 'gpt', 'ttyv0', 'ttyv1', 'ttyv2', 'ttyv3', 'ttyv4', 'ttyv5', 'ttyv6', 'ttyv7', 'ttyv8', 'ttyv9', 'ttyva', 'ttyvb', 'pts']
 (0s), duration=0
2019/10/25 20:29:31.318317 INFO Daemon RDMA capabilities are not enabled, skipping
2019/10/25 20:29:31.337976 INFO Daemon Determined Agent WALinuxAgent-2.2.44 to be the latest agent
2019/10/25 20:29:31.589185 INFO ExtHandler Agent WALinuxAgent-2.2.44 is running as the goal state agent
2019/10/25 20:29:31.591519 INFO ExtHandler Distro info: freebsd 12.1, osutil class being used: FreeBSDOSUtil, agent service name: waagent
2019/10/25 20:29:31.599208 INFO ExtHandler Wire server endpoint:168.63.129.16
2019/10/25 20:29:31.647334 INFO ExtHandler Start env monitor service.
2019/10/25 20:29:31.653701 INFO ExtHandler Configure routes
2019/10/25 20:29:31.654039 ERROR ExtHandler Command: [iptables --version], return code: [127], result: [/bin/sh: iptables: not found
]
2019/10/25 20:29:31.655109 INFO ExtHandler Gateway:None
2019/10/25 20:29:31.657243 WARNING ExtHandler Unable to determine version of iptables
2019/10/25 20:29:31.662576 INFO ExtHandler Routes:None
2019/10/25 20:29:31.670175 WARNING ExtHandler Unable to retrieve firewall packets droppedUnable to determine version of iptables
2019/10/25 20:29:31.701587 INFO ExtHandler Wire server endpoint:168.63.129.16
2019/10/25 20:29:31.719404 INFO ExtHandler WALinuxAgent-2.2.44 running as process 20200
2019/10/25 20:29:31.748370 INFO ExtHandler CGroups Status: Cgroups are not supported by the platform
2019/10/25 20:29:31.757825 INFO ExtHandler Wire server endpoint:168.63.129.16
2019/10/25 20:29:31.820336 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
2019/10/25 20:29:31.821954 ERROR ExtHandler /proc/net/route is missing headers
2019/10/25 20:29:31.822377 INFO ExtHandler Route table: []
2019/10/25 20:29:31.911336 INFO ExtHandler Wire server endpoint:168.63.129.16
2019/10/25 20:29:32.020434 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Target handler state: enabled
2019/10/25 20:29:32.023587 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] [Enable] current handler state is: enabled
2019/10/25 20:29:32.024220 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Update settings file: 0.settings
2019/10/25 20:29:32.026219 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9029] Enable extension [diagnostic.py -enable]
2019/10/25 20:29:34.097473 INFO ExtHandler Wire server endpoint:168.63.129.16
2019/10/25 20:29:34.101564 INFO ExtHandler ProcessGoalState completed [incarnation 27; 2190 ms]
2019/10/25 20:30:31.903393 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
2019/10/25 20:31:32.007228 ERROR ExtHandler Cannot read route table [[Errno 2] No such file or directory: '/proc/net/route']
```

**Comment by minusbat** [comment]
BTW, if you want access to the machine I am happy to provide it if you give me an ssh key... :-)

**Comment by onenachi** [comment]
Could you send me the contents of freebsd.py in /usr/local/lib/python/site-packages/azurelinuxagent/common/osutil/freebsd.py

**Comment by minusbat** [comment]
Ah, and theres the clue I needed - don't have a python.site-packages, but I do have a pytjon2.7/site-packages and also a python3.6/site-packages .... and it was using the python2.7 instead of the python3.6. I suspect this is because it uses 'python' to run the code instead of whatever python the 'setup.py' file was run with, so even though I built and installed it using 'python3.6 setup.py' it still just uses 'python' when it runs - which was pointing at python2.7

Having removed 2.7 entirely and made default python point at 3.6 it now work fine. Thanks for the help and sorry for the noise!
