### ISSUE TITLE
Azure - Password is expired and (401) Unauthorized, but access still works

### ISSUE THREAD

**Issue by KPCSInfra** [Azure/WALinuxAgent#149]
Hello.
I have many scripts for administration Azure on the server that runs in Azure.
The script authorizes to the Azure Tenant by using a Azure AD account. 
After a long time, I discovered that the account password has expired.
But this very important as the script continues to function and retrieves data from the tenant.

For example – The script that loads the status from the waagent daemons
**Part of script: (credentials):**
$User = "xxxxxxxxxxx@ebsacconeuseroutlook.onmicrosoft.com"
$File = "C:\Azure\AzurePassword.txt"
$securpass = (Get-Content $File | ConvertTo-SecureString)
$cred = New-Object System.Management.Automation.PSCredential($User, $securpass)
Add-AzureAccount -Credential $cred

**And there is a error:**
Add-AzureAccount : AADSTS70002: Error validating credentials. AADSTS50055: Password is expired.
Trace ID: eef223fc-ac71-45f3-bd32-17d495daa19e
Correlation ID: eb156e70-0a87-4624-bab3-1a439a55f0af
Timestamp: 2016-02-03 09:37:27Z: The remote server returned an error: (401) Unauthorized.
At C:\AZURE\AzureVM-status-waagent.ps1:38 char:1
+ Add-AzureAccount -Credential $cred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount

**Result of script:**
Checking VM:  xxxxx-portaldb1
VM Guest Agent Status:  Ready
VM SSH Port:  2222
VM/Cloud SSH VIP:  xx.xx.xx.xx

Despite the obvious error, the script continues retrieve data from the Tennant.
The credentials have expiration of about 12 hours ... and that information has been reported a many days ago in the log ...

Thank you.
Jakub Heinz

Sorry, but I not found the section which directly concern Azure AD

**Comment by yuezh** [comment]
Hi, @KPCSInfra. This seems to be an issue of Azure PowerShell. https://github.com/Azure/azure-powershell

**Comment by KPCSInfra** [comment]
KPCSInfra: Yes you are absolutely right. When i upgrade Azure PowerShell to version 1.2.0 problem has been solved. Thank you Jakub
