### ISSUE TITLE
[BUG] Failed uninstalling VM Extension when the installed version of VM Extension's image is deleted

### ISSUE THREAD

**Issue by coin8086** [Azure/WALinuxAgent#1495]
**Describe the bug**
When uninstalling a VM Extension and the version of the Extension image has been deleted, then it always failed, and it keeps writing error to `/var/log/waagent.log` about every second, like

```
2019/03/27 09:30:48.146700 WARNING [Microsoft.HpcPack.HpcAcmAgent-1.0.33.0] Failed to find installed version of Microsoft.HpcPack.HpcAcmAgent to uninstall
2019/03/27 09:30:48.200213 ERROR ExtHandler Event: name=Microsoft.HpcPack.HpcAcmAgent, op=Download, message=Unable to find version 1.0.33.0 in manifest for extension Microsoft.HpcPack.HpcAcmAgent, duration=0
```

Here, the Extension image of version 1.0.33.0 was deleted later after it had been installed on the VM. Now uninstalling 1.0.33.0 is impossible due to the issue!

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs: `/var/log/waagent.log`
2. Serial console output: N/A
3. Steps to reproduce the behavior: as said above

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: CentOS Linux release 7.5.1804 (Core)
 - WALinuxAgent version 2.2.38

**Additional context**
I've got to manually stop the error by
1. Manual disable & uninstall the extension(by commands in `HandlerManifest.json`) and remove the extension dir under `/var/lib/waagent`.
2. Kill the process of `/usr/bin/python -u /usr/sbin/waagent -daemon` and its sub process `python -u bin/WALinuxAgent-2.2.38-py2.7.egg -run-exthandlers`
3. Clean up `/var/lib/waagent/events` by deleting all files under it. 

BTW, one example file(`1553677422709637.tld`) under `events` was

  ```json
{
    "eventId": 1,
    "parameters": [
        {
            "name": "Name",
            "value": "Microsoft.HpcPack.HpcAcmAgent"
        },
        {
            "name": "Version",
            "value": "1.0.33.0"
        },
        {
            "name": "IsInternal",
            "value": false
        },
        {
            "name": "Operation",
            "value": "Download"
        },
        {
            "name": "OperationSuccess",
            "value": false
        },
        {
            "name": "Message",
            "value": "Unable to find version 1.0.33.0 in manifest for extension Microsoft.HpcPack.HpcAcmAgent"
        },
        {
            "name": "Duration",
            "value": 0
        },
        {
            "name": "ExtensionType",
            "value": ""
        }
    ],
    "providerId": "69B669B9-4AF8-4C50-BDC4-6006FA76E975"
}
  ```

And other files under `events` were all like this.

And, the `event_status.json` was

```json
{
    "WALinuxAgent-2.2.18-AutoUpdate": true,
    "WALinuxAgent-2.2.34-AutoUpdate": true,
    "WALinuxAgent-2.2.35.1-AutoUpdate": true,
    "WALinuxAgent-2.2.36-AutoUpdate": true,
    "WALinuxAgent-2.2.37-AutoUpdate": true,
    "WALinuxAgent-2.2.38-AutoUpdate": true
}
```

The `waagent_status.json` was
```json
{
    "agent_name": "WALinuxAgent",
    "current_version": "2.2.38",
    "distro_details": "centos:7.5.1804",
    "extensions_status": [
        {
            "name": "Microsoft.HpcPack.HpcAcmAgent",
            "status": "NotReady",
            "version": "1.0.33.0"
        }
    ],
    "goal_state_version": "2.2.38",
    "last_successful_status_upload_time": "2019-03-27T09:05:16Z",
    "python_version": "Python: 2.7.5"
}
```

Under, `/var/lib/waagent/Microsoft.HpcPack.HpcAcmAgent-1.0.33.0/config`, the `HandlerState` was

```
Enabled
```

and the `HandlerStatus` was

```json
{
    "code": -1,
    "extensions": [],
    "message": "Unable to find version 1.0.33.0 in manifest for extension Microsoft.HpcPack.HpcAcmAgent",
    "name": "Microsoft.HpcPack.HpcAcmAgent",
    "status": "NotReady",
    "version": "1.0.33.0"
}
```

**Comment by vrdmr** [comment]
Hi @coin8086 - Can you please remove this specific extension from the portal? It should get you out of the loop for the time being. We'll take a look at why this extension was removed from our image repository. Thanks.

**Comment by coin8086** [comment]
> Hi @coin8086 - Can you please remove this specific extension from the portal? It should get you out of the loop for the time being. We'll take a look at why this extension was removed from our image repository. Thanks.

Hi @vrdmr , it just can't be removed from the Azure portal, neither by PowerShell with Az module. We're the publisher for the VM Extension and the extension image of old version(1.0.33.0) was deleted by us. We need to delete the old version of image to make room for the new one.

**Comment by coin8086** [comment]
Hi @vrdmr, could I know how it's going, please? The bug matters to us.

**Comment by larohra** [comment]
Had offline discussion with @roiyz-msft.
