### ISSUE TITLE
[BUG/Question] CPU/Memory limit for WALinuxAgent

### ISSUE THREAD

**Issue by jithinjosepkl** [Azure/WALinuxAgent#1497]
**Describe the bug**

We are seeing nearly 20% of performance improvement for HPC applications if we disable WALinuxAgent. 

I notice that there is a cpulimit of 10% (azurelinuxagent/common/cgroups.py), but even this limit is impacting our workloads. A few questions here:

- Can this limit (cpu/memory) be made configurable?
- Is it safe to disable WALinuxAgent before job execution, and turn it on afterwards? Any recommended way for doing this? 
- What are the specific actions of the agent after VM bootup that affects CPU performance? Can this be made light-weight? 
- Are there any WALA guidelines/recommendations for CPU intensive workloads?

**Distro and WALinuxAgent details:**
 - Distro and Version: CentOS 7.6
 - WALinuxAgent version: 2.2.36 (but, we are planning to check the behavior with 2.2.38 also).

**Comment by vrdmr** [comment]
Hi @jithinjosepkl,

The CPU limit you are referring to is not enabled by default and `"CGroups.EnforceLimits"` flag is False by default.

> 1. Can this limit (cpu/memory) be made configurable?

We are working on such a feature to make in configurable for both extensions and agent. #1496 is the first attempt to do it.
> 2. Is it safe to disable WALinuxAgent before job execution, and turn it on afterwards? Any recommended way for doing this?

You can disable the WALinuxAgent service and enable it once your job is completed.
> 3. What are the specific actions of the agent after VM bootup that affects CPU performance? Can this be made light-weight?

In the past, we have observed cases such as AntiVirus and others, where the workloads was mis-accounted as used by WALinuxAgent. Or it could be installation/enabling of all the extensions just after the VM bootup, which could be putting strain on the CPU.
> 4. Are there any WALA guidelines/recommendations for CPU intensive workloads?

@pgombar, @narrieta are currently working on profiling WALinuxAgent, and will get back to you.

**Comment by jithinjosepkl** [comment]
Thanks @vrdmr for the details and making the limits configurable. 
@pgombar , @narrieta , please share your findings.

**Comment by jithinjosepkl** [comment]
@vrdmr - Curious if there are any more updates on this. 

Couple of follow up questions:
- Was there any reason why "CGroups.EnforceLimits" was not enabled by default?
- Can the WAAgent polling interval be made configurable?

Appreciate your thoughts on these.

**Comment by vrdmr** [comment]
Hi @jithinjosepkl - 

> Was there any reason why "CGroups.EnforceLimits" was not enabled by default?

- We are currently working on rolling out the Enforcing of limits and currently planning to get it to release in the coming releases. I'll update once that release is out.

> Can the WAAgent polling interval be made configurable?

-  With polling interval, I assume you mean the cgroup performance metrics collection interval. It is not configurable currently, but you can create a new issue and we can take that in the backlog.

Apologies for the delay. Please let me know if you have any questions, and please directly ping me if you want an immediate response.

**Comment by jithinjosepkl** [comment]
Thanks @vrdmr for the details. 

Yes, i meant the collection interval. I will create a new issue for that.

**Comment by pgombar** [comment]
@jithinjosepkl closing since we are tracking issue #1542 for this.
