### ISSUE TITLE
[BUG/Question] HyperV Entropy doesn't appear to be consumed through new agent system

### ISSUE THREAD

**Issue by nopjmp** [Azure/WALinuxAgent#1500]
**Describe the bug**
Per the README, `Consume Hyper-V entropy for /dev/random` this appears to only be done through the waagent2.0 script. The waagent script will only run the waagent2.0 script when `__name__ == 'waagent'`.

https://github.com/Azure/WALinuxAgent/blob/4c7c8925cb2a4109e9e7ba05800fe53f0b93596e/bin/waagent2.0#L5680-L5684

Unless I'm missing some other way that HyperV Entropy is being consumed especially since the HyperV VMBUS doesn't invoke the LRNG interrupt handler in the Linux kernel.

**Comment by vrdmr** [comment]
@trstringer - Would this be something that would be done only one time during Provisioning, or by the EnvironmentHandler thread regularly?

**Comment by narrieta** [comment]
@nojmp Thanks for pointing this out. The code in waagent2.0 corresponds to a really old version of the agent. You are right that the current agent does not do this anymore. I'll update the documentation.

**Comment by kovacs-andras** [comment]
I've experienced the same.
Please, do not state in the doc _"Consumes Hyper-V entropy for /dev/random"_ if it isn't.
A recommendation somewhere would be also useful. This is what rng-tools reported me on a freshly created VM:
```
$ rngd -l
Entropy sources that are available but disabled
1: TPM RNG Device
4: NIST Network Entropy Beacon
Available and enabled entropy sources:
2: Intel RDRAND Instruction RNG
5: JITTER Entropy generator
```
Thank you!

**Comment by colemickens** [comment]
So is it not necessary to do this anymore in Azure VMs or... why was this functionality removed?

**Comment by narrieta** [comment]
@kovacs-andras @colemickens The Agent was rewritten in late 2014 and the new version did not include this code, but the documentation was not updated. I have updated the documentation. The VM Agent is not the best place to do this; the place where it was done in the code may be too late for components that need this during boot. Also, the agent can be disabled/deleted. We are not planning on adding this functionality back.
