### ISSUE TITLE
[BUG] Broken dependency on WireProtocol implementation

### ISSUE THREAD

**Issue by DwayneNeed** [Azure/WALinuxAgent#1502]
**Describe the bug**
When the agent is using the MetadataProtocol it encounters errors when looking for extension cgroups.  The reason is that the code has incorrectly taken a dependency on the "client" field of the concrete WireProtocol implementation of the abstract Protocol class, and this field is not available on the MetadataProtocol class.

For VMs running on Azure Stack (which currently uses the MetadataProtocol path) you will see errors like this in the waagent.log file:

2019/04/09 00:17:55.117275 WARNING ExtHandler Monitor: failed to update cgroups tracked extensions: 'MetadataProtocol' object has no attribute 'client'

This repros with at least version 2.2.32 but the commit that introduced this dependency was 10 months ago:

https://github.com/Azure/WALinuxAgent/pull/1235/commits/317cb8ea6eb9b44fe7ff44b763542ada035aa6bb

**Additional context**
This is coming from this code in the agent:

https://github.com/Azure/WALinuxAgent/blob/ff01b372acf090cece0564c396b496783985624a/azurelinuxagent/ga/monitor.py#L471

            # Look for extension cgroups we're not already tracking and track them
            try:
                CGroupsTelemetry.update_tracked(self.protocol.client.get_current_handlers())
            except Exception as e:
                logger.warn("Monitor: failed to update cgroups tracked extensions: {0}", ustr(e))
                logger.verbose(traceback.format_exc())

This looks like a bug in the agent to me.  The “wire” and “metadata” protocols are implemented as derived classes from the base “Protocol” python class.  The rest of the agent code is supposed to be agnostic to protocol.  However, only the WireProtocol class implements the “client” field:

https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/common/protocol/wire.py#L94

class WireProtocol(Protocol):
    def __init__(self, endpoint):
        if endpoint is None:
            raise ProtocolError("WireProtocol endpoint is None")
        self.endpoint = endpoint
        self.client = WireClient(self.endpoint)

https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/common/protocol/metadata.py#L72

class MetadataProtocol(Protocol):
    def __init__(self, apiversion=APIVERSION, endpoint=METADATA_ENDPOINT):
        self.apiversion = apiversion
        self.endpoint = endpoint
        self.identity_uri = BASE_URI.format(self.endpoint, "identity",
                                            self.apiversion)
        self.cert_uri = BASE_URI.format(self.endpoint, "certificates",
                                        self.apiversion)
        self.ext_uri = BASE_URI.format(self.endpoint, "extensionHandlers",
                                       self.apiversion)
        self.vmagent_uri = BASE_URI.format(self.endpoint, "vmAgentVersions",
                                           self.apiversion)
        self.provision_status_uri = BASE_URI.format(self.endpoint,
                                                    "provisioningStatus",
                                                    self.apiversion, "")
        self.vm_status_uri = BASE_URI.format(self.endpoint, "status/vmagent",
                                             self.apiversion, "")
        self.ext_status_uri = BASE_URI.format(self.endpoint,
                                              "status/extensions/{0}",
                                              self.apiversion, "")
        self.event_uri = BASE_URI.format(self.endpoint, "status/telemetry",
                                         self.apiversion, "")
        self.certs = None
        self.agent_manifests = None
        self.agent_etag = None
        self.cert_etag = None

Note that the base Protocol class defines the interface as a simple set of methods:

https://github.com/Azure/WALinuxAgent/blob/ce58412bc50cee1d066bd01f0e52ad89d75f1a0d/azurelinuxagent/common/protocol/restapi.py#L319

class Protocol(DataContract):
    def detect(self):
        raise NotImplementedError()

    def get_vminfo(self):
        raise NotImplementedError()

    def get_certs(self):
        raise NotImplementedError()

    def get_incarnation(self):
        raise NotImplementedError()

    def get_vmagent_manifests(self):
        raise NotImplementedError()

    def get_vmagent_pkgs(self, manifest):
        raise NotImplementedError()

    def get_ext_handlers(self):
        raise NotImplementedError()

    def get_ext_handler_pkgs(self, extension):
        raise NotImplementedError()

    def get_artifacts_profile(self):
        raise NotImplementedError()

    def download_ext_handler_pkg(self, uri, destination, headers=None, use_proxy=True):
        raise NotImplementedError()

    def report_provision_status(self, provision_status):
        raise NotImplementedError()

    def report_vm_status(self, vm_status):
        raise NotImplementedError()

    def report_ext_status(self, ext_handler_name, ext_name, ext_status):
        raise NotImplementedError()

    def report_event(self, event):
        raise NotImplementedError()

    def supports_overprovisioning(self):
        return True

Python, like other late-bound languages does not flag these errors up front, so it looks like they slipped in an accidental dependency on a particular member field of the WireProtocol and hit an exception when the MetadataProtocol is being used.

**Comment by adepue** [comment]
@narrieta Proposal to address here:  https://github.com/Azure/WALinuxAgent/pull/1503

**Comment by narrieta** [comment]
This is fixed in 2.2.41
