### ISSUE TITLE
Which python does waagent depend on earth?

### ISSUE THREAD

**Issue by heyconnor** [Azure/WALinuxAgent#1513]
Python2.6? Nope. Python3.6? Nope. The doc is a mess.

**Comment by firemanxbr** [comment]
Hi @heyconnor Can you check our README.md in the main page of this repository:
https://github.com/Azure/WALinuxAgent#requirements

For more specific you can check also:
https://github.com/Azure/WALinuxAgent/blob/develop/requirements.txt 

I hope you can found all dependencies in both links.

**Comment by heyconnor** [comment]
@firemanxbr I saw it. But actually it only runs OK with python3.5.

**Comment by firemanxbr** [comment]
@heyconnor good to know. The WALinuxAgent expect "Python 2.6 **+**" Can you close this issue? based in your request I believe you have all info regarding requirement/dependency, right? if you want to help us with our documentation, suggestions you are welcome.

**Comment by heyconnor** [comment]
@firemanxbr Do you think it's ok that walinuxagent can only works in python3.5? If you think it's ok, I will close it. Anyway I don't use it. I would commit a support request in azure portal when walinuxagent couldn't work again.

**Comment by firemanxbr** [comment]
@heyconnor I have more than 1000k VMs with a bunch of different versions of python running without any issues regarding it. The "minimal" requirement is Python 2.6+, I believe you forget the specific version declared into the 'https://github.com/Azure/WALinuxAgent/blob/develop/requirements.txt':

**python_version >= '3.8'**

I'll send a PR to adjust this version in our [README.md](https://github.com/Azure/WALinuxAgent/blob/develop/README.md) to following the specific version included in your requirements.txt.

**Comment by firemanxbr** [comment]
PR Added: https://github.com/Azure/WALinuxAgent/pull/1520
