### ISSUE TITLE
ERROR ExtHandler Exception processing goal state, giving up: ['-----BEGIN PUBLIC KEY-----<key>-----END PUBLIC KEY-----\n']

### ISSUE THREAD

**Issue by bobsun0917** [Azure/WALinuxAgent#1514]
**ISSUE**
Image: Ubuntu 16.04 LTS
Waagent version: 2.2.32 | 2.2.40

waagent.log is filled with following messages,

INFO ExtHandler WireServer is not responding. Reset endpoint
INFO ExtHandler Protocol endpoint not found: WireProtocol, [ProtocolError] Exceeded max retry updating goal state
INFO ExtHandler Protocol endpoint not found: MetadataProtocol, [ProtocolError] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview
INFO ExtHandler Retry detect protocols: retry=45
INFO ExtHandler WireServer endpoint is not found. Rerun dhcp handler
INFO ExtHandler Test for route to 168.63.129.16
INFO ExtHandler Route to 168.63.129.16 exists
INFO ExtHandler Wire server endpoint:168.63.129.16
INFO ExtHandler Fabric preferred wire protocol version:2015-04-05
INFO ExtHandler Wire protocol version:2012-11-30
INFO ExtHandler Server preferred version:2015-04-05
ERROR ExtHandler Exception processing goal state, giving up: ['-----BEGIN PUBLIC KEY-----<key>-----END PUBLIC KEY-----\n']

**TROUBLESHOOTING**
1) The issue persists in version 2.2.32 and 2.2.40
2) Removing walinuxagent and install again but error remains.
3) paping port 80 on 168.63.129.16 and 169.254.169.254 can succeed

**Comment by johncrim** [comment]
I'm experiencing this exact same issue. This is a blocker for me/my company - we're unable to add new servers to our VM Scaleset. Any ideas for troubleshooting?

**Comment by johncrim** [comment]
Upon further review, I'm getting a slightly different error message - logged every 10 seconds. Again, this is new, didn't happen in deploys a month ago:

```
2019/06/11 04:29:13.084036 INFO Daemon WireServer endpoint is not found. Rerun dhcp handler
2019/06/11 04:29:13.090200 INFO Daemon Test for route to 168.63.129.16
2019/06/11 04:29:13.095114 INFO Daemon Route to 168.63.129.16 exists
2019/06/11 04:29:13.099579 INFO Daemon Wire server endpoint:168.63.129.16
2019/06/11 04:29:13.107259 INFO Daemon Fabric preferred wire protocol version:2015-04-05
2019/06/11 04:29:13.112963 INFO Daemon Wire protocol version:2012-11-30
2019/06/11 04:29:13.117719 INFO Daemon Server preferred version:2015-04-05
2019/06/11 04:29:13.255343 ERROR Daemon Command: [/usr/bin/openssl rsa -in /var/lib/waagent/1.prv -pubout 2>/dev/null], return code: [1], result: []
2019/06/11 04:29:13.266240 ERROR Daemon Command: [/usr/bin/openssl rsa -in /var/lib/waagent/2.prv -pubout 2>/dev/null], return code: [1], result: []
2019/06/11 04:29:13.347505 ERROR Daemon Command: [/usr/bin/openssl rsa -in /var/lib/waagent/1.prv -pubout 2>/dev/null], return code: [1], result: []
2019/06/11 04:29:13.360071 ERROR Daemon Command: [/usr/bin/openssl rsa -in /var/lib/waagent/2.prv -pubout 2>/dev/null], return code: [1], result: []
2019/06/11 04:29:13.449173 ERROR Daemon Command: [/usr/bin/openssl rsa -in /var/lib/waagent/1.prv -pubout 2>/dev/null], return code: [1], result: []
2019/06/11 04:29:13.458728 ERROR Daemon Command: [/usr/bin/openssl rsa -in /var/lib/waagent/2.prv -pubout 2>/dev/null], return code: [1], result: []
2019/06/11 04:29:13.489735 ERROR Daemon Exception processing goal state, giving up: ['']
2019/06/11 04:29:13.491628 INFO Daemon WireServer is not responding. Reset endpoint
2019/06/11 04:29:13.492419 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] Exceeded max retry updating goal state
2019/06/11 04:29:13.496862 INFO Daemon Protocol endpoint not found: MetadataProtocol, [ProtocolError] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview
2019/06/11 04:29:13.497767 INFO Daemon Retry detect protocols: retry=11
```

If this is a distinct issue, I'm happy to create a new bug.

This is on standard Azure VM Scalesets using Ubuntu 16.04. Needless to say, none of the other VM extensions are being run.

**Comment by johncrim** [comment]
Initially I thought I was seeing the same issue, but after investigation it appears distinct, so I created a new issue: #1550

**Comment by pgombar** [comment]
Hi @bobsun0917, please make sure only one openssl library is installed on the system. To confirm if this is causing the issue, try this command:
`/usr/bin/openssl x509 -in /var/lib/waagent/{thumbprint}.crt -fingerprint -noout`

If you see something like this in the output of the command, it means there is more than one reference to openssl and they are conflicting:
```
/usr/bin/openssl: /usr/local/openssl/lib/libssl.so.1.0.0: no version information available (required by /usr/bin/openssl)
/usr/bin/openssl: /usr/local/openssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/bin/openssl)
```

**Comment by pgombar** [comment]
Feel free to re-open if the issue persists after the proposed fix.
