### ISSUE TITLE
"apt-get install ubuntu-desktop" uninstalls waagent

### ISSUE THREAD

**Issue by bingosummer** [Azure/WALinuxAgent#152]
If customers want to install the desktop in the Ubuntu Azure VM,  "apt-get install ubuntu-desktop" will uninstall waagent.

The workaround:
Create a file called “/etc/apt/preferences.d/network-manager” with the following contents:
```
Package: network-manager
Pin: origin ""
Pin-Priority: -1
```
Now `apt-get install gnome-desktop` will work fine and not remove walinuxagent.

**Comment by szarkos** [comment]
FYI, after some discussion Ubuntu is now going to try to resolve this in the packaging as well:
https://bugs.launchpad.net/ubuntu/+source/walinuxagent/+bug/1550461

**Comment by chunliu** [comment]
The workaround doesn't seem to work on Ubuntu 15.10 image in Azure. With the workaround, `apt-get install gnome-desktop` gives an error "Unable to locate package gnome-desktop". `apt-get install Ubuntu-desktop` fails because network-manager-gnome cannot be installed. 

Did I miss anything?

**Comment by szarkos** [comment]
The fix for Ubuntu has been released: https://bugs.launchpad.net/ubuntu/+source/walinuxagent/+bug/1550461

**Comment by ahmetalpbalkan** [comment]
Closing as workaround is provided and Ubuntu fix is released.
