### ISSUE TITLE
Failed to update on Ubuntu 1604

### ISSUE THREAD

**Issue by justyu** [Azure/WALinuxAgent#1531]
I am stuck this issue #1342 #1139 and want to update WALinuxAgent to 2.2.40, but failed.

Current Version:
$waagent -version
WALinuxAgent-2.2.32.2 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.40

What I have tried:
1) sudo apt-get update
2) sudo apt-get install walinuxagent
but is shows:
$sudo apt-get install walinuxagent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
walinuxagent is already the newest version (2.2.32-0ubuntu1~16.04.2).
0 upgraded, 0 newly installed, 0 to remove and 82 not upgraded.

My VM is in Southeast Asia and East Asia,  and I have seen it has been fixed since 2.2.35 and deployed, but how can I update it to 2.2.35+ or 2.2.40?

**Comment by justyu** [comment]
update: finally I update to 2.2.40 by source code, but still hope to use apt-get to updata.

**Comment by narrieta** [comment]
@justyu --- there are 2 versions of the agent installed on each vm (more details here: https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output)

Your VMs should have auto-updated to 2.2.40 automatically (unless auto-update is disabled)
