### ISSUE TITLE
[BUG] Unable to run deprovision on Debian 9.6

### ISSUE THREAD

**Issue by frode** [Azure/WALinuxAgent#1540]
**Describe the bug**
Unable to run the process for deprovisioning:

username@machine:~$ sudo waagent –force -deprovision

usage: /usr/sbin/waagent [-verbose] [-force] [-help] -configuration-path:<path to configuration file>-provision|-deprovision[+user]|-register-service|-version|-daemon|-start|-run-exthandlers||-resourcedisk-show-configuration]

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs.
2. Serial console output
3. Steps to reproduce the behavior.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Debian 9.6
 - WALinuxAgent version WALinuxAgent-2.2.34 running on debian 9.6
Python: 3.5.3
Goal state agent: 2.2.34

**Additional context**
I was able to run the deprovision on Debian 9.4 a few days ago while prepping another VM image for Azure.

**Comment by jasonzio** [comment]
@frode can you add "-verbose" and remove "-force" from your invocation of "waagent -deprovision" and retry the operation? Add any output from waagent to this issue. Also, please check /var/log/waagent to see if there are logged messages from the time period when you run the deprovision command; if there are such entries, please attach them to this issue as well.

**Comment by frode** [comment]
Sure @jasonzio here is the output:

user@hostname:~$ sudo waagent -verbose -deprovision

WARNING! The waagent service will be stopped.

WARNING! All SSH host key pairs will be deleted.

WARNING! Cached DHCP leases will be deleted.

WARNING! root password will be disabled. You will not be able to login as root.

WARNING! /etc/resolv.conf will be deleted.

Do you want to proceed (y/n)y

2019/06/19 10:04:57.925947 VERBOSE Command: [systemctl --job-mode=ignore-dependencies stop walinuxagent]

2019/06/19 10:04:57.938361 VERBOSE Command: [hostname localhost.localdomain]

user@hostname:~$

**Comment by jasonzio** [comment]
That would seem to indicate that `-force` and `-deprovision` cannot be specified at the same time, which matches my intuition. I'm surprised it worked with an earlier version of waagent, assuming it did work with 9.4.

In any event, just don't use `-force` when deprovisioning.
