### ISSUE TITLE
[FeatureRequest] Make performance collection interval configurable

### ISSUE THREAD

**Issue by jithinjosepkl** [Azure/WALinuxAgent#1542]
It would be nice to have a configurable performance collection interval for sensitive workloads such as HPC. Please see #1497 for more details.

**Comment by pgombar** [comment]
@jithinjosepkl we will consider your request. We are currently working on enforcing CPU usage limits.

**Comment by narrieta** [comment]
Had a conversation with @jithinjosepkl. The ask is not about performance data collection itself, but about all periodic tasks the agent performs. Closing this issue and working with jithin separately.

**Comment by SlickNik** [comment]
@narrieta @jithinjosepkl We are also running a performance sensitive workload on Azure, and are being affected by periodic tasks performed by the agent. Would love to understand if you have any recommendations, or guidance to minimize this impact. Thanks!
