### ISSUE TITLE
[Linux] Extensions log files rotation

### ISSUE THREAD

**Issue by gpenin** [Azure/WALinuxAgent#1562]
As extensions log files keep growing indefinitly in /var/log/azure, would it be possible to add log rotation for the extensions in /etc/logrotate.d/waagent.logrotate ? Something like :

```
/var/log/azure/*/*.log {
    compress
    daily
    rotate 7
    notifempty
    missingok
}
```

Thanks in advance.

**Comment by gpenin** [comment]
Removing the "RFE" label as we start having issues with file systems being full and we now have impact on production services.

**Comment by othmanaljundi-microsoft** [comment]
First ensure that WALinuxAgent and omsagent are up to date : 

	# yum update WALinuxAgent
	# yum update omsagent

Then; we will be adding a new entry to logrotation service for this log file :

	# touch /etc/logrotate.d/omsagentextensions
	# vi /etc/logrotate.d/omsagentextensions

		LogFileFullPath
		{
			rotate 10
			hourly
			missingok
			notifempty
			delaycompress
			compress
			size 100M
		}

Restart rsyslog service :

	# service rsyslog restart

Restart Agent service :

	# /opt/microsoft/omsagent/bin/service_control restart
