### ISSUE TITLE
[BUG] WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1

### ISSUE THREAD

**Issue by maccas777** [Azure/WALinuxAgent#1578]
Error log have been having logs as above

 - Distro and Version: CentOS Linux release 7.6.1810 (Core) 
 - WALinuxAgent version WALinuxAgent.noarch  2.2.38-1.el7 

 waagent.log
2019/07/11 15:09:15.634147 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:14:19.218500 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:19:21.706711 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:24:25.268384 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:29:26.667209 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:34:29.337154 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:39:29.832826 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:44:32.302389 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:49:32.795438 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1
2019/07/11 15:54:40.567026 WARNING ExtHandler Failed to decode event file: not well-formed (invalid token): line 1, column 1

**Comment by hestolz** [comment]
FYI not distros-specific; seen on RedHat 7.3, SLES12 SP3, etc as well.

**Comment by vrdmr** [comment]
@nitinbps @zjalali Could you please take a look at this issue?

**Comment by maccas777** [comment]
Hi any idea if there is any fix for this ? Much appreciated if there could be a way to fix this thank you in advance

**Comment by vrdmr** [comment]
Hi @maccas777 - There is a new deployment in progress of the OMSExtension with the fix. It should be completed within a few days.

FYI - @zjalali, @simathih, @hestolz
