### ISSUE TITLE
Getting an error when installing any extension

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#1586]
## Issue 
Cannot run any extension.

## Version
```
# waagent --version
WALinuxAgent-2.2.41 running on centos 7.6.1810
Python: 2.7.16
Goal state agent: 2.2.41
```
This is a custom image and a lot of packages are missing.

## waagent.log

```
INFO ExtHandler Wire server endpoint:168.63.129.16
INFO ExtHandler ProcessGoalState completed [incarnation 1; 77 ms]
INFO ExtHandler Found private key matching thumbprint AE68D31732067426F2BCC7C7B73BC56E4B37A91E
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Target handler state: enabled
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] [Enable] current handler state is: notinstalled
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Downloading extension package: https://zrdfepirv2cy4prdstr04a.blob.core.windows.net/f72653efd9e349ed9842c8b99e4c1712/Microsoft.CPlat.Core__RunCommandLinux__1.0.1
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Unzipping extension package: /var/lib/waagent/Microsoft.CPlat.Core__RunCommandLinux__1.0.1.zip
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Initializing extension Microsoft.CPlat.Core.RunCommandLinux-1.0.1
INFO ExtHandler Created cgroup /sys/fs/cgroup/cpu/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
INFO ExtHandler Created cgroup /sys/fs/cgroup/memory/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Update settings file: 0.settings
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Install extension [bin/run-command-shim install]
INFO ExtHandler Added PID 7428 to cgroup /sys/fs/cgroup/cpu/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
INFO ExtHandler Added PID 7428 to cgroup /sys/fs/cgroup/memory/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
INFO ExtHandler Started tracking new cgroup: Microsoft.CPlat.Core.RunCommandLinux-1.0.1, path: /sys/fs/cgroup/cpu/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
INFO ExtHandler Started tracking new cgroup: Microsoft.CPlat.Core.RunCommandLinux-1.0.1, path: /sys/fs/cgroup/memory/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
ERROR ExtHandler Event: name=Microsoft.CPlat.Core.RunCommandLinux, op=Install, message=eJytkc1Kw1AQRvd5inkAk8mfJs1OasWC1uC2BElzp+2F5E6Ze6OpT2+S4k5BxM3ALL4zh2+2q8GRsZrNSoSlgg0b/4OEgQbtoGFFBUTxzRXstEHpjd9w19VG+faoO9DGurptva11intXeXEYLTDMMMohzIp0UcR5EGZJkiWw3tw/w3juYUy3JHCrFCko13eQpXEOjqE5CPcnQHu2uLd4WbE59fhet9r0Q30g4wL6Urb4pBthy3sXLMu2HicLBS+9WV4kH6fQaxSEQfSDWbq4zv5s1lHHcv4POW9ukEQqD6ei7bEAfKsFW70b+TP6Vzx/5uF3zyqgJOm0neRAkdGkvE9vD6wI, duration=0
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Remove extension handler directory: /var/lib/waagent/Microsoft.CPlat.Core.RunCommandLinux-1.0.1
INFO ExtHandler Deleted cgroup "/sys/fs/cgroup/cpu/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1".
INFO ExtHandler Deleted cgroup "/sys/fs/cgroup/memory/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1".
INFO ExtHandler ProcessGoalState completed [incarnation 2; 1655 ms]
INFO ExtHandler Stopped tracking cgroup: Microsoft.CPlat.Core.RunCommandLinux-1.0.1, path: /sys/fs/cgroup/cpu/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
INFO ExtHandler Stopped tracking cgroup: Microsoft.CPlat.Core.RunCommandLinux-1.0.1, path: /sys/fs/cgroup/memory/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
```
## CommandExecution.log

```
INFO [Microsoft.CPlat.Core.RunCommandLinux-1.0.1] Remove extension handler directory: /var/lib/waagent/Microsoft.CPlat.Core.RunCommandLinux-1.0.1
```
## Additional notes
I can see the extension zip file (*Microsoft.CPlat.Core__RunCommandLinux__1.0.1.zip*) in the waagent directory but the extension folder is missing.

## Question

Any idea what could be missing on that image that would prevent the extension from installing ?

**Comment by tboatman** [comment]
Packages installed on the system -

acl-2.2.51-14.el7
apr-1.4.8-3.el7_4.1
apr-devel-1.4.8-3.el7_4.1
apr-util-1.5.2-6.el7
apr-util-devel-1.5.2-6.el7
audit-2.8.4-4.el7
audit-libs-2.8.4-4.el7
authconfig-6.2.8-30.el7
autogen-libopts-5.18-5.el7
avahi-libs-0.6.31-19.el7
basesystem-10.0-7.el7.centos
bash-4.2.46-31.el7
bind-libs-32:9.9.4-74.el7_6.1
bind-libs-lite-32:9.9.4-74.el7_6.1
bind-license-32:9.9.4-74.el7_6.1
bind-utils-32:9.9.4-74.el7_6.1
binutils-2.27-34.base.el7
biosdevname-0.7.3-1.el7
boost-iostreams-1.53.0-27.el7
boost-random-1.53.0-27.el7
boost-system-1.53.0-27.el7
boost-thread-1.53.0-27.el7
bzip2-1.0.6-13.el7
bzip2-libs-1.0.6-13.el7
ca-certificates-2018.2.22-70.0.el7_5
centos-logos-70.0.6-3.el7.centos
centos-release-7-6.1810.2.el7.centos
chkconfig-1.7.4-1.el7
chrony-3.2-2.el7
cifs-utils-6.2-10.el7
compat-libstdc++-33-3.2.3-72.el7
copy-jdk-configs-3.3-10.el7_5
coreutils-8.22-23.el7
cpio-2.11-27.el7
cpp-4.8.5-36.el7_6.2
cracklib-2.9.0-11.el7
cracklib-dicts-2.9.0-11.el7
cronie-1.4.11-20.el7_6
cronie-anacron-1.4.11-20.el7_6
crontabs-1.11-6.20121102git.el7
cryptsetup-2.0.3-3.el7
cryptsetup-libs-2.0.3-3.el7
cups-libs-1:1.6.3-35.el7
curl-7.29.0-51.el7
cyrus-sasl-2.1.26-23.el7
cyrus-sasl-devel-2.1.26-23.el7
cyrus-sasl-lib-2.1.26-23.el7
dbus-1:1.10.24-13.el7_6
dbus-libs-1:1.10.24-13.el7_6
dejavu-fonts-common-2.33-6.el7
dejavu-sans-fonts-2.33-6.el7
device-mapper-7:1.02.149-10.el7_6.7
device-mapper-event-7:1.02.149-10.el7_6.7
device-mapper-event-libs-7:1.02.149-10.el7_6.7
device-mapper-libs-7:1.02.149-10.el7_6.7
device-mapper-multipath-0.4.9-123.el7
device-mapper-multipath-libs-0.4.9-123.el7
device-mapper-persistent-data-0.7.3-3.el7
dhclient-12:4.2.5-68.el7.centos.1
dhcp-common-12:4.2.5-68.el7.centos.1
dhcp-libs-12:4.2.5-68.el7.centos.1
diffutils-3.3-4.el7
dmidecode-1:3.1-2.el7
dos2unix-6.0.3-7.el7
dracut-033-554.el7
dracut-config-rescue-033-554.el7
dracut-fips-033-554.el7
dracut-network-033-554.el7
e2fsprogs-1.42.9-13.el7
e2fsprogs-libs-1.42.9-13.el7
elfutils-default-yama-scope-0.172-2.el7
elfutils-libelf-0.172-2.el7
elfutils-libs-0.172-2.el7
ethtool-2:4.8-9.el7
expat-2.1.0-10.el7_3
expat-devel-2.1.0-10.el7_3
file-5.11-35.el7
file-libs-5.11-35.el7
filesystem-3.2-25.el7
findutils-1:4.5.11-6.el7
fipscheck-1.4.1-6.el7
fipscheck-lib-1.4.1-6.el7
fontconfig-2.13.0-4.3.el7
fontpackages-filesystem-1.44-8.el7
freetype-2.8-12.el7_6.1
fuse-2.9.2-11.el7
fuse-libs-2.9.2-11.el7
gawk-4.0.2-4.el7_3.1
gcc-4.8.5-36.el7_6.2
gdb-7.6.1-114.el7
gdbm-1.10-8.el7
GeoIP-1.5.0-13.el7
gettext-0.19.8.1-2.el7
gettext-libs-0.19.8.1-2.el7
glib2-2.56.1-4.el7_6
glibc-2.17-260.el7_6.5
glibc-common-2.17-260.el7_6.5
glibc-devel-2.17-260.el7_6.5
glibc-headers-2.17-260.el7_6.5
gmp-1:6.0.0-15.el7
gnupg2-2.0.22-5.el7_5
grep-2.20-3.el7
groff-base-1.22.2-8.el7
grub2-1:2.02-0.76.el7.centos.1
grub2-common-1:2.02-0.76.el7.centos.1
grub2-pc-1:2.02-0.76.el7.centos.1
grub2-pc-modules-1:2.02-0.76.el7.centos.1
grub2-tools-1:2.02-0.76.el7.centos.1
grub2-tools-extra-1:2.02-0.76.el7.centos.1
grub2-tools-minimal-1:2.02-0.76.el7.centos.1
grubby-8.28-25.el7
gzip-1.5-10.el7
hardlink-1:1.0-19.el7
hmaccalc-0.9.13-4.el7
hostname-3.13-3.el7
httpd-2.4.6-89.el7.centos
httpd-devel-2.4.6-89.el7.centos
httpd-tools-2.4.6-89.el7.centos
hwdata-0.252-9.1.el7
info-5.1-5.el7
initscripts-9.49.46-1.el7
iproute-4.11.0-14.el7_6.2
iprutils-2.4.16.1-1.el7
iptables-1.4.21-28.el7
iptables-services-1.4.21-28.el7
iputils-20160308-10.el7
irqbalance-3:1.0.7-11.el7
iscsi-initiator-utils-6.2.0.874-10.el7
iscsi-initiator-utils-iscsiuio-6.2.0.874-10.el7
jansson-2.10-1.el7
java-1.8.0-openjdk-headless-1:1.8.0.212.b04-0.el7_6
javapackages-tools-3.4.1-11.el7
jbigkit-libs-2.0-11.el7
json-c-0.11-4.el7_0
kbd-1.15.5-15.el7
kbd-legacy-1.15.5-15.el7
kbd-misc-1.15.5-15.el7
kernel-3.10.0-957.21.3.el7
kernel-headers-3.10.0-957.21.3.el7
kexec-tools-2.0.15-21.el7_6.3
keyutils-1.5.8-3.el7
keyutils-libs-1.5.8-3.el7
kmod-20-23.el7
kmod-libs-20-23.el7
kpartx-0.4.9-123.el7
krb5-libs-1.15.1-37.el7_6
krb5-workstation-1.15.1-37.el7_6
less-458-9.el7
libacl-2.2.51-14.el7
libaio-0.3.109-13.el7
libarchive-3.1.2-10.el7_2
libassuan-2.1.0-3.el7
libattr-2.4.46-13.el7
libblkid-2.23.2-59.el7_6.1
libcap-2.22-9.el7
libcap-ng-0.7.5-4.el7
libcom_err-1.42.9-13.el7
libcom_err-devel-1.42.9-13.el7
libcroco-0.6.12-4.el7
libcurl-7.29.0-51.el7
libdaemon-0.14-7.el7
libdb-5.3.21-24.el7
libdb-devel-5.3.21-24.el7
libdb-utils-5.3.21-24.el7
libdnet-1.12-13.1.el7
libdrm-2.4.91-3.el7
libedit-3.0-12.20121213cvs.el7
libestr-0.1.9-2.el7
libfastjson-0.99.4-3.el7
libffi-3.0.13-18.el7
libgcc-4.8.5-36.el7_6.2
libgcrypt-1.5.3-14.el7
libgomp-4.8.5-36.el7_6.2
libgpg-error-1.12-3.el7
libicu-50.1.2-17.el7
libidn-1.28-4.el7
libjpeg-turbo-1.2.90-6.el7
libkadm5-1.15.1-37.el7_6
libldb-1.3.4-1.el7
libmnl-1.0.3-7.el7
libmount-2.23.2-59.el7_6.1
libmpc-1.0.1-3.el7
libmspack-0.5-0.6.alpha.el7
libndp-1.2-7.el7
libnetfilter_conntrack-1.0.6-1.el7_3
libnfnetlink-1.0.1-4.el7
libnl3-3.2.28-4.el7
libnl3-cli-3.2.28-4.el7
libpcap-14:1.5.3-11.el7
libpciaccess-0.14-1.el7
libpipeline-1.2.3-3.el7
libpng-2:1.5.13-7.el7_2
libpwquality-1.2.3-5.el7
librados2-1:10.2.5-4.el7
libreport-filesystem-2.1.11-42.el7.centos
libseccomp-2.3.1-3.el7
libselinux-2.5-14.1.el7
libselinux-utils-2.5-14.1.el7
libsemanage-2.5-14.el7
libsepol-2.5-10.el7
libsmartcols-2.23.2-59.el7_6.1
libsmbclient-0:4.8.3-4.el7
libss-1.42.9-13.el7
libssh-0.7.1-7.el7
libssh2-1.4.3-12.el7_6.2
libstdc++-4.8.5-36.el7_6.2
libsysfs-2.1.0-16.el7
libtalloc-2.1.13-1.el7
libtasn1-4.10-1.el7
libtdb-1.3.15-1.el7
libteam-1.27-5.el7
libtevent-0.9.36-1.el7
libtiff-4.0.3-27.el7_3
libtool-ltdl-2.4.2-22.el7_3
libunistring-0.9.3-9.el7
libuser-0.60-9.el7
libutempter-1.1.6-4.el7
libuuid-2.23.2-59.el7_6.1
libverto-0.2.5-4.el7
libwbclient-0:4.8.3-4.el7
libX11-1.6.5-2.el7
libX11-common-1.6.5-2.el7
libXau-1.0.8-2.1.el7
libxcb-1.13-1.el7
libXft-2.3.2-2.el7
libxml2-2.9.1-6.el7_2.3
libXrender-0.9.10-1.el7
libxslt-1.1.28-5.el7
linux-firmware-20180911-69.git85c5d90.el7
lksctp-tools-1.0.17-2.el7
lm_sensors-libs-3.4.0-6.20160601gitf9185e5.el7
logrotate-3.8.6-17.el7
lsscsi-0.27-6.el7
lua-5.1.4-15.el7
lvm2-7:2.02.180-10.el7_6.7
lvm2-libs-7:2.02.180-10.el7_6.7
lz4-1.7.5-2.el7
lzo-2.06-8.el7
mailcap-2.1.41-2.el7
mailx-12.5-19.el7
make-1:3.82-23.el7
man-db-2.6.3-11.el7
mariadb-libs-1:5.5.60-1.el7_5
mdadm-4.1-rc1_2.el7
microcode_ctl-2:2.1-47.4.el7_6
mod_nss-1.0.14-12.el7
mod_ssl-1:2.4.6-89.el7.centos
mozjs17-17.0.0-20.el7
mpfr-3.1.1-4.el7
nano-2.3.1-10.el7
ncurses-5.9-14.20130511.el7_4
ncurses-base-5.9-14.20130511.el7_4
ncurses-libs-5.9-14.20130511.el7_4
net-snmp-1:5.7.2-37.el7
net-snmp-agent-libs-1:5.7.2-37.el7
net-snmp-libs-1:5.7.2-37.el7
net-tools-2.0-0.24.20131004git.el7
NetworkManager-1:1.12.0-10.el7_6
NetworkManager-libnm-1:1.12.0-10.el7_6
NetworkManager-team-1:1.12.0-10.el7_6
NetworkManager-tui-1:1.12.0-10.el7_6
NetworkManager-wifi-1:1.12.0-10.el7_6
newt-0.52.15-4.el7
newt-python-0.52.15-4.el7
nspr-4.19.0-1.el7_5
nss-3.36.0-7.1.el7_6
nss-pem-1.0.3-5.el7_6.1
nss-softokn-3.36.0-5.el7_5
nss-softokn-freebl-3.36.0-5.el7_5
nss-sysinit-3.36.0-7.1.el7_6
nss-tools-3.36.0-7.1.el7_6
nss-util-3.36.0-1.1.el7_6
numactl-libs-2.0.9-7.el7
openldap-2.4.44-21.el7_6
openldap-clients-2.4.44-21.el7_6
openldap-devel-2.4.44-21.el7_6
openssh-7.4p1-16.el7
openssh-clients-7.4p1-16.el7
openssh-server-7.4p1-16.el7
openssl-1:1.0.2k-16.el7_6.1
openssl-libs-1:1.0.2k-16.el7_6.1
open-vm-tools-10.2.5-3.el7
os-prober-1.58-9.el7
p11-kit-0.23.5-3.el7
p11-kit-trust-0.23.5-3.el7
pam-1.1.8-22.el7
parted-3.1-29.el7
passwd-0.79-4.el7
pciutils-3.5.1-3.el7
pciutils-libs-3.5.1-3.el7
pcre-8.32-17.el7
pcsc-lite-libs-1.8.8-8.el7
perl-4:5.16.3-294.el7_6
perl-Carp-1.26-244.el7
perl-constant-1.27-2.el7
perl-Data-Dumper-2.145-3.el7
perl-Encode-2.51-7.el7
perl-Exporter-5.68-3.el7
perl-File-Path-2.09-2.el7
perl-File-Temp-0.23.01-3.el7
perl-Filter-1.49-3.el7
perl-Getopt-Long-2.40-3.el7
perl-HTTP-Tiny-0.033-3.el7
perl-libs-4:5.16.3-294.el7_6
perl-macros-4:5.16.3-294.el7_6
perl-parent-1:0.225-244.el7
perl-PathTools-3.40-5.el7
perl-Pod-Escapes-1:1.04-294.el7_6
perl-podlators-2.5.1-3.el7
perl-Pod-Perldoc-3.20-4.el7
perl-Pod-Simple-1:3.28-4.el7
perl-Pod-Usage-1.63-3.el7
perl-Scalar-List-Utils-1.27-248.el7
perl-Socket-2.010-4.el7
perl-Storable-2.45-3.el7
perl-Text-ParseWords-3.29-4.el7
perl-threads-1.87-4.el7
perl-threads-shared-1.43-6.el7
perl-Time-HiRes-4:1.9725-3.el7
perl-Time-Local-1.2300-2.el7
pinentry-0.8.1-17.el7
pkgconfig-1:0.27.1-4.el7
plymouth-0.8.9-0.31.20140113.el7.centos
plymouth-core-libs-0.8.9-0.31.20140113.el7.centos
plymouth-scripts-0.8.9-0.31.20140113.el7.centos
policycoreutils-2.5-29.el7_6.1
polkit-0.112-18.el7_6.1
polkit-pkla-compat-0.1-4.el7
popt-1.13-16.el7
postfix-2:2.10.1-7.el7
procps-ng-3.3.10-23.el7
psmisc-22.20-15.el7
pth-2.0.7-23.el7
python-2.7.5-80.el7_6
python-javapackages-3.4.1-11.el7
python-libs-2.7.5-80.el7_6
python-lxml-3.2.1-4.el7
qrencode-libs-3.4.1-3.el7
readline-6.2-10.el7
rootfiles-8.1-11.el7
rpm-4.11.3-35.el7
rpm-build-libs-4.11.3-35.el7
rpm-libs-4.11.3-35.el7
rsh-0.17-79.el7
rsync-3.1.2-6.el7_6.1
rsyslog-8.24.0-34.el7
samba-client-0:4.8.3-4.el7
samba-client-libs-0:4.8.3-4.el7
samba-common-0:4.8.3-4.el7
samba-common-libs-0:4.8.3-4.el7
screen-4.1.0-0.25.20120314git3c2946.el7
sed-4.2.2-5.el7
selinux-policy-3.13.1-229.el7_6.12
selinux-policy-targeted-3.13.1-229.el7_6.12
setup-2.8.71-10.el7
shadow-utils-2:4.1.5.1-25.el7_6.1
shared-mime-info-1.8-4.el7
slang-2.2.4-11.el7
snappy-1.1.0-3.el7
sqlite-3.7.17-8.el7
stix-fonts-1.1.0-5.el7
strace-4.12-9.el7
sudo-1.8.23-3.el7
sysfsutils-2.1.0-16.el7
sysstat-10.1.5-17.el7
systemd-219-62.el7_6.6
systemd-libs-219-62.el7_6.6
systemd-sysv-219-62.el7_6.6
sysvinit-tools-2.88-14.dsf.el7
tar-2:1.26-35.el7
tcl-1:8.5.13-8.el7
tcpdump-14:4.9.2-3.el7
tcp_wrappers-libs-7.6-77.el7
teamd-1.27-5.el7
telnet-1:0.17-64.el7
tk-1:8.5.13-6.el7
tzdata-2019a-1.el7
tzdata-java-2019a-1.el7
unzip-6.0-19.el7
ustr-1.0.4-16.el7
util-linux-2.23.2-59.el7_6.1
vim-minimal-2:7.4.160-5.el7
wget-1.14-18.el7_6.1
which-2.20-7.el7
wpa_supplicant-1:2.6-12.el7
xfsprogs-4.5.0-19.el7_6
xmlsec1-1.2.20-7.el7_4
xmlsec1-openssl-1.2.20-7.el7_4
xz-5.2.2-1.el7
xz-libs-5.2.2-1.el7
zlib-1.2.7-18.el7

**Comment by narrieta** [comment]
The extension install is failing with error "Permission Denied". You can decode the message in the ERROR using this:

`echo '<encoded data>' | base64 -d | pigz -zd`

In this case the message is

> [ExtensionError] Non-zero exit code: 126, bin/run-command-shim install
> [stdout]
> 2019/07/18 07:49:28.073373 INFO ExtHandler Added PID 7428 to cgroup /sys/fs/cgroup/cpu/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
> 2019/07/18 07:49:28.074957 INFO ExtHandler Added PID 7428 to cgroup /sys/fs/cgroup/memory/walinuxagent.extensions/Microsoft.CPlat.Core.RunCommandLinux_1.0.1
> 
> [stderr]
> /bin/sh: /var/lib/waagent/Microsoft.CPlat.Core.RunCommandLinux-1.0.1/bin/run-command-shim: Permission denied

You could try debugging why "bin/run-command-shim install" fails. The code is here: https://github.com/Azure/run-command-extension-linux/blob/master/misc/run-command-shim

**Comment by johanburati** [comment]
Thanks @narrieta, you can close this issue, the problem was that /var was being mounted with noexec.
