### ISSUE TITLE
HostGA plugin issue with waagent in Linux VMs

### ISSUE THREAD

**Issue by Mangaleshwar** [Azure/WALinuxAgent#1596]
Waagent is unable to report back to portal because of which the extensions are not working. 

Waagent is running in the guest OS level but we are seeing below errors because of which the VMs are not reporting back to the portal.

Waagent version: 2.2.38
Goal state version: 2.2.41

**Waagent Logs:**
2019/07/22 12:36:56.449403 ERROR ExtHandler HostGAPlugin: Exception Get API versions: [HttpError] [HTTP Failed] GET http://168.63.129.16:32526/versions -- IOError timed out -- 6 attempts made
2019/07/22 12:36:56.509673 ERROR ExtHandler Event: name=WALinuxAgent, op=HealthObservation, message={"Value": "", "ObservationName": "GuestAgentPluginVersions", "Description": "", "IsHealthy": false}, duration=0
2019/07/22 12:36:56.518549 ERROR ExtHandler Event: name=WALinuxAgent, op=InitializeHostPlugin, message=, duration=0
2019/07/22 12:37:06.596718 INFO ExtHandler Route table: [{"Iface": "eth0", "Destination": "168.63.129.16", "Gateway": "10.X.X.X", "Mask": "255.255.255.255", "Flags": "0x0007", "Metric": "0"},{"Iface": "eth0", "Destination": "169.254.169.254", "Gateway": "10.34.128.1", "Mask": "255.255.255.255", "Flags": "0x0007", "Metric": "0"},{"Iface": "eth0", "Destination": "10.X.X.X", "Gateway": "0.0.0.0", "Mask": "255.255.252.0", "Flags": "0x0001", "Metric": "0"},{"Iface": "eth0", "Destination": "169.254.0.0", "Gateway": "0.0.0.0", "Mask": "255.255.0.0", "Flags": "0x0001", "Metric": "1002"},{"Iface": "eth0", "Destination": "0.0.0.0", "Gateway": "10.34.128.1", "Mask": "0.0.0.0", "Flags": "0x0003", "Metric": "0"}]
2019/07/22 12:38:27.525187 ERROR ExtHandler HostGAPlugin: Exception Get API versions: [HttpError] [HTTP Failed] GET http://168.63.129.16:32526/versions -- IOError timed out -- 6 attempts made
2019/07/22 12:38:27.585661 ERROR ExtHandler Event: name=WALinuxAgent, op=HealthObservation, message={"Value": "", "ObservationName": "GuestAgentPluginVersions", "Description": "", "IsHealthy": false}, duration=0
2019/07/22 12:38:27.588360 ERROR ExtHandler Event: name=WALinuxAgent, op=InitializeHostPlugin, message=, duration=0
2019/07/22 12:38:27.636012 WARNING ExtHandler Exception retrieving agent manifests: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/ga/update.py", line 658, in _upgrade_available
    pkg_list = protocol.get_vmagent_pkgs(manifests[0])
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/wire.py", line 144, in get_vmagent_pkgs
    ga_manifest = self.client.get_gafamily_manifest(vmagent_manifest, goal_state)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/wire.py", line 962, in get_gafamily_manifest
    vmagent_manifest.versionsManifestUris)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/wire.py", line 624, in fetch_manifest
    uri, headers = host.get_artifact_request(version.uri)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 129, in get_artifact_request
    raise ProtocolError("HostGAPlugin: Host plugin channel is not available")
ProtocolError: [ProtocolError] HostGAPlugin: Host plugin channel is not available

2019/07/22 12:38:27.636523 ERROR ExtHandler Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/ga/update.py", line 658, in _upgrade_available
    pkg_list = protocol.get_vmagent_pkgs(manifests[0])
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/wire.py", line 144, in get_vmagent_pkgs
    ga_manifest = self.client.get_gafamily_manifest(vmagent_manifest, goal_state)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/wire.py", line 962, in get_gafamily_manifest
    vmagent_manifest.versionsManifestUris)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/wire.py", line 624, in fetch_manifest
    uri, headers = host.get_artifact_request(version.uri)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 129, in get_artifact_request
    raise ProtocolError("HostGAPlugin: Host plugin channel is not available")
ProtocolError: [ProtocolError] HostGAPlugin: Host plugin channel is not available
, duration=0

We are seeing similar errors in few other VMs as well, but in those cases the guest agent reports back to portal successfully but we are still seeing the errors related to HostGA plugin. All the VMs where we are seeing these issues are in West Europe region.

Please let me know if any further information is required.

Regards,
Mangaleshwar

**Comment by larohra** [comment]
Looks like there was some network issues back then in West Europe. This issue would've auto-mitigated since then.  
Additionally we have improved HostGA Plugin resiliency in the linux agent so you hopefully shouldn't see this issue again. If this issue is still persisting, please share tha waagent.log file and I can take a look.

Reopen if still persists.
