### ISSUE TITLE
Error messages to syslog and waagent.log every 5 seconds

### ISSUE THREAD

**Issue by raykimsey** [Azure/WALinuxAgent#1610]
**Describe the bug**

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs.
2. Serial console output
3. Steps to reproduce the behavior.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: [e.g. Ubuntu 16.04]
 - WALinuxAgent version [e.g. 2.2.34, you can copy the output of `waagent --version`, more info [here](https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output) ]

**Additional context**

**Comment by raykimsey** [comment]
I know this has been reported in the past #1393, but not sure if it is being resolved or not. It is still occurring. I just upgrade a VM from ubuntu 16.04 to 18.04 and started having the message:
2019/08/20 06:59:45.813486 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []
added to the syslog and waagent.log file.  Manually starting systemd-networkd (after the system is up and running) mitigates the logging, but not sure what other impact that may be having on the system. Having systemd-networkd start up automatically plays havoc with the network settings on the system. 

waagent -version
WALinuxAgent-2.2.40 running on ubuntu 18.04
Python: 3.6.8
Goal state agent: 2.2.42

**Comment by narrieta** [comment]
@raykimsey - we will have a fix for this issue in our next release, thanks for pointing it out.

**Comment by narrieta** [comment]
The fix is included in v2.2.44, which is currently being deployed to production.
