### ISSUE TITLE
2.2.42 agent constantly calls xtables-multi/iptables --version

### ISSUE THREAD

**Issue by dsa8345784935** [Azure/WALinuxAgent#1615]
Since upgrading to 2.2.42 my logs are filled with constant (every 5s) xtables/iptables --version logs from the agent

surely it's a mistake to run this every 5s executing "iptables --version" via xtables-multi

waagent --version
WALinuxAgent-2.2.40 running on ubuntu 18.04
Python: 3.6.8
Goal state agent: 2.2.42

This is enabled in /etc/waagent.conf
OS.EnableFirewall=y

Example from logs (not more logs suppressed):
```
Aug 22 15:49:13 linuxhost kernel: [4727583.107247] kauditd_printk_skb: 56 callbacks suppressed
Aug 22 15:49:13 linuxhost kernel: [4727583.107249] audit: type=1300 audit(1566514153.835:32399508): arch=c000003e syscall=59 success=yes exit=0 a0=7f42d07b8c28 a1=7f42cddcd770 a2=7fffaa2e82c0 a3=9 items=2 ppid=85554 pid=91077 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="sh" exe="/bin/bash" subj==unconfined key="auoms"
Aug 22 15:49:13 linuxhost kernel: [4727583.107253] audit: type=1309 audit(1566514153.835:32399508): argc=3 a0="/bin/sh" a1="-c" a2=69707461626C6573202D2D76657273696F6E
Aug 22 15:49:13 linuxhost kernel: [4727583.107255] audit: type=1307 audit(1566514153.835:32399508): cwd="/var/lib/waagent/WALinuxAgent-2.2.42"
Aug 22 15:49:13 linuxhost kernel: [4727583.107257] audit: type=1302 audit(1566514153.835:32399508): item=0 name="/bin/sh" inode=3027 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
Aug 22 15:49:13 linuxhost kernel: [4727583.107259] audit: type=1302 audit(1566514153.835:32399508): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=10430 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
Aug 22 15:49:13 linuxhost kernel: [4727583.107261] audit: type=1327 audit(1566514153.835:32399508): proctitle=2F62696E2F7368002D630069707461626C6573202D2D76657273696F6E
Aug 22 15:49:13 linuxhost kernel: [4727583.109243] audit: type=1300 audit(1566514153.839:32399509): arch=c000003e syscall=59 success=yes exit=0 a0=55b5a447baa0 a1=55b5a447bd50 a2=55b5a4479d20 a3=55b5a4471010 items=2 ppid=85554 pid=91077 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/sbin/xtables-multi" subj==unconfined key="auoms"
Aug 22 15:49:13 linuxhost kernel: [4727583.109246] audit: type=1309 audit(1566514153.839:32399509): argc=2 a0="iptables" a1="--version"
Aug 22 15:49:13 linuxhost kernel: [4727583.109248] audit: type=1307 audit(1566514153.839:32399509): cwd="/var/lib/waagent/WALinuxAgent-2.2.42"
Aug 22 15:49:13 linuxhost kernel: [4727583.109250] audit: type=1302 audit(1566514153.839:32399509): item=0 name="/sbin/iptables" inode=9661 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
```

**Comment by vrdmr** [comment]
Hi @dsa8345784935, Apologies for the late reply.

The agent does check the firewall settings every 5 seconds - It is in the design to make sure that the environment is correct for the WALinuxAgent to run. This is a very important operation for our agent and we cannot turn it off as we configure the network rules to keep our access to important endpoints open.

For more context - the `iptables --version` call is done in `osutil.enable_firewall`.

[`osutil.enable_firewall`](https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/ga/env.py#L115)
|- [`get_firewall_will_wait()`](https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/common/osutil/default.py#L218)
|-|- [`shellutil.run_get_output(IPTABLES_VERSION)`](https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/common/osutil/default.py#L147)

If you feel that there is something we can do to reduce the logs (especially in `syslog`), please let us know.

**Comment by andresbarcenas** [comment]
@vrdmr There is no way to disable the noise? We are getting flooded with messages and this becomes a problem. Any ideas?
