### ISSUE TITLE
Misleading information in the FAQ page

### ISSUE THREAD

**Issue by marinnedea** [Azure/WALinuxAgent#1636]
In the https://github.com/Azure/WALinuxAgent/wiki/FAQ#how-to-remove-agent-from-the-box page, the instructions to remove the walinuxagent are: 

>  Depending on the distro - You'll need to stop the agent service.
> 
> systemctl stop walinuxagent # Or service walinuxagent stop
> waagent -deprovision -force
> rm -rf /var/lib/waagent

The information above will not remove the walinuxagent from the box, but will deprovision the VM and prepare it to become a golden image. 
The above will remove the walinuxagent configuration from the box together with user details and set the VM to a state that will allow that VM to be further  used  as a base image for future VM deployments. 
Running this on a production machine will render that machine unusable!

Please modify the instructions and be more specific about what command is doing what.

**Comment by vrdmr** [comment]
@pgombar #1608

**Comment by pgombar** [comment]
Thanks for pointing this out, @marinnedea. We've updated the FAQ accordingly.
