### ISSUE TITLE
[BUG] waagent doesn't mount temporary storage on Gen2 VMs

### ISSUE THREAD

**Issue by msftphleiten** [Azure/WALinuxAgent#1645]
temporary storage is not mounted and therefor swap space doesn't get active with error:

2019/09/17 07:43:28.253251 INFO Daemon Activate resource disk
2019/09/17 07:43:28.255774 ERROR Daemon Failed to mount resource disk [ResourceDiskError] unable to detect disk topology
2019/09/17 07:43:28.257645 ERROR Daemon Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[ResourceDiskError] unable to detect disk topology, duration=0

disks are not SCSI and not IDE anymore.

def mount_resource_disk(self,   mount_point):
--
  | device = self.osutil.**device_for_ide_port**(1)
  | if device is None:
  | raise   ResourceDiskError("unable to detect disk topology")

it only applies to Gen2 VMs (Mv2) as this changes the way disks are handled.
 - Distro and Version: SLES12SP4 Gen2 and SLES15 Gen2 images on marketplace

**Comment by narrieta** [comment]
@jasonzio related to #1362

**Comment by vrdmr** [comment]
Hey @trstringer Could you please take a look at this issue. Thanks.

**Comment by trstringer** [comment]
Fixed by #1654.
