### ISSUE TITLE
[BUG] The Pre Release agent keeps logging INFO messages

### ISSUE THREAD

**Issue by plessisa** [Azure/WALinuxAgent#1653]
Since I upgarded to 2.2.43, I keep receiving log at INFO level every 3 sec:
2019/10/03 14:23:33.469158 INFO ExtHandler Using host plugin as default channel
2019/10/03 14:23:33.487082 INFO ExtHandler Request succeeded using the host plugin channel.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: OpenWRT
 - WALinuxAgent version 2.2.43

Find attach the log file with verbose

[waagent.log](https://github.com/Azure/WALinuxAgent/files/3686558/waagent.log)

**Comment by narrieta** [comment]
@plessisa - Thank you for reporting this. We'll take a look

**Comment by pgombar** [comment]
Hi @plessisa, thanks for letting us know. We were able to identify the issue early in the release. We are issuing a fix and resetting the release.

**Comment by plessisa** [comment]
@pgombar This is resolved on 2.2.43.1.
Thanks
