### ISSUE TITLE
Unconfined Service

### ISSUE THREAD

**Issue by warringaa** [Azure/WALinuxAgent#166]
The WALinuxAgent runs on CentOS/RHEL in an unconfined SELinux domain, therefore this proces fall back to using DAC rules exclusively. If this process is compromised, SELinux does not prevent an attacker from gaining access to system resources and data, but of course, DAC rules are still used. 

Please make specific SELinux policies for the WALinuxAgent so that we don't only have to relay on the DAC rules. Below you will find an example of the output of 'ps auxZ':

system_u:**system_r:unconfined_service_t**:s0 root 1343 0.0  0.2 457440 16192 ?    Ssl  Mar25   5:05 python /usr/sbin/waagent -daemon

**Comment by ahmetalpbalkan** [comment]
@warringaa thanks for reporting this.

In our case, WALinuxAgent forks off various Virtual Machine Extensions which inherently run arbitrary code themselves or provided by the user. This functionality is often used to install new packages and configure the virtual machine. I am not sure if we can come up with a SELinux domain in this case.

**Comment by ahmetalpbalkan** [comment]
Closing as wontfix.
