### ISSUE TITLE
Allow running on VMs with both Python 2 and Python 3

### ISSUE THREAD

**Issue by gopitk** [Azure/WALinuxAgent#167]
On my VM the default python per PATH precedence is setup for Python 3. This causes waagent to not run since it is Python 2.

The issue is coming up when submitting VM images for publishing in the Azure marketplace where as part of verification waagent is run and it fails since it is trying to run under Python 3.

Can we make waagent run on both Python 2 or 3 OR force it to run in Python 2 (In my case /usr/bin/python was still Python 2. In the PATH the Python 3 directory had a higher precedence)

BTW - I am using the default waagent that came with the VM (CentOS 7.x) and I am not installing it from github.

**Comment by ahmetalpbalkan** [comment]
@gopitk It would be helpful to know what exact version of centos and waagent you are using.

On distros like Ubuntu 15.10 and 16.04 where python 2 and 3 co-exist, waagent works just fine as far as I know.

What is the error you are seeing in centos when both are installed? (`journalctl -au waagent`). In any case a fix would be at least a few months away, if you can fix the shebang in the first line of `/sbin/waagent`, it may unblock you.

**Comment by ahmetalpbalkan** [comment]
after discussing with @gopitk they need an agent that could work on python3. waagent 2.1.x supports python3 and here's the instructions to update the agent version: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-update-agent/
