### ISSUE TITLE
[WAagent 2.1] Should evaluate ssh pub key file before using it

### ISSUE THREAD

**Issue by karataliu** [Azure/WALinuxAgent#169]
Should evaluate the pub key file before generate thumbprint, but now it looks at the private key file.

1. Check private key (should be .pub)
https://github.com/Azure/WALinuxAgent/blob/5bfc685/azurelinuxagent/distro/ubuntu/provision.py#L91

2. Generate thumbprint:
https://github.com/Azure/WALinuxAgent/blob/78d9a9d/azurelinuxagent/distro/default/provision.py#L86

**Comment by ahmetalpbalkan** [comment]
@karataliu I am not sure if I understand this. 

Are you saying `get_ssh_host_key_thumbprint` and `wait_for_ssh_host_key` are somewhat related?

It looks like `wait_for_ssh_host_key` can work just fine by looking at the private key. I don't see an issue.

**Comment by hglkrijger** [comment]
@karataliu, does the [referenced commit](https://github.com/hglkrijger/WALinuxAgent/commit/26c972a3796639ed95d4c3555d923ca3504bbd66) implement what you had in mind?

**Comment by ahmetalpbalkan** [comment]
@hglkrijger I'm not sure if that change should be made. The keys and public keys are always generated together and `wait_for_ssh_host_key` is just used as an indicator to find out if cloud-init is completed. The change essentially does not change anything.

**Comment by hglkrijger** [comment]
@ahmetalpbalkan, I *think* the concern behind the original issue was that we check for the existence of one file and then load another. Although we expect them to be generated together, it makes sense to check for the file we are going to load, doesn't it?

**Comment by ahmetalpbalkan** [comment]
@hglkrijger hmm I thought that function was computing the thumbprint of user-provided OpenSSH public key. 

I just realized we actually have some logic that sends the ssh host key thumbprint in the 'provisioned' signal to the Wire Server. 

I am not sure why we do it, if this is actually necessary or cloud-init does the same as well. We should probably understand these first. In any case, it makes sense to apply the change.

**Comment by szarkos** [comment]
The agent pushes the ssh host key fingerprint to the fabric so that it is available to the user via the portal or via the API (i.e. the classic Get Deployment API).  They'll want to verify this when they connect to the VM via SSH for the first time.  The original agent behavior was to push the fingerprint just once at runtime, but in some cases the host key did not exist yet (i.e. cloud-init may not have created it yet), and so wait_for_ssh_host_key() was added.

FYI, the waitFor3rdPartyProvision() is what's used to determine if cloud-init has finished provisioning.

**Comment by karataliu** [comment]
@ahmetalpbalkan, The issue is created for following reason:
'get_ssh_host_key_thumbprint' is waiting for private key and 'get_ssh_host_key_thumbprint' is working on public key. If the two keys were not presented at same time, the later function would fail.

Here is what we do in V2.0: https://github.com/Azure/WALinuxAgent/blob/a41d97a0ac34350ae499969fd54755c563c62de8/waagent#L6740-L6743

And I think the commit https://github.com/hglkrijger/WALinuxAgent/commit/26c972a3796639ed95d4c3555d923ca3504bbd66 can address the issue.

**Comment by hglkrijger** [comment]
fix merged into develop
