### ISSUE TITLE
Unable to detect disk topology resource disk of 8TB of ram 

### ISSUE THREAD

**Issue by jofrance** [Azure/WALinuxAgent#1711]
**Describe the bug**

Uable to detect disk topology, this is given on VMs with more than 4TB on the resource drive, I'm testing on Standard_m416s_v2 that has an 8TB drive, I think that this is related that the waagent used normal partitioning instead of gpt. 

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs.

2019/11/15 20:06:57.724373 INFO Daemon Activate resource disk
2019/11/15 20:06:57.727226 ERROR Daemon Failed to mount resource disk [ResourceDiskError] unable to detect disk topology
2019/11/15 20:06:57.731916 ERROR Daemon Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[ResourceDiskError] unable to detect disk topology, duration=0

2. Serial console output

2019/11/15 20:06:57.724373 INFO Daemon Activate resource disk
2019/11/15 20:06:57.727226 ERROR Daemon Failed to mount resource disk [ResourceDiskError] unable to detect disk topology
2019/11/15 20:06:57.731916 ERROR Daemon Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[ResourceDiskError] unable to detect disk topology, duration=0

3. Steps to reproduce the behavior.

Use a VM size of Standard_m416s_v2

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: "SUSE:SLES-SAP-BYOS:gen2-12-sp4:2019.07.17
 - WALinuxAgent version 

waagent --version
WALinuxAgent-2.2.36 running on suse 12
Python: 2.7.13
Goal state agent: 2.2.36

**Additional context**
Just enable the resource drive configuration.

**Comment by trstringer** [comment]
Is this a gen2 VM? If so, this was fixed in https://github.com/Azure/WALinuxAgent/pull/1654.

**Comment by trstringer** [comment]
@jofrance was this a gen2 VM? If so, can we close out this issue? Otherwise let me know if you have any follow up questions.

**Comment by jofrance** [comment]
Hi, this is a Gen2 VM, I tested the agent on Gen1 with 8+TB resource drive and works perfectly. This can be closed, Thanks a lot

Regards,

/ceschi - Francisco Franceschi
Microsoft Azure Linux Support
Escalation Engineer
Working Hours:
Working Days:
Email:
Office Phone:
0800 – 1700 US Central Time
Monday to Friday
jose.franceschi@microsoft.com<mailto:jose.franceschi@microsoft.com>
+506 411 60004
