### ISSUE TITLE
Issue with multiple extensions on RHEL 8.0

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#1719]
There are issues with multiple extension on **RHEL 8.0** *(RedHat:RHEL:8:latest)*

## ISSUE
**waagent** uses **/usr/libexec/platform-python** from the **platform-python** package, all the python extensions use the unversioned python command which is not installed on the image:

```
# waagent --version
WALinuxAgent-2.2.32.2 running on redhat 8.0
Python: 3.6.8
Goal state agent: 2.2.40
..
# /usr/bin/env python --version
/usr/bin/env: ‘python’: No such file or directory
```

Because of this the extensions fail to install:
```
[stderr]
/usr/bin/env: ‘python’: No such file or directory
..
[stderr]
No Python interpreter found on the box
```

## SOLUTION

I recommend you install **python 2.7** using the command below as I have seen some issues with some extensions and **python 3.6**:

```
sudo yum install python2 -y
sudo alternatives --set python /usr/bin/python2
```

## RELATED
- [[VMAccess] Does not work in RHEL-8](https://github.com/Azure/azure-linux-extensions/issues/800)
- [[OmsAgentForLinux] Install fails on RHEL 8.0](https://github.com/Azure/azure-linux-extensions/issues/945)
- [[VMSnapshotLinux] Install fails on RHEL 8.0 / Backups fails](https://github.com/Azure/azure-linux-extensions/issues/946)

## REQUEST
Maybe **waagent** could check for the unversioned python command and report a error in the log if it cannot find it.

**Comment by larohra** [comment]
Thanks for reporting this @johanburati. We are aware about this issue. The solution that you suggested is not a viable option from the agent end as we can't install python if the platform doesnt contain it, it should be the customer who makes this call. 

We did have a sync with the redhat folks and they agreed to add a new python3.6 path just for the agent/extensions in redhat 8.1. The extensions should work properly in that.

**Comment by yuxisun1217** [comment]
Hi @johanburati ,
Thank you for opening this issue! Yes we have added python3 as WALA package dependency in RHEL-8.1. And we have document this as a known issue in RHEL-8.0 release note and advice customer to install python2 if want to use extensions in Azure.
RHEL-8.0 release note: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.0_release_notes/rhel-8_0_0_release#virtualization_5

**Comment by johanburati** [comment]
@larohra a lot of people are having this issue, you might want to leave this open so it is easier for people to find

**Comment by larohra** [comment]
@johanburati I'm not sure about the general norm for such situations but I don't want to reopen this issue mainly because there's no action plan from the agent end. This is OS specific problem which has already been fixed in the later RHEL version (RHEL 8.1). 

And even if the issue is closed a simple google search would lead them to this link so finding it shouldn't be too much of a problem.

**Comment by johanburati** [comment]
@larohra most people who have an issue wiht *WALinuxAgent* come to this repository page and search for open issues since the default filter on *Github* is "`is:issue is:open`", if they don't find it they just open another issue, since there is already a lot of issues open for the same problem I think that make sense to leave at least this one open.

**Comment by bureado** [comment]
See https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/issues-using-vm-extensions-python-3

If it's not an image problem or an agent problem, is it an extension problem? If it's an extension WONTFIX, then extensions should graciously fail or ensure proper guardrails are applied to set user expectations accordingly.
