### ISSUE TITLE
[BUG][2.2.45] WARNING ExtHandler Failed to process legacy cgroups

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#1732]
**Describe the bug: A clear and concise description of what the bug is.**
See such log when restart waagent service in RHEL-8:
WARNING ExtHandler Failed to process legacy cgroups. Collection of resource usage data will be disabled. Error: The daemon's PID (1397) was already added to the legacy cgroup; this invalidates resource usage data.

Note: Please add some context which would help us understand the problem better
1. Enable autoupdate and waiting for 2.2.45 guest agent start
2. Check waagent.log

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL-8.0
 - WALinuxAgent version 
WALinuxAgent-2.2.32.2 running on redhat 8.0
Python: 3.6.8
Goal state agent: 2.2.45

**Additional context**
Not observed in RHEL-7

**Comment by narrieta** [comment]
@yuxisun1217 - Thanks for reporting this. It is safe to ignore this warning. It is a consequence of using 2.2.32 in combination with 2.2.45. This warning is currently for informational purposes only.
