### ISSUE TITLE
v2.0.18: RPM build for RedHat7 failed

### ISSUE THREAD

**Issue by u6006** [Azure/WALinuxAgent#174]
RPM build errors:
    Installed (but unpackaged) file(s) found:
   /etc/udev/rules.d/66-azure-storage.rules

- Version shows as (with the previous issue got fixed):
# waagent -version
WALinuxAgent-2.0.18 running on centos

**Comment by z3ntu** [comment]
Probably caused with commit 7983334 .

**Comment by szarkos** [comment]
Probably just need to add it to the .spec file.  Are you using the spec files here: https://github.com/Azure/WALinuxAgent/tree/2.0/rpm ?

**Comment by u6006** [comment]
@szarkos Yes, if the udev rule was required, it's missing in the .spec file for building the RPM. Adding it in will fix the issue.

**Comment by ahmetalpbalkan** [comment]
I believe I had exactly the same error while running `make rpm` in cloud-init as well. 
@u6006 or @szarkos could you please send a pull request? (preferably to the `2.1` branch)

**Comment by hglkrijger** [comment]
just updating this issue - @u6006, @szarkos, will one of you be able to send a PR?
