### ISSUE TITLE
[BUG] RHEL 8 "service waagent restart" does not show new context waagent.log

### ISSUE THREAD

**Issue by juhlee-microsoft** [Azure/WALinuxAgent#1747]
**Describe the bug: A clear and concise description of what the bug is.**
I assume waagent service restarting will generate the full of waagent log contexts and display in /var/log/waagent.log file. But I don't see any single line during a few times of waagent service restarting.

Note: Please add some context which would help us understand the problem better
1. %tail -f /var/log/waagent.log
2. %service waagent restart (in the second terminal)
3. Expected behavior: displaying full log contexts. Actual behavior: none change in the tail command terminal.

**Distro and WALinuxAgent details (please complete the following information):**
 - RHEL 8.0 in Azure Gallery image (kernel, 4.18.0-80.11.2.el8_0.x86_64)
 - WALinuxAgent version : originally it was 2.2.32.2 and I upgraded to 2.2.45

**Additional context**

**Log file attached**
No need to attach the file because there is no change in the waagent.log.

**Comment by narrieta** [comment]
is the service actually restarting? what is the status of the service? thanks

**Comment by juhlee-microsoft** [comment]
It was running. However, we are expecting newer version of waagent soon, so I think we can close this bug.  I saw 2.2.45 logging behavior successfully.
