### ISSUE TITLE
[BUG] Azure VM, HC44rs does not have ND but waagent looks for nd kernel module

### ISSUE THREAD

**Issue by juhlee-microsoft** [Azure/WALinuxAgent#1748]
**Describe the bug: Tried to load hv_network_direct kernel module which is not available in this VM size.**

Note: Please add some context which would help us understand the problem better
1. waagent log shows this line in the VM "2020/01/09 04:57:02.931723 ERROR Daemon RDMA: failed to load module hv_network_direct". But HC44rs does not have ND module, it's IB over SR-IOV. 
2. Serial console output
3. Deploy HC44rs size VM in westus2 region. And check the waagent log.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL 8 from Azure Gallery image
 - WALinuxAgent version 
WALinuxAgent-2.2.32.2 running on redhat 8.0
Python: 3.6.8
Goal state agent: 2.2.45

**Additional context**

**Log file attached**
If possible, please provide the full /var/log/waagent.log file to help us understand the problem better and get the context of the issue.

**Comment by juhlee-microsoft** [comment]
[waagent.log](https://github.com/Azure/WALinuxAgent/files/4042243/waagent.log)

**Comment by juhlee-microsoft** [comment]
@longlimsft said this is something Redhat can fix.

**Comment by narrieta** [comment]
@longlimsft - could you take a look at this RDMA issue? thanks

**Comment by juhlee-microsoft** [comment]
Found the RHEL 8.x has older version 2.2.32.2. After upgrading to 2.2.45, the issue resolved. Request to Redhat to approve the waagent version bump for RHEL 8 and wait for new image.
