### ISSUE TITLE
[BUG] NameError: name `distro` is not defined on Alpine 3.11

### ISSUE THREAD

**Issue by ericwj** [Azure/WALinuxAgent#1753]
I have a hard time figuring out how to setup walinuxagent on Alpine 3.11.

I am trying to set it up from sources. Maybe there is a simpler way of getting the agent on Alpine? How?

I am running
`python3 setup.py install --register-service`

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Alpine 3.11
 - WALinuxAgent version tried both `git clone` and `git checkout master` today with the same result.

**Additional context**
I don't think whether I have all prerequisites or not matters for the error I'm getting, but I fulfilled every dependency listed in the readme, except `ip-route` (but I have `iproute2`).
Also, I don't know much about python, I can't get `pip` on Alpine or I don't know how and I have no idea if it is smart enough to resolve that dependency on `distro` although it seems this repo contains an empty definition called `distro` with just comments in it. What or how that impacts what I'm doing &mdash; no idea.

**Log file attached**
I just have a stack trace, which I have to type over since although I installed Hyper-V guest tools, keyboard and mouse integration isn't proper.
future.py:43 AttributeError: platform has no attribute _supported_disks

Traceback:
setup.py:21
version.py:144 __distro__ = get_distro()
version.py:84 get_linux_distribution(0, alpine)
future.py:61 get_linux_distribution_from_distro(get_full_name)
future.py:72 distro.linux_distribution(
NameError: name `distro` is not defined

**Comment by vrdmr** [comment]
Hi @ericwj, It looks like a platform issue where `distro` module is not available.

For installing pip on alpine, I found this from [here](https://stackoverflow.com/a/44634480). If it works, it'll help you get pip installed and resolve the issue with `distro`.
```
apk update
apk add py-pip
```

We don't support platform scenarios, which is why I am closing the issue. But let me know if you still are facing issues.

**Comment by ericwj** [comment]
Yes this worked `apk add py3-setuptools` and the repo now builds. I have left this alone previously; although it might be nice to run Alpine on Azure and get the crazy disk to stop generating 6 IOPS the whole month just idling, the other problem is that waagent and the processes related to it take a whopping lot of memory on a 512MB VM. Any chance that might perhaps radically change in the future? Sure some of it isn't actually using RAM but then it has to be swapped but why...

**Comment by ericwj** [comment]
Just checking my ash log, I also did this after googling a lot and coming accross instructions to this end - not sure what exactly of it was necessary:
```
python3 -m ensurepip --default-pip
python3 -m pip install --upgrade pip setuptools wheel
pip install distro
python3 setup.py install
```

**Comment by vrdmr** [comment]
> the other problem is that waagent and the processes related to it take a whopping lot of memory on a 512MB VM.

The WALinuxAgent uses around 40-60 MB on a normal machine (with the Daemon using 15-20MB and extension-handler using the rest). Could you please let me know how much memory was the waagent using on your small box? Also, if possible, can you paste the process tree of waagent that you see and the memory usage by individual processes in that tree?

**Comment by ericwj** [comment]
That machine is Ubuntu 18.04 on a B1ls VM. My mistake is that I wanted to reboot before running top and tree and I have been busy intermittently trying to connect with ssh for a good two hours before deciding to resize the machine just to do this.

The boot diagnostics at least show a number of times where processes are killed for being oom and it is seriously just a VM running a simple ASP.NET Core website or two. Docker is installed but is not running any containers. Top will show me dotnet followed by 3 python processes at the top sorted by USED.

It might not be just waagent, one offender that also tends to get killed is omsagent. But that too is part of the infrastructure overhead.

**Comment by ericwj** [comment]
Numbers after booting with 2GB memory.

|USED|Command|
|--:|:--|
|27M|phython3|
|20M|python3|
|18M|python2|
|18M|python|
|20M|NetworkWatcherA|
|4M|NetworkWatcherA|
|51M|omsagent|
|34M|omsagent-LAD|
|12M|omiagent|
|9M|omiagent|
|4M|omiengine|
|3M|omiserver|

So that is about 80MB for whomever is using Python, 24MB for Network Watcher Agent and 113MB for OMI.

If it is 40-60MB for waagent and I can get rid of the others, that is still 10% of the available memory on a B1ls.

**Comment by vrdmr** [comment]
To remove `NetworkWatcherAgent` and `omiagent`, I would recommend removing the OMS Extension. They could have been enabled at a subscription level or when some config was turned on, in the VM. Once the OMSExtension gets removed - it should uninstall all the installed plugins.

**Comment by ericwj** [comment]
Yes thanks, I had already removed Network Watcher, with this the usage after rebooting is reduced to some 70MB python2/3 and 17MB omiagent/engine/server and about 250ish MB USED accross everything not charged directly to app-related processes just quickly glancing over `top`.

Not sure why these three omi processes remain but its a lot better. The extensions that are still installed are `AADLoginForLinux` and `LinuxDiagnostic`. But yeah right now about 25% of the memory usage is from python, presumably all `WALinuxAgent`.

**Comment by ericwj** [comment]
OMS is being installed every time I reboot. Spent a few days thinking it'd be just the small processes but I just can't be sure it isn't spawning omsagent several times again for a total of about what I put in the table above.
