### ISSUE TITLE
[Bug] cgroup default setting changed from "yes" to "n" in waagent.conf

### ISSUE THREAD

**Issue by mries** [Azure/WALinuxAgent#1766]
waagent v2.2.32 cgroup had a default setting of "y" (on).   At some point that was updated to "n" (off) in waagent.conf

I suspect this is that case across all distributions 

WALinuxAgent-2.2.40 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.45

let me know if you need any additional information.

**Comment by pgombar** [comment]
Hi @mries, the flag `CGroups.EnforceLimits` is a no-op since this feature hasn't been launched yet. So, the change in the default setting has no impact.
