### ISSUE TITLE
EnableSwapEncryption Support

### ISSUE THREAD

**Issue by StephenLittBelch** [Azure/WALinuxAgent#1775]
The _ResourceDisk.EnableSwapEncryption_ option in README.md suggests support to be generally available, however #1345 notes this is only functional for FreeBSD. Would similar support be added for other distributions over time, or could a note be added the option is FreeBSD-only?

**Comment by narrieta** [comment]
Thanks, we will update the documentation.

**Comment by narrieta** [comment]
Fixed by #1782
