### ISSUE TITLE
Hit error message in CoreOS, not handler properly when get process ID.

### ISSUE THREAD

**Issue by LiliDeng** [Azure/WALinuxAgent#1776]
**Describe the bug: A clear and concise description of what the bug is.**
1. Provision Core Stable OS on Azure
2. Check /var/log/waagent.log
3. Found below error
```
2020-02-11T14:14:12.270807Z ERROR ExtHandler Failed to get the PID of the DHCP client: invalid literal for int() with base 10: 'MainPID=841'
```

**Distro and WALinuxAgent details (please complete the following information):**
 - Core Stable OS - gallery image, kernel version 4.19.95-coreos
 - WALinuxAgent version 
```
WALinuxAgent-2.2.32.2 running on coreos 2303.4.0
Python: 2.7.6
Goal state agent: 2.2.46
```

**Log file attached**
[waagent.log](https://github.com/Azure/WALinuxAgent/files/4186241/waagent.log)

**Comment by narrieta** [comment]
Thanks for reporting this issue. We'll try to take a look at this, but since CoreOS is not an endorsed distro for now we may take a while.

**Comment by larohra** [comment]
Thanks for the issue. Looks like CoreOS has reached End-of-Life - https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros

Closing this issue
