### ISSUE TITLE
Why is the SSH Host Key reported at all?

### ISSUE THREAD

**Issue by colemickens** [Azure/WALinuxAgent#1783]
From what I can tell, the VM's ssh host public key is not retrievable via the Azure API. As such, what's the point of reporting it to the wire server?

**Comment by colemickens** [comment]
Is this marked "needs more information" for me? What other information is needed? The agent reports the SSH host key when it reports provisioning status, yet, this information doesn't seem to be exposed anywhere.

I don't want to be this guy, but is Azure tracking SSH host keys behind the scenes for some reason, maybe? It would potentially allow a third party, with Azure's help, to correlate a past-seen host key fingerprint to a specific Azure customer, for example.

**Comment by trstringer** [comment]
What code path or log message are you referring to specifically?

**Comment by colemickens** [comment]
The codepath where the SSH host key fingerprint is reported during "report_ready".

https://github.com/Azure/WALinuxAgent/blob/017e1bdd7dfb44134ec3e450328091a49b9a77ac/azurelinuxagent/pa/provision/default.py#L97

https://github.com/Azure/WALinuxAgent/blob/017e1bdd7dfb44134ec3e450328091a49b9a77ac/azurelinuxagent/pa/provision/default.py#L313

Reading the code around here makes it clear that it will even report pre-existing, pre-generated keys.

Why is the platform logging my SSH host key thumbprints and not making them available to me?

**Comment by trstringer** [comment]
We will be removing this SSH host key thumbprint shortly from the walinuxagent. It was originally there for the old portal, but was removed with the new portal. Thanks for bringing this to our attention! I'm going to keep this issue open to make sure that your question was answered, and I'll close this out when the PR is merged in with the removal.

**Comment by colemickens** [comment]
Cool! Thanks for the update @trstringer!
