### ISSUE TITLE
[BUG] RPM does not enable service on RHEL 7

### ISSUE THREAD

**Issue by jak119** [Azure/WALinuxAgent#1789]
The RPM version 2.2.38-1.el7 from the rhel-7-server-extras-rpms repo does not enable service in systemctl on RHEL 7, providing an inconsistent experience across RHEL 6 where it does and RHEL 7 where it does not.

Steps to reproduce from an OS without the agent:
1. `yum install walinuxagent -y`
2. `systemctl status waagent` and observe that it's not enabled

On RHEL 6 after the install and `chkconfig --list waagent` the agent is set to on for several run levels.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL 7
 - WALinuxAgent version: 2.2.38

**Comment by pgombar** [comment]
@jak119 can you please share the agent log? It should be under `/var/log/waagent.log`. Thanks.

**Comment by yuxisun1217** [comment]
Hi @jak119 ,
I think it is by design. Some other package - such as cloud-init - the service is also disabled after installed, and have to be enabled manually. And I think this behavior is defined in the rpm spec file.

**Comment by jak119** [comment]
> I think it is by design
@yuxisun1217 Understood that it's by design, it was just very surprising to us that enabling the service is inconsistent between RHEL 6 and RHEL 7 which is why we'd been led to think it was a bug.

> can you please share the agent log?
@pgombar I don't have a log handy but when we looked at it with Azure support we didn't see any agent issues, our concern was more with the RPM install / spec like @yuxisun1217 hinted to. Do you have access to support tickets? If so I can share the ticket number.

**Comment by yuxisun1217** [comment]
Hi @jak119 ,
Thank you for reporting this! I open a BZ in Red Hat Bugzilla(https://bugzilla.redhat.com/show_bug.cgi?id=1817283).

**Comment by jak119** [comment]
Thanks @yuxisun1217, seems like that's the more appropriate place for this given the info here.

**Comment by yuxisun1217** [comment]
Hi @jak119 ,

Here is the update from the bug:
```
The default status for services is specified in /usr/lib/systemd/system-preset/ (redhat-release-server package),
you can see it when you do 

# systemctl status waagent
● waagent.service - Azure Linux Agent
   Loaded: loaded (/usr/lib/systemd/system/waagent.service; enabled; vendor preset: disabled)

Note 'vendor preset: disabled'

on RHEL8 it is not any different:
# systemctl status waagent
● waagent.service - Azure Linux Agent
   Loaded: loaded (/usr/lib/systemd/system/waagent.service; enabled; vendor preset: disabled)

RHEL6 didn't have systemd and had a different mechanism.

I see two options here:
- We re-assign the BZ to redhat-release-server package (currently, it doesn't specify the default and we get 'disabled').
- We close it as WONTFIX

Personally, I'm leaning toward the later: WALinuxAgent is an invasive tool which is used for instance provisioning
so we don't want it enabled 'by accident' -- and this can happen if someone just installs a package.
```
Could you please share your opinion about that? Thanks!

**Comment by jak119** [comment]
@yuxisun1217 I'd argue that the agent isn't _that_ invasive if it were to be installed / enabled "by accident." It'd simply fail to communicate with the Azure Fabric and generate an error log. It's not like having the agent disabled is going to protect a user from accidentally running `waagent -deprovision`.

**Comment by yuxisun1217** [comment]
Hi @jak119 ,
I'm so sorry that I didn't see your reply for such a long time...
I agree that enable it "by accident" isn't _that_ invasive. But IMO there are still some impacts that may make customer feel not good, such as a vast amount of error logs in waagent.log, and even in /var/log/messages. The waagent is not a one-time provisioning tool. As you said, its also a daemon process that communicates with Azure Fabric every several seconds. So if the connection fails, the error log will be printed continuously, like this:
```
Apr 26 12:53:34 localhost platform-python[667]: 2020/04/26 12:53:34.144132 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] WireProtocol endpoint is None
Apr 26 12:54:28 localhost platform-python[667]: 2020/04/26 12:54:28.299428 INFO Daemon Protocol endpoint not found: MetadataProtocol, [ProtocolError] [HttpError] [HTTP Failed] GET http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview -- IOError [Errno 113] No route to host -- 6 attempts made
Apr 26 12:54:38 localhost platform-python[667]: 2020/04/26 12:54:38.571575 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] WireProtocol endpoint is None
Apr 26 12:55:19 localhost platform-python[667]: 2020/04/26 12:55:19.859796 INFO Daemon Protocol endpoint not found: MetadataProtocol, [ProtocolError] [HttpError] [HTTP Failed] GET http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview -- IOError [Errno 113] No route to host -- 6 attempts made
Apr 26 12:55:30 localhost platform-python[667]: 2020/04/26 12:55:30.138991 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] WireProtocol endpoint is None
```

**Comment by pgombar** [comment]
Tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1817283.
