### ISSUE TITLE
waagent version returns byte array for few customers

### ISSUE THREAD

**Issue by soumyapattnaik** [Azure/WALinuxAgent#1790]
In many cases it has been observed that agent version returned is a byte array. This is noticed across multiple distros

**Comment by pgombar** [comment]
@soumyapattnaik can you please clarify? Where is the agent version being returned?

**Comment by soumyapattnaik** [comment]
In our backup flow we run /usr/sbin/waagent --version to get the agent version. We do this, so that if the agent is old we can show warning on customer blade to update the waagent. while running this command we see this incorrect agent version.

**Comment by pgombar** [comment]
This was fixed in version [2.2.15](https://github.com/Azure/WALinuxAgent/blob/v2.2.15/azurelinuxagent/common/version.py#L188).
