### ISSUE TITLE
[BUG / Improvement] WALinuxAgent to auto-restart when facing WireServer Exception

### ISSUE THREAD

**Issue by axelgMS** [Azure/WALinuxAgent#1801]
**Describe the bug: A clear and concise description of what the bug is.**

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs.
2. Serial console output
3. Steps to reproduce the behavior.

When there's a WireServer issue on the host, this will prevent WALinuxAgent to get its GoalState or report status correctly:

*2020/01/19 09:13:16.774102 ERROR ExtHandler [ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] POST http://168.63.129.16/machine?comp=telemetrydata -- IOError timed out -- 6 attempts made
2020/01/19 09:14:57.831376 WARNING ExtHandler HealthService: could not report observations: [HttpError] [HTTP Failed] POST http://168.63.129.16:80/HealthService -- IOError timed out -- 6 attempts made
2020/01/19 09:15:21.783005 ERROR ExtHandler ProtocolError processing goal state, giving up [[ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] GET http://168.63.129.16/machine/?comp=goalstate -- IOError timed out -- 6 attempts made]*

When the cause was a WireServer restarting on the Host, the Linux Agent doesn't recover from that situation.

Suggestion = Could WALinuxAgent trigger an auto-restart if it has faced X “Wireserver Exception" in the last Y minutes/hours ?

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: [e.g. Ubuntu 16.04]
 - WALinuxAgent version [e.g. 2.2.40, you can copy the output of `waagent --version`, more info [here](https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output) ]

2020/01/19 09:09:38.333119 INFO Daemon Azure Linux Agent Version:2.2.32.2
2020/01/19 09:09:38.340148 INFO Daemon OS: ubuntu 16.04
2020/01/19 09:09:38.343088 INFO Daemon Python: 3.5.2

**Additional context**

IcM 175148183

**Log file attached**
If possible, please provide the full /var/log/waagent.log file to help us understand the problem better and get the context of the issue.

**Comment by narrieta** [comment]
discussed offline; we'll try to capture more logs if this incident reoccurs.

**Comment by axelgMS** [comment]
Got similar issue again - see CRI 194758301

**Comment by axelgMS** [comment]
similar issue = 224267350
