### ISSUE TITLE
WALinuxAgent to support Customer DNS infrastructure in Azure

### ISSUE THREAD

**Issue by shashwatchandra** [Azure/WALinuxAgent#1808]
**Exit Criteria/LinkedIn Goal State:**
The WALinuxAgent supports a third party domain name when managing the VM hostname

**Customer Scenario:**
Customer is using its own DNS infrastructure, therefore it own domain name in Azure as Azure DNS (Private) still requires some important DNS features. The hostname of the Linux VM which is a FQDN, therefore has the domain name used by Customer DNS. The WALinuxAgent, which maintains synchronization with Azure, overwrites this domain name when it encounters it in the hostname, creating ripple effects in issues. 

**Customer Impact with Business Justification:**
Customer needs to constantly monitors that the hostname does not get changed, this may lead to serious issues. The mandated update schedule of software may massively overwrite the hostname. 

**Workaround Details (if any):**
Disable the code on the WALLinuxAgent that controls the hostname, but it may re-appear at the next software update.

**Comment by pgombar** [comment]
Hi @shashwatchandra, I believe what you are looking for can be toggled in the /etc/waagent.conf file. More info [here](https://github.com/Azure/WALinuxAgent#provisioningmonitorhostname).
Please re-open if this doesn't address your concern.
