### ISSUE TITLE
[BUG] Console Logging Enabled By Default

### ISSUE THREAD

**Issue by pmjdebruijn** [Azure/WALinuxAgent#1817]
For almost mainline distro's, using the default shipped config waagent logs directly to /dev/console, which is strange that this happens at all, let alone by default.

No user-land process should ever output directly to /dev/console, aside from maybe syslog??

Historically (using SysV init back in the day) some daemons produces output to stdout (aside from a logfile), which ended up on the console given that SysV init script usually didn't do any output redirection. And back then we had fully serialized init, so messages didn't get mixed up too easily. With modern parallelized init this creates a bit of a mess.

These days, the proper way to handle logging in almost all larger systemd-enabled distro's is to have a daemon output to stdout, where it's output ends up in journald. (This does currently seems to happen as well, so that's fine).

However, then waagent also logs to /var/log/waagent.log, which is redundant, so that should be disabled by default on systemd-enabled distros as well.

**Comment by pmjdebruijn** [comment]
This relates to:

https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/common/conf.py#L186

And (for example):

https://github.com/Azure/WALinuxAgent/blob/develop/config/debian/waagent.conf#L66

**Comment by narrieta** [comment]
Fixed by #2043 

Output to console stops after provisioning is completes.
