### ISSUE TITLE
relation between waagent and walinuxagent packages Ubuntu

### ISSUE THREAD

**Issue by wawrzek** [Azure/WALinuxAgent#184]
What's the relations between waagent and walinuxagent packages in Ubuntu?
The former seems to be auto install, but later looks like proper Linux daemon.

**Comment by szarkos** [comment]
The waagent package is just inherited from Debian and is in the "universe" repo.  The walinuxagent package is the one you should use.  It's in the main repo and officially supported by Canonical.  Does that help?

**Comment by wawrzek** [comment]
@szarkos - Thanks for explanation. Is there a  chance to add it to the walinuxagent package description and maybe add a 'Conflict' between them?

**Comment by szarkos** [comment]
That's a good point. I'm not sure what the best thing would be - just removing the waagent package or adding a conflict.  I don't see the waagent package in Xenial, so maybe they spotted this already.  I will ask.

**Comment by hglkrijger** [comment]
@szarkos, can we close this issue?

**Comment by szarkos** [comment]
Sorry for the delay.  I have a bug open with Canonical on this.  It is in their backlog, but their team has just had other issues to deal with.  The eventual solution will be to either remove the waagent package or add a conflict.

If it's OK with everyone I suppose we can close this for now and I will continue to hound the Ubuntu folks to resolve this.
