### ISSUE TITLE
Not working in devuan ascii

### ISSUE THREAD

**Issue by peter9370** [Azure/WALinuxAgent#1843]
I'm setting up a virtualbox VM, intending to upload the image to azure. I'm basing it on devuan ASCII (debian stretch, without systemd) and following the procedure in this document:

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic

Having installed WALinuxAgent (version 2.2.34) from the devuan repository and completed the recommended setup and finally, as instructed in the above document, ran "sudo waagent -deprovision -force". This gave the message:

"/bin/sh: 1: systemctl: not found"

systemctl is a component of systemd - but devuan does not use systemd.

Distro and WALinuxAgent details (please complete the following information):

Distro and Version: devuan ascii 2.1 (based on debian stretch)

WALinuxAgent version: 2.2.34

**Comment by peter9370** [comment]
I've been digging into this myself. Apparently there are two separate problems:

- python's platform.linux_distribution() function returns "debian" instead of "devuan": apparently it looks for the file /etc/lsb-release, and not finding it, hunts through /etc looking for filenames containing either "release" or "version" - if it finds one, it tries to read it. It's finding /etc/debian_version and using it. I worked round this by creating /etc/lsb-release and populating it appropriately: platform.linux_distribution()[0] now gives "devuan"

- currently WALinuxAgent doesn't have an osutils class for devuan. I've created one based on the one for debian (with non-systemd equivalents where appropriate) and modified factory.get_osutil() to load the devuan class.

Now starting to test. If it goes to plan, and if it would be useful, I'll upload some patches.

**Comment by peter9370** [comment]
I encountered another problem: in this version and environment, it appears that waagent -deprovision can't stop the waagent daemon. This appears to be a problem with /etc/init.d/walinuxagent, which I've now fixed (I'll raise another case for this). 

With this fix in place - waagent -deprovision now appear to work

Continuing to test.

**Comment by peter9370** [comment]
Progress: 

- downloaded the source package for 2.2.34 
- added patches for my changes (using quilt)
- modified debian/rules so that dh_auto_test is enabled, so running the whole test suite
- modified debian/rules to skip dh_systemd_enable and dh_systemd_start
- removed debian/waagent.walinuxagent.service
- changed debian/waagent.walinuxagent.init to fix a problem with stopping the service

After this, dpkg-buildpackage runs to successful completion: all tests run successfully, and the resulting package appears to have the correct init file for installation.

Next is probably to understand how to merge these changes onto tip. I see that there have been major changes since 2.2.34. I'll start on that now. 

Any comments would be welcome. This is the first time that I've worked on fixing a problem in a debian/devuan package, and it would be good to know that I'm going in the right direction.

**Comment by pgombar** [comment]
Hi @peter9370 thanks for reporting this. Unfortunately, devuan is not one of our endorsed distros (https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros), so we currently can't spend cycles to develop for it.

We would be more than happy to review external contributions for devuan. It would be a matter of adding a separate [config](https://github.com/Azure/WALinuxAgent/tree/develop/config), [service file](https://github.com/Azure/WALinuxAgent/tree/develop/init), and [osutil class](https://github.com/Azure/WALinuxAgent/tree/develop/azurelinuxagent/common/osutil).

**Comment by peter9370** [comment]
Hi @pgombar 

As I said, this is the first time that I've worked an issue on github, so I'm wondering how to progress this. It seems that the sequence will be: fork the walinuxagent repo; clone it onto my local machine; make the changes; stage and commit them; then submit a pull request so that you can review the changes. 

Is that correct?

Regards,
Peter

**Comment by peter9370** [comment]
I'll take it as read that the sequence in my last comment is what I do need to do, and will proceed accordingly.

**Comment by peter9370** [comment]
Just to mention that this issue is now resolved - I forked the repo and added support for devuan, and this has now been merged (#2553).
