### ISSUE TITLE
[BUG] Some parameter changes are not in waagent.conf

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#1851]
**Describe the bug: A clear and concise description of what the bug is.**
In v2.2.45 there are some parameter changes. But they are not in waagent.conf:
Provisioning.Agent is not added
Provisioning.Enabled and Provisioning.UseCloudInit are not removed

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL-7/8
 - WALinuxAgent version: v2.2.47

**Steps to Reproduce:**
1. cat /etc/waagent.conf

**Actual results:**
```
# Enable instance creation
Provisioning.Enabled=y

# Rely on cloud-init to provision
Provisioning.UseCloudInit=n
```

**Expected results:**
Something like this:
```
# Choose which provisioning agent to use (or allow waagent to figure it out by specifying "auto"). Possible options are "auto" (default), "waagent", "cloud-init", or "disabled".
Provisioning.Agent=auto
```

**Comment by pgombar** [comment]
Fixed in #1853
