### ISSUE TITLE
[BUG] Cannot set destination path for SSH public keys

### ISSUE THREAD

**Issue by qwordy** [Azure/WALinuxAgent#1852]
**Describe the bug: A clear and concise description of what the bug is.**

https://github.com/Azure/azure-cli/issues/12459

When I use Azure CLI to create a VM and specify ssh key path, I get an error.
```
Destination path for SSH public keys is currently limited to its default value /home/[username]/.ssh/authorized_keys due to a known issue in Linux provisioning agent.
```

CLI command:
```
az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --admin-username azureuser --generate-ssh-keys --ssh-dest-key-path './'
```

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs.
2. Serial console output
3. Steps to reproduce the behavior.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: UbuntuServer 18.04-LTS
 - WALinuxAgent version 
WALinuxAgent-2.2.45 running on ubuntu 18.04
Python: 3.6.9
Goal state agent: 2.2.46

**Additional context**

**Log file attached**
If possible, please provide the full /var/log/waagent.log file to help us understand the problem better and get the context of the issue.

**Comment by pgombar** [comment]
@trstringer could you take a look? Thanks!

**Comment by trstringer** [comment]
Thanks for raising this issue! This behavior is by-design. It is best to ignore this option. Thanks!

**Comment by qwordy** [comment]
> 
> 
> Thanks for raising this issue! This behavior is by-design. It is best to ignore this option. Thanks!

May I ask if it can not be set, why this agent provides this parameter?

**Comment by amatukum** [comment]
Hello All, 

I'm getting the below error when creating a Red Hat Linux VMSS. Could You please check and help.

Error:


"Destination path for SSH public keys is currently limited to its default value /home/username/.ssh/authorized_keys  due to a known issue in Linux provisioning agent.".

I'm using Red Hat Enterprise 7.9 version custom image

**Comment by trstringer** [comment]
Please see the information above. This is by-design and the option should be ignored. If you need a non-default location for public keys then at the moment the only way is to create your own custom solution.

**Comment by qwordy** [comment]
Do you have plan to support it?

**Comment by LarrySmith-1437** [comment]
If running the az cli in powershell, where will the key file be generated at?
