### ISSUE TITLE
Support adding keys to custom location

### ISSUE THREAD

**Issue by colemickens** [Azure/WALinuxAgent#186]
ref: https://twitter.com/stack72/status/729399122365698053

The API claims this is a known issue but I was unable to find an Issue related to it.

This two locations hardcode the path at which authorized_keys is updated:

* https://github.com/Azure/WALinuxAgent/blob/2ea019a3b03822ee0d7959b4280d8e72a15c7009/waagent#L1740
* https://github.com/Azure/WALinuxAgent/blob/2ea019a3b03822ee0d7959b4280d8e72a15c7009/waagent#L3134

Plus wherever in the ARM plane [this error](https://pbs.twimg.com/media/Ch9YogHWsAACm7Z.jpg:large
) is returned whenever this is patched.

**Comment by stack72** [comment]
Just a FYI, `testadmin` is the username i am giving the machine here. So it is `/home/<username>/.ssh/authorized_keys` as the required location

**Comment by ahmetalpbalkan** [comment]
Is there a use case for specifying keys for a user that's not the provisioning user?

I think the `Path` key in the API was mistakenly introduced to the user. We should probably start a discussion to see if it is possible to remove this `Path` key from Compute RP instead of implementing this feature.

Additional ssh keys for other users should be specified in cloud-config.

**Comment by ahmetalpbalkan** [comment]
@colemickens ping

**Comment by colemickens** [comment]
/shrug. I don't need the feature and I'm not sure it's reasonable to expect `waagent` to do user management outside of basic provisioning (and thus provisioning the first user). I'd expect any application-specific configuration to be happening in custom-script or custom-data(cloud init).

**Comment by colemickens** [comment]
I'll leave this for a while to let @stack72 add any further thoughts and close out otherwise.

**Comment by stack72** [comment]
you can close it out. IMO it's still a bug in the SDK / API stopping me from doing something like 

`/home/<username>/.ssh/id_rsa` 

but it's ine
