### ISSUE TITLE
Custom data on RHEL 7.7

### ISSUE THREAD

**Issue by hugo-paredes** [Azure/WALinuxAgent#1866]
This isn't exactly a bug, but more a clarification.

I've been trying to use the `custom data` attribute in a RHEL 7.7 VM. I've read in the documentation that this version of RHEL. Initially I wanted to use `cloud init` but I saw that the RHEL version I'm using isn't supported. 
Am I wrong and it should be working or it's not supported?

Thank you
Hugo

**Comment by yuxisun1217** [comment]
Hi Hugo,

Sorry maybe I didn't catch the point. What service do you want to use to invoke customer data? WALinuxAgent or cloud-init? 
I've tried to use WALinuxAgent and cloud-init to invoke custom data and both of these 2 tools should work well. 
I was using azure-cli like: 
az vm create --custom-data xxx ... 
Is that what you meant? Thanks!

**Comment by hugo-paredes** [comment]
Hi @yuxisun1217 

Sorry for the confusion, let me see if I can explain myself better.

I've to deploy a VM running RHEL 7.7 and I need to provision some extra things on it. Initially I looked at `cloud init` but according to the official [documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/using-cloud-init#rhel), it's not yet supported.

Then I saw `CustomData` and, by the look of it, RHEL 7.7 is supported. I'm creating the VM, sending a bash file and the VM is created without any errors. I look at `/var/lib/waagent/CustomData` and it has a base64 encoded string there and nothing is executed.

I've tried using `terraform` and, when it didn't work, I've tried the cli option as you mention.

The bash file I'm sending is very simple:
```bash
#!/usr/bin/env bash

echo "Hello World" > /tmp/file.txt
```

**Comment by yuxisun1217** [comment]
Hi @hugo-paredes ,

I created a VM from image RedHat:RHEL:7.7:latest and can reproduce it. I think it because the /etc/waagent.conf has such configuration: Provisioning.ExecuteCustomData=n
Maybe we should enable it in all the images. I'll report it in bugzilla and ask if Microsoft can help to make this change. 
Thank you so much for reporting this!

**Comment by yuxisun1217** [comment]
Hi @hugo-paredes ,
I've just created a VM from image RedHat:RHEL:7.8:latest. It's a RHEL-7.8 image and provisioning with cloud-init, which can invoke custom data successfully. If urgent maybe you can consider to use this image.

**Comment by yuxisun1217** [comment]
Open BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1827679

**Comment by hugo-paredes** [comment]
> Hi @hugo-paredes ,
> I've just created a VM from image RedHat:RHEL:7.8:latest. It's a RHEL-7.8 image and provisioning with cloud-init, which can invoke custom data successfully. If urgent maybe you can consider to use this image.

Hi @yuxisun1217 

I'll see if I can use that version. There's a restriction on my side where I cannot use RHEL 8 or higher, but I'm not sure if the 7.8 is okay.

Thanks.
Hugo

**Comment by pgombar** [comment]
Tracked in bugzilla ticket

**Comment by yuxisun1217** [comment]
Update:
The latest RHEL-7.7/7.8 images in Azure Marketplaces are using cloud-init as provision agent now. So this issue doesn't exist anymore. The BZ has been closed.
