### ISSUE TITLE
ProvisioningState/failed/VMExtensionProvisioningError - AADLoginForLinux

### ISSUE THREAD

**Issue by marius-udubasa** [Azure/WALinuxAgent#1876]
On enabling the AAD SSO SSH login for linux on a linux backed VMSS I get this error:

```
Message
VM has reported a failure when processing extension 'AADLoginForLinux'. 
Error message: "Failed to get status file [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001/status/1.status'" 

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot

Time
Thursday, April 30, 2020, 2:07:25 AM
```

and then it increments to 9.status directory and so on.

and the status for the VMSS resource in the Azure web portal is marked as failed.

However the ssh login works. Both with the master account and AAD login.

But I would still like to have this error fixed since it could be a time with a real `failed` status.

The are no logs in /var/log/azure/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux
And I've tried the cleanup procedure from here: https://github.com/Azure/WALinuxAgent/issues/1059#issuecomment-370741278
But it does not work in this case.

* my OS is Ubuntu 18.04:

```
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

* kernel 5.3:

```
# uname -a
Linux prod-000006 5.3.0-1020-azure #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

* waagent 2.2.45

```
# waagent --version
WALinuxAgent-2.2.45 running on ubuntu 18.04
Python: 3.6.9
Goal state agent: 2.2.46
```

* python2 and 3 versions:

```
# python --version
Python 2.7.17

# python3 --version
Python 3.6.9
```

Right now I will have to disable the AAD SSH login extension for the VMSS.

Any ideas on how to fix this?

![Screenshot from 2020-04-30 10-55-25](https://user-images.githubusercontent.com/5174707/80686360-434ae080-8ad1-11ea-9bf9-25cd92bc3eb2.png)

**Comment by pgombar** [comment]
Hi @marius-udubasa can you please open a support ticket for this? The agent can throw this error when an installation of an extension failed, and for that, the extension publisher should take a look at the issue first.

**Comment by marius-udubasa** [comment]
Hi, I had some issues in opening that ticket, but, sure, I will try to do that. Thanks.

**Comment by pgombar** [comment]
Should be tracked in an internal ticket
