### ISSUE TITLE
[BUG] waagent delete resolv.conf between reboots

### ISSUE THREAD

**Issue by alv000h** [Azure/WALinuxAgent#1878]
**Description:**

in our RHEL7.7 systems DNS resolution is missing between reboots because waagent deletes /etc/resolv.conf always... the unique available fix to circumvent this behavior is set immutable flag in /etc/resolv.conf (this is fairly very problematic, nobody else imagine setting that flag in that file...)

So, that is the same as in #1151 #1164 #1215 #754 and #855 (cloud-init, fixed by not deleting cloud-init files that waagent have not created)

**waagent should not be deleting files that it didn't create** At least not system critical files.

resolv.conf belongs to a package in the network stack and if waagent messes with it this will generate system malfunction and system package problems (if we check integrity of package it will report that the package have problems because some files were deleted).

**Distro and WALinuxAgent details**
 - Distro and Version: RHEL 7.7
 - WALinuxAgent version 2.2.38-2 (latest version available from official RedHat extras channel)

**Comment by pgombar** [comment]
Hey @trstringer, @anhvoms could you take a look at this? Thanks.

**Comment by alv000h** [comment]
Any news on this?

**Comment by trstringer** [comment]
walinuxagent should only be deleting this file on deprovisioning. Can you provide the scenario that this is happening to you with?

**Comment by alv000h** [comment]
@trstringer we have following all steps described here to upload our custom vhd:
https://docs.microsoft.com/bs-cyrl-ba/azure/virtual-machines/linux/create-upload-generic?view=azurestackps-1.7.0

This guide requires deprovision before vhd upload to azure...

We are deploying using terraform (azureRM) and every reboot /etc/resolv.conf is deleted (we are using chattr +i as a workaround)

**Comment by trstringer** [comment]
Do you mean more specifically [these steps (Prepare a Red Hat-based virtual machine for Azure)](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/redhat-create-upload-vhd?view=azurestackps-1.7.0)?

**Comment by alv000h** [comment]
Yes that is the document.

Please let me reproduce the error and post the logs...

**Comment by trstringer** [comment]
Is your machine running NetworkManager? It appears as though NetworkManager should be managing and updating `/etc/resolv.conf` as well, unless you've set `dns=none` in NetworkManager conf..?

**Comment by trstringer** [comment]
Closing this issue, but if you want to continue troubleshooting please feel free to re-open.

**Comment by amorton-netapp** [comment]
I'd like to reopen this issue, as I've encountered the same odd behavior, and had to use the same workaround to set the file immutable. This feature only works correctly if you're presuming that NetworkManager is handling that file's contents - if you need to retain a static DNS configuration, then waagent blows it away with no option to exclude that file. It's fine as a default, but there really should be a waagent.conf setting that controls this or overrides it.
