### ISSUE TITLE
Need logic improvement to find non loop back interface 

### ISSUE THREAD

**Issue by rginjupalli** [Azure/WALinuxAgent#188]
Source: https://github.com/Azure/WALinuxAgent/blob/2.0/waagent
Function related to the query: GetFirstActiveNetworkInterfaceNonLoopback()
 
The function in question creates a socket to query the list of network interfaces. The function is returning the first one that isn’t lo. If there is a preferred NIC set in its config, it will prefer that one if it’s present. 
 
But what happens, if customer defines an alias to the loop back interface? Does it create any issues because alias like lo:1 is considered as non-loop back interface by that function? In general, I haven’t seen cases where customer creates an alias to loop back interface. I wonder, why would they do that? But, if customer does indeed create an alias to loopback interfaces, how can we avoid any issues if persists?

**Comment by szarkos** [comment]
Currently it just checks for 'lo':
    if iface == b'lo':

Maybe any easy fix is to just use a regex match instead:
    if re.match("^lo", iface):

**Comment by rginjupalli** [comment]
Can we use

if re.match("^lo($|:)", iface): 

That way, it will match a NIC named either simply "lo" or one beginning with "lo" and a :

**Comment by szarkos** [comment]
Yeah, either option would work.  This needs to be fixed here:
https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/distro/default/osutil.py#L423

Ahmet, I think we have a CRI on this issue.  Can this make it for 2.1.5?

**Comment by ahmetalpbalkan** [comment]
@szarkos sure, it would be great if someone can just send a PR.

**Comment by brendandixon** [comment]
@rginjupalli Makes sense and a straightforward change. But why check for "a:" as well? Is that check too broad? I'd hate for the code to go from being too restrictive to being overly accepting.

**Comment by rginjupalli** [comment]
Potentially, I expect to treat NIC with a name beginning with lo and lo: as loopback interface. If we are sure, that no NIC with name lo:* will exist, then first solution works great

**Comment by brendandixon** [comment]
@ahmetalpbalkan We need to take this for 2.1.5. Let's use the regex @rginjupalli provided.

**Comment by jasonzio** [comment]
/sys/class/net contains symlinks to a directory of info for each defined NIC. That directory contains a file "flags" which returns the standard interface flags for the device (see <net/if.h>). IFF_LOOPBACK is defined as 0x8. On my system:
```
$ for name in /sys/class/net/*/flags; do
> echo $name: $(cat $name)
> done
/sys/class/net/eth0/flags: 0x1003
/sys/class/net/lo/flags: 0x9
```

Don't guess based on name. Look at the actual flags. No privileges are needed to read this info.

**Comment by brendandixon** [comment]
@jasonzio Thanks. Much better.

**Comment by ahmetalpbalkan** [comment]
Agreed. Reading /sys/ would be better. It appears like the Python method actually returns an IPv4 addr from these native calls, however `/sys/class/net/eth0/address` is IPv6.

```
$ cat eth0/address
00:0d:3a:11:43:13
$ cat eth0/addr_len
6
```

I'm not sure there will be consequences of returning the IPv6 address. Any ideas how can I get the IPv4 from sysfs?

**Comment by ahmetalpbalkan** [comment]
It looks like IPv4 is used in DHCP, so it is better to stick with that. What we can do is, (a) we can fully replace the method with sysfs if we figure out where to get ipv4 from. Or (b) I can just swap out the loopback check with `flags` file on sysfs and keep the rest of the method. What is more preferred?

Also, this method is called `get_first_if`, I'm assuming the OS provides the interfaces in some ordered fashion. By looking only at sysfs, we might end up returning a different value. That's why (b) might be better.

**Comment by jasonzio** [comment]
Extracting an IPv4 address directly from /sys is surprisingly difficult; Linux IPv6 support, being newer, made it a much cleaner thing.

My recommendation is to start by just replacing the loopback check with the correct code. (Given an interface name, convert the contents of /sys/class/net/<interfacename>/flags to an int; return (flags& 0x8).)

**Comment by jasonzio** [comment]
/sys/class/net/eth0/address is the MAC address of the NIC, not the IPv6 address. (You can get IPv6 address information from /proc/net/if_inet6). There is no /proc or /sys way to obtain the IPv4 address(es) bound to a NIC.

Looks to me like getifaddrs(3) is the best approach for all of this. Within the returned set of data structures, ifa_flags is the same flag word found in /sys/class/net/_interfacename_/flags, and ifa_iaddr contains the IP address (see the man page for excruciating details). I have no idea if this is accessible from Python or not.

(Or there's ioctl SIOCGIFCONF...)

**Comment by szarkos** [comment]
Here are docs FWIW: https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net and 
https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git/tree/include/uapi/linux/if.h

It might be a good idea to look at the minimum kernel version for some of these if you plan to use them.  Things like "flags" and "address" are probably fine, but there are others that maybe are too new.

Regarding option a) above, we looked into other methods for this routine some time ago but were worried about it not working with some of the more exotic network appliances (i.e. Cisco ASAv).  Some of them don't even mount /sys.  But many of those teams have forked one of the older agents by now anyway, so it may not be such an issue anymore.

**Comment by ahmetalpbalkan** [comment]
@szarkos the kernel version and sysfs mount is a good argument.

I say, let's go back to suggested regex for now. Apparently even the `=="lo"` check has worked well so far. Let's just modify that to include the `lo:` as well instead of introducing some logic to parse sysfs or procfs.

**Comment by hglkrijger** [comment]
fixes have been merged, closing the issue.
