### ISSUE TITLE
[FeatureRequest] Support secondary IP addresses

### ISSUE THREAD

**Issue by Klaas-** [Azure/WALinuxAgent#1885]
**Describe the bug: A clear and concise description of what the bug is.**
Azure has a feature to assign secondary IP addresses to a single interface, static and dynamic.

Currently only the primary IP address gets configured via dhcp. dhcp does not support multiple addresses for a single interface. The currently suggested way of setting the additional IPs within the OS: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-multiple-ip-addresses-portal -- this is manual work or needs to be scripted within deployments.
But this only makes sense for static addresses.

I would have some ideas how to automate this myself using instance metadata, but I would much rather see this integrated into WALinuxAgent and support an out of the box IP configuration. You already use WALinuxAgent to do network configuration (routes/firewall), why not also configure secondary addresses?

Scenario only tested on current RHEL images.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Image: Red Hat Enterprise Linux release 8.1 (Ootpa) (updated to 8.2)
 - WALinuxAgent version WALinuxAgent-2.2.38-1.el8.noarch
  waagent --version
  WALinuxAgent-2.2.38 running on redhat 8.2
  Python: 3.6.8
  Goal state agent: 2.2.46

**Additional context**
This was discussed a couple of years ago in #657 -- microsoft support suggested to open a new issue

**Comment by larohra** [comment]
Thank you for this feature request @Klaas. 

Currently we have no plans for adding support for this and since not a lot of customers are asking for it, I doubt its going to be prioritized anytime soon.

That being said, feel free to add the logic for it and send out a PR here, we will gladly take a look at it and can work with you from there.

Thanks!
