### ISSUE TITLE
[Feature request] Ability to control which extensions are able to be installed

### ISSUE THREAD

**Issue by NillsF** [Azure/WALinuxAgent#1886]
**Feature request**
Right now, the WAAGENT has the ability to allow or deny extensions from being installed. There are scenarios for image publishers that want to allow a subset of extensions to be installed (e.g. Azure Backup / Log Analytics agent) but not others (e.g. Custom Script extension / DSC ).

Right now, this cannot be enforced in the Azure Agent. Since the image publishers don't control the target subscriptions, they cannot rely on Azure Policy to enforce which extensions get installed on virtual machines deployed from their images.

**Comment by ZhidongPeng** [comment]
@NillsF, Thanks for your feedback, I will follow up and get back.

**Comment by ZhidongPeng** [comment]
@NillsF , please help check this [Use Azure Policy to restrict VM extension installation (Linux) - Azure Virtual Machines | Microsoft Docs](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/extensions-rmpolicy-howto-cli), does it fill your needs?

**Comment by narrieta** [comment]
Please re-open if the link provided by @ZhidongPeng does not meet the requirements
