### ISSUE TITLE
Agentless VMs

### ISSUE THREAD

**Issue by colemickens** [Azure/WALinuxAgent#1888]
On my images, the agent does nothing except report ssh host key and report the provisioning signal. As of yet, I can't get an answer to what [the agent or platform even actually does with the ssh host key](https://github.com/Azure/WALinuxAgent/issues/1783).

From this page (https://github.com/Azure/WALinuxAgent/wiki/VMs-without-WALinuxAgent): 
>Upcoming versions of cloud-init will support the Azure provisioning process without the need for WALinuxAgent at all. In these cases the agent does not need to be part of the image. As this becomes available we will provide more documentation on the specifics.

This was written quite some time ago. Is this possible now?

**Comment by pgombar** [comment]
@trstringer or @anhvoms could you comment on the cloud-init question? Thanks.

**Comment by trstringer** [comment]
What distro/version are you running, @colemickens?

**Comment by colemickens** [comment]
@trstringer It shouldn't matter, but it happens to be NixOS. I *do not want the agent in my VM*.

**Comment by trstringer** [comment]
@colemickens take a look at this documentation! https://docs.microsoft.com/en-us/azure/virtual-machines/linux/no-agent

Likewise, here is some boilerplate for a custom provisioning agent as well: https://github.com/Azure/linux-provisioning.

I'm going to close this issue for now, as hopefully this answers your questions but feel free to ping me or reopen if there are further items to discuss.

Thanks again for bringing this to our attention!
