### ISSUE TITLE
Azure Linux VM - Barracuda CloudGen Firewall - Agent not responding & unable to upgrade agent

### ISSUE THREAD

**Issue by AnonymousUser01** [Azure/WALinuxAgent#1912]
Hi Everyone,

We have an Azure VM - Barracuda CloudGen Firewall release GWAY-8.0.3-0137 for which existing backup has stopped due to agent not responsding. We checked on portal & observed that VM agent state shows not ready & none of the extenstions are visible. So, we checked the agent version & status within the Barracuda Firewall & following's the output (we did restart the agent - sudo service waagent restart) WALinuxAgent-2.2.40 running on centos 8.0:3 Python: 2.7.5 Goal State Agent: 2.2.40 - sudo service waagent status - active (running) Loaded: Loaded (/etc/rc.d/init.d/waagent; bad;vendor preset: disabled) - is the bad causing the issue or the vendor preset being disabled?

The service restart didn't help. So, as a next step we are trying to upgrade the agent from 2.2.40 to higher version but it says there's no enabled repos & even the repolist is 0

sudo yum check-update WALinuxAgent Following's the output, There are no enabled repos. Run "yum repolist all" to see the repos you have To enable Red Hat Subscription Management repositories: subscription-manager repos --enable <repo> To enable custom repositories: yum-config-manager --enable <repo> output of "yum repolist all" is 0

So, what else needs to be checked & done in order to resolve 1. the agent not responding status 2. perform agent upgrade (from july onwards the minimum linux agent version required is 2.2.41)

Regards,
AnonymousUser01

**Comment by AnonymousUser01** [comment]
following's the output of VAR log messages - is there an issue with agent communication? what needs to be checked based on below logs?

tail -50 /var/log/waagent.log

2020/06/22 12:27:20.929398 INFO ExtHandler looking for leases in path [/var/lib/NetworkManager/dhclient-*.lease]
2020/06/22 12:27:20.939521 INFO ExtHandler cached endpoint not found
2020/06/22 12:27:20.950191 INFO ExtHandler Cache exists [False]
2020/06/22 12:27:20.960682 INFO ExtHandler Send dhcp request
2020/06/22 12:27:20.997148 INFO ExtHandler Choosing non-primary [vpnr0]
2020/06/22 12:27:21.027398 INFO ExtHandler Choosing non-primary [vpnr0]
2020/06/22 12:27:21.095514 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:27:21.138104 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:27:31.217391 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:28:01.313836 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:29:01.394188 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:30:01.461070 INFO ExtHandler Protocol endpoint not found: WireProtocol, [ProtocolError] [DhcpError] Failed to receive dhcp response.
2020/06/22 12:30:01.480189 INFO ExtHandler Protocol endpoint not found: MetadataProtocol, [ProtocolError] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview
2020/06/22 12:30:01.482556 INFO ExtHandler Retry detect protocols: retry=172
2020/06/22 12:30:11.494236 INFO ExtHandler WireServer endpoint is not found. Rerun dhcp handler
2020/06/22 12:30:11.519737 INFO ExtHandler Test for route to 168.63.129.16
2020/06/22 12:30:11.526129 WARNING ExtHandler No route exists to 168.63.129.16
2020/06/22 12:30:11.537960 INFO ExtHandler Checking for dhcp lease cache
2020/06/22 12:30:11.555600 INFO ExtHandler looking for leases in path [/var/lib/dhclient/dhclient-*.lease]
2020/06/22 12:30:11.555860 INFO ExtHandler cached endpoint not found
2020/06/22 12:30:11.578717 INFO ExtHandler looking for leases in path [/var/lib/NetworkManager/dhclient-*.lease]
2020/06/22 12:30:11.595429 INFO ExtHandler cached endpoint not found
2020/06/22 12:30:11.616818 INFO ExtHandler Cache exists [False]
2020/06/22 12:30:11.627385 INFO ExtHandler Send dhcp request
2020/06/22 12:30:11.657953 INFO ExtHandler Choosing non-primary [vpnr0]
2020/06/22 12:30:11.716886 INFO ExtHandler Choosing non-primary [vpnr0]
2020/06/22 12:30:11.775191 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:30:11.824500 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:30:21.858140 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:30:51.972502 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:31:52.064318 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:32:52.121533 INFO ExtHandler Protocol endpoint not found: WireProtocol, [ProtocolError] [DhcpError] Failed to receive dhcp response.
2020/06/22 12:32:52.138621 INFO ExtHandler Protocol endpoint not found: MetadataProtocol, [ProtocolError] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview
2020/06/22 12:32:52.159356 INFO ExtHandler Retry detect protocols: retry=173
2020/06/22 12:33:02.178199 INFO ExtHandler WireServer endpoint is not found. Rerun dhcp handler
2020/06/22 12:33:02.183815 INFO ExtHandler Test for route to 168.63.129.16
2020/06/22 12:33:02.237519 WARNING ExtHandler No route exists to 168.63.129.16
2020/06/22 12:33:02.265748 INFO ExtHandler Checking for dhcp lease cache
2020/06/22 12:33:02.292269 INFO ExtHandler looking for leases in path [/var/lib/dhclient/dhclient-*.lease]
2020/06/22 12:33:02.329298 INFO ExtHandler cached endpoint not found
2020/06/22 12:33:02.354869 INFO ExtHandler looking for leases in path [/var/lib/NetworkManager/dhclient-*.lease]
2020/06/22 12:33:02.393460 INFO ExtHandler cached endpoint not found
2020/06/22 12:33:02.419438 INFO ExtHandler Cache exists [False]
2020/06/22 12:33:02.442985 INFO ExtHandler Send dhcp request
2020/06/22 12:33:02.469590 INFO ExtHandler Choosing non-primary [vpnr0]
2020/06/22 12:33:02.509528 INFO ExtHandler Choosing non-primary [vpnr0]
2020/06/22 12:33:02.573698 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:33:02.641891 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:33:12.683564 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted
2020/06/22 12:33:42.710536 WARNING ExtHandler Failed to send DHCP request: [DhcpError] [Errno 1] Operation not permitted

**Comment by pgombar** [comment]
Hi @AnonymousUser01 could you please file a ticket with Microsoft support? It seems like there are several issues here and we would possibly need to engage other teams (like backup) and investigate why your environment can't communicate to upstream repos.

**Comment by pgombar** [comment]
Closing due to lack of context. Please follow up with Microsoft support.
