### ISSUE TITLE
Set Resource Disk mount flag to nodev

### ISSUE THREAD

**Issue by nbirnel** [Azure/WALinuxAgent#192]
Currently `ActivateResourceDisk` mounts the resource disk with no flags. It would be preferrable to have the nodev flag set, either by default or as configured by `/etc/waagent.conf`, since leaving this unset is a bit insecure and triggers vulnerability reports when running credentialed vulnerability scans (eg Nexpose).

I would prefer to not need to manage `/etc/fstab` to work around this.

This is similar to, but not the same as https://github.com/Azure/WALinuxAgent/issues/113

I am willing to write the code if it is likely to be merged.

**Comment by ahmetalpbalkan** [comment]
@nbirnel we are happy to accept it. It is more preferred if you can send a pull request against the `2.1` branch.

**Comment by nbirnel** [comment]
@ahmetalpbalkan Great! Do you prefer default `nodev`, or a configuration option. (My preferrence is default `nodev`, since I believe it is the correct flag, and it is certainly easiest to implement.)

**Comment by hglkrijger** [comment]
@nbirnel, I think we should provide a configuration option, since:

- no flags is the current behavior and folks may have worked around it
- it could allow us to specify which flags should be set, e.g. ResourceDisk.MountOps with 'nodev' as the default value could be changed to 'nodev,noexec,...'

What do you think?

/cc @szarkos

**Comment by nbirnel** [comment]
Hello @hglkrijger, sorry for the long delay in replying! I think that is a reasonable argument. I have my plate full at the moment; I am handing this over to our intern, @luthes. You can probably expect a PR (or some questions) within a week.

**Comment by nbirnel** [comment]
Hello @hglkrijger . Can you provide some guidelines on testing this feature? I am not seeing an obvious place to put this in the test suite - do you want manual testing?

**Comment by hglkrijger** [comment]
@nbirnel, manual testing is fine, but we should add a unit test or two as well. I would suggest a `test_resourcedisk` under `tests/daemon`. 

Unfortunately this piece of code is not well-structured for testing at the moment, but I think you have a couple options:
- split `mount_resource_disk` into some distinct functional units, like `partition_resource_disk` and `mount_resource_disk`
- leave the code as-is and patch calls to `run_get_output` and the like
- refactor just the calls to `shellutil.run("mount {0} {1}")` and unit test that new method

In the end I imagine the tests will be pretty simple, depending on how much checking we do on the specified config value.

**Comment by nbirnel** [comment]
@hglkrijger tests/daemon exists on the master branch, but not on archive/2.1. Should we merge that whole directory in to 2.1, or do you just want the test_resourcedisk.py created?

**Comment by hglkrijger** [comment]
The last batch of development was in the develop branch, probably best to use that for now. We will be switching over to master at some point, but have not yet.

**Comment by nbirnel** [comment]
I am not sure I understand. Do you want us to branch from develop instead of archive/2.1?

**Comment by hglkrijger** [comment]
Yes, archive/* is only for historical purposes; those branches are not in use any more.
