### ISSUE TITLE
requirements.txt mentions requirement of python >= 3.8, but Readme says 2.6+

### ISSUE THREAD

**Issue by rathiume** [Azure/WALinuxAgent#1939]
requirements.txt mentions requirement of python >= 3.8, but Readme says 2.6+

Can you please explain why this discrepancy?

**Comment by pgombar** [comment]
Hi @rathiume, the requirements.txt file mentions python 3.8 in the context of a package dependency.

> distro; python_version >= '3.8'

This means that package `distro` will be installed if python version is >= 3.8. The agent supports python 2.6+.
