### ISSUE TITLE
[ISSUE] "waagent -deprovision+user -force" not working as expected

### ISSUE THREAD

**Issue by andybacka** [Azure/WALinuxAgent#1945]
When using the `waagent -deprovision+user` command, the user re-appears when imaged

Building a CentOS v7.x VM to be used as a source image for future builds.  One of the last steps before shutting down the VM is to run the above command.  It works as expected for that instance, and the user is removed, but when I build from the new image, my VM contains the user (as defined in `/var/lib/waagent/ovf-env.xml`).  How do I prevent the user from being re-created on every new instance that is based on my image?  From what I've read, the cloud-init daemon is responsible for re-populating the file, which in turn is used by the agent to reprovision the new instance.  But I haven't found how/where to fix it so the user isn't recreated.

Here's the output of the deprovision command.  How do I ensure 'azadmin' is not created on every instance built from this image?  I confirmed that the user has been removed, as had the `/var/lib/waagent/ovf-env.xml` file.
```
[admin@centos-v7-node ~]$ sudo waagent -deprovision+user
WARNING! The waagent service will be stopped.
WARNING! All SSH host key pairs will be deleted.
WARNING! Cached DHCP leases will be deleted.
WARNING! root password will be disabled. You will not be able to login as root.
WARNING! /etc/resolv.conf will be deleted.
WARNING! azadmin account and entire home directory will be deleted.
Do you want to proceed (y/n)y
2020/07/15 15:15:50.111345 INFO Examine /proc/net/route for primary interface
2020/07/15 15:15:50.116477 INFO Primary interface is [eth0]
```

**Comment by andybacka** [comment]
Damn.  Sorry - I meant to include the version information:
```
[admin@centos-v7-node ~]$ sudo waagent -version -verbose
WALinuxAgent-2.2.45 running on centos 7.8.2003
Python: 2.7.5
Goal state agent: 2.2.49.2
```
I see that I'm behind a bit from the latest, but `yum` isn't allowing me to catch up to the latest.

**Comment by pgombar** [comment]
@andybacka thanks for reporting this. As for the agent versions, you are on the latest one (2.2.49.2). The 2.2.45 version is the daemon that is preinstalled on this image. For more info, check out this doc: https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output

@trstringer could you comment on the question related to deprovisioning? Thanks!

**Comment by trstringer** [comment]
I'm unable to reproduce this.

1. Create VM based off of `openlogic:centos:7.7:latest` with user `first`.
1. Deprovision with `waagent -deprovision+user`, then generalize and create image.
1. Create VM based off of image from above step with user `second`.

With the newly created VM I see only the `second` user when I `ls /home` and grep through `/etc/passwd`.

Can you provide explicit repro steps that I could use?

**Comment by andybacka** [comment]
Not surprised.  I'm sure it's something I did, but I can't trace what is causing it.

I created a VM same as you did, ran a bunch of Ansible against it to harden it as per our policies, deprovision it with the same command, shut it down and created the image.  Builds off of that image occasionally work, and that user does not exist.  The last build I did yesterday morning, however, had it.  One of my Ansible steps is to uninstall/install the OMI agents, which seems like the only quasi-related action to this.

I don't think there's anything for you to fix, unless it becomes completely reproducable.  But I would like to know where I can troubleshoot this further, beyond the file I mentioned when I opened the ticket.  Where else is this user account defined?

Thanks.

**Comment by trstringer** [comment]
The log file is the best place to troubleshoot with logging, but if you do have a repro you can always do some local patching to dump additional data to help diagnose or prove theories. Or likewise, if you have a repro feel free to reopen this issue and we can troubleshoot further together.

Thanks!
