### ISSUE TITLE
Documentation Needed: /sys/firmware/acpi/tables/{OEM0,OEMB}

### ISSUE THREAD

**Issue by colemickens** [Azure/WALinuxAgent#1946]
**Describe the bug: A clear and concise description of what the bug is.**

See: https://github.com/Azure/WALinuxAgent/issues/1500

Why was it removed? Are these values documented somewhere for Azure Linux VMs?

```
$ ls /sys/firmware/acpi/tables/OEM*
OEM0 OEMB
```

I want to understand what the agent *should* be doing.

**Comment by colemickens** [comment]
It really seems like it ought to still be in use. https://download.microsoft.com/download/1/c/9/1c9813b8-089c-4fef-b2ad-ad80e79403ba/Whitepaper%20-%20The%20Windows%2010%20random%20number%20generation%20infrastructure.pdf

**Comment by narrieta** [comment]
The hypervisor has an entropy table that it uses to populate OEM0. I do not know the details/properties of this table. As mentioned in #1500, we are not planning on re-adding the functionality that was using this file.
