### ISSUE TITLE
[BUG] Configuration option misnamed

### ISSUE THREAD

**Issue by rjschwei** [Azure/WALinuxAgent#1952]
The agent has code that monitors the hostname of the VM. This code path is controlled with the configuration option:

`Provisioning.MonitorHostName`

in waagent .conf. However, unlike indicated in the configuration, i.e. the code path only applies to provisioning the code path is active all the time, i.e. after provisioning.

This can be seen when running

`hostnamectl set-hostname foo.bar.us`

and watching the log (var/log/waagent.log). After the `hostnamectl` command is issued the agent runs through the code path that pushed the new hostname to the DHCP server. This code path happens to bring down the interface and restarts it which can cause other issues, but that's a different discussion. For this issue a decision needs to be made whether the configuration option gets renamed or the code path moves to the provisioning path only.

**Comment by narrieta** [comment]
I agree that the option is misnamed, but we would need to keep the current name anyways for backwards compatibility. We will leave the code as is, but thanks for pointing this out.
