### ISSUE TITLE
Hostname is NULL after reboot FreeBSD vm in Azure

### ISSUE THREAD

**Issue by KylieLiang** [Azure/WALinuxAgent#196]
The hostname of a vm of  FreeBSD 10.3 with waagent 2.1.4  is NULL after reboot it  in Azure.
Could you please have a look at it?  The agent should configure the right hostname when booting, right?

 (The hostname is NULL after reboot/restart it.)

**Comment by KylieLiang** [comment]
Dong did investigation. The host name is not persisted after rebooting. We’ll write hostname to ‘/etc/hostname’, which Linux will read and set hostname. But FreeBSD will read ‘/etc/rc.conf’ only, the result is a FreeBSD VM would lost its Azure VM hostname after rebooting.

Dong did a private fix for FreeBSD 10.3 which will be published in Azure marketplace. https://github.com/karataliu/WALinuxAgent/tree/freebsd21 
The test for above fix is in the progress. Once it is done, could it be included in Agent 2.1.5? Thank you.

**Comment by KylieLiang** [comment]
We tested above fix with FreeBSD 10.3 and confirmed this bug is fixed. 
Could you please ensure this fix is captured by 2.1.5? Thank you.

**Comment by hglkrijger** [comment]
closing, as the fix is merged.
