### ISSUE TITLE
Agent 2.1.4 does not support FreeBSD 10.1 and FreeBSD 10

### ISSUE THREAD

**Issue by KylieLiang** [Azure/WALinuxAgent#197]
In agent v2.1, we’re using device id ‘2:1:0’ (bus:target:lun) to locate the resource disk, instead of using hardcoded value ‘/dev/da1’ in agent v2.0.

On freebsd v10.1, however, it would introduce ‘/dev/ada*’ which took up the 0th scbus, thus the device id for resource disk becomes ‘3:1:0’.

(‘/dev/daX’ and ‘/dev/adaX’ are referring to identical device through different drivers, which is similar to the ‘sda’ and ‘hda’ in linux, but the latter one usually won’t co-exist to represent the same thing).

On 10.1
# camcontrol devlist -v

scbus0 on ata0 bus 0:
<Virtual HD 1.1.0>                 at scbus0 target 0 lun 0 (ada0,pass0)
<Virtual HD 1.1.0>                 at scbus0 target 1 lun 0 (ada1,pass1)
<>                                 at scbus0 target -1 lun ffffffff ()
scbus1 on ata1 bus 0:
<Msft Virtual CD/ROM 1.0>          at scbus1 target 0 lun 0 (cd0,pass2)
<>                                 at scbus1 target -1 lun ffffffff ()
scbus2 on blkvsc0 bus 0:
<Msft Virtual Disk 1.0>            at scbus2 target 0 lun 0 (da0,pass3)
<>                                 at scbus2 target -1 lun ffffffff ()
scbus3 on blkvsc1 bus 0:
<Msft Virtual Disk 1.0>            at scbus3 target 1 lun 0 (da1,pass4)
<>                                 at scbus3 target -1 lun ffffffff ()
scbus4 on storvsc2 bus 0:
<>                                 at scbus4 target -1 lun ffffffff ()
scbus5 on storvsc3 bus 0:
<>                                 at scbus5 target -1 lun ffffffff ()
scbus-1 on xpt0 bus 0:
<>                                 at scbus-1 target -1 lun ffffffff (xpt0)

On 10.2+
# camcontrol devlist -v

scbus0 on ata1 bus 0:
<Msft Virtual CD/ROM 1.0>          at scbus0 target 0 lun 0 (pass0,cd0)
<>                                 at scbus0 target -1 lun ffffffff ()
scbus1 on blkvsc0 bus 0:
<Msft Virtual Disk 1.0>            at scbus1 target 0 lun 0 (da0,pass1)
<>                                 at scbus1 target -1 lun ffffffff ()
scbus2 on blkvsc1 bus 0:
<Msft Virtual Disk 1.0>            at scbus2 target 1 lun 0 (da1,pass2)
<>                                 at scbus2 target -1 lun ffffffff ()
scbus3 on storvsc2 bus 0:
<>                                 at scbus3 target -1 lun ffffffff ()
scbus4 on storvsc3 bus 0:
<>                                 at scbus4 target -1 lun ffffffff ()
scbus-1 on xpt0 bus 0:
<>                                 at scbus-1 target -1 lun ffffffff (xpt0)

**Comment by KylieLiang** [comment]
Attach initial thoughts here. 
It seems no easy way to disable ada device as discussed in following references:
http://lists.freebsd.org/pipermail/freebsd-questions/2015-August/267440.html 
https://groups.google.com/forum/#!topic/fa.freebsd.stable/CJ-fqRerJ6g 

We thought adding fallback logic there dedicated for v10.1 in agent v2.1, but that approach wouldn’t be quite straightforward.

**Comment by brendandixon** [comment]
@KylieLiang Please test with the latest version (2.2.10) as we made a few adjustments. If problems remain and you believe a solution exists, please re-open with sufficient detail for us to make the appropriate changes. Thank you.

**Comment by KylieLiang** [comment]
Confirm. This bug is fixed against FreeBSD 10.3 and 11.0 with Agent 2.2.10. Thank you.
