### ISSUE TITLE
[BUG] Installation instruction for a particular linux distrbution are not clear

### ISSUE THREAD

**Issue by arybka777** [Azure/WALinuxAgent#1972]
**Describe the bug: A clear and concise description of what the bug is.**

Note: Please add some context which would help us understand the problem better

Reading:
https://github.com/Azure/WALinuxAgent/blob/develop/README.md#installation

"Installation via your distribution's package repository is preferred. You can also customize your own RPM or DEB packages using the configuration samples provided (see deb and rpm sections below)."

This is not clear and neither provides instructions or link to a particular distribution.  What would be the steps for Ubuntu, RHEL etc.?

Thanks

**Comment by narrieta** [comment]
@arybka777 - The commands for installing it differ with the distro, and different distros use different names for their packages, sometimes with small changes across different versions. Any list would be incomplete/out of date in a short time. It is better to look for in the corresponding package repository.
