### ISSUE TITLE
Warning message - [WARNING ExtHandler ExtHandler cgroups v2 mounted at /sys/fs/cgroup/unified.  Controllers: []] show up in ubuntu 18.04

### ISSUE THREAD

**Issue by LiliDeng** [Azure/WALinuxAgent#1982]
**Warning message - [WARNING ExtHandler ExtHandler cgroups v2 mounted at /sys/fs/cgroup/unified.  Controllers: []] show up in ubuntu 18.04**

1. Create 18.04 from gallery image.
2. See warning message from https://github.com/Azure/WALinuxAgent/blob/90aeeb24683d9cd0dcca20c2ac72cdae2547e8ba/azurelinuxagent/common/cgroupconfigurator.py#L115
```
2020-08-17T04:05:52.549532Z INFO ExtHandler ExtHandler The CPU cgroup controller is mounted at /sys/fs/cgroup/cpu,cpuacct
2020-08-17T04:05:52.563090Z INFO ExtHandler ExtHandler The memory cgroup controller is mounted at /sys/fs/cgroup/memory
2020-08-17T04:05:52.584536Z WARNING ExtHandler ExtHandler cgroups v2 mounted at /sys/fs/cgroup/unified.  Controllers: []
```
3. Two questions here, thanks!
> CGroups.EnforceLimits is set not n, should this message show up?
```
# Enforce control groups limits on the agent and extensions
CGroups.EnforceLimits=n

# CGroups which are excluded from limits, comma separated
CGroups.Excluded=customscript,runcommand
```
> What is the purpose this? I didn't see any other place depended on it. 

**Distro and WALinuxAgent details**
 - Ubuntu 18.04, kernel 5.3.0-1034-azure, wala 
 - waagent -version
    WALinuxAgent-2.2.45 running on ubuntu 18.04
    Python: 3.6.9
    Goal state agent: 2.2.49.2

@narrieta

**Comment by narrieta** [comment]
@LiliDeng Currently enforcement of resource limits is experimental and that flag has no effect. You can also ignore the warning, it does not affect the functionality of the agent.

**Comment by LiliDeng** [comment]
thank you @narrieta
