### ISSUE TITLE
[BUG] Exception 'latin-1' codec can't encode characters in position when with Chinese characters in RG 

### ISSUE THREAD

**Issue by FranckChu** [Azure/WALinuxAgent#2003]
**Describe the bug: 
Once after we deployed VM with Ubuntu 16.04 image in the Resource Group with Chinese characters, then it  will report below error in waagent log.  And turns out it's related to Python 3 as we don't see the issue in the CentOS VM with Python 2.7. 
2020/07/28 05:41:49.433705 ERROR ExtHandler [ProtocolError] [Wireserver Exception] 'latin-1' codec can't encode characters in position 1771-1774: Body ('\u9ed1\u6697\u82f1\u96c4') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8. 

$ sudo waagent --version
WALinuxAgent-2.2.45 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.49.2

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs. 
/var/log/waagent.log
2. Serial console output
3. Steps to reproduce the behavior.
I. Create new Resource Group with names in Chinese characters 
II. Deploy the VM with Ubuntu 16.04 in the RG
III. From waagent log we see above error 

**Distro and WALinuxAgent details
 - Distro and Version: Ubuntu 16.04
 - WALinuxAgent version 2.2.45

From waagent log:
2020/07/28 05:41:49.433705 ERROR ExtHandler [ProtocolError] [Wireserver Exception] 'latin-1' codec can't encode characters in position 1771-1774: Body ('\u9ed1\u6697\u82f1\u96c4') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by larohra** [comment]
Fixed in #1937
