### ISSUE TITLE
[BUG] Waagent log fills up with an ExtHandler Event

### ISSUE THREAD

**Issue by elabbarw** [Azure/WALinuxAgent#2024]
We manage a number of Azure Stack Hub based VMs (2002 & 2005) and they all seem to have their waagent log files filled with the following error:

 python3[1291]: 2020/09/25 07:23:46.795804 ERROR ExtHandler Event: name=WALinuxAgent, op=HealthObservation, message={"ObservationName": "InstanceMetadataHeartbeat", "IsHealthy": false, "Description": "", "Value": "IMDS error in /metadata/instance: [HttpError] [HTTP Retry] GET http://169.254.169.254/metadata/instance?api-version=2018-02-01 -"}, duration=0

**Distro and WALinuxAgent details (please complete the following information):**
WALinuxAgent-2.2.45 running on ubuntu 18.04
Python: 3.6.9
Goal state agent: 2.2.45

Apart from the usual messages when installing and uninstalling extensions, the log file fills up with the same exact error until it becomes quite large and this is occurring with all of VMs that use waagent

**Comment by narrieta** [comment]
@byue looking into this

**Comment by elabbarw** [comment]
I am looking into this with the MS PG as well. Thanks!

**Comment by elabbarw** [comment]
Deployed a new VM on 2005 using: 
WALinuxAgent-2.2.40 running on ubuntu 18.04
Python: 3.6.8
Goal state agent: 2.2.48.1

and its exhibiting the same behavior

**Comment by byue** [comment]
@elabbarw as of 2008 IMDS is not supported on AzureStack:
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vm-considerations?view=azs-2008
These instance metadata error messages are expected as this endpoint does not exist yet. Logs in this case will fill up but are capped and pruned.
@narrieta is there some verbosity flag they can set to disable this logging?

**Comment by narrieta** [comment]
@byue Nope

**Comment by elabbarw** [comment]
Thanks for explaining! I will close the issue in this case.
