### ISSUE TITLE
Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml 

### ISSUE THREAD

**Issue by svrangarao** [Azure/WALinuxAgent#2025]
Hi Azure team, 

I have created an Azure VM instance using **Ubuntu 18.04 LTS Server** and later exported the VM disk (vhd) file.

Later upload the VHD file in the data store blob and create an Azure IMAGE. 

Launched VM instance from the Azure image. I have done this many times but recently I am getting this error and VM launch using the image is failing and the process is terminating after 30 minutes. 

Here the boot diagnostics information: 

_**2020/09/22 19:10:08.738515 INFO Daemon Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1705 retries remaining, sleeping 1s]
2020/09/22 19:10:08.743384 WARNING Daemon cloud-init does not appear to be running**_

Tried finding the solution for the above issue but I did not find any solution.

**Comment by trstringer** [comment]
What was the base image URN that you used to provision the original VM? What other operations did you do on the VM prior to creating the secondary image?

**Comment by svrangarao** [comment]
I am using Ubuntu Server 18.04 LTS Gen 1 image from Market place

"imageReference": {
                        "publisher": "Canonical",
                        "offer": "UbuntuServer",
                        "sku": "18.04-LTS",
                        "version": "latest"
                    }

After deploying the VM I am updating a few modules and installing other modules as per my requirement.

curl
imvirt
libcurses-ui-perl
navicli-linux-64-x86-en-us
monit
nginx
nmap
openssh-server
postgresql-10
python-django
resolvconf   # Need to use Default one instead resolvconf
rsyslog
rsyslog-pgsql
snmp
snmpd
snmp-mibs-downloader
squid3
traceroute
unzip 
vim
libxml-simple-perl
libswitch-perl
openjdk-11-jre
bc
pypjsua
python-pycurl
ufw
uwsgi-plugin-python
python-configparser
net-tools
dnsutils
gnupg
ntp
ntpdate
python-yaml
unispherecli-linux-64-x86-en-us
telnet
ethtool
arping
vlan
libpam-cracklib
google-chrome-stable
python-selenium
clamav
sqlite3
python-urllib3
python-apt
python-djangorestframework
lshw
mtr-tiny
mlocate
psmisc
strace
time
tcpdump
python-twisted
python-psycopg2

**Is there any module that is stopping cloud-int to copy the "ova-env.xml" in /var/lib/waagent ?**

**Comment by trstringer** [comment]
How are you actually creating this VM? Can you provide explicit steps that you used? I'm unable to repro this behavior.

I tried with a similar approach, and I did get the error messages for waagent waiting for the OVF to be copied over, but I was still able to SSH into the machine.

> the image is failing and the process is terminating after 30 minutes

Can you expand on this? What do you mean exactly? How did you notice the failure, and during that 30 minutes was the Azure CLI just waiting (assuming you used the Azure CLI to create the VM)?

Finally, could you provide `/var/log/cloud-init.log` as well as `/var/log/waagent.log` so I can investigate further? Please remove any information from those logs that you don't want to share before sending.

Thanks!

**Comment by svrangarao** [comment]
[logs.zip](https://github.com/Azure/WALinuxAgent/files/5307074/logs.zip)

Hi Thomas Stringer, Thanks for your reply.

Could you please verify the log files attached to this thread?

**Comment by trstringer** [comment]
It looks like you don't have the UDF driver anymore:

```
Stderr: mount: /run/cloud-init/tmp/tmpyy80ejpt: unknown filesystem type 'udf'.
2020-09-24 13:09:09,652 - handlers.py[DEBUG]: diagnostic: diagnostic message: /dev/sr0 was not mountable
2020-09-24 13:09:09,652 - DataSourceAzure.py[WARNING]: /dev/sr0 was not mountable
2020-09-24 13:09:09,653 - handlers.py[DEBUG]: start: azure-ds/load_azure_ds_dir: load_azure_ds_dir
2020-09-24 13:09:09,653 - handlers.py[DEBUG]: finish: azure-ds/load_azure_ds_dir: FAIL: load_azure_ds_dir
2020-09-24 13:09:09,653 - handlers.py[DEBUG]: diagnostic: diagnostic message: Did not find Azure data source in /var/lib/waagent
2020-09-24 13:09:09,654 - handlers.py[DEBUG]: diagnostic: diagnostic message: No Azure metadata found
2020-09-24 13:09:09,654 - handlers.py[DEBUG]: finish: azure-ds/crawl_metadata: FAIL: crawl_metadata
```

Did you disable or remove the UDF driver from the image? It looks like it succeeded previously:

```
2020-07-27 09:16:43,404 - util.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'auto', '/dev/sr0', '/run/cloud-init/tmp/tmpc30m0gmp'] with allowed return codes [0] (shell=False, capture=True)
2020-07-27 09:16:43,534 - handlers.py[DEBUG]: start: azure-ds/load_azure_ds_dir: load_azure_ds_dir
2020-07-27 09:16:43,539 - handlers.py[DEBUG]: start: azure-ds/read_azure_ovf: read_azure_ovf
2020-07-27 09:16:43,547 - handlers.py[DEBUG]: start: azure-ds/_extract_preprovisioned_vm_setting: _extract_preprovisioned_vm_setting
2020-07-27 09:16:43,547 - handlers.py[DEBUG]: finish: azure-ds/_extract_preprovisioned_vm_setting: SUCCESS: _extract_preprovisioned_vm_setting
2020-07-27 09:16:43,547 - handlers.py[DEBUG]: finish: azure-ds/read_azure_ovf: SUCCESS: read_azure_ovf
```

The OVF file is extracted from /dev/sr0, which is a UDF filesystem. So we try to mount it as UDF, but if that filesystem doesn't exist then it fails in a similar way.

The fix (or next step) is to understand what step between initial VM provisioning from base image and custom image creation removed or disabled this UDF filesystem and then go from there.

**Comment by svrangarao** [comment]
@trstringer , Thanks for your inputs. I will check with my engineering team and get back to you.

**Comment by svrangarao** [comment]
@trstringer 

We have a file   **/etc/modprobe.d/blacklist-filesystem.conf** and in the file I commented the line    "**install udf /bin/true**"

Then I created an image using the VHD file with the above changes and deployed the gateway and the VM launched quickly without any issue.
WAAGENT is running and ovf-env.xml created in the /var/lib/waagent.

Really appreciate your help in asking me to check the **UDF filesystem** otherwise, it is impossible for us to identify the reason behind the issue.

Thank you once again @trstringer

**Comment by trstringer** [comment]
Great to hear! Thanks for opening the issue and following up!
