### ISSUE TITLE
/var/lib/waagent zip files

### ISSUE THREAD

**Issue by mabicca** [Azure/WALinuxAgent#2031]
Hi Everyone,

I know we had some fixes for this issue in the past:
https://github.com/Azure/WALinuxAgent/issues/1730

We still see cases where there's tons of old zip files in the folder and recently I noticed that specifically the WALinuxAgent install files are still there?

```
drwxr-xr-x  3 root root      4096 Sep 15 19:42 WALinuxAgent-2.2.44
-rw-r--r--  1 root root    502139 Sep 15 19:42 WALinuxAgent-2.2.44.zip
drwxr-xr-x  3 root root      4096 Sep 15 19:42 WALinuxAgent-2.2.45
-rw-r--r--  1 root root    517593 Sep 15 19:42 WALinuxAgent-2.2.45.zip
drwxr-xr-x  3 root root      4096 Sep 15 19:42 WALinuxAgent-2.2.46
-rw-r--r--  1 root root    530463 Sep 15 19:42 WALinuxAgent-2.2.46.zip
drwxr-xr-x  3 root root      4096 Sep 15 19:42 WALinuxAgent-2.2.48.1
-rw-r--r--  1 root root    531494 Sep 15 19:42 WALinuxAgent-2.2.48.1.zip
drwxr-xr-x  3 root root      4096 Sep 15 19:42 WALinuxAgent-2.2.49.2
-rw-r--r--  1 root root    547951 Sep 15 19:42 WALinuxAgent-2.2.49.2.zip
drwxr-xr-x  3 root root      4096 Oct  6 19:43 WALinuxAgent-2.2.51
-rw-r--r--  1 root root    547144 Oct  6 19:43 WALinuxAgent-2.2.51.zip
```
Are there any plans to manage these leftovers better moving forward? We have many users that ask about it.

As far as old ZIP files, if a user wants to clean up let's say 100+ VM's what is the safest way to do that?
Do we have any proper guidance on how to do that safely?

Would let's say:
```
stop the agent
mv /var/lib/waagent /var/lib/waagent.old
start the waagent
cp /var/lib/waagent.old/ovf-env.xml /var/lib/waagent/lib
```
Be a good solution so the waagent would re-download the most recent extensions only?

Thank you,
Marco

**Comment by narrieta** [comment]
@mabicca - This is a different issue to #1730 

I'll do some changes in the backend so that some ZIP files are not downloaded anymore, but for existing VMs the mitigation is to manually remove each of the old agents that are not in use.

Doing this

    mv /var/lib/waagent /var/lib/waagent.old

will not work and will introduce other issues.

**Comment by ZhidongPeng** [comment]
Deleted the older version 2.2.44, 2.2.45 and 2.2.46

**Comment by mabicca** [comment]
Hi @ZhidongPeng , just to make sure, was logic added to remove older zip files moving forward too? If so, how many are we keeping behind? It would be nice to have this behavior somehow documented as users are always asking about space management within the /var/lib/waagent folder.

Thank you!
-Marco

**Comment by narrieta** [comment]
@mabicca The logic to remove older zips (once they have been removed from the backend, which is what @ZhidongPeng was doing) is already there. Can you verify that the agent removed them from the affected VM?

We usually keep 3 or 4 versions, but that depends on several factors and we are soon going to change that, so at this point it wouldn't be worth documenting the current behavior.

**Comment by mabicca** [comment]
Alright, that sounds good, thanks for the clarification @narrieta . I can probably verify that later for sure. Thank you again!

**Comment by mabicca** [comment]
Hi Folks,

Just wanted to check on something, what was the change that we did for this behavior?

I still see this on a fairly new VM:

drwxr-xr-x  3 root root      4096 Jan  8  2021 WALinuxAgent-2.2.52
-rw-r--r--  1 root root    553571 Jan  8  2021 WALinuxAgent-2.2.52.zip
drwxr-xr-x  3 root root      4096 Mar 18 18:17 WALinuxAgent-2.2.53.1
-rw-r--r--  1 root root    598486 Mar 18 18:17 WALinuxAgent-2.2.53.1.zip
drwxr-xr-x  3 root root      4096 Mar 31 18:50 WALinuxAgent-2.2.54.2
-rw-r--r--  1 root root    631616 Mar 31 18:50 WALinuxAgent-2.2.54.2.zip
drwxr-xr-x  3 root root      4096 May 14 19:09 WALinuxAgent-2.3.0.1
-rw-r--r--  1 root root    643478 May 14 19:09 WALinuxAgent-2.3.0.1.zip
drwxr-xr-x  3 root root      4096 May 27 22:22 WALinuxAgent-2.3.0.2
-rw-r--r--  1 root root    643964 May 27 22:22 WALinuxAgent-2.3.0.2.zip
drwxr-xr-x  3 root root      4096 Jul  8 22:31 WALinuxAgent-2.3.1.1
-rw-r--r--  1 root root    643890 Jul  8 22:31 WALinuxAgent-2.3.1.1.zip
drwxr-xr-x  3 root root      4096 Aug 18 14:42 WALinuxAgent-2.4.0.2
-rw-r--r--  1 root root    658281 Aug 18 14:42 WALinuxAgent-2.4.0.2.zip

**Comment by narrieta** [comment]
No changes in the agent itself, the cleanup is on the back end. We have a cleanup scheduled within the next couple of days.

**Comment by mabicca** [comment]
@narrieta Could we have this documented? We always have customers asking why they see all these files and it's always not easy to determine how the cleanup works.

**Comment by strimpak** [comment]
Running version:
`WALinuxAgent-2.2.45 running on ubuntu 18.04
Python: 3.6.9
Goal state agent: 2.5.0.2`

still found zip files and folders under `/var/libwaagent` :

`drwxr-xr-x  5 root root 4.0K Oct  6 02:20 Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9187.0
-rw-r--r--  1 root root 1.6M Oct  6 02:20 Microsoft.Azure.RecoveryServices.VMSnapshotLinux__1.0.9187.0.zip
drwxr-xr-x  8 root root 4.0K Nov 24 02:19 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.40
-rw-r--r--  1 root root 137M Sep 21 18:35 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux__1.13.40.zip
drwxr-xr-x  3 root root 4.0K Jun 26 14:12 WALinuxAgent-2.2.52
-rw-r--r--  1 root root 541K Jun 26 14:12 WALinuxAgent-2.2.52.zip
drwxr-xr-x  3 root root 4.0K Jun 26 14:12 WALinuxAgent-2.2.53.1
-rw-r--r--  1 root root 585K Jun 26 14:12 WALinuxAgent-2.2.53.1.zip
drwxr-xr-x  3 root root 4.0K Jun 26 14:12 WALinuxAgent-2.2.54.2
-rw-r--r--  1 root root 617K Jun 26 14:12 WALinuxAgent-2.2.54.2.zip
drwxr-xr-x  3 root root 4.0K Jun 26 14:12 WALinuxAgent-2.3.0.2
-rw-r--r--  1 root root 629K Jun 26 14:12 WALinuxAgent-2.3.0.2.zip
drwxr-xr-x  3 root root 4.0K Jul  1 18:09 WALinuxAgent-2.3.1.1
-rw-r--r--  1 root root 629K Jul  1 18:09 WALinuxAgent-2.3.1.1.zip
drwxr-xr-x  3 root root 4.0K Aug 18 00:57 WALinuxAgent-2.4.0.2
-rw-r--r--  1 root root 643K Aug 18 00:57 WALinuxAgent-2.4.0.2.zip
drwxr-xr-x  3 root root 4.0K Oct 13 20:26 WALinuxAgent-2.5.0.2
-rw-r--r--  1 root root 653K Oct 13 20:26 WALinuxAgent-2.5.0.2.zip`

Can I safely delete those folders and files? Will they get recreated?

**Comment by larohra** [comment]
> Can I safely delete those folders and files? Will they get recreated?

@strimpak unfortunately deleting them won't help, the agent will end up downloading them again. We're working on a fix that will only keep the current version on disk and will delete everything else. The feature is already implemented but will be released in a couple of months due to pending dependencies on the upstream services. Once that's enabled end-to-end, you should not see any extra zips in your `/var/lib/waagent` directories.

**Comment by itsafire** [comment]
Any info on the current status of this issue? I currently have a client with a /var/lib/waagent of 13GB in size claiming 50% of the filesystem.

**Comment by narrieta** [comment]
@itsafire This should be resolved. In case the agent did not remove old ZIPs, please go ahead and remove them manually.
