### ISSUE TITLE
waagent not checking for holes in swap file

### ISSUE THREAD

**Issue by imabedalghafer** [Azure/WALinuxAgent#2036]
When using a debian OS created from image : Debian:debian-10:10-backports:0.20200928.407
which has the kernel version : 5.7.0-0.bpo.2-cloud-amd64 and trying to enable the swap following the document :
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/oom-swap-file-linux-vm

The swap file will be created but the mount for it will fail, and "swapon -s" will not show any swap file enabled.

Agent logs:
![image](https://user-images.githubusercontent.com/52040217/95673958-b3e44600-0bb5-11eb-8a8e-99181019deee.png)

dmesg logs:
sudo dmesg | grep swap 
[    0.851516] Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization 
[    7.412335] swapon: swapfile has holes 
[   11.457461] swapon: swapfile has holes

checking on the links:
https://manpages.courier-mta.org/htmlman8/swapon.8.html#:~:text=swapon%3A%20swapfile%20has%20holes.,on%2Dwrite%20filesystems%20like%20btrfs.

this is due to fallocate command itself.
A workaround for this issue we had so far is either:
- boot the machine from an older kernel version 5.6.0-0.bpo.2-cloud-amd64 and earlier
- create the swap file using dd.

Checking on source code for agent:
https://github.com/Azure/WALinuxAgent/blob/e004bd0fbecd562d577426d9c1ad8c8e76e94df5/azurelinuxagent/daemon/resourcedisk/default.py#L358

it does fail back to use dd but only if fallocate command fail.

an ask if you may please consider adding a condition to check if mount failed due to file contain holes is to fail back to dd , not only with failure of command itself. 

**Repro steps**

- create a debian 10 machine with kernel 5.7.0-0.bpo.2-cloud-amd64 or greater 
- configure swap following the link:
https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/oom-swap-file-linux-vm
- run command "swapon -s" you will not find any active swap file
- check on dmesg , you will get same messages as above.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Debian 10 with kernel 5.7.0-0.bpo.2-cloud-amd64 or greater
 - WALinuxAgent version : test with 
![image](https://user-images.githubusercontent.com/52040217/95679560-4dbee980-0bdc-11eb-97a7-a98498cc1205.png)
but I think it will be on another versions as well

**Comment by narrieta** [comment]
@trstringer could you take a look? thanks!

**Comment by trstringer** [comment]
Thanks for opening this issue, @imabedalghafer! Doing some research it appears as though `swapon` has it documented that we should be doing `dd` (instead of `fallocate`) for ext4. I've opened up a PR to fix this.

**Comment by trstringer** [comment]
This PR has now been merged and should be resolved. Let me know if you have any questions or issues. Thanks again for opening this issue and bringing this to our attention!

**Comment by imabedalghafer** [comment]
@trstringer thank you so much for your time and effort on this 👍 
one last question , on which waagent we expect this change to take effect ?
