### ISSUE TITLE
Execute Custom Script (Permission Denied)

### ISSUE THREAD

**Issue by willguibr** [Azure/WALinuxAgent#2056]
Hi There,I created an Azure ARM template, which is using the Microsoft.Compute/virtualMachines/extensions in an Ubuntu 18.04 in order to execute a custom script. Once the machine is provisioned, the ubuntu user (non-root) should be able to run the custom script from the following directory /var/lib/waagent/custom-script/download/0 but it receives "permission denied".  This is the default directory where the extension downloads the script to and then executes during the provisioning process. 
I tried to changed the permissions to allow the ubuntu user to access the directory and run the command from there as a regular user, but it returns permission denied.
Is there a way to allow the ubuntu user to access this directory and execute the script from that location?
Thank you

**Comment by narrieta** [comment]
@willguibr The permissions on the "download" directory are set and managed by the custom script extension. Could you open this issue in the https://github.com/Azure/azure-linux-extensions repo? Thank you.
