### ISSUE TITLE
[BUG] Waagent is not able to copy ovf-env.xml

### ISSUE THREAD

**Issue by vish74** [Azure/WALinuxAgent#2058]
**Describe the bug: Waagent is not able to copy ovf-env.xml from mounted location.**

In our distro, we have a script that auto mount various devices at specific locations. Waagent detects the mount location but failing to copy ovf-env.xml.

Logs from Waagent:
> 2020-10-28T23:20:32.999347Z INFO Daemon Daemon Running default provisioning handler
2020-10-28T23:20:33.001779Z INFO Daemon Daemon Copying ovf-env.xml
2020-10-28T23:20:33.006362Z INFO Daemon Daemon /dev/sr0 is already mounted at /run/media/sr0
2020-10-28T23:20:33.006628Z ERROR Daemon Daemon Provisioning failed: [ProtocolError] [CopyOvfEnv] Error reading file /mnt/cdrom/secure/ovf-env.xml: [Errno 2] No such file or directory: '/mnt/cdrom/secure/ovf-env.xml' (116.92s)

1. Currently we have disabled auto mount for /dev/sr0 as a workaround for the issue. Can there be any plans to fix this?
2. Is the "ovf-env.xml" file part of any extension?
3. Can we avoid that step by disabling any flags in configurations? We don't want to disable all extensions as it can include some monitoring capabilities. (Extensions.Enabled=y)  

**Distro and WALinuxAgent details**
 - Custom Linux OS
 - WALinuxAgent version 2.2.49.2

**Edit: Additional Details**

Currently "VM certification" is failing for our OS (even with the workaround) and not reporting any actual logs. We have reached out to Azure Marketplace team and initial response is the URL: https://aka.ms/VM-Provisioning-Issue

Does Waagent provide required details from the host for VM Certifications steps (Linux test cases) ?

Also if we deploy same OS/Image through "Shared Image Galleries" it is able to launch VM as expected without any errors. So we are not sure about the root cause for the issue.

**Comment by narrieta** [comment]
@trstringer Could you take a look? thanks!

**Comment by trstringer** [comment]
Thanks for opening this issue! So what seems to be happening is that you're mounting the cd-rom in a non-default location prior to walinuxagent getting a chance to do that. That shouldn't be an issue, but you should be setting the correct mount point in configuration so that walinuxagent knows where to find the cd-rom mount. In `waagent.conf` you can set `DVD.MountPoint` to `/run/media/sr0`, and that should then allow walinuxagent to successfully read `/run/media/sr0/ovf-env.xml`.

As a side note, this is part of the provisioning agent in walinuxagent and completely separate from extensions.

Let me know if that works!

**Comment by vish74** [comment]
Thanks for the details.
I think setting DVD.MountPoint with static path like `/run/media/sr0` may work as expected, however it can be avoided as waagent shows mounted location. It would be good if Agent can override default path for such cases.

> 2020-10-28T23:20:33.006362Z INFO Daemon Daemon /dev/sr0 is already mounted at /run/media/sr0

This issue can be part of enhancement as most of the generic OS may not run into the issue.

**Comment by trstringer** [comment]
Thanks for the ideas! We will take that into consideration. In the meantime, let me know if setting `DVD.MountPoint` has fixed your issue!

**Comment by vish74** [comment]
Hi, as we disabled the auto mount it fixed the ovf-env.xml file issue.
However currently with Azure Image deployment with our OS, we are seeing this different error.  (which probably wasn't there before. Did something change recently? :) ) 

> {
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "OSProvisioningClientError",
                "message": "SSH host key generation failed. Error details: [ProvisionError] Failed to generate ssh host key: ret=255, out= ssh-keygen: /etc/ssh/ssh_host_rsa_key.pub: No such file or directory\n. To resolve this issue verify if Linux agent is set up properly. \r\n    You can check the instructions at : https://azure.microsoft.com/documentation/articles/virtual-machines-linux-agent-user-guide/\r\n   "
            }
        ]
    }
}


Part of our waagent.conf file - 

> Extensions.Enabled=y
> Extensions.GoalStatePeriod=6
> Extensions.GoalStateHistoryCleanupPeriod=86400
> Provisioning.Agent=waagent
> Provisioning.DeleteRootPassword=n
> Provisioning.RegenerateSshHostKeyPair=n
> Provisioning.SshHostKeyPairType=rsa
> Provisioning.MonitorHostName=n

From waagent.log file -

> 2020-11-06T19:47:20.610053Z INFO Daemon Daemon Configure sshd
2020-11-06T19:47:20.612103Z INFO Daemon Daemon Enabled SSH password-based authentication methods.
2020-11-06T19:47:20.612254Z INFO Daemon Daemon Configured SSH client probing to keep connections alive.
2020-11-06T19:47:20.718783Z ERROR Daemon Daemon Command: [ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub], return code: [255], result: [ssh-keygen: /etc/ssh/ssh_host_rsa_key.pub: No such file or directory
]
2020-11-06T19:47:20.719701Z ERROR Daemon Daemon Provisioning failed: [ProvisionError] Failed to generate ssh host key: ret=255, out= ssh-keygen: /etc/ssh/ssh_host_rsa_key.pub: No such file or directory
 (60.40s)
2020-11-06T19:47:23.956791Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=Provision, message=Provisioning failed: [ProvisionError] Failed to generate ssh host key: ret=255, out= ssh-keygen: /etc/ssh/ssh_host_rsa_key.pub: No such file or directory
 (60.40s), duration=0

> 2020-11-06T19:46:59.250706Z INFO Daemon Daemon Azure Linux Agent Version:2.2.48.1


If we disable ssh provisioning with config, does it still look for the file /etc/ssh/ssh_host_rsa_key.pub ? Are we missing any config?

**Comment by trstringer** [comment]
No matter what I try, I can't seem to repro this (removed the host keys prior to provisioning a new VM with the modified config).

Can you send me step-by-step repro instructions? Thanks!

**Comment by vish74** [comment]
We don't modify waagent code in any way and using it as it is with few changes in waagent.conf file. After deployment and during first boot up on Azure, it starts the systemd process and runs into the issue.
During first boot our system may generate some certificates/keys but not sure if that can create any race condition for files/directories.

What are the waagent configs that are looking for /etc/ssh/ssh_host_rsa_key.pub file? I can check again if those are disabled or not.

Sharing here screenshots, let me know if these can be helpful.

1 ) VM launch config -

![Selection_029](https://user-images.githubusercontent.com/806390/98745066-ae6e4d00-2367-11eb-849d-46dcbcc25451.png)

2) Deployment failed - 

![Selection_031](https://user-images.githubusercontent.com/806390/98745124-cf36a280-2367-11eb-85a6-75d72e2518f2.png)

3 ) Error -

![Selection_032](https://user-images.githubusercontent.com/806390/98745210-f7260600-2367-11eb-865b-a4237c85752b.png)

4 ) Files in /var/lib/waagent - 

![Selection_034](https://user-images.githubusercontent.com/806390/98745229-086f1280-2368-11eb-9655-b0755b9c483a.png)

5 ) Systemd service file -

![image](https://user-images.githubusercontent.com/806390/98745458-7582a800-2368-11eb-96b4-75cec9e33f1d.png)

6 ) /etc/waagent.conf file -

![image](https://user-images.githubusercontent.com/806390/98745506-8f23ef80-2368-11eb-9502-c2b9f66313d7.png)

7 ) Part of /var/log/waagent.log - If you need complete log file, I can send via direct email.

![image](https://user-images.githubusercontent.com/806390/98745564-a6fb7380-2368-11eb-8280-c4465373bd92.png)

8 ) /etc/ssh -

![image](https://user-images.githubusercontent.com/806390/98745677-dad69900-2368-11eb-94c7-4decac1d9272.png)


I think Azure Marketplace team is also running into similar issue for our OS certification.
Thanks for the help.

**Comment by trstringer** [comment]
Thanks for the information! So [get_ssh_host_key_thumbprint](https://github.com/Azure/WALinuxAgent/blob/v2.2.49.2/azurelinuxagent/pa/provision/default.py#L157-L164) is what is throwing this error. And this is because it is running `ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub` and the file *does not exist* at this point.

If you look at the screenshot, the error is thrown at 20:47 and the file has a timestamp of 20:53. So that explains the error.

Do you know what process is creating the ssh host keys later on? Do you have cloud-init installed and enabled on this image? If so, they will conflict for provisioning agents. You have `Provisioning.Agent` set to `waagent` which removes the auto-detect feature, forcing waagent to think it's the provisioning agent.

So the main question now is do you know what process (which ran after waagent) generated the ssh host keys?

**Comment by vish74** [comment]
Thanks for the reply @trstringer 

> Do you know what process is creating the ssh host keys later on?

> So the main question now is do you know what process (which ran after waagent) generated the ssh host keys?

Key generation should be part of Openssh process. We can set systemd configs to run waagent after openssh service.
However I think waggent should only execute [get_ssh_host_key_thumbprint](https://github.com/Azure/WALinuxAgent/blob/v2.2.49.2/azurelinuxagent/pa/provision/default.py#L157) if the keys are created by reg_ssh_host_key and RegenerateSshHostKeyPair=y.  Not sure if keys check is needed by waagent in any other case.


> Do you have cloud-init installed and enabled on this image?

No, we don't have cloud-init on our system. So setting Provisioning.Agent with waagent should be fine, if there aren't any other issues.

**Comment by trstringer** [comment]
> Key generation should be part of Openssh process

I think you would either need to run `dpkg-reconfigure openssh-server` (for deb-based distros) or you would need to run `ssh-keygen -A`. I'm not seeing that sshd creates them if they don't exist. If they don't exist, I see a handful of these messages:

> sshd[509]: Could not load host key: /etc/ssh/ssh_host_rsa_key

Are you seeing in your ssh service that it is automatically generating the keys?

Another thing you could consider is having a small custom service running before walinuxagent that just checks the existence of the key and if it doesn't exist generates it then. Or otherwise, let's try to understand what process it is that is creating these ssh host keys after-the-fact (maybe it is the ssh service and we just have different sshd_config?).

**Comment by vish74** [comment]
Thanks.
Yes, planning to do a test with running waagent after SSH keys generated properly , [example](https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-connectivity/openssh/openssh/sshd_check_keys)

> we can not report ready/success for this VM if you cannot connect/SSH into it

I think this should be documented and part of the requirement if waagent has to look for "ssh_host_rsa_key.pub" file.

**Comment by trstringer** [comment]
Ok sounds good. Let me know how your testing goes for a final resolution.

> I think this should be documented and part of the requirement if waagent has to look for "ssh_host_rsa_key.pub" file.

That's a good idea! I'll take that suggestion back to the team. Thanks!

**Comment by trstringer** [comment]
@vish74, did your testing show success? Let me know if you have any other questions!

**Comment by vish74** [comment]
Hi @trstringer Yes, it was successful and after some help from Azure Marketplace team, we were able to publish.

For future improvements on Waagent it would be good to cover these two based on above discussions.

1 ) As waagent detects mount location in logs - `/dev/sr0 is already mounted at /run/media/sr0`, it should be able to select mount overriding the default config. Setting `DVD.MountPoint` to `/run/media/sr0` should be avoided as `sr0` number can change and cause the same issue. (There can be a variable as well asking to allow override, may be? ) 

2 ) Document "/etc/ssh/ssh_host_rsa_key.pub" directory/file is required to successfully launch custom Azure VM for any distro.

Thanks for the help.

**Comment by trstringer** [comment]
Thanks for opening this issue and thank you for those suggestions! I will take them back to my team. Have a great day!
