### ISSUE TITLE
[BUG][RHEL-8] Miss report "hostnamectl set-hostname --static] failed, attempting fallback"

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2092]
**Describe the bug: A clear and concise description of what the bug is.**
WALA reports "WARNING EnvHandler ExtHandler [hostnamectl set-hostname <hostname> --static] failed, attempting fallback" in waagent.log, which actually run successfully.

Seems the root cause is in azurelinuxagent/common/osutil/redhat.py:
class RedhatOSUtil(Redhat6xOSUtil):
...
    def set_hostname(self, hostname):
...
        if self._run_command_without_raising(hostnamectl_cmd, log_error=False) != 0:
The self._run_command_without_raising function doesn't have return value. Shouldn't get the return value here.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: 
RHEL-8
 - WALinuxAgent version:
WALinuxAgent-2.2.49.2 running on redhat 8.4
Python: 3.6.8
Goal state agent: 2.2.52

**Additional context**
N/A

**Log file attached**
WARNING EnvHandler ExtHandler [hostnamectl set-hostname walacheck3 --static] failed, attempting fallback

**Comment by larohra** [comment]
Fixed in #2093
