### ISSUE TITLE
[BUG] Cannot remove orphaned extension package

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2101]
**Describe the bug: A clear and concise description of what the bug is.**

In exthandlers.py there's such function:
    def _cleanup_outdated_handlers(self):
...
        # Build a collection of uninstalled handlers and orphaned packages
        # Note:
        # -- An orphaned package is one without a corresponding handler
        #    directory

As I understand that this function should remove the extension .zip package that doesn't exist in ExtensionsConfig.xml and doesn't have it's directory. So I tried to make a fake extension package named "Microsoft.OSTCExtensions.VMAccessForLinux__1.0.1.zip" under /var/lib/waagent/. But it cannot be removed. Seems it cannot match the regular expression in _HANDLER_PKG_PATTERN.

Besides, I'm not quite sure if this condition is correct:
            elif os.path.isfile(path) and \
                    not os.path.isdir(path[0:-len(HANDLER_PKG_EXT)]):
Because the package name is not the same as directory name. e.g.
package: Microsoft.OSTCExtensions.VMAccessForLinux__1.5.10.zip
directory: Microsoft.OSTCExtensions.VMAccessForLinux-1.5.10

**Reproduce steps:**
1. Create a file in /var/lib/waagent/ named "Microsoft.OSTCExtensions.VMAccessForLinux__1.0.1.zip"
2. Restart waagent and wait for several seconds

Actual result:
This file is not removed.

**Distro and WALinuxAgent details (please complete the following information):**
WALinuxAgent-2.2.49.2 running on redhat 8.4
Python: 3.6.8
Goal state agent: 2.2.49.2

Thanks!

**Comment by narrieta** [comment]
@yuxisun1217 Does this happen only on the files you created manually, or is it happening on zips created by the agent?

**Comment by yuxisun1217** [comment]
Hi @narrieta ,

I cannot hit this scenario by agent, so I tried to create a file to emulate the orphaned extension package. The package Microsoft.OSTCExtensions.VMAccessForLinux__1.5.10.zip is the real VMAccessForLinux extension package that was downloaded by the agent. I just rename it's version to become Microsoft.OSTCExtensions.VMAccessForLinux__1.0.1.zip. From the code I think it can emulate the orphaned package. Do you think the steps make sense? Thanks!

**Comment by narrieta** [comment]
@yuxisun1217 Thanks for pointing this out. If it is not causing issues with the files downloaded by the agent then we'll take a look at a later time.
