### ISSUE TITLE
[BUG] ERROR ExtHandler ExtHandler Event: name=Microsoft.Azure.Diagnostics.LinuxDiagnostic

### ISSUE THREAD

**Issue by scmdavid** [Azure/WALinuxAgent#2102]
From the following error in log with fresh installation

2020-12-09T04:09:59.087477Z ERROR ExtHandler ExtHandler Event: name=Microsoft.Azure.Diagnostics.LinuxDiagnostic, op=Install, message=eJytkbtOw0AQRfv9iqs0ASlexwo07iJhKh4FZWKkxZ5YIy2z1uw6OEH8O8ZC8AEw1dUp5ozm7qoxkUQO8tiTujSFSjVojYcg2Zk0gEZOaEJLJYoV8qPT3PNL/uZcR5Lye240xHBIdnselOwNu05CTNxEe8cyjL8g29i1LTZF3v4g25+QscTkvDe7mNowpNqYOZJqbYBb9oTF/3sXK3gWwvXVJAF6ZUlYbuFD4zz4tQ+acEG2syt8Sy9xcNM1rUU1NtR/favE+/pjL0vs5y1/m2fzdJLkxrmCEixH57lFnKH5BKHqhhA=, duration=0

Environment:
OS: Red Hat Enterprise Linux release 8.2 (Ootpa)
Agent WALinuxAgent-2.2.52 

[waagent.log](https://github.com/Azure/WALinuxAgent/files/5663545/waagent.log)

**Comment by narrieta** [comment]
@scmdavid - This is an error in the Diagnostics extension. Could you open an issue on https://github.com/Azure/azure-linux-extensions?

The error is:

```
$ echo 'eJytkbtOw0AQRfv9iqs0ASlexwo07iJhKh4FZWKkxZ5YIy2z1uw6OEH8O8ZC8AEw1dUp5ozm7qoxkUQO8tiTujSFSjVojYcg2Zk0gEZOaEJLJYoV8qPT3PNL/uZcR5Lye240xHBIdnselOwNu05CTNxEe8cyjL8g29i1LTZF3v4g25+QscTkvDe7mNowpNqYOZJqbYBb9oTF/3sXK3gWwvXVJAF6ZUlYbuFD4zz4tQ+acEG2syt8Sy9xcNM1rUU1NtR/favE+/pjL0vs5y1/m2fzdJLkxrmCEixH57lFnKH5BKHqhhA=, duration=0' | base64 -d | pigz -zd
base64: invalid input
[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.131/diagnostic.py -install
[stdout]


[stderr]
  File "/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.131/diagnostic.py", line 54
    print 'A local import (e.g., waagent) failed. Exception: {0}\n' \
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by scmdavid** [comment]
Created in https://github.com/Azure/azure-linux-extensions/issues/1274

**Comment by uppalapativinaysai** [comment]
> @scmdavid - This is an error in the Diagnostics extension. Could you open an issue on https://github.com/Azure/azure-linux-extensions?
> 
> The error is:
> 
> ```
> $ echo 'eJytkbtOw0AQRfv9iqs0ASlexwo07iJhKh4FZWKkxZ5YIy2z1uw6OEH8O8ZC8AEw1dUp5ozm7qoxkUQO8tiTujSFSjVojYcg2Zk0gEZOaEJLJYoV8qPT3PNL/uZcR5Lye240xHBIdnselOwNu05CTNxEe8cyjL8g29i1LTZF3v4g25+QscTkvDe7mNowpNqYOZJqbYBb9oTF/3sXK3gWwvXVJAF6ZUlYbuFD4zz4tQ+acEG2syt8Sy9xcNM1rUU1NtR/favE+/pjL0vs5y1/m2fzdJLkxrmCEixH57lFnKH5BKHqhhA=, duration=0' | base64 -d | pigz -zd
> base64: invalid input
> [ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.131/diagnostic.py -install
> [stdout]
> 
> 
> [stderr]
>   File "/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.131/diagnostic.py", line 54
>     print 'A local import (e.g., waagent) failed. Exception: {0}\n' \
>                                                                   ^
> SyntaxError: invalid syntax
> ```

HI @scmdavid @narrieta If you know solution for the above problem please let me know.. I trying harder but I am not getting. 
Thanks in Advance..!!!
