### ISSUE TITLE
Cloudinit fails to copy /var/lib/waagent/ovf-env.xml when /var/tmp has been mounted mode=1777,strictatime,noexec,nodev,nosuid

### ISSUE THREAD

**Issue by lunarfs** [Azure/WALinuxAgent#2103]
So we are hardening a debian 10.7 image using packer, part of the hardening is making sure /var/tmp has been mounted mode=1777,strictatime,noexec,nodev,nosuid
if this particular piece is leftout, we can boot the image, but mounting the /var/tmp drive with a systemd script makes the cloutinit fail, and the vm never gets online.
We are upgrading from wheezy, and in the old weezy image it works nicely. 

adding and enabling the script after cloudinit has been running works, but i guess that upgrading waagent will still be failing?, and we would really like this hardening to be part of our custom base image. At least i have no knowledge of what consequences this would have going forward. 

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Debian Buster, 10.7
   packer image based on the following azure image 
    base_image:
      publisher: "Debian"
      offer: "debian-10"
      sku: "10"
      version: "latest"
 - WALinuxAgent version 
WALinuxAgent-2.2.45 running on debian 10.7
Python: 3.7.3
Goal state agent: 2.2.45

**Additional context**
so the systemd script is as follows
##########################################
cat /lib/systemd/system/var-tmp.mount
[Unit]
Description=Temporary Directory
Documentation=man:hier(7)
Before=local-fs.target

[Mount]
What=tmpfs
Where=/var/tmp
Type=tmpfs
Options=mode=1777,strictatime,noexec,nodev,nosuid

[Install]
WantedBy=multi-user.target
##########################################

**Log file attached**
2020/12/09 14:55:12.332101 INFO Running CloudInit provisioning handler
2020/12/09 14:55:12.332816 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1800 retries remaining, sleeping 1s]
  OK  ] Started Unattended Upgrades Shutdown.
[  OK  ] Started Postfix Mail Transport Agent (instance -).
         Starting Postfix Mail Transport Agent...
[  OK  ] Started Postfix Mail Transport Agent.2020/12/09 14:55:13.347112 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1799 retries remaining, sleeping 1s]

[   21.267410] cloud-init[819]: Cloud-init v. 20.2 running 'modules:config' at Wed, 09 Dec 2020 14:55:12 +0000. Up 19.21 seconds.
[  OK  ] Started Apply the settings specified in cloud-config.
2020/12/09 14:55:14.354867 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1798 retries remaining, sleeping 1s]
2020/12/09 14:55:14.367328 WARNING cloud-init does not appear to be running
2020/12/09 14:55:15.372607 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1797 retries remaining, sleeping 1s]
2020/12/09 14:55:15.393992 WARNING cloud-init does not appear to be running
[  OK  ] Started containerd container runtime.
         Starting Docker Application Container Engine...
2020/12/09 14:55:16.401568 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1796 retries remaining, sleeping 1s]
2020/12/09 14:55:16.414923 WARNING cloud-init does not appear to be running
2020/12/09 14:55:17.423026 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1795 retries remaining, sleeping 1s]
2020/12/09 14:55:17.429048 WARNING cloud-init does not appear to be running

* This system is for authorized use only.
* Users (authorized or unauthorized) have no explicit or implicit expectation of privacy.
* Any or all uses of this system and all files on this system may be monitored.

localhost login: 2020/12/09 14:55:18.459734 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1794 retries remaining, sleeping 1s]
2020/12/09 14:55:18.471745 WARNING cloud-init does not appear to be running
2020/12/09 14:55:19.477369 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1793 retries remaining, sleeping 1s]
2020/12/09 14:55:19.490776 WARNING cloud-init does not appear to be running
2020/12/09 14:55:20.495848 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1792 retries remaining, sleeping 1s]
2020/12/09 14:55:20.507430 WARNING cloud-init does not appear to be running
2020/12/09 14:55:21.508807 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1791 retries remaining, sleeping 1s]
2020/12/09 14:55:21.531789 WARNING cloud-init does not appear to be running
2020/12/09 14:55:22.537695 INFO Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1790 retries remaining, sleeping 1s]
2020/12/09 14:55:22.553012 WARNING cloud-init does not appear to be running

**Comment by narrieta** [comment]
@anhvoms @trstringer Could you take a look at this one? Thanks!

**Comment by trstringer** [comment]
This seems to be unrelated to walinuxagent entirely. I was able to repro it with your systemd mount unit and I see this in the cloud-init log:

```
Command: ['/var/tmp/cloud-init/cloud-init-dhcp-1nb7a8tk/dhclient', '-1', '-v', '-lf', '/var/tmp/cloud-init/cloud-init-dhcp-1nb7a8tk/dhcp.leases', '-pf', '/var/tmp/cloud-init/cloud-init-dhcp-1nb7a8tk/dhclient.pid', 'eth0', '-sf', '/bin/true']
Exit code: -
Reason: [Errno 13] Permission denied: b'/var/tmp/cloud-init/cloud-init-dhcp-1nb7a8tk/dhclient'
Stdout: -
Stderr: -
```

cloud-init will copy `dhclient` to `/var/tmp`, which you have mounted with `noexec`. So the copy succeeds but it fails when trying to execute, and this is why you're seeing the failures.

**Comment by lunarfs** [comment]
Hi,
Thanks for sorting this out, think i will need to work on getting access to the cloud init log.
Sorry for reporting this on the wrong project.
