### ISSUE TITLE
[Suggession] Deal with no-temporary disk sizes gracefully

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2110]
**Describe the bug: A clear and concise description of what the bug is.**
There are several new VM sizes that doesn't have temporary disk(Such as: E2s_v4). Perhaps we can find some way to deal with it more gracefully. Currently WALA reports error logs:
2020-12-15T04:20:40.373033Z ERROR Daemon Daemon Failed to mount resource disk [ResourceDiskError] unable to detect disk topology
2020-12-15T04:20:40.377132Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=ActivateResourceDisk, message=[ResourceDiskError] unable to detect disk topology, duration=0

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL-8.4
WALinuxAgent 2.2.49

**Comment by narrieta** [comment]
@anhvoms @trstringer - could you take a look? thanks!

**Comment by almalinux4all** [comment]
+1 for the graceful deal of the missing resource disk. 

Also, the swap file if enabled, is created on the resource disk, and therefore if the resource disk is missing, the error looks even nicer... 

In a cloud environment, it is expected that the end user changes the instance type of the VM from time to time. If by chance he picks one new instance type that has a missing resource disk, a more meaningful message should be displayed...

**Comment by anhvoms** [comment]
RHEL-8.1+ should be using cloud-init to provision VM and handle resource disk, which does handle missing resource disk in a more graceful manner. walinuxagent as provisioning agent is in maintenance mode and will only receive critical/security updates.
