### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by mhd196** [Azure/WALinuxAgent#2113]
I have an application that send emails in batches. I have two reported incidents of "EMAIL SERVER CONNECTION FAILED" where no reason yet found to explain them. Just a handful number of emails were not sent. I found that both happened in same minute a heartbeat info message. These heartbeats happen every half hours (almost).  Is it a mere coincidence or there could be some kind of resource locking and timeouts?

![image](https://user-images.githubusercontent.com/33846518/102386488-cc1e7a00-3fd7-11eb-8463-2cdffef8f737.png)

-

**Comment by pgombar** [comment]
Hi, the `HEARTBEAT` message is a debug message from WALinuxAgent that is logged every 30 minutes. It shouldn't affect anything else on your system.

**Comment by mhd196** [comment]
According to description of WALinuxAgent  :
...
Networking
Manages routes to improve compatibility with platform DHCP servers
Ensures the stability of the network interface name
...
So I am wondering if this debug message is triggered after or before procedures that are locking a resource for a while which causing the mail sending interruption.

**Comment by pgombar** [comment]
> So I am wondering if this debug message is triggered after or before procedures that are locking a resource for a while which causing the mail sending interruption.

The debug messages are not triggered by anything other than an internal timer in the agent (log every 30 minutes), so the timing is just a coincidence.

**Comment by mhd196** [comment]
Thank you very much.
