### ISSUE TITLE
Use architected interfaces to determine IPv4 addresses of interfaces, identify loopback NICs, etc.

### ISSUE THREAD

**Issue by jasonzio** [Azure/WALinuxAgent#212]
Use sysfs, procfs, or other standard architected interfaces to check NIC flags for IFF_LOOPBACK, find the ipv4 addresses of NICs, etc. See [Issue 188](https://github.com/Azure/WALinuxAgent/issues/188) for more details.

**Comment by rginjupalli** [comment]
Based on the ideas pointed in [Issue 188](https://github.com/Azure/WALinuxAgent/issues/188), 

- Do a kernel version check and availability of /sys to validate flags are available
- If above check fails, use the current logic ( if iface == b'lo' or iface.startswith('lo:'): )

**Comment by hglkrijger** [comment]
this has been merged, closing the issue.
