### ISSUE TITLE
Cannot start waagent

### ISSUE THREAD

**Issue by francescouk** [Azure/WALinuxAgent#2126]
Hi there,

I would like to know if someone had the same issue I´m having:

```
WARNING Daemon Agent WALinuxAgent-2.2.45 launched with command 'python3 -u /usr/local/sbin/waagent -run-exthandlers' failed with exception: [Errno 2] No such file or directory: 'python3': 'python3'
```
Looks something easy to spot but for some reason I could not find a solution.

Running on freebsd
```
WALinuxAgent-2.2.45 running on freebsd 11.3
Python: 3.7.7
Goal state agent: 2.2.45
```

Thanks for the attention.

**Comment by narrieta** [comment]
It seems like your environment doesn't have a 'python3' link pointing to your python binary.

I'll close this issue since it is related to a specific environment, rather than to the agent itself.
