### ISSUE TITLE
RHEL and readme.md Supported Linux Distributions

### ISSUE THREAD

**Issue by CraigWiand** [Azure/WALinuxAgent#213]
While we understand that the agent supported list may be different than the [endorsed distros](http://support.microsoft.com/kb/2805216), Red Hat was tested and should appear in the [readme.md](https://github.com/Azure/WALinuxAgent/blob/master/README.md) Requirements>Supported Linux Distributions.  right?

**Comment by ahmetalpbalkan** [comment]
This is correct. Thanks for reporting.
