### ISSUE TITLE
[BUG] /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg claims to be provided by WALinuxAgent package but is not part of it

### ISSUE THREAD

**Issue by Klaas-** [Azure/WALinuxAgent#2139]
**Describe the bug: A clear and concise description of what the bug is.**
Hi,
on a recent RHEL Image the file /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg claims in header that is is provided by the WALinuxAgent package, but it is not.

```
$ cat /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg
# This configuration file is provided by the WALinuxAgent package.
[...]
$ rpm -qf /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg
file /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg is not owned by any package
```

This particular machine is RHEL 8.2 with the microsoft build image:
```
$ curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2020-09-01"| python3 -m json.tool
[...]
            "imageReference": {
                "id": "",
                "offer": "RHEL-SAP-APPS",
                "publisher": "RedHat",
                "sku": "8_2",
                "version": "latest"
[...]
```

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Red Hat Enterprise Linux release 8.2 (Ootpa)
 - WALinuxAgent version: 
```
WALinuxAgent-2.2.46 running on redhat 8.2
Python: 3.6.8
Goal state agent: 2.2.53
```

**Comment by Klaas-** [comment]
It's also the same on a current rhel 8.3 payg image.

**Comment by narrieta** [comment]
@trstringer - could you take a look? thanks!

**Comment by trstringer** [comment]
Thanks for bringing this to our attention! This will be fixed. Like you mentioned, this isn't part of walinuxagent so I will close this issue here.
