### ISSUE TITLE
VM Provisioning Fails using RHEL 8 image created using AIB

### ISSUE THREAD

**Issue by neleshgoel** [Azure/WALinuxAgent#2144]
RHEL 8.3 image is created using AIB (Marketplace Image with some customisation on top , mainly CIS Hardening - RHEL8 - https://github.com/ansible-lockdown/RHEL8-CIS).

VM provisioning fails with OS Provisioning for VM did not finish in the allotted time , Below warning / error is within the Serial log.

INFO Daemon Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1705 retries remaining, sleeping 1s]
WARNING Daemon cloud-init does not appear to be running

wagent is provisioned by default during the Invoke action by Azure Image Builder, default linux deprovision command/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync.

Any suggestions / comment will be helpful.

Regards,
Nelesh

**Comment by trstringer** [comment]
Can you specify exactly what the customization on top of the marketplace image is? Most likely that is causing some issue, and to further troubleshoot the exact problem it would be best if we knew the specifics. Thanks!

**Comment by neleshgoel** [comment]
> Can you specify exactly what the customization on top of the marketplace image is? Most likely that is causing some issue, and to further troubleshoot the exact problem it would be best if we knew the specifics. Thanks!

@trstringer  - RHEL 8 CIS Hardening is done on top of marketplace image.

"source": {
                    "type": "PlatformImage",
                    "publisher": "RedHat",
                    "offer": "RHEL",
                    "sku": "8-LVM",
                    "version": "8.3.2020111909"

Below are customizations
{
                    "type": "Shell",
                    "name": "Install Ansible",
                    "inline": [
                        "dnf install python3 -y",
                        "dnf install python3-pip -y",
                        "pip3 install ansible",
                        "alternatives --set python /usr/bin/python3"
                    ]
                },
                {
                    "type": "Shell",
                    "name": "Install Updates",
                    "inline": [
                        "sudo yum --security update -y"
                    ]
                },
                {
                    "type": "Shell",
                    "name": "Ansible Playbook Execution (https://github.com/ansible-lockdown/RHEL8-CIS)",
                    "inline": [
                        "/usr/local/bin/ansible-playbook -i localhost, --connection=local /tmp/cis/ansible/main.yml -vvv"
                    ]
                }

**Comment by anhvoms** [comment]
CIS hardening usually includes blacklisting/removing the UDF driver, which is required for provisioning Azure VMs. Please make sure kernel support for mounting UDF filesystem is enabled.

**Comment by neleshgoel** [comment]
> kernel support for mounting UDF filesystem is enabled.

As per the CIS guideline, it should be disabled, i have same for RHEL7 and i have no issue in there..
Below is the CIS guideline for reference
 name: "SCORED | 1.1.1.4 | PATCH | Ensure mounting of udf filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.4 | PATCH | Ensure mounting of udf filesystems is disable | Edit modprob config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install udf(\\s|$)"
            line: "install udf /bin/true"
            create: yes

      - name: "SCORED | 1.1.1.4 | PATCH | Ensure mounting of udf filesystems is disable | Disable udf"
        modprobe:
            name: udf
            state: absent
        when:
            - ansible_connection != 'docker'
  when:
      - rhel8cis_rule_1_1_1_4

**Comment by neleshgoel** [comment]
Issue is fixed after enabling UDF driver... Closing the issue
