### ISSUE TITLE
Consistency with uppercase and lowercase in the logs

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#2171]
Sure it is a detail but on UNIX derived systems case matters, it would be good if there could be some consistency.

Sometimes the word `version` is capitalized, sometimes not.

Also you could put `version` after Python so that one can simply grep the log for the word `version` and retrieve the versions of the various components, just an idea.

```
INFO Daemon Daemon Azure Linux Agent Version:2.2.47
INFO Daemon Daemon Python: 3.9.1
INFO Daemon Daemon Fabric preferred wire protocol version:2015-04-05
INFO Daemon Daemon Wire protocol version:2012-11-30
INFO Daemon Daemon Server preferred version:2015-04-05
```

**Comment by narrieta** [comment]
The different "version" strings come from difference sources, it would not be worth make them the same case since grep -i can handle the different cases. Thanks for reporting this.
