### ISSUE TITLE
Agent 2.1.3 and machine reboot

### ISSUE THREAD

**Issue by xpertkn** [Azure/WALinuxAgent#218]
We recently upgrade the agent from 2.0.19 to 2.1.3. A vm backup was initiated at around 13:00 server time and the machine was unexpectedly rebooted 9 hours later. Near the time the machine was rebooted, the following message was logged in waagent.log:

./waagent.log:2016/06/06 22:16:42 VMBackupForLinuxExtension started to handle.

Here is the machine's reboot time
reboot system boot 2.6.32-573.3.1.e Mon Jun 6 22:16 - 23:37 (01:20)

Is there any case when the agent would reboot a machine? The machine is running Oracle Linux 6.7.

**Comment by brendandixon** [comment]
@xpertkn The agent does not ever intentionally reboot the VM. The reboot must have occurred from other causes.

**Comment by ahmetalpbalkan** [comment]
@sopattna @andyliuliming Would VMBackup extension reboot a customer VM? (apologies if you are not the right person to contact)

**Comment by soumyanishan** [comment]
@ahmetalpbalkan , the VMBackup extension will never reboot the VM

**Comment by ahmetalpbalkan** [comment]
@xpertkn It appears like our components do not directly reboot the VMs. It might have been a host machine update or an intermittent outage caused your VM to reboot. You can contact the Azure Support and they will be able to tell your why your VM has gone down unexpectedly and came back. Sorry for the inconvenience.

**Comment by xpertkn** [comment]
Indeed, I have a case opened with azure and they confirmed the reboot was caused by a hardware issue. The waagent woke up after the machine experienced the event and "started to handle".
