### ISSUE TITLE
Agent should remove/update cloud-inits set-hostname on deprovision

### ISSUE THREAD

**Issue by TuxInvader** [Azure/WALinuxAgent#2184]
On Ubuntu 18.04-LTS, a custom image can not be deployed using the same hostname as used when building the image, because deprovision leaves `/var/lib/cloud/data/set-hostname` configured.

This results in cloud-init choosing not to set the hostname on startup, because it believes the hostname has already been set. In reality the deprovision action has set the hostname to localhost. See:

https://github.com/canonical/cloud-init/blob/695c4f8f46585dd7feac2fdc0729f410c539d3bc/cloudinit/config/cc_set_hostname.py#L80

The end result is the host will come up with the hostame localhost and register localhost.internal.cloudapp.net in DDNS. 

As a workaround I manually `rm` the file as the last step in my packer script.

```
 {
    "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
    "inline": [
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0",
      "rm /var/lib/cloud/data/set-hostname || echo 'no set-hostname file'",
      "sync; sync; sync"
    ],
    "inline_shebang": "/bin/sh -x",
    "type": "shell"
  }
```

_Originally posted by @TuxInvader in https://github.com/Azure/WALinuxAgent/issues/119#issuecomment-785994077_

**Comment by narrieta** [comment]
@trstringer - could you take a look? thanks

**Comment by trstringer** [comment]
Thanks for reporting this issue, @TuxInvader! It appears as though this is a potential issue with cloud-init, and I've created a [bug report (launchpad)](https://bugs.launchpad.net/cloud-init/+bug/1917681) to engage upstream with.

**Comment by trstringer** [comment]
Thanks again for raising this issue! Since this is not an issue with walinuxagent, I'm going to close this. Please follow the above launchpad bug report with cloud-init upstream to track the issue.
