### ISSUE TITLE
Suggested way to disable "systemd-resolve" in ubutu 18.04

### ISSUE THREAD

**Issue by t-bzhan** [Azure/WALinuxAgent#2221]
We've provisioned an Ubuntu machine to host our own DNS service. But It seems the port 53 is already occupied by "system-resolve".

After some searching on the internet. We disabled the "system-resolve" following below steps:

> systemctl disable systemd-resolved.service
> systemctl stop systemd-resolved
> rm /etc/resolv.conf

To make the DNS resolution works again, we recreate the /etc/resolv.conf with below content copied from one old machine:

> ; generated by /usr/sbin/dhclient-script
> search xxxxxxxxxxxxxxxxxxxxxxx
> nameserver 168.63.129.16

For now, the DNS resolution works on my machine, but I am not sure whether this is the suggested way to do that or not.

**Comment by narrieta** [comment]
@t-bzhan this question seems unrelated to WALinuxAgent, will close the issue. Sorry, I do not know the answer to your question.
