### ISSUE TITLE
Stateless VM re-provisioning fails due to missing ovf-env.xml DVD

### ISSUE THREAD

**Issue by tfrederick74656** [Azure/WALinuxAgent#2232]
Hello Azure team,

I suspect this might be a platform issue, and apologies in advance if so, but I figured I would start here.

I've created a **stateless** custom Linux image based on Alpine Linux 3.13 for use in Azure. It's stateless in that `/` is a tempfs and all partitions are mounted read-only. As such, no data is persisted between reboots and the VM must re-provision on each boot.

The image provisions perfectly on the initial boot, but fails to provision on subsequent boots because the DVD device containing the ovf-env.xml file is missing. At first, I suspected this was because waagent ejects the DVD in ([default/osutil.py:653](https://github.com/Azure/WALinuxAgent/blob/9906bc27e0e2ac84d6d8802e27ab5e435dae57dd/azurelinuxagent/common/osutil/default.py#L653)), however I patched this out and still found the DVD missing on subsequent boots. To confirm, I spun up several VMs from certified platform images and observed the same behavior -- the DVD device appears to be automatically removed a short time after provisioning. Based on that, I'm assuming this is an intentional process to avoid having an unnecessary SCSI device attached to every running Azure VM.

**Questions:**
- Am I correct in assuming that the provisioning DVD is automatically removed after some time?
- Is there a method by which to request the platform re-attach the provisioning DVD?
- Alternatively, is there a method to request the platform _not_ remove the provisioning DVD in the first place?

Presumably, there's some solution to this, since Azure officially supports ephemeral VMs in other sizes which (I assume) also need to re-provision on each boot. I was not able to find a good answer anywhere, however. If there's not a workaround, I can roll a custom provisioning agent using IMDS alone, but would prefer not to do that unless it's the only option.

Thank you again for any help you can provide, it's greatly appreciated!

**Comment by narrieta** [comment]
The DVD is mounted only at provisioning time and, I believe, it is not possible to mount it again, @trstringer may be able to confirm.

As far as all the partitions being read-only, once you get past the DVD issue, both the agent and vm extensions will malfunction if they can't write to /var.

**Comment by trstringer** [comment]
Thanks for opening this issue! That is correct, the DVD is removed and unable to be re-added. What exactly are you trying to do? You create an image and then your subsequent deployments are done in what way?

**Comment by tfrederick74656** [comment]
Thanks for the responses! In short, I'm trying to combine the functionality of a "reimage" with the supervised "rolling reboot" capability of a scale set. My end goal is to have a completely stateless deployment in VM scale sets. At boot, waagent handles setting hostname/user/SSH keys, and our application grabs a configuration file from blob storage.

If I need to update the application configuration, I can have a single custom script extension consisting of nothing more than `/bin/sh -c reboot`, which triggers a rolling reboot supervised by an LB probe. Since the VM is stateless, I never have to worry about configuration drift, since a reboot is essentially equivalent to a reimage.

**Comment by tfrederick74656** [comment]
Thanks for all the information. I'm closing this issue as it doesn't seem like there's presently a supported solution. In the meantime, I disabled provisioning in waagent (running as extension handler only) and threw a quick IMDS-based provisioner together. It's very rough but should work until I can write something more robust. Link to the code is below in case this helps anyone else.

https://gist.github.com/tfrederick74656/402ec20a42e00dad01b459712f042196
