### ISSUE TITLE
[2.1] Logs are not flushed to journald (python -u)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#224]
In ubuntu 16.04 `/lib/systemd/system/walinuxagent.service`:

```
...
[Service]
Type=simple
ExecStart=/usr/bin/python3  /usr/sbin/waagent -daemon
Restart=on-failure
...
```

when I start the agent (`systemctl restart walinuxagent.service`) and look at the logs (`journalctl -afu walinuxagent`) I only see:

```
Jun 08 18:22:09 u16 systemd[1]: Started Azure Linux Agent.
Jun 08 18:22:09 u16 systemd[1]: Stopped Azure Linux Agent.
```

and no logs from the agent.

This is because Python has buffered mode enabled by default and logs are not getting flushed (for quite a long time, like 50 lines of logs are not making it to the journal).

If I start `python3` with `python3 -u` everything works fine.

@szarkos can we communicate to distro owners using 2.1 + systemd to incorporate this unit file change?

**Comment by brendandixon** [comment]
@ahmetalpbalkan I wonder if we could disable it within the agent itself. Normally languages / frameworks allow such things.

**Comment by ahmetalpbalkan** [comment]
@brendandixon I don't see a need to do it in the agent when runtime provides the same option. Output buffering is not an agent concern; it is a runtime concern. The `-u` practice is pretty much applied everywhere running 12-factor services (logging to stdout) with python and a well adopted one.

**Comment by brendandixon** [comment]
@ahmetalpbalkan I agree, but we can change the agent more quickly than the corresponding unit.

**Comment by ahmetalpbalkan** [comment]
Tis is not a critical or a blocking issue, logs will get flushed eventually, especially when the agent crashes. We just need to communicate distro vendors to make the change.

**Comment by szarkos** [comment]
I can work with Dan to file the appropriate bugs for the init script update.

For most distros that use setup.py, I suspect that if you fix our systemd init files then they should get the update automatically when they update the agent package: https://github.com/Azure/WALinuxAgent/tree/master/init/.

**Comment by ahmetalpbalkan** [comment]
@szarkos hmm so the one checked in there has `ExecStart=/usr/sbin/waagent -daemon`

Among the distros that I know use systemd, briefly:

- **ubuntu 16.04**: the ExecStart of the systemd unit file here (`/usr/bin/python3 -u /usr/sbin/waagent -daemon`) does not match what we have checked in. I bet we have to let them know particularly
- **coreos**: still on waagent-2.0.16 (python 2.7.6). unit file does not have `-u` and even adding `-u` don't get thee logs flushed (I think this is sadly because 2.0 doesn't log to stdout for journald to collect). `/usr/share/oem/python/bin/python /usr/share/oem/bin/waagent -daemon`
- **debian 8**: same as coreos, running `waagent-2.0.16` with a different ExecStart: `/usr/bin/python /usr/sbin/waagent -daemon`

So it doesn't appear to me like anyone actually uses that file we checked in there... ExecStart is not the only different one, I see other variances in the unit files such as:

## Ubuntu 16.04
```
After=network-online.target cloud-final.service
Wants=network-online.target sshd.service sshd-keygen.service cloud-final.service
[...]
Restart=on-failure
```

## CoreOS

```
Wants=network-online.target sshd-keygen.service
After=network-online.target sshd-keygen.service

[...]
Restart=always
RestartSec=5s
```

## Debian

- ⚠️ ⚠️ ⚠️ ⚠️  Does not have `Restart=` clause 🔥🔥🔥 
- Has a `ConditionVirtualization=microsoft`
- Does not have the same `Wants`/`After` targets/services as Ubuntu


We should probably work on unifying them.

**Comment by ahmetalpbalkan** [comment]
fixed now
