### ISSUE TITLE
[BUG]  waagent-network-setup.service fails if /var is on a separate LVM volume

### ISSUE THREAD

**Issue by almalinux4all** [Azure/WALinuxAgent#2247]
If the `/var` partition is on a separate LVM volume, the `waagent-network-setup.service` is executed before the `/var` LVM volume is mounted. Therefore, the `waagent-network-setup.service` fails with the following error:

` python[595]: /usr/bin/python: can't open file '/var/lib/waagent/WALinuxAgent-2.2.54.2/bin/WALinuxAgent-2.2.54.2-py2.7.egg': [Errno 2] No such file or directory`

Currently I have noticed this in CentOS 7.9, with the following WALinuxAgent version installed: `WALinuxAgent-2.2.46-2.el7_9.noarch`

> waagent --version
WALinuxAgent-2.2.46 running on centos 7.9.2009
Python: 2.7.5
Goal state agent: 2.2.54.2

This is a portion of the `/var/log/waagent.log` that shows this issue as well:

> 2021-05-13T14:22:46.866204Z INFO ExtHandler ExtHandler Distro: centos-7.9.2009; OSUtil: RedhatOSUtil; AgentService: waagent; Python: 2.
7.5; systemd: True; LISDrivers: Absent; logrotate: ;
2021-05-13T14:22:46.868059Z INFO ExtHandler ExtHandler WALinuxAgent-2.2.54.2 running as process 1252
2021-05-13T14:22:46.870137Z INFO ExtHandler ExtHandler Cgroup monitoring is not supported on ['centos', '7.9.2009', 'Core', 'CentOS Linux']
2021-05-13T14:22:46.870713Z INFO ExtHandler ExtHandler Starting setup for Persistent firewall rules
2021-05-13T14:22:47.129887Z INFO ExtHandler ExtHandler Firewalld service not running/unavailable, trying to set up waagent-network-setup.service
2021-05-13T14:22:47.139972Z INFO ExtHandler ExtHandler Service: waagent-network-setup.service already enabled. No change needed.
2021-05-13T14:22:47.163120Z INFO ExtHandler ExtHandler Logs from the waagent-network-setup.service since system boot:
 -- Logs begin at Thu 2021-05-13 14:22:36 UTC, end at Thu 2021-05-13 14:22:47 UTC. --
May 13 14:22:40 centos-1 python[595]: /usr/bin/python: can't open file '/var/lib/waagent/WALinuxAgent-2.2.54.2/bin/WALinuxAgent-2.2.54.2-py2.7.egg': [Errno 2] No such file or directory
May 13 14:22:41 centos-1 systemd[1]: waagent-network-setup.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 13 14:22:41 centos-1 systemd[1]: Failed to start Setup network rules for WALinuxAgent.
May 13 14:22:41 centos-1 systemd[1]: Unit waagent-network-setup.service entered failed state.
May 13 14:22:41 centos-1 systemd[1]: waagent-network-setup.service failed.
2021-05-13T14:22:47.165043Z INFO ExtHandler ExtHandler Drop-in file /usr/lib/systemd/system/waagent-network-setup.service.d/10-environment.conf successfully updated
2021-05-13T14:22:47.165237Z INFO ExtHandler ExtHandler Persistent firewall rules setup successfully
2021-05-13T14:22:47.166384Z INFO ExtHandler ExtHandler Checking if log collection is allowed at this time [False]. All three conditions must be met: configuration enabled [False], systemd present [True], python supported: [True]
2021-05-13T14:22:47.167612Z INFO ExtHandler ExtHandler Start env monitor service.
2021-05-13T14:22:47.167786Z INFO ExtHandler ExtHandler Configure routes
2021-05-13T14:22:47.167959Z INFO MonitorHandler ExtHandler WireServer endpoint 168.63.129.16 read from file
2021-05-13T14:22:47.167894Z INFO ExtHandler ExtHandler Gateway:None
2021-05-13T14:22:47.168083Z INFO MonitorHandler ExtHandler Wire server endpoint:168.63.129.16
2021-05-13T14:22:47.168131Z INFO ExtHandler ExtHandler Routes:None
2021-05-13T14:22:47.168557Z INFO MonitorHandler ExtHandler Monitor.NetworkConfigurationChanges is disabled.

On the console, during the boot process, you can clearly see that `waagent-network-setup.service` is executed first, and then, later, the /var LVM volume is mounted:

> [  OK  ] Stopped plymouth-start.service.
[  OK  ] Started Read and set NIS domainname from /etc/sysconfig/network.
[  OK  ] Started Create list of required sta...ce nodes for the current kernel.
[FAILED] Failed to start Setup network rules for WALinuxAgent.
See 'systemctl status waagent-network-setup.service' for details.
[  OK  ] Started Remount Root and Kernel File Systems.
[  OK  ] Started Apply Kernel Variables.
[  OK  ] Started LVM2 metadata daemon.
         Starting udev Coldplug all Devices...
         Starting Configure read-only root support...
         Starting Create Static Device Nodes in /dev...
[  OK  ] Reached target Paths.
[  OK  ] Started Create Static Device Nodes in /dev.
[  OK  ] Started Configure read-only root support.
         Starting udev Kernel Device Manager...
[  OK  ] Started udev Coldplug all Devices.
[  OK  ] Started udev Kernel Device Manager.
[    6.945020] hv_vmbus: registering driver hv_balloon
[    6.949999] pps_core: LinuxPPS API ver. 1 registered
[    6.953698] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    6.953704] hv_balloon: Using Dynamic Memory protocol version 2.0
[    6.964661] sd 2:0:0:0: Attached scsi generic sg0 type 0
[    6.969108] sd 3:0:1:0: Attached scsi generic sg1 type 0
[    6.973048] sd 5:0:0:0: Attached scsi generic sg2 type 0
[    6.973126] hv_vmbus: registering driver hv_pci
[    6.973434] hv_pci 7217c097-9b23-4c29-be54-601fa9846b1e: PCI VMBus probing: Using version 0x10002
[    6.976037] hv_pci 7217c097-9b23-4c29-be54-601fa9846b1e: PCI host bridge to bus 9b23:00
[    6.976039] pci_bus 9b23:00: root bus resource [mem 0xfe0000000-0xfe00fffff window]
[    6.997522] sr 1:0:0:0: Attached scsi generic sg3 type 5
[    7.002614] PTP clock support registered
[    7.081697] hv_utils: Registering HyperV Utility Driver
[    7.087298] hv_vmbus: registering driver hv_util
[    7.095327] pci 9b23:00:02.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown speed x0 link at 9b23:00:02.0 (capable of 63.008 Gb/s with 8 GT/s x8 link)
[    7.109768] pci 9b23:00:02.0: BAR 0: assigned [mem 0xfe0000000-0xfe00fffff 64bit pref]
[  OK  ] Created slice system-lvm2\x2dpvscan.slice.
[    7.125291] hv_utils: Heartbeat IC version 3.0
[    7.128208] hv_utils: Shutdown IC version 3.0
[    7.131403] hv_utils: TimeSync IC version 4.0
         Starting LVM2 PV scan on device 8:3...
[    7.139367] piix4_smbus 0000:00:07.3: SMBus base address uninitialized - upgrade BIOS or use force_addr=0xaddr
[  OK  ] Found device Virtual_Disk centos-boot.
[    7.151645] input: PC Speaker as /devices/platform/pcspkr/input/input5
[  OK  ] Found device Virtual_Disk 1.
[  OK  ] Found device /dev/ttyS0.
[    7.165107] cryptd: max_cpu_qlen set to 1000
[    7.181759] AVX2 version of gcm_enc/dec engaged.
[    7.185661] AES CTR mode by8 optimization enabled
[    7.196358] alg: No test for __gcm-aes-aesni (__driver-gcm-aes-aesni)
[    7.203480] alg: No test for __generic-gcm-aes-aesni (__driver-generic-gcm-aes-aesni)
[  OK  ] Started Monitoring of LVM2 mirrors,...ng dmeventd or progress polling.
[  OK  ] Reached target Local File Systems (Pre).
         Mounting /boot...
         Starting File System Check on /dev/disk/cloud/azure_resource-part1...
[    7.276471] XFS (sda2): Mounting V5 Filesystem
[  OK  ] Found device /dev/mapper/centos-usr.
[  OK  ] Found device /dev/mapper/centos-tmp.
[  OK  ] Found device /dev/mapper/centos-var.
[  OK  ] Found device /dev/mapper/centos-home.
         Mounting /home...
         [    7.342375] XFS (dm-3): Mounting V5 Filesystem
Mounting /var...[    7.345021] XFS (dm-4): Mounting V5 Filesystem
[    7.355830] mlx5_core 9b23:00:02.0: firmware version: 14.25.8368
[    7.358568] XFS (dm-4): Ending clean mount
[    7.358709] XFS (dm-1): Mounting V5 Filesystem
[    7.366814] XFS (dm-3): Ending clean mount
         Mounting /tmp...
[  OK  ] Mounted /home.
[  OK  ] Mounted /var.
         Starting Flush Journal to Persistent Storage...

Please note that this does not happen during the first boot of a VM instance running the `WALinuxAgent-2.2.46-2.el7_9.noarch`. The VM is booting first without any issue, then the WALinuxAgent updates itself with latest version available... After this update, during the next reboot, this issue is happeining.

> 2021-05-13T14:14:23.705369Z INFO ExtHandler Agent WALinuxAgent-2.2.46 discovered update WALinuxAgent-2.2.54.2 -- exiting
2021-05-13T14:14:23.958390Z INFO Daemon Agent WALinuxAgent-2.2.46 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
2021-05-13T14:14:23.976972Z INFO Daemon Determined Agent WALinuxAgent-2.2.54.2 to be the latest agent
2021-05-13T14:14:24.113868Z INFO ExtHandler ExtHandler The agent will now check for updates and then will process extensions. Output to /dev/console will be suspended during those operations.

Having the /var partition on a separate LVM volume is quite a common setup, the reason being that keeping logs separated prevents the entire filesystem becoming full in case a lot of logs are generated...

**Comment by kevinclark19a** [comment]
Hi @almalinux4all, looking into this issue. Something you can do to fix this error manually in the meantime is to add a `RequiresMountsFor=/var` line in the `[Unit]` section of the `waagent-network-setup.service` file. You can find the path of this file with `systemctl status waagent-network-setup.service`, and it is likely to be `/usr/lib/systemd/system/waagent-network.setup.service`.

Note that this comes with a caviat that this file will be replaced on deprovision via a daemon (not goal state/extension) agent v2.2.54.2+.

**Comment by kevinclark19a** [comment]
Closing this issue for now.

**Comment by almalinux4all** [comment]
> 
> 
> Hi @almalinux4all, looking into this issue. Something you can do to fix this error manually in the meantime is to add a `RequiresMountsFor=/var` line in the `[Unit]` section of the `waagent-network-setup.service` file. You can find the path of this file with `systemctl status waagent-network-setup.service`, and it is likely to be `/usr/lib/systemd/system/waagent-network.setup.service`.
> 
> Note that this comes with a caviat that this file will be replaced on deprovision via a daemon (not goal state/extension) agent v2.2.54.2+.

Thanks for your feedback, that is exactly what we did. We also configured dnf to not allow the WALinuxAgent package to be updated...

Is there any plan to make this fix part of the main package?

**Comment by kevinclark19a** [comment]
@almalinux4all, we are not planning on adding any more dependencies on boot order as of today. We may consider it when we remove our hardcoded dependency on /var, but there is no timeline for that.

**Comment by brianandrus** [comment]
This is terrible. 
I have found that ANY nfs mount in /etc/fstab will cause waagent-network-setup to hang indefinitely on boot.
If disable the service, things work, but waagent seems to re-enable it every time, so doing 'reboot' will always result in a hung vm
