### ISSUE TITLE
[INFO] Any reason why AutoUpdate.Enabled is N on SUSE images?

### ISSUE THREAD

**Issue by 1lomeno3** [Azure/WALinuxAgent#2274]
Just a question why AutoUpdate.Enabled parameter is disabled on SUSE images? Is there any reason why it should be kept like this or can we enable automatic update?

Thank you!
Jan

**Comment by narrieta** [comment]
I believe that was a contribution/suggestion from SUSE a long time ago and it has stayed like that over time. We do recommend enabling AutoUpdate.
