### ISSUE TITLE
SSH host key regeneration in provisioning doesn't skip enough

### ISSUE THREAD

**Issue by nathanleclaire** [Azure/WALinuxAgent#231]
In here: https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/distro/default/provision.py#L78 you see that generating a new SSH keypair for the host will be skipped if the config option to do so is set.  But, it assumes that a keypair is present there to read from.  If one is not present, this code will fail.

__Expected__: It should skip the thumbprint return if the keypair does not exist OR, go ahead with regenerating anyway in spite of the config option (since no existing keys are present to be over-written).

**Comment by hglkrijger** [comment]
@nathanleclaire, the original location from above is no longer visible, but #357 could be related. Does this address the issue?

**Comment by nathanleclaire** [comment]
hm I'm not sure I think I have worked around it in my case so I'll close
