### ISSUE TITLE
ModuleNotFoundError: No module named 'azurelinuxagent' in SLES 15 SP1 - Backup is failing due to this azure linux agent issue

### ISSUE THREAD

**Issue by pavanchvk** [Azure/WALinuxAgent#2310]
I have two python(python2.7.18 and python3.6.12) versions installed in SLES 15 SP1 OS.

I have tried uninstalled and reinstalled the agent. That didnt work.
Tried pointing the python in waagent.service unit file to /usr/bin/python instead of /usr/bin/python3 and in /usr/sbin/waagent file changed she bang to #!/usr/bin/env python. Nothing worked.

Per log it says: 
==========================================
2021-07-19T14:41:39.830627+00:00  python3[14949]:   File "/usr/sbin/waagent", line 35, in <module>
2021-07-19T14:41:39.830753+00:00  python3[14949]:     import azurelinuxagent.agent as agent
2021-07-19T14:41:39.830870+00:00  python3[14949]: ModuleNotFoundError: No module named 'azurelinuxagent'
==========================================
![image](https://user-images.githubusercontent.com/87658368/126193317-05c9e6f4-ce97-4d4b-95ee-e46bbdb32e6c.png)

![image](https://user-images.githubusercontent.com/87658368/126193576-e60bf96c-7287-450b-aeda-b97140b5fd32.png)

**Comment by narrieta** [comment]
@pavanchvk this seems particular to your installation, I am closing it for now, but if you have a repro using a marketplace image please do re-open this issue. Thanks
