### ISSUE TITLE
The specified blob does not exist.

### ISSUE THREAD

**Issue by sanjaikumarkhola** [Azure/WALinuxAgent#2311]
Hi All,

I am getting the Below Error while trying to SetMetadata into azure Blob, Could someone help me into this ?

The specified blob does not exist.
RequestId:2c5cb273-801e-0012-38c1-7c2e2d000000
Time:2021-07-19T17:13:46.8208200Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:2c5cb273-801e-0012-38c1-7c2e2d000000
Time:2021-07-19T17:13:46.8208200Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 2c5cb273-801e-0012-38c1-7c2e2d000000
x-ms-client-request-id: 16235613-6776-48be-a7b4-923871ef3a36
x-ms-version: 2020-08-04
x-ms-error-code: BlobNotFound
Date: Mon, 19 Jul 2021 17:13:46 GMT
Content-Length: 215
Content-Type: application/xml

**Comment by narrieta** [comment]
@sanjaikumarkhola your question seems unrelated to the Linux Agent, closing for now
