### ISSUE TITLE
waagent failing with custom-script-extension: Text file busy

### ISSUE THREAD

**Issue by jpveritone** [Azure/WALinuxAgent#2320]
I'm running an azure govcloud environment with many VMSS using the CIS RHEL 7.9 image. About 70% of the time my extension scripts fail to run and looking in /var/log/waagent.log see the error
`The handler for VM extension type 'Microsoft.Azure.Extensions.CustomScript' has reported terminal failure for VM extension 'fastcore-proxy-MSILinuxExtension1' with error message: '[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.7/bin/custom-script-shim install [stdout] + /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.7/bin/custom-script-extension install /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.7/bin/custom-script-shim: line 77: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.7/bin/custom-script-extension: Text file busy [stderr] '. 'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot'`

Googling for answers I found many experiencing same issue on CentOS. The microsoft repo (rhui-1.microsoft.com) I'm using is allowing me to only set version `2.2.46`. 

Is there a known version of waagent that fixes this problem on RHEL 7.9 and if so any documentation on how I could install that particular version?

**Comment by narrieta** [comment]
@jpveritone you log snippet shows that the error is in the extension, Could you open an issue in https://github.com/Azure/custom-script-extension-linux? I'll close this one.

**Comment by jpveritone** [comment]
done.. https://github.com/Azure/custom-script-extension-linux/issues/188
