### ISSUE TITLE
[2.1] get_protocol vs get_protocol_by_file

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#233]
In the daemon code [there is a `clear_protocol` call](https://github.com/Azure/WALinuxAgent/blob/e877916550b8634ff3bc406362d4e8c18c32a311/azurelinuxagent/daemon/main.py#L107) which just [deletes a file called `Protocol`](https://github.com/Azure/WALinuxAgent/blob/e877916550b8634ff3bc406362d4e8c18c32a311/azurelinuxagent/common/protocol/util.py#L209-L222). (stores either `WireProtocol` or `MetadataProtocol`).

Then the [`get_protocol`](https://github.com/Azure/WALinuxAgent/blob/e877916550b8634ff3bc406362d4e8c18c32a311/azurelinuxagent/common/protocol/util.py#L223-L249) and [`get_protocol_by_file`](https://github.com/Azure/WALinuxAgent/blob/e877916550b8634ff3bc406362d4e8c18c32a311/azurelinuxagent/common/protocol/util.py#L252-L284) refer to this file to pick the protocol.

I guess my question is
- if this is a cache, why are we [clearing](https://github.com/Azure/WALinuxAgent/blob/e877916550b8634ff3bc406362d4e8c18c32a311/azurelinuxagent/daemon/main.py#L107) it everytime agent restarts?
- why is this on a file; and not an in-memory variable?
- why does only [provisioning code use `get_protocol_by_file`](https://github.com/Azure/WALinuxAgent/blob/e877916550b8634ff3bc406362d4e8c18c32a311/azurelinuxagent/pa/provision/default.py#L61) and in 8 other places still use `get_protocol`?

😕

**Comment by brendandixon** [comment]
@ahmetalpbalkan All likely remnants of the on-prem work being new. I do not know if an existing VHD image can be moved between cloud and on-prem. If so, it may be possible for it begin in one place then be rebooted in another. That would explain the conservative approach, though a file, in that case, is overkill *except* for its diagnostic advantage. And yes, our calls should be consistent: There should be just one call and *it* should figure out what to do.
