### ISSUE TITLE
WAAGENT not updating hostname in DNS on CentOS 7.9

### ISSUE THREAD

**Issue by devszr** [Azure/WALinuxAgent#2331]
When a new VM is created from a captured image, waagent doesn't seem to correctly set the VM hostname in Azure DNS. 

Versions:
*waagent*
WALinuxAgent-2.3.1.1 (installed by auto-update)
*OS*
CentOS 7.9
*Cloud-init version:*
Name        : cloud-init
Arch        : x86_64
Version     : 19.4
Release     : 7.el7.centos.3

Additional description:

Once a VM from a captured image is deployed on Azure, the hostname on the VM itself is set correctly, however, trying to resolve the VM's hostname from another VM on the same VNET does not work. On the deployed VM itself, running *hostname* displays the correct name, cloud-init's config file has the correct VM name and waagent's published-hostname file under /var/lib/waagent is also correct. However, if one pings the VM name from the VM itself, we get a response from locahost. 

Example below:

`[root@testfx4 ~]# ping testfx4`
`PING testfx4 (10.1.0.11) 56(84) bytes of data.`
`64 bytes from localhost.internal.cloudapp.net (10.1.0.11): icmp_seq=1 ttl=64 time=0.036 ms`
`64 bytes from localhost.internal.cloudapp.net (10.1.0.11): icmp_seq=2 ttl=64 time=0.045 ms`

Now, if we force a VM name change using the *hostname* command, waagent correctly detects the hostname has changed and updates the DNS records correctly. We have not seen this behavior on CentOS 7.7.

Is this a bug or a mis-config or our side, or, is it expected behavior?

Thanks.

**Comment by narrieta** [comment]
@anhvoms could you take a look? thanks

**Comment by narrieta** [comment]
@anhvoms could you take a look? thanks

**Comment by narrieta** [comment]
Thanks @FladoToo. This was fixed by #1951, and the issue should be resolved once the SUSE images are updated
