### ISSUE TITLE
Freebsd 12 mount issue.. 

### ISSUE THREAD

**Issue by cjhoon1014** [Azure/WALinuxAgent#2333]
I try to install opnsense on freebsd 12 image. 
so i try to install freebsd 12 with ms azure marketplace freebsd 12 image.
and then install opnsense after then, deprovisioning and capture image and create new vm with capture image. 
but i found deploy error message how to solve this? 

=====================

{
  "code": "DeploymentFailed",
  "message": "하나 이상의 리소스 배포 작업에 실패했습니다. 자세한 내용을 보려면 배포 작업을 나열하세요. 사용 정보는 https://aka.ms/DeployOperations를 참조하세요.",
  "details": [
    {
      "code": "OSProvisioningInternalError",
      "message": "내부 오류 [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to mount dvd device\nInner error: [mount -o ro -t udf,iso9660 /dev/cd0 /mnt/cdrom/secure] returned 1: mount_udf: /dev/cd0: Device not configured\n.(으)로 인해 VM 'opnsenseroot1'에 대한 OS 프로비전 실패"
    }
  ]
}

**Comment by narrieta** [comment]
@anhvoms - could you take a look? thanks

**Comment by g-psantos** [comment]
@cjhoon1014 Were you able to figure this out?

**Comment by anhvoms** [comment]
We have limited support for freebsd. Please file an azure support ticket for production issues related to walinuxagent provisioning on freebsd
