### ISSUE TITLE
[Question] Change in behavior of reporting VM ID / VM UUID in Linux Agent?

### ISSUE THREAD

**Issue by stowen-msft** [Azure/WALinuxAgent#2410]
Hi!  

  I have an Azure Service which needs to retrieve information about Linux VMs in Azure.  

  When we gathered the VM ID field from Azure Linux VMs and noticed that previously, the VM'd ID field, shown as `properties.vmId` in InstanceView, was reported in reverse, with a different endianness than we would see on the VM.  

  For instance, we'd run `dmidecode` on an Azure Linux VM and see a UUID of 
  
  `Linux VM DMIDecode from the VM`
        `e69f2d51-e308-4440-9990-b202f5527013`.   
  
  However the VM in Azure would report a UUID of 
  `512D9FE6-08E3-4044-9990-B202F5527013`
  
  **Recently we have noticed** that this behavior has changed and now the VM uuid is correctly reported.  I would love whatever info you can offer as to when this happened so we will know if most Linux VMs going forward will be reporting their ID's in little or big endianness.

**Comment by narrieta** [comment]
@stowen-msft given the internal email thread on this subject, this is unrelated to the linux agent. closing this issue.
