### ISSUE TITLE
[BUG] Waagent does not shut down when it detects that it is not running in Azure

### ISSUE THREAD

**Issue by GurliGebis** [Azure/WALinuxAgent#2423]
**Describe the bug: A clear and concise description of what the bug is.**

When running a VM locally in Hyper-V where the waagent service is installed, it keeps trying to connect to the Azure backend.
Instead, it should detect that it is not running in Azure, and shut down.

Note: Please add some context which would help us understand the problem better
The easy way to reproduce it is to install TrueNAS on a local Hyper-V VM, update the waagent to the deb package attached the downstream ticket (https://jira.ixsystems.com/browse/NAS-112773)
Then watch as it keeps trying to connect to the Azure backend, even though it is not running in Azure.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: TrueNAS Scale RC2
 - WALinuxAgent version 2.4.0.2

**Additional context**
I started by creating a ticket with more info on the bug at ixSystems, since the problem occurs on their TrueNAS Scale distro.
https://jira.ixsystems.com/browse/NAS-112773
It has more info and screenshot showing the error - please note the NewError.png, since that is the one relevant.

**Log file attached**
Not able to get the logfile, but I have attached screenshots of the issue to the ticket created with ixSystems.

Is there a way for the agent to detect if running in Azure, or should it only be installed when running in Azure?

**Comment by sonicaj** [comment]
To clarify TrueNAS Scale is based off on debian bullseye stable. The same should be easily reproducible on a standard debian bullseye stable installation.

**Comment by narrieta** [comment]
@GurliGebis 

`Is there a way for the agent to detect if running in Azure, or should it only be installed when running in Azure?`

It should only be installed on Azure VMs, or it should be disabled on non-Azure VMs.
