### ISSUE TITLE
mount -v /dev/sr0 /mnt/cdrom/secure failed

### ISSUE THREAD

**Issue by imduffy15** [Azure/WALinuxAgent#246]
Hi all,

I'm seeing the mount of the VMM drive fail due to a no filesystem type being specified.

I'm running on CentOS 6.8

Just out of curiosity is there reasoning behind not specifying -t iso9660?

**Comment by ahmetalpbalkan** [comment]
@imduffy15 Are you using a customized image? I remember this was there in the past, perhaps it got removed for some reason.

Can you please paste the `/var/log/waagent.log`?

**Comment by imduffy15** [comment]
Hi,

I am indeed using a custom built image. I'm running version 2.0.18.

Just after spotting the issue, the image is CIS hardened so the UDF module
is disabled from loading thus causing CD mount errors.

Rebuilding as we speak with this module enabled... Will keep you posted.

**Comment by jasonzio** [comment]
Is there a traceback or error message you can show us? It may be possible for a future agent to detect this configuration problem and report it in a more useful and transparent way.

**Comment by imduffy15** [comment]
Sure @jasonzio no problem at all. Just wanted to confirm my thoughts detailed above. Turns out they were correct.

So lets sum this up:

Given a CentOS 6.8 image installed with WaLinuxAgent 2.0.18 with the UDF kernel module disabled by running the following `echo "install udf /bin/true" > /etc/modprobe.d/udf.conf` as per http://www.scaprepo.com/view.jsp?id=CCE-26677-5 causes the WaLinuxAgent to fail to pass its checks due to being unable to mount sr0 with the following logs:

```
2016/06/17 23:27:32 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:27:32 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:27:32 ERROR:CalledProcessError.  Command result was mount: unknown filesystem type 'udf'
2016/06/17 23:27:32 mount: unknown filesystem type 'udf'
2016/06/17 23:27:32 mount failed on attempt #1
2016/06/17 23:27:32 mount loop sleeping 5...
2016/06/17 23:27:37 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:27:37 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:27:37 ERROR:CalledProcessError.  Command result was mount: unknown filesystem type 'udf'
2016/06/17 23:27:37 mount: unknown filesystem type 'udf'
2016/06/17 23:27:37 mount failed on attempt #2
2016/06/17 23:27:37 mount loop sleeping 5...
2016/06/17 23:27:42 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:27:42 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:27:42 ERROR:CalledProcessError.  Command result was mount: unknown filesystem type 'udf'
2016/06/17 23:27:42 mount: unknown filesystem type 'udf'
2016/06/17 23:27:42 mount failed on attempt #3
2016/06/17 23:27:42 mount loop sleeping 5...
2016/06/17 23:27:47 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:27:47 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:27:47 ERROR:CalledProcessError.  Command result was mount: unknown filesystem type 'udf'
2016/06/17 23:27:47 mount: unknown filesystem type 'udf'
2016/06/17 23:27:47 mount failed on attempt #4
2016/06/17 23:27:47 mount loop sleeping 5...
2016/06/17 23:27:52 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:27:53 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:27:53 ERROR:CalledProcessError.  Command result was mount: unknown filesystem type 'udf'
2016/06/17 23:27:53 mount: unknown filesystem type 'udf'
2016/06/17 23:27:53 mount failed on attempt #5
2016/06/17 23:27:53 mount loop sleeping 5...
2016/06/17 23:27:58 ERROR:Unable to provision: Missing ovf-env.xml on DVD.
2016/06/17 23:27:58 Posted Role Properties. CertificateThumbprint=227b4536e37e85cc7ba16416bf31e055
2016106/17 23:28:01 Finished processing ExtensionsConfig.xml
2016/06/17 23:28:01 Successfully reported handler status
2016/06/17 23:28:23 Retrieved GoalState from Azure Fabric.
2016/06/17 23:28:23 ExpectedState: Started
2016/06/17 23:28:23 RoleInstanceId: b8bc40ad-ec18-4c60-81d4-e95eb827d798._vm5740812
2016/06/17 23:28:24 Private key with thumbprint: C89CE9EC9CB08DEA291532B0505A8326AB96AAA6 was retrieved.
2016/06/17 23:28:24 Public cert with thumbprint: C89CE9EC9CB08DEA291532B0505A8326AB96AAA6 was retrieved.
2016/06/17 23:28:24 Provisioning image started.
016/06/17 23:28:29 ERROR:CalledProce016/06/17 23:28:29 ERROR:CalledProcessError.  Error Code is 1
2016/06/17 23:28:29 ERROR:CalledProcessError.  Command string was LC_ALL=C fdisk -l /dev/sr0 | grep Disk
2016/06/17 23:28:29 ERROR:CalledProcessError.  Command result was 
2016/06/17 23:28:29 Module /lib/modules/2.6.32-642.1.1.el6.centos.plus.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2016/06/17 23:28:44 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:28:44 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:28:44 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2016/06/17 23:28:44 mount: you must specify the filesystem type
2016/06/17 23:28:44 mount failed on attempt #1
2016/06/17 23:28:44 mount loop sleeping 5...
2016/06/17 23:29:04 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:29:04 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:29:04 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2016/06/17 23:29:04 mount: you must specify the filesystem type
2016/06/17 23:29:04 mount failed on attempt #2
2016/06/17 23:29:04 mount loop sleeping 5...
2016/06/17 23:29:24 ERROR:CalledProcessError.  Error Code is 32
2016/06/17 23:29:24 ERROR:CalledProcessError.  Command string was mount /dev/sr0 /mnt/cdrom/secure
2016/06/17 23:29:24 ERROR:CalledProcessError.  Command result was mount: you must specify the filesystem type
2016/06/17 23:29:24 mount: you must specify the filesystem type
2016/06/17 23:29:24 mount failed on attempt #3
2016/06/17 23:29:24 mount loop sleeping 5...
```

Thanks for the fast responses and your help on this. I hope the above information is enough to satisfy any concerns you may have. If your happy with the information provided please go ahead and close this ticket, if there is anything else I can give you let me know :)

**Comment by ahmetalpbalkan** [comment]
I remember we used to specify `-t iso9660` in v2.0 branch at some point. I wonder what happened to it though...

**Comment by ahmetalpbalkan** [comment]
It looks like this is in place on v2.1 tip (`develop` branch). We mount the cdrom with `-o ro -t iso9660,udf`.

**Comment by brendandixon** [comment]
@kmongwa The agent does not mount a "physical" CDROM; it is a virtual CDROM provided by the hypervisor. It contains information needed to provision the VM. The agent supports, not only VMs in Azure, but also images running within Microsoft System Center. The latter is what adds the UDF, in addition to ISO9660, requirement.

Is your concern that the agent attempts *both* UDF and ISO9660 or that it is attempting to mount the CDROM at all?

**Comment by kmongwa** [comment]
Thank you for the explanation about why the virtual CDROM device is needed.  I am really not concerned about that, but rather that I still can't provision from a hardened image which has UDF disabled.  Enabling UDF (removing it from the hardening process) of course works, but I'd hate to present that to the security team as a workaround.  The updated mount line as you mentioned is supposed to try both UDF and ISO9660, but for some reason, it is not working.  ISO9660 is enabled in the image.  It is listed in /etc/filesystems, and I can successfully mount ISO files specifying `-t iso9660 -o loop`.

**Comment by jerrish** [comment]
I am facing a similar issue while trying to migrate a custom VM (RedHat) to azure. Everytime we could see the following in the serial logs.

======================== 
2016/10/24 21:18:17.580149 INFO OS: redhat 7.0
2016/10/24 21:18:17.582578 INFO Python: 2.7.5
2016/10/24 21:18:17.585192 INFO Run daemon
2016/10/24 21:18:17.587806 INFO Run provision handler.
2016/10/24 21:18:17.590648 INFO Copy ovf-env.xml.
2016/10/24 21:18:18.077116 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2016/10/24 21:18:18.082710 ERROR Error Code:32
2016/10/24 21:18:18.086093 ERROR Result:mount: unknown filesystem type '(null)'

2016/10/24 21:18:18.091759 WARNING Mount dvd failed: retry=0, ret=32
0016/10/24 21:18:23.248057 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2016/10/24 21:18:23.255966 ERROR Error Code:32
2016/10/24 21:18:23.259505 ERROR Result:mount: unknown filesystem type '(null)'
=========================== 

How can we address this while we prepare the VM for migration?

**Comment by brendandixon** [comment]
@jerrish The agent needs to mount a faux DVD to obtain the Xml file containing provisioning data. The mount is failing because, since you are using a custom image, there is no provisioning data. You can circumvent this by setting Provisioning.Enabled to "n" in /etc/waagent.conf.

I hope this helps!

**Comment by imjoseangel** [comment]
Just for your info. We are using the [devsec](https://github.com/dev-sec/ansible-os-hardening) project and disabling **UDF** has done the job.

**Comment by msLinuxNinja** [comment]
@imjoseangel In my case was the other way around, udf module was blacklisted on /etc/modprobe.d/ through the install udf /bin/true. Removing the entry allowed the DVD to mount and provision the VM.
Note that some people blacklist udf as a hardening measure as it is considered an uncommon filesystem.

**Comment by kbinghamnetfoundry** [comment]
This is still a problem. The agent attempts to mount with UDF which is intentionally disabled to conform with CIS hardening guidance. Our custom image upstream is CentOS 7.6 offered by OpenLogic in Azure Marketplace. The result is that a VM can be created, but cloud-init fails because it depends upon the ovf-env.xml file provided by the first-boot (per-instance) mount.

**Comment by philwinder** [comment]
In addition to @imjoseangel and like @kbinghamnetfoundry, I'm using both dev-sec and CIS. This is my workaround.

With an `ansible-galaxy` `requirements.yaml` of:
```yaml
- src: https://github.com/MindPointGroup/RHEL7-CIS.git
- src: https://github.com/dev-sec/ansible-os-hardening.git
```

You will need a top level `playbook.yaml` of:
```yaml
---
- hosts: all
  roles:
    - role: RHEL7-CIS
      vars:
        - rhel7cis_rule_1_1_1_7: false # Required so the azure waagent can mount init scripts
    - role: ansible-os-hardening
      vars:
        - os_filesystem_whitelist: ["udf"] # Required so the azure waagent can mount init scripts
```

**Comment by jasonzio** [comment]
There are no plans to remove the requirement for UDF at initial provisioning to enable the Azure control plane to provide provisioning information to the VM. Once initial provisioning is complete, the UDF driver is no longer required; the ovf-env.xml file, initially obtained from the mounted volume, is redacted and cached in /var/lib/waagent.
