### ISSUE TITLE
WaLinuxAgent vs Cloud-init

### ISSUE THREAD

**Issue by imduffy15** [Azure/WALinuxAgent#249]
Hi All,

Question rather than issue here just out of curiosity. 

Why does this project exist over using a pre-existing solution like cloud-init and making the azure platform suit such metadata standards or adding an extra data source provider to cloud-init?

It seems to be the standard followed by most other cloud platforms (AWS, GCE, OpenStack, CloudStack, etc.).

I'm interested to know the rational behind such a project and why this approach was taken when a lot of the work (password setting, hosting name setting, user data executing, provisioner bootstrapping, ssh key injection, etc.) is already done by a popular solution.

Thanks,
Ian.

**Comment by brendandixon** [comment]
@imduffy15 Good, sensible question. Much has changed since we began offering Linux in Azure. In the beginning, and even now to an extent, clean, cross-distro solutions did not exist we could use in Azure. Already, however, in our popular distributions, such Ubuntu, cloud-init is used; the code in the agent is skipped. I can envision such occurring more and more, with the agent evolving into a role to manage extensions and other, post-setup, state only.

**Comment by imduffy15** [comment]
Hi @brendandixon 

Thank you for your response - let me give you some context from where this question came from. I'm currently working with a client on an evaluation of Azure and AWS for their public cloud solution. One of the main criteria is that custom hardened linux machine image is upload and utilised for all VMs. In an ideal world, this machine image would be identical as much as possible to the bare-mental, ESXi and private cloud images. In the AWS context an extra agent has not been required as cloud-init is already part of the machine image and utilised by many different datasources (ConfigDrive, Openstack EC2 metadata service, NoCloud, None, etc.). Given the azure context WaLinuxAgent is an extra dependency and slight divergence that makes a fair amount  of system changes.

Would it be possible for your to share some documentation around the necessary configuration for cloud-init to work on a Ubuntu VM and lessen the requirement for WaLinuxAgent? I would be very interested if this was something that is achievable.

What is the maturity and utilisation of Linux with the WaLinuxAgent like on Azure today? What is the release and test life cycle like for WaLinuxAgent? It concerns me that it plays a core role around instance proviosning and the issue log appears to have at least one regression issue (#248).

**Comment by brendandixon** [comment]
@imduffy15 I appreciate what you're trying to achieve. Azure, in some ways, offers features not immediately present with AWS / GCE (e.g., our extensions) that have proven popular with our customers. Having said that, I agree that an "agent-less" solution would be a good option to have, but we're not there (yet). I cannot, at this time, make commitments about when we might achieve such, but improving provisioning, extension management, and the general experience of Linux on Azure is **all**, as Principle on my team, I think about.

Regarding the regression: The agent was recently refactored. The developers lost a couple of things in that process, but we're actively addressing those issues and hardening the agent. However, regressions are possible in any environment; they are not unique to our model.

When comparing platforms, I believe it is important to evaluate, not how similar they are, but the value each provides to the customer, even if they do so using different mechanisms. It makes sense that, if things were similar, comparison is easier, but, then, in that case, true differentiation and additional value is harder. A platform is never improved by copying what someone else has done.

**Comment by imduffy15** [comment]
Thank you for all the information @brendandixon
I look forward to exploring the azure platform more and seeing what it has to offer :)
