### ISSUE TITLE
Failure in RPM Build

### ISSUE THREAD

**Issue by sabman3** [Azure/WALinuxAgent#2568]
On RHEL 8 during RPM build an error occurs because "/usr/lib/rpm/redhat/brp-mangle-shebangs" requires that /bin/waagent and /bin/waagent2.0 require the specific python version for the shebang line. So instead of "#!/usr/bin/env python" it should be "#!/usr/bin/env python2".  The change to the shebang should be backwards compatible to RHEL 7, since that version if the OS recognizes python2 as a valid interpreter (Not tested).  I can branch and then do a pull request if you want.

**Comment by sabman3** [comment]
Okay. Actually just tested the RPM I created on RHEL 8 and using python2 in the shebang forces it to have a dependency on python2. I redid the RPM using python3 in the shebang an all worked well. Now I don't know if the problem is with Red Hats rpmbuild package and /usr/lib/rpm/redhat/brp-mangle-shebangs, or with python ez_setup. Maybe someone else has input into this issue.

**Comment by narrieta** [comment]
@sabman3 sorry, i did not quite get what the issue is. 

As a note, we are using now bin/py3/waagent for distros in which only Python 3 is installed
