### ISSUE TITLE
[BUG] Systemd services aren't created after installation for DEBIAN machines with python3

### ISSUE THREAD

**Issue by thedarksage** [Azure/WALinuxAgent#2573]
setup.py script tries to create systemd service after copying packages for DEBIAN, for which it has a check at line 220

```
if debian_has_systemd():
            set_systemd_files(data_files, dest=systemd_dir_path)
```

```
def debian_has_systemd():
    try:
        return subprocess.check_output(
            ['cat', '/proc/1/comm']).strip() == 'systemd'
    except subprocess.CalledProcessError:
        return False
```

The function return type is different for python3 and python (b'systemd' and 'systemd') , hence the check fails, causing setup to wrongly assume systemd is absent, t therefore the guest agent service is not created.

![image](https://user-images.githubusercontent.com/22216432/165859726-17e6f58a-1ca7-4a7b-ae60-c198f938eac6.png)

**Comment by nagworld9** [comment]
Fixed the issue.
