### ISSUE TITLE
Support for Rocky Linux and/or Alma Linux?

### ISSUE THREAD

**Issue by pmdci** [Azure/WALinuxAgent#2588]
Due to CentOS changing to Stream, alternatives like Rocky Linux and Alma Linux have been introduced. Any chance we can get the WA Linux Agent to work with Rocky Linux and/or Alma Linux?

**Comment by narrieta** [comment]
@pmdci We already have internal work items to add Rocky Linux and Alma, but presently we are working on another features, so we do not have an ETA. I'll post any updates here.

**Comment by almalinux4all** [comment]
+1 for the AlmaLinux and Rocky Linux support.

**Comment by jameswmcnab** [comment]
Are there any updates on this?

AlmaLinux and Rocky Linux have packages for the agent, but I assume this remains unsupported to date?

**Comment by narrieta** [comment]
We'll get to this work item within a few weeks. In the meanwhile, have you tried to execute any VM extensions on AlmaLinux or Rocky? If you do, please post any errors you may get here, it will help to scope the work that needs to be done.

**Comment by jameswmcnab** [comment]
> We'll get to this work item within a few weeks. In the meanwhile, have you tried to execute any VM extensions on AlmaLinux or Rocky? If you do, please post any errors you may get here, it will help to scope the work that needs to be done.

Is there an update on this work after 2 months?

Rocky Linux and AlmaLinux are both very popular and important distributions, so the lack of focus here is a bit confusing.

**Comment by narrieta** [comment]
@jameswmcnab @supershal I'm closing this issue since the WaLinuxAgent now supports both Alma and Rocky and they have been added to the test automation (fixed by #2796)

@supershal I'll try to investigate who is responsible for the rpm packages and post here. The WALinuxAgent team does not create those packages,
