### ISSUE TITLE
[2.1] journald logs incomplete

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#260]
```
  ├─python -u /usr/sbin/waagent -daemon
  │   ├─python /usr/sbin/waagent run-exthandlers
```

Ever since we split the agent into this model, only the logs from the parent process shows up in the journald logs. However /var/log/waagent.log is complete. It might be a bad exec where we perhaps don't pass the stdout/stderr pipe correctly.

OR maybe it's just a missing `-u` again...

**Comment by brendandixon** [comment]
@ahmetalpbalkan Good catch! I simply passed /dev/null to the child. I can fix that quickly.

**Comment by ahmetalpbalkan** [comment]
@brendandixon hmm this fix didn't really fix the situation here. It's puzzling as I see that the child project gets the same fds for stdout/stderr; but `journalctl -u waagent` logs are only from the parent.

```
$ pstree -a -p 1920
python,1920 -u /usr/sbin/waagent -daemon
  ├─python,1934 /usr/sbin/waagent run-exthandlers
  ├─{python},1924
  └─{python},1933

$ ls -al /proc/1920/fd
total 0
dr-x------. 2 root root  0 Jun 25 05:14 .
dr-xr-xr-x. 8 root root  0 Jun 25 05:14 ..
lr-x------. 1 root root 64 Jun 25 05:14 0 -> /dev/null
lrwx------. 1 root root 64 Jun 25 05:14 1 -> socket:[23851]
lrwx------. 1 root root 64 Jun 25 05:14 2 -> socket:[23851]

$ ls -al /proc/1934/fd
total 0
dr-x------. 2 root root  0 Jun 25 05:16 .
dr-xr-xr-x. 8 root root  0 Jun 25 05:14 ..
lr-x------. 1 root root 64 Jun 25 05:16 0 -> /dev/null
lrwx------. 1 root root 64 Jun 25 05:16 1 -> socket:[23851]
lrwx------. 1 root root 64 Jun 25 05:16 2 -> socket:[23851]
```

Querying journalctl by PID does not help (`journalctl _PID=1934`) it comes back empty.

Here's the current diff between `waagent.log` and `journalctl waagent` command: https://gist.github.com/ahmetalpbalkan/880be2b77f6bcdcbfc2e6f7c9735a09d

I started to suspect if it is because we are missing some `-u` in the child process causing output buffering...

**Comment by ahmetalpbalkan** [comment]
@brendandixon Yep it looks like not having `['python', '-u']` in the children (`subprocess.Popen([agent_bin, 'run-exthandlers'],...)`) is the problem.

When pstree looks like the following, I finally get log from the children in the `journalctl`:

```
  ├─python,2113 -u /usr/sbin/waagent -daemon
  │   ├─python,2126 -u /usr/sbin/waagent run-exthandlers
```

**Comment by ahmetalpbalkan** [comment]
Seems to have resolved... Picks up the right python2/python3 thing as well
