### ISSUE TITLE
[BUG] The description of "Logs.Collect" is incorrect

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2603]
**Describe the bug: A clear and concise description of what the bug is.**
In the config/waagent.conf, the description of the "Logs.Collect" is "# Enable periodic log collection, default is n". Actually the default is y in the code
```
# cat azurelinuxagent/common/conf.py:
...
__SWITCH_OPTIONS__ = {
    "Logs.Collect": True
...
def get_collect_logs(conf=__conf__):
    return conf.get_switch("Logs.Collect", True)
```

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL-9.1
 - WALinuxAgent version
WALinuxAgent-2.7.0.6 running on rhel 9.1
Python: 3.9.10
Goal state agent: 2.7.1.0

**Comment by kevinclark19a** [comment]
Thanks for bringing this to our attention, will make the change and add the PR # here.
