### ISSUE TITLE
[BUG] SUSE: Valid values for DHCLIENT_HOSTNAME_OPTION can get clobbered

### ISSUE THREAD

**Issue by FladoToo** [Azure/WALinuxAgent#2614]
wicked accepts AUTO, 'AUTO', and "AUTO" as valid values for DHCLIENT_HOSTNAME_OPTION in /etc/sysconfig/network/dhcp. However, when the agent detects a hostname change, it recognizes only one of these values (the newest version in the SLES repository python-azure-agent-2.2.49.2-150100.3.23.1 recognizes only AUTO, the version here on GitHub - only "AUTO") and replaces any of the other with the actual host name, thus breaking the AUTO functionality.

See https://github.com/Azure/WALinuxAgent/issues/2607 for exact location of the bug and further impact details.

**Comment by nagworld9** [comment]
@FladoToo you mean agent should support all three types ("AUTO", 'AUTO', and AUTO). If it matches, agent shouldn't the update the hostname.

**Comment by FladoToo** [comment]
@nagworld9 yes, exactly.

**Comment by nagworld9** [comment]
Address the issue.
