### ISSUE TITLE
Question: waagent does not automatically start upon VM reboot

### ISSUE THREAD

**Issue by kirancheparthi** [Azure/WALinuxAgent#2646]
2.7.0.6 version of waagent does not start automatically after VM reboot in Azure. Is this expected? 
This is seen on Oracle Linux 7.9 and 8.6 with WALinuxAgent-2.7.0.6-1.el7.noarch.rpm.

With [v2.6.0.2] that is not the case, waagent starts automatically upon VM reboot.

**Comment by narrieta** [comment]
@kirancheparthi No, this is not expected. Please check the system logs for errors.

@Jithinjosepkl How does #2647 address this issue?

**Comment by jithinjosepkl** [comment]
@narrieta - Sorry, it was a typo. Right one is  #2645. Can we get some eyes on the PR? Is that the right approach?

**Comment by narrieta** [comment]
@jithinjosepkl thanks for correcting the link. But how does that PR address the issue of the agent not starting on Oracle Linux?

**Comment by kirancheparthi** [comment]
I don't see any error messages related to waagent in syslog. When I check the status, it shows loaded and inactive.
# systemctl status waagent
● waagent.service - Azure Linux Agent
   Loaded: loaded (/usr/lib/systemd/system/waagent.service; disabled; vendor pr>
   Active: inactive (dead)

**Comment by kirancheparthi** [comment]
Is there a status on the resolution of this issue?

**Comment by narrieta** [comment]
@kirancheparthi from the status you posted, it looks like the waagent service is disabled on your VM, so it won't start on boot. Try enabling the service,
