### ISSUE TITLE
[BUG] WALinuxAgent rpm removal does not remove udev rpm on OL7

### ISSUE THREAD

**Issue by kirancheparthi** [Azure/WALinuxAgent#2657]
On Oracle Linux 7, removal of WALinuxAgent-2.7.0.6-1.el7.noarch.rpm does not automatically remove WALinuxAgent-udev-2.7.0.6-1.el7.noarch.rpm. 

This is seen on Oracle Linux 7.9 with WALinuxAgent-2.7.0.6-1.el7.noarch.rpm.

On Oracle Linux 8 behavior is correct, or removes the dependency as well. Note that, this is the first time we have WALinuxAgent-udev-2.7.0.6-1.el7.noarch.rpm for OL7. For the previous releases we did not have the udev rpm. For OL8, we always had two rpms or udev was always there.

**Comment by narrieta** [comment]
@kirancheparthi We do not create the deb/rpm packages for the WALinuxAgent. You would need to track where to open issues for Oracle Linux, sorry.
