### ISSUE TITLE
WALinuxAgent Version

### ISSUE THREAD

**Issue by piyush94** [Azure/WALinuxAgent#2670]
When I run `waagent --version`, I get the below output.
```
WALinuxAgent-2.2.45 running on ubuntu 18.04
Python: 3.6.9
Goal state agent: 2.8.0.11
```

So what is the current agent version, 2.2.45 or 2.8.0.11 ?

In Azure Portal as well I see the version as,
![image](https://user-images.githubusercontent.com/11614204/191508272-a9ca1c24-4d20-45a1-8ff9-9ec3cde4d8b1.png)

**Thanks**

**Comment by narrieta** [comment]
We have some info in our FAQ: https://github.com/Azure/WALinuxAgent/wiki/FAQ

**Comment by piyush94** [comment]
@narrieta Thanks for the info. Looking at my output and releases in this git repository, how do I update the waagent version to 2.8.0.11 ?

**Comment by narrieta** [comment]
It should update automatically, unless autoupdate is disabled 

https://github.com/Azure/WALinuxAgent#autoupdateenabled
