### ISSUE TITLE
Uses subprocess with shell=True

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#268]
Arbitrary information is pushed into `shellutil.run` unchecked. This function calls subprocess with `shell=True` and is prone to injection attacks as root.

**Comment by brendandixon** [comment]
@waldiTM We appreciate you looking closely at the code, particularly for security issues. In this case, we're good. The method is only invoked with, and will only be invoked with, either statements built inline or with statements retrieved from known, trusted sources (e.g., Linux extensions). There is no security exposure.

Just so you know, we do periodically run various security scanners across our code to help ensure that such issues are caught. Thank you for noticing!

**Comment by waldiTM** [comment]
The strings are from outside sources, so consider them tainted, always. And tainted strings don't belong into a command given to a shell, never.

**Comment by brendandixon** [comment]
@waldiTM All security reduces to a chain of trust. In this case, we own the *entire* chain which is secured at multiple points along the way. Again, in the general case, your comments are sound. In this case, we've secured the chain that delivers the strings and so the code is sound.

**Comment by ahmetalpbalkan** [comment]
Closing as Virtual Machine Exceptions are already running as `root` anyway and as Brendan said we own these packages officially.
