### ISSUE TITLE
RHEL 8 The GoalState.1.xml file is empty and Extensionsconfig.1.xml file is not created.

### ISSUE THREAD

**Issue by vpidatala94** [Azure/WALinuxAgent#2681]
**Describe the bug: The GoalState.1.xml file is empty and Extensionsconfig.1.xml file is not created.

1. No error reported in the log files
2. Machine has Rhel8 linux distribution. 
[root@redhat-rhel8 waagent]# waagent -version
WALinuxAgent-2.3.0.2 running on redhat 8.2
Python: 3.6.8
Goal state agent: 2.8.0.11

[root@redhat-rhel8 waagent]# cat /etc/waagent.conf | grep "Extensions"
Extensions.Enabled=y
[root@redhat-rhel8 waagent]#

3. Any possible leads to troubleshoot the issue?

**Comment by narrieta** [comment]
@vpidatala94 The agent does not create those files anymore. They were part of an internal cache that is no longer needed, you should not take dependencies on those files.

**Comment by vpidatala94** [comment]
Thank you for the prompt response!

**Comment by vpidatala94** [comment]
Our product code requires Plugin Name information which we parse from ExtensionsConfig XML file. Could you please suggest alternative location where we can get this information?
