### ISSUE TITLE
[BUG] Don't backlist agent version when fetching goalstate failed

### ISSUE THREAD

**Issue by smartpcr** [Azure/WALinuxAgent#2683]
**Describe the bug: A clear and concise description of what the bug is.**

In azure stack environment, we observed that when agent find new version of agent, and run new agent to fetch goalstate/config during network outage window, the failure would put new agent version in backlist, and never try agent update again.

Current retry logic (maxretry=6) doesn't account for network outage, we would like to increase retry interval (from 1 sec to 5 min) for new agent, this would give enough time (30 min) for network to recover.

thanks!

**Comment by narrieta** [comment]
Talked with @smartpcr offline. The blacklisting logic is problematic and we are planning on removing it in a later version of the agent.
