### ISSUE TITLE
[BUG] Host certificate file suddenly removed

### ISSUE THREAD

**Issue by baelter** [Azure/WALinuxAgent#2687]
Something causes the agent to remove our host cert.
```
ls /etc/ssh/
...
-rw-r--r--   1 root root    534 Oct 21 12:22 ssh_host_ed25519_key-cert.pub
```

That file is suddenly gone.

Ubuntu 20.x
waagent 2.8.x 

Can send waagent.log privately, but I can't see anything interesting that looks related.

**Comment by dentarg** [comment]
This pattern would match the key

https://github.com/Azure/WALinuxAgent/blob/04ded9f0b708cfaf4f9b68eead1aef4cc4f32eeb/azurelinuxagent/common/conf.py#L331-L332

Used in these places https://github.com/Azure/WALinuxAgent/search?q=get_ssh_key_glob

**Comment by baelter** [comment]
But we have `Provisioning.RegenerateSshHostKeyPair=n` is the config :thinking:

**Comment by baelter** [comment]
Turns out that `cloud-init` regenerates to keys for some reason
