### ISSUE TITLE
nothing provides WALinuxAgent-udev = 2.7.3.0-1_ol001.el8

### ISSUE THREAD

**Issue by almalinux4all** [Azure/WALinuxAgent#2692]
Hello,

I am using a Rocky Linux 8 box, with the OpenLogic repo configured to download packages from http://olcentgbl.trafficmanager.net/openlogic/8/openlogic/x86_64/RPMS/

Doing an "yum update WALinuxAgent", I get the following error:

Error:
 Problem: cannot install the best update candidate for package WALinuxAgent-2.5.0.2-1_ol001.el8.noarch
  - nothing provides WALinuxAgent-udev = 2.7.3.0-1_ol001.el8 needed by WALinuxAgent-2.7.3.0-1_ol001.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

So it looks that there is no WALinuxAgent-udev version 2.7.3.0-1_ol001.el8 available at http://olcentgbl.trafficmanager.net/openlogic/8/openlogic/x86_64/RPMS/, and this leads to the WALinuxAgent package not being updated to the latest version....

Am I doing something wrong?

Thank you,

**Comment by fifinonz** [comment]
Hello, 
Experienced the same error today. Using CentOS stream and running 
`dnf update`

Error message:

> Error: 
>  Problem: cannot install the best update candidate for package WALinuxAgent-2.7.0.6-2.el8.noarch
>   - nothing provides WALinuxAgent-udev = 2.7.3.0-1_ol001.el8 needed by WALinuxAgent-2.7.3.0-1_ol001.el8.noarch
>

**Comment by stanislavrupec** [comment]
Hello,
as I was trying to solve an issue with intense logging by waagent to /var/lib/waagent/events/ on one of our CentOS VMs (CentOS Stream release 8). Because of that I tried to update the WALinuxAgent to the latest version and got the same error:
![image](https://user-images.githubusercontent.com/117273606/199468747-7170c8a2-6802-41ef-a67b-b2f49cae3477.png)

**Comment by almalinux4all** [comment]
So it seems the dependency is broken for WALinuxAgent version 2.7.3.0-1_ol001.el8 in the OpenLogic repository, since the corrsponding WALinuxAgent-udev package is missing. 

So as a temporary workaround, I have disabled the OpenLogic repo as below:

`sudo  dnf config-manager --set-disable openlogic`

You can find out the openlogic repo name in your box by running `dnf repolist`

**Comment by almalinux4all** [comment]
The WALinuxAgent-udev package version 2.7.3.0-1_ol001.el8 is now available in the repo, and I was able to update the WALinuxAgent package to latest version.

**Comment by almalinux4all** [comment]
The WALinuxAgent-udev package version 2.7.3.0-1_ol001.el8 is now available in the repo, and I was able to update the WALinuxAgent package to latest version.
