### ISSUE TITLE
[BUG] python3 errors flooding logs (Ubuntu 22.04.1)

### ISSUE THREAD

**Issue by kinneko** [Azure/WALinuxAgent#2695]
**python3 errors flooding logs.**
I've observed that the syslog file is very bloated.
The amount exceeded 1GB in 6 days, and most of them were python3 errors.
Most of the errors were coming from /usr/sbin/waagent.
I was getting the same error once a second.

**Distro and WALinuxAgent details:**
 - Ubuntu 22.04.1
 - WALinuxAgent version 2.2.46-0ubuntu5.1

**Log file attached**
Oct 30 00:00:12 recboxlogdb python3[1654075]: 2022-10-30T00:00:12.833653Z WARNING ExtHandler Agent WALinuxAgent-2.2.46 failed with exception: str expected, not NoneType
Oct 30 00:00:12 recboxlogdb python3[1654075]: 2022-10-30T00:00:12.834844Z WARNING ExtHandler Traceback (most recent call last):
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/update.py", line 268, in run
Oct 30 00:00:12 recboxlogdb python3[1654075]:     monitor_thread.run()
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/monitor.py", line146, in run
Oct 30 00:00:12 recboxlogdb python3[1654075]:     self.init_sysinfo()
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/monitor.py", line185, in init_sysinfo
Oct 30 00:00:12 recboxlogdb python3[1654075]:     vminfo = self.protocol.get_vminfo()
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 113, in get_vminfo
Oct 30 00:00:12 recboxlogdb python3[1654075]:     goal_state = self.client.get_goal_state()
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 856, in get_goal_state
Oct 30 00:00:12 recboxlogdb python3[1654075]:     self.goal_state = GoalState(xml_text)
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 1381, in __init__
Oct 30 00:00:12 recboxlogdb python3[1654075]:     self._parse(xml_text)
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 1398, in _parse
Oct 30 00:00:12 recboxlogdb python3[1654075]:     os.environ[CONTAINER_ID_ENV_VARIABLE] = self.container_id
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3.10/os.py", line 684, in __setitem__
Oct 30 00:00:12 recboxlogdb python3[1654075]:     value = self.encodevalue(value)
Oct 30 00:00:12 recboxlogdb python3[1654075]:   File "/usr/lib/python3.10/os.py", line 756, in encode
Oct 30 00:00:12 recboxlogdb python3[1654075]:     raise TypeError("str expected, not %s" % type(value).__name__)
Oct 30 00:00:12 recboxlogdb python3[1654075]: TypeError: str expected, not NoneType

2022-11-02T01:01:07.758491Z WARNING ExtHandler Agent WALinuxAgent-2.2.46 failed with exception: str expected, not NoneType
2022-11-02T01:01:07.760561Z WARNING ExtHandler Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/update.py", line 268, in run
    monitor_thread.run()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/monitor.py", line 146, in run
    self.init_sysinfo()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/monitor.py", line 185, in init_sysinfo
    vminfo = self.protocol.get_vminfo()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 113, in get_vminfo
    goal_state = self.client.get_goal_state()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 856, in get_goal_state
    self.goal_state = GoalState(xml_text)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 1381, in __init__
    self._parse(xml_text)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 1398, in _parse
    os.environ[CONTAINER_ID_ENV_VARIABLE] = self.container_id
  File "/usr/lib/python3.10/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

2022-11-02T01:01:08.589323Z WARNING Daemon Agent WALinuxAgent-2.2.46 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' failed with return code: 1

**Comment by nagworld9** [comment]
@kinneko  If you still see this, could you capture the contents of GoalState.*.xml under /var/lib/waagent and check it is a valid XML file and has a valid ContainerID element? (it should be a GUID) or share it if you have full agent logs.

**Comment by narrieta** [comment]
@kinneko Closing this issue since there is no reply (if you still see this, removing /var/lib/waagent/GoalState.1.xml may help)
