### ISSUE TITLE
[BUG] Bug Title# AutoUpdate.Enabled=y
AutoUpdate.Enabled=y

### ISSUE THREAD

**Issue by Mebare** [Azure/WALinuxAgent#2700]
**Describe the bug: A clear and concise description of what the bug is.**

Note: Please add some context which would help us understand the problem better
1. Section of the log where the error occurs.
2. Serial console output
3. Steps to reproduce the behavior.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: [e.g. Ubuntu 16.04]
 - WALinuxAgent version [e.g. 2.2.40, you can copy the output of `waagent --version`, more info [here](https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output) ]

**Additional context**

**Log file attached**
If possible, please provide the full /var/log/waagent.log file to help us understand the problem better and get the context of the issue.

**Comment by narrieta** [comment]
@Mebare Maybe this issue was opened by mistake? there is no description of the issue so I'm closing it. Please open a new issue with details if needed.
