### ISSUE TITLE
[BUG] Problem using on fedora 37 . 

### ISSUE THREAD

**Issue by asklinux** [Azure/WALinuxAgent#2709]
** the vm cant deploy on azure its have this error **

Provisioning state Provisioning failed.
OS Provisioning failed for VM 'testf0101' due to an internal error: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to mount dvd device
Inner error: [['mount', '-o', 'ro', '-t', 'udf,iso9660,vfat', '/dev/sr0', '/mnt/cdrom/secure']] returned 32:
 stdout: 

stderr: mount: /mnt/cdrom/secure: no medium found on /dev/sr0.
       dmesg(1) may have more information after failed mount system call.

**Comment by narrieta** [comment]
@anhvoms could you take a look? thanks

**Comment by asklinux** [comment]
any update ? its is any problume with new version waagent or any configure i need change after upgrade  the vm ?

**Comment by asklinux** [comment]
2022-12-12T03:06:39.575140Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=Provision, message=Provisioning failed: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to mount dvd device
Inner error: [mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure] returned 32:  (71.30s), duration=0
2022-12-12T03:06:39.602999Z WARNING Daemon Daemon Could not mount cgroups: [Errno 1]

**Comment by anhvoms** [comment]
How did you deploy fedora 37, is this a marketplace image or did you bring your own VHD?
