### ISSUE TITLE
[BUG] Ubuntu 18.4.0 Could not find swap counter, is it harmless?

### ISSUE THREAD

**Issue by LiliDeng** [Azure/WALinuxAgent#2718]
Ubuntu 18.4.0
INFO MonitorHandler ExtHandler Could not find swap counter from "memory.stat" file in the cgroup: /sys/fs/cgroup/memory/system.slice/walinuxagent.service. Internal error: Cannot find counter: swap

see above *INFO* but from description it is error? can it be ignored?

**Comment by nagworld9** [comment]
yes, error can be ignored. It's just info msg and not an issue in agent.

**Comment by nagworld9** [comment]
we will improve the message to make it explicit.
