### ISSUE TITLE
[BUG][RHEL8] systemd service should not use python3

### ISSUE THREAD

**Issue by Klaas-** [Azure/WALinuxAgent#2728]
**Describe the bug: A clear and concise description of what the bug is.**
Hi,
it seems on systems where python3 is not pointing to the same python version as platform-python waagent fails to start. This happens because you try to directly use python3 in the systemd service file.

1. Section of the log where the error occurs.
```
Traceback (most recent call last):
  File "/usr/sbin/waagent", line 35, in <module>
    import azurelinuxagent.agent as agent
ModuleNotFoundError: No module named 'azurelinuxagent'
```
2. Steps to reproduce the behavior.
I'd guess this happens on any rhel8 system where /usr/bin/python3 is not pointing to python 3.6 (platform-python)

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Red Hat Enterprise Linux release 8.7 (Ootpa)
 - WALinuxAgent version 
```
WALinuxAgent-2.7.0.6 running on redhat 8.7
Python: 3.6.8
Goal state agent: 2.8.0.11
```

```
$ python3 --version
Python 3.9.13
```

**Additional context**
Workaround: Create an override for the waagent.service file, something like this:
```
# /etc/systemd/system/waagent.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/libexec/platform-python -u /usr/sbin/waagent -daemon
```

This happens because WALinuxAgent uses platform-python (3.6 on RHEL8).
```
head -n1 /usr/sbin/waagent
#!/usr/libexec/platform-python
```

I am guessing you could also change it to start /usr/sbin/waagent directly, without python, then it will work as well because /usr/sbin/waagent has the correct shebang and is executable

**Comment by narrieta** [comment]
@Klaas- Installation of Python and the setup in the service file are done by the publisher of the image. If this is the standard image coming published by Red Hat, could you report the issue on their site? At some point they were using the platform Python, but there were some issues and they changed that after 1 release (AFAIK).

**Comment by Klaas-** [comment]
@narrieta yeah, but it's your file that is creating the issues and easily fixed by my PR #2729 - then it'll trickle down into RHEL, I'll create a backport request once it's merged here. About which python version rhel uses, the beauty is I don't care :D Look at the PR, there is no need to specify which python in the service file, as long as the shebang is correct that service file will work.

**Comment by Klaas-** [comment]
@narrieta any progress here? :)

**Comment by narrieta** [comment]
@Klaas- As previously mentioned, the Python setup is done by the image publisher. I left your PR open in case in the future we find time to test it and see if we should merge it.

**Comment by Klaas-** [comment]
but that is the whole point, you supply a systemd service that specifies which python is used, red hat uses that file as is, but you could be leaving the python selection up to the image publisher, which is what the PR introduces

**Comment by narrieta** [comment]
@Klaas- yes, thank you for your contribution. we'll consider it at a later time

**Comment by Klaas-** [comment]
So Red Hat will not patch the service file downstream: https://gitlab.com/redhat/rhel/src/walinuxagent/-/merge_requests/16  // https://bugzilla.redhat.com/show_bug.cgi?id=2170104

**Comment by narrieta** [comment]
Closing this issue. Image publishers adapt the service files as best suited to their image.

**Comment by Klaas-** [comment]
@narrieta I still think you should give a good example upstream :)

**Comment by narrieta** [comment]
@Klaas-  thanks for pointing this out. I took a look at the service files of the distros we tests and there are several differences between them. There is really not a "good example", it's up to the distro owner to set this up. Ideally we would like the different customizations of the agent to be submitted upstream, but that does not always happen.

**Comment by Klaas-** [comment]
@narrieta rhel 8.8 will use the suggestion from my PR, so I am guessing you can consider that PR rhel upstreaming their changes :)

**Comment by Klaas-** [comment]
the file is just for redhat based distros "init/redhat/waagent.service" :) But with rhel9 it seems to be a little different: https://bugzilla.redhat.com/show_bug.cgi?id=2170104#c36 I still think it makes sense not to set the python version in the service file, but then I do no longer care if python3 is static :)
