### ISSUE TITLE
[BUG] traceback.format_exception - 3.10 compatibility

### ISSUE THREAD

**Issue by ebatutis** [Azure/WALinuxAgent#2753]
The signature for traceback.format_exception changed in Python 3.10 - it is not entirely backwards compatible.

https://docs.python.org/3/library/traceback.html

There is no "etype" parameter any more.

The code in 2.8.0.11 tries to format an exception, but this causes another exception on Python 3.10+:

azurelinuxagent/common/utils/textutil.py
       msg += ''.join(traceback.format_exception(etype=type(exception), value=exception, tb=tb))

**Comment by nagworld9** [comment]
Thanks for reporting. We already made a fix https://github.com/Azure/WALinuxAgent/pull/2663. It's available in 2.9.0.4
