### ISSUE TITLE
[BUG] Packet capture failed on Kali Linux after installing docker package

### ISSUE THREAD

**Issue by naoikeda** [Azure/WALinuxAgent#2765]
**Describe the bug: A clear and concise description of what the bug is.**

On Kali linux VM, packet capture in Azure Network Watcher fails after installing docker-related package.
Here are more detailed steps:
1. Deploy a Kali VM from marketplace image (Kali 2022.4b (kali-rolling))
2. Run `apt-update`
3. Install docker.io package (`apt install docker.io`)
4. Start packet capture
5. Stop packet capture (fails with `InternalServerError`)

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Kali Linux 2022.4
 ```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2022.4"
VERSION_ID="2022.4"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```
 - WALinuxAgent version: 2.7.3.0
 ```
WALinuxAgent-2.7.3.0 running on kali 2022.4
Python: 3.11.1
Goal state agent: 2.7.3.0
```

**Additional context**
Here is the output of the failed packet-capture stop command.
```
az network watcher packet-capture stop -l japaneast -n kali_1        
(InternalServerError) An error occurred.
Code: InternalServerError
Message: An error occurred.
```

**Comment by narrieta** [comment]
@naoikeda This seems to be an issue with network watcher, rather than walinuxagent. I did not find a github repo for network watcher, but I forwarded your report to the team in charge of it. I'll close this issue.
