### ISSUE TITLE
Add all config keys in the code to waagent.conf(s)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#279]
The:
- `waagent.conf` files checked in and 
- the README

do not have the keys such as

* AutoUpdate.GAFamily
* AutoUpdate.Enabled

these should be added to those files and documented properly.

**Comment by brendandixon** [comment]
@ahmetalpbalkan You know, you could have just added the documentation. :)

**Comment by brendandixon** [comment]
@ahmetalpbalkan I'll add it....

**Comment by ahmetalpbalkan** [comment]
Also I'm not sure how each distro publisher picks up waagent.conf... I guess we need to make sure `AutoUpdate.Enabled` is `y` by default when the key is missing, bc I have a good feeling like it will be

**Comment by ahmetalpbalkan** [comment]
@brendandixon you're welcome

**Comment by ahmetalpbalkan** [comment]
@brendandixon ping.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Many configuration keys are not documented at this time. We should plan an update that documents them all, but not at the moment.

**Comment by ahmetalpbalkan** [comment]
@brendandixon which other ones are also not documented?

**Comment by ahmetalpbalkan** [comment]
also not sure why not at the moment... I end up adding these two keys to waagent.conf myself at 5 times a day

**Comment by brendandixon** [comment]
@ahmetalpbalkan I started adding these and was comparing conf.py against the markdown. I found many missing. We should eventually fix. Not now.

**Comment by hglkrijger** [comment]
they have been added
