### ISSUE TITLE
[BUG] noisy SyntaxWarning for python "is not 0"

### ISSUE THREAD

**Issue by moreOver0** [Azure/WALinuxAgent#2808]
The code https://github.com/Azure/WALinuxAgent/blob/76f769cb53eced67609b3c2f9c758afc96be9934/bin/waagent2.0#L2319
produces a warning in log, like
```
/var/lib/waagent/Microsoft.AKS.Compute.AKS.Linux.AKSNode-1.46/waagent:2555: SyntaxWarning: "is not" with a literal. Did you mean "!="?
```
modify the "is not 0" to be "!= 0" helps reducing noise in log.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: [any]
 - WALinuxAgent version [any]

**Additional context**

**Log file attached**
If possible, please provide the full /var/log/waagent.log file to help us understand the problem better and get the context of the issue.

**Comment by narrieta** [comment]
waagent2.0 is dead code from the agent's point of view, it is not invoked by the agent. Some very old legacy VM extensions use that code, in your case it seems to be the AKS extension. This issue would need to be reported in their repo (it may be this one: https://github.com/Azure/AKS)
