### ISSUE TITLE
Warning daemon daemon unable to load distro implementation for lfs

### ISSUE THREAD

**Issue by cacheguard** [Azure/WALinuxAgent#2812]
Hello,

I'm trying to properly start waagent on a Linux system built from scratch. My OS is a derivation of the LFS (Linux From Scratch) project. I start the daemon using the following command:`waagent -configuration-path:/etc/waagent.conf -start`

That command produces several times the following message on the console port: **WARNING Daemon Daemon Unable to load distro implementation for lfs. Using default distro implementation instead.**

Is this normal, while the `-configuration-path:/etc/waagent.conf` option has been specified?

Also, while my **/etc/waagent.conf** file contains the `OS.EnableRDMA=n` directive,  I get the following message: **INFO Daemon Daemon No RDMA handler exists for distro='1' version='1.1-rc1'**

Again is this normal? It seems that my /etc/waagent.conf file is not taken into consideration at all.

Is there a way to get rid of INFO and WARNING messages?

Thanks in advance.

**Comment by narrieta** [comment]
From this warning (WARNING Daemon Daemon Unable to load distro implementation for lfs. Using default distro implementation instead) likely this code https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/version.py#L105 is not identifying your distro correctly.

This is something you would need to debug on your side, sorry.

**Comment by cacheguard** [comment]
Thank you for your response.

Well, we finally decided to write a subclass of DefaultOSUtil for our OS. Below our class definition and a sample method:

```
class CacheGuardOSUtil( DefaultOSUtil ):

    def __init__( self ):
        super( CacheGuardOSUtil, self ).__init__( )
        self.jit_enabled = True

    def test( self ):
        logger.warn( "Hello CacheGuard" )
```
Now we need to tests all methods that we specialized in our class. Can you please provide with a template program (including all required import and other statements) that would allow us to simply and **locally** test our methods?

The methods that we developed mainly call `shellutil.run_command( )` in order to execute CLI commands in our OS (which is a network appliance). We had a look at the tests directory but without any guide, it's hard to understand for us... We are looking for a simpler method to tests our program. 

Best Regards,

**Comment by narrieta** [comment]
@cacheguard  There are some basic tests for osutil under https://github.com/Azure/WALinuxAgent/tree/master/tests/common/osutil
