### ISSUE TITLE
WALinuxAgent 2.0 under Freebsd

### ISSUE THREAD

**Issue by crea7or** [Azure/WALinuxAgent#29]
Here is the log from waagent.log file. It looks like I did something wrong and agent failed at launch. Maybe I just don't understand how to test if it work or not.
This is freebsd 10 release system.

2014/04/26 21:28:47 Windows Azure Linux Agent Version: WALinuxAgent-2.0.5-PRE
2014/04/26 21:28:47 Module /lib/modules/10.0-RELEASE/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM does not exist.
2014/04/26 21:28:47 VMM Init script not found.  Provisioning for Azure
2014/04/26 21:28:47 lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
2014/04/26 21:28:47     options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
2014/04/26 21:28:47     inet6 ::1 prefixlen 128 
2014/04/26 21:28:47     inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
2014/04/26 21:28:47     inet 127.0.0.1 netmask 0xff000000 
2014/04/26 21:28:47     nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
2014/04/26 21:28:47 hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
2014/04/26 21:28:47     options=18<VLAN_MTU,VLAN_HWTAGGING>
2014/04/26 21:28:47     ether 00:15:5d:d0:1c:ce
2014/04/26 21:28:47     inet 100.70.32.79 netmask 0xfffffe00 broadcast 100.70.33.255 
2014/04/26 21:28:47     nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
2014/04/26 21:28:47 
2014/04/26 21:28:47 IPv4 address: 100.70.32.79
2014/04/26 21:28:47 lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
2014/04/26 21:28:47     options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
2014/04/26 21:28:47     inet6 ::1 prefixlen 128 
2014/04/26 21:28:47     inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
2014/04/26 21:28:47     inet 127.0.0.1 netmask 0xff000000 
2014/04/26 21:28:47     nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
2014/04/26 21:28:47 hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
2014/04/26 21:28:47     options=18<VLAN_MTU,VLAN_HWTAGGING>
2014/04/26 21:28:47     ether 00:15:5d:d0:1c:ce
2014/04/26 21:28:47     inet 100.70.32.79 netmask 0xfffffe00 broadcast 100.70.33.255 
2014/04/26 21:28:47     nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
2014/04/26 21:28:47 
2014/04/26 21:28:47 MAC  address: 00:15:5D:D0:1C:CE
2014/04/26 21:28:47 ERROR:Reading from file /sys/firmware/acpi/tables/OEM0 Exception is [Errno 2] No such file or directory: '/sys/firmware/acpi/tables/OEM0'
2014/04/26 21:28:47 Probing for Windows Azure environment.
2014/04/26 21:28:47 lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
2014/04/26 21:28:47     options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
2014/04/26 21:28:47     inet6 ::1 prefixlen 128 
2014/04/26 21:28:47     inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
2014/04/26 21:28:47     inet 127.0.0.1 netmask 0xff000000 
2014/04/26 21:28:47     nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
2014/04/26 21:28:47 hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
2014/04/26 21:28:47     options=18<VLAN_MTU,VLAN_HWTAGGING>
2014/04/26 21:28:47     ether 00:15:5d:d0:1c:ce
2014/04/26 21:28:47     inet 100.70.32.79 netmask 0xfffffe00 broadcast 100.70.33.255 
2014/04/26 21:28:47     nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
2014/04/26 21:28:47 
2014/04/26 21:28:47 ERROR:CalledProcessError.  Error Code is 64
2014/04/26 21:28:47 ERROR:CalledProcessError.  Command string was route -n
2014/04/26 21:28:47 ERROR:CalledProcessError.  Command result was route: usage: route [-dnqtv] command [[modifiers] args]
2014/04/26 21:28:47 lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
2014/04/26 21:28:47     options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
2014/04/26 21:28:47     inet6 ::1 prefixlen 128 
2014/04/26 21:28:47     inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
2014/04/26 21:28:47     inet 127.0.0.1 netmask 0xff000000 
2014/04/26 21:28:47     nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
2014/04/26 21:28:47 hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
2014/04/26 21:28:47     options=18<VLAN_MTU,VLAN_HWTAGGING>
2014/04/26 21:28:47     ether 00:15:5d:d0:1c:ce
2014/04/26 21:28:47     inet 100.70.32.79 netmask 0xfffffe00 broadcast 100.70.33.255 
2014/04/26 21:28:47     nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
2014/04/26 21:28:47 
2014/04/26 21:28:47 DoDhcpWork: Missing default route - adding broadcast route for DHCP.
2014/04/26 21:28:47 DoDhcpWork: Setting socket.timeout=10, entering recv
2014/04/26 21:28:47 DoDhcpWork: Removing broadcast route for DHCP.
2014/04/26 21:28:47 Discovered Windows Azure endpoint: 100.70.32.160
2014/04/26 21:28:47 Fabric preferred wire protocol version: 2012-11-30
2014/04/26 21:28:47 Negotiated wire protocol version: 2012-11-30
2014/04/26 21:28:47 Retrieved GoalState from Windows Azure Fabric.
2014/04/26 21:28:47 ExpectedState: Started
2014/04/26 21:28:47 ContainerId: 24a4f28d-e92d-42b9-a415-ed6156b18a2c
2014/04/26 21:28:47 RoleInstanceId: 55cfc878d43f46d4b493969d17113db2.coroste
2014/04/26 21:28:48 Spawning bsd_activate_resource_disk.py
2014/04/26 21:28:48 Provisioning image started.
2014/04/26 21:28:48 ERROR:Traceback (most recent call last):
2014/04/26 21:28:48 ERROR:  File "/usr/sbin/waagent", line 4713, in main
2014/04/26 21:28:48 ERROR:    WaAgent.Run()
2014/04/26 21:28:48 ERROR:  File "/usr/sbin/waagent", line 4309, in Run
2014/04/26 21:28:48 ERROR:    provisionError = self.Provision()
2014/04/26 21:28:48 ERROR:  File "/usr/sbin/waagent", line 4164, in Provision
2014/04/26 21:28:48 ERROR:    if MyDistro.mediaHasFilesystem(dvd) is False :
2014/04/26 21:28:48 ERROR:  File "/usr/sbin/waagent", line 1524, in mediaHasFilesystem
2014/04/26 21:28:48 ERROR:    if Run('LC_ALL=C fdisk -p ' + dsk + ' | grep "invalid fdisk partition table found" ',False):
2014/04/26 21:28:48 ERROR:TypeError: cannot concatenate 'str' and 'NoneType' objects
2014/04/26 21:28:48 ERROR:
2014/04/26 21:28:48 ERROR:Exception: cannot concatenate 'str' and 'NoneType' objects
2014/04/26 21:28:49 Resource disk (/dev/da1s1) is mounted at /mnt/resource with fstype ufs2

**Comment by wangjj1989** [comment]
@szarkos 
Hi, I also have this issue on Linux. My Linux is based on Redhat but I make many customizations .
I find following info from log:
`INFO Run provision handler.
     2016/11/02 22:30:31.414999 INFO Copy ovf-env.xml.
     2016/11/02 22:30:31.419522 ERROR Event: name=WALA, op=Provision, message=Failed to copy ovf-env.xml: (000008)(000007) Failed to get dvd device
`
I also can't find dvd device under /dev.
I have some question  about dvd device:
1. This dvd device is attached by Azure (underlying hypervisor?) 
2. When this dvd device will be attached? (boot and provision?)

Looking forward for your help!

**Comment by wangjj1989** [comment]
Another question: usually, I create the VHD from HyperV and I don't attach a dvd for it. Does it relate to this?

**Comment by wangjj1989** [comment]
Is /dev/sr0 created by waagent for Linux on Azure?
I create a centos 7 linux on hyperv and I also can't find /dev/{cdrom, hdc, sr0}.

**Comment by szarkos** [comment]
On Azure, at first boot a configuration file is passed to the guest VM via the DVD device.  Usually the DVD device is picked up by the ata_piix driver.  The agent doesn't create /dev/sr0.

Since the original issue is from 2014 please file a new issue for this if you think it's a bug in the Azure agent.  However, this is almost certainly a bug in your custom kernel or distro.

**Comment by wangjj1989** [comment]
Yes, I find ata_piix driver doesn't exist in my VM. And I also find this Microsoft post:
https://support.microsoft.com/en-sg/kb/2600152
so I should load ata_piix driver after hv_utils/storvsc drivers have been loaded, right?( I need change my os rc boot script, I afraid hv driver will unload it again)

**Comment by wangjj1989** [comment]
Hi szarkos,
I still have one question: if the first boot provision failed, for example, the agent is still not installed, is there are the other ways to trigger the provision(get the configration file via the DVD device)?
I find "Provisioning.Enabled=y" in waagent.conf, does this option will make the provision happen every times(include passing the configuration file to guest VM)?

**Comment by brendandixon** [comment]
@wangjj1989 Provisioning is (meant to be) a one-time action. The `Provisioning.Enabled` flag allows / disallows that one-time action. It does not request provisioning on every boot.
