### ISSUE TITLE
Tried to create VMs in azure Across availability zone and got this error: No python interpreter found

### ISSUE THREAD

**Issue by gargrahulms** [Azure/WALinuxAgent#2921]
/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4/shim.sh -install\n[stdout]\n\n\n[stderr]\nRunning scope as unit: install_317ba06b-a576-4192-b265-6cb3081c6b7d.scope\nNo Python interpreter found on the box\n'.\r\n    \r\n'Install handler failed for the extension.

**Comment by nagworld9** [comment]
@gargrahulms what distro is this? Looks to me coming from customscript code.

**Comment by gargrahulms** [comment]
Yes coming from custom script, which I was trying to install in ubuntu 20 VM.

**Comment by nagworld9** [comment]
Adding CSE team @norakoiralamsft to check this issue.

**Comment by norakoiralamsft** [comment]
Hi @gargrahulms  
This is an old/no longer supported version of CSE Linux. 
Here are the new details: 
They're running old CSE (no longer supported), the namespace and type is different now. 

      <ProviderNameSpace>Microsoft.Azure.Extensions</ProviderNameSpace>
      <Type>CustomScript</Type>
      <Version>2.1.10</Version>
     Documentation: https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux
