### ISSUE TITLE
Running collect-logs

### ISSUE THREAD

**Issue by CalvoM** [Azure/WALinuxAgent#2929]
Hello,
I am trying to run the collect-logs command and it seems to fail however I see that the daemon runs it by prefixing the command with some `systemd-run` configuration.  Is there a way of running the `collect-log` command from the cli without prefixing it with the `systemd-run` config?

I am testing v2.9.1.1 on ubuntu versions>= 18.04.

**Comment by maddieford** [comment]
@CalvoM Thanks for pointing this out. We added resource monitoring on collect logs in 2.9.1.1+, which broke the command line option. We'll work on fixing that. 

In the meantime, if you have 2.8.0.11 on the machine, you can use the following command to collect logs from cli:
`python3 -u /var/lib/waagent/WALinuxAgent-2.8.0.11/bin/WALinuxAgent-2.8.0.11-py2.7.egg -collect-logs`

**Comment by maddieford** [comment]
Fix is merged
