### ISSUE TITLE
[BUG] VMAccess does not work for FreeBSD

### ISSUE THREAD

**Issue by souradeep100** [Azure/WALinuxAgent#2973]
Changing password using Azure Portal does not work in FreeBSD

The error which happens during first attempt 

> ARM request failed
Reset password for virtualMachines 'schakrabarti-freebsd4' failed with error: VM has reported a failure when processing extension 'enablevmAccess' (publisher 'Microsoft.OSTCExtensions' and type 'VMAccessForLinux'). Error message: "Enable failed: chpasswd() got an unexpected keyword argument 'crypt_id'". More information on troubleshooting is available at 

During next attempt it shows the password change is successful but it does not change in reality.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: FreeBSD 13.2 FreeBSD14 RC2/RC3
 - WALinuxAgent version: WALinuxAgent-2.8.0.11 running on freebsd 13.2
Python: 3.9.16
Goal state agent: 2.8.0.11

**Comment by narrieta** [comment]
@souradeep100 Please open this issue at https://github.com/Azure/azure-linux-extensions
