### ISSUE TITLE
[BUG] Ubuntu 2204 & Azure Linux v2: v2.9.1.1 fails to assign IP address for IB interface

### ISSUE THREAD

**Issue by henryli001** [Azure/WALinuxAgent#3025]
OS: Azure Linux V2 marketplace image (mariner 2.0.20240112). The same error can also be repro'ed on Ubuntu 2204 marketplace image (canonical 0001-com-ubuntu-server-jammy 22_04-lts 22.04.202307010) and possible any other versions.

WALinuxAgent-2.9.1.1 running on mariner 2.0.20240112
Python: 3.9.14
Goal state agent: 2.9.1.1

After editing /etc/waagent.conf to specify OS.EnableRDMA=y and rebooting the VM, the ib0 interface is created but no IP address is assigned to ib0. However, if switching to the prior 2.9.0.4 version, everything looks good so seems like a regression with the latest source.

Discovered the following error in waagent.log which might be related to the IP address assignment failure:
```
2024-01-18T06:33:19.000375Z INFO Daemon Daemon RDMA capabilities are enabled in configuration
2024-01-18T06:33:19.000495Z ERROR Daemon Daemon Error setting up rdma device: [ProtocolError] Error fetching goal state
Inner error: 'WireProtocol' object has no attribute 'fetch_config'
```

**Comment by narrieta** [comment]
Fixed by #3073
