### ISSUE TITLE
[2.1] leaks child process in centos65

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#309]
Current behavior on centos6.5 (upstart)  I execute `service waagent restart`, the child process (`-run-exthandlers`) is being orphaned and gets parented to pid 1.

If I keep restarting the service/unit, it keeps leaking more child processes.

strangely I can't repro this on centos7.1, centos7.2 or ubuntu16.04...

**Comment by brendandixon** [comment]
@ahmetalpbalkan Can you try with the latest code? Possible #308 ?

**Comment by ahmetalpbalkan** [comment]
@brendandixon not sure if I'll be able to get to this. if you think you fixed I encourage you to provision a vm and give it a try. Creating a VM is not very complicated:

    azure vm quick-create <rg> centos65 westus linux 'openlogic:centos:6.5:latest' <user> --ssh-publickey-file ~/.ssh/id_rsa.pub

and installing the agent doesn't take more than 1 minute.
