### ISSUE TITLE
[BUG] ARM instances does not update to latest version

### ISSUE THREAD

**Issue by pyr0hu** [Azure/WALinuxAgent#3118]
**Describe the bug: A clear and concise description of what the bug is.**

Trying to update the agent on ARM instances (aarch64) but it does not want to pick up the latest goal state version and stays on 2.2.46. The same config (Ubuntu 22, with x86_64) picks up 2.10.0.8. The `/var/log/waagent.log` says:

`2024-05-02T19:57:24.540364Z INFO Daemon Installed Agent WALinuxAgent-2.2.46 is the most current agent`

Not sure what can I do with this as I cannot used the Azure Update Manager because it says it's unsupported.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Ubuntu 22.04 LTS ARM (aarch64)
 - WALinuxAgent version [e.g. 2.2.40, you can copy the output of `waagent --version`, more info [here](https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output) ]

```
WALinuxAgent-2.2.46 running on ubuntu 22.04
Python: 3.10.12
Goal state agent: 2.2.46
```

**Comment by nagworld9** [comment]
@pyr0hu which region is it?

**Comment by nagworld9** [comment]
@pyr0hu As of now, updates enabled entirely in Canary, West US 2, East US and few slices in South Central US and North Europe. We plan to make the newer arm64 versions available in all regions in the next month or 2. 

If your vm was in enabled region, it may be that it hit the known bug in 2.2.46. For mitigation, agent needs a service restart
`systemctl restart walinuxagent`

**Comment by pyr0hu** [comment]
@nagworld9 All of our instances currently residing in Germany West. So not all ARM instances get the latest version at the moment? I've already tried restarting the services but that didn't solve the problem so I think we are just not in an enabled region.

**Comment by nagworld9** [comment]
we haven't enabled yet in Germany West. It will take a month or 2 to enable in all regions.

**Comment by pyr0hu** [comment]
@nagworld9 Thanks for the heads up, I'll close this in the meanwhile. Is there a page where we can follow the rollout?

**Comment by pyr0hu** [comment]
@nagworld9 is there any update on the ARM rollout?

**Comment by nagworld9** [comment]
@pyr0hu Roll out started and release is in it's first stage and Germany west is stage 3. We don't have estimated date. We will update this thread when we reach stage3

![image](https://github.com/Azure/WALinuxAgent/assets/84482346/718504a3-f50c-4e16-a884-7110637e9320)

**Comment by maddieford** [comment]
@pyr0hu Roll out completed in Major Release 1, which includes GermanyWestCentral. Your arm64 machines in this region should update to the latest agent version. Note that a service restart may be required ('systemctl restart walinuxagent')

**Comment by pyr0hu** [comment]
@maddieford thank you for the heads up, will check them out!
