### ISSUE TITLE
WAAgent available through apt-get very old

### ISSUE THREAD

**Issue by LiquidPT** [Azure/WALinuxAgent#3161]
I've tried this with both Ubuntu 22.04 and 20.04 images from Azure Marketplace. The installed WAAgent is 2.2.46, which is over 4 years old. It appears the extension handler is much newer (2.11.1.4), but there isn't an updated provisioning agent, which [the docs say I should update via package manager to at least 2.2.53](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows/support-extensions-agent-version) (and I would think something much newer than that). Output of `waagent --version`:

> /usr/sbin/waagent:27: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
> WALinuxAgent-2.2.46 running on ubuntu 22.04
> Python: 3.10.12
> Goal state agent: 2.11.1.4

**Comment by narrieta** [comment]
@LiquidPT Canonical is currently working on updating the walinuxagent package. You could open an issue on their side, too.
