### ISSUE TITLE
Azure storage TLS 1.0/1.1 deprecation

### ISSUE THREAD

**Issue by rikraft-cisco** [Azure/WALinuxAgent#3258]
Does the upcoming TLS deprecation https://techcommunity.microsoft.com/t5/azure-storage-blog/tls-1-0-and-1-1-support-will-be-removed-for-new-amp-existing/ba-p/4026181 have any impact to waagent communication with Azure if the host application/virtual machine is configured with TLS 1.0/1.1?

**Comment by nagworld9** [comment]
waagent has two channels to communicate with azure. If direct calls fail, we fallback to host application(hgap) to interact with azure. This hgap already using TLS 1.2 for all outbound calls which includes storage calls and no impact on incoming calls to hgap. So, if vm setup to use 1.0/1.1, fallback with HGAP still works.
