### ISSUE TITLE
Failed to fetch ExtensionManifest from all sources

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/WALinuxAgent#326]
This started to happen today after we delete our only Prod agent update package (2.1.2).

I now see error:

```
2016/07/14 20:34:16.889247 WARNING Incarnation 2 failed to get Prod package list: (000008)Failed to fetch ExtensionManifest from all sources
2016/07/14 20:34:16.890106 ERROR Event: name=WALinuxAgent, op=Download, message=Incarnation 2 failed to get Prod package list: (000008)Failed to fetch ExtensionManifest from all sources
```

**Comment by ahmetalpbalkan** [comment]
@brendandixon where did you see the links? My agent gets ExtensionsConfig.{N}.xml like this:

```
  <GAFamilies>
    <GAFamily>
      <Name>Prod</Name>
      <Uris />
    </GAFamily>
    <GAFamily>
      <Name>Test</Name>
      <Uris />
    </GAFamily>
  </GAFamilies>
```

there are no manifests or URLs.

**Comment by sweekarp** [comment]
Guys, I get the same error with WALinuxAgent-2.2.0:

2016/10/03 17:12:17.913149 INFO WALinuxAgent-2.2.0 running as process 892
2016/10/03 17:12:17.923151 INFO Checking for agent family Prod updates
2016/10/03 17:12:17.930234 INFO Wire server endpoint:10.92.52.17
2016/10/03 17:12:17.943293 WARNING Incarnation 1 failed to get Prod package list: (000008)Failed to fetch ExtensionManifest from all sources
2016/10/03 17:12:17.955872 ERROR Event: name=WALinuxAgent, op=Download, message=Incarnation 1 failed to get Prod package list: (000008)Failed to fetch ExtensionManifest from all sources
2016/10/03 17:12:17.972388 INFO Wire server endpoint:10.92.52.17
