### ISSUE TITLE
Tests are not documented

### ISSUE THREAD

**Issue by nbirnel** [Azure/WALinuxAgent#336]
There is no documentation on how to run the tests.

**Comment by brendandixon** [comment]
@nbirnel Unit tests are ran using the standard Python mechanisms (e.g., nosetests tests).

**Comment by nbirnel** [comment]
What I have found is that python2 is not running any tests, whether through nosetests or python -m unittest. Python3 seems to be required (which is surprising to me for a python2.7 project). I wonder if I am missing anything else.

**Comment by brendandixon** [comment]
@nbirnel Python3 is *not* required. We run the tests under 2.6, 2.7, and 3.4 as part of our CI.
