### ISSUE TITLE
2.1.x versions do not detect the status of extensions installed using 2.0.x versions.

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#337]
The 2.0.x branch writes/reads extension state (and status) to/from (essentially) `/var/lib/waagent/<extension directory>/config/HandlerState`. The 2.1.x branch writes/reads that same state to/from (essentially) `/var/lib/handler_state/<extension directory>/state`.

We need to modify the 2.1.x branch to write/read the state in same manner as the 2.0.x branch (since such state should be part of the extension files). And we'll need to write code that migrates any such state incorrectly written to `/var/lib/handler_state` to those correct locations.

**Comment by ahmetalpbalkan** [comment]
hmm I remember the spec was saying the agent will not store any extension handler state, so extensions should manage it themselves. What does it store?

**Comment by brendandixon** [comment]
@ahmetalpbalkan It saves what state (e.g., enabled, installed) it believes the extension to be in. It is part of its state machine processing.

**Comment by hglkrijger** [comment]
I have verified the following scenarios:

- 2.0.x + ext -> 2.1.5 (ext re-installed) -> 2.1.5.2 (ext migrated)
- 2.0.x + ext -> 2.1.5.2 (ext migrated)
- 2.1.5 + ext -> 2.1.5.2 (ext migrated)

I think we can close this issue.

**Comment by hglkrijger** [comment]
adding a note, this was fixed by #340
