### ISSUE TITLE
Behavior does not match published documentation

### ISSUE THREAD

**Issue by shcleste** [Azure/WALinuxAgent#342]
Documentation at: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-agent-user-guide/#ubuntu-cloud-images states

```
•The following configuration parameters have no effect on Ubuntu Cloud Images that use cloud-init to manage the resource disk and swap space:
•ResourceDisk.Format
•ResourceDisk.Filesystem
•ResourceDisk.MountPoint
•ResourceDisk.EnableSwap
•ResourceDisk.SwapSizeMB
```

ResourceDisk.Format=y
ResourceDisk.Filesystem=ext4
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.EnableSwap=y
ResourceDisk.SwapSizeMB=2048

Restarted the agent:
root@AZUbuntu1404ARM:/etc# service walinuxagent restart
walinuxagent stop/waiting
walinuxagent start/running, process 2926

And checked that the agent created a swap file.
root@AZUbuntu1404ARM:/etc# swapon -s
Filename Type Size Used Priority /mnt/resource/swapfile file 2097148 0 -1

This behavior has caused confusion for customers, and can cause issues as previously discussed at:
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1374115

**Comment by ahmetalpbalkan** [comment]
IMO

> The following configuration parameters have no effect on Ubuntu Cloud Images that use cloud-init to manage the resource disk and swap space:

we should just change this to

> The following configuration parameters **should not be modified** on Ubuntu Server or Debian images that use cloud-init to manage the resource disk and swap space:

**Comment by hglkrijger** [comment]
@szarkos if you agree, can we update the guidance?

**Comment by hglkrijger** [comment]
Docs appear to have been updating, closing
