### ISSUE TITLE
OvfEnv object stomping on sshd_config symlinks

### ISSUE THREAD

**Issue by caphrim007** [Azure/WALinuxAgent#349]
Hey folks,

I have a distribution that keeps the sshd_config file in different location than the Azure waagent expects it. We worked around that little bit by using a symlink to point to the sshd_config file that we store, but during the running of the Process() method of the OvfEnv object, the

```
ReplaceFileContentsAtomic(filepath, "\n".join(filter(lambda a:...
```

block overwrites this symlink. I was wondering if y'all would be open to a patch that checks the filepath to see if it is a symlink and instead use `SetFileContents` instead of `ReplaceFileContentsAtomic`.

We'd love to get off of a private fork of the code that we have, so I'm reaching out to see what I can do to accelerate that.

Thanks!

**Comment by ahmetalpbalkan** [comment]
@caphrim007 I think making `sshd_config` path configurable through waagent.conf would be a better solution rather than dealing with symlinks.

**Comment by brendandixon** [comment]
@caphrim007 @ahmetalpbalkan The OS.SshdConfigPath option sets the path to the sshd_config file (with a default value of `/etc/ssh/sshd_config`).

**Comment by ahmetalpbalkan** [comment]
ah great, then in that case @caphrim007 you need to configure this key in your distro image.

**Comment by caphrim007** [comment]
Excellent! I'll give that a shot!
