### ISSUE TITLE
[2.1.5]waagent doesn't delete /etc/resolv.conf during deprovisioning

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#351]
Description of problem:
After deprovisioning, the /etc/resolv.conf is not deleted.

Version-Release number of selected component (if applicable):
WALinuxAgent-2.1.5

RHEL Version:
RHEL-7.3 internal build

How reproducible:
100%

Steps to Reproduce:
1. Prepare a RHEL7.3 VM on Azure. Check /etc/resolv.conf:
\# ls -l /etc/resolv.conf
-rw-r--r--. 1 root root 125 Aug  8 10:18 /etc/resolv.conf
2. Deprovision the VM:
\# waagent -deprovision and input 'y' to execute deprovisioning.
3. Check the messages:
WARNING! The waagent service will be stopped.
WARNING! All SSH host key pairs will be deleted.
WARNING! Cached DHCP leases will be deleted.
WARNING! root password will be disabled. You will not be able to login as root.
Do you want to proceed (y/n)y
4. Check the /etc/resolv.conf
\# ls -l /etc/resolv.conf
-rw-r--r--. 1 root root 125 Aug  8 10:18 /etc/resolv.conf

Actual results:
There's no WARNING message to show that /etc/resolv.conf file will be deleted.
The /etc/resolv.conf file is not deleted after deprovisioning.

Expected results:
There's a WARNING message to show that /etc/resolv.conf file will be deleted.
The /etc/resolv.conf file is deleted after deprovisioning.

Additional info:
1. In WALinuxAgent-2.0.16 the /etc/resolv.conf is deleted during deprovisioning.
2. It seems that there's no code to delete /etc/resolv.conf in azurelinuxagent/pa/deprovision/default.py.

**Comment by hglkrijger** [comment]
@yuxisun1217, we pushed a fix to master - would you be able to verify the issue is resolved?

**Comment by yuxisun1217** [comment]
Hi @hglkrijger ,
Thank you for your update. I use v2.1.5.2 and try. It works well. :)
