### ISSUE TITLE
[2.0.16] Agent locks up when told to install version of extension that is not available

### ISSUE THREAD

**Issue by paulmey** [Azure/WALinuxAgent#355]
On Ubuntu 14.04, when goal state refers to a version of an extension for which no bundleUri can be found, the agent [stores xml](https://github.com/Azure/WALinuxAgent/blob/WALinuxAgent-2.0.16/waagent#L3700-L3722) where [it expects json](https://github.com/Azure/WALinuxAgent/blob/WALinuxAgent-2.0.16/waagent#L4098) during status reporting. The agent fails to report status to CRP/RDFE and the exception triggers a restart of the Agent.Run, which creates a new copy of the EnvMonitor object with it's monitor thread. After this loop happening every 15 seconds for about half a day, the agent starts run into its file handle limit and "too many open file" error start to emerge.

The case where an extension is removed from production does not seem to be handled at all. Since this has been seen in the wild, I'd recommend fixing/backporting this.

**Comment by brendandixon** [comment]
@paulmey We are no longer taking changes v2.0.x. And this bug does not exist in the v.2.1.x branch that is active.

**Comment by paulmey** [comment]
@brendandixon as long as you fix Ubuntu 14.04... :wink:

**Comment by brendandixon** [comment]
@paulmey v2.1.5+ cannot have *this* bug as it correctly parses and handles the Xml (no nasty reuse of attributes). v2.1.5 should be out by the end of the month as the default agent for Ubuntu 14.04.

**Comment by paulmey** [comment]
Thanks for the ETA!
