### ISSUE TITLE
[freebsd] Failed to copy ovf-env.xml and failed to get dvd device

### ISSUE THREAD

**Issue by xian123** [Azure/WALinuxAgent#356]
Find the "Failed to copy ovf-env.xml and failed to get dvd device" errors in /var/log/waagent.log and these errors will lead to provisioning time out when creating a vm on Azure.  BTW, the location is West Europe and the rate of repro is about 1/20 in my test.

cat /var/log/waagent.log
2016/08/11 09:36:30.994078 INFO Azure Linux Agent Version:2.1.4
2016/08/11 09:36:30.994879 INFO OS: freebsd 10.3
2016/08/11 09:36:30.996465 INFO Python: 2.7.11
2016/08/11 09:36:31.022885 INFO Run daemon
2016/08/11 09:36:31.199885 INFO Run provision handler.
2016/08/11 09:36:31.200427 INFO Copy ovf-env.xml.
2016/08/11 09:36:31.201543 ERROR Event: name=WALA, op=Provision, message=Failed to copy ovf-env.xml: (000008)(000007)Failed to get dvd device
2016/08/11 09:36:31.203407 INFO Activate resource disk
2016/08/11 09:36:31.342568 INFO Resource disk device da1 found.
........................

**Comment by hglkrijger** [comment]
@xian123, we made some small fixes in this area with 2.1.5, but they may be relevant to your issue. The latest release is 2.1.6. Could you test with either of these and let us know if it still occurs?

**Comment by hglkrijger** [comment]
I have not been able to reproduce this with the latest agent. Please re-open if you see this with >= 2.1.6 and have somewhat reliable repro steps.
