### ISSUE TITLE
503 Error Handling

### ISSUE THREAD

**Issue by danielsollondon** [Azure/WALinuxAgent#361]
Hi, can we consider changing the code to forever ignore (with sleeps) 503s from wireserver (and only wireserver). Wireserver can be assumed to be there by the agent. 

thanks.

**Comment by brendandixon** [comment]
We should change wire.py#call_wireserver to sleep the same LONG_WAITING_INTERVAL we do for httpclient.FORBIDDEN.

**Comment by hglkrijger** [comment]
merged, closing
