### ISSUE TITLE
[2.1.5]Sometimes there're redundant lines in sudoers.d/waagent

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#366]
Description of problem:
If deprovision a VM(don't delete user) than create a VM with the same username as before, there will be 2 lines with this user account in the /etc/sudoers.d/waagent. The detail steps are as follow. 

I'm not quite sure that why we have two commands: -deprovision and -deprovision+user but not just use -deprovision+user? On Azure UI, when I capture an image, it shows:
![screenshot from 2016-08-16 19-43-46](https://cloud.githubusercontent.com/assets/19280786/17697841/d3afedb8-63e9-11e6-9087-117196c4037d.png)
If I check the "I've run waagent -deprovision on the virtual machine"(so that the image os state is generalized), I need to provide a new username when I provision a new VM base on this image. And if I don't check that checkbox, the new username is not needed.
So it seems that it only expect two scenarios: run deprovision, or not run deprovision. But it doesn't expect a scenario that I run deprovision but not delete user. And I confuse that when I should use "-deprovision" but not "-deprovision+user".

Version: WALinuxAgent-2.1.5
RHEL Version: RHEL-7.3 internal build

Steps to Reproduce:
1. Prepare a RHEL7.3 VM on Azure(ASM mode) with user account "azureuser"
\# cat /etc/sudoers.d/waagent
azureuser ALL=(ALL) ALL
2. run "waagent -deprovision -force"
3. Shutdown the VM. And capture an image with "I have run "waagent -deprovision" on the virtual machine" checked
4. Create a new VM base on this image with user account "azureuser"
5. # cat /etc/sudoers.d/waagent
azureuser ALL=(ALL) ALL
azureuser ALL=(ALL) ALL

Additional Info:
There's no functional impact because "Where there are multiple matches, the last match is used"(In sudoers.man)

**Comment by brendandixon** [comment]
@yuxisun1217 The agent code, I believe, took this approach to minimize risk (vs. trying to parse and correctly rebuild the file).

**Comment by hglkrijger** [comment]
Since there is no functional impact, and this was intentional, I am closing this issue. @yuxisun1217, feel free to comment/reopen if you disagree.
