### ISSUE TITLE
[2.1.5] Agent modifies IP tables

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#368]
The agent modifies the IP tables to ensure it can reach the wireserver. Such updates are necessary only for VMs not contained in a VNET. The agent should restrict making such changing only to VMs not contained in a VNET.

**Comment by hglkrijger** [comment]
It already does. This code path, which is in `send_dhcp_req`, is only executed as part of a fallback when no `wireserver_route_exists` (non-vnet) and no `dhcp_cache_exists`.

**Comment by hglkrijger** [comment]
Closing this issue for now - feel free to open again if this does not meet requirements.
