### ISSUE TITLE
[2.1.5] The configuration parameters may need to be updated in waagent.conf

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#369]
This is an issue that is separated from #360 to record the configuration parameters we may need to update.

Role.ConfigurationConsumer (Useless in wala-2.1.5. Need to be removed)
Role.TopologyConsumer (Useless in wala-2.1.5. Need to be removed)
Role.StateConsumer (If we confirm that wala will not add this feature, we can remove this)
AutoUpdate.GAFamily (Due to brendandixon's explanation, this parameters cannot be removed from waagent.conf now, so may I suggest to add a comment for this in the waagent.conf that tell customers not to edit this value?)

**Comment by hglkrijger** [comment]
these have been merged
