### ISSUE TITLE
Rerunning a Custom Script Extension via an updated ARM template reruns the code from the original template

### ISSUE THREAD

**Issue by pedrams1** [Azure/WALinuxAgent#374]
Consider the following Custom Script Extension resource:

```json
        {
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[concat(variables('vm_name'), '/Bootstrap')]",
            "apiVersion": "[variables('virtual_machine_api_version')]",
            "location": "[parameters('region')]",
            "dependsOn": [
                "[resourceId('Microsoft.Compute/virtualMachines', variables('vm_name')]"
            "properties": {
                "publisher": "Microsoft.OSTCExtensions",
                "type": "CustomScriptForLinux",
                "typeHandlerVersion": "1.5",
                "autoUpgradeMinorVersion": true,
                "settings": {
                    "fileUris": [
                        ""
                    ],
                    "commandToExecute": "echo hello > /tmp/test.txt",
                    "enableInternalDNSCheck": false
                }
            }
        }
```

This should create a file with the word "hello" in it. If you updated the ARM template, changed the command to execute to something else and redeployed the template (in either complete or incremental mode) the Custom Script Extension will run again, but it'll run the same code it did when the Custom Script Extension was first deployed, it will not reflect the changes in the updated ARM template.

Sorry not sure if this issue belongs here or against the Custom Script Extension itself. I figured the Custom Script Extension isn't being updated to reflect the change and hence the issue must be related to the agent or something lower in the stack.

**Comment by ahmetalpbalkan** [comment]
@pedrams1 CustomScriptExtension provides a field called `timestamp`, if you just add this field to `"settings"` with any integer value and redeploy, commandToExecute will be executed again. You can keep changing `timestamp` value (or any other configuration in `settings` or `protectedSettings` keys) and redeploy as many times and the command will be executed again. Please read [`CustomScript/README.md`](https://github.com/Azure/azure-linux-extensions/blob/master/CustomScript/README.md).

Closing as it's not related to the agent.

**Comment by ahmetalpbalkan** [comment]
@pedrams1 if you're seeing the old command being executed even though you deploy a configuration change, let us know. We'll take a look.

**Comment by pedrams1** [comment]
@ahmetalpbalkan Will do - I'm going to test this hopefully this afternoon or on Monday. Sorry I should have checked the README first, I was following the quickstart templates and didn't see an option for this field.

On a site note - I've raised / commented on a few issues here and you're always super responsive & helpful. Just wanted to say thank you.
