### ISSUE TITLE
Debian package built per instructions has unmet pre-depends

### ISSUE THREAD

**Issue by nbirnel** [Azure/WALinuxAgent#386]
/home/ubuntu# dpkg -i walinuxagent_1.3-0ubuntu1_amd64.deb
    dpkg: regarding walinuxagent_1.3-0ubuntu1_amd64.deb containing walinuxagent, pre-dependency problem:
     walinuxagent pre-depends on walinuxagent-data-saver (= 1.3-0ubuntu1)
    
    dpkg: error processing archive walinuxagent_1.3-0ubuntu1_amd64.deb (--install):
     pre-dependency problem - not installing walinuxagent
    Errors were encountered while processing:
     walinuxagent_1.3-0ubuntu1_amd64.deb

`walinuxagent-data-server` is *not* required (or available) pulling from the Ubuntu repositories.

**Comment by hglkrijger** [comment]
We have decided to remove all packaging from this repo, and have it managed downstream (see #396). Closing this issue as a result.
