### ISSUE TITLE
[2.1.6] The updated WALA will be used after restart waagent twice even if its version is lower than the local version

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#387]
Description of problem:
If enable AutoUpdate, WALA will always use the updated WALA after restart waagent service twice, even if its version is echo to or lower than the local version.

Version-Release number of selected component (if applicable):
WALinuxAgent-2.1.6

RHEL Version:
RHEL-7.3 internal build

How reproducible:
100%

Steps to Reproduce:
1. Prepare a RHEL7 VM on Azure East US location(ASM mode) with WALA-2.1.6 installed. Enable AutoUpdate in the /etc/waagent.conf:
\# AutoUpdate.Enabled=y
\# AutoUpdate.GAFamily=Prod
2. restart waagent service
\# systemctl restart waagent
3. Wait until the new WALA package is downloaded.
(Now WALA still use the local version)
\# ps aux|grep -E "waagent|WALinux"
python -u /usr/sbin/waagent -run-exthandlers
4. restart waagent service again
\# systemctl restart waagent
5. Check the -run-exthandler process
\# ps aux|grep -E "waagent|WALinux"
python -u bin/WALinuxAgent-2.1.6-py2.7.egg -run-exthandlers

Actual results:
WALA uses the updated version(2.1.6), not the local version(2.1.6).

Expected results:
WALA uses the local version because the new version is not higher than the local version.

Additional info:
1. If change the local version to 2.1.7 in the /usr/lib/python2.7/site-packages/azurelinuxagent/common/version.py, this issue also exists.
2. If I delete the /var/lib/waagent/WALinuxAgent-2.1.6/ and then restart waagent service, it will use the local version(python -u /usr/sbin/waagent -run-exthandlers)

**Comment by brendandixon** [comment]
@yuxisun1217 Good catch! The last line in update.py#get_latest_agent (https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/ga/update.py#L299) should filter to return an agent whose version is greater than `CURRENT_VERSION`.
