### ISSUE TITLE
[2.1.5] python setup.py install --register-service doesn't start service

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#391]
Hi,

I notice that in the v2.1.5, the "python setup.py install --register-service" doesn't start waagent service any more, which does start waagent service in the v2.1.4. Perhaps it's because the "Agent(False).register_service()" change to "get_osutil().register_agent_service()" in the setup.py script. And the get_osutil().register_agent_service function only register the service but not start the service. 
Is it the expected result? Thanks!

**Comment by hglkrijger** [comment]
Fix is merged, closing
