### ISSUE TITLE
Fedora23 vm formatting and mounting resource disk as ntfs instead of ext4

### ISSUE THREAD

**Issue by Priya91** [Azure/WALinuxAgent#392]
We are using fedora23 images from azure in [dotnet/corefx](https://github.com/dotnet/corefx) in our Jenkins CI. The /etc/waagent.conf has the configuration as

![image](https://cloud.githubusercontent.com/assets/7853870/18016010/046eecdc-6b7f-11e6-95a6-56c814cb41da.png)

And the provisioning logs show,

```
[dotnet-bot@fedora-test ~]$ cat /var/log/waagent.log | grep ext4
2016/08/25 17:28:46 Resource disk (/dev/sdb1) is mounted at /mnt/resource with fstype ext4
```

But still upon vm creation, checking the mount type,

```
[dotnet-bot@fedora-test ~]$ mount | grep resource
/dev/sdb1 on /mnt/resource type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)

[dotnet-bot@fedora-test ~]$ sudo lsblk -o type,name,mountpoint,fstype
TYPE NAME   MOUNTPOINT    FSTYPE
disk sda
part ├─sda1 /boot         ext4
part └─sda2 /             xfs
disk sdb
part └─sdb1 /mnt/resource ntfs
rom  sr0                  udf
```

Not sure how the mount type is changed..

Tracking issue in corefx: [#9293](https://github.com/dotnet/corefx/issues/9293)

**Comment by hglkrijger** [comment]
@Priya91, thanks for logging this issue. Actually all ephemeral drives in Azure start as ntfs, and then the guest agent or cloud-init formats them for Linux. We have seen this issue before, and it could be for a number of reasons. 

How reproducible is this for you? Could you let me have the VM sku and image urn, as well as repro steps, if possible with the Azure CLI?

**Comment by Priya91** [comment]
> How reproducible is this for you?

Everytime the vm is provisioned from image.

>  Could you let me have the VM sku and image urn, as well as repro steps, if possible with the Azure CLI?

The image is under team's storageaccount customized with extra install packages for dotnet. What would be best way to share the required data without compromising security ?

**Comment by hglkrijger** [comment]
Is it reproducible with the public base image?

What is the VM sku?

**Comment by Priya91** [comment]
> Is it reproducible with the public base image?

Haven't tried this.

> What is the VM sku?

 uname -a
```Linux Azure0829100424 4.4.9-300.fc23.x86_64 #1 SMP Wed May 4 23:56:27 UTC 2016 x                                              86_64 x86_64 x86_64 GNU/Linux```

cat /etc/os-release
```
NAME=Fedora
VERSION="23 (Twenty Three)"
ID=fedora
VERSION_ID=23
PRETTY_NAME="Fedora 23 (Twenty Three)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:23"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=23
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=23
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
```

**Comment by hglkrijger** [comment]
Please try reproduce this with the base image.

VM sku refers to the Azure hardware instance sizing, for example A0, D2, D2_V2, etc.

**Comment by Priya91** [comment]
lol haha ok, yeah was not sure what you wanted with vm sku. I'll try with the public base image when i have time later in the week.

**Comment by Priya91** [comment]
Region: West US, VM Size: Standard_D3_v2

**Comment by Priya91** [comment]
From internal discussions, we have verified that the base image we used was custom prepared, as we couldn't find a public fedora23 image on azure marketplace. This problem could be happening due to wrong system setup configurations, but no idea how to debug to get to the cause of problem.. Any ideas on how we can fix this or docs pointing to debugging such failures will be helpful ..

**Comment by hglkrijger** [comment]
I suspect then that this instance of the problem is due to the following: 

- Fedora is not supported as an agent distribution
- agent falls back to behavior which expects cloud-init to take care of the formatting

I would need to take a closer look to confirm, but if you must have Fedora support, then I recommend updating your custom image to use cloud init. 

Out of interest, why is Fedora one of the supported distros in CoreFX ahead of those which _are_ supported in Azure?

**Comment by mmitche** [comment]
@hglkrijger Thanks for the info.  It's not ahead, it's in addition.  We have a large number of other distros and this is just one we run in our outer-loop testing.
