### ISSUE TITLE
[2.1.6] Is "NetworkManager" a must for WALA in RHEL-7?

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#401]
Hi,

I only find some information that "recommend not remove" or "not conflict with" NetworkManager in RHEL-7 or CentOS-7 here:
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-centos/
https://github.com/Azure/WALinuxAgent/pull/129
But it seems that if I remove NetworkManager, there're error messages in the /var/log/waagent.log:
2016/08/31 22:33:53.018886 ERROR run cmd 'service NetworkManager restart' failed
2016/08/31 22:33:53.060207 ERROR Error Code:5
2016/08/31 22:33:53.089492 ERROR Result:Redirecting to /bin/systemctl restart  NetworkManager.service
Failed to restart NetworkManager.service: Unit not found.

I'm not quite sure if NetworkManager is a must for WALA in RHEL-7. If it is, I'd like to add the NetworkManager into the rpm package spec requirements.
Thanks!

**Comment by yuxisun1217** [comment]
If the NetworkManger is not a required package, there is a weird issue:
1. Prepare a RHEL-7 vhd with NetworkManager removed.
2. Create(provision) a VM base on that.
3. Run "systemctl status waagent"
# systemctl status waagent
● waagent.service - Azure Linux Agent
   Loaded: loaded (/usr/lib/systemd/system/waagent.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-09-01 14:11:58 CST; 1h 0min ago
 Main PID: 1025 (python)
   CGroup: /system.slice/waagent.service
           ├─1025 /usr/bin/python -u /usr/sbin/waagent -daemon
           ├─2300 /sbin/dhclient -H wala730825a4 -1 -q -lf /var/lib/dhclient/dhclient--eth0.lease -pf /var/run/dhclient-eth0.pid eth0
           └─2376 python -u /usr/sbin/waagent -run-exthandlers

The dhclient process in the waagent cgroup. And if I restart waagent service, the dhclient will be stopped and never restart until network service restart or VM reboot. And if the dhclient process is stopped, the waagent will keep checking the pidof dhclient and print error logs. Then if I reboot the VM, the dhclient process belongs to the network service so that this issue doesn't exist.

I didn't find any code in WALA about starting dhclient process during provisioning. And I'm trying to confirm that it's related to WALA or related to the systemd. Could you please help to confirm that what WALA does about the dhclient during provisioning? Thank you very much!

**Comment by yuxisun1217** [comment]
We may find the root cause:
The publish_hostname function in azurelinuxagent/common/osutil/default.py calls the restart_if function, it executes "ifdown && ifup" which restarts the dhclient process. So that the dhclient process belongs to the waagent service CGroup.

**Comment by hglkrijger** [comment]
@yuxisun1217 - we discussed this internally, and believe we should make NetworkManager required for WALA in RHEL-7. Could you please add it to the rpm spec?

**Comment by yuxisun1217** [comment]
@hglkrijger 
Thanks Hans! I'll add the NetworkManager requirement into the rpm spec file for RHEL-7.

**Comment by hglkrijger** [comment]
@yuxisun1217 great, thanks. closing this issue then

**Comment by nmikuni** [comment]
@hglkrijger Hi, I'm sorry for commenting to closed issue.
I'm using WALA 2.2.18. Is the NetworkManeger still required? Is there any document about WALA's requirement in order to catch up to latest version's info?

Thanks.
