### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by pablolibo** [Azure/WALinuxAgent#409]
Hi guys, I've checked some issue with Blob Storage and waagent,

```
2016/09/06 15:01:38 ERROR:Retry=1
2016/09/06 15:01:38 ERROR:HTTP Req: HEAD https://xxxxxxxxxx.blob.core.windows.net/vhds/Prod01nginx01.xxxxxxxxxxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxxx.status?sv=2014-02-14&sr=b&sig=w8Tl%2FjDfKJpBw%2FczXk6v1h9EbzHsz2yj8if%2BPKPClt8%3D&se=9999-01-01T00%3A00%3A00Z&sp=rw
2016/09/06 15:01:38 ERROR:HTTP Req: Data=None
2016/09/06 15:01:38 ERROR:HTTP Req: Header={'x-ms-version': '2014-02-14', 'x-ms-date': '2016-09-06T18:01:28Z'}
2016/09/06 15:01:38 ERROR:HTTP Err: Status=404
2016/09/06 15:01:38 ERROR:HTTP Err: Reason=The specified blob does not exist.
2016/09/06 15:01:38 ERROR:HTTP Err: Header=[('transfer-encoding', 'chunked'), ('date', 'Tue, 06 Sep 2016 18:01:37 GMT'), ('x-ms-request-id', '15a86c23-0001-005e-1968-08bbf3000000'), ('x-ms-version', '2014-02-14'), ('server', 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0')]
2016/09/06 15:01:38 ERROR:HTTP Err: Body=
```
The blob is creating and working

Do you have idea about this problem?

Thanks

**Comment by hglkrijger** [comment]
@pablolibo, does the error persist or was this a transient issue?

**Comment by hglkrijger** [comment]
Assuming this was a transient issue - feel free to reopen if not.

**Comment by pritz2** [comment]
I'm seeing this issue in a vmss! From the azure portal I see
"VM 'xxxxxxxxxxx' has not reported status for VM agent or extensions. Please verify the VM has a running VM agent, and can establish outbound connections to Azure storage."

So I deleted one of the VMs and ran the same thing. Now the new VM shows no error logs and is working fine, but the old VMs all still show the same "The specified blob does not exist" message when trying to upload a 'success' status
