### ISSUE TITLE
Agent should not attempt to install extensions on unsupported distributions

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#410]
The agent should "whitelist" approved / supported distributions (by vendor with minimal version numbers) and skip extension processing on unsupported distributions. Status and provisioning should still run.

**Comment by hglkrijger** [comment]
Is this something we want to own, or can we push the support decision to the extension?

**Comment by brendandixon** [comment]
This is different than that: This is recognizing that we're running on a distribution we do not fully support and we do no extension processing at all.

**Comment by hglkrijger** [comment]
Got it

**Comment by brendandixon** [comment]
Closing as the issue will be addressed in other ways.
