### ISSUE TITLE
[2.1.6] How does "Provisioning.Enabled=n" work now?

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#411]
Hi,

In 2.1.6, if I set "Provisioning.Enabled=n" in the waagent.conf, run "waagent -deprovision", capture a image with "I've run waagent -deprovision" checked, then create a VM base on this image, the VM status is always "Running(Provisioning)" and after a long time becomes "Running(Provisioning Timeout)". And when I ssh into this VM, there's no "/var/lib/waagent/provisioned" file generated. Is it true?
I remember that in WALA-2.0.16, the VM can be created successfully. The status becomes "Running" and the "/var/lib/waagent/provisioned" file is generated.
In my opinion, if I set "Provisioning.Enabled=n", it means I'll use other tools to provision this VM. So I think wala should put the "provisioned" file there and the VM status should become "Running" without warning. Is it right? Thank you very much!

WALA version: 2.1.6
RHEL version: RHEL-6.8

Steps:
1. Prepare a VM on ASM mode. Set "Provisioning.Enabled=n" into the /etc/waagent.conf
2. Run "waagent -deprovision -force"
3. Deallocate this VM. Capture an image with "I've run waagent -deprovision" checked.
4. Create a VM base on this image.
5. Check the VM status. Check if the /var/lib/waagent/provisioned file is generated.

Actual result:
The VM status is Running(Provisioning) and after a long time becomes "Running(Provisioning Timeout)"
There's no /var/lib/waagent/provisioned file inside this VM.

**Comment by hglkrijger** [comment]
Thanks @yuxisun1217, I will add this fix to the next release.

**Comment by yuxisun1217** [comment]
Thanks Hans!
