### ISSUE TITLE
Spams journal with `pidof dhlient` related messages

### ISSUE THREAD

**Issue by towolf** [Azure/WALinuxAgent#417]
We use our own image but we have the agent installed.

Since we are using systemd-networkd with its own DHCP stack, there is no dhclient being used.

How do we stop the log spam?  Is it safe to kill and disable this stuff?  it is there another solution? 

Relevant:

https://github.com/Azure/WALinuxAgent/issues/195#issuecomment-245983434

**Comment by hglkrijger** [comment]
@towolf, thanks for logging this issue. Today the agent has a built-in assumption that some form of dhclient will be available, and unfortunately there is currently no way to disable that check or error logging. I agree this is a poor experience, and we should take a change to improve it. I will investigate some more.

**Comment by hglkrijger** [comment]
@brendandixon, what do you think about something like this to prevent log spamming? https://github.com/hglkrijger/WALinuxAgent/commit/402bffbd734828e6b5eaa3bfed6655a1cce852a8 

@towolf, would you be willing to try this patch out and see if it resolves your issue?

**Comment by brendandixon** [comment]
lgtm

**Comment by towolf** [comment]
We have 2.1.3 installed. Patch from @hglkrijger of course does not apply to that. I'd like to test but need a version that this patch works against. Would the most recent release work?

**Comment by hglkrijger** [comment]
@towolf - yes, 2.1.6 would work or you could simply clone from my fork. Not sure which distro your image is based on, but something along these lines:
```
git clone https://github.com/hglkrijger/WALinuxAgent
cd WALinuxAgent
git checkout gh417
wget https://bootstrap.pypa.io/ez_setup.py -O - | python
python setup.py install
systemctl daemon-reload
service waagent restart
waagent --version
```
If you happen to be using Ubuntu 1604, which uses Python 3 by default, you would need to run `update-alternatives` first.
