### ISSUE TITLE
waagent updates to 2.1.6 but still shows 2.1.5

### ISSUE THREAD

**Issue by mabicca** [Azure/WALinuxAgent#418]
Hi everyone,

I have been seeing an issue where the 2.1.5 waagent automatically updated to 2.1.6:

2016/08/18 00:00:23.675275 INFO Instantiating Agent WALinuxAgent-2.1.6 from disk
2016/08/18 00:00:23.683873 INFO Agent WALinuxAgent-2.1.6 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/08/18 00:00:23.696464 INFO Ensuring Agent WALinuxAgent-2.1.6 is downloaded
2016/08/18 00:00:23.704099 INFO Agent WALinuxAgent-2.1.6 was previously downloaded - skipping download
2016/08/18 00:00:23.714184 INFO Agent WALinuxAgent-2.1.6 loaded manifest from /var/lib/waagent/WALinuxAgent-2.1.6/HandlerManifest.json
2016/08/18 00:00:23.726333 INFO Determined Agent WALinuxAgent-2.1.6 to be the latest agent
2016/08/18 00:00:23.746267 INFO Agent WALinuxAgent-2.1.6 launched with command 'python -u bin/WALinuxAgent-2.1.6-py2.7.egg -run-exthandlers'
2016/08/18 00:00:23.814628 INFO Agent WALinuxAgent-2.1.6 is running as the goal state agen

Here you can see that the 2.1.6 version is being loaded:
[root@centos72 log]# systemctl status waagent
● waagent.service - Azure Linux Agent
   Loaded: loaded (/usr/lib/systemd/system/waagent.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-09-12 20:35:29 UTC; 7min ago
 Main PID: 947 (python)
   CGroup: /system.slice/waagent.service
           ├─ 947 /usr/bin/python -u /usr/sbin/waagent -daemon
           ├─1079 python -u bin/WALinuxAgent-2.1.6-py2.7.egg -run-exthandlers
           ├─1136 python /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007/diagnostic.py -daemon
           └─1239 /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007/bin/mdsd -A -C -c /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007/...

However, if you run: waagent -version you still see 2.1.5
# waagent -version
WALinuxAgent-2.1.5 running on centos 7.2.1511
Python: 2.7.5

It seems to happen in any distro that has 2.1.5 installed, this one in particular I tested it on CentOS 7.2.

**Comment by brendandixon** [comment]
@mabicca This is expected behavior. The updated agent does not overwrite the installed agent, but runs as sub-process and receives control only over extension processing.

**Comment by mabicca** [comment]
@brendandixon would it be possible to maybe include that in the output for waagent -version or something? most customers are familiar with the waagent -version command and that might be somewhat confusing moving forward. There is also some troubleshooting documents where we ask customers to run that to quickly see the version.

**Comment by brendandixon** [comment]
@mabicca Not easily at this time. However, the version running is *always* that reported in the /var/log/waagent.log file, regardless of the output of this command. A quick grep of that file (for last instance of a line with `Azure Linux Agent Version`.

**Comment by mabicca** [comment]
hi @brendandixon if possible I would like to keep this open, this is not as easy for customers, having to grep a log to find the version is a little bit confusing for majority of customers. Also, most of the documentation out there talks about using waagent -version too. Please , let me know if it's ok to keep this open for now until we can correct the behavior.

**Comment by brendandixon** [comment]
@mabicca Sure. But I cannot estimate when we might be able to make improvements.

**Comment by mabicca** [comment]
That should be ok @brendandixon just don't want to lose track/reference on this for now.
Thank you.
