### ISSUE TITLE
walinuxagent.service should not Want or After on cloud-final.service

### ISSUE THREAD

**Issue by smoser** [Azure/WALinuxAgent#425]
As filed in launchpad at [bug 1623570](https://bugs.launchpad.net/bugs/1623570) we've come across some issues with the After and Wants in walinux-agent.service.

This was noticed due to change to cloud-init for [bug 1576692](http://bugs.launchpad.net/bugs/1576692).  However, it is not clear why either of those were added to the unit.

**Comment by brendandixon** [comment]
Fixed by #425.
