### ISSUE TITLE
Walinux agent 2.1.6 does not work when the guest linux vm has 4 vcpus. 

### ISSUE THREAD

**Issue by kumarv330** [Azure/WALinuxAgent#433]
When the guest linux vm has 2 vcpus, the walinuxagent works fine. When I selected 4 vcpus for the same vm image, the kernel keeps crashing. If I disable the walinuxagent for the same image, the guest vm wtih 4 vcpus works fine.

**Comment by jinhyunr** [comment]
If you can provide VMAgent log, that will be great. Otherwise, we would not have much details..

**Comment by hglkrijger** [comment]
@kumarv330 - let us know if you can reproduce this on the latest agent, and if so please provide logs.
