### ISSUE TITLE
Support for F5 Networks BIG-IP

### ISSUE THREAD

**Issue by caphrim007** [Azure/WALinuxAgent#446]
A fork of WAAgent is currently maintained out-of-band by F5 Networks that includes a number of changes to the WAAgent code to make it work correctly on BIG-IP. We would like to move to the newer WAAgnet code and do away with our OOB hacks.

I think that WAAgent has matured to the point where this is possible, so with that said I'd like to see the BIG-IP family of OS's supported natively by WAAgent.

**Comment by hglkrijger** [comment]
@caphrim007 is this done with #498?

**Comment by caphrim007** [comment]
@hglkrijger I think "enough" of it is done. There are still traces remaining that we're filing more PRs for.

**Comment by hglkrijger** [comment]
@caphrim007 ok, sounds like we can mark this done; closing.
