### ISSUE TITLE
[2.2.0]waagent unexpectedly restart when create a VM base on a specialized image

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#460]
Description of problem:
There's an error log "WALinuxAgent-2.2.0 unexpectedly restarted" in the waagent.log when create a VM base on a specialized image. The specialized image is captured when the base VM is running.

Version-Release number of selected component (if applicable):
WALinuxAgent-2.2.0/2.1.6

RHEL Version: RHEL-7.3

How reproducible:
100%

Steps to Reproduce:
1. Prepare a VM with WALA-2.2.0 installed on ASM mode.
2. Capture a specialized image from this VM.(Capture when the VM is running)
3. Create a new VM base on this image.
4. Check the waagent.log
 
Actual Result:
"WALinuxAgent-2.2.0 unexpectedly restarted" message exists in the waagent.log.

/var/log/waagent.log:
2016/10/09 13:56:28.079588 INFO Start env monitor service.
2016/10/09 13:56:28.085487 INFO Configure routes
2016/10/09 13:56:28.091958 VERBOSE Found event file: /var/lib/waagent/events/1475992177311592.tld
2016/10/09 13:56:28.093109 INFO Gateway:None
2016/10/09 13:56:28.097999 INFO Routes:None
2016/10/09 13:56:28.106174 VERBOSE run cmd 'pidof dhclient'
2016/10/09 13:56:28.144945 VERBOSE Processed event file: /var/lib/waagent/events/1475992177311592.tld
2016/10/09 13:56:28.155009 VERBOSE Found event file: /var/lib/waagent/events/1475992588091745.tld
2016/10/09 13:56:28.185060 VERBOSE Processed event file: /var/lib/waagent/events/1475992588091745.tld
2016/10/09 13:56:28.195144 INFO Set block dev timeout: sda with timeout: 300
2016/10/09 13:56:28.196404 INFO WALinuxAgent-2.2.0 running as process 2103
2016/10/09 13:56:28.198425 VERBOSE Sleep 1 second to avoid throttling.
2016/10/09 13:56:28.212005 INFO Set block dev timeout: sdb with timeout: 300
2016/10/09 13:56:28.227663 INFO WALinuxAgent-2.2.0 unexpectedly restarted
2016/10/09 13:56:28.234527 ERROR Event: name=WALinuxAgent, op=Restart, message=WALinuxAgent-2.2.0 unexpectedly restarted
2016/10/09 13:56:28.246089 INFO Checking for agent family Prod updates

Expect Result:
waagent is not restarted unexpectedly.

Additional Info:
1. No functional impact is observed.
2. The root cause might be this:
   i). Only if the /var/lib/waagent/current_version file exists and the content is equal to the current wala version, the unexpectedly restart is touched off.
   ii). When the waagent service is stopping, waagent removes the current_version file. When the waagent service is starting, waagent create the current_version file.
   iii). Capture clone the OS disk when the VM is running, so the current_version is not removed. When a new VM is created base on this OS disk, the current_version file is already there and the content is equal to the current wala version.

**Comment by brendandixon** [comment]
@yuxisun1217 The message does not mean that the agent was restarted unexpectedly, but that it was not cleanly shutdown. (The message could be more clear.) The agent writes a sentinel file used to track clean start-up / shutdown of the Goal State Processing extension code. If agent starts the extensions and finds the file present from a prior run, it emits this message. It is not an error unless accompanied by other errors.

I hope this clears things up a bit.

**Comment by yuxisun1217** [comment]
Hi @brendandixon ,
Thank you very much for your explanation and I realize it now :) I quite agree that it's reasonable to restart the service because the service was not cleanly stopped during capture. 
And as you said, perhaps it's better to log more details if possible(or not to log error message if it is not really an unexpectedly action), because I think users might feel confused to see an "unexpectedly restart" error message.

**Comment by brendandixon** [comment]
@yuxisun1217 This is addressed in #462.

**Comment by yuxisun1217** [comment]
Got it. Thanks @brendandixon !
