### ISSUE TITLE
ERROR:socket IOError  args: (101, 'Network is unreachable') in waagnet log file 

### ISSUE THREAD

**Issue by kailashkkd** [Azure/WALinuxAgent#461]
Hi All,

I am working on a case where the user is using a CentOS 7.2 vms.
one day his 3vm's were hanged and he has to restart from the portal to login into to the vm.
we could not get much info messages file of the servers,
but in the waagent file, we could see many errors.
can someone help me in knowing why this errors occurs and what does these erros mean.

ERROR:socket IOError  args: (110, 'Connection timed out')
ERROR:HttpPutBlockBlob(https://ew1ss01sto01.blob.core.windows.net/vhds/ew1-
ERROR:sleep 10 seconds HttpPutBlockBlob(https://ew1ss01sto01.blob.core.wind
ERROR:retry HttpPutBlockBlob(https://ew1ss01sto01.blob.core.windows.net/vhd
ERROR:response HttpPutBlockBlob(https://ew1ss01sto01.blob.core.windows.net/
ERROR:return HttpPutBlockBlob(https://ew1ss01sto01.blob.core.windows.net/vh
ERROR:CalledProcessError.  Error Code is 1
ERROR:CalledProcessError.  Command string was pidof dhclient
ERROR:CalledProcessError.  Command result was 
ERROR:CalledProcessError.  Error Code is 1
ERROR:CalledProcessError.  Command string was pidof dhclient
ERROR:CalledProcessError.  Command result was 
ERROR:socket IOError  args: (101, 'Network is unreachable')
ERROR:HttpPost(/machine?comp=health),retry=0,status=None
ERROR:sleep 10 seconds HttpPost(/machine?comp=health),retry=0,status=None

Thanks 

Kailash B

**Comment by jinhyunr** [comment]
It usually indicates that VM Agent is having trouble making an outbound network connection. 

Did the issue start to appear on the VMs which used to work? Do you have a customized network settings which may block VM Agent to send/receive REST call?

**Comment by kailashkkd** [comment]
The VM was running and suddenly it went to hung state, the user has to restart the VM from the portal so that he can coonect again. Once he restarted , he was able to connect. About the Network settings ,I will check and update you . can you please explain more on the issue?

**Comment by kailashkkd** [comment]
Firstly there is no NSG configured in this case.
Network settings seems fine. 
Any thing else you want me to check?

**Comment by jinhyunr** [comment]
If you could grep logs share the /var/logs/waagent.log and files from /var/lib/waagent, that would be great-!

**Comment by kailashkkd** [comment]
[waagent.txt](https://github.com/Azure/WALinuxAgent/files/535034/waagent.txt)
I have uploaded the waagent.log file .
please let me know if you need anything else

**Comment by kailashkkd** [comment]
@jinhyunr Any update for me on this?

**Comment by jinhyunr** [comment]
Hey @kailashkkd,
sorry for the late reply. I will take a look. Meanwhile, I advise to see upgrading to the latest version of linux agent fixes the issue. From the log, it seems that the version is 2.0.11, which is quite old. The latest version is 2.2.0 with considerable amount of changes.

**Comment by mabicca** [comment]
I was also going to ask, do we have anywhere the requirements on what needs to be open/setup for the waagent to communicate properly?

I see a lot of customers that they need for instance to block all traffic outbound to Internet so it would be good to see the basic ports and ip ranges that we need to be open to make sure the agent communication is not blocked.

**Comment by brendandixon** [comment]
@mabicca The agent requires access, among other things, Azure Storage in its region. It discovers those IPs dynamically. The Azure Storage team *may* publish their IP ranges.

**Comment by mabicca** [comment]
hi @brendandixon yes, thanks so I guess I'll look for those ranges and I know that we also need to have 168.63.129.16 whitelisted as well.

**Comment by kailashkkd** [comment]
Guys are you saying that VM and the storage group have to be in the same location ,
Also can u explain more on how walinuxagent works.

**Comment by mabicca** [comment]
hi @kailashkkd I would recommend reading this:
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-agent-user-guide/

In regards of storage, Brendan just mentioned that the agent will need to be able to access the storage, which is usually in the same region as the VM.

**Comment by kailashkkd** [comment]
Thanks @mabicca   @brendandixon. Lots of useful stuff here

**Comment by jasonzio** [comment]
The current set of Azure IP address ranges are always available from [this document](https://www.microsoft.com/en-us/download/details.aspx?id=41653), which is continually updated.

**Comment by hglkrijger** [comment]
Looks like this has been discussed to completion, closing
