### ISSUE TITLE
Ensure the transport certificate expires in no more than two years

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#463]
The code needs to set a two-year expiration on the transport certificate and check for / replace nearly expired certificates.

**Comment by yuhuijiang** [comment]
Hi @brendandixon @hglkrijger ,
As you know,we are planning to use cloud-init replace WALA doing provision process in RHEL7.4.
But the certificate exporation date is still 32768 in cloud-init,so this enhancement in v2.2.11 seems make no sense. 
Any suggestions?
Thx.

**Comment by brendandixon** [comment]
@yuhuijiang The changes affects the life of the *transport* certificate the agent uses in exchanging data with wireserver. So, the change "makes sense" both for VMs provisioned with cloud-init and those provisioned using the agent. (The agent continues to exist to manage extensions on cloud-init provisioned VMs.)
