### ISSUE TITLE
opt-out of all network management

### ISSUE THREAD

**Issue by colemickens** [Azure/WALinuxAgent#466]
Is it possible to completely opt-out of network management from waagent?

I'm on 2.1.5 and don't want the agent to do anything at all except report ProvisioningStatus to CRP so my VM doesn't get rebooted. I understand that in the future I will be able to tell the platform to leave my VM alone and I can omit the agent... For now, how can I opt out of `waagent` managing my network at all.

Do I have to add a new "distro" variant and make the networking functions noops, or is there an easier switch I can flip?

**Comment by hglkrijger** [comment]
@colemickens, you would need to add a new variant at the moment.

**Comment by colemickens** [comment]
Thanks @hglkrijger. Do you know, can I boot VMs in Azure without the agent entirely? I thought there was a status signal that needed to be sent to keep CRP from rebooting me... but I was recently told that was not the case. Any idea?

**Comment by hglkrijger** [comment]
I think @jinhyunr has more knowledge on this, but as far as I know it is still required for Linux..

**Comment by colemickens** [comment]
@jinhyunr Any idea about this?

**Comment by colemickens** [comment]
ping. @jinhyunr do you know when Azure will let me run Linux VMs without needing the agent to write the status blob?

**Comment by hglkrijger** [comment]
@colemickens - hopefully this semester.

**Comment by hglkrijger** [comment]
@colemickens - can we close this issue?
