### ISSUE TITLE
Package upgrade can disable RDMA configuration

### ISSUE THREAD

**Issue by szarkos** [Azure/WALinuxAgent#467]
Typically, when a package is upgraded the /etc/waagent.conf file will not be replaced with the new one if it has been modified. This is because, for example, if a customer modifies waagent.conf to configure swap space they would not want those changes overwritten with a default waagent.conf on package upgrade.

This has implications for HPC images because in 2.2.0 there is now a new configuration parameter called OS.EnableRDMA, and the old parameters OS.UpdateRdmaDriver & OS.UpdateRdmaDriver are obsolete. So customers upgrading the agent package on their existing HPC images will see their RDMA adapters are not be configured and need to manually modify their waagent.conf file with the new parameter to re-enable RDMA driver/interface initialization.

Maybe there's a better way to do this, but probably the easiest is to just equate the old parameters to OS.EnableRDMA in conf.py, i.e.:

```
def enable_rdma(conf=__conf__):
    if conf.get_switch("OS.EnableRDMA", False):
        return True
    elif conf.get_switch("OS.UpdateRdmaDriver", False) or conf.get_switch("OS.UpdateRdmaDriver", False):
        return True
    else:
        return False
```

**Comment by hglkrijger** [comment]
fixed with #507
