### ISSUE TITLE
[2.2.0]waagent fails to run "swapon" in xfs file system

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#468]
Description of problem:
If set resource disk file system as "xfs", the waagent fails to run "swapon" to the swapfile. "ERROR Result:swapon: /mnt/resource/swapfile: swapon failed: Invalid argument"

Version-Release number of selected component (if applicable):
WALinuxAgent-2.2.0

RHEL Version: RHEL-7.3 internal build

How reproducible:
100%

Steps to Reproduce:
1. Prepare a VM with WALA-2.2.0 installed on ASM mode.
2. Set "ResourceDisk.Filesystem=xfs" in the /etc/waagent.conf
3. Deprovision. Shutdown this VM. Capture a generalized image from this VM.
4. Create a new VM base on this image.
5. Check swapsize
    # free -m

Actual Result:
swapsize is 0. Fail to enable swap.

/var/log/waagent.log:
2016/10/14 15:39:39.144948 VERBOSE run cmd 'mkfs.xfs /dev/sdb1 -f'
2016/10/14 15:39:39.743088 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2016/10/14 15:39:40.162923 INFO Resource disk /dev/sdb is mounted at /mnt/resource with xfs
2016/10/14 15:39:40.199074 INFO Enable swap
2016/10/14 15:39:40.203751 VERBOSE run cmd 'swapon -s'
2016/10/14 15:39:40.267425 INFO Create swap file
2016/10/14 15:39:40.272537 VERBOSE run cmd 'umask 0077 && fallocate -l 2147483648 '/mnt/resource/swapfile''
2016/10/14 15:39:40.390053 VERBOSE run cmd 'mkswap /mnt/resource/swapfile'
2016/10/14 15:39:40.475485 VERBOSE run cmd 'swapon /mnt/resource/swapfile'
2016/10/14 15:39:40.560859 ERROR run cmd 'swapon /mnt/resource/swapfile' failed
2016/10/14 15:39:40.568498 ERROR Error Code:255
2016/10/14 15:39:40.591525 ERROR Result:swapon: /mnt/resource/swapfile: swapon failed: Invalid argument

2016/10/14 15:39:40.647574 ERROR Failed to enable swap (000005)/mnt/resource/swapfile

Expect Result:
Can enable swap in xfs file system.

Additional Info:
The fallocate does not physically allocate the space -- but swapon syscall requires a real space. (https://bugzilla.redhat.com/show_bug.cgi?id=1129205#c3)
So for xfs file system, perhaps we have to use "dd" instead of "fallocate". I tried "dd" then run "swapon" and it works well in xfs file system.

**Comment by jinhyunr** [comment]
Hello @yuxisun1217,
Thanks for the report.

First of all, was this working before v2.2.0? 
Second, If swapOn requires an actual physical space initialized with 0s, then would this be the case for any kind of Linux, not only bound to RHEL? Or are you suggesting RHEL version of 'swapon' requires an actuall space?

Thanks.

**Comment by yuxisun1217** [comment]
Hi @jinhyunr ,
1. Before v2.2.0 it doesn't support xfs file system because of this issue: #400 
2. It seems that at least CenOS7+ and RHEL7+ have this problem. (CentOS: http://unix.stackexchange.com/questions/294600/i-cant-enable-swap-space-on-centos-7). I'm sorry I'm not quite sure about other Linux platforms.

**Comment by hglkrijger** [comment]
Fixed with #502
