### ISSUE TITLE
AutoUpdate is enabled by default

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#473]
Hi,

We know that if there's no "AutoUpdate.Enabled" item in the /etc/waagent.conf, it's enabled by default. In RHEL-7/6 WALA package, we made a patch to set "AutoUpdate.Enabled=n" to disable it. But if users update WALA from 2.0.16 to 2.2.0 through "rpm -Uvh", the waagent.conf file is not changed so that there's no "AutoUpdate" item inside the waagent.conf file, which means the AutoUpdate is enabled. 
We wish this feature can be disabled unless users set "AutoUpdate.Enabled=y" themselves. So just a suggestion, is it possible to set the default value of "AutoUpdate.Enabled" as "False" in the conf.py? Thanks!

**Comment by brendandixon** [comment]
@yuxisun1217 It is in the best interest of Azure customers for `AutoUpdate.Enabled` to be true ('y'). We will not be changing the default.

**Comment by yuxisun1217** [comment]
OK, got it. Thank you very much @brendandixon !
