### ISSUE TITLE
Process a given GoalState just once

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#474]
The code in exthandlers.py#run notes that latest processed GoalState in `self.last_etag`, however it never checks the value before processing the GoalState. This can cause unnecessary work and redundant messages in the log files.

**Comment by jinhyunr** [comment]
Talked with Brendan and went trough the code offline. WALA is not processing GoalState when etag is not updated yet prints out excessive logs. Thus lowering the log level.

**Comment by hglkrijger** [comment]
fixed with #483
