### ISSUE TITLE
Wrong alarms are reported for GAFamily contains empty Uris on some data centers

### ISSUE THREAD

**Issue by ccic** [Azure/WALinuxAgent#488]
I created FreeBSD 10.3 VM on West Europe, and found the following error in /var/log/waagent.log:

> 2016/11/03 16:10:27.167205 ERROR Event: name=WALinuxAgent, op=Download, message=Incarnation 1 failed to get Prod package list: (000008)Failed to fetch ExtensionManifest from all sources

It does not hurt any features, but it misleads user to think about there is something wrong.
After investigation, I found it was caused by empty Uris in GAFamily element of ExtenstionsConfig.xml. That XML file sometimes contain empty Uris in GAFamily, sometimes contains empty GAFamily. I verified this by creating FreeBSD 10.3 VM again, and did not find the above error in waagent.log.

The invalid ExtensionsConfig.xml is like:
<?xml version="1.0" encoding="utf-8"?>
<Extensions version="1.0.0.0" goalStateIncarnation="1"><GuestAgentExtension xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <GAFamilies>
    **<GAFamily>
      <Name>Prod</Name>
      <Uris />
    </GAFamily>**
    ...

But a valid one is like:
<?xml version="1.0" encoding="utf-8"?>
<Extensions version="1.0.0.0" goalStateIncarnation="1"><GuestAgentExtension xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  **<GAFamilies />**
  <Location>westeurope</Location>
  <ServiceName>CRP</ServiceName>
</GuestAgentExtension>

**Comment by brendandixon** [comment]
@ccic Thank you. We saw this as well and have fixed it in #462.
