### ISSUE TITLE
Can't run waagent -deprovision using custom script extension

### ISSUE THREAD

**Issue by ashisa** [Azure/WALinuxAgent#489]
I am trying to deprovision a VM by running this script - https://raw.githubusercontent.com/ashisa/azuretoolkit/master/generalize.sh using the custom script extension. The extension gets installed and the execution starts but it seems the waagent command doesn't run at all. The script execution also seems to break then.

Can this be done at all?

**Comment by brendandixon** [comment]
@ashisa The agent installs and enables extensions, including the custom script extension. Deprovisioining, among other things, stops the agent. Deprovisioning from within the custom script extension _might_ work, but it may not. It is not a suggested or supported pattern.
