### ISSUE TITLE
Support for Infiniband Drivers on Ubuntu 16.04, SLES12SP2, and CentOS 7.3

### ISSUE THREAD

**Issue by shirgall** [Azure/WALinuxAgent#495]
We've been working to enable the Infiniband driver in Ubuntu 16.04 and we should examine if anything new is needed for SLES12SP2 or CentOS 6.8, 7.2, and 7.3.

Progress of Infiniband driver in Ubuntu tracked here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1641139

**Comment by brendandixon** [comment]
@shirgall And...what is the specific issue you have found?

**Comment by rjschwei** [comment]
Driver has been rebuild for SLES 12 SP2, repos are here:

https://drivers.suse.com/microsoft/Microsoft-RDMA/sle-12-sp2/install/

autoloading of driver has been tested with WALA 2.2.0 and it works as expected.

**Comment by hglkrijger** [comment]
@rjschwei @shirgall do we need to keep this issue open?

**Comment by rjschwei** [comment]
From the SUSE side this can be closed when we get the 2.2.3 release of the agent which I think is right around the corner.

**Comment by hglkrijger** [comment]
2.2.3 has been released, so closing this issue.
