### ISSUE TITLE
Python-setuptools requirements

### ISSUE THREAD

**Issue by mabicca** [Azure/WALinuxAgent#504]
Hi there,

Would it be possible to document the python-setuptools requirements or even better install that for our customers?

Something similar to what is described here could possibly help:
http://peak.telecommunity.com/dist/ez_setup.py

We have seen lots of customers that want to install the waagent 2.2.0+ manually and most of them do not have the knowledge of python so they end up having issues.

Even if we can't automate that install, we should at least show a warning with examples to install the setuptools for their distro, something along the lines of:

yum install python-setuptools
apt-get update && apt-get install python-setuptools

Thanks.

**Comment by mabicca** [comment]
Hi, do we have any updates around this? Will this be documented or are we also looking at the option of installing those tools too?

**Comment by brendandixon** [comment]
@mabicca While we support, we do not encourage users installing the agent directly from source. We prefer they pull from their vendor's repository (e.g., apt-get install walinuxagent). It is too easy to break the installation when installing by hand. We will not, as a result, either remove this requirement or install the tools. We are evaluating improving our hand-installation documentation.
