### ISSUE TITLE
Fails to reset password on a vm based on a captured image on which the reset password manipulation is done before

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#506]
Description of problem:
Fails to reset password on a vm created base on a captured image(specialized).
This image is captured from a vm on which the reset password is done.

Version-Release number of selected component (if applicable):
WALinuxAgent-2.2.1

How reproducible:
Always

Steps to Reproduce:
1. Prepare a VM and do reset password on it through portal.
2. Capture this VM as a image(DO NOT check "I've run waagent -deprovision). And create a new VM base on this image.
3. Do reset password on this new VM.
4. Try to use the new password to login the new VM

Actual results:
3. Fails to reset password on this new VM even it returns success on portal.
4. Fails to login the new VM.
The following is the log from /var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.6.0/extension.log.
```
2016/12/06 17:31:07 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence number is 0
2016/12/06 17:31:07 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/config/0.settings
2016/12/06 17:31:07 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIB6AYJKoZIhvcNAQcDoIIB2TCCAdUCAQAxggFxMIIBbQIBADBVMEExPzA9BgoJkiaJk/IsZAEZFi9XaW5kb3dzIEF6dXJlIFNlcnZpY2UgTWFuYWdlbWVudCBmb3IgRXh0ZW5zaW9ucwIQOfMLY+W36qFPyuCDJL3BrzANBgkqhkiG9w0BAQEFAASCAQAq2lglqcQ1CL0LyiuJBR4mfzmuqorXf7387E5k+YsZhgc3lHZeGKBSrDi3Ej89IRYhwYx3wd82ieu00vbPVTt6/BUVsTbDBjNjkiZYL8DdXUfapKl44eyBL04xRUCjwDPMXSHJqHZdP52P954OEjN5NoEmziK2nvl7AyWA12mWHR00NkAL63N4/vUzTFa5eViwf7I2Y9n0uPy1Gl1ewTPRDHNVnFRlUQLQkKSpWJ4No8m+ULPATye591azPkGFxbW7DdiJYzrwG1+5Q9bKv/E5BduJ6QgRb0dNPUi5fuLagx4QC3uuLc9raAZreamt4ei0pQIwNCctAUcitPny15ZZMFsGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIX2MYjGEcf1eAOLJI7E89pqe9XiKCOq8AnLt1giqx6iyhogkotRA5x4piRZerNbolmzSVw4cWYksWfzUU9OMuhgD+", "publicSettings": null, "protectedSettingsCertThumbprint": "1A65F7C761B060DB09B931A8829B6436662D2712"}}]}
2016/12/06 17:31:07 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config decoded correctly.
2016/12/06 17:31:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] set most recent sequence number to 0
2016/12/06 17:31:11 Change user password
2016/12/06 17:31:11 Created user account: azureuser1
2016/12/06 17:31:11 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Succeeded in create the account or set the password.
2016/12/06 17:31:14 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Enable,success,0,Enable succeeded.
2016/12/06 17:44:43 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] sequence number is 0
2016/12/06 17:44:43 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/config/0.settings
2016/12/06 17:44:43 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIIB6AYJKoZIhvcNAQcDoIIB2TCCAdUCAQAxggFxMIIBbQIBADBVMEExPzA9BgoJkiaJk/IsZAEZFi9XaW5kb3dzIEF6dXJlIFNlcnZpY2UgTWFuYWdlbWVudCBmb3IgRXh0ZW5zaW9ucwIQFUAVyuzoyZlJRSO+ZNLgkjANBgkqhkiG9w0BAQEFAASCAQC8T5GlBBhsq83LGCqFFmfSOmIsGe1ph0hn37K0Gt+I7mtQ8Kvb+pf3gnaDdDhhsiGWno86erfubdgDfXDEidPwwf6eTDz0QbS2g421oo6/WGpHBPz9t3cd8j0Bb962OZIZ+m4BwODXpWbbE3UFV2JdJMJ+K1h6nNtpDM9VCtyfgyGPt9fX5M/56FMdWhPOPvcb3VEeKgwK9/EGf2i9tVqJdj+EohNGR46U5q77ap9JGV+DSb99o6JC48Lcxj/7aRa2W30dJVdzeK7V8dCiHGlkr4wJcph4sLi7iuJ5Q/sTBF26JD0X1kGfFLovJHXCD64V1nvY6GtzHNEYgDjCtruVMFsGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQII7rVWjRnJBCAOL5JD2pH+oG/WmwYZJZyxmlQA1iTosEejwrvucdLXVipZC2fhGRTkjblRnCJFhaVR1teeDO7RSZ3", "publicSettings": null, "protectedSettingsCertThumbprint": "BD0F719C2990181F526A6CBB55013BD1A40348F9"}}]}
2016/12/06 17:44:43 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Config decoded correctly.
2016/12/06 17:44:43 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Current sequence number, 0, is not greater than the sequnce number of the most recent executed configuration. Exiting...
```

Expected results:
Success to reset password in the VM.

Additional info:
The root cause is the most recent sequence number on the new VM is get from the file `/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/mrseq`
And it's always greater than or equal to the Current sequence number which will be reset when do the reset password on a new provisioned VM.

**Comment by yuxisun1217** [comment]
Hi,

This issue exists from 2.0.16 to 2.1.1. It seems that it impacts every extension which needs to compare the sequence number. Is it possible to deal with the mrseq(such as remove it?) if the VM is created from a specialized image? Thanks!

**Comment by hglkrijger** [comment]
@yuxisun1217 I believe this would be expected behavior. Since the sequence number is reset when creating a VM, we expect de-provisioning to be done before capturing the image to remove that state on disk. 

@brendandixon - could you comment on whether we support this scenario?

**Comment by brendandixon** [comment]
@yuxisun1217 This is not, as far as I know, a supported scenario. That is why we added `waagent -deprovision`.

**Comment by yuxisun1217** [comment]
Hi @hglkrijger and @brendandixon ,

Thank you very much for your explanations and sorry for replying late.
I agree that run -deprovision before capture is the regular way. But for Azure, there're two kinds of captured image: generalized and specialized. 
1. I think that the -deprovision is usually used to capture a generalized image, and users use this image as a template to create plenty of VMs.(In this scenario this issue doesn't exist). 
2. In my option, the specialized image is just similar to a VM snapshot that it doesn't recommend users to do the "-deprovision" before capturing(This issue exists here).  
So I think for the 2nd scenario there's a risk. What do you think about that? Thanks!

Best regards,
Yuxin Sun

**Comment by hglkrijger** [comment]
@jinhyunr - do you know how/if this works for the Windows agent?

@brendandixon - what if we added the container-id to the mrseq file?

**Comment by brendandixon** [comment]
@yuxisun1217 The proper approach is to remove the Microsoft.OSTCExtensions.VMAccessForLinux extension before capturing the image. Users can use either the portal or CLI to do so. Once removed, the scenario will work as expected.

While I agree it is a design short-coming, capturing and re-launching will break the protocols and documents used by Azure to manage extensions. Changing this extends far beyond the agent.
