### ISSUE TITLE
Azure agent cannot connect to Azure platform if two nics are in the same subnet

### ISSUE THREAD

**Issue by wangjj1989** [Azure/WALinuxAgent#512]
Hi,
Recently, I come across this problem: if I configure two nics and the two nics are in the same subnet, then azure agent cannot connect to azure platform.
logs show: socket IO error, timeout.
But I can connect my VM from those two nics.
And if the two nics are in different subnets or just config one nic, no problem.
Any one knows if it's the right behavior?

**Comment by hglkrijger** [comment]
No, this is not expected. What version of the agent are you using? Which OS+version? Can you post your logs?

**Comment by wangjj1989** [comment]
My agent is 2.1.6. My Os is not a standard distribution. The kernel and distro are compiled by myself. And I also do some customization to agent because many configurations are different.
I will update the logs later( I need to reproduce it)

**Comment by hglkrijger** [comment]
Could you try reproduce with the latest agent?

**Comment by wangjj1989** [comment]
I find that I have two nics and eth0 is set to primary but the agent choose eth1 to communicate with wire server endpoint:168.63.129.16. And I check /proc/net/route and eth0 's flag is 0001 and eth1 's flag is 0003.
Looks like only the primary nic is okay.

**Comment by hglkrijger** [comment]
Could you please provide agent logs from `/var/log/waagent.log`?

**Comment by hglkrijger** [comment]
Just re-read the previous comments. If you have made changes to the agent, then it will not be possible to determine the issue. This scenario does work in the agent today.

**Comment by thepowercoders** [comment]
I think the issue observed above is because you can only communicate to the Azure anycast address 168.63.129.16 via the virtual machine primary NIC and it's primary IP. That is certainly the rule when communicating with the VM IMDS metadata service - described here: https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=windows
