### ISSUE TITLE
Commit #478 breaks SLES 11

### ISSUE THREAD

**Issue by rjschwei** [Azure/WALinuxAgent#514]
While SLES 11 is a bit older ;) it is still used by many enterprise customers. EOL of SLES 11 SP4 is not until 2019. The changes to the use of sfdisk committed with #478 break SLES 11 based instances as the version of sfdisk does not yet support --part-type. The code needs to be structured such that both -c or --part-type can be supported for the sfdik call depending on what the version on the system expects.

**Comment by hglkrijger** [comment]
@rjschwei - we already do this [here](https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/daemon/resourcedisk/default.py#L177-L203).

**Comment by rjschwei** [comment]
Agreed, sorry I was only looking at the commits based on the links form the release notes.
