### ISSUE TITLE
waagent breaks sshd_config while disabling passwords

### ISSUE THREAD

**Issue by olegoz** [Azure/WALinuxAgent#52]
If a VM is created from an image without enabling a password for the login user (using ssh key only), waagent modifies sshd_config by adding these two lines at the end of the file:

PasswordAuthentication no
ChallengeResponseAuthentication no

But if sshd_config ends with a Match block, the above modification breaks it:

[azureuser@oleg-test7 ~]$ sudo service sshd restart
Stopping sshd:                                             [  OK  ]
Starting sshd: /etc/ssh/sshd_config line 146: Directive 'ChallengeResponseAuthentication' is not allowed within a Match block    [FAILED]

As a Match block cannot be closed, there's no good work-around that I can think of. The initial VM start-up works (because the agent does "sshd condrestart" and it fails sanity checks), but after a reboot the VM becomes unreachable.

waagent probably needs to get smarter about modifying sshd_config (e.g. by inserting those lines before the first Match block).

This is in CentOS 6 based VM.

**Comment by yuezh** [comment]
@olegoz. We've fixed this in version 2.1. Please check the latest release of this version.
https://github.com/Azure/WALinuxAgent/tree/v2.1.2.rc1

**Comment by SuperScottz** [comment]
try this guidance to upgrade:

**Comment by SuperScottz** [comment]
try this guidance to upgrade:https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-update-agent/
