### ISSUE TITLE
Ensure events only contain VM info from the agent

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#520]
Extensions may write events and, in some case, may include VM information values (such as ContainerID) they should not. This can result in events containing duplicate PARAMs which may confuse off-board telemetry collectors.

`monitor.py#collect_and_send_events` should, after parsing the event, should purge from the event any fields it intends to add from its `sysinfo` object.

**Comment by jinhyunr** [comment]
do we simply remove the second line from here...?

```python
            try:
                event = parse_event(data_str)
                event.parameters.extend(self.sysinfo)
                event_list.events.append(event)
```

**Comment by hglkrijger** [comment]
@brendandixon can you clarify the requirement?

**Comment by brendandixon** [comment]
@jinhyunr @hglkrijger Certainly. @boumenot and I ran into this before the Christmas holidays. `monitor.py#init_sysinfo` creates a structure containing `VMName`, `TenantName`, `RoleName`, `RoleInstanceName`, and `ContainerId`. `monitory.py#collect_and_send_events` at https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/ga/monitor.py#L165 appends this structure to the telemetry object (as @jinhyunr points out above). That data, however, is the correct data. We need to ensure that any read data (within `event` after parsing) does not contain any of those fields. They must be single instance and they must have the values `monitor.py` collected at initialization.
