### ISSUE TITLE
 WALinuxAgent-2.2.2 failed with exception: syntax error: line 1, column 49

### ISSUE THREAD

**Issue by vilibert** [Azure/WALinuxAgent#523]
Upgrading the agent on a CentOS 6.7 system

yum install WALinuxAgent

when setting proxy in waagent.conf for example

HttpProxy.Host=linux-tr.cloudapp.net
HttpProxy.Port=443

and restart the agent i see the following error

**2016/12/16 10:27:22.553306 WARNING httplib does not support https tunnelling (new in python 2.7)
2016/12/16 10:27:22.579535 WARNING Agent WALinuxAgent-2.2.2 failed with exception: syntax error: line 1, column 49**

#ps -eaf | grep -i agent
root     57555 57175  0 10:23 pts/1    00:00:00 tail -f /var/log/waagent.log
root     57954     1  1 10:29 pts/0    00:00:00 python /usr/sbin/waagent -daemon
root     57979 57135  0 10:30 pts/0    00:00:00 grep -i agent

If you comment these 2 lines:

#HttpProxy.Host=linux-tr.cloudapp.net
#HttpProxy.Port=443

and restart the agent I now see 2 processes the 2nd 2.2.2-py2.7.egg is for what purpose ?

root     57806     1  0 10:28 pts/0    00:00:00 python /usr/sbin/waagent -daemon
root     57810 57806  1 10:28 pts/0    00:00:00 python -u bin/WALinuxAgent-2.2.2-py2.7.egg -run-exthandlers

Should the agent support proxies?

**Comment by hglkrijger** [comment]
@vilibert I was not able to reproduce this issue. Here are the steps I followed:

- created VM with `OpenLogic:CentOS:6.7:6.7.20160310`
- setup squid on another VM in the same subnet
- updated azure agent with:
```
yum makecache
yum update WALinuxAgent
```
- update the proxy setting:
```
HttpProxy.Host=10.0.1.5
HttpProxy.Port=3128
```
I can see the access entries from the agent in the squid logs, and although there are https warnings as expected I am not able to reproduce the syntax error. 

If you are able to provide repro steps please let me know and we can reopen this issue.
