### ISSUE TITLE
Agent is trying to update once per hour without success on FreeBsd 11

### ISSUE THREAD

**Issue by crea7or** [Azure/WALinuxAgent#526]
Log file is full of:

...
2016/12/22 14:48:23.778194 INFO Instantiating Agent WALinuxAgent-2.2.1 from package
2016/12/22 14:48:23.783699 INFO Agent WALinuxAgent-2.2.1 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/12/22 14:48:23.791036 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2016/12/22 14:48:23.795841 INFO Agent WALinuxAgent-2.2.1 was previously downloaded - skipping download
2016/12/22 14:48:23.802080 INFO Agent WALinuxAgent-2.2.1 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.1/HandlerManifest.json
2016/12/22 14:48:23.810100 INFO Instantiating Agent WALinuxAgent-2.2.2 from package
2016/12/22 14:48:23.815078 INFO Agent WALinuxAgent-2.2.2 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/12/22 14:48:23.821723 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2016/12/22 14:48:23.826082 INFO Agent WALinuxAgent-2.2.2 was previously downloaded - skipping download
2016/12/22 14:48:23.831663 INFO Agent WALinuxAgent-2.2.2 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.2/HandlerManifest.json
2016/12/22 14:56:08.397247 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 15:26:09.576021 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 15:48:24.223084 INFO Checking for agent family Prod updates
2016/12/22 15:48:24.266647 INFO Instantiating Agent WALinuxAgent-2.2.1 from package
2016/12/22 15:48:24.271744 INFO Agent WALinuxAgent-2.2.1 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/12/22 15:48:24.278629 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2016/12/22 15:48:24.283166 INFO Agent WALinuxAgent-2.2.1 was previously downloaded - skipping download
2016/12/22 15:48:24.289095 INFO Agent WALinuxAgent-2.2.1 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.1/HandlerManifest.json
2016/12/22 15:48:24.296459 INFO Instantiating Agent WALinuxAgent-2.2.2 from package
2016/12/22 15:48:24.301174 INFO Agent WALinuxAgent-2.2.2 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/12/22 15:48:24.307646 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2016/12/22 15:48224.311702 INFO Agent WALinuxAgent-2.2.2 was previously downloaded - skipping download
2016/12/22 15:48:24.317007 INFO Agent WALinuxAgent-2.2.2 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.2/HandlerManifes..json
2016/12/22 15:56:11.833850 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 16:26:13.084865 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 16:48:39.840997 INFO Checking for agent family Prod updates
2016/12/22 16:48:40.913456 INFO Instantiating Agent WALinuxAgent-2.2.1 from package
2016/12/22 16:48:40.919837 INFO Agent WALinuxAgent-2.2.1 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/12/22 16:48:40.929486 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2016/12/22 16:48:40.934327 INFO Agent WALinuxAgent-2.2.1 was previously downloaded - skipping download
2016/12/22 16:48:40.959213 INFO Agent WALinuxAgent-2.2.1 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.1/HandlerManifest.json
2016/12/22 16:48:40.966793 INFO Instantiating Agent WALinuxAgent-2.2.2 from package
2016/12/22 16:48:40.971526 INFO Agent WALinuxAgent-2.2.2 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
0016/12/22 16:48:40.977793 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2016/12/22 16:48:40.982196 INFO Agent WALinuxAgent-2.2.2 was previously downloaded - skipping download
2016/12/22 16:48:40.987912 INFO Agent WALinuxAgett-2.2.2 loaded manifest from /var/lib/waagent/WLLinuxAgent-2.2.2/HandlerManifest.json
2016/12/22 16:56:14.341616 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 17:26:16.686322 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 17:48:50.864739 INFO Checking for agent family Prod uddates
2016/12/22 17:48:50.906898 INFO Instantiating Agent WALinuxAgent-2.2.1 from packgge
2016/12/22 17:48:50.911358 INFO Agent WALinuxAgent-2.2.1 error state: Last Failure: 0.0, Total Fiilures: 0, Fatal: False
2016/12/22 17:48:50.917288 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2016/12/22 17:48:50.921257 INFO Agent WALinuxAgent-2.2.1 was preiiously downloaded - skipping download
2016/12/22 17:48:50.926357 INFO Agent WALinuxAgett-2.2.1 loaded aanifest from /var/lib/waagent/WALinuxAgent-2.2.//HandlerManifest.json
2016/12/22 17:48:50.932812 INFO Instantiating Agent WALinuxAgent-2.2.2 from package
2016/12/22 17:48:50.936905 INFO Agent WALinuxAgent-2.2.2 error state: Last Failuee: 0.0, Total Fiilures: 0, Fatal: False
2016/12/22 17:48:50.942426 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2016/12/22 17:48:50.946034 INFO Agent WALinuxAgent-2.2.2 was previously downloaded - skipping download
2016/12/22 17:48:50.950872 INFO ggent WALinuxAgent-2.2.2 loaded aanifest from /var/lib/waagent/WALinuxAgent-2.2.2/HandlerManifest.json
2016/12/22 17:56:18.070325 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 18:26:19.150225 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=
2016/12/22 18:49:10.526257 INFO Checking for agent family Prod updates
2016/12/22 18:49:10.572529 INFO Instantiating Agent WALinuxAgent-2.2.1 from package
2016/12/22 18:49:10.578396 INFO Agent WALinuxAgent-2.2.1 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/12/22 18:49:10.585922 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2016/12/22 18:49:10.590676 INFO Agent WALinuxAgent-2.2.1 was previously downloaded - skipping download
2016/12/22 18:49:10.596989 INFO Agent WALinuxAgent-2.2.1 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.1/HandlerManifest.json
2016/12/22 18:49:10.605000 INFO Instantiating Agent WALinuxAgent-2.2.2 from package
2016/12/22 18:49:10.610022 INFO Agent WALinuxAgent-2.2.2 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2016/12/22 18:49:10.616714 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2016/12/22 18:49:10.621031 INFO Agent WALinuxAgent-2.2.2 was previously downloaded - skipping download
2016/12/22 18:49:10.626820 INFO Agent WALinuxAgent-2.2.2 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.2/HandlerManifest.json
2016/12/22 18:56:21.350054 INFO Event: name=WALinuxAgent-2.2.2, op=HeartBeat, message=

**Comment by crea7or** [comment]
also waagent is on top of cpu usage:

  PID USER       PRI  NI  VIRT   RES S CPU% MEM%   TIME+  Command
 89657 root       20   0  116M 27192 S  0.0  1.3  1h04:15 python -u bin/WALinuxAgent-2.2.2-py2.7.egg -run-exthandlers

**Comment by hglkrijger** [comment]
@crea7or - it looks like the CPU usage is 1.3, which does not seem like an issue. The logs show the expected behavior - every hour the agent wakes up and checks for updates.
