### ISSUE TITLE
Where is the status file if the VM is in the premium storage?

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#527]
Hi,

We know that WALA upload status to blob every 25 seconds. If the VM is located in a standard storage, we can find the status file in the same storage-"vhds" container. But if the VM is located in a premium storage, we can't find the status file.
I've checked the ExtensionConfig.n.xml. If the VM is located in a premium storage, the StatusUploadBlob is like this:

`
<StatusUploadBlob statusBlobType="PageBlob">https://wala68ond31414.blob.core.windows.net/$system/wala68ond3.wala68ond3.wala68ond3.status?sr=b&amp;sp=rw&amp;se=9999-01-01&amp;sk=system-1&amp;sv=2014-02-14&amp;sig=rG%2BGOj93PJj9sG68R4Bx1yavI5Z3mepkdGx0uza6Xa0%3D</StatusUploadBlob></Extensions>
`

There's a "$system" in the url. Is it right? Thanks.

Platform: RHEL-6.8 on-demand
WALA: 2.2.2

Steps to Reproduce:
1. Create a VM(Standard DS1 Size) by Azure Web Portal
2. Check Premium Storage Account,'vhds' container

waagent.log:

2016/12/27 03:59:44.911563 VERBOSE Report vm agent status
2016/12/27 03:59:44.917203 VERBOSE Upload status blob
2016/12/27 03:59:44.922375 VERBOSE Check blob type.
2016/12/27 03:59:44.927449 VERBOSE HTTP method: [HEAD]
2016/12/27 03:59:44.932768 VERBOSE HTTP host: [wala68ond31414.blob.core.windows.net]
2016/12/27 03:59:44.940516 VERBOSE HTTP uri: [/$system/wala68ond3.wala68ond3.wala68ond3.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=rG%2BGOj93PJj9sG68R4Bx1yavI5Z3mepkdGx0uza6Xa0%3D]
2016/12/27 03:59:44.957921 VERBOSE HTTP port: [None]
2016/12/27 03:59:44.962823 VERBOSE HTTP data: [None]
2016/12/27 03:59:44.968674 VERBOSE HTTP secure: [True]
2016/12/27 03:59:44.974443 VERBOSE HTTP headers: [{'x-ms-version': '2014-02-14', 'x-ms-date': '2016-12-27T08:59:44Z'}]
2016/12/27 03:59:44.985000 VERBOSE HTTP proxy: [None:None]
2016/12/27 03:59:44.991181 VERBOSE HTTPConnection [HEAD] [/$system/wala68ond3.wala68ond3.wala68ond3.status?sr=b&sp=rw&se=9999-01-01&sk=system-1&sv=2014-02-14&sig=rG%2BGOj93PJj9sG68R4Bx1yavI5Z3mepkdGx0uza6Xa0%3D] [None] [{'x-ms-version': '2014-02-14', 'x-ms-date': '2016-12-27T08:59:44Z'}]
2016/12/27 03:59:45.030830 VERBOSE HTTP response status: [200]

Best regards,
Yuxin Sun

**Comment by hglkrijger** [comment]
Yes, this is correct. The `$system` container is expected for premium storage based containers.
