### ISSUE TITLE
Error when installing new extension

### ISSUE THREAD

**Issue by hglkrijger** [Azure/WALinuxAgent#530]
The following error log is unnecessary:
```
2017/01/04 00:45:55.784621 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.2] Expected handler state: enabled
2017/01/04 00:45:55.829788 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.2] Current handler state is: NotInstalled
2017/01/04 00:45:55.859532 ERROR [Microsoft.Azure.Extensions.CustomScript-2.0.2] Failed to set state: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.2/config/HandlerState'
2017/01/04 00:45:55.877452 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.2] Download extension package
2017/01/04 00:45:56.339726 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.2] Unpack extension package
```
It should be set to a warning or removed.

**Comment by jgardner04** [comment]
I have run into this same issue when running the [OSTCExtesions.CustomScriptForLinux](https://github.com/Azure/azure-linux-extensions/tree/master/CustomScript) and the updated [Custom Script extension](https://github.com/Azure/custom-script-extension-linux).  Both hang on `Preparing to unpack .../walinuxagent_2.1.5-0ubuntu4~16.04.0_amd64.deb ...`  

I discovered this when tracking down [Unable to deploy the VM when doing the CD with hosted agent step #105](https://github.com/Microsoft/PartsUnlimitedMRP/issues/105)

**Comment by hglkrijger** [comment]
@jgardner04 - not sure if this is the same issue, but a fix has been merged, so closing this one. If you still see issues with CSE please open another issue.

**Comment by jgardner04** [comment]
@hglkrijger great.  We made changes to the custom script to use SSH keys instead of UN/PW and that seemed to take care of it on our end.  That is the best practice anyway so we are good.  Thank you!
