### ISSUE TITLE
Configuration location at CoreOS

### ISSUE THREAD

**Issue by lshahar** [Azure/WALinuxAgent#535]
We found at new version of CoreOS the configuration created at /usr/share/oem/waagent.conf
There is way to defined for the agent from there to read the configuration? 
maybe solution can be to try find the configuration from both location /etc/waagent.conf and /usr/share/oem/waagent.conf

**Comment by hglkrijger** [comment]
The agent already reads the config from this location. See [this].(https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/osutil/coreos.py#L26)
