### ISSUE TITLE
waagent fail on CoreOS after update

### ISSUE THREAD

**Issue by sepiroth887** [Azure/WALinuxAgent#549]
Problem: 

waagent update requires /etc/waagent.conf but is not providing one on coreos. 

Current workaround: 

manually set the coreos waagent.conf and reboot. 

Is it possible to guard against these issues? 
Missing this conf will end up not mounting the SSD to /mnt/resources which we do rely on for ephemeral data a lot. If it's not present our Root FS will blow up within a few hours. 

Lots of reboots in the cluster due to this bug. :(

**Comment by hglkrijger** [comment]
Configuration for CoreOS is read from `/usr/share/oem/waagent.conf`. See https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/osutil/coreos.py#L26
