### ISSUE TITLE
What circumstances require the agent to run?

### ISSUE THREAD

**Issue by jnoxon** [Azure/WALinuxAgent#550]
I'm working on a project to launch a managed SaaS "appliance" image in Azure. This product is already available in several other cloud environments. It's a weird model where the product is deployed in the customer's infrastructure, but not managed by the customer.

We need to be able to disable the WALinuxAgent extension functionality, which doesn't seem possible. For example, we do not want customers who run our image to be able to change passwords, create users, install software, or do anything else that could potentially alter the state of the system. Shell access is not available. I understand that a determined customer could do this stuff if they wanted (it's their environment, after all), but it shouldn't just take a few clicks in the portal.

What breaks if the agent does not run at all? It seems like our minimal provisioning requirements can be satisfied with cloud-init. Thanks!

**Comment by hglkrijger** [comment]
The appliance model prevents the customer from modifying resources which are managed for them, so I am not sure this should be a concern.

**Comment by jnoxon** [comment]
Thanks! If there's some documentation about this you can point me to, I'd be really grateful.

**Comment by hglkrijger** [comment]
I have asked some folks to follow up with you if there is any documentation available. Closing this issue for now.
