### ISSUE TITLE
sfdisk: unrecognized option '--part-type'

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#554]
The agent now uses ``--part-type``, which is not supported sfdisk from util-linux 2.25.2, as for example used by Debian Jessie.

**Comment by hglkrijger** [comment]
There is a fallback to `-c` if this does not work. See here: https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/daemon/resourcedisk/default.py#L183-L192

**Comment by boumenot** [comment]
The issue is more so that the error is logged, and then we fallback to a working command. If the command is expected to fail it would be better to log it as verbose instead of info.
