### ISSUE TITLE
Tries to parse stderr of sfdisk

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#555]
The agent merges and tries to parse stdout and stderr of for example sfdisk. stderr should never be considered structured output. Fixed in Debian by:

    --- a/azurelinuxagent/common/utils/shellutil.py
    +++ b/azurelinuxagent/common/utils/shellutil.py
    @@ -74,7 +74,7 @@ def run_get_output(cmd, chk_err=True, log_cmd=True):
         if log_cmd:
             logger.verbose(u"run cmd '{0}'", cmd)
         try:
    -        output=subprocess.check_output(cmd,stderr=subprocess.STDOUT,shell=True)
    +        output=subprocess.check_output(cmd,shell=True)
             output = ustr(output, encoding='utf-8', errors="backslashreplace")
         except subprocess.CalledProcessError as e :
             output = ustr(e.output, encoding='utf-8', errors="backslashreplace")

**Comment by hglkrijger** [comment]
@waldiTM - thanks for logging this. I agree that merging `std_err` is not ideal, but I would also be concerned about changing it at this point. This has been around for quite some time, and code outside our control (extensions, for example) may well have taken a dependency on this behavior. 

As far as parsing `std_err`, I did a quick scan through the agent code and looked at all the usages of this function. Unless I missed something, the agent only ever uses the return code to make decisions, and uses the output only when the return code is 0. So I do not believe we ever parse `std_err`. If you do find an instance of this feel free to reopen this issue.
