### ISSUE TITLE
Quote the Username Passed to the useradd Command

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#558]
A customer failed to provision a VM because an unfortunate username was chosen.  The customer chose a username similar to *-appname*.  The guest agent passed this value as is directly to the useradd command, and it failed by responding with a help message that indicated it does not support the parameter *-a*.

```text
2017/01/14 09:59:21.045306 ERROR run cmd 'useradd -m -appname' failed
2017/01/14 09:59:21.045546 ERROR Error Code:2
2017/01/14 09:59:21.046153 ERROR Result:useradd: invalid option -- 'a'
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]
```

I have only seen one case like this, and I do not think the agent is the correct spot to do user name validation.  IMHO it should happen much higher up the stack.  At the very least I am logging this bug in case other hit a similar issue and wonder why.  Feel free to reject if you do not think a fix is appropriate.

**Comment by hglkrijger** [comment]
@boumenot - I agree the validation needs to be done centrally and much earlier in the stack. Thanks for logging this for others to see. Closing.
