### ISSUE TITLE
Agent Needs Better Exception Response for Swap Creation

### ISSUE THREAD

**Issue by taylorsmcclure** [Azure/WALinuxAgent#559]
Currently if you enable swap in /etc/waagent.conf and put a value that is not an int for `ResourceDisk.SwapSizeMB=` such as `ResourceDisk.SwapSizeMB=4GB` or `ResourceDisk.SwapSizeMB=4000MB` the value of var **nbyte** in [azurelinuxagent/daemon/resourcedisk/default.py](https://github.com/Azure/WALinuxAgent/blob/515415a4789cda7aebddc3552257220c3b74c0c4/azurelinuxagent/daemon/resourcedisk/default.py#L237) will be '0'.

This will pass the validation check on line [256](https://github.com/Azure/WALinuxAgent/blob/515415a4789cda7aebddc3552257220c3b74c0c4/azurelinuxagent/daemon/resourcedisk/default.py#L256) and continue where it will eventually fail the fallocate syscall as the length is zero.

I would suggest modifying line 256 to have more strict error checking for **nbyte** being zero:

```python
        if nbytes <= 0:
            raise ValueError(nbytes)
```

**Comment by hglkrijger** [comment]
@taylorsmcclure - thanks for catching this.
