### ISSUE TITLE
freebsd blank root password allows anyone to su root?

### ISSUE THREAD

**Issue by rhavenn** [Azure/WALinuxAgent#575]
Is there a reason why the password on FreeBSD get sets to blank? This makes it so any user can su to root without a password at all. Seems a rather poor security idea.

In FreeBSD deleterootpassword you're better off doing:
`return Run("pw usermod root -h -")`

which "should", if I'm reading the Python code right, just execute:
`pw usermod root -h -`

which will set the root password to *, which is an invalid password, and will prevent anyone logging in as root. You can still `sudo su -` or SSH key, if enabled, but blocks password logins.

Sorry if I'm not aware of some Azure thing that needs it to be blank.

If you want me to submit a commit, let me know.

**Comment by hglkrijger** [comment]
@rhavenn - thanks for reporting this. I submitted a fix with #578, feel free to reopen this issue if you have any further comments.
