### ISSUE TITLE
Remount of filesystems wipes /tmpfs volumes of data initialized by cloud-init. 

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/WALinuxAgent#583]
Upgrading from 2.1.x to 2.2.2 has caused waagent to be much more aggressive about remounting all attached filesystems. This assumes that volumes are durable - in the case of /tmpfs volumes we lose data that is initialized by cloud-init.

**Comment by clarkbreyman-yammer** [comment]
OS Ubuntu 16.04.1

**Comment by hglkrijger** [comment]
@clarkbreyman-yammer thanks for reporting this. Could you provide an example repro?

**Comment by hglkrijger** [comment]
closing for lack of details
