### ISSUE TITLE
waagent cannot handle hostname change and dhcp client restart

### ISSUE THREAD

**Issue by rajeshnair** [Azure/WALinuxAgent#585]
We are facing an issue where waagent fails in specific regions ( mostly US-west) and works in other ( East -Asia etc)

## Symptom
The failed VMs show this message in waagent.log

````
2017/02/07 00:50:46.059925 WARNING Exception retrieving agent manifests: (000008)(000009)HTTP GET failed
2017/02/07 00:50:46.060142 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: (000008)(000009)HTTP GET failed
2017/02/07 00:50:46.061256 INFO Wire server endpoint:168.63.129.16
2017/02/07 00:50:46.062024 WARNING Exception retrieving extension handlers: (000008)(000009)HTTP GET failed
2017/02/07 00:50:46.062175 ERROR Event: name=WALinuxAgent, op=, message=Exception retrieving extension handlers: (000008)(000009)HTTP GET failed
2017/02/07 00:50:49.347846 INFO EnvMonitor: Detected dhcp client restart. Restoring routing table.
2017/02/07 00:50:49.348137 INFO Configure routes
2017/02/07 00:50:49.348611 INFO Gateway:None
2017/02/07 00:50:49.348788 INFO Routes:None
2017/02/07 00:51:11.101978 WARNING Exception retrieving extension handlers: (000008)/var/lib/waagent/ExtensionsConfig.2.xml is missing.
2017/02/07 00:51:11.106286 ERROR Event: name=WALinuxAgent, op=, message=Exception retrieving extension handlers: (000008)/var/lib/waagent/ExtensionsConfig.2.xml is missing.
````

## System details
````
# waagent -version
WALinuxAgent-2.2.2 running on centos 6.8
Python: 2.6.6
Goal state agent: 2.2.2
````

## More details
It appears that in every instance of failed waagent start , there is a dhcp client restart and hostname change

````
2017/02/07 00:50:45.029505 INFO EnvMonitor: Detected hostname change: None -> bktestcluster-masternode
...
2017/02/07 00:50:49.347846 INFO EnvMonitor: Detected dhcp client restart. Restoring routing table.
````

Attached is a good log and a bad log for you to compare
[good-waagent.txt](https://github.com/Azure/WALinuxAgent/files/756746/good-waagent.txt)
[bad-waagent.txt](https://github.com/Azure/WALinuxAgent/files/756745/bad-waagent.txt)

## Our solution template 
Link to our solution template is here
https://github.com/striim/azure-solution-template

**Comment by rajeshnair** [comment]
@hglkrijger , @ahmetalpbalkan

Let me know if you need any more data from the bad VMs

**Comment by hglkrijger** [comment]
@rajeshnair, thanks for reporting the issue; some questions:

- how reproducible is this within the affected region? 
- could you provide the contents of `/var/lib/waagent` from an affected vm?
- does the issue persist after a service restart? if so, could you enable verbose logging, restart the service and then also include the verbose log? i.e. set `Logs.Verbose=y` in `/etc/waagent.conf`

**Comment by rajeshnair** [comment]
@hglkrijger 

Answering your query

- Since last few days at least since Feb 4, we are facing this recurrently on West US region and sometime on Central US region. Deployments succeeds in other regions like East US and East Asia. My hypotheses is this is a race condition between waagent process running and hostname being set on VM by azure VM provisioner. So the chances of hostname change is higher in heavily loaed regions like West US. Prior to this we have done lot of test on West US region around Jan 1-15 timeframe and it succeeded

- I have uploaded entire /var/lib/waagent compressed [here](http://striim-downloads.s3.amazonaws.com/waagent.tgz)

- Which service are you referring to ? waagent? We are provisioning Azure VM and tenconfiguring VM using LinuxExtension. We cannot ask end-users to restart waagent service if they face this issue.

**Comment by hglkrijger** [comment]
@rajeshnair, thanks for the info. I understand, just trying to gather information for the fix. I have obtained a verbose log in any case, thanks.

**Comment by rajeshnair** [comment]
Thanks @hglkrijger 

Do you have any estimate on when can we expect the fix?
This is blocking us to rollout our solution template to production

**Comment by hglkrijger** [comment]
@rajeshnair please try deploy again, you should be unblocked.

**Comment by rajeshnair** [comment]
@hglkrijger , Does this require me to update the ``typeHandlerVersion``  to test or should I continue with existing codebase?

**Comment by hglkrijger** [comment]
@rajeshnair, existing is fine.

**Comment by rajeshnair** [comment]
@hglkrijger , thanks for the quick response and the fix!

Provisioned couple of VMs in US-West and it came up fine!
Looks much stable !

BTW , I don't see commit in WALinuxAgent repo.
Just wondering was the fix in some other place !

**Comment by hglkrijger** [comment]
@rajeshnair glad to confirm the issue is fixed.

**Comment by rajeshnair** [comment]
Thanks @hglkrijger for the timely fix !!!
