### ISSUE TITLE
Enable support for including other config files in waagent.conf

### ISSUE THREAD

**Issue by OddBloke** [Azure/WALinuxAgent#586]
When building Ubuntu images, we want to be able to ship a config file in the walinuxagent package without auto-update enabled, but enable auto-update within the image build process.

To avoid conflicts on upgrade, this would need to be done in a separate config file, so we would like to be able to include config files within waagent.conf (probably from /etc/waagent.conf.d/*, but it should be configurable).

**Comment by OddBloke** [comment]
(We're going to look at submitting a PR for this from Canonical's side.)

**Comment by sil2100** [comment]
Related to this: would everyone here be fine if in Ubuntu we, by using this 'include' functionality, add the /etc/waagent.conf.d/ directory as an official additional configuration directory to our packaging?

**Comment by brendandixon** [comment]
@OddBloke @sil2100 I have mixed feelings about it. Most of the configuration settings are not that useful; they remain *mostly* for historical reasons. However, mis-setting them could cause customers problems. I *strongly* prefer that customers not alter configuration settings, except the HTTP proxy settings, unless they have a very clear, well-understood reason for doing so. Therefore, having an extensible mechanism, while nice in one sense, to me seems to open the door to more possible errors.

**Comment by sil2100** [comment]
I understand your concern completely. But the solution proposed by OddBloke seems a safe thing to do to get us unblocked from the Ubuntu POV. This way there would be tools in place that aren't enabled by default (like, there would be no new directory for configuration for everyone), but can allow us to add it only through our packaging.

Of course, we can also think about just hard-coding an additional directory for overrides like these instead (we did discuss that possibility in our team as well as it could work-around some of our other problems), but not sure if that would change the situation.

**Comment by sil2100** [comment]
Is there anything we can do to move this forward? Personally this (or hard-coding an additional configuration path) would be perfect for us as this way we could finally safely (from the formal POV) enable auto-updates. The release of 2.2.4 on Ubuntu is blocked on having this resolved as our plan was to include the auto-update change along with the release.

**Comment by elyscape** [comment]
@brendandixon:
>I _strongly_ prefer that customers not alter configuration settings, except the HTTP proxy settings, unless they have a very clear, well-understood reason for doing so.

One setting that would be nice to be able to alter is the values of `ResourceDisk.EnableSwap` and `ResourceDisk.SwapSizeMB`. They default to `n` and `0`, respectively. Right now, I have to modify these in `/etc/waagent.conf` and then, every time there's an update, copy any changes from the upstream into my file. It would be nice to be able to set them in an auxiliary file and could leave the main file alone to pick up changes from upstream.

**Comment by brendandixon** [comment]
@elyscape I appreciate that having multiple configuration files eases some scenarios. However, the complexity it adds is not worth the marginal gains.

**Comment by OddBloke** [comment]
@brendandixon I'd perhaps argue that having separate configuration files makes customers _less_ likely to modify settings that they shouldn't be touching.

For example, if WALA shipped proxy configuration files in `/etc/waagent.conf.d/proxy.conf` then all documentation could just tell users to modify that file, and they won't even see the others that they shouldn't be changing.

(Furthermore, if customers decide they are going to make modifications then it's better that they make them in a separate file which allows waagent.conf to be safely upgraded. I don't think them all being in the same file will really discourage them from doing it if they've decided they want to, they'll just do it in a worse way.)

Also, unless I'm misunderstanding, this is only another 15 lines of application code, and .d configuration includes are a common pattern in the free software world; I'm not sure I really see that it adds much complexity.

**Comment by elyscape** [comment]
Indeed. The code changes would basically amount to:
```
# pseudocode
conf = load_conf_file(conf_file)
conf_dir = conf_file + '.d'
if Dir.exists(conf_dir):
  foreach conf_dir_file in Dir.children(conf_dir):
    conf.merge(load_conf_file(conf_dir_file))
```

**Comment by elyscape** [comment]
@hglkrijger Was this closed to indicate that it won't be done?
