### ISSUE TITLE
Waagent genereated big size log with error "Too many open files"

### ISSUE THREAD

**Issue by Lickkylee** [Azure/WALinuxAgent#595]
WALinuxAgent on two of Linux CentOS 7.0 went into weird status. 

1. The agent cannot start successfully with below errors. And then keep trying to restart in 15 seconds. 
2. Seems the restart will not release the losf file descriptors. everytime it restart, it will open more files and then finally reach the limit. the "too many open files" error happen. 
3. there was 45274 records of waagent when using lsof which is definately an abnormal condition. 

Anyone can help to know what exactlly cuase this error?

=================================
waagent.log
=================================
### 2017/02/23 02:37:59 Restart agent in 15 seconds
2017/02/23 02:38:14 Azure Linux Agent Version: WALinuxAgent-2.0.16
2017/02/23 02:38:14 Linux Distribution Detected      : centos
2017/02/23 02:38:14 Module /lib/modules/3.10.0-123.20.1.el7.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2017/02/23 02:38:14 VMM Init script not found.  Provisioning for Azure
2017/02/23 02:38:14 IPv4 address: 172.21.1.20
2017/02/23 02:38:14 MAC  address: 00:17:FA:00:CF:5D
2017/02/23 02:38:14 Probing for Azure environment.
2017/02/23 02:38:18 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/02/23 02:38:18 Set default gateway: 172.21.1.1
2017/02/23 02:38:19 Discovered Azure endpoint: 168.63.129.16
2017/02/23 02:38:19 Fabric preferred wire protocol version: 2015-04-05
2017/02/23 02:38:19 Negotiated wire protocol version: 2012-11-30
2017/02/23 02:38:19 Retrieved GoalState from Azure Fabric.
2017/02/23 02:38:19 ExpectedState: Started
2017/02/23 02:38:19 ContainerId: ff2842fa-48d9-47eb-9086-26e0ef7f26f6
2017/02/23 02:38:19 RoleInstanceId: a7a2b9c2fa3042fe896047cc3b0cfa2e.aoyouaz17
2017/02/23 02:38:21 Private key with thumbprint: 4AD9F101BDADE32141F71A0551878299EABC110F was retrieved.
2017/02/23 02:38:21 Public cert with thumbprint: 4AD9F101BDADE32141F71A0551878299EABC110F was retrieved.
2017/02/23 02:38:22 Posted Role Properties. CertificateThumbprint=75353bbaf4fa947c0df7f613d871df01
2017/02/23 02:38:25 Found Plugin: Microsoft.Compute.VMAccessAgent version: 2.3
2017/02/23 02:38:25 Found RuntimeSettings for Microsoft.Compute.VMAccessAgent V 2.3
2017/02/23 02:38:25 ERROR:Error parsing HandlerManifest.json.
2017/02/23 02:38:25 ERROR:Error Traceback (most recent call last):
2017/02/23 02:38:25 ERROR:  File "/usr/sbin/waagent", line 4878, in AddExtensionEvent
2017/02/23 02:38:25 ERROR:    event.Save()
2017/02/23 02:38:25 ERROR:  File "/usr/sbin/waagent", line 4848, in Save
2017/02/23 02:38:25 ERROR:    raise Exception("WriteToFolder:Too many file under "+eventfolder+" exit")
2017/02/23 02:38:25 ERROR:Exception: WriteToFolder:Too many file under /var/lib/waagent/events exit
2017/02/23 02:38:25 ERROR:
2017/02/23 02:38:25 SetHandlerState: Microsoft.Compute.VMAccessAgent-2.3, NotInstalled
2017/02/23 02:38:25 ERROR:Installation failed for Microsoft.Compute.VMAccessAgent-2.3
2017/02/23 02:38:25 Processing completed for Microsoft.Compute.VMAccessAgent-2.3
2017/02/23 02:38:25 Finished processing ExtensionsConfig.xml
2017/02/23 02:38:25 ERROR:Traceback (most recent call last):
2017/02/23 02:38:25 ERROR:  File "/usr/sbin/waagent", line 6258, in main
2017/02/23 02:38:25 ERROR:    WaAgent.Run()
2017/02/23 02:38:25 ERROR:  File "/usr/sbin/waagent", line 5844, in Run
2017/02/23 02:38:25 ERROR:    ret = goalState.ExtensionsConfig.ReportHandlerStatus()
2017/02/23 02:38:25 ERROR:  File "/usr/sbin/waagent", line 4098, in ReportHandlerStatus
2017/02/23 02:38:25 ERROR:    reportHeartbeat = json.loads(p.getAttribute("manifestdata"))[0]['handlerManifest']['reportHeartbeat']
2017/02/23 02:38:25 ERROR:  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
2017/02/23 02:38:25 ERROR:    return _default_decoder.decode(s)
2017/02/23 02:38:25 ERROR:  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
2017/02/23 02:38:25 ERROR:    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2017/02/23 02:38:25 ERROR:  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
2017/02/23 02:38:25 ERROR:    raise ValueError("No JSON object could be decoded")
2017/02/23 02:38:25 ERROR:ValueError: No JSON object could be decoded
2017/02/23 02:38:25 ERROR:
2017/02/23 02:38:25 ERROR:Exception: No JSON object could be decoded
2017/02/23 02:38:25 Restart agent in 15 seconds
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sdb/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sdb/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sda/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sda/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sdb/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sdb/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sdb/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sdb/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sda/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sda/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sda/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sda/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sdd/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sdd/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sdb/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sdb/device/timeout'
2017/02/23 02:38:34 ERROR:Reading from file /sys/block/sdd/device/timeout Exception is [Errno 24] Too many open files: '/sys/block/sdd/device/timeout'

=================================
part of lsof result
=================================l
python      994  4112           root  cwd       DIR                8,1      4096     262260 /var/lib/waagent
python      994  4112           root  rtd       DIR                8,1      4096          2 /
python      994  4112           root  txt       REG                8,1      7136    1315504 /usr/bin/python2.7
python      994  4112           root  mem       REG                8,1    694112    1704677 /usr/lib64/python2.7/lib-dynload/unicodedata.so
python      994  4112           root  mem       REG                8,1    173288    1312488 /usr/lib64/libexpat.so.1.6.0
python      994  4112           root  mem       REG                8,1     54528    1704667 /usr/lib64/python2.7/lib-dynload/pyexpat.so
python      994  4112           root  mem       REG                8,1     91040    1704651 /usr/lib64/python2.7/lib-dynload/datetime.so
python      994  4112           root  mem       REG                8,1     39024    1704634 /usr/lib64/python2.7/lib-dynload/_json.so
python      994  4112           root  mem       REG                8,1     24096    1704679 /usr/lib64/python2.7/lib-dynload/zlibmodule.so
python      994  4112           root  mem       REG                8,1     29160    1704670 /usr/lib64/python2.7/lib-dynload/selectmodule.so
python      994  4112           root  mem       REG                8,1     12336    1704657 /usr/lib64/python2.7/lib-dynload/grpmodule.so
python      994  4112           root  mem       REG                8,1     24984    1704675 /usr/lib64/python2.7/lib-dynload/timemodule.so
python      994  4112           root  mem       REG                8,1     19192    1704654 /usr/lib64/python2.7/lib-dynload/fcntlmodule.so
python      994  4112           root  mem       REG                8,1    156848    1704633 /usr/lib64/python2.7/lib-dynload/_io.so
python      994  4112           root  mem       REG                8,1     23888    1704649 /usr/lib64/python2.7/lib-dynload/cStringIO.so
python      994  4112           root  mem       REG                8,1     39784    1704642 /usr/lib64/python2.7/lib-dynload/_ssl.so
python      994  4112           root  mem       REG                8,1     16984    1704629 /usr/lib64/python2.7/lib-dynload/_functoolsmodule.so
python      994  4112           root  mem       REG                8,1     83840    1704640 /usr/lib64/python2.7/lib-dynload/_socketmodule.so
python      994  4112           root  mem       REG                8,1     38912    1704643 /usr/lib64/python2.7/lib-dynload/_struct.so
python      994  4112           root  mem       REG                8,1     48128    1704644 /usr/lib64/python2.7/lib-dynload/arraymodule.so
python      994  4112           root  mem       REG                8,1     22856    1704631 /usr/lib64/python2.7/lib-dynload/_heapq.so
python      994  4112           root  mem       REG                8,1     61976    1704659 /usr/lib64/python2.7/lib-dynload/itertoolsmodule.so
python      994  4112           root  mem       REG                8,1     47032    1704664 /usr/lib64/python2.7/lib-dynload/operator.so
python      994  4112           root  mem       REG                8,1     33024    1704622 /usr/lib64/python2.7/lib-dynload/_collectionsmodule.so
python      994  4112           root  mem       REG                8,1     16328    1704639 /usr/lib64/python2.7/lib-dynload/_randommodule.so
python      994  4112           root  mem       REG                8,1    153184    1312118 /usr/lib64/liblzma.so.5.0.99
python      994  4112           root  mem       REG                8,1    398264    1312121 /usr/lib64/libpcre.so.1.2.0
python      994  4112           root  mem       REG                8,1    147120    1312130 /usr/lib64/libselinux.so.1
python      994  4112           root  mem       REG                8,1    110808    1311984 /usr/lib64/libresolv-2.17.so
python      994  4112           root  mem       REG                8,1     15688    1312648 /usr/lib64/libkeyutils.so.1.5
python      994  4112           root  mem       REG                8,1     58480    1314132 /usr/lib64/libkrb5support.so.0.1
python      994  4112           root  mem       REG                8,1     90632    1312133 /usr/lib64/libz.so.1.2.7
python      994  4112           root  mem       REG                8,1    214816    1314120 /usr/lib64/libk5crypto.so.3.1
python      994  4112           root  mem       REG                8,1     15840    1312145 /usr/lib64/libcom_err.so.2.1
python      994  4112           root  mem       REG                8,1    929144    1314130 /usr/lib64/libkrb5.so.3.3
python      994  4112           root  mem       REG                8,1    308008    1314116 /usr/lib64/libgssapi_krb5.so.2.2
python      994  4112           root  mem       REG                8,1   2004592    1314143 /usr/lib64/libcrypto.so.1.0.1e
python      994  4112           root  mem       REG                8,1    445664    1314145 /usr/lib64/libssl.so.1.0.1e
python      994  4112           root  mem       REG                8,1     18224    1704630 /usr/lib64/python2.7/lib-dynload/_hashlib.so
python      994  4112           root  mem       REG                8,1     25696    1704646 /usr/lib64/python2.7/lib-dynload/binascii.so
python      994  4112           root  mem       REG                8,1     37344    1704661 /usr/lib64/python2.7/lib-dynload/math.so
python      994  4112           root  mem       REG                8,1     28672    1704672 /usr/lib64/python2.7/lib-dynload/stropmodule.so
python      994  4112           root  mem       REG                8,1    502040    1311913 /usr/lib64/libfreebl3.so
python      994  4112           root  mem       REG                8,1     40816    1311960 /usr/lib64/libcrypt-2.17.so
python      994  4112           root  mem       REG                8,1      7464    1704623 /usr/lib64/python2.7/lib-dynload/_cryptmodule.so
python      994  4112           root  mem       REG                8,1 106065056    1312002 /usr/lib/locale/locale-archive
python      994  4112           root  mem       REG                8,1     58288    1311974 /usr/lib64/libnss_files-2.17.so
python      994  4112           root  mem       REG                8,1   2107600    1311956 /usr/lib64/libc-2.17.so
python      994  4112           root  mem       REG                8,1   1141552    1311964 /usr/lib64/libm-2.17.so
python      994  4112           root  mem       REG                8,1     14608    1311990 /usr/lib64/libutil-2.17.so
python      994  4112           root  mem       REG                8,1     19512    1311962 /usr/lib64/libdl-2.17.so
python      994  4112           root  mem       REG                8,1    141616    1311982 /usr/lib64/libpthread-2.17.so
python      994  4112           root  mem       REG                8,1   1822488    1314972 /usr/lib64/libpython2.7.so.1.0
python      994  4112           root  mem       REG                8,1    160240    1311949 /usr/lib64/ld-2.17.so
python      994  4112           root    0r      CHR                1,3       0t0       1028 /dev/null
python      994  4112           root    1u     unix 0xffff8802933a5dc0       0t0      16199 socket
python      994  4112           root    2u     unix 0xffff8802933a5dc0       0t0      16199 socket
python      994  4112           root    3r      REG               0,16      4096      11546 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:6/timeout
python      994  4112           root    4r      REG               0,16      4096      11424 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:1/timeout
python      994  4112           root    5r      REG                8,1      3166     264046 /var/lib/waagent/Certificates.pem
python      994  4112           root    6r      DIR               0,16         0       1637 /sys/block
python      994  4112           root    7r      DIR               0,16         0       1637 /sys/block
python      994  4112           root    8r      REG               0,16      4096      11607 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:7/timeout
python      994  4112           root    9r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   10r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   11r      REG               0,16      4096      11363 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:4/timeout
python      994  4112           root   12r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   13r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   14r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   15r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   16r      REG               0,16      4096      11363 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:4/timeout
python      994  4112           root   17r      REG               0,16      4096      11241 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:3/timeout
python      994  4112           root   18r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   19r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   20r      REG               0,16      4096      11424 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:1/timeout
python      994  4112           root   21r      REG               0,16      4096      10936 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_2/host3/target3:0:1/3:0:1:0/timeout
python      994  4112           root   22r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   23r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   24r      REG               0,16      4096      10824 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_1/host2/target2:0:0/2:0:0:0/timeout
python      994  4112           root   25r      REG               0,16      4096      11180 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:0/timeout
python      994  4112           root   26r      REG               0,16      4096      11607 /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/vmbus_0_7/host5/target5:0:0/5:0:0:7/timeout
python      994  4112           root   27r      DIR               0,16         0       1637 /sys/block
python      994  4112           root   28r      DIR               0,16         0       1637 /sys/block

**Comment by brendandixon** [comment]
@Lickkylee The v2.0.xx branch of the agent is deprecated. The v2.1+ branch (such as the most recent release of v2.2.5) is what all VMs should use. The code is *substantially* improved. Please install an up-to-date version of the agent. I suspect you're problems will evaporate.
