### ISSUE TITLE
Support KVP for Linux Guests

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#597]
The Windows guest agent support KVP for telemetry, and diagnosis.  There is no such mechanism on Linux, but there should be.

/cc: @brendandixon

**Comment by brendandixon** [comment]
Notes from @szarkos:

The various KVP channels are managed via files in /var/lib/hyperv/.  These will be files such as .kvp_pool_0 through .kvp_pool_4.  I believe pool_1 is used for arbitrary key/value pairs from the guest->host.
 
The pool files are binary not text files.  We have some C code that implements read/writing to these pools here: https://github.com/LIS/lis-test/tree/master/WS2012R2/lisa/tools/KVP.  This should be pretty easy to port to Python.
 
Note that the Linux VM will also need the KVP daemon installed and running for these pool files to be populated.  I don’t think all the gallery images have this running by default, so we should discuss how to update all the images.

**Comment by boumenot** [comment]
@paulmey has added support for KVP to cloud-init, which is going to be our focus for KVP.  I will not support KVP in the agent as a result unless there is a compelling need.
