### ISSUE TITLE
waagent can not mount resource disk if locale is changed.

### ISSUE THREAD

**Issue by FumiakiNagano** [Azure/WALinuxAgent#607]
This issue happens 100%.
Is this by design? Is there a workaround for this issue?

Repro steps
------------
1. Deploy Red Hat 7.2 V2 VM from Azure Portal
2. SSH to the Red Hat VM
3. open /etc/locale.conf 
4. change LANG value from LANG="en_US.UTF-8" to LANG="ja_JP.eucJP"
5. reboot the VM
6. Resource disk is not mounted.
   [root@redhat72 /]# df
　　▒ե▒▒▒▒륷▒▒   1K-▒֥▒å▒    ▒▒▒▒   ▒▒▒Ѳ▒ ▒▒▒▒% ▒ޥ▒▒▒Ȱ▒▒▒
　　/dev/sda2         33025276 1647268 31378008    5% /
　　devtmpfs           3557816       0  3557816    0% /dev
　　tmpfs              3567780       0  3567780    0% /dev/shm
　　tmpfs              3567780   16692  3551088    1% /run
　　tmpfs              3567780       0  3567780    0% /sys/fs/cgroup
　　/dev/sda1           508588  119184   389404   24% /boot
　　tmpfs               713560       0   713560    0% /run/user/1000
7. The following error is logged in /var/log/waagent
　　2017/03/06 00:53:43.638336 ERROR Event: name=WALA, op=UnhandledError, message=Traceback (most recent call last):
　　  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 68, in run
  　　  self.daemon()
  　　File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 109, in daemon
　　    self.resourcedisk_handler.run()
　　  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/resourcedisk/default.py", line 55, in run
    　　mount_point = self.activate_resource_disk()
　　  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/resourcedisk/default.py", line 65, in activate_resource_disk
  　　  mount_point = self.mount_resource_disk(mount_point, fs)
　　  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/resourcedisk/default.py", line 104, in mount_resource_disk
    　　ret = shellutil.run_get_output("parted {0} print".format(device))
　　  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/utils/shellutil.py", line 78, in run_get_output
  　　  output = ustr(output, encoding='utf-8', errors="backslashreplace")
　　TypeError: don't know how to handle UnicodeDecodeError in error callback

**Comment by FumiakiNagano** [comment]
The following should be a workaround. 

1.Open /usr/lib/systemd/system/waagent.service
2.Change “ExecStart”:
  Before) ExecStart=/usr/bin/python -u /usr/sbin/waagent -daemon
  After) ExecStart=/bin/env LANG=en_US.UTF-8 /usr/bin/python -u /usr/sbin/waagent -daemon

**Comment by hglkrijger** [comment]
@FumiakiNagano, thanks for reporting this. We currently do expect the default encoding to be utf-8, so the workaround looks good and should fix any issues with the agent. Let us know if you run into any further issues.

**Comment by yuxisun1217** [comment]
Hi @hglkrijger ,

It seems that the workaround is add language parameters in the waagent.service, and this file is provided by WALA. So do you think it's better to directly add this workaround into WALA, but not ask the customers to edit the waagent.service manually? Thanks!
