### ISSUE TITLE
Blob type mismatch [HEAD BlockBlob], [CONFIG Unknown]

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#608]
A customer reported an issue based on his reading of the logs. The customer noted the following event, and had concerns.

```
ERROR Event: name=WALinuxAgent, op=HealthCheck, message=Blob type mismatch [HEAD BlockBlob], [CONFIG Unknown]
```

This message is a telemetry event, and is used to determine when it will be safe to turn off an extraneous HEAD call to the storage blob account.  

The agent claims the status blob type (i.e., Block or Page) specified in the ExtensionsConfig.xml file disagrees with that returned via HEAD request to storage. In the case that I investigated it was meaningless since the type expressed in ExtensionsConfig was absent.

This error can be safely ignored, and it may be better to remove it from the logs.

**Comment by hglkrijger** [comment]
Closing this issue for now. If we find the event is confusing, we can hide it from the logs.
