### ISSUE TITLE
[2.2.4] Failed to copy ovf-env.xml: (000008)(000007)Failed to get dvd device on CentOS 7.1 HPC

### ISSUE THREAD

**Issue by kramimus** [Azure/WALinuxAgent#610]
Azure support recommended I report this issue here, the support ticket # is 117022815387573

We are trying to apply updates to the base CentOS 7.1 HPC disto in the Azure marketplace and then capture a VHD. 

Our process is the following
1. Boot VM with azure CLI running latest CentOS 7.1 HPC image from marketplace (boots without error)
2. SSH in and run `yum upgrade`. Among other things, it upgrades WALinuxAgent from 2.0.18 to 2.2.4
3. Run `waagent -deprovision+user`
4. Run standard capture commands `azure vm deallocate...; azure vm generalize...; azure vm capture...`

When we deploy the captured VHD in a new resource group, the deployment fails with an error on the new VM:

`OS Provisioning failed for VM '1487974532-HPC-VM0' due to an internal error.`

Looking at the boot diagnostics, there are a couple errors:

```
2017/03/07 18:54:17.381137 ERROR [ProtocolError] Provisioning failed: (000008)(000007)Failed to get dvd device
2017/03/07 18:54:17.381664 INFO Detect protocol endpoints
2017/03/07 18:54:17.381894 INFO Clean protocol
2017/03/07 18:54:17.382174 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/03/07 18:54:17.382424 INFO test for route to 168.63.129.16
2017/03/07 18:54:17.382814 INFO route to 168.63.129.16 exists
2017/03/07 18:54:17.382949 INFO Wire server endpoint:168.63.129.16
2017/03/07 18:54:17.488776 INFO Fabric preferred wire protocol version:2015-04-05
2017/03/07 18:54:17.489590 INFO Wire protocol version:2012-11-30
2017/03/07 18:54:17.490133 WARNING Server preferred version:2015-04-05
2017/03/07 18:54:22.583779 ERROR Event: name=WALA, op=Provision, message=Failed to copy ovf-env.xml: (000008)(000007)Failed to get dvd device
```

If INSTEAD of running `yum upgrade`, we run `yum upgrade --exclude=WALinuxAgent`, we end up with a captured VHD that works just fine, so it looks like there is a bad interaction between CentOS 7.1 HPC and the updated (2.2.4) version of the agent.

**Comment by hglkrijger** [comment]
@kramimus, thanks for reporting this. So far I have not been able to reproduce the issue. Here are the steps I followed for reference:
```
azure vm quick-create -M ~/.ssh/id_rsa.pub -l westus -n hpc1 -y Linux -g tests -u hans -z Standard_D2_V2 OpenLogic:CentOS-HPC:7.1:7.1.20160408
ssh 13.93.146.213
sudo -s
yum upgrade WALinuxAgent
waagent -deprovision+user -force
azure vm deallocate tests hpc1
azure vm generalize tests hpc1
azure vm capture tests hpc1 -t ~/scripts/hpc.json
azure group create -l westus hpc
azure group deployment create -f ~/scripts/hpc.json hpc
``` 
I noticed that the agent on this image is `2.0.18`, not `2.0.8` as listed above. Was that a typo, or are you using a different image? Could you provide more details on the image, region, vm sku, and deployment steps?

**Comment by kramimus** [comment]
Yes, I just checked the version output I originally captured and you are right, we started at version 2.0.18, my mistake, sorry. 

Your method is a bit more concise so I can try to reproduce from your steps. It probably does not matter much but where are you getting your hpc.json template from? azure-quickstart-templates?

**Comment by kramimus** [comment]
Ok, you are right, your method yields a successful deployment, but if I follow your steps except run "yum upgrade" instead, I get the same deployment failure.

Bad news is that there are 300+ packages upgraded by yum upgrade.

**Comment by hglkrijger** [comment]
This leads me to suspect it might be a driver update:
```
[ProtocolError] Provisioning failed: (000008)(000007)Failed to get dvd device
```
The code which generates this error is here: https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/osutil/default.py#L281 

Are there any relevant system warnings or errors for a driver failing? I think perhaps this might be an issue OpenLogic could look into?

**Comment by kramimus** [comment]
Here is the entire boot diagnostics log from a failed VM:

https://gist.github.com/kramimus/7d18767b9585d446ba65d623444971fd

I don't see any driver errors.

**Comment by kramimus** [comment]
Here is /var/log/messages from a successful boot of the captured VHD where we DID NOT upgrade WALinuxAgent (but did upgrade everything else). Might be useful for comparison:

https://gist.github.com/kramimus/5c1fc1accffe316f40147008c6c739a1

Looks like there might be some sort of Hyper-V error, not sure it is relevant:

Mar  7 19:47:57 localhost hv_fcopy_daemon: Starting Hyper-V FCOPY daemon [  OK  ]
Mar  7 19:47:57 localhost HV_FCOPY: starting; pid is:1223
Mar  7 19:47:57 localhost HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory

**Comment by szarkos** [comment]
The root cause is that ata_piix is not loading.  This issue is fixed in this change to hyperv_pvdrivers.conf: https://github.com/LIS/lis-next/commit/dde8bde8d1261d08b0f096b1ddb1d489f91e6328

For now, to fix this I would recommend just editing hyperv_pvdrivers.conf manually to make the trivial change.  We are actually close to releasing updated HPC images and drivers, and so with the next images you should no longer need to make this manual change to hyperv_pvdrivers.conf.

Some old distros also did not autoload ata_piix properly, and so WALA 1.x and 2.0.x included some extra code to load the ata_piix driver in case it did not autoload: https://github.com/Azure/WALinuxAgent/blob/archive/2.0/waagent#L6476.  I guess that behavior was dropped later, but that's why this issue does not repro with WALA 2.0.18.

**Comment by kramimus** [comment]
Excellent, thanks! I tried the Hyper-V patch and it looks like the deployment now works with the new agent and all the upgrades.

Looking forward to the CentOS-HPC update on the marketplace.
