### ISSUE TITLE
VM Created from Specialized image cannot display SSH certificate Thumbprint in classic portal

### ISSUE THREAD

**Issue by Lickkylee** [Azure/WALinuxAgent#615]
I used a public image to create an Linux VM in classic portal. I didn't run waagent -deprovision and captured the image when the VM is running.  Then I used the image to create a new VM. when the new VM is ready, the SSH certificate Thumbprint is blank. 

I understand that the thumbprint/fingerprint information might be generated/collected when provisioning the VM using waagent. However, the specialized VM didn't have same provisioning steps as generialized images. So the thumbprint/fingerprint didn't send to the fabric, thus the value is empty. (please correct if I was wrong.) 

But is there any way to update this kind information to fabric after provisioning?

**Comment by hglkrijger** [comment]
@Lickkylee there is no simple way to do this after provisioning.
