### ISSUE TITLE
v2.2.x - Blindly run custom data

### ISSUE THREAD

**Issue by u6006** [Azure/WALinuxAgent#616]
In v2.2.x, injected custom data was blindly run without checking the potential shebang line in save_customdata(). It would be an issue if the custom data is just metadata configs for Cloud-Init in non-Ubuntu/CoreOS OS's

Python snippet

        if conf.get_execute_customdata():
            logger.info("Execute custom data")
            os.chmod(customdata_file, 0o700)
            shellutil.run(customdata_file)

**Comment by hglkrijger** [comment]
@u6006 as of today we do not support cloud-init provisioning for non-Ubuntu.
