### ISSUE TITLE
WALinuxAgent 2.2.1  to 2.2.5 update in cycle on FreeBsd 11

### ISSUE THREAD

**Issue by crea7or** [Azure/WALinuxAgent#618]
2017/03/11 23:56:34.474340 INFO Checking for agent family Prod updates
2017/03/11 23:56:34.525117 INFO Instantiating Agent WALinuxAgent-2.2.1 from package
2017/03/11 23:56:34.530607 INFO Agent WALinuxAgent-2.2.1 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/03/11 23:56:34.538426 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2017/03/11 23:56:34.543089 INFO Agent WALinuxAgent-2.2.1 was previously downloaded - skipping download
2017/03/11 23:56:34.549151 INFO Agent WALinuxAgent-2.2.1 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.1/HandlerManifest.json
2017/03/11 23:56:34.556644 INFO Instantiating Agent WALinuxAgent-2.2.2 from package
2017/03/11 23:56:34.561384 INFO Agent WALinuxAgent-2.2.2 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/03/11 23:56:34.567893 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2017/03/11 23:56:34.572045 INFO Agent WALinuxAgent-2.2.2 was previously downloaded - skipping download
2017/03/11 23:56:34.577631 INFO Agent WALinuxAgent-2.2.2 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.2/HandlerManifest.json
2017/03/11 23:56:34.584830 INFO Instantiating Agent WALinuxAgent-2.2.5 from package
2017/03/11 23:56:34.589141 INFO Agent WALinuxAgent-2.2.5 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/03/11 23:56:34.594945 INFO Ensuring Agent WALinuxAgent-2.2.5 is downloaded
2017/03/11 23:56:34.599071 INFO Agent WALinuxAgent-2.2.5 was previously downloaded - skipping download
2017/03/11 23:56:34.604005 INFO Agent WALinuxAgent-2.2.5 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.5/HandlerManifest.json
2017/03/11 23:57:36.954030 INFO Event: name=WALinuxAgent-2.2.5, op=HeartBeat, message=
2017/03/12 00:27:38.210983 INFO Event: name=WALinuxAgent-2.2.5, op=HeartBeat, message=
2017/03/12 00:56:38.452914 INFO Checking for agent family Prod updates
2017/03/12 00:56:39.590815 INFO Instantiating Agent WALinuxAgent-2.2.1 from package
2017/03/12 00:56:39.597039 INFO Agent WALinuxAgent-2.2.1 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/03/12 00:56:39.604590 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2017/03/12 00:56:39.609550 INFO Agent WALinuxAgent-2.2.1 was previously downloaded - skipping download
2017/03/12 00:56:39.616532 INFO Agent WALinuxAgent-2.2.1 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.1/HandlerManifest.json
2017/03/12 00:56:39.625272 INFO Instantiating Agent WALinuxAgent-2.2.2 from package
2017/03/12 00:56:39.630485 INFO Agent WALinuxAgent-2.2.2 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/03/12 00:56:39.637550 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2017/03/12 00:56:39.642140 INFO Agent WALinuxAgent-2.2.2 was previously downloaded - skipping download
2017/03/12 00:56:39.648072 INFO Agent WALinuxAgent-2.2.2 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.2/HandlerManifest.json
2017/03/12 00:56:39.655677 INFO Instantiating Agent WALinuxAgent-2.2.5 from package
2017/03/12 00:56:39.660596 INFO Agent WALinuxAgent-2.2.5 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/03/12 00:56:39.667132 INFO Ensuring Agent WALinuxAgent-2.2.5 is downloaded
2017/03/12 00:56:39.671687 INFO Agent WALinuxAgent-2.2.5 was previously downloaded - skipping download
2017/03/12 00:56:39.677438 INFO Agent WALinuxAgent-2.2.5 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.5/HandlerManifest.json
2017/03/12 00:57:39.332816 INFO Event: name=WALinuxAgent-2.2.5, op=HeartBeat, message=

**Comment by brendandixon** [comment]
@crea7or The logs are admittedly noisy, but they indicate that v2.2.5 is running as the most current version. There is no error that I can see.

**Comment by crea7or** [comment]
No, it switches from 2.2.1 to 2.2.2,next to 2.2.5 - a part of recent log (today): 

2017/03/13 17:00:02.807221 INFO Agent WALinuxAgent-2.2.1 error state: Last Failu
re: 0.0, Total Failures: 0, Fatal: False
2017/03/13 17:00:02.814651 INFO Ensuring Agent WALinuxAgent-2.2.1 is downloaded
2017/03/13 17:00:02.819598 INFO Agent WALinuxAgent-2.2.1 was previously download
ed - skipping download
2017/03/13 17:00:02.826833 INFO Agent WALinuxAgent-2.2.1 loaded manifest from /v
ar/lib/waagent/WALinuxAgent-2.2.1/HandlerManifest.json
2017/03/13 17:00:02.835099 INFO Instantiating Agent WALinuxAgent-2.2.2 from pack
age
2017/03/13 17:00:02.840085 INFO Agent WALinuxAgent-2.2.2 error state: Last Failu
re: 0.0, Total Failures: 0, Fatal: False
2017/03/13 17:00:02.846745 INFO Ensuring Agent WALinuxAgent-2.2.2 is downloaded
2017/03/13 17:00:02.851086 INFO Agent WALinuxAgent-2.2.2 was previously download
ed - skipping download
2017/03/13 17:00:02.856724 INFO Agent WALinuxAgent-2.2.2 loaded manifest from /v
ar/lib/waagent/WALinuxAgent-2.2.2/HandlerManifest.json
2017/03/13 17:00:02.864154 INFO Instantiating Agent WALinuxAgent-2.2.5 from pack
age

**Comment by brendandixon** [comment]
@crea7or No, it's not. The logs are simply noisy and slightly misleading. Those messages (and you can verify this by examining https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/ga/update.py) only attest to the fact that the versions are present; not that they're used.
