### ISSUE TITLE
Improve the Azure Linux Agent’s logic for distro specific functions

### ISSUE THREAD

**Issue by SuperScottz** [Azure/WALinuxAgent#62]
As we planned, we will refactor current code of Azure Linux Agent with improving the logic for distro specific functions, submitt this bug to track the progress.

#### Suggestions from customer to refactor the code, put it here for reference. 

a) split up the waagent python script, into 

- a core script (required for creation, deletion, start and shutdown of a VM) 
- multiple distro-orientated scripts (of which only one script will be installed, for the specific linux distro that is running on the VM)

Original comment link by trialotto: http://feedback.azure.com/forums/216843-virtual-machines/suggestions/6790345-options-to-set-waagent-conf-variables-linux

**Comment by ahmetalpbalkan** [comment]
@SuperScottz has there been any progress or plans about this?
