### ISSUE TITLE
WAAgent should always delete ssh keys on deprovisioning

### ISSUE THREAD

**Issue by ne-msft** [Azure/WALinuxAgent#621]
This circles back to issue #591 

WAAgent should always delete ssh keys on deprovision. This is a private key which should never be put in an image.

Currently Provisioning.RegenerateSshHostKeyPair=n will prevent regeneration, but also deletion of keys. Deletion on deprovisioning should not be affected by this switch.

**Comment by hglkrijger** [comment]
@ne-msft, Keys are deleted on de-provisioning

**Comment by ne-msft** [comment]
@hglkrijger Only when Provisioning.RegenerateSshHostKeyPair is set to yes. See [here](https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/pa/deprovision/default.py#L111)
The option is disabled for cloud-init enabled distributions. In the spirit of "Defense in depth", the keys should always be removed, no matter what this option says.
