### ISSUE TITLE
Error uploading status blob

### ISSUE THREAD

**Issue by pritz2** [Azure/WALinuxAgent#622]
Seeing this issue: https://github.com/Azure/WALinuxAgent/issues/409 in a VMSS. Keeps happening even on update of old VMs, but new VMs have no errors.

**Comment by hglkrijger** [comment]
@pritz2, the fix for this was further upstream in Azure. To get the fix on your older VMs, you can either add a tag (see https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags) or resize the VM. Both should trigger creation of the missing status blob.
