### ISSUE TITLE
message=WALinuxAgent-2.2.6 did not terminate cleanly

### ISSUE THREAD

**Issue by FumiakiNagano** [Azure/WALinuxAgent#626]
We see the following errors.

2017/03/27 14:00:45.746183 INFO WALinuxAgent-2.2.6 running as process 52863
2017/03/27 14:00:45.762344 INFO WALinuxAgent-2.2.6 did not terminate cleanly
2017/03/27 14:00:45.765942 ERROR Event: name=WALinuxAgent, op=Restart, message=WALinuxAgent-2.2.6 did not terminate cleanly
2017/03/27 14:00:45.787347 INFO Checking for agent family Prod updates
2017/03/27 14:00:45.791247 INFO Wire server endpoint:168.63.129.16
2017/03/27 14:01:15.868247 ERROR get API versions returned status code [400]
2017/03/27 14:01:15.879299 ERROR Event: name=WALA, op=InitializeHostPlugin, message=
2017/03/27 14:01:15.892356 ERROR host plugin channel is not available
2017/03/27 14:01:15.906145 WARNING Agent WALinuxAgent-2.2.6 failed with exception: 'NoneType' object has no attribute 'find'
2017/03/27 14:01:45.397617 WARNING Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with return code: 1
2017/03/27 14:01:45.416995 ERROR Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with return code: 1
2017/03/27 14:01:45.441745 WARNING Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' returned code: 1

According to #589, it seems that the above issue was fixed at version 2.2.6. However, as you can see, we still see the errors on 2.2.6.

**Comment by hglkrijger** [comment]
@FumiakiNagano - the error is a little different, can you provide a repro?
```
2017/03/27 14:01:15.906145 WARNING Agent WALinuxAgent-2.2.6 failed with exception: 'NoneType' object has no attribute 'find'
```

**Comment by FumiakiNagano** [comment]
@hglkrijger 
You can find the repro steps at #632

2017/03/28 11:15:38.100784 WARNING Agent WALinuxAgent-2.2.6 failed with exception: 'NoneType' object has no attribute 'find'

**Comment by hglkrijger** [comment]
@FumiakiNagano ok, then closing this as a duplicate.
