### ISSUE TITLE
Agent returns 400 error from status request, but claims to have successfully reported status

### ISSUE THREAD

**Issue by avenging** [Azure/WALinuxAgent#627]
The latest azure agent (and probably previous ones too) cannot seem to report correctly back to Azure that they are Ok when using Managed Disks, but the agent itself seems to think everything is fine. The status request continually returns a 400 BAD REQUEST:

2017/03/27 11:46:54.831691 VERBOSE Posting VM status to host plugin
2017/03/27 11:46:54.839248 VERBOSE HTTP connection [PUT] [/status]  (debug content removed wasn't sure how sensitive it was)
2017/03/27 11:46:55.016262 VERBOSE HTTP response status: [400]
2017/03/27 11:46:55.022925 WARNING PUT http://168.63.129.16:32526/status [400: Bad Request]
2017/03/27 11:46:55.034311 VERBOSE Successfully reported vm agent status

The Azure Agent is never shown as running in the Azure portal and additional plugins cannot be installed (such as the azure backup extension) due to the Azure infrastructure not knowing the state of the agent.

[root@blah]# waagent -version
WALinuxAgent-2.2.6 running on redhat 7.3
Python: 2.7.5
Goal state agent: 2.2.6

**Comment by hglkrijger** [comment]
@avenging, thanks for reporting this, we are aware of the issue. For the moment, the agent will not be able to report status from behind a NSG if using Managed Disks. There are several fixes in the pipeline for this, including one to correct the misleading log statement above. We are working to get this fixes as soon as we can.

**Comment by hglkrijger** [comment]
I will update this issue when the fixes are generally available.

**Comment by hglkrijger** [comment]
@avenging this fix is generally available.
