### ISSUE TITLE
ERROR Failed to run 'deprovision': 

### ISSUE THREAD

**Issue by kolargol** [Azure/WALinuxAgent#628]
Hi,

On latest credativ (Debain 8), waagent do not deprovision image:

> python3 /usr/sbin/waagent -force -deprovision
> WARNING! The waagent service will be stopped.
> WARNING! All SSH host key pairs will be deleted.
> WARNING! Cached DHCP leases will be deleted.
> WARNING! root password will be disabled. You will not be able to login as root.
> WARNING! /etc/resolv.conf will be deleted.
> 2017/03/27 12:48:23.065983 ERROR Failed to run 'deprovision': 

there is no more details, even on debug level it do not show anything usable to trace problem. Debian image is in clean state (latest 8.7), waagent 2.2.6 (but looks like problem is since 2.2.2).

Anyone can help debug that?

**Comment by hglkrijger** [comment]
This appears to be an issue in the latest Debian images. 

Compare https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/osutil/debian.py :

    def stop_agent_service(self):
        return shellutil.run("service azurelinuxagent stop", chk_err=False)

To /usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/debian.py:

    def stop_agent_service(self):
        raise NotImplementedError

The result of this is the following:
```
root@testdeb8:/home/hans# waagent -deprovision -force
WARNING! The waagent service will be stopped.
WARNING! All SSH host key pairs will be deleted.
WARNING! Cached DHCP leases will be deleted.
WARNING! root password will be disabled. You will not be able to login as root.
WARNING! /etc/resolv.conf will be deleted.
2017/03/20 23:59:23.161923 ERROR Failed to run 'deprovision':
```
Digging in:
```
root@testdeb8:/home/hans# /usr/bin/python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from azurelinuxagent.pa.deprovision import get_deprovision_handler
>>> h = get_deprovision_handler()
>>> h.run(force=True, deluser=False)
WARNING! The waagent service will be stopped.
WARNING! Cached DHCP leases will be deleted.
WARNING! /etc/resolv.conf will be deleted.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/azurelinuxagent/pa/deprovision/default.py", line 138, in run
    action.invoke()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/pa/deprovision/default.py", line 37, in invoke
    self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/debian.py", line 43, in stop_agent_service
    raise NotImplementedError
NotImplementedError
```

@waldiTM, is this a known issue?

**Comment by kolargol** [comment]
ou that's weird. Is this something that i can patch easy or there is a reason behind it?

**Comment by kolargol** [comment]
i have patched file with:
`    def stop_agent_service(self):
        return shellutil.run("service walinuxagent stop", chk_err=False)

    def start_agent_service(self):
        return shellutil.run("service walinuxagent start", chk_err=False)

    def start_network(self):
        pass
`

and deprovision works correctly now. Note that by default there is no "azurelinuxagent" but there is "walinuxagent"

**Comment by kolargol** [comment]
[patch here](https://onefellow.com/download/waagent_isse_628.patch) - not sure that's all but after patching it and deploying on azure with deprovision, image seems correct.

**Comment by hglkrijger** [comment]
yes, this is the code we have in our repo. 

@waldiTM, any chance we could get this fixed in the Debian images?

**Comment by kolargol** [comment]
yes, same question: when it will be fixed in the azure images?

**Comment by hglkrijger** [comment]
We have confirmed that Credativ is aware of this, and are getting a fix ready. Closing this issue as there is nothing more to be done in the agent. I will update this issue when the updated image is released.

**Comment by hglkrijger** [comment]
@kolargol - this has been fixed.
