### ISSUE TITLE
Host plugin fails for multi-nic VMs

### ISSUE THREAD

**Issue by FumiakiNagano** [Azure/WALinuxAgent#632]
(This issue relates to #626)

Repro steps. As far as I know, this issue happens 100% after following the below steps.

1.	Create a Multi-NICs VMs.
I used the following template.
https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-multiple-nics-linux
I tested Ubuntu OS 14.04.4-LTS and CentOS 7.3
2.	Reset VM’s password using “Reset password” -> “Reset password” on Azure Portal
3.	SSH into the VM and update waagent to 2.2.6
wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
wget https://github.com/Azure/WALinuxAgent/archive/v2.2.6.zip
apt-get update
apt-get install unzip
unzip ./v2.2.6.zip
cd WALinuxAgent-2.2.6/
python setup.py install
service walinuxagent restart
waagent version
4.	Block HTTPS (443) outbound on nic1 (which is eth0) using NSG on Azure Portal.
5.	Restart waagent
6.	“message=WALinuxAgent-2.2.6 did not terminate cleanly” is logged repeatedly on /var/log/waagent
2017/03/28 11:15:07.992057 ERROR Event: name=WALinuxAgent, op=Restart, message=WALinuxAgent-2.2.6 did not terminate cleanly
2017/03/28 11:15:07.994526 INFO Checking for agent family Prod updates
2017/03/28 11:15:07.995759 INFO Wire server endpoint:168.63.129.16
2017/03/28 11:15:38.079518 ERROR get API versions returned status code [400]
2017/03/28 11:15:38.093941 ERROR Event: name=WALA, op=InitializeHostPlugin, message=
2017/03/28 11:15:38.099217 ERROR host plugin channel is not available
2017/03/28 11:15:38.100784 WARNING Agent WALinuxAgent-2.2.6 failed with exception: 'NoneType' object has no attribute 'find'
2017/03/28 11:16:07.939638 WARNING Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with return code: 1
2017/03/28 11:16:07.941868 ERROR Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' failed with return code: 1
2017/03/28 11:16:07.944094 WARNING Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' returned code: 1

**Comment by hglkrijger** [comment]
@FumiakiNagano, I am able to reproduce this and there are two issues:
- the component we are communicating with is not handling multiple nics; I am looking into a fix for this outside of the agent or for any possible workarounds
- the agent is mishandling the condition and crashing; I will submit a fix for this so the failure is more graceful

**Comment by hglkrijger** [comment]
@FumiakiNagano I have confirmed the bug lies upstream in the component with which we are communicating, and this is where the fix needs to be. For the moment this unfortunately means the agent will not work with multiple NICs behind a NSG.

**Comment by hglkrijger** [comment]
Closing this issue as the fix on the agent side is merged. When the external fix is generally available, I will update this issue.

**Comment by hglkrijger** [comment]
@FumiakiNagano - this fix is generally available.
