### ISSUE TITLE
WALinuxAgent: Unable to add dhcp broadcast route

### ISSUE THREAD

**Issue by ujjwalKSingh** [Azure/WALinuxAgent#650]
Hi, 
I am facing the below issue this issue while deploying the VM that leads to deployment failure. I can ssh to VM. Can you please me in this ?

2017/04/05 15:19:20 Azure Linux Agent Version: WALinuxAgent-2.0.18
2017/04/05 15:19:20 Linux Distribution Detected      : debian
2017/04/05 15:19:20 Module /lib/modules/3.16.7-cb2000v1/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2017/04/05 15:19:20 VMM Init script not found.  Provisioning for Azure
2017/04/05 15:19:20 IPv4 address: 10.1.1.10
2017/04/05 15:19:20 MAC  address: 00:0D:3A:16:AD:36
2017/04/05 15:19:20 Probing for Azure environment.
2017/04/05 15:19:20 DoDhcpWork: Missing default route - adding broadcast route for DHCP.
2017/04/05 15:19:20 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/04/05 15:19:30 ERROR:timed out
2017/04/05 15:19:30 ERROR:Traceback (most recent call last):
2017/04/05 15:19:30 ERROR:  File "/usr/sbin/waagent", line 6171, in DoDhcpWork
2017/04/05 15:19:30 ERROR:    receiveBuffer = sock.recv(1024)
2017/04/05 15:19:30 ERROR:timeout: timed out
2017/04/05 15:19:30 ERROR:
2017/04/05 15:19:30 DoDhcpWork: Removing broadcast route for DHCP.
2017/04/05 15:19:30 DoDhcpWork: Missing default route - adding broadcast route for DHCP.
2017/04/05 15:19:30 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/04/05 15:19:40 ERROR:timed out
2017/04/05 15:19:40 ERROR:Traceback (most recent call last):
2017/04/05 15:19:40 ERROR:  File "/usr/sbin/waagent", line 6171, in DoDhcpWork
2017/04/05 15:19:40 ERROR:    receiveBuffer = sock.recv(1024)
2017/04/05 15:19:40 ERROR:timeout: timed out
2017/04/05 15:19:40 ERROR:
2017/04/05 15:19:40 DoDhcpWork: Removing broadcast route for DHCP.
2017/04/05 15:19:40 DoDhcpWork: Missing default route - adding broadcast route for DHCP.
2017/04/05 15:19:40 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/04/05 15:19:50 ERROR:timed out
2017/04/05 15:19:50 ERROR:Traceback (most recent call last):
2017/04/05 15:19:50 ERROR:  File "/usr/sbin/waagent", line 6171, in DoDhcpWork
2017/04/05 15:19:50 ERROR:    receiveBuffer = sock.recv(1024)
2017/04/05 15:19:50 ERROR:timeout: timed out
2017/04/05 15:19:50 ERROR:
2017/04/05 15:19:50 DoDhcpWork: Removing broadcast route for DHCP.
2017/04/05 15:19:50 DoDhcpWork: Missing default route - adding broadcast route for DHCP.
2017/04/05 15:19:50 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/04/05 15:20:00 ERROR:timed out
2017/04/05 15:20:00 ERROR:Traceback (most recent call last):
2017/04/05 15:20:00 ERROR:  File "/usr/sbin/waagent", line 6171, in DoDhcpWork
2017/04/05 15:20:00 ERROR:    receiveBuffer = sock.recv(1024)
2017/04/05 15:20:00 ERROR:timeout: timed out
2017/04/05 15:20:00 ERROR:
2017/04/05 15:20:00 DoDhcpWork: Removing broadcast route for DHCP.
2017/04/05 15:20:00 DoDhcpWork: Missing default route - adding broadcast route for DHCP.
2017/04/05 15:20:00 DoDhcpWork: Setting socket.timeout=10, entering recv
2017/04/05 15:20:10 ERROR:timed out
2017/04/05 15:20:10 ERROR:Traceback (most recent call last):
2017/04/05 15:20:10 ERROR:  File "/usr/sbin/waagent", line 6171, in DoDhcpWork

thanks,
Ujjwal

**Comment by brendandixon** [comment]
@ujjwalKSingh The agent needs to obtain DHCP option 245 to know the address of the Azure "wireserver" which provides various state. This error often means that DHCP is misconfigured in some interesting way.

We have addressed issues in this area and I suggest upgrading to the most recent agent in your vendor's repository.

**Comment by ujjwalKSingh** [comment]
@brendandixon, thanks for your response.
I can understand the moving to recent agent will resolve this issue. But it requires different packages dependency.

So, can you please provide the info regarding in what sense DHCP is misconfigured?
Is it, dhcp packet must go through the first network device detected? if you can pin point then it will be great.

In my scenarios, third interface is management and dhcp packet must go through that interface only.


-ujjwal

**Comment by brendandixon** [comment]
@ujjwalKSingh The agent *always* sends its requests across the primary interface. So, limiting DHCP access to the secondary will keep the agent from working. We have no reliable means of determining which interface to use. Primary is safest.

**Comment by ujjwalKSingh** [comment]
@brendandixon Thanks ..!!
