### ISSUE TITLE
Two machines in a scale set: Failed to report vm agent status

### ISSUE THREAD

**Issue by jjjordanmsft** [Azure/WALinuxAgent#652]
I end up with this status for two of my machines in the public scale set of an ACS cluster:

```
"vmAgent": {
    "vmAgentVersion": "Unknown",
    "statuses": [
      {
        "code": "ProvisioningState/Unavailable",
        "level": "Warning",
        "displayStatus": "Not Ready",
        "message": "VM status blob not found.",
        "time": "2017-04-05T22:59:56+00:00"
      }
    ]
```

and the `waagent.log` is filled with:

```
2017/04/03 10:09:48.318199 ERROR Event: name=WALA, op=, message=Failed to report vm agent status: (000008)Failed to get status blob type: 404
```

However, there is still a heartbeat:

```
2017/04/03 13:34:33.759472 INFO Event: name=WALA, op=HeartBeat, message=
```

And extensions on those machines seem to be updated -- but Azure Powershell will report failure when I try to deploy anything to them (i.e., update the scale set properties).

What can I do to fix this?

**Comment by hglkrijger** [comment]
@jjjordanmsft this is an instance of an issue where CRP fails to create a status blob. The bug has since been fixed, so any new deployments should not have the same issue. If you prefer to recover this deployment, you can create the status blob manually.
