### ISSUE TITLE
Please support distros managed by purely systemd, e.g. Archlinux.

### ISSUE THREAD

**Issue by enihcam** [Azure/WALinuxAgent#653]
Please support distros managed by systemd, e.g. Archlinux.

Concretely, there are three comments:

1. Before falling back to default, please detect if the distro is managed by systemd.
`
2017/04/06 15:57:46.294102 WARNING Unable to load distro implemetation for arch.
2017/04/06 15:57:46.312828 WARNING Use default distro implemetation instead.
2017/04/06 15:57:46.314404 INFO No RDMA handler exists for distro='arch' version=''
`

2. Archlinux does not have debian tools like ifup and ifdown.
`
2017/04/06 15:58:24.812463 VERBOSE run cmd 'ifdown eth0 && ifup eth0'
2017/04/06 15:58:24.825142 ERROR run cmd 'ifdown eth0 && ifup eth0' failed
2017/04/06 15:58:24.834340 ERROR Error Code:127
2017/04/06 15:58:24.841365 ERROR Result:/bin/sh: ifdown: command not found
`

3. DHCP is managed by systemd in Archlinux.
`
2017/04/06 15:58:49.945059 WARNING Dhcp client is not running. 
2017/04/06 15:58:49.949842 VERBOSE run cmd 'pidof dhclient'
2017/04/06 15:58:49.968002 ERROR run cmd 'pidof dhclient' failed
2017/04/06 15:58:49.968590 ERROR Error Code:1
2017/04/06 15:58:49.970555 ERROR Result:
`

Thanks!

Attached detailed log:
[Archlinux.b49e9e4a-8f0f-4eec-82ed-78b47de3c7b5.serialconsole.zip](https://github.com/Azure/WALinuxAgent/files/901971/Archlinux.b49e9e4a-8f0f-4eec-82ed-78b47de3c7b5.serialconsole.zip)

**Comment by enihcam** [comment]
I found that WALinuxAgent 'supports' Archlinux, but it just does not work. :(

**Comment by hglkrijger** [comment]
@enihcam we are happy to accept a PR to add this support, but have no plans to add this in the near term.

**Comment by enihcam** [comment]
@hglkrijger Can I send a pull-request to fix this? 😄

**Comment by hglkrijger** [comment]
@enihcam yes, please do.
