### ISSUE TITLE
Can WALA support multiple IP addresses?

### ISSUE THREAD

**Issue by gossion** [Azure/WALinuxAgent#657]
Currently, Azure support assigning multiple IP addresses for one NIC, either primary or secondary NIC. See this [link](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-multiple-ip-addresses-template) for deployment guide.  However, in the deployment it needs users to manually add all the private IP addresses to the VM, for example, in Ubuntu, user need to add these lines to the end of /etc/network/interfaces.d/eth[?].cfg
  ```
   iface eth0 inet static
   address <your private IP address here>
   netmask <your subnet mask>
  ```  

Can WALA detect the change of NICs information, add them to cfg file and reset the network interface accordingly?

**Comment by hglkrijger** [comment]
@gossion, the agent is not the appropriate mechanism for this type of configuration.

**Comment by Klaas-** [comment]
Why is this not the right mechanism for adding secondary IPs? What would be the appropriate place to get runtime changes into a VM?

You are already modifying the network configuration through the agent - adding routes, modifying the firewall configuration. Why not add secondary IPs aswell?
