### ISSUE TITLE
Outbound connectivity from a secondary NIC

### ISSUE THREAD

**Issue by gossion** [Azure/WALinuxAgent#658]
I met an connection issue on setting up internal load balancer (ILB) on the secondary NIC. Here is the configuration:

  VM1 has two NICs:
  - VM1NIC1(primary): 10.0.0.5 (subnet 10.0.0.0/24)
  - VM1NIC2(secondary): 10.0.1.5 (subnet 10.0.1.0/24)  #ILB on this NIC

  ILB:
  - FrondEnd: 10.0.1.4 (subnet 10.0.1.0/24)  #Same subnet with NIC2
  - Backendpool: 10.0.1.5 (VM1NIC2), 10.0.1.6(VM2NIC2)
  - Probe:  -Protocol tcp -Port 80

When I tried to connect to the VM through the ILB frondend 10.0.1.4, it failed. After an investigation, I found that the ILB can't probe the VM through secondary NIC correctly. During probing, the ILB use IP 168.63.129.16 to connect to secondary NICs (10.0.1.5), they are not in same subnet,  so the default gateway (10.0.0.1) was used and then it fail to connect. 

As a workaround, I need to add a custom route for the secondary NIC. The custom route is as below: 
```
echo 150 custom >> /etc/iproute2/rt_tables 

ip rule add from 10.0.1.5 lookup custom
ip route add default via 10.0.1.1 dev eth2 table custom
```

Then the ILB works. I wonder if it is possible that WALA can handle such a situation that traffic from the secondary NIC should go to its gw (10.0.1.1 in this case) rather than use a default gw?

Thanks

**Comment by hglkrijger** [comment]
@gossion, the agent is not in the business of trying to detect or manage how a user would like to setup their network configuration. We respond to options requests passed to the system by dhcp, if necessary. In most cases these are handled by dhcpd and outside the scope of the agent's responsibilities.
