### ISSUE TITLE
[Microsoft.OSTCExtensions.LinuxDiagnostic] SyntaxError: Missing parentheses in call to 'print'  

### ISSUE THREAD

**Issue by enihcam** [Azure/WALinuxAgent#671]
`
Apr 16 01:26:44 shenzhen python[369]: 2017/04/16 01:26:44.196907 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9023] Enable extension [diagnostic.py -enable]

Apr 16 01:26:44 shenzhen python[369]: Traceback (most recent call last):

Apr 16 01:26:44 shenzhen python[369]:   File "/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9023/diagnostic.py", line 33, in <module>

Apr 16 01:26:44 shenzhen python[369]:     from Utils.imds_util import ImdsLogger

Apr 16 01:26:44 shenzhen python[369]:   File "/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9023/Utils/imds_util.py", line 89

Apr 16 01:26:44 shenzhen python[369]:     print result

Apr 16 01:26:44 shenzhen python[369]:                ^

Apr 16 01:26:44 shenzhen python[369]: SyntaxError: Missing parentheses in call to 'print'

Apr 16 01:26:45 shenzhen python[369]: 2017/04/16 01:26:45.214558 ERROR Event: name=Microsoft.OSTCExtensions.LinuxDiagnostic, op=Enable, message=(000003)Non-zero exit code: 1, diagnostic.py -enable
`

**Comment by hglkrijger** [comment]
Thanks for reporting this @enihcam; it seems to be an extension issue, could you please open this over at https://github.com/Azure/azure-linux-extensions?

**Comment by jasonzio** [comment]
I think this is fixed in 2.3.9025, but please do open the issue on the [Linux extensions project](https://github.com/Azure/azure-linux-extensions) as @hglkrijger indicated.
