### ISSUE TITLE
Is there a way for Agent for get the password used during provision?

### ISSUE THREAD

**Issue by jan-wang** [Azure/WALinuxAgent#678]
Hi,
After i deploy a VM, is there a way to get the password I used during provision in agent?
For example, after deploy, reboot the VM, I need that password to do some special work.
I find agent get password from ovf-env.xml but I find password is shown as '*' in that file.

**Comment by brendandixon** [comment]
@jan-wang Passwords are *never* saved as clear-text to the VM (or even in Linux). That would open a huge security hole. You need to take other means to remember the password given during provisioning. Or, alternatively, provide an SSH public key and rely on it for authentication.
