### ISSUE TITLE
Which port Azure agent open?

### ISSUE THREAD

**Issue by jan-wang** [Azure/WALinuxAgent#681]
Hi all,
Can someone tell me which port Azure agent open but not used?
I run a tool on one of my VM and get the result that Azure agent open a TCP endpoints but not used.

For now, I only know it opens 68 for dhcp but it's udp and 443 for https but this one should be used.
Can anyone help me on this?

**Comment by brendandixon** [comment]
@jan-wang The ports the agent uses are those needed to receive DHCP packets (as you've noted), engage with Azure Storage (usually 443, but not always), and to send / received data to / from the underlying Azure fabric (usually port 80, but sometimes others, such as, 32536).

However, these can be dynamic. For example, the 32536 port used with the Azure fabric is subject to change. When using Managed Disks the port used with Azure Storage also is no longer 443. Even with DHCP the agent sends / receives packets on the NIC for which DHCP is enabled (and these are broadcast UDP packets on port 68).

I hope this helps.
