### ISSUE TITLE
Deprovision Should Remove all Extension Data

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#705]
A customer reported an [issue](https://github.com/Azure/custom-script-extension-linux/issues/94) against CustomScript.  He reported that he ran the deprovision step, but it did not clean up /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript*.  As a result, when he re-deployed the VM he had to explicitly delete the extension before executing any new CustomScript extension.  CustomScript is assiduous.  It noticed a discrepancy, and refused to execute. I can see how other extensions may not flag this.

I checked the docs, and deprovision does not call out that extension data are deleted.  Is there any reason to preserve extension data across deprovisions?  If not, can you please clean these files up as well.

**Comment by brendandixon** [comment]
@boumenot This is an ill-defined case. While, at one level, I agree that deprovisioning should remove the content, I am concerned about possible side-effects of doing so.

**Comment by brendandixon** [comment]
@boumenot It turns out that current agent versions (e.g., 2.1+) do remove all the data. Closing.

**Comment by boumenot** [comment]
:) For posterity or when I have to re-read this... What should the agent do for extensions that exist on the VM when deprovision is executed.  Should the agent delete all data, or should it invoke the uninstall action for each installed extension.

**Comment by brendandixon** [comment]
@boumenot Good point. The entire directories, `/var/lib/waagent` and `/var/log/azure`, are safe to remove in deprovisioning.

**Comment by yuhuijiang** [comment]
Hi, @brendandixon ,
During WALA deprovisioning,WALA remove it's log file(/var/log/waagent.log),but doesn't remove extension's log(/var/log/azure/*).

According to your reply "The entire directories, /var/lib/waagent and /var/log/azure, are safe to remove in deprovisioning.", why doesn't remove this folder? For some special considering?

**Comment by brendandixon** [comment]
@yuhuijiang A simple oversight. We can correct that. #717.
