### ISSUE TITLE
Provision Event is not Fired if Customer Forgets to Deprovision VM

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#706]
Scenario:

 1. Customer deploys a gallery image.
 1. Agent sends a provision event, and touches /var/lib/waagent/provisioned.
 1. Customer turns off VM.
 1. Customer creates a new VM using the VHD from (1).
 1. Agent sees that /var/lib/waagent/provisioned exists, and skips further processing.

As a result of the agent skipping further processing, a provision event is never sent, and the customer sees a OS Provisioning Timeout.  It would be better if the agent took into account the unique ID of the VM, and observed that if this value changes it should send a provision event.  The provision should include a message to the customer indicating that they failed to deprovision the VM.

In the case of a cloud-init enabled VM, cloud-init will reprovision the VM.

**Comment by brendandixon** [comment]
Addressed in #707
