### ISSUE TITLE
v2.2.x - shutting down VM etc must be processed if extension handling goes wrong

### ISSUE THREAD

**Issue by u6006** [Azure/WALinuxAgent#710]
For using a Linux variant that's not in your list to support, I cannot shut down my VM with Portal if an Extension failed to install/run. It's probably because all events are serially queued together without priority assigned.

**Comment by brendandixon** [comment]
@u6006 Without logs, we have no idea of what the issue could be. The agent, just so you know, cannot prevent shutting down a VM as it plays no role in that.

**Comment by u6006** [comment]
I've deleted the instance since it cannot be shut down. I cannot reproduce it on my other instances. You can close it as no-repro for now. I will re-open or re-file when running into it next time.
