### ISSUE TITLE
v2.2.2 - setting extension cmd-line hung if the install failed

### ISSUE THREAD

**Issue by u6006** [Azure/WALinuxAgent#713]
This is a long post.

Let me know if you have addressed this issue in newer versions of Waagent.

The cmd-line must fail right away and Waagent stops retries (it MUST remove related goal state etc) if the extension fails with unrecoverable issue(s). Details are as follows:

- LinuxAsm is an incompatible Azure Extension with my instance (though its OSUtil is in Waagent, so this extension should know it's the supported platform). Installation failed with the following message:

- <ext-root>/config/HandlerStatus
{"status": "NotReady", "code": -1, "name": "Microsoft.Azure.Extensions.LinuxAsm", "version": "2.2.3", "extensions": [], "message": "(000003)Non-zero exit code: 14, asm-extension enable"}

- <ext-root>/status/0.status
[
        {
                "version": 1,
                "timestampUTC": "2017-05-13T18:56:32Z",
                "status": {
                        "operation": "Enable ASM",
                        "status": "error",
                        "formattedMessage": {
                                "lang": "en",
                                "message": "Enable ASM failed: OS is not supported. Error: Failed to locate a release file. OS Name and version cannot be determined."
                        }
                }
        }
]

- waagent.log
2017/05/12 22:22:52.738589 ERROR Event: name=Microsoft.Azure.Extensions.LinuxAsm, op=Install, message=(000003)Non-zero exit code: 14, asm-extension install
2017/05/12 22:22:52.925266 INFO Event: name=WALinuxAgent, op=HealthCheck, message=Blob type match [PageBlob]
...
2017/05/13 11:56:32.333366 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.3] Enable extension.
2017/05/13 11:56:32.345567 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.3] Launch command:asm-extension enable
2017/05/13 11:56:33.362721 ERROR Event: name=Microsoft.Azure.Extensions.LinuxAsm, op=Enable, message=(000003)Non-zero exit code: 14, asm-extension enable

- issues
1. my cmd-line that launched the install hung there overnight (>3 hours). I saw it failed in the morning (**it must fail right away**) (log shows that required events/message have been communicated)
2. retry is triggered with new goal-state (updating), restart of Waagent ... (**It must fail forever in this case**)

There're multiple issues here and the major one is to combine all info together and make the right decision for them (Waagent, extension, Fabric Controller (backend components), az cmd-line etc). IMO, all required info is already there.

Below is the related feature list (not directly related to this issue)

- Waagent MUST provide extension allow-list for instances to filter out incompatible and risky extensions.
https://github.com/Azure/WALinuxAgent/issues/656 (previously filed issue)
- Azure components MUST warn users about the potential issues if the operation triggers an Azure Extension to install and run
- Azure Extensions MUST do pre-install/enable checks (they can only be installed and run on tested platforms) **AFAIK, most extensions are not tested on all platforms listed in Waagent's OSUtil dir.**

Features like these will help both extension users and devs:
- devs don't need to worry about the unsupported/untested platforms
- users don't need to worry about that an extension (enabled by a wrong/curious click in the portal) might screw up their instances

more details can be provided

**Comment by brendandixon** [comment]
@u6006 I do not know why, in your case, it took so long for the Azure CLI to detect the failed installation. However, the agent *does* emit all the correct messages and makes the proper updates to the storage blob used to communicate state. If the issue persists, I suggest opening an issue against the Azure CLI.

Regarding your other points (e.g., providing an extension allow-list): You raise good points with which we (generally) agree. However, making such changes requires adjusting many moving parts. All I can say is that we're well aware that we could and should do better. We are evaluating various approaches.

**Comment by u6006** [comment]
@brendandixon I agree that most parts of this issue are not Waagent related. One thing that I want to emphasize on is:
Can Waagent stop retries if the extension fails with unrecoverable issues? In my case, VMAccessForLinux failed for detecting unknown (unsupported) platform. I would say, in this case, retry MUST be suppressed. I'd like to see this directly happen inside Waagent, rather than through the Azure backend (after processing the reported event)

**Comment by brendandixon** [comment]
@u6006 That would be nice, but the contract with extensions is quite narrow: The agent only receives a return code.
