### ISSUE TITLE
v2.2.11 - cannot raise exception if mkdir() fails for creating extension config dir

### ISSUE THREAD

**Issue by u6006** [Azure/WALinuxAgent#715]
The following code cannot report the issue back with event if extension config dir fails (in azurelinuxagent.ga.exthandler.ExtHandlerInstance.download())

#Create status and config dir
        try:
            status_dir = self.get_status_dir()
            fileutil.mkdir(status_dir, mode=0o700)
            conf_dir = self.get_conf_dir()
            fileutil.mkdir(conf_dir, mode=0o700)
        except IOError as e:
            raise ExtensionError(u"Failed to create status or config dir", e)

Normally, the exception will be captured by "handle_ext_handler()"

        except ExtensionError as e:
            ext_handler_i.set_handler_status(message=ustr(e), code=-1)
            ext_handler_i.report_event(message=ustr(e), is_success=False)

"set_handler_status()" depends on config dir to save extension state and status. So, there's no way to report the issue if config-dir is missing.

Correct me if I missed anything.

**It's not a big deal, but nice to be fixed.**

**Comment by brendandixon** [comment]
@u6006 Unless you are seeing something that I've missed, I do not believe we have an issue. As you note, `ExtHandlerInstance#download` will raise an `ExtensionError` exception if it fails to create either the `status` or `config` directories (extensions require both). That exception is handled, as you also point out, by `ExtHandlersHandler#handle_ext_handler`, which invokes `ExtHandlerInstance#set_handler_state`. However, `ExtHandlerInstance#set_handler_state` will correctly catch and consume the raised `IOError` should the `config` directory be missing (see https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/ga/exthandlers.py#L911).

Is there a failure path I'm missing?

**Comment by u6006** [comment]
@brendandixon I believe you catch the issue. set_handler_status() will fail to write the status to "HandlerStatus" file, and the exception will only be logged but will not be reported when get_handler_status()'s called to send the event out because status file was not there.

    def get_handler_status(self):
        state_dir = self.get_conf_dir()
        status_file = os.path.join(state_dir, "HandlerStatus")
        if not os.path.isfile(status_file):
            return None

**status's not fine**

This is what I mean don't raise exception, instead, just log the issue if mkdir() fails to create extension's config dir.

Let me know if I miss anything there.

**Comment by brendandixon** [comment]
@u6006 The status file is owned and written by the extension; the agent should not create one on its behalf, even in this case. The agent consumes `HandlerStatus` *only* to report status outbound (which eventually appears in the portal and other places). As per the specification and contract the agent has with extensions, it is best to leave the code as-is.
