### ISSUE TITLE
Any way to avoid starting of sshd?

### ISSUE THREAD

**Issue by pavanrangain** [Azure/WALinuxAgent#718]
Is there any configuration in waagent.conf which we can use to avoid ssh being enabled on running waagent service?

**Comment by brendandixon** [comment]
@pavanrangain On many distributions, the SSH daemon is started automatically when the socket is touched. On others, the management of the SSH daemon is controlled via `systemd` (or other init scripts). The agent does not enable the daemon; it will *restart* after installing ssh keys. I suggest you create an image whose configuration matches your needs as a base for VMs.
