### ISSUE TITLE
Allow user managment to be disabled

### ISSUE THREAD

**Issue by menglert2** [Azure/WALinuxAgent#719]
Our use case requires managing users outside of local accounts.  Could we have a configuration option to disable account creation in waagent?  As an example, we currently apply a patch along these lines:

```
common/conf.py
+def get_enable_provision_users(conf=__conf__):
+    return conf.get_switch("ProvisionUsers.Enabled", True)

pa/provision/default.py
-            self.config_user_account(ovfenv)
+            if conf.get_enable_provision_users():
+                self.config_user_account(ovfenv)
```

**Comment by brendandixon** [comment]
@menglert2 While the agent controls provisioning for many distributions, we are moving towards using `cloud-init` (which we use only on Ubuntu at present). As a result, we are avoiding optional changes to agent-driven provisioning.
