### ISSUE TITLE
[2.2.11] WALA deprovision process not clean up all cloudinit  file

### ISSUE THREAD

**Issue by yuhuijiang** [Azure/WALinuxAgent#721]
Hi there,
cloudinit marker file("/var/lib/cloud/sem/config_scripts_per_once.once") not remove during deprovision process
This file is a marker for cloudinit module "scripts-per-once".So if not remove this file during deprovision process,while deploy a new VM use this,during the new VM's provision process, "scripts-per-once" module check the marker file exists,so the module will skip this module's follow code,and run the next module.
So this will cause some issues in some scenarious.

Now,WALA only clean up below folders,
pa/deprovision/default.py(line 102-106)

>  def cloud_init_directories(self):
        return ["/var/lib/cloud/instance",
            "/var/lib/cloud/instances/",
            "/var/lib/cloud/data"]

 

B&R
Yuhui

**Comment by brendandixon** [comment]
@yuhuijiang Thank you. We'll address it in our next release.

**Comment by brendandixon** [comment]
Fixed in #728
