### ISSUE TITLE
Run waagent from a Docker container

### ISSUE THREAD

**Issue by radu-matei** [Azure/WALinuxAgent#723]
Hi!

Is there any plan / blocker on running waagent from a Docker container? I know this was done (at least with the RancherOS project) and I would also like to implement it to the LinuxKit project.

What would be a good starting point for this?

Thanks!

**Comment by brendandixon** [comment]
@radu-matei We have to no plans to block, but have yet to officially ensure or guarantee it works. If you care to contribute... :)

**Comment by radu-matei** [comment]
The question was whether you are aware of anything specifically that is blocking this, and if there are specific plans / roadmap for this.

Thanks!

**Comment by brendandixon** [comment]
@radu-matei There are details that may keep this from working. At the very least, the agent should skip provisioning (likely) and requires access to wireserver (a service that runs on the host from whom it receives information about extensions and so forth).

We have no plans to support, but are not against it either. It's just not our top priority.

**Comment by igorgatis** [comment]
Have you checked https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=walinuxagent&starCount=0?
