### ISSUE TITLE
[2.2.11] Location of configuration file should be editable issue

### ISSUE THREAD

**Issue by yuhuijiang** [Azure/WALinuxAgent#724]
Hi there,
As we know,due to the issue #531 ,so  waagent add a new parameter " -configuration-path:<path to configuration file>".

But because WALA exists 2 daemon process,

> /usr/bin/python -u /usr/sbin/waagent -configuration-path:/root/waagent.conf -daemon

> python -u /usr/sbin/waagent -run-exthandlers

1st one will invoke 2nd one.
For 1st one ,it's configuration file is customized,while 2nd one use default value("/etc/waagent")

file agent.py (line41-55)

> class Agent(object):
    def __init__(self, verbose, conf_file_path=None):
        \#Initialize agent running environment.
        self.osutil = get_osutil()
        \#Init stdout log
        level = logger.LogLevel.VERBOSE if verbose else logger.LogLevel.INFO
        logger.add_logger_appender(logger.AppenderType.STDOUT, level)
        \#Init config
        if conf_file_path is None:
            conf_file_path = self.osutil.get_agent_conf_file_path()
        conf.load_conf_from_file(conf_file_path)

Becaue 2nd daemon process not have "-configuration-path" parameter,so function"def parse_args(sys_args):" in agent.py get the value of "conf_file_path" is None.And then inside class Agent , Agent class will get the default value "conf_file_path = self.osutil.get_agent_conf_file_path()"

**Comment by brendandixon** [comment]
@yuhuijiang Good catch. We'll address this.

**Comment by brendandixon** [comment]
Fixed by #729.
