### ISSUE TITLE
v2.2.11 cannot update status for RDFE VMs

### ISSUE THREAD

**Issue by amitchat** [Azure/WALinuxAgent#727]
Due to the StatusBlobType being unknown for RDFE VMs in Azure, the agent fails to communicated the status and gives the following error:

2017/05/16 04:38:58.102520 WARNING Unknown is an unsupported blob type
2017/05/16 04:38:58.102813 ERROR Event: name=WALinuxAgent, op=ReportStatus, message=Unknown is an unsupported blob type

**Comment by brendandixon** [comment]
Fixed in #728
