### ISSUE TITLE
resource disc fails on FreeBSD 11.1-PRERELEASE

### ISSUE THREAD

**Issue by minusbat** [Azure/WALinuxAgent#734]
Upgraded my test machine to FreeBSD 11.1-PRERELEASE last night and waagent now fails to work with the resource disc. I have upgraded waagent, but get the same result. The traceback is below. It seems to find the pas device correctly, but then there is a python error.

2017/05/25 10:09:00.745944 INFO Activate resource disk
2017/05/25 10:09:00.788944 INFO Resource disk device pass1 found.
2017/05/25 10:09:00.794396 ERROR Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 77, in run
    self.daemon(child_args)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 117, in daemon
    self.resourcedisk_handler.run()
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/resourcedisk/default.py", line 59, in run
    mount_point = self.activate_resource_disk()
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/resourcedisk/default.py", line 68, in activate_resource_disk
    mount_point = self.mount_resource_disk(mount_point)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/resourcedisk/freebsd.py", line 85, in mount_resource_disk
    partition_table_type = disks[device]
KeyError: u'pass1'

**Comment by minusbat** [comment]
The problem appears to be that it is finding 'pass1' as the disc device instaead of 'da1' as it should. Am not usre what has chnaged in FreeBSD to make this stop working though. Have asked on stable@ to see if anyone has any ideas.

**Comment by minusbat** [comment]
A bit more investigation on this and I think I found what the differece is
at least. waagent is using camcontrol periphlist 3:1:0 to find devices,
and this has chnaged from placing the discs before the pass
devices to afterwards. So on an earlier version I get this:

        root@joanna-may:/home/webadmin # camcontrol periphlist 3:1:0
        da1:  generation: 4 index: 1 status: MORE
        pass1:  generation: 4 index: 2 status: LAST

and on the box with the issue it does this:

        root@backup-db:/home/webadmin # camcontrol periphlist 3:1:0
        pass1:  generation: 4 index: 1 status: MORE
        da1:  generation: 4 index: 2 status: LAST

So that box finds 'pass1' as the device when it should be finding 'da1'
which leads to the error. I have a vague memory of seeing a commit for this
go past too.

On the other hand, the oython looks like it shuold handle this, as it
appears to try and detect which devices are disks from the output of
gpart list, which should not let it use pass1 as if it was a disc.

**Comment by minusbat** [comment]
I traced what the python was doing. The basic problem is that device_for_ide_port is now returning 'pass1' instead of 'da1'.  The code above does not check the return from this function to make sure it is a valid disc, unlike the fallback routines below it. The simples solution to make the argent work again is to make the code which calls the function look like this:

        device = self.osutil.device_for_ide_port(1)
        if not device in disks:
            device = None

That will then trigger the fallback properly if it doesn't get a device name which was returned by apart.

This allows waagent to run and mount the resource disc again, but I am going to continue to see if I can fix the original python method too.

**Comment by minusbat** [comment]
Turns out the issue is with the basic 'camcontrol devlist' output, which has changed from this:

       <Msft Virtual Disk 1.0>            at scbus2 target 0 lun 0 (da0,pass0)
       <Msft Virtual Disk 1.0>            at scbus3 target 1 lun 0 (da1,pass1)

to this:

    <Msft Virtual Disk 1.0>            at scbus2 target 0 lun 0 (pass0,da0)
    <Msft Virtual Disk 1.0>            at scbus3 target 1 lun 0 (pass1,da1)

and the code in freebsd/osutil.py uses awk to print the first member of the list.

**Comment by minusbat** [comment]
Have written a fix for this and submitted a pull request.

**Comment by hglkrijger** [comment]
Thanks for reporting and fixing; I have merged.
