### ISSUE TITLE
Agent will not configure network properly on boot time if dhclient package is not installed

### ISSUE THREAD

**Issue by rafalborczuch** [Azure/WALinuxAgent#735]
This may be by design but at least specific diagnostic message in the boot diagnostics on Azure would be helpful in the below conditions.

CentOS 6.9 with dynamic private IP configured in Azure portal and dhclient package removed from the system.
During VM boot `eth0` doesn't get IP address assigned due to missing dhcp client. Linux Agent tries to connect to WireEndpoint but is missing the route:

From Azure boot diagnostics:
```
2017/05/24 00:38:40.277623 INFO Wire server endpoint:168.63.129.16
2017/05/24 00:38:40.306105 INFO Retry [1/1 - IO error: HTTP GET [Errno 101] Network is unreachable]
2017/05/24 00:38:43.309915 INFO WireServer is not responding. Reset endpoint
2017/05/24 00:38:43.310139 INFO Protocol endpoint not found: WireProtocol, [000008] [000009] HTTP GET failed
2017/05/24 00:3:52.313748 INFO Protocol endpoint not found: MetadataProtocol, [000008] [000009] HTTP GET failed
2017/05/24 00:38:52.314013 INFO Retry detect protocols: retry=0
2017/05/24 00:3:02.324465 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/05/24 00:39:02.324735 INFO Test for route to 168.63.129.16
2017/05/24 00:39:02.325139 WARNING No route exists to 168.63.129.16
2017/05/24 00:39:02.325328 INFO Send dhcp request
2017/05/24 00:39:02.892827 INFO Examine /proc/net/route for primary interface
2017/05/24 00:39:02.895678 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/05/24 00:39:02.905231 WARNING Contents of /proc/net/route:
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT                                                       
eth0	0000FEA9	00000000	0001	0	0	1002	0000FFFF	0	0	0
                                                             
2017/05/24 00:39:02.918120 WARNING Primary interface examination will retry silently
```

I understand that this is an edge condition and you need to remove the `dhclient` package first. To be honest, you can ended up without the dhclient package unwittingly
I did `yum update` which failed in the middle due to out of memory problem (I was running A0 size VM). This caused yum to have many duplicate packages as the transaction was not finished. `yum-complete-transaction` was not able to finish the last transaction marking it as broken. Subsequent `yum update` trials were failing due to package conflicts. `package-cleanup --cleandupes` removed quite a lot of packages and my bet is that `dhclient` was one of them.

I suggest to add a check in the Azure Linux Agent for the condition where `eth0` doesn't get dhcp assigned IP at boot and try to set it explicitly from the lease data stored in `/var/lib/dhclient/dhclient-eth0.leases`. This way the Agent should be able to recover network connectivity.
In addition more explicit error message should be printed to boot diagnostics by the Agent that tells the user that dynamic IP configuration is configured for `eth0` but the dhcp client is not available.

**Comment by brendandixon** [comment]
@rafalborczuch Yes, this is very much an "edge condition." The agent, in Azure, *requires* DHCP (which, oddly, is missing from the list in the README). Additionally, the agent does not configuration the network; that is handled by various packages in the distributions. The agent cannot, nor should it, inspect or make assumptions about the network; it is not its job and would likely lead to more false positives than helpful data. Thank you for the question.

**Comment by kailashms** [comment]
Hi have similar case with me,
Centos 6.9 , the vm was stopped as regularly on saturday and sunday
monday when the vm was started, it was not accessible, we could see login prompt everthing is fine.
except the waagent.log
2017/12/11 09:24:48.409157 INFO Azure Linux Agent Version:2.2.14
2017/12/11 09:24:48.411873 INFO OS: centos 6.9
2017/12/11 09:24:48.412608 INFO Python: 2.6.6
2017/12/11 09:24:48.416631 INFO Run daemon
2017/12/11 09:24:48.418592 INFO Activate resource disk
2017/12/11 09:24:48.443251 INFO Examining partition table
2017/12/11 09:24:48.513612 INFO GPT not detected, determining filesystem
2017/12/11 09:24:48.534690 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/11 09:24:48.556336 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/11 09:24:48.556547 INFO The partition is formatted with ntfs, updating partition type to 83
2017/12/11 09:24:48.564476 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/11 09:24:48.607103 INFO sfdisk -c  /dev/sdb 1 83 succeeded
2017/12/11 09:24:48.637212 INFO Format partition [mkfs.ext4 -F /dev/sdb1]
2017/12/11 09:24:52.672898 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/11 09:24:52.746001 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/11 09:24:52.751542 INFO Clean protocol
2017/12/11 09:24:52.857868 INFO Provisioning already completed, skipping.
2017/12/11 09:24:52.857978 INFO RDMA capabilities are not enabled, skipping
2017/12/11 09:24:52.895045 INFO Determined Agent WALinuxAgent-2.2.18 to be the latest agent
2017/12/11 09:24:53.125820 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
2017/12/11 09:24:53.148854 INFO Detect protocol endpoints
2017/12/11 09:24:53.148965 INFO Clean protocol
2017/12/11 09:24:53.149079 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/11 09:24:53.149172 INFO Test for route to 168.63.129.16
2017/12/11 09:24:53.149410 WARNING No route exists to 168.63.129.16
2017/12/11 09:24:53.149507 INFO Checking for dhcp lease cache
2017/12/11 09:24:53.149593 INFO looking for leases in path [/var/lib/dhclient/dhclient-*.leases]
2017/12/11 09:24:53.255337 INFO dhcp entry:168.63.129.16, 245:True, expired:False
2017/12/11 09:24:53.255449 INFO found endpoint [168.63.129.16]
2017/12/11 09:24:53.255570 INFO dhcp entry:168.63.129.16, 245:True, expired:False
2017/12/11 09:24:53.255655 INFO found endpoint [168.63.129.16]
2017/12/11 09:24:53.255787 INFO cached endpoint found [168.63.129.16]
2017/12/11 09:24:53.327792 INFO Cache exists [True]
2017/12/11 09:24:53.327953 INFO Wire server endpoint:168.63.129.16
2017/12/11 09:24:53.358169 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:24:58.363055 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:03.368157 INFO WireServer is not responding. Reset endpoint
2017/12/11 09:25:03.368305 INFO Protocol endpoint not found: WireProtocol, [000008] [Wireserver Exception] [000009] [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:03.368602 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:08.373120 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:13.378178 INFO Protocol endpoint not found: MetadataProtocol, [000008] [000009] [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:13.378318 INFO Retry detect protocols: retry=0
2017/12/11 09:25:23.387929 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/11 09:25:23.423962 INFO Test for route to 168.63.129.16
2017/12/11 09:25:23.475809 WARNING No route exists to 168.63.129.16
2017/12/11 09:25:23.515952 INFO Send dhcp request
2017/12/11 09:25:23.690153 INFO Examine /proc/net/route for primary interface
2017/12/11 09:25:23.735026 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/12/11 09:25:23.764947 WARNING Contents of /proc/net/route:
2017/12/11 09:25:23.779796 WARNING Primary interface examination will retry silently
2017/12/11 09:39:53.803278 INFO Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/12/11 09:39:53.803907 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running

So the vm was rebooted again and the vm was accessible again
latest logs after the reboot

2017/12/11 10:42:46.787304 INFO Agent WALinuxAgent-2.2.14 forwarding signal 15 to WALinuxAgent-2.2.18
2017/12/11 10:44:07.381244 INFO Azure Linux Agent Version:2.2.14
2017/12/11 10:44:07.384151 INFO OS: centos 6.9
2017/12/11 10:44:07.384262 INFO Python: 2.6.6
2017/12/11 10:44:07.384546 INFO Run daemon
2017/12/11 10:44:07.384884 INFO Activate resource disk
2017/12/11 10:44:07.413219 INFO Examining partition table
2017/12/11 10:44:07.514489 INFO GPT not detected, determining filesystem
2017/12/11 10:44:07.533596 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/11 10:44:07.562805 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/11 10:44:07.562971 INFO The partition type is 83
2017/12/11 10:44:07.563195 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/11 10:44:07.700764 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/11 10:44:07.725242 INFO Clean protocol
2017/12/11 10:44:07.760679 INFO Provisioning already completed, skipping.
2017/12/11 10:44:07.760807 INFO RDMA capabilities are not enabled, skipping
2017/12/11 10:44:07.837128 INFO Determined Agent WALinuxAgent-2.2.18 to be the latest agent
2017/12/11 10:44:08.071869 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
2017/12/11 10:44:08.076098 INFO Detect protocol endpoints
2017/12/11 10:44:08.076358 INFO Clean protocol
2017/12/11 10:44:08.076566 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/11 10:44:08.076735 INFO Test for route to 168.63.129.16
2017/12/11 10:44:08.077291 INFO Route to 168.63.129.16 exists
2017/12/11 10:44:08.077457 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:08.098126 INFO Fabric preferred wire protocol version:2015-04-05
2017/12/11 10:44:08.098921 INFO Wire protocol version:2012-11-30
2017/12/11 10:44:08.099081 WARNING Server preferred version:2015-04-05
2017/12/11 10:44:11.951230 INFO Start env monitor service.
2017/12/11 10:44:11.951395 INFO Configure routes
2017/12/11 10:44:11.951487 INFO Gateway:None
2017/12/11 10:44:11.951575 INFO Routes:None
2017/12/11 10:44:11.950206 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 10:44:12.053870 INFO WALinuxAgent-2.2.18 running as process 1728
2017/12/11 10:44:12.054794 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:12.055229 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:12.147714 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:12.191772 INFO Set block dev timeout: sdb with timeout: 300
2017/12/11 10:44:12.195141 INFO Set block dev timeout: sda with timeout: 300
2017/12/11 10:44:12.310696 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=163
2017/12/11 10:59:08.602039 INFO Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/12/11 10:59:08.603978 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/12/11 11:14:14.445493 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 11:44:17.093560 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 12:14:18.680816 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 12:44:19.951018 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 13:14:22.384833 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 13:44:23.795860 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 14:14:25.239115 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 14:44:27.613904 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0

also the logs states that the vm is running with 2.2.14 , but its forwarding signal to 2.2.18
also the errors are gone after the reboot.

we have checked the yum log also we could see the that there was no package removed/installed

is this something to do with the wireserver. waagent was not able to reach the wireserver and it failed.
after the reboot it was able to reach the wireserver?

can you explain why this happened and how we can avoid this is future?

Thanks,

Kailash B

**Comment by nmikuni** [comment]
Add some tips.
I found similar issue and the root cause was kernel version error. If kernel version is such as 2.6.32-671, and using distribution like RHEL or Cent OS 6.9, the issue occurs.
[https://access.redhat.com/solutions/3275261](https://access.redhat.com/solutions/3275261)

You might find kernel output like this.
Mar 14 09:37:52 azusvap01 kernel: : hv_netvsc vmbus-000d3a51-6833-000d-3a51-6833000d3a51: eth0: timeout before we got a set response...
Mar 14 09:37:52 azusvap01 kernel: : hv_netvsc vmbus-000d3a51-6833-000d-3a51-6833000d3a51: eth0: unable to open device (ret -110).

**Comment by boumenot** [comment]
Hopefully, you are no longer seeing this issue.

```text
kernel: : hv_netvsc vmbus-000d3a51-6833-000d-3a51-6833000d3a51: eth0: unable to open device (ret -110)
```

If you are, please update to the latest kernel if your distro.  A fix was made.

**Comment by surajmuthreja** [comment]
I am seeing the similar issue on Ubuntu 14. After reboot the VM, I am not able to ssh into this VM. Got the same error message:

=================================================================
2018/05/23 10:20:49.824774 INFO Agent WALinuxAgent-2.2.25 is running as the goall
 state agent
2018/05/23 10:20:49.944813 INFO Detect protocol endpoints
2018/05/23 10:20:49.945316 INFO Clean protocol
2018/05/23 10:20:49.946398 INFO WireServer endpoint is not found. Rerun dhcp hann
dler
2018/05/23 10:20:49.947801 INFO Test for route to 168.63.129.16
2018/05/23 10:20:49.949442 WARNING No route exists to 168.63.129.16
2018/05/23 10:20:49.950658 INFO Checking for dhcp lease cache
2018/05/23 10:20:49.952108 INFO looking for leases in path [/var/lib/dhcp/dhcliee
nt.*.leases]
2018/05/23 10:20:49.985682 INFO dhcp entry:168.63.129.16, 245:True, expired:Falss
e
2018/05/23 10:20:49.986090 INFO found endpoint [168.63.129.16]
2018/05/23 10:20:49.987629 INFO cached endpoint found [168.63.129.16]
2018/05/23 10:20:49.989024 INFO Cache exists [True]
2018/05/23 10:20:49.990275 INFO Wire server endpoint:168.63.129.16
2018/05/23 10:21:21.037609 INFO WireServer is not responding. Reset endpoint
2018/05/23 10:21:21.039236 INFO Protocol endpoint not found: WireProtocol, [Prott
ocolError] [Wireserver Exception] [HttpError] [HTTP Failed] GET http://168.63.122
9.16/?comp=versions -- IOError [Errno 101] Network is unreachable -- 6 attempts
made
2018/05/23 10:21:52.071287 INFO Protocol endpoint not found: MetadataProtocol, [[
ProtocolError] [HttpError] [HTTP Failed] GET http://169.254.169.254/Microsoft.Coo
mpute/identity?api-version=2015-05-01-preview -- IOError [Errno 101] Network is
unreachable -- 6 attempts made
2018/05/23 10:21:52.072268 INFO Retry detect protocols: retry=0
2018/05/23 10:22:02.083674 INFO WireServer endpoint is not found. Rerun dhcp hann
dler
2018/05/23 10:22:02.085277 INFO Test for route to 168.63.129.16
2018/05/23 10:22:02.087009 WARNING No route exists to 168.63.129.16
2018/05/23 10:22:02.088468 INFO Send dhcp request
2018/05/23 10:22:02.353090 INFO Examine /proc/net/route for primary interface
2018/05/23 10:22:02.355156 WARNING Could not determine primary interface, pleasee
 ensure /proc/net/route is correct
2018/05/23 10:22:02.356631 WARNING Contents of /proc/net/route:
Iface   Destination     Gateway         Flags   RefCnt  Use     Metric  Mask
        MTU     Window  IRTT

eth0    0001020A        00000000        0001    0       0       0       00FFFFFFF
        0       0       0

eth1    0002020A        00000000        0001    0       0       0       00FFFFFFF
        0       0       0


2018/05/23 10:22:02.358716 WARNING Primary interface examination will retry silee
ntly
2018/05/23 10:35:50.281239 INFO Agent WALinuxAgent-2.2.25 launched with command
'python3 -u bin/WALinuxAgent-2.2.25-py2.7.egg -run-exthandlers' is successfully
running
2018/05/23 10:35:50.284582 INFO Event: name=WALinuxAgent, op=Enable, message=Agee
nt WALinuxAgent-2.2.25 launched with command 'python3 -u bin/WALinuxAgent-2.2.255
-py2.7.egg -run-exthandlers' is successfully running, duration=0
==============================================================

Ubuntu Version: 
Linux versa-analytics 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I tried reboot VM, stop and restart VM also but no use.
Please provide the proper resolution for this.

**Comment by jmb1304** [comment]
I am having the same issue with my vm. I left it turned off for a few days and now I cannot ssh into it.
