### ISSUE TITLE
Extension white-list/disable new feature

### ISSUE THREAD

**Issue by eduda** [Azure/WALinuxAgent#736]
It appears right now that there's no way to either disable the agent from installing extensions, for example, ms custom script.  Would it be possible to add a config in waagent.conf to either disable adding them automatically, or a feature to white-list the ones to allow.

**Comment by brendandixon** [comment]
@eduda While we agree it is a useful feature to limit the extensions that can be installed on a VM, the agent, within the Azure model, is not the best place to implement the feature. It should be implemented "upstream" (so, that, among other things, the Azure portal "does the right thing").

That said, we are examining various changes that would influence what extensions may be installed.

**Comment by eduda** [comment]
thanks for the feedback, two followup questions:
1. where does one request this change upstream, is that something you can create?
2. would i be able to get the patch for adding support to disable the extensions you are referring to or any time frame around that?

**Comment by brendandixon** [comment]
@eduda I'll raise the issue with our program managers who track such feature requests. However, there will not be a patch to the agent; all the changes would occur upstream.
