### ISSUE TITLE
Ubuntu 14.04.0-LTS agent outdated

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/WALinuxAgent#738]
So if you create a fresh 14.04.0-LTS VM from the marketplace you cannot do anything with it, as the agent cannot talk to Azure, if you update the agent it works fine, if you use 14.04.5-LTS the VM works fine, so I would suppose either update the image 14.04.0 with the new image or stop offering it?

Thanks!

**Comment by hglkrijger** [comment]
@4c74356b41 Thanks for reporting - Canonical publishes these images and any updates. Also fyi, the naming scheme changed for 16.04 but 14.04 updates are actually made to `14.04.5-LTS`, you might try that one instead.

**Comment by 4c74356b41** [comment]
Well, I know that, but you might discontinue this image or update it, since its pretty unusable as of now
