### ISSUE TITLE
Duplicate logging on RHEL/CentOS

### ISSUE THREAD

**Issue by clangaxon** [Azure/WALinuxAgent#740]
The agent logs to both the log file and stdout/stderr, so logs are duplicated in /var/log/waagent.log and /var/log/messages. This doubles the impact of #711

**Comment by brendandixon** [comment]
@clangaxon Writing to the Console (aka /var/log/messages) is standard Linux practice, as is writing to a separate log file (e.g., /var/log/waagent.log). Admittedly, the agent has (and perhaps does still) emit too many messages. It is best that we address those issues vs. not writing to the standard locations.

**Comment by clangaxon** [comment]
I can't think of many software packages that intentionally log everything twice with no user controls to avoid it.

It'd be nice if you would: a) raise the logging threshold on console, or b) allow it to be disabled in the config, or c) package a systemd config that sent it to /dev/null.

Thanks.

**Comment by brendandixon** [comment]
@clangaxon We'll change the agent to only log warnings and errors to the console (aka /var/log/messages). That should reduce output.

However, having it log to the Console is important for cloud instances since, at times, that is the only data available for diagnostics.

**Comment by clangaxon** [comment]
@brendandixon thanks!

**Comment by brendandixon** [comment]
We should review all messages emitted during GoalState processing and reduce their frequency.

**Comment by brendandixon** [comment]
Addressed by #776
