### ISSUE TITLE
hostname was automatically set to localhost.

### ISSUE THREAD

**Issue by catwarrior** [Azure/WALinuxAgent#742]
I found hostname is not properly set, so I'm trying to set the hostname manually , but it is reset to localhost.

Here is the log - waagent.log

2017/05/31 08:11:42.575076 INFO Azure Linux Agent Version:2.2.6
2017/05/31 08:11:42.576197 INFO OS: suse 12
2017/05/31 08:11:42.577190 INFO Python: 2.7.9
2017/05/31 08:11:42.577716 INFO Run daemon
2017/05/31 08:11:42.578862 INFO Activate resource disk
2017/05/31 08:11:42.595260 INFO Examining partition table
2017/05/31 08:11:42.747908 INFO GPT not detected, determining filesystem
2017/05/31 08:11:42.837844 INFO sfdisk --part-type -f /dev/sdb 1 succeeded
2017/05/31 08:11:42.838254 INFO The partition is formatted with ntfs, updating partition type to 83
2017/05/31 08:11:43.603117 INFO sfdisk --part-type  /dev/sdb 1 83 succeeded
2017/05/31 08:11:43.603805 INFO Format partition [mkfs.ext4 /dev/sdb1 -F]
2017/05/31 08:11:46.603390 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/05/31 08:11:46.669444 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/05/31 08:11:46.675240 INFO Clean protocol
2017/05/31 08:11:46.677689 INFO Running provisioning handler
2017/05/31 08:11:46.680525 INFO Copying ovf-env.xml
2017/05/31 08:11:46.748040 INFO Successfully mounted dvd
2017/05/31 08:11:46.833519 INFO Detect protocol by file
2017/05/31 08:11:46.835606 INFO Clean protocol
2017/05/31 08:11:46.836811 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/05/31 08:11:46.837320 INFO test for route to 168.63.129.16
2017/05/31 08:11:46.838527 INFO route to 168.63.129.16 exists
2017/05/31 08:11:46.839331 INFO Wire server endpoint:168.63.129.16
2017/05/31 08:11:46.846157 INFO Fabric preferred wire protocol version:2015-04-05
2017/05/31 08:11:46.847663 INFO Wire protocol version:2012-11-30
2017/05/31 08:11:46.848304 WARNING Server preferred version:2015-04-05
2017/05/31 08:11:51.938317 INFO Starting provisioning
2017/05/31 08:11:51.938759 INFO Handle ovf-env.xml.
2017/05/31 08:11:51.941652 INFO Set hostname [vmssrvpln000003]
2017/05/31 08:11:51.948955 INFO Publish hostname [vmssrvpln000003]
2017/05/31 08:11:51.962536 INFO examine /proc/net/route for primary interface
2017/05/31 08:11:51.968436 INFO primary interface is [eth0]
2017/05/31 08:11:51.971195 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 08:11:51.975641 INFO interface [lo] skipped
2017/05/31 08:11:51.980471 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 08:11:51.985381 INFO interface [eth0] selected
2017/05/31 08:12:09.133527 INFO Create user account if not exists
2017/05/31 08:12:09.771863 INFO Set user password.
2017/05/31 08:12:09.973406 INFO Configure sudoer
2017/05/31 08:12:09.992335 INFO Configure sshd
2017/05/31 08:12:09.995803 INFO Enabled SSH password-based authentication methods.
2017/05/31 08:12:09.999416 INFO Configured SSH client probing to keep connections alive.
2017/05/31 08:12:10.822038 INFO Event: name=WALA, op=Provision, message=Provision succeed
2017/05/31 08:12:12.453920 INFO Provisioning complete
2017/05/31 08:12:12.455008 INFO RDMA capabilities are not enabled, skipping
2017/05/31 08:12:12.455548 INFO Installed Agent WALinuxAgent-2.2.6 is the most current agent
2017/05/31 08:12:12.461147 INFO Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers'
2017/05/31 08:12:12.619079 INFO Agent WALinuxAgent-2.2.6 is running as the goal state agent
2017/05/31 08:12:12.647527 INFO Wire server endpoint:168.63.129.16
2017/05/31 08:12:12.662359 INFO Start env monitor service.
2017/05/31 08:12:12.662680 INFO Event: name=WALinuxAgent-2.2.6, op=HeartBeat, message=
2017/05/31 08:12:12.668223 INFO Configure routes
2017/05/31 08:12:12.671123 INFO Gateway:None
2017/05/31 08:12:12.675389 INFO Routes:None
2017/05/31 08:12:12.691066 WARNING Move rules file 75-persistent-net-generator.rules to /var/lib/waagent/75-persistent-net-generator.rules
2017/05/31 08:12:12.691585 INFO WALinuxAgent-2.2.6 running as process 13676
2017/05/31 08:12:12.692199 WARNING Move rules file 70-persistent-net.rules to /var/lib/waagent/70-persistent-net.rules
2017/05/31 08:12:12.694766 INFO Wire server endpoint:168.63.129.16
2017/05/31 08:12:12.695259 INFO EnvMonitor: Detected hostname change: vmssrvpln000003 -> localhost
2017/05/31 08:12:12.716797 INFO examine /proc/net/route for primary interface
2017/05/31 08:12:12.720645 INFO primary interface is [eth0]
2017/05/31 08:12:12.723518 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 08:12:12.728306 INFO interface [lo] skipped
2017/05/31 08:12:12.730641 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 08:12:12.733914 INFO interface [eth0] selected
2017/05/31 08:12:12.801922 INFO Event: name=WALinuxAgent, op=HealthCheck, message=Blob type match [BlockBlob]
2017/05/31 08:12:40.903629 INFO Event: name=WALinuxAgent, op=HealthCheck, message=Blob type match [BlockBlob]
2017/05/31 08:14:30.288448 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Expected handler state: enabled
2017/05/31 08:14:30.294278 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Current handler state is: NotInstalled
2017/05/31 08:14:30.295521 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Download extension package
2017/05/31 08:14:30.485585 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Unpack extension package
2017/05/31 08:14:30.623298 INFO Event: name=Microsoft.Azure.Extensions.customScript, op=Download, message=Download succeeded
2017/05/31 08:14:30.624205 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Initialize extension directory
2017/05/31 08:14:30.625760 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Update settings file: 0.settings
2017/05/31 08:14:30.626971 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Install extension.
2017/05/31 08:14:30.629079 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Launch command:bin/custom-script-shim install
2017/05/31 08:14:31.635501 INFO Event: name=Microsoft.Azure.Extensions.customScript, op=Install, message=Launch command succeeded: bin/custom-script-shim install
2017/05/31 08:14:31.637862 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Enable extension.
2017/05/31 08:14:31.639151 INFO [Microsoft.Azure.Extensions.customScript-2.0.2] Launch command:bin/custom-script-shim enable
2017/05/31 08:14:32.648450 INFO Event: name=Microsoft.Azure.Extensions.customScript, op=Enable, message=Launch command succeeded: bin/custom-script-shim enable
2017/05/31 08:14:32.706057 INFO Event: name=WALinuxAgent, op=HealthCheck, message=Blob type match [BlockBlob]
2017/05/31 08:14:40.064696 INFO EnvMonitor: Detected hostname change: localhost -> vm2577142731
2017/05/31 08:14:40.076350 INFO examine /proc/net/route for primary interface
2017/05/31 08:14:40.078078 INFO primary interface is [eth0]
2017/05/31 08:14:40.079083 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 08:14:40.079614 INFO interface [lo] skipped
2017/05/31 08:14:40.080816 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 08:14:40.089727 INFO interface [eth0] selected
2017/05/31 08:15:02.652572 INFO EnvMonitor: Detected hostname change: vm2577142731 -> localhost
2017/05/31 08:15:02.664678 INFO examine /proc/net/route for primary interface
2017/05/31 08:15:02.668683 INFO primary interface is [eth0]
2017/05/31 08:15:02.672546 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 08:15:02.676432 INFO interface [lo] skipped
2017/05/31 08:15:02.679040 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 08:15:02.682832 INFO interface [eth0] selected
2017/05/31 08:27:13.099929 INFO Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/05/31 08:27:13.100887 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.6 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/05/31 08:42:14.742478 INFO Event: name=WALinuxAgent-2.2.6, op=HeartBeat, message=
2017/05/31 09:12:15.987447 INFO Event: name=WALinuxAgent-2.2.6, op=HeartBeat, message=
2017/05/31 09:23:08.730821 INFO EnvMonitor: Detected hostname change: localhost -> Linuxidc
2017/05/31 09:23:08.744743 INFO examine /proc/net/route for primary interface
2017/05/31 09:23:08.745606 INFO primary interface is [eth0]
2017/05/31 09:23:08.747206 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 09:23:08.748268 INFO interface [lo] skipped
2017/05/31 09:23:08.749903 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 09:23:08.751634 INFO interface [eth0] selected
2017/05/31 09:23:31.015095 INFO EnvMonitor: Detected hostname change: Linuxidc -> localhost
2017/05/31 09:23:31.031501 INFO examine /proc/net/route for primary interface
2017/05/31 09:23:31.035744 INFO primary interface is [eth0]
2017/05/31 09:23:31.038327 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 09:23:31.042630 INFO interface [lo] skipped
2017/05/31 09:23:31.045618 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 09:23:31.049329 INFO interface [eth0] selected
2017/05/31 09:28:02.733288 INFO EnvMonitor: Detected hostname change: localhost -> Linuxidc
2017/05/31 09:28:02.745326 INFO examine /proc/net/route for primary interface
2017/05/31 09:28:02.747490 INFO primary interface is [eth0]
2017/05/31 09:28:02.749734 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 09:28:02.751063 INFO interface [lo] skipped
2017/05/31 09:28:02.752815 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 09:28:02.754360 INFO interface [eth0] selected
2017/05/31 09:28:24.861318 INFO EnvMonitor: Detected hostname change: Linuxidc -> localhost
2017/05/31 09:28:24.875729 INFO examine /proc/net/route for primary interface
2017/05/31 09:28:24.879437 INFO primary interface is [eth0]
2017/05/31 09:28:24.882140 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 09:28:24.886187 INFO interface [lo] skipped
2017/05/31 09:28:24.888911 INFO interface [eth0] has flags [4163], is loopback [False]
2017/05/31 09:28:24.892507 INFO interface [eth0] selected
2017/05/31 09:34:27.294311 INFO EnvMonitor: Detected hostname change: localhost -> x1234
2017/05/31 09:34:27.311660 INFO examine /proc/net/route for primary interface
2017/05/31 09:34:27.315545 INFO primary interface is [eth0]
2017/05/31 09:34:27.318874 INFO interface [lo] has flags [73], is loopback [True]
2017/05/31 09:34:27.322102 INFO interface [lo] skipped
2017/05/31 09:34:27.324458 INFO interface [eth0] has flags [4163], is loopback [
2017/05/31 09:34:27.327874 INFO interface [eth0] selected
2017/05/31 09:34:50.085465 INFO EnvMonitor: Detected hostname change: x1234 -> l
2017/05/31 09:34:50.097630 INFO examine /proc/net/route for primary interface
2017/05/31 09:34:50.098468 INFO primary interface is [eth0]
2017/05/31 09:34:50.099870 INFO interface [lo] has flags [73], is loopback [True
2017/05/31 09:34:50.100874 INFO interface [lo] skipped
2017/05/31 09:34:50.102645 INFO interface [eth0] has flags [4163], is loopback [
2017/05/31 09:34:50.106415 INFO interface [eth0] selected
2017/05/31 09:35:11.626680 INFO EnvMonitor: Detected hostname change: localhost
2017/05/31 09:35:11.639125 INFO examine /proc/net/route for primary interface
2017/05/31 09:35:11.640461 INFO primary interface is [eth0]
2017/05/31 09:35:11.642022 INFO interface [lo] has flags [73], is loopback [True
2017/05/31 09:35:11.642960 INFO interface [lo] skipped
2017/05/31 09:35:11.644110 INFO interface [eth0] has flags [4163], is loopback [
2017/05/31 09:35:11.645143 INFO interface [eth0] selected
2017/05/31 09:35:33.123275 INFO EnvMonitor: Detected hostname change: x1234 -> l
2017/05/31 09:35:33.139131 INFO examine /proc/net/route for primary interface
2017/05/31 09:35:33.143603 INFO primary interface is [eth0]
2017/05/31 09:35:33.146990 INFO interface [lo] has flags [73], is loopback [True
2017/05/31 09:35:33.150936 INFO interface [lo] skipped
2017/05/31 09:35:33.153880 INFO interface [eth0] has flags [4163], is loopback [
2017/05/31 09:35:33.158132 INFO interface [eth0] selected

**Comment by catwarrior** [comment]
Interesting it works on Canonical:UbuntuServer:16.04-LTS:16.04.201705160 (image from azure)
but not SUSE:SLES:12-SP2:2017.03.20(image from azure), actually I have tried other SLES:12-SP2, also doesn't work.

**Comment by brendandixon** [comment]
@catwarrior The agent first sets and saves (in `/var/lib/waagent/published_hostname`) the hostname during VM provisioning. These two lines from the beginning of the log show the name used at that time:

```
2017/05/31 08:11:51.941652 INFO Set hostname [vmssrvpln000003]
2017/05/31 08:11:51.948955 INFO Publish hostname [vmssrvpln000003]
```

The agent then monitors for hostname changes by periodically invoking `socket.gethostname` (a standard Python library call). If the string returned differs from that it has cached, it emits messages similar to:

```
2017/05/31 08:12:12.695259 INFO EnvMonitor: Detected hostname change: vmssrvpln000003 -> localhost
```
The first value (in this case, `vmssrvpln000003`) is the cached name and the second value (here it is `localhost`) is that *returned* by the `socket.gethostname` call.

I do not know how you are setting the hostname. If you are only updating the `/etc/hostname` file, that is likely insufficient. You should also use the `hostname` command.

If you can document a case where the agent is publishing a hostname that differs from that returned by the `hostname` command, please re-open this issue. We'll likely need logs and the commands by which you changed the hostname (so we can recreate the issue).

**Comment by jakehoms** [comment]
Did any further info arise from this issue? I am having exactly the same issue with a SLES 12 for SAP SP3 image. Please let me know if I should open a new ticket or if this comment will re-open it. 

Few extra details: We do this process for our RHEL/CentOS/OEL images just fine, but our Suse images do not work and re-set the hostname to localhost, even after setting it correctly earlier in boot. I am creating the image using the GUI of Azure and cloud-init is not being used (as it's not supported in Suse). This is solely using WALinuxAgent. Please let me know if you need more info. Thanks. 

This is the link to my waagent.log in verbose mode (the first portion which covers the hostname changes). 

https://pastebin.com/pDaRFuGv
Lines 66-68: Set hostname as chosen from the Azure GUI (desired state)
Lines 343-344: Recognize and set hostname to localhost  (not the desired state)
