### ISSUE TITLE
[2.2.12] VM cannot become running if Provisioning.Enabled=n and Provisioning.UseCloudInit=n

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#756]
Hi,

When Provisioning.Enabled=n and Provisioning.UseCloudInit=n, the VM cannot become running status. (The same as #411)
I wonder if we support the scenario that customer use neither WALA nor cloud-init to provision there VM. If we support this, I think we'd better report ready status as before.

Best regards,
Yuxin Sun

**Comment by brendandixon** [comment]
@yuxisun1217 Thank you for the report. Disabling both agent provisioning and cloud-init is a user / configuration error.

**Comment by jayden-at-arista** [comment]
@brendandixon We require provisioning/cloud-init disabled for our Azure appliance, and our test VMs are no longer showing 'running' due to this recent change. Can you send me your email address so we can start a private thread about this issue, or if you can send me an email at jayden at arista dot com that would be great?

**Comment by brendandixon** [comment]
@jayden-at-arista While we do not have scripted support for this, you can make it work. You'll need to create a file named `provisioned` in the `/var/lib/waagent directory`. The file should contain the VM unique identifier. Azure writes the identifier to `/sys/class/dmi/id/product_uuid`. In the odd case that file is not present, you can also obtain using the command `dmidecode --string system-uuid`.

**Comment by brendandixon** [comment]
Consider adding an option to mark an image as provisioned.

**Comment by jayden-at-arista** [comment]
@brendandixon Thank you for this information. This workaround should be sufficient for our needs.

**Comment by jayden-at-arista** [comment]
@brendandixon I've tried the command `cp /sys/class/dmi/id/product_uuid /var/lib/waagent/provisioned` but the status still says creating. I'm using the classic deployment model currently.

Checking in on a resource deployed model with an older version of the waagent I see that the file /var/lib/waagent/provisioned exists but is empty. Is the product UUID inside of provisioned file fairly new? Any suggestions for debugging why creating the provisioned file isn't changing the status on the instance with the new version of Waagent?

**Comment by brendandixon** [comment]
@jayden-at-arista The provisioning code sends an event (see https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/pa/provision/default.py#L91) that conveys to the Azure fabric the VM state.

Now that I think more deeply on the request, it may be difficult and dangerous to skip provisioning altogether. The problem is that per-VM state will not be properly set. The Azure model for re-using a VM image is to "de-provision" it (e.g., `waagent --deprovision`) and then use the VHD as the basis for a new VM. Provisioning continues to run in that case and should allow you to use your hardened image.

**Comment by jayden-at-arista** [comment]
@brendandixon We are using our own provisioning agent that attaches the provisioning drive, parses the xml, and sets up the appliance, all before the Waagent is started. How can we communicate that we do not want the Waagent to perform any provisioning but to mark status as provisioned? 

If there is currently no way to do this, I would like to work on a change that does the following:
if provisioning is disabled but the provisioned file was written to with UUID (i.e. is_provisioned() is true), then we send the provisioned status event.

**Comment by jayden-at-arista** [comment]
It seems that after 30 minutes the VM now is marked as running, implying that the provisioned file is checked periodically (is this the heartbeat? The 30 minute interval would seem to align with that) and we missed the first check. Adding provisioned file before Waagent is started should fix this, so I will test that now and hopefully it will work.

**Comment by jayden-at-arista** [comment]
I tested adding the `/var/lib/waagent/provisioned` file before starting Waagent and the status still isn't being marked as running. I have no idea why that instance mentioned in my last comment had its status changed to running.

I will work on a fix and issue a pull request.

**Comment by yuxisun1217** [comment]
Hi @brendandixon ,

Thank you for your response. 
If we confirm that the customers must use one of the WALA or cloud-init to provision the VM, do you think it'll be better to use only one switch in waagent.conf but not two? I think it is a little confused to have two switches to control the provisioning action. (But if we use only 1 switch, the 3rd-part provision agent will be forbidden. Maybe we can consider more about how to make it more clearly.)

**Comment by brendandixon** [comment]
@yuxisun1217 I agree that it would be less confusing. But changing the switches now might impact running instances (e.g., when someone installs an update, their configuration may not be correct). I felt it best to make the additive change.

**Comment by yuxisun1217** [comment]
OK. Thank you very much @brendandixon !
