### ISSUE TITLE
WALA fails if both eth0 and bond0 have IP address

### ISSUE THREAD

**Issue by haiyangz** [Azure/WALinuxAgent#758]
In SRIOV support, we bond eth0 (synthetic nic) and vf1 (VF nic) together into bond0.

If eth0 is configured by cloudinit later, both eth0 and bond0 have IP address. But eth0 doesn't have datapath , only bond0 is functional. In this case, network is still connected, we can ssh into the VM successfully.

But WALA fails. Seems it cannot automatically retry the other interface if one interface is in /proc/net/route, but not functional.

Here are the /proc/net/route:
Iface   Destination     Gateway         Flags   RefCnt  Use     Metric  Mask            MTU     Window  IRTT                                                      
bond0   00000000        0100000A        0003    0       0       0       00000000        0       0       0
bond0   0000000A        00000000        0001    0       0       0       00FFFFFF        0       0       0
eth0    0000000A        00000000        0001    0       0       0       00FFFFFF        0       0       0
bond0   10813FA8        0100000A        0007    0       0       0       FFFFFFFF        0       0       0
bond0   FEA9FEA9        0100000A        0007    0       0       0       FFFFFFFF        0       0       0

log from WALA (collected by Simon):
2017/06/07 08:11:15.144278 INFO Azure Linux Agent Version:2.2.9
... …
2017/06/07 08:11:21.783697 INFO Protocol endpoint not found: MetadataProtocol, (000008)(000009)HTTP GET failed
2017/06/07 08:11:21.784097 INFO Retry detect protocols: retry=0
2017/06/07 08:11:31.794848 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/06/07 08:11:31.795305 INFO Test for route to 168.63.129.16
2017/06/07 08:11:31.795553 WARNING No route exists to 168.63.129.16
2017/06/07 08:11:31.795690 INFO Send dhcp request
2017/06/07 08:11:31.856155 INFO Examine /proc/net/route for primary interface
2017/06/07 08:11:31.856624 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/06/07 08:11:31.857362 WARNING Contents of /proc/net/route:
Iface      Destination         Gateway              Flags      RefCnt  Use        Metric   Mask                     MTU      Window               IRTT                                                       
bond0   0000000A             00000000             0001       0              0              0              00FFFFFF             0              0              0 
2017/06/07 08:11:31.858213 WARNING Primary interface examination will retry silently

**Comment by simonxiaoss** [comment]
Here is another log:

[    9.874765] cloud-init[1341]: + i=eth0
[    9.880936] cloud-init[1341]: + x=0
[    9.886712] cloud-init[1341]: + ifdown eth0
[    9.919081] cloud-init[1341]: + ifup eth0
[    9.946480] cloud-init[1341]: + exit 0
[[0;32m  OK  [0m] Started Azure Linux Agent.
[   10.147734] cloud-init[1341]: Cloud-init v. 0.7.9 running 'init' at Mon, 12 Jun 2017 19:13:30 +0000. Up 9.58 seconds.
[   10.155390] cloud-init[1341]: ci-info: ++++++++++++++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++++++++++++
[   10.163487] cloud-init[1341]: ci-info: +--------+------+-----------------------------+---------------+-------+-------------------+
[   10.170435] cloud-init[1341]: ci-info: | Device |  Up  |           Address           |      Mask     | Scope |     Hw-Address    |
[   10.177595] cloud-init[1341]: ci-info: +--------+------+-----------------------------+---------------+-------+-------------------+
[   10.187284] cloud-init[1341]: ci-info: |  vf1   | True |              .              |       .       |   .   | 00:0d:3a:f9:5d:ac |
[   10.194329] cloud-init[1341]: ci-info: |   lo   | True |          127.0.0.1          |   255.0.0.0   |   .   |         .         |
[   10.201873] cloud-init[1341]: ci-info: |   lo   | True |           ::1/128           |       .       |  host |         .         |
[   10.209456] cloud-init[1341]: ci-info: | bond0  | True |           10.0.0.5          | 255.255.255.0 |   .   | 00:0d:3a:f9:5d:ac |
[   10.217221] cloud-init[1341]: ci-info: | bond0  | True | fe80::20d:3aff:fef9:5dac/64 |       .       |  link | 00:0d:3a:f9:5d:ac |
[   10.224139] cloud-init[1341]: ci-info: |  eth0  | True |           10.0.0.5          | 255.255.255.0 |   .   | 00:0d:3a:f9:5d:ac |
[   10.231881] cloud-init[1341]: ci-info: |  eth0  | True | fe80::20d:3aff:fef9:5dac/64 |       .       |  link | 00:0d:3a:f9:5d:ac |
[   10.239633] cloud-init[1341]: ci-info: +--------+------+-----------------------------+---------------+-------+-------------------+
[   10.246791] cloud-init[1341]: ci-info: ++++++++++++++++++++++++++++++Route IPv4 info+++++++++++++++++++++++++++++++
[   10.253908] cloud-init[1341]: ci-info: +-------+-----------------+----------+-----------------+-----------+-------+
[   10.260563] cloud-init[1341]: ci-info: | Route |   Destination   | Gateway  |     Genmask     | Interface | Flags |
[   10.267346] cloud-init[1341]: ci-info: +-------+-----------------+----------+-----------------+-----------+-------+
[   10.274287] cloud-init[1341]: ci-info: |   0   |     0.0.0.0     | 10.0.0.1 |     0.0.0.0     |    eth0   |   UG  |
[   10.281475] cloud-init[1341]: ci-info: |   1   |     10.0.0.0    | 0.0.0.0  |  255.255.255.0  |    eth0   |   U   |
[   10.288118] cloud-init[1341]: ci-info: |   2   |     10.0.0.0    | 0.0.0.0  |  255.255.255.0  |   bond0   |   U   |
[   10.294820] cloud-init[1341]: ci-info: |   3   |  168.63.129.16  | 10.0.0.1 | 255.255.255.255 |    eth0   |  UGH  |
[   10.302697] cloud-init[1341]: ci-info: |   4   | 169.254.169.254 | 10.0.0.1 | 255.255.255.255 |    eth0   |  UGH  |
[   10.309928] cloud-init[1341]: ci-info: +-------+-----------------+----------+-----------------+-----------+-------+
[   10.318314] cloud-init[1341]: 2017-06-12 19:13:30,731 - stages.py[WARNING]: Failed to rename devices: duplicate mac found! both 'eth0' and 'vf1' have mac '00:0d:3a:f9:5d:ac'
2017/06/12 19:13:30.948421 INFO Azure Linux Agent Version:2.2.9
2017/06/12 19:13:30.954899 INFO OS: ubuntu 16.04
2017/06/12 19:13:30.960524 INFO Python: 3.5.2

... ...

Ubuntu 16.04.2 LTS asixiao-v2-2-3 ttyS0

asixiao-v2-2-3 login: 2017/06/12 19:13:47.162955 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/06/12 19:13:47.168540 INFO Test for route to 168.63.129.16
2017/06/12 19:13:47.169518 WARNING No route exists to 168.63.129.16
2017/06/12 19:13:47.170182 INFO Send dhcp request
2017/06/12 19:13:47.206185 INFO Examine /proc/net/route for primary interface
2017/06/12 19:13:47.207155 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/06/12 19:13:47.207725 WARNING Contents of /proc/net/route:
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT                                                       
bond0	0000000A	00000000	0001	0	0	0	00FFFFFF	0	0	0                                                                              
eth0	0000000A	00000000	0001	0	0	0	00FFFFFF	0	0	0                                                                               

2017/06/12 19:13:47.209077 WARNING Primary interface examination will retry silently

**Comment by simonxiaoss** [comment]
Another boot up log which contains some error from WALA:

2017/06/12 22:02:30.244643 INFO Protocol endpoint not found: MetadataProtocol, [000008] [000009] HTTP GET failed
2017/06/12 22:02:30.245006 INFO Retry detect protocols: retry=12
2017/06/12 22:02:40.257126 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/06/12 22:02:40.257850 INFO Test for route to 168.63.xx.xx
2017/06/12 22:02:40.258351 INFO Route to 168.63.xx.xxexists
2017/06/12 22:02:40.259260 INFO Wire server endpoint:168.63.xx.xx
2017/06/12 22:02:46.270355 INFO WireServer is not responding. Reset endpoint
2017/06/12 22:02:46.271033 INFO Protocol endpoint not found: WireProtocol, [000008] [000009] HTTP GET failed

**Comment by iamshital** [comment]
another boot logs with same error (WALA 2.2.10) on RHEL7.3

```
localhost login: 2017/06/14 09:08:39.583380 INFO Azure Linux Agent Version:2.2.10
2017/06/14 09:08:39.583853 INFO OS: redhat 7.3
2017/06/14 09:08:39.583953 INFO Python: 2.7.5
2017/06/14 09:08:39.584114 INFO Run daemon
2017/06/14 09:08:39.584319 INFO No RDMA handler exists for distro='Red Hat Enterprise Linux Server' version='7.3'
2017/06/14 09:08:39.585450 INFO Activate resource disk
2017/06/14 09:08:39.609367 INFO Examining partition table
2017/06/14 09:08:39.728833 INFO GPT not detected, determining filesystem
[   41.861234]  sdb: sdb1
2017/06/14 09:08:39.732277 INFO sfdisk with --part-type failed [1], retrying with -c
2017/06/14 09:08:39.736915 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/06/14 09:08:39.737182 INFO The partition is formatted with ntfs, updating partition type to 83
2017/06/14 09:08:39.740215 INFO sfdisk with --part-type failed [1], retrying with -c
2017/06/14 09:08:39.745685 INFO sfdisk -c  /dev/sdb 1 83 succeeded
[   41.877732]  sdb: sdb1
[   41.880357]  sdb: sdb1
2017/06/14 09:08:39.752885 INFO Format partition [mkfs.ext4 /dev/sdb1 -F]
2017/06/14 09:08:42.916307 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
[   45.085434] EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: (null)
2017/06/14 09:08:42.960073 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/06/14 09:08:42.963060 INFO Enable swap
2017/06/14 09:08:42.983428 INFO Create swap file
[   45.195104] Adding 2097148k swap on /mnt/resource/swapfile.  Priority:-1 extents:6 across:2260988k FS
2017/06/14 09:08:43.071260 INFO Enabled 2097152KB of swap at /mnt/resource/swapfile
2017/06/14 09:08:43.071469 INFO Clean protocol
2017/06/14 09:08:43.071990 INFO Running default provisioning handler
2017/06/14 09:08:43.077992 INFO Copying ovf-env.xml
2017/06/14 09:08:43.163028 INFO Successfully mounted dvd
2017/06/14 09:08:43.257644 INFO Detect protocol by file
2017/06/14 09:08:43.258591 INFO Clean protocol
2017/06/14 09:08:43.258718 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/06/14 09:08:43.258825 INFO Test for route to 168.63.xxx.xxx
2017/06/14 09:08:43.258976 WARNING No route exists to 168.63.xxx.xxx
2017/06/14 09:08:43.259751 INFO Checking for dhcp lease cache
2017/06/14 09:08:43.260533 INFO looking for leases in path [/var/lib/dhclient/dhclient-*.lease]
2017/06/14 09:08:43.261269 INFO cached endpoint not found
2017/06/14 09:08:43.261723 INFO looking for leases in path [/var/lib/NetworkManager/dhclient-*.lease]
2017/06/14 09:08:43.262574 INFO cached endpoint not found
2017/06/14 09:08:43.262935 INFO Cache exists [False]
2017/06/14 09:08:43.263717 INFO Send dhcp request
2017/06/14 09:08:43.338731 INFO Examine /proc/net/route for primary interface
2017/06/14 09:08:43.339034 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/06/14 09:08:43.339457 WARNING Contents of /proc/net/route:
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT                                                       

2017/06/14 09:08:43.339943 WARNING Primary interface examination will retry silently
```

**Comment by hglkrijger** [comment]
@haiyangz, I added a test (#831) for the valid routing table listed in the first comment above, which shows the agent will process that as expected. The other routing tables actually found by the agent in the log afterwards are not valid, which means the agent seems to be behaving as expected. 

Valid:
```
Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT
bond0 00000000 0100000A 0003 0 0 0 00000000 0 0 0
bond0 0000000A 00000000 0001 0 0 0 00FFFFFF 0 0 0
eth0 0000000A 00000000 0001 0 0 0 00FFFFFF 0 0 0
bond0 10813FA8 0100000A 0007 0 0 0 FFFFFFFF 0 0 0
bond0 FEA9FEA9 0100000A 0007 0 0 0 FFFFFFFF 0 0 0
```

Invalid:
```
Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT
bond0 0000000A 00000000 0001 0 0 0 00FFFFFF 0 0 0
```

Invalid:
```
Iface	Destination	Gateway Flags	RefCnt	Use	Metric	Mask	MTU	Window	IRTT
bond0	0000000A	00000000	0001	0	0	0	00FFFFFF	0	0	0
eth0	0000000A	00000000	0001	0	0	0	00FFFFFF	0	0	0
```
