### ISSUE TITLE
Since upgrade waagent is constantly using 1-2% CPU

### ISSUE THREAD

**Issue by RobDonovan** [Azure/WALinuxAgent#759]
I've had my Ubuntu VM running for many years with very little CPU being used when 'idle'.

Yesterday I upgraded Ubuntu (and therefor waagent, was on 2.0.14 before), and now I'm getting a continuous load of about 1-2% from the process: python3 -u /usr/sbin/waagent -run-exthandlers

(Looking from my sar logs before I updated, this wasn't running like this before)

I know 1-2% isn't much, but I run a tight machine, and don't like leaky process that continuously steal CPU. Normally it suggests a problem or bad scripts.

I've noticed that I'm getting continual events in /var/lib/waagent/events/ for ProcessGoalState (that match the logs below)

Not really sure why it keeps running this over and over and how to stop it, and if its some kind of problem that has happened since I upgraded.

If I enable verbose logging I get this every 3 seconds:
2017/06/11 09:54:31.885430 VERBOSE Get extension handler config
2017/06/11 09:54:31.893684 VERBOSE HTTP connection [GET] [/machine/?comp=goalstate] [None] [{'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent'}]
2017/06/11 09:54:31.913495 VERBOSE HTTP response status: [200]
2017/06/11 09:54:31.920503 VERBOSE Load GoalState.xml
2017/06/11 09:54:31.934841 VERBOSE Handle extensions updates for incarnation 6
2017/06/11 09:54:31.942976 VERBOSE [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Decide which version to use
2017/06/11 09:54:31.954069 VERBOSE Get extension handler package
2017/06/11 09:54:31.960473 VERBOSE Fetch manifest
2017/06/11 09:54:31.965515 VERBOSE Fetch [http://<removed by me for security/Microsoft.OSTCExtensions_VMAccessForLinux_ussouth_manifest.xml] with headers [None]
2017/06/11 09:54:31.984336 VERBOSE HTTP connection [GET] [/removed by me for security/Microsoft.OSTCExtensions_VMAccessForLinux_ussouth_manifest.xml] [None] [None]
2017/06/11 09:54:32.010703 VERBOSE HTTP response status: [200]
2017/06/11 09:54:32.016915 VERBOSE Load ExtensionManifest.xml
2017/06/11 09:54:32.032190 VERBOSE [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Use version: 1.4.6.0
2017/06/11 09:54:32.041749 VERBOSE [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Collect extension status
2017/06/11 09:54:32.051706 VERBOSE Report vm agent status
2017/06/11 09:54:32.056940 VERBOSE Prepare status blob
2017/06/11 09:54:32.062024 VERBOSE Put block blob
2017/06/11 09:54:32.067085 VERBOSE HTTP connection [PUT] [/vhds/fireflux5.fireflux5.fireflux5.status?sr=b&sp=rw&se=9999-01-01&sk=key1&sv=2014-02-14&sig=removed by me for security] [{"timestampUTC": "2017-06-11T09:54:32Z", "aggregateStatus": {"guestAgentStatus": {"hostname": "fireflux5", "status": "Ready", "version": "2.2.12", "formattedMessage": {"message": "Guest Agent is running", "lang": "en-US"}, "osname": "ubuntu", "osversion": "14.04"}, "handlerAggregateStatus": [{"handlerVersion": "1.4.6.0", "status": "Ready", "runtimeSettingsStatus": {"sequenceNumber": 0, "settingsStatus": {"status": {"name": "Microsoft.OSTCExtensions.VMAccessForLinux", "configurationAppliedTime": null, "code": "0", "operation": "Install", "formattedMessage": {"message": "Install Succeeded", "lang": "en-US"}, "status": "success"}, "timestampUTC": "2017-06-11T09:54:32Z", "version": 1.0}}, "handlerName": "Microsoft.OSTCExtensions.VMAccessForLinux", "formattedMessage": {"message": "Plugin enabled", "lang": "en-US"}, "code": 0}]}, "version": "1.1"}] [{'Content-Length': '853', 'x-ms-date': '2017-06-11T09:54:32Z', 'x-ms-version': '2014-02-14', 'x-ms-blob-type': 'BlockBlob'}]
2017/06/11 09:54:32.197174 VERBOSE HTTP response status: [201]
2017/06/11 09:54:32.203008 VERBOSE Completed vm agent status report
2017/06/11 09:54:32.209887 VERBOSE Instantiating Agent WALinuxAgent-2.2.10 from disk
2017/06/11 09:54:32.224733 VERBOSE Agent WALinuxAgent-2.2.10 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/11 09:54:32.234865 VERBOSE Ensuring Agent WALinuxAgent-2.2.10 is downloaded
2017/06/11 09:54:32.241861 VERBOSE Agent WALinuxAgent-2.2.10 was previously downloaded - skipping download
2017/06/11 09:54:32.251010 VERBOSE Agent WALinuxAgent-2.2.10 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.10/HandlerManifest.json
2017/06/11 09:54:32.262227 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.10 HandlerManifest.json: {'name': 'WALinuxAgent', 'handlerManifest': {'enableCommand': 'python -u bin/WALinuxAgent-2.2.10-py2.7.egg -run-exthandlers', 'installCommand': '', 'disableCommand': '', 'uninstallCommand': '', 'updateCommand': '', 'rebootAfterInstall': False, 'reportHeartbeat': False}, 'version': 1.0}
2017/06/11 09:54:32.292927 VERBOSE Instantiating Agent WALinuxAgent-2.2.8 from disk
2017/06/11 09:54:32.300884 VERBOSE Agent WALinuxAgent-2.2.8 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/11 09:54:32.310974 VERBOSE Ensuring Agent WALinuxAgent-2.2.8 is downloaded
2017/06/11 09:54:32.317850 VERBOSE Agent WALinuxAgent-2.2.8 was previously downloaded - skipping download
2017/06/11 09:54:32.326572 VERBOSE Agent WALinuxAgent-2.2.8 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.8/HandlerManifest.json
2017/06/11 09:54:32.337625 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.8 HandlerManifest.json: {'name': 'WALinuxAgent', 'handlerManifest': {'enableCommand': 'python -u bin/WALinuxAgent-2.2.8-py2.7.egg -run-exthandlers', 'installCommand': '', 'disableCommand': '', 'uninstallCommand': '', 'updateCommand': '', 'rebootAfterInstall': False, 'reportHeartbeat': False}, 'version': 1.0}
2017/06/11 09:54:32.368372 VERBOSE Instantiating Agent WALinuxAgent-2.2.12 from disk
2017/06/11 09:54:32.375955 VERBOSE Agent WALinuxAgent-2.2.12 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/11 09:54:32.385957 VERBOSE Ensuring Agent WALinuxAgent-2.2.12 is downloaded
2017/06/11 09:54:32.393005 VERBOSE Agent WALinuxAgent-2.2.12 was previously downloaded - skipping download
2017/06/11 09:54:32.402447 VERBOSE Agent WALinuxAgent-2.2.12 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.12/HandlerManifest.json
2017/06/11 09:54:32.413780 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.12 HandlerManifest.json: {'name': 'WALinuxAgent', 'handlerManifest': {'enableCommand': 'python -u bin/WALinuxAgent-2.2.12-py2.7.egg -run-exthandlers', 'installCommand': '', 'disableCommand': '', 'uninstallCommand': '', 'updateCommand': '', 'rebootAfterInstall': False, 'reportHeartbeat': False}, 'version': 1.0}

**Comment by brendandixon** [comment]
@RobDonovan We changed (either 2.2.10 or 2.2.11, I forget which) to poll for changes more frequently. It is a bit of a balancing act: Since Azure, at present, relies on the agent to poll for updates, long poll delays add substantive overhead to the total time before changes take effect. On the other hand, shorter poll delays, while making changes more responsive, add (a small) CPU overhead. The agent on both Windows and Linux VMs use the same polling frequencies. We are aware and are evaluating other approaches. Implementing those, however, will take more time (and changes beyond the agent).

I appreciate your efforts to run a tight VM, but doing so in a virtual, cloud VM does not mean the same as with an on-premise VM or physical machine. There are too many factors to make using CPU consumption a reliable proxy for performance. I suggest you rely on outbound / inbound measures instead.

**Comment by RobDonovan** [comment]
Ok I see :(

Its not just the CPU though, each run is receiving ~15k of data, every 3 seconds, totals to about 400mb per day... since you charge by the MB... that's a bit crafty that you are 'generating' income that way ;)

My normal in-usage was only about 40mb per day for the last 4 years, but since that has been running the last few days, its shot up to 500+. Which is quite an increase.

Ah well... I'll just have to uninstall it, since I can see no real use of it for myself anyway.

**Comment by brendandixon** [comment]
@RobDonovan Hmm, that should not be caused by this. Every three seconds the agent invokes an on-node service for changes. The received Xml file contains an "incarnation" number (a monotonically increasing integer). If that has not change, then processing stops and waits until the next cycle. The file is not coming from Azure Storage, so you should not see *any* effect on your storage charges.

If you have data showing otherwise, we need to know. Thank you!

**Comment by RobDonovan** [comment]
Ah yes, sorry, its inbound traffic, so no charge for that.

It seems to be involving the Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0 extension.

I see it doing 2 get requests, the first "/machine/?comp=goalstate" gets the incarnation number, and that is always '6' for every request for me. That request is about 2kb.

But, after that, it then also does a get request for "xxxxxxxx/Microsoft.OSTCExtensions_VMAccessForLinux_ussouth_manifest.xml" (I've removed the first part, as I'm not sure if its some kind of secure token etc)

That request is about 12kb.

So since your explanation said it shouldn't do anything if it gets the same incarnation number, is there something wrong then? Or is that 'normal' behavior?

**Comment by brendandixon** [comment]
@RobDonovan Is the request for the Xml successful? The agent should not be repeatedly requesting it.

The Xml is the "manifest" for the extension. The URL is a self-signed read-only URL into Azure Storage (more or less). The returned file lists the available versions of the extension. The agent will, depending on the settings, upgrade extensions to their latest hot fixes. *Usually* the manifest is fetched and cached to disk, so no network access should occur unless the incarnation updates.

The VM Access extension is installed whenever you reset your password or SSH key via the Azure Portal (or via the CLI). You can safely remove it (again, via the Azure Portal or CLI). It will install again if needed. Uninstalling it will silence all the traffic.

**Comment by RobDonovan** [comment]
Ok, I'll remove it from Azure Portal, but I'll leave it for a few days, incase you need me to do anything to find any problem.

And yes, the 2nd request is successful, its XML that is returned (the 12kb) and its returned with a HTTP 200 OK. It just keeps doing that every 3 seconds.

I can send you an strace log of it if you want?

**Comment by brendandixon** [comment]
@RobDonovan I would need to look over the log. The log contains no secrets, so sharing it is safe. (Feel free to review it yourself if you have concerns.) It is the intention of the code that no work be done unless the incarnation number changes.

**Comment by RobDonovan** [comment]
Here you go, tar file with the logs, strace, settings etc...

As you can see from waagent.log, it does the goalstate, gets 6, and then gets the VMAccess xml file every time, even though /var/lib/waagent/Incarnation has a 6 in it.

HTHs.
[waagent.tar.gz](https://github.com/Azure/WALinuxAgent/files/1072753/waagent.tar.gz)

**Comment by RobDonovan** [comment]
Great :) Glad it helped you find something.
