### ISSUE TITLE
ResourceDisk.EnableSwap to y and rebooting does not add swap

### ISSUE THREAD

**Issue by mitar** [Azure/WALinuxAgent#76]
I am using an official Ubuntu Server 14.04 LTS image. After booting I noticed that there is no swap. So I went and edited the `/etc/waagent.conf`, configured:

```
ResourceDisk.EnableSwap=y
ResourceDisk.SwapSizeMB=10240
```

Rebooted, but there is still not swap.

**Comment by szarkos** [comment]
The Ubuntu images use cloud-init to configure the swap partition.  To configure this on Ubuntu you will need to send a cloud-config during provisioning:  https://wiki.ubuntu.com/AzureSwapPartitions
