### ISSUE TITLE
Can I install WALinuxAgent as post installation script?. 

### ISSUE THREAD

**Issue by KeerthigaKrishnan** [Azure/WALinuxAgent#765]
HI, 

I have a image which hardened it. But the waagent is not installed on that. 
Can I install that after OS boots ?.

**Comment by brendandixon** [comment]
@KeerthigaKrishnan Yes, you can. However, you'll need to create a file named `provisioned` in the `/var/lib/waagent` directory. The file should contain the VM unique identifier. Azure writes the identifier to `/sys/class/dmi/id/product_uuid`. In the odd case that file is not present, you can also obtain using the command `dmidecode --string system-uuid`.
