### ISSUE TITLE
Parametes being read from waagent.conf also include comments after update

### ISSUE THREAD

**Issue by lovepreetkaul** [Azure/WALinuxAgent#766]
The waagent.conf parameters also read comments into the value if the comments are in the same line.
For example:
```
OS.OpensslPath=None                       # If "None", the system default version is used.
```
The value passed into the cmd for `OS.OpensslPath` is `None                       # If "None", the system default version is used.`

```
WALinuxAgent-2.2.13 running on centos 7.3.1611
Python: 2.7.5
Goal state agent: 2.2.13
```

**Comment by brendandixon** [comment]
@lovepreetkaul We appreciate your finding, but the /etc/waagent.conf file is a very, simple key, value based file. We do not support end-of-line comments.
