### ISSUE TITLE
HostGAPlugin requests should never go through proxy

### ISSUE THREAD

**Issue by paulmey** [Azure/WALinuxAgent#769]
When downloading from storage fails, requests [are routed through the HostGAPlugin](https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/protocol/wire.py#L629), but they are also still going through the proxy. In the case that the proxy is misconfigured, this will lead to ultimate failure to download the artifact.
Additionally, there should probably be a warning when a proxy is configured and storage is still unreachable through the proxy.

**Comment by brendandixon** [comment]
Addressed by #776
