### ISSUE TITLE
 High processor consumption

### ISSUE THREAD

**Issue by r1ckyfl0w** [Azure/WALinuxAgent#772]
this is correct? All this process for one program

~# systemctl status waagent
● waagent.service - LSB: WindowsAzureLinuxAgent
   Loaded: loaded (/etc/init.d/waagent)
   Active: active (running) since Tue 2017-06-20 10:47:33 AST; 6min ago
  Process: 61047 ExecStop=/etc/init.d/waagent stop (code=exited, status=0/SUCCESS)
  Process: 65515 ExecStart=/etc/init.d/waagent start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/waagent.service
           ├─  302 python -u /usr/sbin/waagent -run-exthandlers
           ├─  310 python -u /usr/sbin/waagent -run-exthandlers
           ├─  367 python -u /usr/sbin/waagent -run-exthandlers
           ├─  430 python /usr/sbin/waagent -daemon
           ├─ 2326 python /usr/sbin/waagent -daemon
           ├─65436 python /usr/sbin/waagent -daemon
           ├─65524 python /usr/sbin/waagent -daemon
           └─65534 python -u /usr/sbin/waagent -run-exthandlers

Jun 20 10:47:33 localhost systemd[1]: Starting LSB: WindowsAzureLinuxAgent...
Jun 20 10:47:33 localhost waagent[65515]: Starting WindowsAzureLinuxAgent....
Jun 20 10:47:33 localhost systemd[1]: Started LSB: WindowsAzureLinuxAgent.

WALinuxAgent-2.2.13 running on debian 8.7
Python: 2.7.9
Goal state agent: 2.2.13

waagent.log

2017/06/20 11:47:43.586454 INFO WALinuxAgent-2.2.13 waiting for orphan process 367 to terminate
2017/06/20 11:47:43.801300 INFO WALinuxAgent-2.2.13 waiting for orphan process 367 to terminate
2017/06/20 11:47:43.842308 INFO WALinuxAgent-2.2.13 waiting for orphan process 65534 to terminate
2017/06/20 11:47:44.977682 INFO Agent WALinuxAgent-2.2.10 is blacklisted - skipping download
2017/06/20 11:47:44.979090 INFO Agent WALinuxAgent-2.2.8 is blacklisted - skipping download
2017/06/20 11:47:44.980313 INFO Agent WALinuxAgent-2.2.12 is blacklisted - skipping download
2017/06/20 11:47:44.981554 INFO Agent WALinuxAgent-2.2.13 is blacklisted - skipping download

repeat... and repeat
![waagent](https://user-images.githubusercontent.com/29577146/27342888-69858660-55af-11e7-917e-35fa3eae60dc.jpg)

**Comment by brendandixon** [comment]
@r1ckyfl0w I'm not sure what's occurred, but there should be a single instance of the daemon process (i.e., `python -u /usr/sbin/waagent - daemon`) and a single instance of the child process (i.e., `python -u /usr/sbin/waagent -run-exthandlers`).

Here's what I suggest you do:

* Stop the instance managed by systemctl (i.e., `systemctl stop waagent`).
* `kill` any remaining instances of the parent (that should take the children as well).
* Restart the systemctl managed instance (i.e., `systemctl start waagent`).

That should clear things up.

**Comment by r1ckyfl0w** [comment]
Done...

~# systemctl status waagent
● waagent.service - LSB: WindowsAzureLinuxAgent
   Loaded: loaded (/etc/init.d/waagent)
   Active: active (running) since Tue 2017-06-20 12:24:04 AST; 15s ago
  Process: 7152 ExecStop=/etc/init.d/waagent stop (code=exited, status=0/SUCCESS)
  Process: 7440 ExecStart=/etc/init.d/waagent start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/waagent.service
           ├─7446 python /usr/sbin/waagent -daemon
           └─7452 python -u /usr/sbin/waagent -run-exthandlers

Jun 20 12:24:04 localhost waagent[7440]: Starting WindowsAzureLinuxAgent....
Jun 20 12:24:04 localhost
![waagent2](https://user-images.githubusercontent.com/29577146/27344369-0f9f1e7c-55b4-11e7-93fb-5d92cdaae705.PNG)
 systemd[1]: Started LSB: WindowsAzureLinuxAgent.
