### ISSUE TITLE
Service walinuxagent is dead and hang while manually starting on Debian 8

### ISSUE THREAD

**Issue by beelesnik** [Azure/WALinuxAgent#773]
Unfortunatelly You closed my prevoius ticket (https://github.com/Azure/WALinuxAgent/issues/767) and I don't know why...

What concerns method of installation of walinuxagent.
I have tried all options.

But last log was taken from VM created by original  Debian image from Azure and I did no touch agent at all except enabling verbose logging.
And I have got such log with dead walinuxagent service:

walinuxagent.service - Microsft Azure Linux Agent
Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled)
Active: inactive (dead)

2017/06/20 10:38:53.055050 VERBOSE Agent WALinuxAgent-2.2.13 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.13/HandlerManifest.json
2017/06/20 10:38:53.077214 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.13 HandlerManifest.json: {'handlerManifest': {'reportHeartbeat': False, 'installCommand': '', 'rebootAfterInstall': False, 'enableCommand': 'python -u bin/WALinuxAgent-2.2.13-py2.7.egg -run-exthandlers', 'updateCommand': '', 'uninstallCommand': '', 'disableCommand': ''}, 'name': 'WALinuxAgent', 'version': 1.0}
2017/06/20 10:38:53.133992 VERBOSE Instantiating Agent WALinuxAgent-2.2.12 from disk
2017/06/20 10:38:53.145231 INFO Agent WALinuxAgent-2.2.2 forwarding signal 15 to WALinuxAgent-2.2.13
2017/06/20 11:01:58.965411 INFO Activate resource disk
2017/06/20 11:01:59.002772 VERBOSE run cmd 'mount'
2017/06/20 11:01:59.047799 INFO Examining partition table
2017/06/20 11:01:59.056929 VERBOSE run cmd 'blkid -o value -s PTTYPE /dev/sdb'
2017/06/20 11:01:59.137793 INFO GPT not detected, determining filesystem
2017/06/20 11:01:59.170816 VERBOSE run cmd 'blkid -o value -s TYPE /dev/sdb1'
2017/06/20 10:39:48.160101 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/06/20 10:39:48.220541 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/06/20 10:39:48.293273 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/06/20 10:40:00.593970 INFO Provisioning already completed, skipping.
2017/06/20 12:00:49.979667 INFO Activate resource disk
2017/06/20 12:00:50.008467 VERBOSE run cmd 'mount'
2017/06/20 12:00:50.055507 INFO Examining partition table
2017/06/20 12:00:50.077054 VERBOSE run cmd 'blkid -o value -s PTTYPE /dev/sdb'
2017/06/20 12:00:34.282794 INFO GPT not detected, determining filesystem
2017/06/20 12:00:34.335180 VERBOSE run cmd 'blkid -o value -s TYPE /dev/sdb1'
2017/06/20 12:00:34.398692 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/06/20 12:00:34.411053 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/06/20 12:00:34.449575 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/06/20 12:01:06.807027 INFO Provisioning already completed, skipping.

I.e. original Debian image from Azure contains waagent package that could fail under some conditions?

I have no any problems with  such initial customization on hundreds of Debian servers in my company  that placed in Openstack, AWS, Cloudstack and on real hardware.

Why did You think that it was not waagent package problem?

**Comment by brendandixon** [comment]
@beelesnik The agent *does not* kill itself. The logs clearly show 2.2.2 receiving and forwarding a kill signal (15). We do not package the agent for the distributions; the vendors (e.g., Debian) own and distribute those packages.

I'm not sure how to help you. The default Debian image from the Azure gallery works fine. The agent runs as expected. It even downloads and launches the latest agent (2.2.13).

Given that nothing in the logs you've provided suggests the agent is malfunctioning and that the agent behaves as expected on the default Debian image, I cannot, at this time, blame the agent. It appears, instead, to be a problem with the installation.

**Comment by beelesnik** [comment]
First of all I want to solve the problem because now I have a task to try to arrange some servers in the Azure cloud.  I understand that the walinuxagent is an important part for a full implementation.

Take one of the options that I have worked...
1. I created a virtual machine from the Debian 8 standard image provided in Azure. And walinuxagent works well.  Ok, it's great! But who will use the empty system to work? To use a virtual machine in my business processes, I need to configure it. Isn't it?

2. I configure system for needs of my organization (adding packages, putting configuration files, enabling LDAP authentication and so on).  I note, all these actions do not affect the package waagent in principle, because these actions were previously applied to servers where there is no waagent package.

3. After that service walinuxagent is not working (it is dead and could not start). 

4. You said "It appears, instead, to be a problem with the installation.". But with installation of what? waagent? But in last case I used preinstalled package and  did not touch any part of waagent except enabling verbose logging for analysis. 

5. Summary. I have Debian 8 standard image with preinstalled waagent and it works well for newly created VM. But after some actions that do not directly affect the walinuxagent in any way, I get a dead walinuxagent. How could I understand why walinuxagent becomes dead?

**Comment by brendandixon** [comment]
@beelesnik I am not trying to be confusing or difficult, but the logs lines above *clearly* show that something asked the agent to stop running. So it stopped. I have no idea what made the request or why. Further, we have *many* instances of Debian and Ubuntu running successfully with custom configurations and the agent running. You can skim the agent log (i.e., `/var/log/waagent.log`) for errors. If you see one, we can try to help. But, all evidence you've supplied suggests that something on the system is requesting the agent to stop running.

**Comment by beelesnik** [comment]
Today I tried step by step to apply the changes necessary to me, reboot the virtual machine after changes and found the following.
As soon as  I applied the configuration for LDAP authentication (including ldap.conf and appropriate pam-files ) -  the next reboot of VM made the agent unworkable. I could attach this log to comment but You won't see anything new.
It look like these strings from my previous comments:
2017/06/20 10:38:53.133992 VERBOSE Instantiating Agent WALinuxAgent-2.2.12 from disk
2017/06/20 10:38:53.145231 INFO Agent WALinuxAgent-2.2.2 forwarding signal 15 to WALinuxAgent-2.2.13
2017/06/20 11:01:58.965411 INFO Activate resource disk
2017/06/20 11:01:59.002772 VERBOSE run cmd 'mount'
2017/06/20 11:01:59.047799 INFO Examining partition table
2017/06/20 11:01:59.056929 VERBOSE run cmd 'blkid -o value -s PTTYPE /dev/sdb'

I think that after reboot waagent could not start at all.
I tried configuration with autoupdating agent and with disable autoupdating - it does not matter.
If I enable LDAP authentication next reboot kills the walinuxagent.

Tomorrow I will try to study this situation in more detail

**Comment by brendandixon** [comment]
@beelesnik It would be odd for LDAP to affect the agent. Perhaps, while configuring LDAP, some other change was made as well?

I suggest you also examine the systemd journal for the agent to see if it has any messages that might help.

**Comment by beelesnik** [comment]
News for today
1. I repeated the steps of rolling the required configuration onto the test virtual machine.
2. Before I put the our custom /etc/ldap.conf file on the virtual machine, everything was fine. The agent worked, I could restart it and it did not die when the system was rebooted.
3. When I put the file on the virtual machine, until I rebooted it, the agent also worked successfully, I could restart it.
Here's what happened:
 # date
Thu Jun 22 09:56:52 UTC 2017
 # systemctl restart walinuxagent
 # date
Thu Jun 22 09:57:15 UTC 2017
 # systemctl status walinuxagent
● walinuxagent.service - Microsft Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled)
   Active: active (running) since Thu 2017-06-22 09:57:02 UTC; 16s ago
 Main PID: 6323 (waagent)
   CGroup: /system.slice/walinuxagent.service
           ├─6323 /usr/bin/python3 /usr/sbin/waagent -daemon
           └─6367 python3 -u /usr/sbin/waagent -run-exthandlers

Jun 22 09:57:10 testsalt waagent[6323]: 2017/06/22 09:57:10.324427 INFO [Microsoft.Azure.RecoveryServices.VMS...sion.
Jun 22 09:57:10 testsalt waagent[6323]: 2017/06/22 09:57:10.350878 INFO [Microsoft.Azure.RecoveryServices.VMS...nable
Jun 22 09:57:10 testsalt waagent[6323]: Traceback (most recent call last):
Jun 22 09:57:10 testsalt waagent[6323]: File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLin...dule>
Jun 22 09:57:10 testsalt waagent[6323]: from Utils import HandlerUtil
Jun 22 09:57:10 testsalt waagent[6323]: File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLin...dule>
Jun 22 09:57:10 testsalt waagent[6323]: from waagent import LoggerInit
Jun 22 09:57:10 testsalt waagent[6323]: ImportError: cannot import name LoggerInit
Jun 22 09:57:11 testsalt waagent[6323]: 2017/06/22 09:57:11.368563 ERROR Event: name=Microsoft.Azure.Recovery...nable
Jun 22 09:57:11 testsalt waagent[6323]: 2017/06/22 09:57:11.869173 INFO Event: name=WALinuxAgent, op=HealthCh...Blob]
Hint: Some lines were ellipsized, use -l to show in full.

4. After the virtual machine was rebooted, the agent died, as I have seen many times before
Here is the log:
am Name="ContainerId" Value="6bbeb9cc-018d-4f3f-ad27-720b7ff4c171" T="mt:wstr" />]]></Event></Provider></TelemetryData>] [{'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent', 'Content-Type': 'text/xml;charset=utf-8'}]
2017/06/22 09:58:10.440375 VERBOSE HTTP response status: [200]
2017/06/22 09:58:22.884531 INFO Agent WALinuxAgent-2.2.2 forwarding signal 15 to WALinuxAgent-2.2.2
2017/06/22 09:59:36.663334 INFO Activate resource disk
2017/06/22 09:59:36.683850 VERBOSE run cmd 'mount'
2017/06/22 09:59:36.720512 INFO Examining partition table
2017/06/22 09:59:36.735969 VERBOSE run cmd 'blkid -o value -s PTTYPE /dev/sdb'
2017/06/22 09:59:36.833443 INFO GPT not detected, determining filesystem
2017/06/22 09:59:36.858241 VERBOSE run cmd 'blkid -o value -s TYPE /dev/sdb1'
2017/06/22 09:59:36.976081 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/06/22 09:59:37.017467 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/06/22 09:59:26.331254 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/06/22 10:00:04.063622 INFO Provisioning already completed, skipping.

As You see "2017/06/22 09:58:22.884531 INFO Agent WALinuxAgent-2.2.2 forwarding signal 15 to WALinuxAgent-2.2.2" means that virtual machine was rebooted. But after rebooting walinuxagent could not start at all.

Every attempt to start walinuxagent by 'systemctl start walinuxagent' adds next strings to log:
<<OLD STRING>>2017/06/22 10:00:04.063622 INFO Provisioning already completed, skipping.
2017/06/22 10:17:56.299171 INFO Provisioning already completed, skipping.
2017/06/22 10:17:56.309669 INFO Activate resource disk
2017/06/22 10:17:56.326830 VERBOSE run cmd 'mount'
2017/06/22 10:17:56.355149 INFO Resource disk [/dev/sdb1] is already mounted [/mnt/resource]

And command 'systemctl start walinuxagent' is hanging forever....


I definetely does not know what should I do next... I could attach strace output  [https://pastebin.com/dhYLmUgb](https://pastebin.com/dhYLmUgb) if it helps

**Comment by beelesnik** [comment]
This is all error messages in waagent.log. At the end You will see unsuccessful  attempt to create snapshot initiated myself, but it is not important because I cancelled the task of backup VM.
I enable verbose logging and disable autoupdate for agent at this time.

 # cat /var/log/waagent.log  | grep -i error
2017/06/22 05:52:33.690610 INFO Agent WALinuxAgent-2.2.10 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:52:33.852242 INFO Agent WALinuxAgent-2.2.10 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:52:33.908087 INFO Agent WALinuxAgent-2.2.12 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:52:34.051328 INFO Agent WALinuxAgent-2.2.12 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:52:34.123719 INFO Agent WALinuxAgent-2.2.13 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:52:34.283493 INFO Agent WALinuxAgent-2.2.13 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:52:34.346218 INFO Agent WALinuxAgent-2.2.8 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:52:34.514621 INFO Agent WALinuxAgent-2.2.8 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:53:29.640073 INFO Agent WALinuxAgent-2.2.13 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:53:29.695705 INFO Agent WALinuxAgent-2.2.10 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:53:29.744273 INFO Agent WALinuxAgent-2.2.8 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 05:53:29.791786 INFO Agent WALinuxAgent-2.2.12 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/22 09:06:13.296093 ERROR [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9114.0] Failed to set state: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9114.0/config/HandlerState'
2017/06/22 09:06:14.693748 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Install, message=(000003)Non-zero exit code: 1, main/handle.py -install
2017/06/22 09:57:11.368563 ERROR Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Enable, message=(000003)Non-zero exit code: 1, main/handle.py -enable

**Comment by brendandixon** [comment]
@beelesnik The repeated lines are normal output when the agent restarts. They do not indicate any problem.

You must be including a limited set of lines from `/var/log/waagent.log`. There are a series of additional lines that are *always* emitted after those you pasted.

Again -- and I am not trying to be difficult -- *nothing* you've pasted or shared suggests a problem with the agent. Even the fact that `systemctl start walinuxagent` "hangs" does not mean a problem with the agent (since `systemd` does much more than simply launch the named process / service). The agent *has no* dependencies in any way on LDAP. That installation of that file *must* be affecting something else on your system.

If you share the entire log (`/var/log/waagent.log`), I can look it over. But, again, it is exceedingly unlikely that this is a problem with the agent.

**Comment by beelesnik** [comment]
I think I find the solution, but it is not reanimation.  It is recreation.
I removed package waagent (apt-get remove waagent) and its config and logfile.
Then I install github version of walinuxagent, unmask walinuxagent unit and now it is alright.
After reboot I have working walinuxagent on my custom system.

**Comment by brendandixon** [comment]
@beelesnik Ok. That's good. However, if a manual install works, then an install from the repository should work as well. Since you're now running successfully, I'll close the issue.
