### ISSUE TITLE
WALA fails in AzureStack in update flow

### ISSUE THREAD

**Issue by nikhilmhatre** [Azure/WALinuxAgent#774]
I tried to deploy a azurestack VM after updating the cloud foundry  (Ubuntu 1404) image to WALA 2.2.13

I am seeing the following error. 
2017/06/08 21:06:18.692103 INFO WALinuxAgent-2.2.13 waiting for orphan process 33736 to terminate
2017/06/08 21:06:20.516163 WARNING Agent WALinuxAgent-2.2.13 failed with ```
exception: 'MetadataProtocol' object has no attribute 'client'
2017/06/08 21:06:20.611799 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/azurelinuxagent/ga/update.py", line 256, in run
    if self._upgrade_available():
  File "/usr/local/lib/python2.7/dist-packages/azurelinuxagent/ga/update.py", line 427, in _upgrade_available
    if protocol and protocol.client:
AttributeError: 'MetadataProtocol' object has no attribute 'client'

```
[waagent.txt](https://github.com/Azure/WALinuxAgent/files/1089466/waagent.txt)

**Comment by brendandixon** [comment]
@nikhilmhatre This will be addressed by #761.
