### ISSUE TITLE
Status Blob type is unspecified -- assuming it is a BlockBlob

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#775]
A customer i's getting the "Status Blob type is unspecified -- assuming it is a BlockBlob" message showing up every 3 seconds with 2.2.13 and filling up the log.  What does that message means and how to get rid of it ?

There is a also an exception when the agent try to post its status:
```
2017/06/16 21:29:11.162571 INFO Status Blob type is unspecified -- assuming it is a BlockBlob
2017/06/16 21:29:14.220657 INFO Status Blob type is unspecified -- assuming it is a BlockBlob
2017/06/16 21:29:18.283114 INFO Status Blob type is unspecified -- assuming it is a BlockBlob
2017/06/16 21:29:48.579497 INFO Event: name=WALinuxAgent, op=InitializeHostPlugin, message=
2017/06/16 21:30:18.636194 ERROR Event: name=WALinuxAgent, op=ReportStatus, message=HostGAPlugin: Exception Put VM status: [000009] HTTP PUT failed, Traceback (most recent call last):
  File "bin/WALinuxAgent-2.2.13-py2.7.egg/azurelinuxagent/common/protocol/hostplugin.py", line 173, in put_vm_status
    self._put_block_blob_status(sas_url, status_blob)
  File "bin/WALinuxAgent-2.2.13-py2.7.egg/azurelinuxagent/common/protocol/hostplugin.py", line 197, in _put_block_blob_status
    headers=self._build_status_headers())
  File "bin/WALinuxAgent-2.2.13-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 192, in http_put
    max_retry=max_retry, chk_proxy=chk_proxy)
  File "bin/WALinuxAgent-2.2.13-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 172, in http_request
    raise HttpError("{0} failed".format(log_msg))
HttpError: [000009] HTTP PUT failed

2017/06/16 21:30:18.678341 WARNING HostGAPlugin: resetting default channel
2017/06/16 21:30:21.701695 INFO Status Blob type is unspecified -- assuming it is a BlockBlob
2017/06/16 21:30:24.764154 INFO Status Blob type is unspecified -- assuming it is a BlockBlob
2017/06/16 21:30:28.820477 INFO Status Blob type is unspecified -- assuming it is a BlockBlob
```

[waagent.log](https://gist.githubusercontent.com/johanburati/453ae9c699e6353dfc135eae55c6aafd/raw/16839f2bf7bdf8bd93acfb729276a291dba804cf/waagent.log)

**Comment by brendandixon** [comment]
@johanburati We apologize about the over abundance of messages. We made a change that adjust the rate at which the agent polls. The over abundance of messages was the unintended side-effect. However, we will address this in our next release (2.2.14) via #740.

The exception, too, is dealt with by changes on the underlying host running the VM.

**Comment by johanburati** [comment]
thank you @brendandixon.  Could you reply to the following questions ?

1. what is the cause of the error ?
2. what does the error mean and what are the effects ?
3. the agent is supposed to auto install the latest version, when will it update to version 2.2.14 ?

**Comment by brendandixon** [comment]
@johanburati The cause is buried in code that runs on the host node. That code is not, at present, open source and, so, cannot share the specific details. The effect of the error was, for a single cycle, the agent failed to push an update to the blob that holds the VM status.

We'll be releasing v2.2.14 into Azure regions very soon (starting today, actually). Once available, existing agents should pick it up.
