### ISSUE TITLE
WAAgent 2.2.13 - Shows not ready / not running on ASM - InvalidBlobType errors

### ISSUE THREAD

**Issue by mabicca** [Azure/WALinuxAgent#779]
$  cat /etc/*release >> /tmp/Solr4.txt

CentOS release 6.9 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
CentOS release 6.9 (Final)
CentOS release 6.9 (Final)

+++++++++++++====================+++++++++++++====================

	$ uname -a >> /tmp/Solr4.txt

Linux HOSTNAME 2.6.32-358.14.1.el6.x86_64 #1 SMP Tue Jul 16 23:51:20 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

+++++++++++++====================+++++++++++++====================

	$ waagent --version >> /tmp/Solr4.txt

WALinuxAgent-2.2.13 running on centos 6.9
Python: 2.6.6
Goal state agent: 2.2.13

+++++++++++++====================+++++++++++++====================

	$ tail -f /var/log/waagent.log
	
	
    self.read_response_error(response)))
HttpError: [000009] HostGAPlugin: Put BlockBlob failed: [409: Conflict] {
    "errorCode": "The blob type is invalid for this operation.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:1c301074-0001-009b-2ab8-ead9ec000000
Time:2017-06-21T18:04:35.9058949Z</Message></Error>",
    "details": ""
}

2017/06/21 11:04:34.929646 WARNING HostGAPlugin: resetting default channel
2017/06/21 11:04:39.146907 ERROR Event: name=WALinuxAgent, op=ReportStatus, message=HostGAPlugin: Exception Put VM status: [000009] HostGAPlugin: Put BlockBlob failed: [409: Conflict] {
    "errorCode": "The blob type is invalid for this operation.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:1c3017e7-0001-009b-6eb8-ead9ec000",
    "details": ""
}, Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 173, in put_vm_status
    self._put_block_blob_status(sas_url, status_blob)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 201, in _put_block_blob_status
    self.read_response_error(response)))
HttpError: [000009] HostGAPlugin: Put BlockBlob failed: [409: Conflict] {
    "errorCode": "The blob type is invalid for this operation.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:1c3017e7-0001-009b-6eb8-ead9ec000",
    "details": ""
}

2017/06/21 11:04:39.373312 WARNING HostGAPlugin: resetting default channel
2017/06/21 11:04:42.615278 ERROR Event: name=WALinuxAgent, op=ReportStatus, message=HostGAPlugin: Exception Put VM status: [000009] HostGAPlugin: Put BlockBlob failed: [409: Conflict] {
    "errorCode": "The blob type is invalid for this operation.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:656cc7c0-0001-006d-29b8-eafefa000000
Time:2017-06-21T18:04:44.3455336Z</Message></Error>",
    "details": ""
}, Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 173, in put_vm_status
    self._put_block_blob_status(sas_url, status_blob)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 201, in _put_block_blob_status
    self.read_response_error(response)))
HttpError: [000009] HostGAPlugin: Put BlockBlob failed: [409: Conflict] {
    "errorCode": "The blob type is invalid for this operation.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:656cc7c0-0001-006d-29b8-eafefa000000
Time:2017-06-21T18:04:44.3455336Z</Message></Error>",
    "details": ""
}

2017/06/21 11:04:42.809203 WARNING HostGAPlugin: resetting default channel
2017/06/21 11:04:46.017431 ERROR Event: name=WALinuxAgent, op=ReportStatus, message=HostGAPlugin: Exception Put VM status: [000009] HostGAPlugin: Put BlockBlob failed: [409: Conflict] {
    "errorCode": "The blob type is invalid for this operation.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:656ccbaf-0001-006d-22b8-eafefa000000
Time:2017-06-21T18:04:47.7487180Z</Message></Error>",
    "details": ""
}, Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 173, in put_vm_status
    self._put_block_blob_status(sas_url, status_blob)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/protocol/hostplugin.py", line 201, in _put_block_blob_status
    self.read_response_error(response)))
HttpError: [000009] HostGAPlugin: Put BlockBlob failed: [409: Conflict] {
    "errorCode": "The blob type is invalid for this operation.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:656ccbaf-0001-006d-22b8-eafefa000000
Time:2017-06-21T18:04:47.7487180Z</Message></Error>",
    "details": ""
}

2017/06/21 11:04:46.326259 WARNING HostGAPlugin: resetting default channel

**Comment by brendandixon** [comment]
@mabicca This issue is not with the agent, but caused by the underlying compute infrastructure. It created an incorrect object type in Azure Storage. You could either a) delete the VM and start over or b) contact Azure support (they would direct you to support team who can make changes to the underlying storage object). I hope this helps!
