### ISSUE TITLE
Requested role config file is not found

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#781]
A customer is getting the following warning in his VM waagent.log about once a day,
I have seen that warning message as well in my VMs log most often around 18:00 UTC.

Is there a reason why around time, the agent is enable to fetch the page ?

Also I found a similar issue  [661](https://github.com/Azure/WALinuxAgent/issues/661), it says that the agent falls back to using the url because the port 8443 is blocked, in our case port 8443 is not blocked, should the agent use the url in the first place ?

For the customer, that message show up also after it took a backup, is there any correlation ?

```
2017/06/17 02:35:13.404600 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/06/17 02:37:26.284964 INFO Event: name=WALinuxAgent-2.2.13, op=HeartBeat, message=
2017/06/17 02:55:53.982579 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/06/17 03:07:38.143509 INFO Event: name=WALinuxAgent-2.2.13, op=HeartBeat, message=
2017/06/17 03:10:57.565494 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/06/17 03:12:47.206728 WARNING Could not fetch http://168.63.129.16:32526/extensionArtifact [[400: Bad Request] {
    "errorCode": "RequestRoleConfigFileNotFound",
    "message": "Requested role config file is not found.",
    "details": ""
}]
2017/06/17 03:12:47.285905 WARNING Forcing update of goal state
2017/06/17 03:12:50.432880 INFO Retry fetch in 1 seconds
2017/06/17 03:12:51.457089 INFO Event: name=WALinuxAgent, op=InitializeHostPlugin, message=
2017/06/17 03:25:54.426663 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/06/17 03:37:50.308376 INFO Event: name=WALinuxAgent-2.2.13, op=HeartBeat, message=
2017/06/17 03:40:54.804377 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message
```
[waagent.log](https://gist.githubusercontent.com/johanburati/8e92de315cb0f826ac8c4ef81282a745/raw/6be0de43e504b3290a71937b9dda52ff71a1972e/waagent.log)

**Comment by brendandixon** [comment]
@johanburati It's nothing to be concerned about. It has to do with how the host beneath the VM caches certain files. We track these for monitoring purposes; it should not affect the VM. I would like to see these eliminated, but it requires work, as I mentioned, on the host node. We will eventually get to it.

**Comment by johanburati** [comment]
Thank you @brendandixon. If possible it would be better to log those kind of message only if _Logs.Verbose_ is set to _y_.

**Comment by brendandixon** [comment]
@johanburati The messages normally rare and best kept in as they are. We have, however, reduce the noisiness of many messages in the latest build.
