### ISSUE TITLE
walinuxagent 2.2.14 duplicate processes while restarting

### ISSUE THREAD

**Issue by beelesnik** [Azure/WALinuxAgent#787]
Good day
I started using Agent version 2.2.14 and noticed that it duplicates the processes at startup

For example, for waagent 2.2.4 I see following:
$ waagent -version
WALinuxAgent-2.2.2 running on debian 8.8
Python: 3.4.2
Goal state agent: b'2.2.13'
root@cleandebian8:/home/tcadmin$ systemctl status walinuxagent
● walinuxagent.service - Microsft Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled)
   Active: active (running) since Mon 2017-06-26 10:58:06 UTC; 2min 19s ago
 Main PID: 483 (waagent)
   CGroup: /system.slice/walinuxagent.service
           ├─483 /usr/bin/python3 /usr/sbin/waagent -daemon
           └─500 python3 -u bin/WALinuxAgent-2.2.13-py2.7.egg -run-exthandlers

Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.364749 INFO Start env monitor service.
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.382501 INFO Configure routes
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.391943 INFO Gateway:None
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.410150 INFO Routes:None
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.419727 WARNING Hostname record does not exist, creating [/var/lib/waagent/published_hostname] with hostname [cleandebian8]
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.455735 INFO WALinuxAgent-2.2.13 running as process 500
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.463096 WARNING Dhcp client is not running.
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.470242 INFO Wire server endpoint:168.63.129.16
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.543855 INFO Wire server endpoint:168.63.129.16
Jun 26 10:59:07 cleandebian8 waagent[483]: 2017/06/26 10:59:07.758519 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
$
$ ps aux | grep waagent
root       483  0.2  0.5  64860 18944 ?        Ss   10:58   0:00 /usr/bin/python3 /usr/sbin/waagent -daemon
root       579  0.0  0.0  13176   996 pts/0    S+   11:00   0:00 grep waagent
$ systemctl restart walinuxagent
$ systemctl status walinuxagent
● walinuxagent.service - Microsft Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled)
   Active: active (running) since Mon 2017-06-26 11:01:00 UTC; 2s ago
 Main PID: 591 (waagent)
   CGroup: /system.slice/walinuxagent.service
           ├─591 /usr/bin/python3 /usr/sbin/waagent -daemon
           └─605 python3 -u bin/WALinuxAgent-2.2.13-py2.7.egg -run-exthandlers
$ ps aux | grep waagent
root       591  5.2  0.5  64864 18852 ?        Ss   11:00   0:00 /usr/bin/python3 /usr/sbin/waagent -daemon
root       618  0.0  0.0  13176   996 pts/0    S+   11:01   0:00 grep waagent

With waagent 2.2.14 every restart duplicates the processes:

$ date
Mon Jun 26 10:41:48 UTC 2017
$ waagent -version
WALinuxAgent-2.2.14 running on debian 8.8
Python: 2.7.9
Goal state agent: 2.2.14
$ systemctl status walinuxagent
● walinuxagent.service - LSB: Microsoft Azure Linux Agent
   Loaded: loaded (/etc/init.d/walinuxagent)
   Active: active (running) since Mon 2017-06-26 10:27:26 UTC; 14min ago
  Process: 403 ExecStart=/etc/init.d/walinuxagent start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/walinuxagent.service
           ├─454 python /usr/sbin/waagent -daemon
           └─701 python -u /usr/sbin/waagent -run-exthandlers
Jun 26 10:26:42 debianfromimage2306-02 systemd[1]: Starting LSB: Microsoft Azure Linux Agent...
Jun 26 10:27:26 debianfromimage2306-02 systemd[1]: Started LSB: Microsoft Azure Linux Agent.
$ date
Mon Jun 26 10:45:26 UTC 2017
$ systemctl restart walinuxagent
$ systemctl status walinuxagent
● walinuxagent.service - LSB: Microsoft Azure Linux Agent
   Loaded: loaded (/etc/init.d/walinuxagent)
   Active: active (running) since Mon 2017-06-26 10:45:34 UTC; 2s ago
  Process: 2885 ExecStop=/etc/init.d/walinuxagent stop (code=exited, status=0/SUCCESS)
  Process: 2893 ExecStart=/etc/init.d/walinuxagent start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/walinuxagent.service
           ├─ 454 python /usr/sbin/waagent -daemon
           ├─2902 python /usr/sbin/waagent -daemon
           ├─2907 python -u /usr/sbin/waagent -run-exthandlers
           └─2912 python -u /usr/sbin/waagent -run-exthandlers
Jun 26 10:45:34 debianfromimage2306-02 systemd[1]: Starting LSB: Microsoft Azure Linux Agent...
Jun 26 10:45:34 debianfromimage2306-02 systemd[1]: Started LSB: Microsoft Azure Linux Agen

After several times of restart I see:
$ ps aux | grep waagent
root       454  0.0  0.4  48700 14780 ?        S    10:26   0:00 python /usr/sbin/waagent -daemon
root      2902  0.0  0.4  48588 14940 ?        S    10:45   0:00 python /usr/sbin/waagent -daemon
root      3029  0.0  0.4  48588 14916 ?        S    10:45   0:00 python /usr/sbin/waagent -daemon
root      3073  0.0  0.4  48588 14744 ?        S    10:45   0:00 python /usr/sbin/waagent -daemon
root      3215  0.0  0.4  48588 14840 ?        S    10:46   0:00 python /usr/sbin/waagent -daemon
root      5586  0.5  0.4 200768 15632 ?        Sl   11:06   0:00 python -u /usr/sbin/waagent -run-exthandlers
root      5593  0.5  0.4 200768 15192 ?        Sl   11:06   0:00 python -u /usr/sbin/waagent -run-exthandlers
root      5698  0.5  0.4 200768 15268 ?        Sl   11:07   0:00 python -u /usr/sbin/waagent -run-exthandlers
root      5705  0.7  0.4 200768 15416 ?        Sl   11:07   0:00 python -u /usr/sbin/waagent -run-exthandlers
root      5811  0.0  0.0  13180   992 pts/0    S+   11:08   0:00 grep --colour=auto waagent

And waagent.log is appending by strings
$ tail -f /var/log/waagent.log
2017/06/26 10:46:44.220046 INFO WALinuxAgent-2.2.14 waiting for orphan process 2912 to terminate
2017/06/26 10:46:45.000297 INFO WALinuxAgent-2.2.14 waiting for orphan process 3034 to terminate
2017/06/26 10:46:46.935574 INFO WALinuxAgent-2.2.14 waiting for orphan process 3220 to terminate
2017/06/26 10:46:46.992809 INFO WALinuxAgent-2.2.14 waiting for orphan process 3078 to terminate
2017/06/26 10:46:47.237880 INFO WALinuxAgent-2.2.14 waiting for orphan process 2912 to terminate
2017/06/26 10:46:48.011339 INFO WALinuxAgent-2.2.14 waiting for orphan process 3034 to terminate
2017/06/26 10:46:49.948442 INFO WALinuxAgent-2.2.14 waiting for orphan process 3220 to terminate
2017/06/26 10:46:50.007244 INFO WALinuxAgent-2.2.14 waiting for orphan process 3078 to terminate

I think it is not correct behavior

**Comment by beelesnik** [comment]
The behavior of walinuxagent 2.2.14 is the same for clean Debian 8 from Azure (when I remove 2.2.2 and install 2.2.14 from github) and for my customized Debian 8 system.

**Comment by brendandixon** [comment]
@beelesnik The agent runs fine on Debian 8 when correctly installed. We do *not* recommend installing directly from GitHub as each distribution vendor makes modifications for the agent to correctly run on their systems. As output below shows, when correctly installed, the agent operates as expected on Debian 8:

```
root@d8:/home/azlinux/WALinuxAgent# systemctl status walinuxagent
● walinuxagent.service - Microsft Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled)
   Active: active (running) since Mon 2017-06-26 17:17:05 UTC; 2s ago
 Main PID: 9077 (python3)
   CGroup: /system.slice/walinuxagent.service
           ├─9077 python3 /usr/sbin/waagent -daemon
           └─9087 python3 -u /usr/sbin/waagent -run-exthandlers

Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.633848 INFO Agent WALinuxAgent-2.2.14 is running as the goal state agent
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.658219 INFO Detect protocol endpoints
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.668281 INFO Clean protocol
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.681983 INFO WireServer endpoint is not found. Rerun dhcp handler
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.696946 INFO Test for route to 168.63.129.16
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.709984 INFO Route to 168.63.129.16 exists
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.720338 INFO Wire server endpoint:168.63.129.16
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.745870 INFO Fabric preferred wire protocol version:2015-04-05
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.763539 INFO Wire protocol version:2012-11-30
Jun 26 17:17:06 d8 waagent[9077]: 2017/06/26 17:17:06.773895 WARNING Server preferred version:2015-04-05
root@d8:/home/azlinux/WALinuxAgent# systemctl restart walinuxagent
root@d8:/home/azlinux/WALinuxAgent# systemctl status walinuxagent
● walinuxagent.service - Microsft Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled)
   Active: active (running) since Mon 2017-06-26 17:17:20 UTC; 1s ago
 Main PID: 9112 (python3)
   CGroup: /system.slice/walinuxagent.service
           ├─9112 python3 /usr/sbin/waagent -daemon
           └─9124 python3 -u /usr/sbin/waagent -run-exthandlers

Jun 26 17:17:20 d8 waagent[9112]: 2017/06/26 17:17:20.864634 INFO Agent WALinuxAgent-2.2.14 is running as the goal state agent
Jun 26 17:17:20 d8 waagent[9112]: 2017/06/26 17:17:20.887404 INFO Detect protocol endpoints
Jun 26 17:17:20 d8 waagent[9112]: 2017/06/26 17:17:20.896914 INFO Clean protocol
Jun 26 17:17:20 d8 waagent[9112]: 2017/06/26 17:17:20.910211 INFO WireServer endpoint is not found. Rerun dhcp handler
Jun 26 17:17:21 d8 waagent[9112]: 2017/06/26 17:17:20.925347 INFO Test for route to 168.63.129.16
Jun 26 17:17:21 d8 waagent[9112]: 2017/06/26 17:17:20.936441 INFO Route to 168.63.129.16 exists
Jun 26 17:17:21 d8 waagent[9112]: 2017/06/26 17:17:20.948547 INFO Wire server endpoint:168.63.129.16
Jun 26 17:17:21 d8 waagent[9112]: 2017/06/26 17:17:20.969946 INFO Fabric preferred wire protocol version:2015-04-05
Jun 26 17:17:21 d8 waagent[9112]: 2017/06/26 17:17:20.988807 INFO Wire protocol version:2012-11-30
Jun 26 17:17:21 d8 waagent[9112]: 2017/06/26 17:17:20.995171 WARNING Server preferred version:2015-04-05
```

Notice, when correctly installed, the agent on Debian 8 uses **Python3** and not Python2:

```
root@d8:/home/azlinux/WALinuxAgent# waagent --version
WALinuxAgent-2.2.14 running on debian 8.8
Python: 3.4.2
Goal state agent: 2.2.14
```

I suspect this (part) of your problem: Your output above clearly shows the agent you installed running under Python2. Installing the agent under Python3 requires modifying files (e.g., `/usr/sbin/waagent`) *after* installing with Python3 PIP.

I wish you all the best, but we cannot support hand installations for these reasons.
