### ISSUE TITLE
Standard walinuxagent for Debian 8 could not start after adding LDAP authentication

### ISSUE THREAD

**Issue by beelesnik** [Azure/WALinuxAgent#788]
Good day.
As You know I have created some tickets:
https://github.com/Azure/WALinuxAgent/issues/767
https://github.com/Azure/WALinuxAgent/issues/773
https://github.com/Azure/WALinuxAgent/issues/787
And You closed all of them. Ok

Now I have such question.
I created VM from standard Debian 8 image in Azure. Walinuxagent works well.  I added only Logs.Verbose=y in configuration file.
After I set up LDAP authentication walinuxagent is not working at all.
This is information about agent on my system:
# waagent -version
WALinuxAgent-2.2.2 running on debian 8.8
Python: 3.4.2
Goal state agent: 2.2.2
# systemctl status walinuxagent
● walinuxagent.service - Microsft Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; enabled)
   Active: inactive (dead)
# tail -n 50 /var/log/waagent.log
2017/06/27 07:03:48.606613 VERBOSE Get extension handler config
2017/06/27 07:03:48.615327 VERBOSE HTTP connection [GET] [/machine/?comp=goalstate] [None] [{'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent'}]
2017/06/27 07:03:48.635686 VERBOSE HTTP response status: [200]
2017/06/27 07:03:48.644167 VERBOSE Load GoalState.xml
2017/06/27 07:03:48.652640 VERBOSE Handle extensions updates for incarnation 2debug2: channel 0: window 999039 sent adjust 49537
2017/06/27 07:03:48.660811 VERBOSE No extension handler config found
2017/06/27 07:03:48.668279 VERBOSE Report vm agent status
2017/06/27 07:03:48.674970 VERBOSE Prepare status blob
2017/06/27 07:03:48.681192 VERBOSE Put page blob
2017/06/27 07:03:48.687158 VERBOSE HTTP connection [PUT] [/$system/debian-lsn.eb5affa7-5e37-41ce-b51f-8ae3d0172ef5.status?sv=2016-05-31&sr=b&sk=system-1&sig=Mp7VzVlDVqSG6l3wkilhuFHrqcfBZIUmvoCSQnRo%2fvw%3d&se=9999-01-01T00%3a00%3a00Z&sp=rw] [] [{'x-ms-date': '2017-06-27T07:03:48Z', 'x-ms-blob-content-length': '512', 'Content-Length': '0', 'x-ms-blob-type': 'PageBlob', 'x-ms-version': '2014-02-14'}]
2017/06/27 07:03:48.734625 VERBOSE HTTP response status: [201]
2017/06/27 07:03:48.741050 VERBOSE Upload page blob
2017/06/27 07:03:48.748296 VERBOSE HTTP connection [PUT] [/$system/debian-lsn.eb5affa7-5e37-41ce-b51f-8ae3d0172ef5.status?sv=2016-05-31&sr=b&sk=system-1&sig=Mp7VzVlDVqSG6l3wkilhuFHrqcfBZIUmvoCSQnRo%2fvw%3d&se=9999-01-01T00%3a00%3a00Z&sp=rw&comp=page] [<memory at 0x7f5a308cb818>] [{'x-ms-date': '2017-06-27T07:03:48Z', 'x-ms-version': '2014-02-14', 'Content-Length': '512', 'x-ms-range': 'bytes=0-511', 'x-ms-page-write': 'update'}]
2017/06/27 07:03:48.854198 VERBOSE HTTP response status: [201]
2017/06/27 07:03:48.861351 VERBOSE Completed vm agent status report
2017/06/27 07:03:48.869276 VERBOSE Instantiating Agent WALinuxAgent-2.2.13 from disk
2017/06/27 07:03:48.878059 VERBOSE Agent WALinuxAgent-2.2.13 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/27 07:03:48.889744 VERBOSE Ensuring Agent WALinuxAgent-2.2.13 is downloaded
2017/06/27 07:03:48.898466 VERBOSE Agent WALinuxAgent-2.2.13 was previously downloaded - skipping download
2017/06/27 07:03:48.929040 VERBOSE Agent WALinuxAgent-2.2.13 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.13/HandlerManifest.json
2017/06/27 07:03:48.947522 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.13 HandlerManifest.json: {'handlerManifest': {'installCommand': '', 'rebootAfterInstall': False, 'reportHeartbeat': False, 'updateCommand': '', 'uninstallCommand': '', 'enableCommand': 'python -u bin/WALinuxAgent-2.2.13-py2.7.egg -run-exthandlers', 'disableCommand': ''}, 'name': 'WALinuxAgent', 'version': 1.0}
2017/06/27 07:03:48.989882 VERBOSE Instantiating Agent WALinuxAgent-2.2.10 from disk
2017/06/27 07:03:48.999073 VERBOSE Agent WALinuxAgent-2.2.10 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/27 07:03:49.012795 VERBOSE Ensuring Agent WALinuxAgent-2.2.10 is downloaded
2017/06/27 07:03:49.021698 VERBOSE Agent WALinuxAgent-2.2.10 was previously downloaded - skipping download
2017/06/27 07:03:49.032724 VERBOSE Agent WALinuxAgent-2.2.10 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.10/HandlerManifest.json
2017/06/27 07:03:49.047067 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.10 HandlerManifest.json: {'handlerManifest': {'installCommand': '', 'rebootAfterInstall': False, 'reportHeartbeat': False, 'updateCommand': '', 'uninstallCommand': '', 'enableCommand': 'python -u bin/WALinuxAgent-2.2.10-py2.7.egg -run-exthandlers', 'disableCommand': ''}, 'name': 'WALinuxAgent', 'version': 1.0}
2017/06/27 07:03:49.099969 VERBOSE Instantiating Agent WALinuxAgent-2.2.8 from disk
2017/06/27 07:03:49.109363 VERBOSE Agent WALinuxAgent-2.2.8 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/27 07:03:49.123399 VERBOSE Ensuring Agent WALinuxAgent-2.2.8 is downloaded
2017/06/27 07:03:49.132005 VERBOSE Agent WALinuxAgent-2.2.8 was previously downloaded - skipping download
2017/06/27 07:03:49.142434 VERBOSE Agent WALinuxAgent-2.2.8 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.8/HandlerManifest.json
2017/06/27 07:03:49.157363 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.8 HandlerManifest.json: {'handlerManifest': {'installCommand': '', 'rebootAfterInstall': False, 'reportHeartbeat': False, 'updateCommand': '', 'uninstallCommand': '', 'enableCommand': 'python -u bin/WALinuxAgent-2.2.8-py2.7.egg -run-exthandlers', 'disableCommand': ''}, 'name': 'WALinuxAgent', 'version': 1.0}
2017/06/27 07:03:49.198388 VERBOSE Instantiating Agent WALinuxAgent-2.2.12 from disk
2017/06/27 07:03:49.206740 VERBOSE Agent WALinuxAgent-2.2.12 error state: Last Failure: 0.0, Total Failures: 0, Fatal: False
2017/06/27 07:03:49.218252 VERBOSE Ensuring Agent WALinuxAgent-2.2.12 is downloaded
2017/06/27 07:03:49.226621 VERBOSE Agent WALinuxAgent-2.2.12 was previously downloaded - skipping download
2017/06/27 07:03:49.237101 VERBOSE Agent WALinuxAgent-2.2.12 loaded manifest from /var/lib/waagent/WALinuxAgent-2.2.12/HandlerManifest.json
2017/06/27 07:03:49.283615 VERBOSE Successfully loaded Agent WALinuxAgent-2.2.12 HandlerManifest.json: {'handlerManifest': {'installCommand': '', 'rebootAfterInstall': False, 'reportHeartbeat': False, 'updateCommand': '', 'uninstallCommand': '', 'enableCommand': 'python -u bin/WALinuxAgent-2.2.12-py2.7.egg -run-exthandlers', 'disableCommand': ''}, 'name': 'WALinuxAgent', 'version': 1.0}
2017/06/27 07:03:52.146459 INFO Agent WALinuxAgent-2.2.2 forwarding signal 15 to WALinuxAgent-2.2.13
2017/06/27 07:05:31.852936 INFO Activate resource disk
2017/06/27 07:05:31.864036 VERBOSE run cmd 'mount'
2017/06/27 07:05:31.887789 INFO Examining partition table
2017/06/27 07:05:31.905662 VERBOSE run cmd 'blkid -o value -s PTTYPE /dev/sdb'
2017/06/27 07:05:32.011733 INFO GPT not detected, determining filesystem
2017/06/27 07:05:32.050760 VERBOSE run cmd 'blkid -o value -s TYPE /dev/sdb1'
2017/06/27 07:05:32.154005 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/06/27 07:05:32.223783 VERBOSE run cmd 'mount /dev/sdb1 /mnt/resource'
2017/06/27 07:05:01.183831 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/06/27 07:05:19.121403 INFO Provisioning already completed, skipping.

String "2017/06/27 07:03:52.146459 INFO Agent WALinuxAgent-2.2.2 forwarding signal 15 to WALinuxAgent-2.2.13" - is last reboot of VM.
After that walinuxagent could not start on my VM at all.

What should I do to make walinuxagent to work again?

**Comment by brendandixon** [comment]
@beelesnik I really apologize. We are not trying to be difficult. But, we cannot debug a problem for which we have no data. Simply showing us that the agent fails to start (which, by the way, has yet to be clearly shown), is not diagnostic data. Without that data, it is not possible for us to help you to "make walinuxagent work again"; the request is too vague. I've suggested several times that causes outside the agent are likely your issue; I continue to encourage you to investigate those.

Configuring Linux systems, or any modern OS for that matter, is not easy and small changes may have large effects. I am going to have to push this back on you. If you can clearly show that the code of the agent (that is, not the `systemd` unit or the package supplied by the distribution vendor) is at fault we will fix it. (We regularly and quickly address filed bugs.) But until then, there is really nothing that we can do.

I will leave this issue open for a few days, but, without substantive data clearly showing an issue within the agent, we will then close it. I hope you understand. Take care.

**Comment by beelesnik** [comment]
What data do Yoy want to get?
Full waagent.log from creating machine to agent stat fail? OK, I'll give You tomorrow.
Also I could give all messages journal.
Is it enoug?
If it is not, could You say what should I provide?

**Comment by brendandixon** [comment]
@beelesnik If you provide the logs, we'll look at them. But, again, **everything I've seen suggests the error lies outside the agent**. You will likely need to figure this out as it appears to be a system configuration problem.

**Comment by beelesnik** [comment]
As I said I'll give You logs tomorrow.
But it is very general text " lies outside the agent.". I have a big set of software on production servers with such configuration without any issues.
And it is looks strange for me that I could not customize my system with walinuxagent without so fatal intervention to agent functionality.

**Comment by szarkos** [comment]
My two cents on this issue -

The Debian packaging of the Azure agent has split out the agent functions into three systemd services:

    waagent-walinuxagent.service - Azure goalstate agent (vm extension handling, etc.)
    waagent-resourcedisk.service - Format/mount the ephemeral disk
    waagent-provision.service - VM provision service

The waagent-provision.service "wants" the other two services, and those appear to be running successfully.  But the waagent-walinuxagent.service isn't attempting to run at all.

I think the reason is because the walinuxagent service configures "After=multi-user.target," but systemd is looping aggressively because the login service is failing to start.  It's not clear to me that multi-user.target is ever reached, at least it's not in the systemd log.  I would troubleshoot the logind issue and if multi-user target can be reached.

**Comment by brendandixon** [comment]
@szarkos Good find. Thank you. I had not yet had time to look at the files.

@beelesnik Please see Steve's comments above. They make sense, they fit the data, and they align with my expectations (that the problem lies outside the agent). It appears your LDAP configuration is possible incorrect (hence, preventing `logind` from starting). Further, Debian owns the systemd unit for the agent. If you feel it is incorrect, you will need to work with them.

**Comment by beelesnik** [comment]
I found solution myself :)
If you are wondering - this strange behavior of the two services (walinuxagent and systemd-logind) is due to the fact that the package libnss-ldap  that works everywhere breaks these services. We must use an alternative package - libnsss-ldapd.
Why is the configuration that works anywhere (Openstack, Cloudstack, AWS, Oracle Virtualbox and real hardware), fails precisely in the Azure cloud  - this is a question for the company Microsoft.
