### ISSUE TITLE
Python bycode files created when waagent and waagent2.0 sourced as libraries

### ISSUE THREAD

**Issue by szarkos** [Azure/WALinuxAgent#789]
When VM extensions source waagent and waagent2.0, Python creates bytcode files such as /usr/sbin/waagentc and /usr/sbin/waagent2.0c [1].  Ideally any libraries should be moved to /usr/lib/python*/ to avoid polluting /usr/sbin with these files, or another option is to configure Python to not create those files when sourcing modules.

One way to do this is to set the environment variable "PYTHONDONTWRITEBYTECODE=1".  Since it's usually the VM extension that sources these files as libraries we'd need to make sure to pass this environment variable to the extension subprocess.

Another option may be to add "sys.dont_write_bytecode=True" into the waagent and/or waagent2.0 code directly.  I haven't done any testing yet to see which approach might work best.

[1]: https://github.com/Azure/azure-linux-extensions/tree/master/Utils

**Comment by brendandixon** [comment]
@szarkos Moving those files at this point will break extensions (as Debian is finding); that is a very poor customer experience. We could not emit the byte code, but an environment variable is too wide scope: We would want to only not emit the byte code for the files in `/usr/sbin/` vs. all Python files (e.g., extension code).

@waldiTM My understanding is that this matters a good deal to Debian. Would it make most sense for Debian to modify the package created install the agent vs. changing the agent behavior of all installations?

**Comment by brendandixon** [comment]
@szarkos We believe that distribution vendors can make the changes necessary in their packages to eliminate the byte code files. That is better and safer than making a sweeping change to the agent.

**Comment by szarkos** [comment]
@brendandixon - can we then provide information about the recommended changes they need to make to their package to resolve this issue?

This bug came up because a distribution vendor *did* take action to fix this issue.  Removing the waagent2.0 file is one such solution as it is old code.  Another solution is moving waagent2.0 to /usr/lib/python since it does not belong in /usr/sbin.  Either option would then impact core Azure services.  Are you sure you want distribution vendors making these decisions on Azure's behalf?

**Comment by brendandixon** [comment]
@szarkos There are other solutions, such as the environment variable you mentioned above. Additionally, @boumenot recently pushed a change (https://github.com/Azure/azure-linux-extensions/pull/424) to the extension we own that removes the dependency on `/etc/waagent2.0`.

**Comment by waldiTM** [comment]
@brendandixon This code is in the extension handler part, which is updated. So to fix this in the package I have to disable the update mechanism.

**Comment by brendandixon** [comment]
@waldiTM I didn't quite follow your explanation. I don't believe you need to disable auto-update. I was suggesting, only, that you update the installed package (which auto-update never affects).

**Comment by waldiTM** [comment]
@brendandixon No, you said that I should fix the code in the package. This means I need to actually control which code is run in the extension handler, which means I have to use the packaged code and not the one provided via the auto-update.

**Comment by waldiTM** [comment]
@brendandixon Okay, I'll blacklist all agent and therefor extension-handler code from updates.

**Comment by brendandixon** [comment]
@waldiTM What do you mean by "blacklist" the agent from updates? I don't believe disabling updates benefits Debian or Azure customers. Perhaps my earlier suggestion was unclear.

Here's what I propose: You could, in the package deployed to the repository, add the environment variable `PYTHONDONTWRITEBYTECODE=1`. Doing so would disable byte-code generation for the agent and all loaded code, including extensions and auto-updates.

Further, a recent pull request (https://github.com/Azure/azure-linux-extensions/pull/424) modifies the search paths so that extensions requiring access to `waagent2.0` code will find their local copy (removing their dependence on the version in `/etc`).
