### ISSUE TITLE
Prevent bloating sudoers waagent when agent has problem

### ISSUE THREAD

**Issue by ChrisJergens** [Azure/WALinuxAgent#791]
I'm having a separate issue with waagent service on Centos 6.7, causing the daemon to continuously restart.
INFO Sleep 15 seconds and restart daemon

And every time it goes through
INFO Create user account if not exists
INFO User exampleuser already exists, skip useradd
INFO Set user password.
INFO Configure sudoer

And /etc/sudoers.d/waagent contains many hundreds of duplicate entries now, one for every daemon start.
Perhaps there needs to be logic to prevent this.

**Comment by brendandixon** [comment]
@ChrisJergens Agreed.

**Comment by hglkrijger** [comment]
Fix merged
