### ISSUE TITLE
Evaluate failing provisioning if RDMA is requested on a non-HPC image

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#795]
Consider adding to provisioning a quick check to ensure that an HPC image is running on HPC hardware. Full setup of RDMA will continue post-provisioning, but failing early will give better feedback.

**Comment by smith1511** [comment]
Please dont do this.  We have customers that run MPI applications on single node setups, but still require the Intel MPI runtime on the HPC images.  These customers also require the ability to burst to HPC hardware when larger jobs come in and hence need a single implementation that will run on HPC and non-HPC VMs.

**Comment by brendandixon** [comment]
Closing in favor of #841
