### ISSUE TITLE
Support Ubuntu RDMA driver update

### ISSUE THREAD

**Issue by longlimsft** [Azure/WALinuxAgent#798]
On VM boot, RDMA driver is checked, updated and loaded based on host ND version.

Currently we support SLES12 and CentOS for this feature. In Ubuntu, this step is skipped and we always use the RDMA driver preinstalled.

Ubuntu should also be supported to the same feature set as SLES and CentOS.

**Comment by brendandixon** [comment]
@longlimsft It is a good idea, but updating the package is vendor-specific. Do you know how to update it for Ubuntu images? If so, we'll happily accept a pull request.

**Comment by brendandixon** [comment]
Addressed by #836
