### ISSUE TITLE
[2.2.14] WALA provision failed even if cloud-init services are not enabled

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#806]
Description:
If cloud-init package is installed in the VM, no matter if it is enabled, the /etc/NetworkManager/dispatcher.d/cloud-init-azure-hook script(This script is inside the cloud-init package) will call cloud-init while VM booting. WALA detects the cloud-init process and stop provisioning. 

WALA version: 2.2.14
RHEL version: RHEL-7.4
cloud-init version: cloud-init-0.7.9-9

Steps:
1. Install cloud-init package in VM, disable related services:
systemctl disable cloud-{init-local,init,config,final}
2. Deprovision the VM and use this os disk to create a new VM
3. Check VM status

Actual result:
Provision failed. 
/var/log/waagent.log:
2017/07/21 02:46:16.396313 INFO Running default provisioning handler
2017/07/21 02:46:16.424520 ERROR cloud-init is running [PID 673, /usr/bin/python^@/usr/bin/cloud-init^@dhclient-hook^@up^@eth0^@]
...
2017/07/21 02:46:24.561451 ERROR Event: name=WALinuxAgent, op=Provision, message=[000004] cloud-init appears to be running, this is not expected, cannot continue
2017/07/21 02:46:24.569447 ERROR Provisioning failed: [000004] cloud-init appears to be running, this is not expected, cannot continue

Expect result:
WALA can provision VM successfully if cloud-init services are disabled.

**Comment by brendandixon** [comment]
@yuxisun1217 Hmm, I doubt there is another means by which the agent can determine, in a cross-distribution friendly way, if `cloud-init` is running. Any suggestions?

**Comment by yuxisun1217** [comment]
Hi @brendandixon ,
We discuss again and actually we think the it will be the best solution if cloud-init can have a change that never call the cloud-init process if it is not enabled. We'll also discuss with our cloud-init team and I'll update status here later. Thanks!

**Comment by brendandixon** [comment]
@yuxisun1217 Any updates?

**Comment by yuxisun1217** [comment]
Hi @brendandixon ,

I'm so sorry I didn't notice this. I've already opened a bug to our cloud-init team, and it seems that the fix is call cloud-init earlier so that it is already finished when WALA check the cloud-init pid. I worried about that if this fix can absolutely prevent this issue.  
From my side, is it possible to check cloud-init services enable status instead of pid? I think it might be a safe way to catch the cloud-init usage. Thanks!
Here's the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1474226
Currently the comments are private. I'll ask if we can share the details tomorrow. Thanks!

**Comment by brendandixon** [comment]
@tomasquith Ensure to use v2.2.10+ of the agent. We've made many changes; some affecting provisioning and `cloud-init`.

@yuxisun1217 I do not care for how the agent presently checks for `cloud-init`. If you have another, better suggestion, we'll gladly consider it!

**Comment by yuxisun1217** [comment]
Hi @brendandixon ,

OK. Maybe the best fix is on cloud-init side. We'll track the cloud-init issue and I'll update here if it is fixed.
Please close this issue. Thank you for your response!

**Comment by tomasquith** [comment]
Thanks for the information @brendandixon, Why is cloud-init now disabled? Does cloud-init run after the waagent tasks?

@yuxisun1217 @brendandixon Is there an ETA for this? Currently i'm having to rely on the RogueWave CentOS 7.3 image from last year.

**Comment by brendandixon** [comment]
@tomasquith Until recently, the Linux Agent has supported `cloud-init` only on Ubuntu images. In release v2.2.11 we opened up enabling `cloud-init` on any distribution provided the `Provisioning.UseCloudInit` option in `/etc/waagent.conf` is set to `y`. While we do not officially support (yet) `cloud-init` on distributions other than Ubuntu, we are heading in that direction.

@yuxisun1217 Thank you, closing.

**Comment by brendandixon** [comment]
@tomasquith I *believe* RedHat 7.3 just released with `cloud-init` installed, but not on by default. You'll have to check with your distribution vendor as they need to package it into their images.
