### ISSUE TITLE
PyPI Package

### ISSUE THREAD

**Issue by mxplusb** [Azure/WALinuxAgent#810]
Would it be possible to get a `setup.cfg` created for this package so it can be added to the [Python PyPI](https://pypi.python.org/pypi) repository? I have a use case where I want to import some features for an internal service to come up with the proper configurations.

I would also like to be able to vendor the package so I can include it in my code base.

**Comment by brendandixon** [comment]
@mxplusb If you would like to submit a pull request with one, we'll consider adding it. The normal distribution path is through distribution (e.g., Ubuntu) repositories. We need to be careful to not complicate that path.

**Comment by mxplusb** [comment]
@brendandixon I agree that we should not complicate the standard distribution path.

While I can create a PR, with a PyPI package, it requires a user on PyPI, and uses said user's authentication for the upload configuration. [Here](http://peterdowns.com/posts/first-time-with-pypi.html) is an example of how to upload a package.

What I can do, is add a hook as part of the install script, which would generate a `setup.cfg` and read credentials from the user responsible as environment variables. I'm not sure this is the right approach.

The other option is to let this project's owner privately create a `setup.cfg` file and add it within the `.gitignore` for the projecct, so there's no risk of those credentials being exposed. Then the project owner can upload the project to PyPI as part of this project's release cycle. I believe this is the safest method.

In all honesty, I could do this myself as I have a PyPI user, even without a PR, but it's not my project and I didn't want to accept responsibility without explicit permission as I am not a maintainer. :)

**Comment by brendandixon** [comment]
@mxplusb At this time, adding a PyPl package to the project is outside our plans and scope.
