### ISSUE TITLE
WALA should contine the provisioning with any available network connections

### ISSUE THREAD

**Issue by simonxiaoss** [Azure/WALinuxAgent#829]
Looks like current code will look for a primary interface and stick on that for all the following provisioning work. If the primary interface is down during the provisioning, the provisioning will fail accordingly, even there are other available networks.

We hope WALA could continue the provisioning in the above situation and finish that so that user can connect to this VM from ssh/outside later to debug what happened to the primary interface.

**Comment by brendandixon** [comment]
@simonxiaoss The primary interface is assigned to the VM by Azure (via Hyper-V). If it is missing, all bets are off. The agent should fail in that case. We have other tools by which we can analyze these failures.
