### ISSUE TITLE
The specified blob does not exist

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#833]
Hi @brendandixon ,
The error below show up from time to time in the waagent.log 
Do you know what is causing the  error, what's its  impact and if there is anything that can be done to prevent it from occurring again ? Also is it related to the storage backend ?
Thanks,
Johan

Full log: [waagent.log](https://gist.githubusercontent.com/johanburati/5f57971a4f7c14f0bb26e66713d91842/raw/a8690fc2cb4a79e0998160512591ff10f0ed3ee6/waagent.log)
```
2017/08/03 14:43:51.650589 WARNING Could not fetch https://rdfepirv2os1prdstr01.blob.core.windows.net/80afa74b14194a679c6347109557b7ee/Microsoft.Azure.RecoveryServices_VMSnapshotLinux_japanwest_manifest.xml [[404: The specified blob does not exist.] <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:68bcbeea-0001-0043-601b-0cbefd000000
Time:2017-08-03T05:43:51.4391387Z</Message></Error>]
2017/08/03 14:43:51.715995 WARNING Could not fetch http://168.63.129.16:32526/extensionArtifact [[404: Not Found] {
    "errorCode": "The specified blob does not exist.",
    "message": "<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:db06202f-0001-001a-541b-0cbb7b000000
Time:2017-08-03T05:43:51.1943355Z</Message></Error>",
    "details": ""
}]
2017/08/03 14:43:51.754204 WARNING Forcing update of goal state
2017/08/03 15:13:35.116073 WARNING Forcing update of goal state
```

**Comment by brendandixon** [comment]
@johanburati It means the agent was unable to retrieve the Xml manifest (which lists the versions available) for the Microsoft.Azure.RecoveryServices_VMSnapshotLinux extension. Unless the message recurred after the subsequent GoalState fetch (and the logs show no further errors), it may be safely ignored.

We monitor these failures for trends. At present, a low-level of transient failures occurs which the agent handles successfully.
