### ISSUE TITLE
Agent should auto-detect IB interface and attempt to configure RDMA driver

### ISSUE THREAD

**Issue by szarkos** [Azure/WALinuxAgent#841]
Today the agent will only attempt to configure the IB/RDMA interface if OS.EnableRDMA is set to 'y' in waagent.conf.  Ideally this condition is auto-detected and auto-configured.  This would simplify image generation and deployment, as currently enabling RDMA requires custom images.

**Options to detect IB interface**
  - Check if an ND driver version was passed via KVP (see get_rdma_version()).  This data is only populated on HPC VM sizes.
  - Process SharedConfig for 'rdmaIPv4Address'.  This data is only populated on HPC VM sizes.
  - Another possibility would be to modify IMDS to provide information on the VM type, but HPC sizes are also available via classic VMs so this may not be the best option.

**Open questions**
  - What to do about failure conditions - fail provisioning?
  - How to communicate RDMA configuration failure to the user?

**Comment by szarkos** [comment]
This is a feature request, of course, but I guess I don't have permission to modify labels.

**Comment by szarkos** [comment]
We can query vmbus via /sys and check the class_id for the presence of an ND interface.  The following type of test will detect if a VM in Azure is enabled with RDMA:

if ( grep -qr 8c2eaf3d-32a7-4b09-ab99-bd1f1c86b501 /sys/bus/vmbus/devices/*/class_id ) ; then
	# RDMA enabled
else
	# RDMA not enabled
fi

The GUID above is defined in hyperv.h for the network direct driver: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/hyperv.h?h=v4.13#n1308

Note that this test will work even if the hv_network_direct kernel module is not loaded yet, which is key since we want to detect that RDMA is enabled before querying the KVP value to determine the ND driver version and load the correct module.

**Comment by szarkos** [comment]
The current proposal is to enable a new configuration option, "OS.EnableRDMA=auto".  This will enable a test similar to above where the agent will automatically detect the existence of an ND enabled device and configure it if found.

In this case the agent default would remain "OS.EnableRDMA=n," but distros could feasibly set this to "auto" in their packages.

**Comment by hmeiland** [comment]
In the initial comment, it is mentioned that RDMA can only be enabled in a custom image; however in a stock image, by changing the config file and restarting the waagent, RDMA can also be enabled; without a reboot. (tested on Ubuntu 16.04)

**Comment by szarkos** [comment]
The point is that you'll want this to happen automatically, i.e. provision a 100-node cluster using a single image and have RDMA configured automatically.  You cannot do this currently unless you spin up an instance, modify waagent.conf and then deprovision/capture the image.  This is one reason why CentOS and SLES HPC images are a separate sku.

**Comment by hglkrijger** [comment]
Internally we have agreed the direction to move in is for RDMA to be outside of the agent, so we are not going to take this change on. We will take a PR if @longlimsft or someone else would like to submit.
