### ISSUE TITLE
python version problem

### ISSUE THREAD

**Issue by lwmonster** [Azure/WALinuxAgent#842]
In REQUIREMENT, you write python2.6+, and my python is python 2.7.10, but when checking walinuxagent status by command:
```
service walinuxagent status
```

it shows the following error:

```
walinuxagent.service - Azure Linux Agent
   Loaded: loaded (/lib/systemd/system/walinuxagent.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit) since 三 2017-08-16 17:37:56 CST; 1s ago
  Process: 24900 ExecStart=/usr/bin/python3 -u /usr/sbin/waagent -daemon (code=exited, status=1/FAILURE)
 Main PID: 24900 (code=exited, status=1/FAILURE)

```      

Why it use python3 ?  How to solve it ?

**Comment by brendandixon** [comment]
@lwmonster When both Python2 and Python3 are installed, how you install the Linux Agent matters. This is why we *strongly* suggest you only install the agent as a package from your distribution vendor's repository (e.g., for Ubuntu use `sudo apt-get install walinuxagent`).

If you install manually using PIP, you *must* ensure that you use the PIP associated with your default Python. Other changes may also be necessary (e.g., ensuring the shebang (`#!`) portion of `/usr/sbin/waagent` is also correct).
