### ISSUE TITLE
[2.2.14.2]  ')' is missed in "show-configuration"

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#845]
Hi there,

azurelinuxagent/agent.py Line#208: 
        elif re.match("^([-/]*show-configuration", a):
Seems should be:
        elif re.match("^([-/]*)show-configuration", a):

**Comment by brendandixon** [comment]
@yuxisun1217 Yikes! Good catch. This code is hard to test...

**Comment by brendandixon** [comment]
Addressed by #848
