### ISSUE TITLE
[2.2.14.2] How does wala get proxy environment variables?

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#846]
Hi there,

In #783 ,wala should be able to read http_proxy or https_proxy environment variables. But if I set "http_proxy" in /etc/profile, the os.environ in wala cannot get it. It seems that the process that managed by systemd cannot read the system environment variables. 
```
# cat /proc/[pid of waagent]/environ
LANG=en_US.UTF-8PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```

Currently I found that write the environment variable into waagent.service can make the wala get it, like:
```
[Service]
Environment=http_proxy=172.20.0.254:3128
```
Or set system.conf:
```
# vi /etc/systemd/system.conf
DefaultEnvironment=http_proxy=172.20.0.254:3128
```

Is this what this feature supposed to do? Thanks!

**Comment by brendandixon** [comment]
@yuxisun1217 The feature only means that, if `http_proxy` or `https_proxy` are in the current environment, the agent will use the values. How the environment within which the agent runs gets established is outside of our control and could affect such things as the systemd unit that starts the agent. Ok?

**Comment by yuxisun1217** [comment]
Got it. Thank you @brendandixon !
