### ISSUE TITLE
Waagent deprovision should not be messing with the cloudinit directories

### ISSUE THREAD

**Issue by dsutherland1492** [Azure/WALinuxAgent#855]
Deleting and changing the files under /var/lib/cloud upon deprovision fundamentally breaks how per-once and per-instance works.   You also lose the ability to track instances created from the original image.  At the minimum, there should be a flag to turn this functionality completely off.

**Comment by szarkos** [comment]
Can you clarify your scenario a bit more?  Deprovisioning assumes that you want to create an "image" from the VM, which could then be used to provision any number of new VMs with their own new cloud-config.  For snapshots, etc. you generally wouldn't deprovision a specialized image.

**Comment by dsutherland1492** [comment]
Correct, but let's say you make a base image from your current machine and want to use per-once on the first instance of a machine provisoned from that image.  An example situation would be where your image is going to be deployed to the Azure Marketplace.  Ultimately, you need to use waagent deprovision before doing that but this would inevitability destroy anything in the per-once directory.

**Comment by szarkos** [comment]
I think the primary reasoning was just to clean /var/lib/cloud/instances/<foo> to remove obsolete user data (customdata).  Perhaps we can discuss with the cloud-init team what's safe to remove here.

**Comment by dsutherland1492** [comment]
The instances folder keeps tabs of what machines were previously
instaniated by cloud-init.  Clearing that directory would impact the
per-once scripts by making they run on each new instance rather than just
on the first instance.

**Comment by hglkrijger** [comment]
I agree, we should leave the cloud-init directories alone during deprovision.

**Comment by szarkos** [comment]
Cleaning stale user data is still a valid thing to do at deprovisioning.  I spoke with Scott Moser during the Cloud-Init Summit a couple weeks ago.  He said he will provide us with some details about what could be cleaned here without impacting per-once/per-instance scripts.  I can post that here once we have those details.

He also mentioned a cloud-init clean utility that apparently is on their backlog, which could replace this at some point (and should have various parameters to determine what to clean, etc.).

**Comment by brendandixon** [comment]
@szarkos Did you get the details of what is safe to remove?

**Comment by szarkos** [comment]
Not yet.  Scott thought the issue is worthy of wider discussion and recommended we discuss the issue on the cloud-init mailing list, which I've started now.

**Comment by hglkrijger** [comment]
@szarkos - any updates on the guidance here?

**Comment by hglkrijger** [comment]
@szarkos, any updates?

**Comment by hglkrijger** [comment]
I am going to remove all cloud-init directories from cleanup.

**Comment by Deshke** [comment]
ehm, this  seems broken. if you create a vm image from a instance where cloud-init has been running, cloud init will refuse to run the custom-data from the new instance.

i've tried to run `cloud-init clean -l -s` but no luck
