### ISSUE TITLE
WALA behavior on Oracle Linux seems different than described in instruction

### ISSUE THREAD

**Issue by GoreMaria** [Azure/WALinuxAgent#861]
On Oracle Linux 7.3 we have a problem with installing extensions.
The instruction says the installation should be completed in 15 minutes.
Because this distribution does not include perl, we install it. This increases the time to install the extension.
WALA through 5 minutes stops installation on timeout. Then starts the installation again.
There may be a problem with the version of WALA. The 2.0.15 version is installed on this distribution.
There is no problem with the other distributions of Linux. The version of Wala is newer than 2.0.15.
Link on distributive: https://portal.azure.com/#create/Oracle.OracleLinux73000-ARM
Link to instruction: https://github.com/Azure/azure-linux-extensions/blob/master/docs/design-details.md

**Comment by brendandixon** [comment]
@GoreMaria v2.0.15 is quite old and you'll see improved behavior by updating. The latest agents (e.g., v2.2.10) do honor the published timeouts (15 minutes for install, 5 minutes for enable). Oracle has made these newer versions available in their repository. I hope this helps!

**Comment by GoreMaria** [comment]
@brendandixon thank you! It helps a little, but extension installation status is incorrect. It's not clear how much time WALA allocates for "installation" and "enable" processes? For windows it's 15 minutes for installation and 5 minutes to enable. What about WALA?

**Comment by brendandixon** [comment]
@GoreMaria The Linux Agent (WALA) uses the same times as the Windows agent. Again, you really should upgrade from 2.0.15 to a more current version (2.2.10); you'll see much better behavior.
