### ISSUE TITLE
Excessive Logging when Agent Version is Blacklisted

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#862]
I am noticing an excessive amount of logging when an agent version has been blacklisted.  Log messages are emitted once every 3 to 5 seconds with the following message.

I noticed this on 2.2.12, so it may already be fixed.

```text
2017/08/24 11:12:51.292124 INFO Agent WALinuxAgent-2.2.13 is blacklisted - skipping download
2017/08/24 11:12:54.848243 INFO Agent WALinuxAgent-2.2.13 is blacklisted - skipping download
2017/08/24 11:12:58.129415 INFO Agent WALinuxAgent-2.2.13 is blacklisted - skipping download
2017/08/24 11:13:01.094124 INFO Agent WALinuxAgent-2.2.13 is blacklisted - skipping download
```

The messages go on, and on.

**Comment by brendandixon** [comment]
@boumenot This entire code path was cleaned up for v.2.2.15. This message no longer occurs.
