### ISSUE TITLE
A centos7 vhd for Microsoft Azure created by using Virtualbox cannot be deployed to a VM (dracut timeout)

### ISSUE THREAD

**Issue by AliceAlbano** [Azure/WALinuxAgent#863]
Hello, 

I have created a centos7 VHD by following the official documentation: https://docs.microsoft.com/fr-fr/azure/virtual-machines/linux/create-upload-centos
I have made all these steps on a fresh-installed centos7 official machine. I uploaded the vhd to Azure ARM, created a VM from it. It stayed in "Creating" for a while, then went to "Failed". The boot diagnostics (in attachement) shows a problem of "dracut timeout".
I have tried to search for this problem on google, but nothing was really helpful.
I have seen in the documentation that the vhd can be created for VBox, but it seems that some steps are missing to make it work, do you have any clues about this ?

Thanks,
Alice

[vhd_upload_centos7head.txt](https://github.com/Azure/WALinuxAgent/files/1255365/vhd_upload_centos7head.txt)

**Comment by brendandixon** [comment]
@AliceAlbano I suggest that you contact Azure support (https://azure.microsoft.com/en-us/support/options/?v=17.33). They have the proper engineers who can best help you. It is, at present, unlikely this is an agent issue. I hope this helps!
