### ISSUE TITLE
[2.2.15] WALA cannot write sudoer string to /etc/sudoers.d/waagent during provisioning

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#868]
Hi there,

/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py Line#284:
fileutil.findstr_in_file(sudoers_wagent, sudoer) is None:
Seems should be:
fileutil.findstr_in_file(sudoers_wagent, sudoer) is False:

Because the return value of fileutil.findstr_in_file() function is True of False, never be None.

**Comment by yuxisun1217** [comment]
It seems that this issue is involved in this fix: [#791] -- Prevent bloating sudoers waagent when agent has problem

**Comment by brendandixon** [comment]
Fixed by #894
