### ISSUE TITLE
[2.2.16] WALA: waiting for orphan process to terminate

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#872]
Backup failed with _UserErrorGuestAgentStatusUnavailable_ error on a Oracle 7.4 Linux server, 
looking at the log it look like WALA was upgrade to 2.2.15 on 2015/09/01 and there are a lot of  _orphan process_ afterward, the problem was eventually solve by rebooting the VM, but the customer want to know why the agent was unavailable after the update. any idea ?

I think it is the same issue as reported in https://github.com/Azure/WALinuxAgent/issues/871, is it possible to determine what was the cause of the error this time ?

## version
```
waagent --version
WALinuxAgent-2.2.0 running on oracle 7.4
Python: 2.7.5
Goal state agent: 2.2.15
```
## log
[waagent.log](https://gist.githubusercontent.com/johanburati/9a1e65f8614eb929f5d1ba04ee949c95/raw/ad961f3e6eaf8ffae4da168a6c30138e8b3113ba/waagent.log)
```
2017/09/01 03:12:02.879583 INFO WALinuxAgent-2.2.15 waiting for orphan process 7585 to terminate
2017/09/02 08:02:51.802805 INFO WALinuxAgent-2.2.15 waiting for orphan process 7585 to terminate
2017/09/02 08:02:54.806330 WARNING WALinuxAgent-2.2.15 forcibly terminated orphan process 7585
2017/09/02 08:02:54.806633 WARNING Exception occurred waiting for orphan agent to terminate: an integer is required

2017/09/03 14:05:13.215487 INFO WALinuxAgent-2.2.15 waiting for orphan process 38515 to terminate
2017/09/04 05:06:18.564377 INFO WALinuxAgent-2.2.15 waiting for orphan process 38515 to terminate
2017/09/04 05:06:21.567953 WARNING WALinuxAgent-2.2.15 forcibly terminated orphan process 38515
2017/09/04 05:06:21.568253 WARNING Exception occurred waiting for orphan agent to terminate: an integer is required

2017/09/02 23:04:06.601263 INFO WALinuxAgent-2.2.15 waiting for orphan process 38491 to terminate
2017/09/03 14:05:10.205177 INFO WALinuxAgent-2.2.15 waiting for orphan process 38491 to terminate
2017/09/03 14:05:13.208885 WARNING WALinuxAgent-2.2.15 forcibly terminated orphan process 38491
2017/09/03 14:05:13.211986 WARNING Exception occurred waiting for orphan agent to terminate: an integer is required
```

**Comment by brendandixon** [comment]
@johanburati The agent runs as a daemon and a child process. These messages occur when the agent has been asked to shutdown and it is waiting for the child process to terminate. The question behind the question to ask, then, is why is the agent being asked to shutdown and restart? That is not common.

**Comment by johanburati** [comment]
thanks @bendandixon, I have the previous [waagent.log]  (https://gist.githubusercontent.com/johanburati/a3aa758bf9568dd99472579282db11ea/raw/c3b98a0a2e0f1dfc7214d6e6e1150e649825436a/waagent.log2).

The problem started to occur after the waagent was upgraded to 2.2.15 and it was fixed by rebooting the server on 9/5, the waagent was upgraded to 2.2.16 after the reboot. 
Apart from the orphan process messages can you tell that something went wrong with the 2.2.15 upgrade from the log ?

**Comment by johanburati** [comment]
Same issue has been reported with 2.2.16

**Comment by brendandixon** [comment]
@johanburati The logs, otherwise, look fine. What's odd is that the code which emits the recurring message also decrements a counter. When the counter is less-than or equal to zero, it kills the errant process and terminates the loop. It's really hard to see why that failed to occur.

**Comment by brendandixon** [comment]
@johanburati The default OS utilities look for a directory under `/proc` with that number (e.g., `/proc/42/`).

**Comment by johanburati** [comment]
@brendandixon the orphan process is one thing but when the problem occur the extensions become unresponsive and the only way we found to get them back working is to reboot the VM which is not ideal. So I would like to keep this issue open until we find the root cause.

**Comment by AidarKh** [comment]
Hi. I have the same issue with WALA after upgrading to version WALinuxAgent-2.2.18 from redhat repo. After restarting WALA during upgrade it doesn't started properly and there is a lot of messages in log file:
2017/12/25 11:39:20.873252 INFO WALinuxAgent-2.2.18 waiting for orphan process 65036 to terminate
I have resolved this issue without reboot by this procedure:
1. stop WALA
2. check that all processes are stopped
3. remove all pid files for waagent process from /var/run
4. start waagent service.
After that waagent has started and it's working as expected.
