### ISSUE TITLE
WALinuxAgent is to set up swap size depending on RAM size

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/WALinuxAgent#881]
WALinuxAgent is to set up swap size depending on RAM size
is it being planned?

**Comment by alexeyshishkin01** [comment]
$ cat /usr/lib/systemd/system/waagent.service
[Unit]
Description=Azure Linux Agent
Wants=network-online.target sshd.service sshd-keygen.service
After=network-online.target

ConditionFileIsExecutable=/usr/sbin/waagent
ConditionPathExists=/etc/waagent.conf

[Service]
Type=simple
ExecStartPre=/usr/bin/cp -f /etc/ovf-env.xml /var/lib/waagent/ovf-env.xml
ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment memtotal=$(expr `cat /proc/meminfo | grep MemTotal | awk '{ print $2 }'` / 1024)"
ExecStartPre=/usr/bin/sed -i "s|ResourceDisk.SwapSizeMB=.*|ResourceDisk.SwapSizeMB=${memtotal}|" /etc/waagent.conf
ExecStart=/usr/bin/python -u /usr/sbin/waagent -daemon
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by hglkrijger** [comment]
We have no plans for changes in this area.
