### ISSUE TITLE
Suggest to remove kdump initramfs file during deprovisioning

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#882]
Hi there,

Currently there's an issue in RHEL-7.4 on-demand image that the old kdump initramfs file in RHEL-7.4 on-demand image doesn't have hyperv drivers so that trigger kdump in MSFT ondemand RHEL7.4 can not generate vmcore file. Here's detail description:
https://bugzilla.redhat.com/show_bug.cgi?id=1489282

The kdump initramfs file will not be replaced if the configuration is not changed. So if there's something wrong with the old kdump initramfs it will impact the kdump feature. Shell wala remove the old kdump initramfs file while deprovisioning?

Thanks!

**Comment by hglkrijger** [comment]
This seems like an image issue - I have added the right folks from our side to the bugzilla issue. Thanks for reporting!
