### ISSUE TITLE
HTTP PUT IOError ('The read operation timed out',)

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/WALinuxAgent#885]
I see the following in /var/log/messages or systemctl -l status waagent:

Sep 16 23:05:50 centos-20170915-ent-vm python[978]: 2017/09/16 23:05:50.388041 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP PUT IOError ('The read operation timed out',)

what does it mean?

how to fix it?

**Comment by hglkrijger** [comment]
There is nothing to fix, this is an information message which indicates there was a network timeout.
