### ISSUE TITLE
"Failed to flush firewall" flood

### ISSUE THREAD

**Issue by enihcam** [Azure/WALinuxAgent#889]
OS: Archlinux

Too many "Failed to flush firewall" warnings. How to disable it? Thanks.

**Comment by hglkrijger** [comment]
Thanks for reporting this. It looks like a bug, which we will need to address in the next release. Out of interest, could you let me know what happens if you run `iptables -t security --flush` on this system?

**Comment by enihcam** [comment]
@hglkrijger The VM is highly customized therefore does not have iptables modules.

> modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.12.13

**Comment by milowe** [comment]
The same log flood for CoreOs as well (Container Linux by CoreOS 1465.8.0 (Ladybug)).
iptables not in use or setup.

**Comment by brendandixon** [comment]
Fixed by #894
