### ISSUE TITLE
[2.2.17] Suggest to remove OS.EnableFirewall if not used

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#890]
Hi there,

It seems that currently the OS.EnableFirewall is not used in the source code. Shell we remove it from waagent.conf to prevent misunderstanding?

Thanks!

**Comment by brendandixon** [comment]
@yuxisun1217 It is our intention to add back the firewall, once we have a better understanding of the impact. I'll leave this configuration setting in-place.
