### ISSUE TITLE
Create a Telemetry Event to Track Custom Data Execution

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#891]
There is no event to track the execution of Custom Data. Executing a script for Custom Data may take a very long time, and we have no insight into this. Please consider creating a event to track this, and the total execution time.  

Does provisioning need to be gated by the execution of a script injected into Custom Data?

**Comment by brendandixon** [comment]
@boumenot We'll consider this for the next release. Any preferences on the event raised and accompanying values? Also, cloud-init provisioned VMs will require another mechanism since the agent, in that case, does not execute the custom data.

**Comment by boumenot** [comment]
I do not have a strong preference.  My first though is simply CustomData.  I don't have anything to add to the message.  The use of this event is more for tracking purposes, and to understand if CustomData is being by our customers.

I already have work items queued up for @paulmey. 😝
