### ISSUE TITLE
Add support for configuring CA certificate authentication - TrustedUserCAKeys

### ISSUE THREAD

**Issue by gregjhogan** [Azure/WALinuxAgent#895]
When I create a VM I want to provide the public CA certificate which allows any user with certificate signed by that CA to authenticate.  This requires setting TrustedUserCAKeys in /etc/ssh/sshd_config.

I believe it is possible to identify when a certificate is a CA cert, and then you could set TrustedUserCAKeys when appropriate without changing the mechanism by which the VM receives public certificate?

Adding support for this makes it significantly easier to manage access to a large fleet of VMs centrally and more securely.  I only want to grant people access to VMs for short periods of time, so normally there would be no valid certificates signed by the CA and therefore normally no one has access.  Then when access is needed I can sign a certificate with the CA which would only be valid for a short period of time.

**Comment by brendandixon** [comment]
@gregjhogan We appreciate the use-case, but such support is outside the design goals of the agent. You are best off implementing it via the CustomScript or similar extension.
