### ISSUE TITLE
End of Line Comments are Not Supported nor Handled

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#896]
If a customer inserts an end-of-line comment in waagent.conf the agent gladly appends it to the current configuration value.  The agent should either support this style of commenting or reject it outright.

```text
# If "None", the system default version is used.
OS.OpensslPath=/var/log/openssl  # private build of OpenSSL
```

Results in a value of "/var/log/openssl # private build of OpenSSL," which is not the intention.

**Comment by brendandixon** [comment]
@boumenot The agent has never supported end-of-line comments. We can look to add minimal support.
