### ISSUE TITLE
/mnt/resource mounting to managed data disk

### ISSUE THREAD

**Issue by dirkslab** [Azure/WALinuxAgent#900]
Good Afternoon,

Hope somebody can point me in the right direction.

I am testing a simple Azure ARM template. Linux scalset of Centos 7.3 servers.
Attaching 2x managed datadisk as part of the deploy.
I am using a extension script to partition and format the disks.
One difference from my usual setup is that I am testing managed datadisks. Not sure if this is a clue. 

Issue:
This is actually and old issue from a few years ago that seems to have come back with a vengeance. 
Occasionally  on deploy the /mnt/resource mounts to /dev/sdd1 instead of the expected /dev/sdb1
This causes my script to fail as it looks for available datadisks to raid.
Looking at /var/log/waagent.log, it does not even seem to attempt to mount /dev/sdb1

> 

2017/10/04 12:18:45.783732 INFO Azure Linux Agent Version:2.2.18
2017/10/04 12:18:45.797623 INFO OS: centos 7.3.1611
2017/10/04 12:18:45.808375 INFO Python: 2.7.5
2017/10/04 12:18:45.824642 INFO Run daemon
2017/10/04 12:18:45.838587 INFO Activate resource disk
2017/10/04 12:18:45.863089 INFO Examining partition table
2017/10/04 12:18:45.932356 INFO GPT not detected, determining filesystem
2017/10/04 12:18:45.964972 INFO sfdisk with --part-type failed [1], retrying wit                                                                                                                                                             h -c
2017/10/04 12:18:45.985087 INFO sfdisk -c -f /dev/sdd 1 -n succeeded
2017/10/04 12:18:45.998576 INFO The partition is formatted with ntfs, updating p                                                                                                                                                             artition type to 83
2017/10/04 12:18:46.024239 INFO sfdisk with --part-type failed [1], retrying wit                                                                                                                                                             h -c
2017/10/04 12:18:46.045130 INFO sfdisk -c  /dev/sdd 1 83 succeeded
2017/10/04 12:18:46.083781 INFO Format partition [mkfs.ext4 -F /dev/sdd1]
2017/10/04 12:18:51.232097 INFO Mount resource disk [mount /dev/sdd1 /mnt/resour                                                                                                                                                             ce]
2017/10/04 12:18:51.580619 INFO Resource disk /dev/sdd is mounted at /mnt/resour                                                                                                                                                             ce with ext4
2017/10/04 12:18:51.601751 INFO Clean protocol
2017/10/04 12:18:51.611511 INFO Running default provisioning handler
2017/10/04 12:18:51.635691 INFO Copying ovf-env.xml
2017/10/04 12:18:51.684105 INFO Successfully mounted dvd
2017/10/04 12:18:51.710789 INFO Detect protocol by file
2017/10/04 12:18:51.716293 INFO Clean protocol
2017/10/04 12:18:51.725693 INFO WireServer endpoint is not found. Rerun dhcp han                                                                                                                                                             dler
2017/10/04 12:18:51.734828 INFO Test for route to 168.63.129.16
2017/10/04 12:18:51.740271 INFO Route to 168.63.129.16 exists
2017/10/04 12:18:51.742605 INFO Wire server endpoint:168.63.129.16
2017/10/04 12:18:51.777039 INFO Fabric preferred wire protocol version:2015-04-0                                                                                                                                                             5
2017/10/04 12:18:51.783080 INFO Wire protocol version:2012-11-30
2017/10/04 12:18:51.784839 WARNING Server preferred version:2015-04-05
2017/10/04 12:18:55.938709 INFO Starting provisioning
2017/10/04 12:18:55.945525 INFO Handle ovf-env.xml.
2017/10/04 12:18:55.955746 INFO Set hostname [ppdocker7000000]
2017/10/04 12:18:55.998663 INFO Publish hostname [ppdocker7000000]
2017/10/04 12:18:56.105991 INFO Examine /proc/net/route for primary interface
2017/10/04 12:18:56.120358 INFO Primary interface is [eth0]
2017/10/04 12:18:56.132110 INFO interface [lo] has flags [73], is loopback [True                                                                                                                                                             ]
2017/10/04 12:18:56.146318 INFO Interface [lo] skipped
2017/10/04 12:18:56.155959 INFO interface [eth0] has flags [4163], is loopback [                                                                                                                                                             False]
2017/10/04 12:18:56.171477 INFO Interface [eth0] selected
2017/10/04 12:18:56.184187 INFO Examine /proc/net/route for primary interface
2017/10/04 12:18:56.189379 INFO Primary interface is [eth0]
2017/10/04 12:18:56.193939 INFO interface [lo] has flags [73], is loopback [True                                                                                                                                                             ]
2017/10/04 12:18:56.196222 INFO Interface [lo] skipped
2017/10/04 12:18:56.200934 INFO interface [eth0] has flags [4163], is loopback [                                                                                                                                                             False]
2017/10/04 12:18:56.203252 INFO Interface [eth0] selected
2017/10/04 12:18:59.159026 INFO Create user account if not exists
2017/10/04 12:18:59.288659 INFO Set user password.
2017/10/04 12:18:59.337850 INFO Configure sudoer
2017/10/04 12:18:59.347384 INFO Configure sshd
2017/10/04 12:18:59.357452 INFO Enabled SSH password-based authentication method                                                                                                                                                             s.
2017/10/04 12:18:59.372277 INFO Configured SSH client probing to keep connection                                                                                                                                                             s alive.
2017/10/04 12:18:59.868198 INFO Event: name=WALinuxAgent, op=Provision, message=                                                                                                                                                             Provision succeed, duration=8256
2017/10/04 12:19:04.985013 INFO Provisioning complete
2017/10/04 12:19:04.990312 INFO RDMA capabilities are not enabled, skipping
2017/10/04 12:19:04.993534 INFO Installed Agent WALinuxAgent-2.2.18 is the most                                                                                                                                                              current agent
2017/10/04 12:19:05.103395 INFO Agent WALinuxAgent-2.2.18 is running as the goal                                                                                                                                                              state agent
2017/10/04 12:19:05.121802 INFO Wire server endpoint:168.63.129.16
2017/10/04 12:19:05.137948 INFO Event: name=WALinuxAgent, op=HeartBeat, message=                                                                                                                                                             , duration=0
2017/10/04 12:19:05.138631 INFO Start env monitor service.
2017/10/04 12:19:05.166401 INFO Configure routes
2017/10/04 12:19:05.176834 INFO Gateway:None
2017/10/04 12:19:05.185905 INFO Routes:None
2017/10/04 12:19:05.206352 INFO Wire server endpoint:168.63.129.16
2017/10/04 12:19:05.209262 INFO WALinuxAgent-2.2.18 running as process 1446
2017/10/04 12:19:05.205639 INFO Event: name=WALinuxAgent, op=AutoUpdate, message                                                                                                                                                             =, duration=0
2017/10/04 12:19:05.211995 INFO Wire server endpoint:168.63.129.16
2017/10/04 12:19:05.294798 INFO Set block dev timeout: sda with timeout: 300
2017/10/04 12:19:05.309777 INFO Set block dev timeout: sdb with timeout: 300
2017/10/04 12:19:05.324548 INFO Set block dev timeout: sdc with timeout: 300
2017/10/04 12:19:05.339121 INFO Set block dev timeout: sdd with timeout: 300
2017/10/04 12:19:05.358673 INFO Event: name=WALinuxAgent, op=Install, message=Ag                                                                                                                                                             ent WALinuxAgent-2.2.15 downloaded successfully, duration=0
2017/10/04 12:19:05.404888 INFO Event: name=WALinuxAgent, op=Install, message=Ag                                                                                                                                                             ent WALinuxAgent-2.2.16 downloaded successfully, duration=0
2017/10/04 12:19:05.453981 INFO Event: name=WALinuxAgent, op=Install, message=Ag                                                                                                                                                             ent WALinuxAgent-2.2.17 downloaded successfully, duration=0
2017/10/04 12:19:05.462015 INFO Wire server endpoint:168.63.129.16
2017/10/04 12:19:05.526819 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3]                                                                                                                                                              Target handler state: enabled
2017/10/04 12:19:05.532705 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3]                                                                                                                                                              [Enable] current handler state is: notinstalled
2017/10/04 12:19:05.674048 INFO Event: name=Microsoft.Azure.Extensions.CustomScr                                                                                                                                                             ipt, op=Download, message=Download succeeded, duration=0
2017/10/04 12:19:05.680076 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3]                                                                                                                                                              Initialize extension directory
2017/10/04 12:19:05.683320 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3]                                                                                                                                                              Update settings file: 1.settings
2017/10/04 12:19:05.685560 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3]                                                                                                                                                              Install extension [bin/custom-script-shim install]
2017/10/04 12:19:06.697290 INFO Event: name=Microsoft.Azure.Extensions.CustomScr                                                                                                                                                             ipt, op=Install, message=Launch command succeeded: bin/custom-script-shim instal                                                                                                                                                             l, duration=0
2017/10/04 12:19:06.706844 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3]                                                                                                                                                              Enable extension [bin/custom-script-shim enable]
2017/10/04 12:19:07.778674 INFO Event: name=Microsoft.Azure.Extensions.CustomScr                                                                                                                                                             ipt, op=Enable, message=Launch command succeeded: bin/custom-script-shim enable,                                                                                                                                                              duration=0
2017/10/04 12:19:08.033738 INFO Event: name=WALinuxAgent, op=ProcessGoalState, m                                                                                                                                                             essage=, duration=2571

>

**Comment by brendandixon** [comment]
@dirkslab Traditional Linux devices names are not stable for systems using udev (most these days). You'll need to follow the guidance in https://docs.microsoft.com/en-us/azure/virtual-machines/linux/troubleshoot-device-names-problems. I hope this helps.

**Comment by dirkslab** [comment]
@brendandixon Thanks Brendan, I will have a look.
I would think Mount resource disk [mount /dev/sdd1 /mnt/resour ce] happens before my extension script runs? Can you possibly confirm if this happens before or as part of waagent install?
I do know if /resource mounts correctly to /dev/sdb1/mnt/resource my script will run fine.
In my mind things go wary before my script even runs, but this is what I am trying to understand and troubleshoot. Appreciate the feedback and insight.

**Comment by brendandixon** [comment]
@dirkslab The article I referenced should tell you all you need to know to write reliable scripts. It explains the situation well.
