### ISSUE TITLE
issue with /dev/disk/cloud/azure_resource-part1 on OEL7

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/WALinuxAgent#904]
hello, I cannot get rid of the error message:

$ sudo systemctl -l status mnt.mount
● mnt.mount - /mnt
   Loaded: loaded (/etc/fstab; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-10-10 21:17:25 UTC; 9min ago
    Where: /mnt
     What: /dev/disk/cloud/azure_resource-part1
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 1025 ExecMount=/bin/mount /dev/disk/cloud/azure_resource-part1 /mnt -o defaults,comment=cloudconfig (code=exited, status=32)

Oct 10 21:17:25 oel-ent-prepare systemd[1]: Mounting /mnt...
Oct 10 21:17:25 oel-ent-prepare mount[1025]: mount: unknown filesystem type 'ntfs'
Oct 10 21:17:25 oel-ent-prepare systemd[1]: mnt.mount mount process exited, code=exited status=32
Oct 10 21:17:25 oel-ent-prepare systemd[1]: Failed to mount /mnt.
Oct 10 21:17:25 oel-ent-prepare systemd[1]: Unit mnt.mount entered failed state.

**Comment by brendandixon** [comment]
@alexeyshishkin01 The Linux agent does not create or modify the fstab or modify disks. At most, it mounts the Azure resource disk. The message indicate a problem either with the resource disk itself or with the fstab. I suggest you contact Azure support.
