### ISSUE TITLE
Hardcoded value for sshd's ClientAliveInterval (180)

### ISSUE THREAD

**Issue by ricoli** [Azure/WALinuxAgent#906]
I have noticed that the agent is setting the value of ClientAliveInterval to 180, and that this is hardcoded in https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/common/osutil/default.py#L443. This can be problematic for hardened systems that disable TCPKeepAlive and/or set ClientAliveCountMax to 0, as any value of ClientAliveInterval set before the machine is brought up will be overridden to be 180 seconds, causing ssh to disconnect after those 180 seconds of inactivity, which will catch people by surprise.

**Comment by brendandixon** [comment]
@szarkos Do you want to weigh in on why the agent sets this default value? It is rather old code.

**Comment by szarkos** [comment]
Azure's LB has a default timeout of 4-mins, and of course all classic VMs at least are behind a load balancer.  The goal here was to ensure SSH sessions would not timeout, which proved annoying to customers.  Some SSH clients send keepalives, but not all do which lead to customer incidents.

However, the use case here is to actively close idle connections - set ClientAliveInterval to some value (i.e. 900), and ClientAliveCountMax to 0 or similar typically to conform to a CIS requirement.

I'm not sure what the right answer is.  Maybe make this value configurable with a default of 180 seconds.  Some CIS documents suggest a value of 900 and 0 for ClientAliveInterval and ClientAliveCountMax respectively, while newer CIS guidelines suggest that "ClientAliveInterval is 300 or less and ClientAliveCountMax is 3 or less".

In any case, if the VM is behind a load balancer and the customer hasn't modified its timeout, then setting this to anything >240 seconds should have no effect.  Perhaps in practice if your goal is to have a timeout closer to 900 seconds, then setting ClientAliveInterval and ClientAliveCountMax to something more like 220 and 3 would be close to what you want even if the VM is behind a load balancer.

**Comment by ricoli** [comment]
It would be great if it's at least configurable, so that one can set it to match the security policy

**Comment by brendandixon** [comment]
@ricoli @szarkos We'll add an integer configuration option -- OS.SshClientAliveInterval -- whose default will be 180 seconds.

**Comment by ricoli** [comment]
Wonderful :)
