### ISSUE TITLE
localhost with reboot a capture and not real hostname

### ISSUE THREAD

**Issue by fbejarano** [Azure/WALinuxAgent#91]
In Ubuntu 14.04 64bits, when capture a image and reboot de vm, the hostname is localhost and not de real hostname of the azure vm.

waagent: 2.0.13-0ubuntu2~14.04.0

**Comment by yuezh** [comment]
Would you please share the detail steps you do? Did you run "waagent -deprovision+user -forece", before you capture the image?

**Comment by fbejarano** [comment]
1: Only with
 sudo apt-get update+ sudo apt-get dist-upgrade(install the waagent)+reboot and the hostname change to localhost when it init.

2:  sudo apt-get update+ sudo apt-get dist-upgrade(install the waagent)+waagent -deprovision+shutdown vm+capture image+create new vm and the hostname change to localhost when it init.

**Comment by yuezh** [comment]
What command did you use to capture VM?

**Comment by fbejarano** [comment]
azure vm capture -d [dns] -t [mv] capture_name-20140513-123900

**Comment by mmitche** [comment]
Are you still seeing this issue? I saw this after a package update (walinuxagent was updated) and reboot on 14.04.

**Comment by fbejarano** [comment]
I have the same issue in ubuntu 14.04 with last version of wagent

**Comment by yuezh** [comment]
@fbejarano I couldn't repo this issue with official Ubuntu 14.04 image. What image are you using?
My steps are: 
1. Create a VM
2. Run waagent -deprovision+user -force
3. Run "azure vm capture -d [dns] -t [vm_name] [image_name]"

**Comment by mmitche** [comment]
@yuezh We occasionally see this with our images (which were stock Ubuntu).  I have one that just repro'd it right now and can give you access.

**Comment by fbejarano** [comment]
Some data

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

$ waagent -version
WALinuxAgent-2.0.14 running on Ubuntu
```
Original /etc/waagent.conf with 2 changes

```
# Monitor host name changes and publish changes via DHCP requests.
#Provisioning.MonitorHostName=n
Provisioning.MonitorHostName=y

# Format if unformatted. If 'n', resource disk will not be mounted.
#ResourceDisk.Format=n
ResourceDisk.Format=y
```

**Comment by ahmetalpbalkan** [comment]
@mmitche @fbejarano could you please try version 2.1.3 version of the Linux Agent and see if the behavior persists? Here's how you can update the agent: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-update-agent/

**Comment by hglkrijger** [comment]
closing, due to lack of activity. please reopen if you still see this with the latest agent (currently 2.1.6).
