### ISSUE TITLE
How to change azure agent log file path?

### ISSUE THREAD

**Issue by jan-wang** [Azure/WALinuxAgent#916]
I want to redirect azure agent log file to other path, e.g. original log file is /var/log/waagent.log, I want to put in other path. I check waagent.conf and don't find such conf option.
Do you know how to do it?

**Comment by marinnedea** [comment]
https://github.com/Azure/WALinuxAgent/search?utf8=%E2%9C%93&q=%22waagent.log%22&type=  will give you all the files with "waagent.log" inside. 
Not sure if changing those values is the correct way, some developer maybe has better info.

**Comment by jan-wang** [comment]
Find it in source code. Its set in agent.py.
I suggest add a knob to config it.
Close it.
