### ISSUE TITLE
waagent ephemerial setup  formats another partition under /mnt/ folder 

### ISSUE THREAD

**Issue by mikiha81** [Azure/WALinuxAgent#917]
This is related to issue REG:117052915810681 in azure support 
We use a debian 8.1 image from the market , with waa version 2.2 .
most of our machines  have another partition on the boot drive mounted as a data disk under /mnt/data 
in some case (around 5 out of 200 )we rebooted some machines and once they finished rebooting 
the  partition mounted under /mnt/data would come back as an empty ext4 partition even though we used ext2 for that partition , and the partition was either garbled or empty . 
we use fstab and uuid to mount partitions with default settings . 

also once they reboot blkid returns the secondary disk type as ext2 
/dev/sdc1: UUID="73ac25c0-f433-42bb-9fa1-315df11cfd36" TYPE="ext4"
/dev/sdc2: UUID="5b0e5c2f-f5bd-4e8d-8d01-40b03d6e8d3b" SEC_TYPE="ext2" TYPE="ext4"

we use azure python api to create all our machines from a deprovisioned image (deb 8.1 ) 
we tried completely  removing azure agent but then provisioning an image fails from the api . 
that's another issue .  we prefer removing the agent completely  as our users should not have access to our machines.  but once we do this our provisioning method  gets a false negative on provision.

**Comment by brendandixon** [comment]
@mikiha81 Azure does not, at this time, support Linux VMs without the agent installed. While it is a goal of ours to provide such, it is not a feature presently supported.

As regards your other issues, you are best continuing to pursue help through Azure Support.
