### ISSUE TITLE
The agent should emit an event when receiving an IOError

### ISSUE THREAD

**Issue by brendandixon** [Azure/WALinuxAgent#918]
The agent should emit a telemetry event when it receives an out-of-space IOError. This will likely need to touch multiple exception handlers.

**Comment by boumenot** [comment]
I would also suggest when /var is mounted with the noexec flag.

**Comment by boumenot** [comment]
This issue requires considerable changes, and will not fit in 2.2.21.  I am closing for now, and we can revisit if necessary.
