### ISSUE TITLE
HTTP GET errors after upgrade to 2.2.18

### ISSUE THREAD

**Issue by scarvel8** [Azure/WALinuxAgent#922]
After an upgrade of WALinuxAgent to 2.2.18, we are starting to see many errors such as INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError timed out.

Relevant lines from the logfile for waagent: 

```2017/10/02 17:42:40.170331 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.18 downloaded successfully, duration=0
2017/10/02 17:42:40.184193 INFO Agent WALinuxAgent-2.2.17 discovered WALinuxAgent-2.2.18 as an update and will exit
2017/10/02 17:42:40.254095 INFO Determined Agent WALinuxAgent-2.2.18 to be the latest agent
2017/10/02 17:42:40.478907 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
2017/10/02 17:42:40.490486 INFO Wire server endpoint:168.63.129.16
2017/10/02 17:42:40.501360 INFO Start env monitor service.
2017/10/02 17:42:40.499748 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/10/02 17:42:40.515109 INFO Configure routes
2017/10/02 17:42:40.522481 INFO Gateway:None
2017/10/02 17:42:40.526873 INFO Routes:None
2017/10/02 17:42:40.536965 INFO WALinuxAgent-2.2.18 running as process 51976
2017/10/02 17:42:40.544028 INFO Wire server endpoint:168.63.129.16
2017/10/02 17:42:40.550571 INFO Event: name=WALinuxAgent, op=AutoUpdate, message=, duration=0
2017/10/02 17:42:40.562539 INFO Wire server endpoint:168.63.129.16
2017/10/02 17:42:40.598330 INFO Wire server endpoint:168.63.129.16
2017/10/02 17:42:40.631295 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.4] Target handler state: enabled
2017/10/02 17:42:40.641515 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.4] [Enable] current handler state is: enabled
2017/10/02 17:42:40.651968 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.4] Update settings file: 7.settings
2017/10/02 17:42:40.662079 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.4] Enable extension [asm-extension enable]
2017/10/02 17:42:41.675332 INFO Event: name=Microsoft.Azure.Extensions.LinuxAsm, op=Enable, message=Launch command succeeded: asm-extension enable, duration=0
2017/10/02 17:42:41.713076 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9025] Target handler state: enabled
2017/10/02 17:42:41.724272 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9025] [Enable] current handler state is: enabled
2017/10/02 17:42:41.735678 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9025] Update settings file: 2.settings
2017/10/02 17:42:41.746546 INFO [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9025] Enable extension [diagnostic.py -enable]
2017/10/02 17:42:41 LinuxAzureDiagnostic started to handle.
2017/10/02 17:42:41 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9027] cwd is /var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9027
2017/10/02 17:42:41 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9027] Change log file to /var/log/azure/Microsoft.OSTCExtensions.LinuxDiagnostic/2.3.9027/extension.log
2017/10/02 17:42:42.760388 INFO Event: name=Microsoft.OSTCExtensions.LinuxDiagnostic, op=Enable, message=Launch command succeeded: diagnostic.py -enable, duration=0
2017/10/02 17:42:42.811160 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=2212
2017/10/02 17:57:41.007228 INFO Agent WALinuxAgent-2.2.18 launched with command 'python3 -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/10/02 17:57:41.022163 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.18 launched with command 'python3 -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running, duration=0
2017/10/06 08:48:12.130059 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError timed out
2017/10/06 08:48:27.150650 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Failed] HTTP GET IOError timed out
2017/10/06 08:48:42.170697 WARNING Exception retrieving extension handlers: [000008] [Wireserver Exception] [000009] [HTTP Failed] HTTP GET IOError timed out
2017/10/06 08:48:42.189159 ERROR Event: name=WALinuxAgent, op=, message=Exception retrieving extension handlers: [000008] [Wireserver Exception] [000009] [HTTP Failed] HTTP GET IOError timed out, duration=0
```

Azure
OS: Ubuntu 14.04.5 LTS, Ubuntu 16.04.3 LTS
WALinuxAgent version: 2.2.18
Python: 2.7.12

**Comment by brendandixon** [comment]
@scarvel8 What region are you running this in? We have not altered the timeout values for over a year.

**Comment by scarvel8** [comment]
@brendandixon East US 2. Is there anything else I can provide that would be useful?

**Comment by scarvel8** [comment]
@brendandixon also see it in West US

**Comment by brendandixon** [comment]
@scarvel8 Not at the moment. We're seeing an increase in these errors on other VMs as well. I do not believe it is *caused* by 2.2.18 (since the timeout has not changed). I'm examining those VMs; if I need more I'll ask.

**Comment by LoganZhao** [comment]
seeing the same issue with some VMs. causing waagent status shows not Ready.

[waagent.log](https://github.com/Azure/WALinuxAgent/files/1433251/waagent.log)

2017/10/31 21:29:08 [Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9027] Change log file to /var/log/azure/Microsoft.OSTCExtensions.LinuxDiagnostic/2.3.9027/extension.log
2017/10/31 21:29:13.874287 INFO Event: name=Microsoft.OSTCExtensions.LinuxDiagnostic, op=Enable, message=Launch command succeeded: diagnostic.py -enable, duration=0
2017/10/31 21:29:14.025424 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2] Target handler state: enabled
2017/10/31 21:29:14.052229 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2] [Enable] current handler state is: enabled
2017/10/31 21:29:14.090374 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2] Update settings file: 0.settings
2017/10/31 21:29:14.125229 INFO [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2] Enable extension [customscript.py -enable]
2017/10/31 21:29:14 CustomScriptForLinux started to handle.
2017/10/31 21:29:14 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2] cwd is /var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2
2017/10/31 21:29:14 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2] Change log file to /var/log/azure/Microsoft.OSTCExtensions.CustomScriptForLinux/1.5.2.2/extension.log
2017/10/31 21:29:15.159298 INFO Event: name=Microsoft.OSTCExtensions.CustomScriptForLinux, op=Enable, message=Launch command succeeded: customscript.py -enable, duration=0
2017/10/31 21:29:15.318594 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=100918
2017/10/31 21:42:31.136863 INFO Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/10/31 21:42:31.156130 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/10/31 21:43:18.650228 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/10/31 21:43:23.672797 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/10/31 21:43:28.694125 WARNING Exception retrieving extension handlers: [000008] [Wireserver Exception] [000009] [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/10/31 21:43:28.712176 ERROR Event: name=WALinuxAgent, op=, message=Exception retrieving extension handlers: [000008] [Wireserver Exception] [000009] [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable, duration=0

any idea how is it happened?

**Comment by sylr** [comment]
I also get a lot of those (2.2.17-0ubuntu1~16.04.1):

```
2017/11/10 11:19:59.190494 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:20:12.753189 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:20:12.754713 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:20:27.816173 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:20:27.818098 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:21:03.395389 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:21:03.397375 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:21:22.545598 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:21:22.546454 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:21:47.899774 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:21:47.902352 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:22:36.869434 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:22:36.873478 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:23:40.344474 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:23:40.347319 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:24:11.858446 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:24:11.860464 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:24:26.884260 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:24:26.886856 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:25:02.520553 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:25:02.523069 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:25:38.141126 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:25:38.144932 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:26:10.708221 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:26:10.711720 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:26:43.241716 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:26:43.245160 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:27:25.162696 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:27:25.164662 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:27:44.277236 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:27:44.279211 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:28:02.442805 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:28:02.444745 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:28:27.755305 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:28:27.757020 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/10 11:30:28.735493 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/10 11:30:28.737532 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
```

**Comment by erksam** [comment]
Same errors here. Just upgraded from 17.04 to 17.10 and same errors continue;
[...]
$ tail /var/log/waagent.log
2017/11/11 00:51:18.134291 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/11 00:51:18.158251 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/11 00:52:07.221090 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/11 00:52:07.243814 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/11 00:52:39.796253 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/11 00:52:39.821682 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/11 00:53:01.065689 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/11 00:53:01.089683 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/11 00:53:26.451987 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/11 00:53:26.532693 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503

$ waagent --version
WALinuxAgent-2.2.17 running on ubuntu 17.10
Python: 3.6.3
Goal state agent: 2.2.17
[...]

**Comment by scarvel8** [comment]
@brendandixon any updates on this?

**Comment by saimsh** [comment]
hi i just gopt a similar case:
ubuntu 16.04
kernel version:Linux version 4.4.0-98-generic
D11_V2 VM 
location west europe

Ubuntu 16.02017/11/20 07:24:31.885462 INFO Configure routes
4.2 LTS 2017/11/20 07:24:31.964471 INFO Gateway:None
GFI-RHA-DT001 ttyS0

GFI-RHA-DT001 2017/11/20 07:24:31.969199 INFO Routes:None
login: 2017/11/20 07:24:32.064239 INFO WALinuxAgent-2.2.18 running as process 1339
2017/11/20 07:24:32.062019 INFO Wire server endpoint:168.63.129.16
2017/11/20 07:24:32.070864 INFO Wire server endpoint:168.63.129.16
2017/11/20 07:24:32.213205 INFO Set block dev timeout: sda with timeout: 300
2017/11/20 07:24:32.243235 INFO Set block dev timeout: sdb with timeout: 300
2017/11/20 07:24:32.261078 INFO Wire server endpoint:168.63.129.16
2017/11/20 07:24:32.360810 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Target handler state: enabled
2017/11/20 07:24:32.373422 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] [Enable] current handler state is: enabled
2017/11/20 07:24:32.389082 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Update settings file: 136.settings
2017/11/20 07:24:32.417811 INFO [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0] Enable extension [main/handle.sh enable]
2017/11/20 07:24:32 [MyBackupTestLinuxInt-0.0]cwd is /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9124.0
2017/11/20 07:24:32 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Change log file to /var/log/azure/Microsoft.Azure.RecoveryServices.VMSnapshotLinux/1.0.9124.0/extension.log
2017-11-20 07:24:32.806279  Info  starting to enable 
2017/11/20 07:24:33.449885 INFO Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Enable, message=Launch command succeeded: main/handle.sh enable, duration=0
2017/11/20 07:24:33.512726 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Target handler state: enabled
2017/11/20 07:24:33.588128 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] [Enable] current handler state is: enabled
2017/11/20 07:24:33.636937 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Update settings file: 0.settings
2017/11/20 07:24:33.673662 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Enable extension [omsagent.py -enable]
2017/11/20 07:24:41.726933 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Enable, message=Launch command succeeded: omsagent.py -enable, duration=0
2017/11/20 07:24:41.786075 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:24:41.818261 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503


2017/11/20 07:24:56.914694 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.5] Target handler state: uninstall
2017/11/20 07:24:56.937494 INFO [Microsoft.Azure.Extensions.LinuxAsm-2.2.5] [Uninstall] current handler state is: notinstalled
2017/11/20 07:24:57.103250 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=24842
2017/11/20 07:25:00.229955 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:25:00.242645 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:25:33.040596 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:25:33.050691 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:25:48.102816 INFO [HTTP Delay] Delay 15 seconds for Status oode 503
2017/11/20 07:25:48.113760 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:26:27.443607 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:26:27.454189 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:26:46.647593 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:26:46.658484 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:27:12.215609 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:27:12.225841 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:27:30.361997 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:27:30.372737 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:28:09.500137 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:28:09.504985 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:28:24.536480 INFO [HTTP Delay] Delay 15 seconds for Status Code 503
2017/11/20 07:28:24.542764 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Retry] HTTP GET Status Code 503
2017/11/20 07:28:57.416885 INFO [HTTP Delay] Del55555 seconds for Status Code 503
2017/11/20 07:28:57.421362 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503

**Comment by saimsh** [comment]
Some more thoughts, could this be related to the azure platform itself where service is unavailable at a particular region ( i see 2 hit counts for west europe) and the waagent is simply responding to it with a 503 error. 
the vm in issue is a classic vm and a reboot/resize has not helped. i also checked the network configs, it is set to defaults i.e, defaults for endorsed distributions in azure gallery

**Comment by tenstarju** [comment]
Hi, we are experiencing the same "Status Code 503" issue.

```
WALinuxAgent-2.2.17 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.18
```

Using tcpdump we can see more information, maybe it means something to anyone?

The request:
```
GET /extensionArtifact HTTP/1.1
Host: 168.63.129.16:32526
Accept-Encoding: identity
x-ms-containerid: 5dd40870-b603-456d-bb3b-15cf69924776
x-ms-host-config-name: 54a0c878-59d9-4a16-8196-042c57eeb632.95.54a0c878-59d9-4a16-8196-042c57eeb632.96._TSPlastic.1.xml
x-ms-version: 2015-09-01
x-ms-artifact-location: https://rdfepirv2am2prdstr02.blob.core.windows.net/80afa74b14194a679c6347109557b7ee/Microsoft.Azure.RecoveryServices_VMSnapshotLinux_europewest_manifest.xml
```

The response:
```
HTTP/1.1 503 Service Unavailable
Content-Length: 281
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.5
Date: Wed, 22 Nov 2017 12:20:13 GMT

{
    "errorCode": "The server is busy.",
    "message": "......<?xml version="1.0" encoding="utf-8"?><Error><Code>ServerBusy</Code><Message>The server is busy.
RequestId:215a106d-001e-0002-508c-63f0e0000000
Time:2017-11-22T12:20:14.6282267Z</Message></Error>",
    "details": ""
}
```

**Comment by hglkrijger** [comment]
Suggest we move retry to verbose logs, as this is not normally pertinent info.

**Comment by boumenot** [comment]
Commit 0026f451 reduced retry messages from info to verbose. 

e.g.
```text
 [HTTP Retry] Attempt 2 of 3: [HTTP Retry] HTTP GET Status Code 503
```

Commit 74bd379d eliminated the delay messages.

```text
INFO [HTTP Delay] Delay 15 seconds for Status Code 503
```

These commits are already in 2.2.19, so there's nothing more to do.
