### ISSUE TITLE
[v2.2.18.4] name 'dropped_packets' is not defined

### ISSUE THREAD

**Issue by enihcam** [Azure/WALinuxAgent#926]
> Oct 30 13:38:51 localhost python[228]: 2017/10/30 13:38:51.976554 INFO Azure Linux Agent Version:2.2.18.4
Oct 30 13:38:51 localhost python[228]: 2017/10/30 13:38:51.976739 INFO OS: arch
Oct 30 13:38:51 localhost python[228]: 2017/10/30 13:38:51.976839 INFO Python: 3.6.2
Oct 30 13:38:51 localhost python[228]: 2017/10/30 13:38:51.976977 INFO Run daemon
Oct 30 13:38:51 localhost python[228]: 2017/10/30 13:38:51.977109 INFO No RDMA handler exists for distro='arch' version=''
Oct 30 13:38:51 localhost python[228]: 2017/10/30 13:38:51.977248 INFO Activate resource disk
Oct 30 13:38:51 localhost python[228]: 2017/10/30 13:38:51.982177 INFO Examining partition table
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.000934 INFO GPT not detected, determining filesystem
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.015108 INFO sfdisk --part-type -f /dev/sdb 1 -n succeeded
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.015314 INFO The partition type is 83
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.015456 INFO Mount resource disk [mount -o delalloc,rw,noatime,nobarrier,users /dev/sdb1 /mnt/resource]
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.056343 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.058095 INFO Clean protocol
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.058354 INFO Provisioning is disabled, skipping.
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.059571 INFO Detect protocol endpoints
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.059708 INFO Clean protocol
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.059827 INFO WireServer endpoint is not found. Rerun dhcp handler
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.059939 INFO Test for route to 168.63.129.16
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.060121 INFO Route to 168.63.129.16 exists
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.060231 INFO Wire server endpoint:168.63.129.16
Oct 30 13:38:52 localhost kernel: EXT4-fs (sdb1): barriers disabled
Oct 30 13:38:52 localhost kernel: EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: delalloc,nobarrier
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.074981 INFO Fabric preferred wire protocol version:2015-04-05
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.075364 INFO Wire protocol version:2012-11-30
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.075469 WARNING Server preferred version:2015-04-05
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.415904 INFO RDMA capabilities are not enabled, skipping
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.418472 INFO Installed Agent WALinuxAgent-2.2.18.4 is the most current agent
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.530751 INFO Agent WALinuxAgent-2.2.18.4 is running as the goal state agent
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.542986 INFO Wire server endpoint:168.63.129.16
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.546744 INFO Start env monitor service.
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.546924 INFO Configure routes
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.547032 INFO Gateway:None
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.547125 INFO Routes:None
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.556645 INFO WALinuxAgent-2.2.18.4 running as process 249
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.557855 INFO Event: name=WALinuxAgent, op=Partition, message=55, duration=0
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.558985 INFO Wire server endpoint:168.63.129.16
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.559289 INFO Set block dev timeout: sdb with timeout: 300
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.559437 INFO Set block dev timeout: sda with timeout: 300
Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.561121 INFO Event: name=WALinuxAgent, op=AutoUpdate, message=, duration=0
**Oct 30 13:38:52 localhost python[228]: 2017/10/30 13:38:52.561518 INFO Wire server endpoint:168.63.129.16
Oct 30 13:38:52 localhost python[228]: Exception in thread Thread-1:
Oct 30 13:38:52 localhost python[228]: Traceback (most recent call last):
Oct 30 13:38:52 localhost python[228]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Oct 30 13:38:52 localhost python[228]:     self.run()
Oct 30 13:38:52 localhost python[228]:   File "/usr/lib/python3.6/threading.py", line 864, in run
Oct 30 13:38:52 localhost python[228]:     self._target(*self._args, **self._kwargs)
Oct 30 13:38:52 localhost python[228]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/ga/monitor.py", line 198, in daemon
Oct 30 13:38:52 localhost python[228]:     incarnation, counter, heartbeat_id, dropped_packets)
Oct 30 13:38:52 localhost python[228]: NameError: name 'dropped_packets' is not defined**

**Comment by brendandixon** [comment]
@enihcam Thank you for this! It was caused by a mis-spelled variable name. However, v2.2.18.4 is pre-release and still being tested. We do not recommend it's use on production VMs.
