### ISSUE TITLE
Linux agent for OpenSuse 11

### ISSUE THREAD

**Issue by ssujai** [Azure/WALinuxAgent#93]
Hi,

We are trying to import a legacy application which has a dependency on PHP 5.2 to Azure. It is currently running on an OpenSuse 11 server. We are unable to figure out which version WALinux agent to be used in this operating system. Can anyone guide us on this please?

Regards,
Shiji

**Comment by thomas1206** [comment]
Can you try "waagent -version"?

**Comment by ssujai** [comment]
Could you please clarify? I didnt install the agent yet since I was not
able to find an agent compatible with OpenSuse 11.

**Comment by thomas1206** [comment]
Oh, I misunderstand your question. Do you have chance to try this:
https://azure.microsoft.com/en-gb/documentation/articles/virtual-machines-linux-create-upload-vhd-suse/
I'm not sure whether it works for OpenSUSE 11. Currently, OpenSUSE 13.1 and 13.2 are officially supported. And there is also one VMDepot image for openSUSE 12.3.

**Comment by ssujai** [comment]
Thanks...We were trying using the same link. Unfortunately, we were unable
to get it working for OpenSuse 11, it says no repo found. We wanted to know
if there is any archived version of the agent that will work in OpenSuse 11

**Comment by thomas1206** [comment]
You could try manually install WALA in your VM.
# cd /tmp
# wget https://raw.githubusercontent.com/Azure/WALinuxAgent/WALinuxAgent-2.0.12/waagent --no-check-certificate
# chmod +x waagent
# cp waagent /usr/sbin
# cd /usr/sbin
# waagent -install 

WALA needs Python version 2.6+, you may need update your Python lib as well.
