### ISSUE TITLE
Constant stream at 800k/min Rx, 140k/min Tx on CentoOS 7.4

### ISSUE THREAD

**Issue by rhertzler** [Azure/WALinuxAgent#931]
A newly provisioned CentOS 7.4 VM receives a constant stream at 800k/min from blob.bn1prdstr01a.store.core.windows.net and blob.bz6prdstr09a.store.core.windows.net and also sends a 140k/min stream to blob.bz6prdstr09a.store.core.windows.net. The VM is not actively used yet so is basically just sitting there. The process causing the traffic is "python -u /usr/sbin/waagent -run-exthandlers" and when the process is suspended, the traffic totally stops. 

It is one of two VMs built from the same image and the other has only a tiny amount of static traffic from waagent. Both VMs have identical waagent.conf files which have been modified from stock to create a swap file in “/mnt/resource”. After the VMs were created, OmsAgentForLinux was added but then subsequently removed through the Azure Portal. 

![netusegraph](https://user-images.githubusercontent.com/33293720/32291134-8c21bbea-bf12-11e7-9c02-64c1b26207a8.png)
The graph shows this static background traffic. The gaps are our troubleshooting efforts to narrow the problem to waagent. Not sure where to go next to find the specific problem and coming up empty on relevant differences between the two VMs.

**Comment by rhertzler** [comment]
Here's the data on the version running:

Package | WALinuxAgent
Version | 2.2.18-1.el7.centos 
Vendor | Microsoft Corporation <walinuxagent@microsoft.com>
Architecture | noarch 
Installed | 31/Oct/2017 10:30

**Comment by brendandixon** [comment]
@rhertzler These numbers are not out-of-line with our expectations. They reflect that which we see on other VMs. At present, Azure relies on the agent updates of a storage blob to convey VM health. The blob is generally not large, but the updates occur frequently (every few seconds).

Even though the behavior is "as per design," I will leave the issue open. Perhaps we can better optimize  to reduce network load.

**Comment by rhertzler** [comment]
Wow - that's over 34G in per month and over 6G out per month. Those numbers are not insignificant and seem quite high for conveying VM health. 

Our second VM that I referred to above has static values in and out of 160k/75k per min which is different enough that we thought something must be amiss. Also, the higher rate VM reports to 2 blobs as listed above while the other reports to a single blob. (Both transfer data to a 168.63.129.16 IP as well.)

**Comment by justyu** [comment]
this problem also appears in Ubuntu 14.04/17.04,

almost 3~6GB out per month.
![image](https://user-images.githubusercontent.com/5106317/33466759-01bfe6bc-d68b-11e7-9b8e-6d35f65e9898.png)

**Comment by eruditej** [comment]
You know what's fun. When MS reboots all 108 VMs behind a Virtual Firewall on Jan 4th, the walinuxagent downloads its latest ver when it starts after reboots, and it begins DDOS'ing your Virtual Firewall with Fabric Traffic that should never egress. The MS engineers on this tech bridge say hi.

**Comment by eruditej** [comment]
This was incorrectly labeled an "enhancement". Since this is sending some sort of traffic related to the basic operation of the hosts/fabric to PUBLIC IPs this opens fabric traffic to MITM attacks.

Not to mention, you can flood a virtual firewall with this traffic.

When the traffic passes through a VFW being routed, it appears as egress for the VFW.

Please give an ETA on resolution.

**Comment by zephyia** [comment]
I am experiencing a similar issue, but I still dont understand what is going on. We have 3 VMs on the same subnet in the same vnet, all created from the same Centos 7 OpenLogic OS image, however 1 of them is sending a bucket load of traffic constantly to 52.239.131.36 - blob.syd23prdstr01a.store.core.windows.net but the other 2 send virtually none - why is one sending so much and the others sending hardly any? They are identical machines (created with terraform). They are behind a virtual fortigate firewall appliance and thus I can see all the traffic.

These machines are not supposed to have any outbound access and I will be dropping all teh traffic at the firewall soon - what problems will this cause?

Finally where is the documentation that explains all this, the azure documentation about the agent doesn't seem to explain that this is how it all works, nor explain whether we can or cannot block this traffic?

**Comment by eruditej** [comment]
set the http_proxy in the walinuxagent conf file to localhost and it the
client will fall back to the wire server endpoint instead of using the
routed public IP

This issue occurs with virtual firewalls with a forced tunnel mode and
since most of them are forced to use 1 gigabit  virtual links this is too
impactful for a sizable deployment.

**Comment by zephyia** [comment]
Thanks Ill give that a go.

Does anyone know why only some machines send lots of traffic and others send hardly any, when they are all essentially identical except for host name?

Thanks

c.

**Comment by eruditej** [comment]
it could depend, restart the agent on the boxes that arent sending as much.

they may have been started at a time when they couldn't reach the public IP
and fallen back to the wire server endpoint (the 169 address)

I don't recommend doing that though since you could increase the amount of
traffic hitting your firewall

**Comment by boumenot** [comment]
> Does anyone know why only some machines send lots of traffic and others send hardly any, when they are all essentially identical except for host name?

Is the agent version the same?
Does one VM have extensions vs. not?

You can enable verbose logging via a setting in /etc/waagent.conf, restart the agent, and observe the HTTP traffic being emitted by the agent.  It is very noisy, but it may give you an idea.

**Comment by hglkrijger** [comment]
Should be addressed with #1194, to be released with 2.2.28.
