### ISSUE TITLE
HTTP PUT IOError timed out

### ISSUE THREAD

**Issue by linuxelf001** [Azure/WALinuxAgent#933]
Nov  2 02:00:2 python: 2017/11/02 03:00:29.408051 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP PUT IOError timed out
Nov  2 06:08:30 python: 2017/11/02 07:08:30.382668 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP PUT IOError timed out
Nov  2 15:06:39 python: 2017/11/02 16:06:39.487851 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError timed out

As shown above, I notice occurrences of agent failing to reach wire server or possible network timeout. Is it common/expected to notice IOError timedout traces in waagent log file?

**Comment by brendandixon** [comment]
@linuxelf001 The agent logs all timeout errors. It is useful when diagnosing other issues. It is possible for the agent to occasionally fail to reach a resource, such as storage. In those cases you will see the above.
