### ISSUE TITLE
[Extension] Extension will not run if WALA use customerized configuration file path

### ISSUE THREAD

**Issue by yuhuijiang** [Azure/WALinuxAgent#935]
If we use a customerized configuration file path to WALA, extension VMAccessForLinux will not successfully install.Because inside VMAccessForLinux extension,it will only check the default configuration file path(/etc/waagent.conf).If /etc/waagent.conf not exist,it will unistall.

**Comment by brendandixon** [comment]
@yuhuijiang You'll need to open an issue on the repository for VMAccess: https://github.com/Azure/azure-linux-extensions.
