### ISSUE TITLE
walinux agent messing up with directory permissions

### ISSUE THREAD

**Issue by manojbhatt** [Azure/WALinuxAgent#936]
I am trying to run chef-solo using walinux agent and when chef-solo is running it install some packages. There are directories which get created as part of the installation. These directories are not getting right permission on them. I suspect the issue is related to umask and I saw in the repo some code regarding the same.

**Comment by brendandixon** [comment]
@manojbhatt Thank you for your concern. Do you have a specific instance you can share where the directories had one set of permissions and then, after the agent ran, they changed?

You might consider installing and running `auditd` (see https://www.systutorials.com/docs/linux/man/8-auditd/). You can configure it to monitor such changes and identify the process.

**Comment by manojbhatt** [comment]
@brendandixon thanks for looking into it. I think the issue was not with the linux agent but I am still in doubt because it got fixed for few of our servers. I'll check on the other servers if it will repeat and will post the details if any.

**Comment by hglkrijger** [comment]
@manojbhatt - please reopen if the issue was indeed the agent
