### ISSUE TITLE
Ability to execute custom scripts during extension installation

### ISSUE THREAD

**Issue by twitek** [Azure/WALinuxAgent#937]
For 3rdparty integration purposes, it would be useful to have the capability to execute scripts/callbacks during various points of the installation or uninstallation of an extension.

My idea would be something along the lines of having, for example, directories for each stage mentioned in the manifest: `/var/lib/waagent/<stage>.d/` (e.g. `/var/lib/waagent/install.d/`). Whenever an extension is installed, enabled, updated, etc., the scripts in the corresponding directory would be invoked.

That would provide 3rdparty integrators with standardized integration points to "hook into" (e.g. to perform custom actions when a VM is added to or removed from an OMS dashboard).

Or is there a better way to achieve such functionality?

Thanks a lot in advance!

**Comment by brendandixon** [comment]
@twitek Thank you for your suggestion. The agent has a much more narrow role in Azure: Preparing the VM. Extensions are conceived of as packages by which to add pre-designed features to the VM. The exception being CustomScript as it eases running start-up scripts. Adding additional scripts would complicate the process and likely increase instability. Further, given when the agent runs, they would be very hard to debug for most users.

So, thank you, but your suggestion lies outside the realm of the agent's role.
