### ISSUE TITLE
[2.2.18] Set "Provisioning.SshHostKeyPairType=auto" causes provisioning fail in RHEL-6

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#941]
Description of problem:
If set "Provisioning.SshHostKeyPairType=auto", WALA runs "ssh-keygen -A" command during provisioning, which is supported since OpenSSH 5.9.
In RHEL-6.9, the openssh version is openssh-5.3p1-123

Expected results:
Suggest to add notice messages in /etc/waagent.conf. (Currently the introduction of this parameter is "# Supported values are "rsa", "dsa", "ecdsa", "ed25519", and "auto".")
Or check openssh version before running "ssh-keygen -A" command.

Version-Release number of selected component (if applicable):
WALinuxAgent-2.2.18

RHEL Version:
RHEL-6.9/6.8/6.7
How reproducible: 
100%

Steps to Reproduce: 
1. Prepare a RHEL6.9 VM in Azure. Set "Provisioning.SshHostKeyPairType=auto" in /etc/waagent.conf. Then "waagent -deprovision+user -force", make an image and create a new VM base on it.
2. Try to login through ssh.

Actual results: 
Cannot login. After "reset remote access", can login. There're error logs in /var/log/waagent.log:
2017/11/13 03:24:57.717203 ERROR Command: 'ssh-keygen -A'
2017/11/13 03:24:57.737975 ERROR Return code: 1
2017/11/13 03:24:57.751176 ERROR Result: ssh-keygen: illegal option -- A
usage: ssh-keygen [options]
Options:
  -a trials   Number of trials for screening DH-GEX moduli.
  -B          Show bubblebabble digest of key file.
  -b bits     Number of bits in the key to create.
  -C comment  Provide new comment.
  -c          Change comment in private and public key files.
  -D pkcs11   Download public key from pkcs11 token.
  -e          Convert OpenSSH to RFC 4716 key file.
  -F hostname Find hostname in known hosts file.
  -f filename Filename of the key file.
  -G file     Generate candidates for DH-GEX moduli.
  -g          Use generic DNS resource record format.
  -H          Hash names in known_hosts file.
  -h          Generate host certificate instead of a user certificate.
  -I key_id   Key identifier to include in certificate.
  -i          Convert RFC 4716 to OpenSSH key file.
  -L          Print the contents of a certificate.
  -l          Show fingerprint of key file.
  -M memory   Amount of memory (MB) to use for generating DH-GEX moduli.
  -N phrase   Provide new passphrase.
  -O option   Specify a certificate option.
  -P phrase   Provide old passphrase.
  -p          Change passphrase of private key file.
  -q          Quiet.
  -R hostname Remove host from known_hosts file.
  -r hostname Print DNS resource record.
  -S start    Start point (hex) for generating DH-GEX moduli.
  -s ca_key   Certify keys with CA key.
  -T file     Screen candidates for DH-GEX moduli.
  -t type     Specify type of key to create.
  -V from:to  Specify certificate validity interval.
  -v          Verbose.
  -W gen      Generator to use for generating DH-GEX moduli.
  -y          Read private key file and print public key.
  -Z name,... User/host principal names to include in certificate
  -z serial   Specify a serial number.

2017/11/13 03:24:58.215978 ERROR Command: 'ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub'
2017/11/13 03:24:58.239057 ERROR Return code: 1
2017/11/13 03:24:58.255399 ERROR Result: /etc/ssh/ssh_host_rsa_key.pub: No such file or directory

2017/11/13 03:25:00.514745 ERROR Event: name=WALinuxAgent, op=Provision, message=[000004] Failed to generate ssh host key: ret=1, out= /etc/ssh/ssh_host_rsa_key.pub: No such file or directory
, duration=0
2017/11/13 03:25:00.566516 ERROR Provisioning failed: [000004] Failed to generate ssh host key: ret=1, out= /etc/ssh/ssh_host_rsa_key.pub: No such file or directory

**Comment by boumenot** [comment]
Th original commit ed5bb330 did document that this was only supported on OpenSSH >= 5.9, but I do not think it was documented in a very useful place.  I have updated the comments for all waagent.conf files.

I decided not to fix this by matching the version string because our telemetry does not indicate this is an issue.  If it does become an issue then I recommend we revisit with a better fix.
