### ISSUE TITLE
Download operation failure

### ISSUE THREAD

**Issue by hglkrijger** [Azure/WALinuxAgent#945]
```Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing.```

**Comment by hglkrijger** [comment]
Issues seem to stem from `_upgrade_available` as all exception errors are similar to:
```
Exception retrieving agent manifests: [000008] [Wireserver Exception] [000009] None
Exception retrieving agent manifests: [000008] Failed to retrieve GAFamily manifest
```
These are the top two.

**Comment by kailashms** [comment]
Hi, 

I have similar case with me, where the cx complains that the backup is not working on the vm.
open checking the waagent.log file we could see similar error
2017/12/15 12:49:24.269432 WARNING Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing.
2017/12/15 12:49:24.272582 ERROR Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing., duration=0
2017/12/15 12:49:27.287900 WARNING Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing.
2017/12/15 12:49:27.291279 ERROR Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing., duration=0
2017/12/15 12:49:30.305082 WARNING Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing.

All this started happneniing when the new goalstate is pointed to 2.2.19 and the issue started.
also if we check the duration for the agent to get the manfiest files, is showing as 0, is there anything to do with the time out section for this,

we have mitigated the issue by using the below steps and the backup is working now,

waagent --version
yum remove walinuxagent or yum remove WALinuxAgent
waagent --version
mv /var/lib/waagent /var/lib/waagent_old
yum install walinuxagent or yum install WALinuxAgent

cx wants to know what could be the reason for the file missing,.

Thanks,

Kailash B

**Comment by kailashms** [comment]
++ Logs

2017/12/15 11:45:24.743731 INFO Agent WALinuxAgent-2.2.18 forwarding signal 15 to WALinuxAgent-2.2.19
2017/12/15 11:48:59.177682 INFO Azure Linux Agent Version:2.2.18
2017/12/15 11:48:59.219491 INFO OS: centos 7.3.1611
2017/12/15 11:48:59.279376 INFO Python: 2.7.5
2017/12/15 11:48:59.308719 INFO Run daemon
2017/12/15 11:48:59.328929 INFO Activate resource disk
2017/12/15 11:48:59.349912 INFO Examining partition table
2017/12/15 11:48:59.648099 INFO GPT not detected, determining filesystem
2017/12/15 11:48:59.851157 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/15 11:48:59.886830 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/15 11:48:59.907196 INFO The partition is formatted with ntfs, updating partition type to 83
2017/12/15 11:48:59.932665 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/15 11:48:59.956669 INFO sfdisk -c  /dev/sdb 1 83 succeeded
2017/12/15 11:48:59.994813 INFO Format partition [mkfs.ext4 -F /dev/sdb1]
2017/12/15 11:49:02.365824 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/15 11:49:02.422599 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/15 11:49:02.439707 INFO Clean protocol
2017/12/15 11:49:02.449310 INFO Provisioning already completed, skipping.
2017/12/15 11:49:02.462388 INFO RDMA capabilities are not enabled, skipping
2017/12/15 11:49:02.513662 INFO Determined Agent WALinuxAgent-2.2.19 to be the latest agent
2017/12/15 11:49:02.718240 INFO Agent WALinuxAgent-2.2.19 is running as the goal state agent
2017/12/15 11:49:02.745979 INFO Detect protocol endpoints
2017/12/15 11:49:02.751398 INFO Clean protocol
2017/12/15 11:49:02.753862 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/15 11:49:02.756203 INFO Test for route to 168.63.129.16
2017/12/15 11:49:02.759064 INFO Route to 168.63.129.16 exists
2017/12/15 11:49:02.761151 INFO Wire server endpoint:168.63.129.16
2017/12/15 11:49:02.810822 INFO Fabric preferred wire protocol version:2015-04-05
2017/12/15 11:49:02.827117 INFO Wire protocol version:2012-11-30
2017/12/15 11:49:02.832393 WARNING Server preferred version:2015-04-05
2017/12/15 11:49:03.150323 INFO Start env monitor service.
2017/12/15 11:49:03.155634 INFO Configure routes
2017/12/15 11:49:03.158214 INFO Gateway:None
2017/12/15 11:49:03.163282 INFO Routes:None
2017/12/15 11:49:03.203853 INFO Wire server endpoint:168.63.129.16
2017/12/15 11:49:03.216089 INFO WALinuxAgent-2.2.19 running as process 1072
2017/12/15 11:49:03.240161 INFO Wire server endpoint:168.63.129.16
2017/12/15 11:49:03.262763 WARNING Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing.
2017/12/15 11:49:03.268155 ERROR Event: name=WALinuxAgent, op=Download, message=Exception retrieving agent manifests: [ProtocolError] /var/lib/waagent/GoalState.1.xml is missing., duration=0
2017/12/15 11:49:03.317730 INFO Wire server endpoint:168.63.129.16

**Comment by kailashms** [comment]
Any update on this.

**Comment by Shuanglu** [comment]
Hi, 
I have customer met similar issue on Ubuntu 16.04. Even tried with purge and reinstall, the issue(/var/lib/waagent/GoalState.1.xml is missing) still persists. Could you please advise the workaround?

**Comment by EricTendian** [comment]
I'm also running into this issue on Ubuntu 16.04 and while the workaround mentioned by @kailashms worked for most of my VMs, it doesn't seem to work for a few of my newer ones. I managed to come up with this command as a workaround (run as root):

```bash
cp -a $(ls -td /var/lib/waagent/GoalState.*.xml | head -n 1) /var/lib/waagent/GoalState.1.xml
```

What this will do is copy the most recent goal state to GoalState.1.xml and preserve permissions, suppressing the error. I don't know what kind of adverse effects this could cause, but it worked for my VMs. (As long as the goal state is recent, to prevent any significant changes increasing the possibility of error.) I'd like an official workaround to the issue if possible.

**Comment by kailashms** [comment]
@EricTendian @Shuanglu 
I too had a similar  case with Ubuntu 16.04 and this is what i did to overcome the issue.
#waagent --version à check the version
#apt-get remove walinuxagent  à to remove the waagent
#apt-get purge walinuxagent à if not removed the above command, use this one
#waagent –version à recheck again
#mv /var/lib/waagent /var/lib/waagent_old à move the folder
#apt-get install walinuxagent à install the waagent again
#service walinuxagent status.
and then check the waagent.log file.
#tail -f /var/log/waagent.log.

**Comment by hglkrijger** [comment]
@EricTendian, @Shuanglu, are you able to reliably reproduce this? Could you provide details?

**Comment by hglkrijger** [comment]
We are currently working on hotfix release 2.2.20 for this issue. Please see details [here](https://github.com/Azure/WALinuxAgent/wiki/Known-Issues#2219---protocolerror-varlibwaagentgoalstate1xml-is-missing) for RCA and mitigation.
