### ISSUE TITLE
WALinuxAgent Issue during Reboot (2.2.18)

### ISSUE THREAD

**Issue by isaki-x** [Azure/WALinuxAgent#947]
I have several identical VMs, and only one of them has the issue. I have tried redeploying the VM in Azure which rectified the issue for a brief period. I suspect this may be related to the fact this box takes Azure image takes a small eternity to reboot, whereas its sister images reboot nearly instantly.

```
$ journalctl -b | grep -i WALinux
Nov 20 14:50:55 jeanne python3[1167]: 2017/11/20 14:50:55.982566 INFO Determined Agent WALinuxAgent-2.2.18 to be the latest agent
Nov 20 14:50:56 jeanne python3[1167]: 2017/11/20 14:50:56.535867 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
Nov 20 14:51:01 jeanne python3[1167]: 2017/11/20 14:51:01.038968 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
Nov 20 14:51:01 jeanne python3[1167]: 2017/11/20 14:51:01.070577 INFO WALinuxAgent-2.2.18 running as process 1335
Nov 20 14:51:01 jeanne python3[1167]: 2017/11/20 14:51:01.082158 INFO WALinuxAgent-2.2.18 did not terminate cleanly
Nov 20 14:51:01 jeanne python3[1167]: 2017/11/20 14:51:01.083570 ERROR Event: name=WALinuxAgent, op=Restart, message=WALinuxAgent-2.2.18 did not terminate cleanly, duration=0
Nov 20 14:51:01 jeanne python3[1167]: 2017/11/20 14:51:01.174951 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=43
```

This is the final line in the Azure console from this process prior to reboot:

```
2017/11/20 14:48:38.656704 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=62
```

Thanks!

**Comment by hglkrijger** [comment]
We suspect this may be improved by #944. Once that fix is released, we need to check in on this issue again.

**Comment by hglkrijger** [comment]
We decided against #944, but I believe there is a fix for the issue you saw above in the upcoming version of the agent (2.2.28). If you continue to see this feel free to reopen.

**Comment by isaki-x** [comment]
Excellent, I'll re-open if the issue persists after 2.2.28 is available.
