### ISSUE TITLE
Python used by WALinuxAgent need to be updated from 2.6 to 2.7

### ISSUE THREAD

**Issue by FumiakiNagano** [Azure/WALinuxAgent#952]
Azure Backup needs python 2.7. If python 2.6 is used, the following error is logged at /var/log/waagent.log

   WARNING httplib does not support https tunnelling (new in python 2.7)

I deployed a Red Hat 6.7 VM and executed the following commands in order to update python to 2.7.

yum groupinstall "Development tools"
wget https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz
tar xvfz Python-2.7.14.tgz
cd Python-2.7.14
./configure
make
make altinstall
mv /usr/bin/python /usr/bin/python_back
cp /usr/local/bin/python2.7 /usr/bin/python

When I tried to start the service, I got an error.

[root@redhat67 bin]# service waagent restart
Stopping AzureLinuxAgent:                                  [FAILED]
Starting AzureLinuxAgent: Traceback (most recent call last):
  File "/usr/sbin/waagent", line 31, in <module>
    import azurelinuxagent.agent as agent
ImportError: No module named azurelinuxagent.agent

Copying azurelinuxagent seemed to fix this issue, but I don't know this is a supported method or not. 

[root@redhat67 lib]# cp -r /usr/lib/python2.6/site-packages/azurelinuxagent/ /usr/local/lib/python2.7/site-packages/
[root@redhat67 lib]# service waagent restart
Stopping AzureLinuxAgent:                                  [FAILED] 
Starting AzureLinuxAgent:
[root@redhat67 lib]# service waagent restart
Stopping AzureLinuxAgent:                                  [  OK  ] # I needed to restart the service twice.
Starting AzureLinuxAgent:

**Comment by hglkrijger** [comment]
We do not provide system or Python update support.

**Comment by FumiakiNagano** [comment]
Does that mean WALinuxAgent will not be supported once I update Python from 2.6 to 2.7? Python 2.7 is required by Azure Backup (which is, off course, one of the Azure services). 
I can update Python at my own risk but I would like to know how I need to change WALinuxAgent files/configurations after the update. As I said, it seems WALinuxAgent specific files need to be copied to a different folder.

**Comment by hglkrijger** [comment]
You do not need to change anything, WALinuxAgent supports Python 2.7; however, your upgrade process may break the package install, which we do not support.
