### ISSUE TITLE
Agent installing wrong RDMA driver for CentOS HPC on 2.2.12

### ISSUE THREAD

**Issue by axelgMS** [Azure/WALinuxAgent#955]
similar to issue #943 https://github.com/Azure/WALinuxAgent/issues/943

            "imageReference": {
                "publisher": "OpenLogic",
                "offer": "CentOS-HPC",
                "sku": "7.1",
                "version": "latest"

2017/11/28 10:46:18.362153 INFO Azure Linux Agent Version:2.2.12
2017/11/28 10:46:18.363358 INFO OS: centos 7.1.1503
2017/11/28 10:46:18.363707 INFO Python: 2.7.5
2017/11/28 10:46:18.364576 INFO Run daemon
…
2017/11/28 10:46:29.146846 INFO Provisioning complete
2017/11/28 10:46:39.221784 INFO RDMA: kvp daemon (hv_kvp_daemon) is running
2017/11/28 10:46:39.223650 INFO RDMA: kvp daemon running: True
2017/11/28 10:46:49.235676 INFO RDMA: found firmware version: 144.0
2017/11/28 10:46:49.456463 INFO RDMA: driver package present: microsoft-hyper-v-rdma-4.2.0.142-20170426.x86_64

2017/11/28 10:46:49.457961 INFO RDMA: driver package needs updating
2017/11/28 10:46:49.458198 INFO RDMA: updating RDMA packages
2017/11/28 10:46:49.458478 INFO RDMA: refreshing yum repos
2017/11/28 10:46:52.144839 INFO RDMA: repositories refreshed
2017/11/28 10:46:52.146782 INFO RDMA: Force installing package: msft-rdma-drivers
2017/11/28 10:46:58.304882 INFO RDMA: installation completed: msft-rdma-drivers
2017/11/28 10:46:58.306676 INFO RDMA: pkgs dir: /opt/microsoft/rdma/rhel71
2017/11/28 10:46:58.308247 INFO RDMA: found 7 files in package directory
2017/11/28 10:46:58.309718 INFO RDMA: deleting existing kvp driver packages
2017/11/28 10:46:58.333356 INFO RDMA: kvp package hypervkvpd does not exist, skipping
2017/11/28 10:46:58.355451 INFO RDMA: kvp package microsoft-hyper-v does not exist, skipping
2017/11/28 10:46:58.356568 INFO RDMA: Processing kernel mode driver: /opt/microsoft/rdma/rhel71/kmod-microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/11/28 10:46:58.356714 INFO RDMA: Try to uninstall existing version: kmod-microsoft-hyper-v-rdma
2017/11/28 10:47:43.820930 INFO RDMA: Successfully uninstaled kmod-microsoft-hyper-v-rdma
2017/11/28 10:47:43.827637 INFO RDMA: Installing kernel mode package from /opt/microsoft/rdma/rhel71/kmod-microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/11/28 10:48:08.296829 INFO RDMA: Processing user mode driver: /opt/microsoft/rdma/rhel71/microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/11/28 10:48:08.297815 INFO RDMA: Try to uninstall existing version: microsoft-hyper-v-rdma
2017/11/28 10:48:08.469516 INFO RDMA: Successfully uninstaled microsoft-hyper-v-rdma
2017/11/28 10:48:08.470672 INFO RDMA: Installing user mode package from /opt/microsoft/rdma/rhel71/microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/11/28 10:48:24.675480 INFO RDMA: driver packages installed
2017/11/28 10:48:24.676622 INFO RDMA: probing module 'hv_network_direct'
2017/11/28 10:48:24.680381 ERROR Command: 'modprobe --first-time hv_network_direct'
2017/11/28 10:48:24.681733 ERROR Return code: 1
2017/11/28 10:48:24.683164 ERROR Result: modprobe: ERROR: could not insert 'hv_network_direct': Module already in kernel

2017/11/28 10:48:24.683504 ERROR Could not load "hv_network_direct" kernel module. Run "modprobe --first-time hv_network_direct" as root for more details
**2017/11/28 10:48:24.683808 INFO RDMA: driver module is not loaded; reboot required
2017/11/28 10:48:24.684437 INFO RDMA: Rebooting system.**
2017/11/28 10:48:46.441051 INFO Azure Linux Agent Version:2.2.12
2017/11/28 10:48:46.442205 INFO OS: centos 7.1.1503

**Comment by hglkrijger** [comment]
This is by design.
