### ISSUE TITLE
"yum update WALinuxAgnet" resets /etc/waagent.conf to default

### ISSUE THREAD

**Issue by FumiakiNagano** [Azure/WALinuxAgent#958]
Repro steps:
1. Deploy Oracle Linux 7.3.0.0.0 from Azure Portal.
2. Change /etc/waagent.conf
  For example: Logs.Verbose=n -> Logs.Verbose=y
3. yum update WALinuxAgent
  During the update, the following log can be found.
  "warning: /etc/waagent.conf saved as /etc/waagent.conf.rpmsave"
4. /etc/waagent.conf was reset to default
   You can confirm that "Logs.Verbose=y" is changed to "Logs.Verbose=n"

a) is this (= "yum update WALinuxAgent" resets /etc/waagent.conf to default) by design?
b) If (a) is yes, can this happen during auto update?

If (b) is yes, it means the settings of waagent could be changed without user notice.

**Comment by hglkrijger** [comment]
The way the config changes are handled is decided by the package and so this should be taken up with the package maintainer, Oracle in this case.
