### ISSUE TITLE
In cross geo replication scenario, the VM can be failed over from Geo1 to Geo2. We can end up with situation where the extension version is lower in Geo2 than the one present in the Geo1. So, if a VM is failed over from Geo1 to Geo2, we see undefined behavior by the GA.

### ISSUE THREAD

**Issue by innosam** [Azure/WALinuxAgent#961]
Last I tested following behavior was observed when we hit such a scenario:
1.	Windows: The guest agent continued using the higher version of extension, even though the compute advertised a lower one.

Impact: None, things worked smoothly for us.

2.	Linux: the guest agent was not able to proceed with enable and continuously logged error messages that **extension cannot be downgraded**.

Impact: The extension operation did not start.

We are looking for a consistent behavior across both the windows and Linux guest agent.

**Comment by hglkrijger** [comment]
Linux GA is correct in this scenario. Extension downgrade is not supported.

**Comment by boumenot** [comment]
I think we should discuss this one more.

/cc @danielsollondon

**Comment by innosam** [comment]
Even windows extension does not downgrade, but uses the most recent available extension in the VM.

Though, Linux extension keep does not do any action, and just reports failure.

@hglkrijger  So, is there any issue if the GA uses the higher version extension in the VM, even though a lower version is advertised by the compute.
