### ISSUE TITLE
I/O

### ISSUE THREAD

**Issue by khenidak** [Azure/WALinuxAgent#963]
WALinux agent frequently (every ~2 second) command as the following
 
```
#pstree output 
**snip**
  |-python3 -u /usr/sbin/waagent -daemon
  |   `-python3 -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers
  |       `-2*[{python3}]
**snip**
```

This commands writes 27.x KB every time it runs (not sure why). Also i think it loads 516KB egg from disk every time it runs. Is this really necessary?

**Comment by hglkrijger** [comment]
At the moment, yes. We have an open item to try and improve this though (#931).
