### ISSUE TITLE
Reduce noisy diagnostic spew to /dev/console

### ISSUE THREAD

**Issue by amitchat** [Azure/WALinuxAgent#965]
This is a request to reduce the noisy diagnostic spew that is being sent to /dev/console. Specifically this causes interference with someone connecting to /dev/ttyS0 session on the VM and interactive with it during a session as random noisy log messages pop up.

Here are some specific examples:
* After reboot the following spew is present in /dev/console that interferes with someone looking to find the login prompt in /dev/ttyS0

Ubuntu 16.04.3 LTS amitchat-pilottestvm ttyS0

**amitchat-pilottestvm** login: 2017/12/08 01:24:19.945575 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Enable, message=Launch command succeeded: omsagent.py -enable, duration=0
2017/12/08 01:24:20.039393 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 1, duration=6435

* Besides the login interference, the other noisy spew is from heartbeats.

2017/12/08 01:54:14.782090 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;1;CA446D00-B6F8-4262-8ACE-AAFC17B8DED4;0, duration=0
2017/12/08 02:24:15.996202 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 02:24:16.204557 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;2;CA446D00-B6F8-4262-8ACE-AAFC17B8DED4;0, duration=0
2017/12/08 02:54:17.456154 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;3;CA446D00-B6F8-4262-8ACE-AAFC17B8DED4;0, duration=0
2017/12/08 03:24:18.555719 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 03:24:18.678799 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;4;CA446D00-B6F8-4262-8ACE-AAFC17B8DED4;0, duration=0
2017/12/08 03:54:20.092973 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;5;CA446D00-B6F8-4262-8ACE-AAFC17B8DED4;0, duration=0
2017/12/08 04:24:21.156631 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 04:24:21.411791 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;6;CA446D00-B6F8-4262-8ACE-AAFC17B8DED4;0, duration=0
2017/12/08 04:54:22.551485 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;7;CA446D00-B6F8-4262-8ACE-AAFC17B8DED4;0, duration=0
2017/12/08 05:24:23.717222 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 06:24:26.369679 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 07:24:29.482495 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 08:24:32.991244 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 09:24:36.942873 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 10:24:40.172169 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 11:24:43.573205 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0
2017/12/08 12:24:46.682534 INFO Event: name=WALinuxAgent, op=Firewall, message=, duration=0

----------

It would be nice to reduce some noise if these are not useful messages directed to /dev/console.

Thanks!
-Amit

**Comment by hglkrijger** [comment]
Let's turn off logging for both of these completely.
