### ISSUE TITLE
Issue connecting to azure default IP in a RHEL VM with 2 NIC

### ISSUE THREAD

**Issue by saimsh** [Azure/WALinuxAgent#968]
The VMs after provisioning is unable to reach the default Azure IP  168.63.129.16. 

This is causing the VM to provision time out.
workaround ( using policy based routing)
Need to manually add the IP address to the IP route table to establish connection. 

ip route add 168.63.129.16 via <gateway ip>

In waagent.log  i see the below errors

2017/11/29 13:35:06.086945 INFO Retry detect protocols: retry=332
2017/11/29 13:35:16.089753 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/11/29 13:35:16.094042 INFO Test for route to 168.63.129.16
2017/11/29 13:35:16.097666 INFO Route to 168.63.129.16 exists
2017/11/29 13:35:16.099283 INFO Wire server endpoint:168.63.129.16
2017/11/29 13:35:19.107998 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError [Errno 113] No route to host
2017/11/29 13:35:27.123996 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Failed] HTTP GET IOError [Errno 113] No route to host
2017/11/29 13:35:35.136057 INFO WireServer is not responding. Reset endpoint
2017/11/29 13:35:35.140463 INFO Protocol endpoint not found: WireProtocol, [000008] [Wireserver Exception] [000009] [HTTP Failed] HTTP GET IOError [Errno 113] No route to host
2017/11/29 13:35:35.145578 INFO Protocol endpoint not found: MetadataProtocol, [000008] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview

# cat /etc/sysconfig/network-scripts/ifcfg-eth0

DEVICE=eth0
ONBOOT=yes
BOOTPROTO=dhcp
TYPE=Ethernet
USERCTL=no
PEERDNS=yes
IPV6INIT=no
DHCP_HOSTNAME=localhost.localdomain
# cat /etc/sysconfig/network-scripts/ifcfg-eth1
DHCP_HOSTNAME=AVSCW-FE04-B-1
DEVICE=eth1
ONBOOT=yes
BOOTPROTO=dhcp
TYPE=Ethernet
USERCTL=no
PEERDNS=yes
IPV6INIT=no

# waagent -version
WALinuxAgent-2.2.18 running on redhat 7.2
Python: 2.7.5
Goal state agent: 2.2.18

**Comment by hglkrijger** [comment]
The agent in this case is a victim since the routing table does not contain an entry for 168.63, as it should automatically via dhcp. We do validate that the agent works with multiple NICs. Please look at the dhcp configuration to determine where the issue is, or follow up with networking.
