### ISSUE TITLE
agent and wireserver not able to communicate, becasuse of which vm is inaccessible.

### ISSUE THREAD

**Issue by kailashms** [Azure/WALinuxAgent#972]
we have Cantos 6.9 , the vm was stopped as regularly on Saturday and Sunday
monday when the vm was started, it was not accessible, we could see login prompt everthing is fine.
except the waagent.log
2017/12/11 09:24:48.409157 INFO Azure Linux Agent Version:2.2.14
2017/12/11 09:24:48.411873 INFO OS: centos 6.9
2017/12/11 09:24:48.412608 INFO Python: 2.6.6
2017/12/11 09:24:48.416631 INFO Run daemon
2017/12/11 09:24:48.418592 INFO Activate resource disk
2017/12/11 09:24:48.443251 INFO Examining partition table
2017/12/11 09:24:48.513612 INFO GPT not detected, determining filesystem
2017/12/11 09:24:48.534690 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/11 09:24:48.556336 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/11 09:24:48.556547 INFO The partition is formatted with ntfs, updating partition type to 83
2017/12/11 09:24:48.564476 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/11 09:24:48.607103 INFO sfdisk -c /dev/sdb 1 83 succeeded
2017/12/11 09:24:48.637212 INFO Format partition [mkfs.ext4 -F /dev/sdb1]
2017/12/11 09:24:52.672898 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/11 09:24:52.746001 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/11 09:24:52.751542 INFO Clean protocol
2017/12/11 09:24:52.857868 INFO Provisioning already completed, skipping.
2017/12/11 09:24:52.857978 INFO RDMA capabilities are not enabled, skipping
2017/12/11 09:24:52.895045 INFO Determined Agent WALinuxAgent-2.2.18 to be the latest agent
2017/12/11 09:24:53.125820 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
2017/12/11 09:24:53.148854 INFO Detect protocol endpoints
2017/12/11 09:24:53.148965 INFO Clean protocol
2017/12/11 09:24:53.149079 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/11 09:24:53.149172 INFO Test for route to 168.63.129.16
2017/12/11 09:24:53.149410 WARNING No route exists to 168.63.129.16
2017/12/11 09:24:53.149507 INFO Checking for dhcp lease cache
2017/12/11 09:24:53.149593 INFO looking for leases in path [/var/lib/dhclient/dhclient-*.leases]
2017/12/11 09:24:53.255337 INFO dhcp entry:168.63.129.16, 245:True, expired:False
2017/12/11 09:24:53.255449 INFO found endpoint [168.63.129.16]
2017/12/11 09:24:53.255570 INFO dhcp entry:168.63.129.16, 245:True, expired:False
2017/12/11 09:24:53.255655 INFO found endpoint [168.63.129.16]
2017/12/11 09:24:53.255787 INFO cached endpoint found [168.63.129.16]
2017/12/11 09:24:53.327792 INFO Cache exists [True]
2017/12/11 09:24:53.327953 INFO Wire server endpoint:168.63.129.16
2017/12/11 09:24:53.358169 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:24:58.363055 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:03.368157 INFO WireServer is not responding. Reset endpoint
2017/12/11 09:25:03.368305 INFO Protocol endpoint not found: WireProtocol, [000008] [Wireserver Exception] [000009] [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:03.368602 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:08.373120 INFO [HTTP Retry] Attempt 3 of 3: [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:13.378178 INFO Protocol endpoint not found: MetadataProtocol, [000008] [000009] [HTTP Failed] HTTP GET IOError [Errno 101] Network is unreachable
2017/12/11 09:25:13.378318 INFO Retry detect protocols: retry=0
2017/12/11 09:25:23.387929 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/11 09:25:23.423962 INFO Test for route to 168.63.129.16
2017/12/11 09:25:23.475809 WARNING No route exists to 168.63.129.16
2017/12/11 09:25:23.515952 INFO Send dhcp request
2017/12/11 09:25:23.690153 INFO Examine /proc/net/route for primary interface
2017/12/11 09:25:23.735026 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/12/11 09:25:23.764947 WARNING Contents of /proc/net/route:
2017/12/11 09:25:23.779796 WARNING Primary interface examination will retry silently
2017/12/11 09:39:53.803278 INFO Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/12/11 09:39:53.803907 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running

So the vm was rebooted again and the vm was accessible again
latest logs after the reboot

2017/12/11 10:42:46.787304 INFO Agent WALinuxAgent-2.2.14 forwarding signal 15 to WALinuxAgent-2.2.18
2017/12/11 10:44:07.381244 INFO Azure Linux Agent Version:2.2.14
2017/12/11 10:44:07.384151 INFO OS: centos 6.9
2017/12/11 10:44:07.384262 INFO Python: 2.6.6
2017/12/11 10:44:07.384546 INFO Run daemon
2017/12/11 10:44:07.384884 INFO Activate resource disk
2017/12/11 10:44:07.413219 INFO Examining partition table
2017/12/11 10:44:07.514489 INFO GPT not detected, determining filesystem
2017/12/11 10:44:07.533596 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/11 10:44:07.562805 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/11 10:44:07.562971 INFO The partition type is 83
2017/12/11 10:44:07.563195 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/11 10:44:07.700764 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/11 10:44:07.725242 INFO Clean protocol
2017/12/11 10:44:07.760679 INFO Provisioning already completed, skipping.
2017/12/11 10:44:07.760807 INFO RDMA capabilities are not enabled, skipping
2017/12/11 10:44:07.837128 INFO Determined Agent WALinuxAgent-2.2.18 to be the latest agent
2017/12/11 10:44:08.071869 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
2017/12/11 10:44:08.076098 INFO Detect protocol endpoints
2017/12/11 10:44:08.076358 INFO Clean protocol
2017/12/11 10:44:08.076566 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/11 10:44:08.076735 INFO Test for route to 168.63.129.16
2017/12/11 10:44:08.077291 INFO Route to 168.63.129.16 exists
2017/12/11 10:44:08.077457 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:08.098126 INFO Fabric preferred wire protocol version:2015-04-05
2017/12/11 10:44:08.098921 INFO Wire protocol version:2012-11-30
2017/12/11 10:44:08.099081 WARNING Server preferred version:2015-04-05
2017/12/11 10:44:11.951230 INFO Start env monitor service.
2017/12/11 10:44:11.951395 INFO Configure routes
2017/12/11 10:44:11.951487 INFO Gateway:None
2017/12/11 10:44:11.951575 INFO Routes:None
2017/12/11 10:44:11.950206 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 10:44:12.053870 INFO WALinuxAgent-2.2.18 running as process 1728
2017/12/11 10:44:12.054794 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:12.055229 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:12.147714 INFO Wire server endpoint:168.63.129.16
2017/12/11 10:44:12.191772 INFO Set block dev timeout: sdb with timeout: 300
2017/12/11 10:44:12.195141 INFO Set block dev timeout: sda with timeout: 300
2017/12/11 10:44:12.310696 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=163
2017/12/11 10:59:08.602039 INFO Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/12/11 10:59:08.603978 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.18 launched with command 'python -u bin/WALinuxAgent-2.2.18-py2.7.egg -run-exthandlers' is successfully running
2017/12/11 11:14:14.445493 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 11:44:17.093560 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 12:14:18.680816 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 12:44:19.951018 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 13:14:22.384833 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 13:44:23.795860 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 14:14:25.239115 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/11 14:44:27.613904 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0

also the logs states that the vm is running with 2.2.14 , but its forwarding signal to 2.2.18
also the errors are gone after the reboot.

we have checked the yum log also we could see the that there was no package removed/installed

is this something to do with the wireserver. waagent was not able to reach the wireserver and it failed.
after the reboot it was able to reach the wireserver?

afaik, the wireserver and the waagent are responsible for providing the status of the vm to the fabric.
also the wireserver is responsible for mapping the ipaddress to the vm

can you explain why this happened and how we can avoid this is future?

**Comment by hglkrijger** [comment]
Looks like the routing table was not initialized correctly:
```
2017/12/11 09:25:23.735026 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/12/11 09:25:23.764947 WARNING Contents of /proc/net/route:
2017/12/11 09:25:23.779796 WARNING Primary interface examination will retry silently
```
This would indicate a dhcp problem; please follow up with networking.
