### ISSUE TITLE
TypeError: add_event() got an unexpected keyword argument 'msg'

### ISSUE THREAD

**Issue by FumiakiNagano** [Azure/WALinuxAgent#974]
The following logs are logged at /var/log/message.

Dec 15 09:40:49 totanicap python: 2017/12/15 09:40:49.019671 INFO Event: name=WALinuxAgent, op=HeartBeat, message=73;13;5BB2C42E-5309-42FD-8228-BA47D0034DFF;0, duration=0
Dec 15 09:40:49 totanicap python: Exception in thread Thread-1:
Dec 15 09:40:49 totanicap python: Traceback (most recent call last):
Dec 15 09:40:49 totanicap python: File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
Dec 15 09:40:49 totanicap python: self.run()
Dec 15 09:40:49 totanicap python: File "/usr/lib64/python2.7/threading.py", line 765, in run
Dec 15 09:40:49 totanicap python: self.__target(*self.__args, **self.__kwargs)
Dec 15 09:40:49 totanicap python: File "bin/WALinuxAgent-2.2.19-py2.7.egg/azurelinuxagent/ga/monitor.py", line 225, in daemon
Dec 15 09:40:49 totanicap python: msg=msg)
Dec 15 09:40:49 totanicap python: TypeError: add_event() got an unexpected keyword argument 'msg'

Source code can be found at  https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/ga/monitor.py .
it seems msg at line 225 need to be message.

OS: Red Hat 7.3
Version: WALinuxAgent-2.2.19

**Comment by boumenot** [comment]
Good catch!
