### ISSUE TITLE
Repeated firewall logs (CentOS 6.5 HPC image + WALA 2.2.19)

### ISSUE THREAD

**Issue by iamshital** [Azure/WALinuxAgent#977]
**Repro Steps:**
1. Deploy CentOS 6.5 HPC VM.
2. Upgrade WALA to latest using master branch.
3. Restart.

**Issue -**
1. waagent keeps dumping firewall related messages to  /var/log/waagent.log infinitely.
2. I've seen waagent.log file grow beyond 4GB.
3. If we allow this state, OS will run out of disk space.

**Comment by iamshital** [comment]
Is this related to #976 ?

**Comment by hglkrijger** [comment]
Thanks for reporting this. #976 is somewhat related, but this is a different issue. For the moment the best way to mitigate this is to disable the firewall via config, flush the iptables rules, and restart the agent. From `/etc/waagent.conf`:
```
OS.EnableFirewall=n
```
The flush the rules (note this will flush **ALL** rules):
```
iptables -t security --flush
```
Restart the agent:
```
systemctl restart waagent
```
We will correct this in 2.2.20.

**Comment by boumenot** [comment]
CentOS 6.5 ships with iptables 1.4.7. The agent checks if a rules exists using iptable's --check option.  The --check option was not introduced until iptables 1.4.11. I am going to add a check for this version of iptables, and abort processing unless 1.4.11 or greater is installed.

The iptables commit message that added the --check option says that people used to grep the output of `iptables -L`, which is error prone.  I agree.  We can revisit if we really need to support such an old version in the future, but for now I am going to disable firewall enablement.

**Comment by boumenot** [comment]
The plot thickens.  CentOS 6.9 ships with iptables 1.4.7, but it **does** support the -C option.  I assume they backport-ed the change.
