### ISSUE TITLE
Cannot ssh to linux vm possible because of agent route issue 

### ISSUE THREAD

**Issue by digeler** [Azure/WALinuxAgent#980]
Boot log show the following
Welcome to SUSE Linux Enterprise Server 12 SP1  (x86_64) - Kernel 4.15.0-rc4-1.gff8819c-default (ttyS0).

sapbwh login: 2017/12/24 18:05:11.429009 INFO Azure Linux Agent Version:2.2.18
2017/12/24 18:05:11.430532 INFO OS: suse 12
2017/12/24 18:05:11.430997 INFO Python: 2.7.9
2017/12/24 18:05:11.431523 INFO Run daemon
2017/12/24 18:05:11.432159 INFO Activate resource disk
2017/12/24 18:05:11.438987 INFO Examining partition table
2017/12/24 18:05:11.683568 INFO GPT not detected, determining filesystem
2017/12/24 18:05:11.738205 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/24 18:05:11.760457 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/24 18:05:11.761593 INFO The partition is formatted with ntfs, updating partition type to 83
2017/12/24 18:05:11.764265 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/24 18:05:11.789840 INFO sfdisk -c  /dev/sdb 1 83 succeeded
2017/12/24 18:05:11.794488 INFO Format partition [mkfs.ext4 -F /dev/sdb1]
2017/12/24 18:05:15.392538 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/24 18:05:15.457778 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/24 18:05:15.467804 INFO Clean protocol
2017/12/24 18:05:15.468914 INFO Running default provisioning handler
2017/12/24 18:05:15.472633 INFO Copying ovf-env.xml
2017/12/24 18:05:15.474446 INFO Detect protocol endpoints
2017/12/24 18:05:15.475467 INFO Clean protocol
2017/12/24 18:05:15.475979 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/24 18:05:15.476419 INFO Test for route to 168.63.129.16
2017/12/24 18:05:15.476929 WARNING No route exists to 168.63.129.16
2017/12/24 18:05:15.477791 INFO Checking for dhcp lease cache
2017/12/24 18:05:15.478247 INFO Cache exists [False]
2017/12/24 18:05:15.478704 INFO Send dhcp request
2017/12/24 18:05:15.658527 INFO Examine /proc/net/route for primary interface
2017/12/24 18:05:15.659872 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/12/24 18:05:15.660329 WARNING Contents of /proc/net/route:
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT      

i can see the console is with the login -but cant ssh.

how do i fix this behavior ,is there any kind of logging ?
thanks

**Comment by digeler** [comment]
upgraded the kernel because of this article https://support.microsoft.com/en-us/help/4041171/an-azure-virtual-machine-running-an-older-linux-kernel-fails-to-restart

now i have the following ::
I have upgraded to sp2 and kernel :
(x86_64)
VERSION = 12
PATCHLEVEL = 2
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
sapbwh:/home/sdelfa # uname -r
4.4.103-92.53-default

**Comment by hglkrijger** [comment]
The logs show the routing table is empty:
```
2017/12/24 18:05:15.659872 WARNING Could not determine primary interface, please ensure /proc/net/route is correct
2017/12/24 18:05:15.660329 WARNING Contents of /proc/net/route:
Iface	Destination	Gateway Flags	RefCnt	Use	Metric	Mask	MTU	Window	IRTT
```

Please follow up with Networking, this is not an agent issue.
