### ISSUE TITLE
`/var/lib/waagent/Certificates.pem` is not the CA root cert in Azure Stack

### ISSUE THREAD

**Issue by bingosummer** [Azure/WALinuxAgent#981]
According to https://docs.microsoft.com/en-za/azure/azure-stack/user/azure-stack-connect-cli#trust-the-azure-stack-ca-root-certificate, I want to use CustomScript extension to get the CA root cert from `/var/lib/waagent/Certificates.pem`.
In most cases, the content of `Certificates.pem` is the CA root cert. But sometimes, it's not. It seems to be an intermediate cert. After comparing with other certs in `/var/lib/waagent/`, I found that it's same with another pem file `9F470657A38F5B314E50B7A64E090402F21FB61D.crt`.
Could you please confirm whether the behavior is expected? If so, how to make sure that `certificates.pem` is ready and CustomScript can fetch the CA root cert?

**Comment by hglkrijger** [comment]
The agent simply extracts all certs from the payload it receives, and does not do any filtering or validation of the cert chain. The behavior is expected, and if the Azure Stack certificates are not passed along correctly, please open an issue with them.
