### ISSUE TITLE
GoalState.1.xml is to be deleted when deallocate/start VM which has 50+ GoalState.#.xml file

### ISSUE THREAD

**Issue by nmikuni** [Azure/WALinuxAgent#993]
`def purge_cache` deletes GoalState.1.xml when /var/lib/waagent has 50+ GoalState.#.xml file.
When VM is deallocated and started, GoalState.1.xml seems to be created by `def update_goal_state`.
However it seems to be suddenly deleted by `def purge_cache` when /var/lib/waagent has 50+ GoalState.#.xml file. (For example, if there is 50 files like GoalState.11.xml, GoalState.12.xml, ... GoalState.60.xml). The algorithm of sorting in `def purge_cache` might be the cause.

It might cause following message which is being discussed in #945 .
`Exception retrieving extension handlers: [ProtocolError] /var/lib/waagent/ GoalState.1.xml is missing.`

It could be mitigated by deleting GoalState.#.xml, ExtensionsConfig.#.xml, and files which has # in /var/lib/waagent, and restart WALinuxAgent.

**Comment by hglkrijger** [comment]
Thank you for reporting. We are currently working on hotfix release 2.2.20 for this issue. Please see details [here](https://github.com/Azure/WALinuxAgent/wiki/Known-Issues#2219---protocolerror-varlibwaagentgoalstate1xml-is-missing) for RCA and mitigation.
