### ISSUE TITLE
[ProtocolError] /var/lib/waagent/GoalState.1.xml is missing.

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#996]
WireServer may reset the incarnation to an arbitrary value.  The guest agent does not consider the incarnation value when determining the list of files to purge periodically. The purge process looks at the latest files as determined by an integer value.  If the incarnation is reset, the agent must use the incarnation when considering the values to purge, but it does not. This the bug that causes this behavior. 

The agent continually executes the following cycle. 

 1. Determine the latest incarnation from WireServer, and save it.
 1. Purge the last 50 old files based on the highest integer value associated with the file name. (For example, GoalState.11.xml, has integer value 11.)  If the value is reset to 1, and the latest integer value is 51, then 1 will be deleted by the purge process.  This is bad.
  1. Rinse and repeat.

This cycle will repeat over and over again every three seconds.

I do not have a VM to verify a mitigation, **but** I believe it is sufficient to delete all of the files that would be purged to stop this behavior. The files on disk are simply a cache, and good for debugging.  They are not need to make the agent work. The list of files to be deleted under `/var/lib/waagent` match the following globs.

 1. `*.[0-9]*.xml`
 1. `*.[0-9]*.agentsManifest`

```sh
rm -f *.[0-9]*.xml *.[0-9]*.agentsManifest
```

**Comment by hglkrijger** [comment]
We are working on hotfix 2.2.20 to address this issue. This information has also been copied to [the wiki](https://github.com/Azure/WALinuxAgent/wiki/Known-Issues#2219---protocolerror-varlibwaagentgoalstate1xml-is-missing).
