### ISSUE TITLE
Add configurable option to enable/disable console redirection

### ISSUE THREAD

**Issue by amitchat** [Azure/WALinuxAgent#997]
Serial Console users may want to disable the console redirection of log messages completely. My suggestion is to make this a configurable option through the agent conf file.

It looks like standard journald based logging use the "ForwardToConsole" key to decide if messages should be forwarded to /dev/console.

Can we add a similar key which is honored by the agent in its conf file?

**Comment by hglkrijger** [comment]
Feel free to submit a PR for this.
